### ISSUE TITLE
Broken Link 

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#1003]
https://krimdok.uni-tuebingen.de/Content/fid#content
Dort unter Sponsoring period 2017-2019 > link auf „notifications and dates“ geht nicht

**Comment by thefass** [comment]
Desgleichen:
https://krimdok.uni-tuebingen.de/Content/fid#content
Dort unter Historical development > link auf DFG guidelines geht nicht

**Comment by thefass** [comment]
Desgleichen:
https://krimdok.uni-tuebingen.de/Content/research_data_management#content
Link auf KVK

**Comment by jriedl** [comment]
"notifications und dates" im Englischen auf sobek und ub15 behoben.

**Comment by jriedl** [comment]
DFG-Link scheint nicht mehr zu existieren. Alternativlink?

**Comment by jriedl** [comment]
Wie ist die genaue Bezeichnung für den KVK-Link?

**Comment by k-decker** [comment]
Der KVK-Link ist bei den Katalogen zu finden:
https://krimdok.uni-tuebingen.de/Content/catalogs#content

Der funktionierenden Link wäre:
https://kvk.bibliothek.kit.edu/index.html

**Comment by k-decker** [comment]
Alternativlink zur DFG:
https://www.dfg.de/foerderung/programme/infrastruktur/lis/lis_foerderangebote/fachinfodienste_wissenschaft/index.html

**Comment by mtrojan-ub** [comment]
ist geändert und kann auf sobek getestet werden

**Comment by thefass** [comment]
@k-decker Bitte prüfen, ob das Issue geschlossen werden kann. Wenn ja, bitte machen. DAnke

**Comment by k-decker** [comment]
> "notifications und dates" im Englischen auf sobek und ub15 behoben.

Der Link geht auch in der englischen Version auf eine Seite mit deutschem Text. Gibt es da noch keine englische Variante dafür?

Und ich kann das Issue leider nicht schließen (wahrscheinlich, weil ich nicht dazu assigned wurde).

**Comment by ruschein** [comment]
@k-decker Die Person, die ein Issue angelegt hat kann es schließen.  Oder wir Entwickler aber das machenb wir selten.

**Comment by ruschein** [comment]
@k-decker Die News-Seite gibt es nur auf Deutsch.
@thefass Ich denke man kann dieses Issue jetzt schließen.
