### ISSUE TITLE
Falsche Link Adresse

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#1004]
https://krimdok.uni-tuebingen.de/Content/research_data_management#content
hier der Link auf IISL Library Catalogue führt fälschlicherweise auf die Sage-Seite

**Comment by KStelzel** [comment]
Tatsächlich ist dort der falsche Link hinterlegt; richtig wäre dieser: http://150.241.255.158/cgi-bin/abnopac/O7569/IDdb6bf137/NT2?ACC=120&FORM=1
Das ist in KrimDok auf der Seite der Kataloge (nicht bei FDM, aber sowohl auf der deutschen als auch auf der englischsprachigen Seite): https://krimdok.uni-tuebingen.de/Content/catalogs#content

**Comment by mtrojan-ub** [comment]
Wenn ich die o.g. URL öffne kommt eine Fehlermeldung

"La sesión ha expirado"

Stattdessen würde ich folgende URL verlinken:
http://150.241.255.158/abnopac/

**Comment by KStelzel** [comment]
Das ist natürlich ungünstig, wenn hier erscheint, dass die Sitzung abgelaufen ist... @Mario: Die Seite, die du vorgeschlagen hast, ist besser und funktioniert auch, aber bitte die englische Version verlinken: http://150.241.255.158/cgi-bin/abnopac/O7745/ID9acad535/NT1?ACC=111&LANG=en-US

**Comment by KStelzel** [comment]
Okay, ich fürchte wir müssen hier die spanischsprachige Variante drin lassen, da auch bei der englischsprachigen eine Time-out-Meldung kommt...Mir würde es jedoch besser gefallen, wenn wir stattdessen diese Seite verlinken würden: http://www.iisj.net/en/library/about-library

**Comment by mtrojan-ub** [comment]
kann auf sobek getestet werden

**Comment by KStelzel** [comment]
Funktioniert. Super, danke!
