### ISSUE TITLE
Zusatz zum Sachtitel in der Volltitelanzeige

### ISSUE THREAD

**Issue by jjspp01** [ubtue/tuefind#1016]
Der Zusatz zum Sachtitel wird in der Vollanzeige nicht nach Doppelpunkt angezeigt. 
Bitte ergänzen Sie in der Vollanzeige zwischen 245 $a und $b wie in der Kurzanzeige einen Doppelpunkt. 

Bsp.:  https://sobek.ub.uni-tuebingen.de/Record/166800965X#details

245 14$aThe penal voluntary sector$ba hybrid sociology$cPhilippa Tomczak, Gillian Buck

![245_b](https://user-images.githubusercontent.com/29603226/70426271-02dfbd00-1a73-11ea-9688-de929724be48.PNG)

**Comment by mtrojan-ub** [comment]
Das Problem wurde behoben.

Bei der Analyse des Problems ist mir noch aufgefallen, dass die Titel in IxTheo/RelBib und KrimDok auf unterschiedliche Art erzeugt werden.

Für TueFind allgemein (und somit auch KrimDok):
https://github.com/ubtue/tuefind/blob/f9383b700394593019e898a8323e7b78cccadee6/module/TueFind/src/TueFind/RecordDriver/SolrDefault.php#L323

Speziell für IxTheo/RelBib:
https://github.com/ubtue/tuefind/blob/f9383b700394593019e898a8323e7b78cccadee6/module/IxTheo/src/IxTheo/RecordDriver/SolrDefault.php#L28

Frage an @ruschein und @jriedl (für nach der Urlaubszeit): Lässt sich das vereinheitlichen? Die allgemeine Implementierung scheint besser zu sein als die für IxTheo/Relbib, können wir den Spezialfall für IxTheo/RelBib gefahrlos entfernen?

**Comment by mtrojan-ub** [comment]
Heute in der VC mit @ruschein und @jriedl besprochen: Der Spezialfall IxTheo/RelBib kann entfernt werden
