### ISSUE TITLE
BEACON: Unterscheidung IxTheo / RelBib

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#1018]
Die BEACON Dateien für IxTheo und RelBib haben zwar einen anderen Header, sind aber vom Inhalt her identisch:

https://ptah.ub.uni-tuebingen.de/docs/ixtheo-beacon.txt
https://ptah.ub.uni-tuebingen.de/relbib_docs/relbib-beacon.txt

Beim Erzeugen werden die Normdaten gegen die Titeldaten abgeglichen die bei uns tatsächlich vorhanden ist. Für RelBib sollten hier nur die tatsächlich in RelBib vorhandenen Titel berücksichtigt  werden.

**Comment by thefass** [comment]
ja, das sehe ich auch so

**Comment by mtrojan-ub** [comment]
Kann auf ptah getestet werden

**Comment by relhei** [comment]
Text ist veraltet - ich passe noch an und schicke die aktuelle Version.

**Comment by mtrojan-ub** [comment]
Der Text wurde aktualisiert, es kann voraussichtlich ab morgen auf ptah getestet werden.

**Comment by mtrojan-ub** [comment]
@thefass: Da wir die BEACON-Datei nur einsprachig generieren können wurden die Beschreibungen im Header nun auf Englisch umgestellt. Soll das bei IxTheo auch erfolgen? Falls ja bitte englischen Text zukommen lassen.

**Comment by relhei** [comment]
Für RelBib habe ich stichprobenartig geprüft, scheint zu passen. Danke!
