### ISSUE TITLE
BEACON: #TARGET korrigieren

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#1019]
Die BEACON-Datei enthält eine Liste mit GND-Nummern. Im Header-Abschnitt #TARGET ist ein Schema für Hyperlinks angegeben mit dem man zu Informationen zu dieser GND-Nummer springen können soll.

Aktuell:
#TARGET: https://ixtheo.de/Search/Results?lookfor={ID}

Dies ist aber falsch, da hiermit eine Titelsuche über "Alle Felder" mit der GND-Nummer ausgelöst wird. Die GND-Nummer ist aktuell aber nicht indexiert (Solr-Feld "author_id" = K10plus-PPN). Sobald das Normdaten-Thema live geht, könnte aber auch hier der Eintrag entsprechend angepasst werden.

**Comment by mtrojan-ub** [comment]
Aktuelles Test-Beispiel:
#TARGET: https://ptah.ub.uni-tuebingen.de/Authority/Search?lookfor=gnd:118562215

**Comment by IxTheoKm** [comment]
Ist es beabsichtigt, statt Internformat eine andere Ansicht für Benutzer zu präsentieren?

**Comment by thefass** [comment]
Ja, das ist beabsichtigt und wird gerade vorbereitet

**Comment by mtrojan-ub** [comment]
Auf ptah ist nun auch der direkte Aufruf eines Normdatensatzes über die GND-Nummer möglich (=Vorarbeit):
https://ptah.ub.uni-tuebingen.de/Authority/Record?gnd=118562215

**Comment by thefass** [comment]
super!

**Comment by mtrojan-ub** [comment]
Ich habe das TARGET im Template entsprechend geändert, es wird ab dem nächsten Pipeline-Durchlauf auf ptah angepasst sein.

Folgende Dinge sind für mich noch unklar:

1) Das TARGET ist im Standard anders definiert als auf der Wikipedia-Seite. (Die {ID} kommt im Standard nicht vor. Was gilt genau?
https://de.wikipedia.org/wiki/Wikipedia:BEACON
https://gbv.github.io/beaconspec/beacon.html

2) Ist irgendwo tatsächlich definiert was bei Abfrage der Links tatsächlich kommen muss, also => ist es aus Sicht des BEACON-Standards egal, ob eine Normdatenseite oder eine Liste mit Titeldaten das Ziel dieser URL ist?

**Comment by mtrojan-ub** [comment]
Nach interner Diskussion sind wir so verblieben:
1. Lassen wir so gemäß GBV Spezifikation
2. Wird so umgestellt dass auf die Liste mit Titeldaten verlinkt wird

**Comment by IxTheoKm** [comment]
"Liste mit Titeldaten" meint nur die Titel, von denen die Person _Autor oder sonstige beteiligte Person_ ist?
Sieht für mich derzeit so aus:
https://ptah.ub.uni-tuebingen.de/Authority/Record?gnd=118567705
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=author_id:061939080

Ist es geplant, auch die Titel _über_ die Person und über deren Werke dort zu verlinken (Feld 689), oder bleibt es bewusst bei der bisherigen Einschränkung?

Bsp.:
https://ptah.ub.uni-tuebingen.de/Record/1670054403#details
https://ptah.ub.uni-tuebingen.de/Record/1642759139#details

**Comment by thefass** [comment]
Ist momentan so, soll aber erweitert werden. Die Personenseite wird noch entwickelt und da gehört die Literatur über eine Person auch dazu. Und viele andere Ideen sind auch schon gesammelt ..

**Comment by mtrojan-ub** [comment]
Im Rahmen der personalisierten Seiten gab es ja nun einige Fortschritte, und es wurden mehrere Stufen für die Differenzierung eingeführt. Welche davon sollen denn für die BEACON-Datei gelten?

Newest Titles (By) => Haupt- oder Nebenautor
Newest Titles (About) => Normiertes Schlagwort

**Comment by mtrojan-ub** [comment]
Ab morgen wird eine neues TARGET-Schema auf ptah verwendet:
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=117104604&Type=GND

Die Suche an sich funktioniert zwar, aber die Anzahl der Suchergebnisse stimmt noch nicht in allen Fällen mit der Anzahl der Titel laut BEACON-Datei überein.

**Comment by thefass** [comment]
Sollten wir die GND Beacon Suche nicht gleich in die Authority Seiten laufen lassen?
https://ptah.ub.uni-tuebingen.de/Authority/14700599X
Begründung: dort sind nicht nur die Titel, sondern auch die infos und die graphischen Elemente wie Wordcloud und timeline.
@socheres wie siehst Du das?

**Comment by relhei** [comment]
In Sitzung heute besprochen: Via BEACON weiterhin mit Titeldaten verknüpfen.

**Comment by mtrojan-ub** [comment]
Dann ist ja jetzt bereits alles so, wie es sein soll. Da ich den Issue geöffnet habe, schließe ich ihn hiermit wieder.
