### ISSUE TITLE
Liste der IxTheo-Klassifikation

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#1024]
https://ixtheo.de/IxTheoClassification

Die Liste ist veraltet. Bitte "BA Nichtchristliche Religion" streichen. Diese Notation existiert nicht mehr. Sie ist auch im Auswahlfeld der erweiterten Suche nicht mehr aufgeführt.

**Comment by jriedl** [comment]
Behoben.

**Comment by IxTheoKm** [comment]
Vielen Dank!
