### ISSUE TITLE
Veraltete PDA-Nutzerinformation

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#1025]
https://ixtheo.de/docs/ixtheo-pda.pdf

Anmerkung 1 zum Direktlieferservice sollte vorerst entfallen, da stark veraltet.

**Comment by mtrojan-ub** [comment]
@jriedl : Hast Du evtl die Originaldatei (als nicht-PDF) noch und kannst die Änderung relativ einfach vornehmen?

**Comment by jriedl** [comment]
Meines Wissens wurde das damals von @thefass als PDF zur Verfügung gestellt.

**Comment by thefass** [comment]
Ich schicke per mail eine korrigierte pdf

**Comment by jriedl** [comment]
Auf ptah und ub16.
