### ISSUE TITLE
Verfasser in der Kurzanzeige

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#1027]
![RelBib_OA](https://user-images.githubusercontent.com/17004223/70919012-57a9a780-2020-11ea-9974-51bac4280f8f.JPG)

siehe
https://134.2.67.9/Search/Results?lookfor=id%3A1535185988&type=AllFields&limit=20&botprotect=

Im IxTheo ist die Anzeige in Ordnung:

![IxTheo_OA](https://user-images.githubusercontent.com/17004223/70919121-8d4e9080-2020-11ea-84ff-8bc5a4bd239a.JPG)

siehe 
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=id%3A1535185988&type=AllFields&botprotect=

**Comment by jriedl** [comment]
Behoben.

**Comment by IxTheoKm** [comment]
Danke!
