### ISSUE TITLE
Personennamen in Nachlassdatensätzen unvollständig

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#1029]
Vgl. #911 

Personennamen werden unvollständig angezeigt, daher ist bei gleichnamigen Personen nicht erkennbar, um welche es sich handelt:
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=nachlass+k%C3%B6nig+ludwig+frankreich&type=AllFields&limit=20&botprotect=

![Ludwig_Liste](https://user-images.githubusercontent.com/17004223/70923760-b2470180-2028-11ea-9076-81f169555865.JPG)

**Feld 100 muss mit $b und $d aus dem GND-Satz angezeigt werden.**

Bsp.:
https://ptah.ub.uni-tuebingen.de/Record/LR11872942X#details

GND-Satz: 
100 0 $aLudwig$bXIII.$cFrankreich, König$d1601-1643

Anzeigeform:
Ludwig XIII. (Frankreich, König) 1601-1643

![Ludwig](https://user-images.githubusercontent.com/17004223/70922877-22ed1e80-2027-11ea-8c84-d4aede222cc9.JPG)

**Comment by ruschein** [comment]
Auf Ptah!

**Comment by IxTheoKm** [comment]
Die Titelanzeige ist jetzt perfekt. Vielen Dank!
Die Verfasserangabe ist allerdings noch unvollständig. Bitte auch hier anpassen:

https://ptah.ub.uni-tuebingen.de/Author/Home?author=Ludwig+XVI.+%28Frankreich%2C+K%C3%B6nig%29

![Nachlass](https://user-images.githubusercontent.com/17004223/71245106-4e685580-2314-11ea-8a9d-3268d31d2805.JPG)

Bei anderen Datensätzen, die keine Nachlässe sind, ist es schon korrekt:
https://ptah.ub.uni-tuebingen.de/Record/110165810X

![Nachlass2](https://user-images.githubusercontent.com/17004223/71245251-9ab39580-2314-11ea-8be1-36ad6106ec6e.JPG)

![Nachlass3](https://user-images.githubusercontent.com/17004223/71245255-9dae8600-2314-11ea-85a6-559bddeb296d.JPG)

**Comment by ruschein** [comment]
Auf Ptah.

**Comment by IxTheoKm** [comment]
Jetzt in Ordnung
