### ISSUE TITLE
Schlagwortsuche führt zu nicht erwünschten Ergebnissen

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#1033]
Ein Nutzer hat uns per Feedback-Formular mitgeteilt, dass bei der Suche nach dem Schlagwort "Wesen" u. a. als Treffer (1. Seite, Sortierung nach Relevanz) Titel, die den Fluss "Weser" enthalten, entsprechend angezeigt und gehighlighted werden.
https://www.relbib.de/Search/Results?join=AND&lookfor0%5B%5D=wesen&type0%5B%5D=Subject&bool0%5B%5D=AND&limit=20&daterange%5B%5D=publishDate&publishDatefrom=&publishDateto=&botprotect
Lässt sich der Suchalgorithmus hier noch schärfen?

**Comment by jriedl** [comment]
Für konkrete bekannte Fälle (hier "Wesen") ja, indem man diese Begriffe vom Stemming ausschließt. Das ist jetzt auch ptah umgesetzt. Eine für den allgemeinen Fall befriedigende Lösung wird sich allerdings wahrscheinlich nicht finden lassen.

**Comment by relhei** [comment]
Sieht jetzt gut aus. Vielen Dank!
