### ISSUE TITLE
IxTheo-Klassifikationen fehlen

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#1042]
Zwei Titel wurden testweise mit Notationen versehen, um unterschiedliche PICA-Felder zu testen.
Sie enthalten beide die Notationen in den korrekten lokalen Feldern, sind aber darunter nicht recherchierbar. In der Facette "IxTheo-Klassifikation" steht "unzugewiesen":

https://ixtheo.de/Search/Results?lookfor=id%3A1685921035&type=AllFields&botprotect
https://ixtheo.de/Search/Results?lookfor=id%3A1685921027&type=AllFields&limit=20&botprotect=

![Notation](https://user-images.githubusercontent.com/17004223/71243664-1b709280-2311-11ea-9111-507c484b7a21.JPG)

![Notation2](https://user-images.githubusercontent.com/17004223/71243676-1f041980-2311-11ea-9cd0-87effb2d64dc.JPG)

**Comment by mtrojan-ub** [comment]
Im Lokalsatz prüfen wir auf 852a = "Tü 135" oder "Tü 135/1". Im genannten Datensatz ist eine andere Schreibweise gewählt: "DE-Tue135", diese muss in die Prüfung mit aufgenommen werden.

Wurde diese Kennzeichnung geändert? Gibt es noch weitere Kennzeichnungen die hier aufgenommen werden sollen?

https://ixtheo.de/Record/1685921035#details

**Comment by IxTheoKm** [comment]
Ich habe im BSZ angefragt, ob statt des Sigels Tü 135 jetzt die ISIL DE-Tue135 ausgeliefert wird.
Sieht ganz so aus.
Weiteres Bsp. aus Innsbruck: https://ixtheo.de/Record/1685087795#details

Betroffen sind alle derzeitigen und zuküftigen Kooperationspartner mit Tü 135/...:
Tü 135 --> DE-Tue135
Tü 135/1 --> DE-Tue135-1
Tü 135/2 --> DE-Tue135-2
Tü 135/3 --> DE-Tue135-3
Tü 135/4 --> DE-Tue135-4

**Comment by mtrojan-ub** [comment]
Die Änderung ist auf ptah aktiv und kann ab dem nächsten Pipeline-Durchlauf dort getestet werden (also voraussichtlich ab morgen).

**Comment by obrandt** [comment]
Hallo in die Runde,

anscheinend gab es in der VZG eine Anpassung aller Umlaute in den Sigeln. Das ist natürlich mehr als suboptimal, insbesondere ohne Information für nachgelagerte Nutzer, aber auch nicht mehr änderbar.

Viele Grüße

Olaf Brandt

Von: IxTheoKm <notifications@github.com>
Gesendet: Freitag, 20. Dezember 2019 10:53
An: ubtue/tuefind <tuefind@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [ubtue/tuefind] IxTheo-Klassifikationen fehlen (#1042)


Ich habe im BSZ angefragt, ob statt des Sigels Tü 135 jetzt die ISIL DE-Tue135 ausgeliefert wird.
Sieht ganz so aus.
Weiteres Bsp. aus Innsbruck: https://ixtheo.de/Record/1685087795#details

Betroffen sind alle derzeitigen und zuküftigen Kooperationspartner mit Tü 135/...:
Tü 135 --> DE-Tue135
Tü 135/1 --> DE-Tue135-1
Tü 135/2 --> DE-Tue135-2
Tü 135/3 --> DE-Tue135-3
Tü 135/4 --> DE-Tue135-4

**Comment by IxTheoKm** [comment]
[Ein grundsätzlicher Hinweis: bitte die Antwort nicht aus dem Mailprogramm schicken! Da wird alles nochmals mitgeschickt!]

Es wurden nicht nur die Umlaute aufgelöst, sondern statt des Sigels (ohne "DE-"), nun die ISIL ausgeliefert. Das Sigel hat weiterhin Umlaute.

**Comment by IxTheoKm** [comment]
Notationen werden nun angezeigt. Danke!
