### ISSUE TITLE
Mehrsprachigkeit durch Browsereinstellungen

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#1055]
Bitte noch die Fehlermeldung ins Englische, Italienische, Französische übersetzen (lassen). Oder einfach nur aktivieren, wenn das in VuFind schon integriert ist?

![Bildschirmfoto 2020-01-08 um 16 06 58](https://user-images.githubusercontent.com/14169098/71989058-3c9e1200-3231-11ea-84d3-c0c31bc34ec3.png)

_Originally posted by @thefass in https://github.com/ubtue/tuefind/issues/875#issuecomment-572112467_

**Comment by thefass** [comment]
Antwort von @mtrojan-ub 

Die Meldung "Bitte füllen Sie dieses Feld aus." wird vom Browser gesetzt. Es ist ein Standardfeature in HTML5. Die Sprache der Meldung ändert sich also nur, wenn man in seinem Browser die Sprache anpasst. Das bezieht sich also nicht nur auf das Feedback-Formular.

siehe auch:
https://www.w3schools.com/tags/att_input_required.asp

Beispiel Firefox (in "about:preferences"):
![grafik](https://user-images.githubusercontent.com/14169098/71997669-90632800-323e-11ea-8f53-74ed5703e250.png)

**Comment by thefass** [comment]
Das bedeutet aber, dass bei Umschaltung in eine andere Sprache in VuFind, diese Meldungen nicht in die andere Sprache umgesetzt werden. Finde ich unglücklich.
Sollten wir diskutieren

**Comment by ruschein** [comment]
Ich finde die Formulierung "wenn man in seinem Browser die Sprache anpasst" etwas unglücklich.  Man kann das zwar machen aber es macht normalerweise niemand.  Die Standardspracheinstellung des Browsers ist die, die vom Betriebssystem kommt.  D.h., wenn jemand bei sich im Betriebssystem z.B. Italienisch benutzt, ist die voreingestellte Browsersprache Italenisch etc.  Dies ist auch in vielen anderen Fällen so.  Ich denke es wäre sinnlos zu versuchen da manuell einzugreifen.  Schließlich ist das das Standardverhalten auf allen Webseiten.

**Comment by mtrojan-ub** [comment]
Wie in der FID-Runde besprochen => wird geschlossen, lassen wir so
