### ISSUE TITLE
Nachlass-Facette für RelBib

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#1062]
IxTheo hat sie bereits. Bitte für RelBib (evt. auch KrimDok?) "Nachlass" in die Facette "Medienart" mit aufnehmen und über die BEACON-Datei entsprechend mit Kalliope und Archivportal-D verlinkte Titelsätze erzeugen. Vielen Dank!
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=&type=Author&filter%5B%5D=%7Eformat%3A%22Literary+Remains%22&limit=20&botprotect=

**Comment by ruschein** [comment]
Auf Ptah.

**Comment by relhei** [comment]
Passt. Vielen Dank!
