### ISSUE TITLE
Nachlass-Facette: Suchoptimierung?

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#1063]
Bei der Suche nach einem Autor (Suchfeld: Verfasser) wird (wenn vorhanden) "Nachlass" im Filter "Medienart" angezeigt, wenn nur nach dem Namen gesucht wird, Bsp.:
![grafik](https://user-images.githubusercontent.com/25769591/72518525-d9763600-3855-11ea-8be2-3b3931904256.png)
Wenn man nach einem spezifischen Autor (durch die Lebensdaten erweiterter Name) sucht, wird "Nachlass" hingegen nicht gefunden:
![grafik](https://user-images.githubusercontent.com/25769591/72518742-3a9e0980-3856-11ea-8de9-98c4e4438a20.png)

**Comment by jriedl** [comment]
@ruschein : Im Prinzip sollte es ausreichen, in den Nachlassrecords in 100$d die Lebensdaten zu hinterlegen.

**Comment by ruschein** [comment]
Auf Ptah.

**Comment by relhei** [comment]
Passt. Vielen Dank!
