### ISSUE TITLE
Tracking für Weiterleitung auf Weblogs

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#1073]
Können aktuell die Nutzerzahlen des Newsaggregators auf RelBib festgestellt werden? Falls nicht, benötigen wir eine "unauffällige" Weiterleitungsseite, um die Nutzung zu erfassen.

**Comment by mtrojan-ub** [comment]
Sieht so aus als ob das mit Matomo nicht möglich ist. Für die Weiterleitungsseite hätte ich noch folgende Rückfragen:

- Was genau soll getrackt werden?
  - Also z.B. nur wieviele Weiterleitungen wurden aufgerufen?
  - Oder welche Weiterleitung wurde wie oft aufgerufen?
  - Oder welche Weiterleitung wurde in welchem Zeitraum wie oft aufgerufen? (Wie groß ist der Zeitraum?)
- Wie genau wollt Ihr es auswerten?
  - Fragt Ihr dann bei Bedarf nach und wir schicken es Euch zu?
  - Oder benötigt Ihr einen View o.Ä.? (Müsste dann ja Passwortgeschützt sein)

**Comment by relhei** [comment]
Zur 1. Frage: Am besten wäre "Welche Weiterleitung (also bezogen auf einzelne Blogs) wurde wie oft in einem bestimmten Zeitraum aufgerufen?" Ich denke, dass der Zeitraum auf 1 Monat festgelegt werden sollte. Gibt es Gegenstimmen?
Zur 2. Frage: Bei Matomo erhalten wir monatlich automatisch eine E-Mail mit der Statistik, wäre so eine Automatisierung auch von eurer Seite möglich? Dann benötigen wir kein PW.

**Comment by relhei** [comment]
Wie ist hier der Stand?

**Comment by mtrojan-ub** [comment]
Der Stand ist, dass es mir aufgrund mehrerer Projekte außerhalb von TueFind mit höherer Prio bislang nicht möglich war diesen Issue weiter zu bearbeiten (das wird wohl leider auch noch einige Zeit so bleiben).

Aber zur Definition:
Zu Frage 1) gab es ja bisher keine Gegenstimmen, also ist 1 Monat vermutlich OK
Zu Frage 2) @ruschein, was meinst Du denn dazu?

**Comment by ruschein** [comment]
Ich sehe keinen Grund warum wir nicht eine Statistik für ein Zeitfenster von einem Monat für Weiterleitungen erzeugen könnten.  Allerdings ist meine Frage, ist das im Ramen unseres jetzigen Antrags und selbst falls die Antwort positiv ausfällt haben wir gerade auf mindestens ein paar Wochen hinaus wichtigere Aufgaben.

**Comment by thefass** [comment]
Statistik ist immer im Rahmen unserer Anträge abgedeckt, da wir ja immer über unsere Services Rechenschaft ablegen müssen. Das wir zunehmend noch antragsrelevanter sein. Das trifft darüber hinaus besonder auf die neuen, innovativen features zu, bei denen man in den Berichten dann auch noch zeigen muss, dass die Förderung wichtig und richtig war. 
Zeitlich hat das - denke ich - noch etwas Luft, da wir ja in RW erst wieder im April 2021 berichten müssen. Ein halbes Jahr statistischer Nachweis sollte aber schon zusammenkommen.

**Comment by relhei** [comment]
1) Schön, dass beides umsetzbar ist.
2) Zur Frage, ob das im jetzigen Antrag enthalten ist: Blogaggregator auf jeden Fall, meiner Meinung nach gehört auch die Weiterleitung dazu - das Angebot sollte ja hinsichtlich der Nutzung prüfbar sein. Weiß aber nicht, ob noch IT-Stunden dafür übrig.
3) Hinsichtlich Zeitrahmen: Wenn das nicht sehr zeitaufwendig ist, wäre es schön, wenn es nicht erst im März 2021 umgesetzt wäre, da wir dann ein paar Zahlen für den Folgeantrag brauchen.

**Comment by thefass** [comment]
Zum Procedere:
Wenn man einen Verlauf der Nutzung zeigen will und nicht nur einen punktuellen Stand, sollten die Daten nicht per Mail übermittelt werden, sondern als csv oder gleich als excel.  Oder als View in einer neuen Zederinstanz (da kann man entsprechend exportieren).
Wir sollten die Anforderungen und den Zeitpunkt der Umsetzung in der nächsten IT Besprechung aufgreifen

**Comment by mtrojan-ub** [comment]
Laut FID-Meeting heute sollen die Zugriffe auf jeden Fall einzeln mit timestamp gespeichert werden, damit man im Nachgang Auswertungen pro Monat oder pro Jahr machen kann (z.B. in Office nach CSV-Export).

**Comment by mtrojan-ub** [comment]
Die Änderung ist jetzt auf ptah aktiv. Alle Hyperlinks auf externe Seiten in der RSS-Kurzansicht sowie in der Vollansicht zeigen nun auf die neue Weiterleitungsseite. Die Weiterleitung wird mit Timestamp in eine Tabelle eingetragen. Der Benutzer wird nach 3 Sekunden weitergeleitet.

Weiterleitungen aus der Kurzansicht werden mit Gruppenbezeichnung "relbib-rss-short" und aus der Vollansicht mit "relbib-rss-full" gespeichert, so dass man sie bei Bedarf später auseinander halten kann.

Zugriff auf den Inhalt der Tabelle für Auswertungszwecke ist nicht per Oberfläche möglich, hier müsste einer von uns Admins die Tabelle bei Bedarf in eine CSV exportieren. Wenn Ihr ein wenig getestet habt kann ich gerne eine CSV vom Testserver als Beispiel exportieren.

**Comment by thefass** [comment]
Funktioniert gut. Könnte man die Zeit von 3 Sekunden verkürzen?

**Comment by thefass** [comment]
Könntest du die Daten mit einem cronjob in eine csv schreiben, so dass das nicht manuell angstoßen werden muss?

**Comment by mtrojan-ub** [comment]
Verkürzung ist Einstellungssache, auf wieviel Sekunden soll verkürzt werden?

Grundsätzlich könnte man die CSV auch per Cronjob erstellen + verschicken. Wie oft soll das passieren + an welche Adresse?

**Comment by thefass** [comment]
Kommt darauf an, was damit erreicht werden soll. Soll der Nutzer erkennen können, dass eine Weiterleitung stattfindet, dann muss er das ja lesen können, also 1-2 Sekunden
Aber wenn das nicht notwendig wäre, dann könnte doch auch direkt weitergeleitet werden.

**Comment by thefass** [comment]
Cronjob: täglich, irgendwann in der Nacht, dann ist die Gefahr nicht groß, dass jemand die Datei geöffnet hat.
Ort: auf einem Server, den wir intern erreichen können. Müssen wir überlegen.

**Comment by Gazeller** [comment]
Meiner Meinung nach muss der Nutzer nicht merken, dass er weiter geleitet wird, es sei denn, dies ist notwendig in Bezug auf Datenschutz. Ansonsten ich wäre auch für Verkürzung / direktes Weiterleiten.

**Comment by thefass** [comment]
Kannst Du darauf zugreifen? Wenn ja, wäre das der Ort!

ze020110 > Fachinformationsdienste > Statistik

**Comment by mtrojan-ub** [comment]
Der Delay wurde auf 0 gesetzt, die Seite muss aber aus technischen Gründen dennoch aufgerufen werden und wird für einen kurzen Augenblick angezeigt, bevor die Weiterleitung erfolgt.

Auf ZE020110 haben wir bisher nur Zugriff auf das Unterverzeichnis FID-Projekte (wegen Default und Default_Test für zotaut). Wäre es möglich, dass wir die Daten dort irgendwo ablegen?

**Comment by thefass** [comment]
Ok, ich verschiebe das

**Comment by thefass** [comment]
ze020110 > FID-Projekte > Statistik

**Comment by mtrojan-ub** [comment]
Auf ptah ist jetzt auch der cronjob für den Export aktiv. Gestern wurde erstmals dort die Datei "redirects_ptah.csv" abgelegt.

![grafik](https://user-images.githubusercontent.com/26873381/89618806-1dca3180-d88d-11ea-833d-aa5c980fbd62.png)

Für ub16 wird dann später dementsprechend eine Datei "redirects_ub16.csv" erzeugt. Allerdings ist momentan noch unklar wann wir das nächste Mal Änderungen auf ub16 einspielen und das Feature aktiviert wird. Ich setze es trotzdem wieder auf "ready for testing".

Vom 10.-21.08. bin ich übrigens im Urlaub.

**Comment by mtrojan-ub** [comment]
In der Zwischenzeit wurden die Live-Server aktualisiert. Ich habe die redirects_ub16.csv jetzt einmalig von Hand exportiert, ab morgen erfolgt das automatisch per cronjob.

Gibt es noch Anmerkungen zum Inhalt der CSV-Datei?

**Comment by mtrojan-ub** [comment]
Passt laut Aussage von @relhei im heutigen FID-Meeting.
