### ISSUE TITLE
Anzeige mehrerer DOIs

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#1074]
Beispiel:
https://ixtheo.de/Record/1523156384
https://ptah.ub.uni-tuebingen.de/Record/1523156384

Der Datensatz enthält 2 DOIs und 1 Handle. 

PICA:
2051 10.15496/publikation-36718
2051 10.1515/nzsth-2012-0009
2052 10900/95335
4950 http://dx.doi.org/10.15496/publikation-36718$xR$3Volltext$4LF$534
4950 http://hdl.handle.net/10900/95335$xR$3Volltext$4LF$534
4950 http://dx.doi.org/10.1515/nzsth-2012-0009$xR$xH$3Volltext$4ZZ$534

MARC:
024 7 $a10.15496/publikation-36718$2doi
024 7 $a10.1515/nzsth-2012-0009$2doi
024 7 $a10900/95335$2hdl
856 40$uhttp://dx.doi.org/10.15496/publikation-36718$xResolving-System$zKostenfrei$3Volltext
856 40$uhttp://hdl.handle.net/10900/95335$xResolving-System$zKostenfrei$3Volltext
856 40$uhttp://dx.doi.org/10.1515/nzsth-2012-0009$xResolving-System$xVerlag$zLizenzpflichtig$3Volltext

Unter dem Reiter "Beschreibung" ist unter "DOI" nur einer aufgeführt, unter "Persistent identifiers"nur die DOIs, kein Handle:

![DOI](https://user-images.githubusercontent.com/17004223/72888372-b93eef00-3d0d-11ea-9724-9b6866429318.JPG)

PTAH:
![DOI_PTAH](https://user-images.githubusercontent.com/17004223/72888420-cfe54600-3d0d-11ea-8298-4c73732d8090.JPG)

Ist das so beabsichtigt? 
Welches Feld fließt unter "Beschreibung" in "DOI" ein, welches in "Persistent identifiers"?

**Comment by mtrojan-ub** [comment]
In "DOI" wird momentan nur eine der DOIs angezeigt, aber nicht alle.
Persistent Identifiers enthält:
- DOIs aus 024
- URNs aus 856
- Handles aus 856

Folgende Fragen stellen sich mir zu dieser Thematik:
- Wenn es ein Feld "Persistent Identifiers" gibt, brauchen wir dann separate Felder für z.B. DOI überhaupt?
- Soll man nach Persistent Identifiers auch direkt suchen können (wenn ja wie) oder sollen diese nur angezeigt werden?
- Gibt es noch weitere Persistent Identifiers die noch nicht berücksichtigt werden? (Ist eine ISBN/ISSN nicht auch ein Persistent Identifier)
- Sollte überall auch gleich ein Link auf einen Resolver o.Ä. hinterlegt sein?

Ich werde das Issue auch mal im heutigen FID-Meeting ansprechen

**Comment by mtrojan-ub** [comment]
Im FID Meeting besprochen:

- Separate Zeile für DOIs soll entfernt werden. Persistent Identifiers Zeile bleibt erhalten
- Einträge darin werden entsprechend gekennzeichnet ob es sich um eine DOI, Handle, URN etc. handelt (bereits der Fall?)
- Falls möglich immer Hyperlinks
- Suchbar sind diese bereits (Suche nach "Alle Felder"), dies ist so ausreichend

**Comment by ruschein** [comment]
Auf Ptah.  Wie besprochen im FID-Meeting sind die DOIs jetzt nicht mehr separat aufgeführt.  Deswegen sind die Einträge unter "Persistente Identifikatoren" Links.

**Comment by IxTheoKm** [comment]
PPN 1523156384 jetzt in Ordnung
