### ISSUE TITLE
Auswahl des Suchaspektes funktioniert nicht richtig

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#1076]
Wenn man den Suchaspekt ändert, wird die Änderung nicht angezeigt
z.B. von Alle Felder zu Verfasser.
![Bildschirmfoto 2020-01-23 um 23 15 23](https://user-images.githubusercontent.com/14169098/73028686-55fcac00-3e36-11ea-8085-b5a46813a9af.png)

Ebenso ist der Suchen Button manchmal nur halb blau
![Bildschirmfoto 2020-01-23 um 23 09 46](https://user-images.githubusercontent.com/14169098/73028485-eab2da00-3e35-11ea-80d7-262098d05eb3.png)

erst wenn man die Suche auslöst, wird der ausgewählte Suchaspekt angezeigt und auch bei der Suche verwendet
![Bildschirmfoto 2020-01-23 um 23 15 40](https://user-images.githubusercontent.com/14169098/73028749-74fb3e00-3e36-11ea-83da-62999034021b.png)

**Comment by thefass** [comment]
scheint nur der Ixtheo betroffen zu sein

**Comment by mtrojan-ub** [comment]
Ich kann es nicht reproduzieren... tritt es noch auf? Welcher Browser + welche Version wird genau verwendet?

**Comment by mtrojan-ub** [comment]
Da es seit fast 2 Monaten keine Reaktion auf meine letzte Frage gab habe ich das "High Priority" Label entfernt. Ist da noch etwas offen oder kann der Issue geschlossen werden?
