### ISSUE TITLE
Fehlende IxTheo Notation

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#1078]
Die Titelsuche https://ixtheo.de/Search/Results?lookfor=+++++++Zur+strittigen+Frage+arianischer+Glaubenserkl%C3%A4rung+auf+dem+Konzil+von+Nicaea+%28325%29+&type=AllFields 
ergibt 3 Treffer
Der erste mit der PPN 158882313X hat auch IxTheo-Notationen:

![Bildschirmfoto 2020-01-25 um 14 37 28](https://user-images.githubusercontent.com/14169098/73122081-d6c7bf00-3f80-11ea-8bdf-c52bb33a6e9b.png)

(Anmerkung: die zwei ersten werden am Montag gelöscht, da sie nur zu Testzwecken eingegeben wurden)
Komisch ist, dass die Notationen in der Facette IxTheo-Klassifikation nicht angzeigt wird. Dort sind 100% unzugewiesen.
![Bildschirmfoto 2020-01-25 um 14 35 28](https://user-images.githubusercontent.com/14169098/73122073-c1529500-3f80-11ea-87c7-a68103af5aeb.png)

**Comment by IxTheoKm** [comment]
Evtl. wieder dasselbe Problem wie https://github.com/ubtue/tuefind/issues/1042 ?

**Comment by ruschein** [comment]
Scheint jetzt auf Path zu tun.

**Comment by thefass** [comment]
ok
