### ISSUE TITLE
Fehler bei Klick auf Zeitschriftengesamtaufnahme

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#108]
Dieser Fehler tritt sowohl im IxTheo als auch auf Ptah auf:
Wenn man in den folgenden Datensätzen
https://ptah.ub.uni-tuebingen.de/Record/491950365
und 
https://www.ixtheo.de/Record/491950365#details
auf die Zss "Vigiliae Christianae" tritt ein Fehler auf:

![bildschirmfoto 2017-12-18 um 23 02 08](https://user-images.githubusercontent.com/14169098/34130483-3fe7f02c-e448-11e7-9242-89fc2e02b55e.png)

**Comment by IxTheoKm** [comment]
Vigilia Christianae ist wieder eine Zeitschrift, die massenhaft Lokaldaten hat. Vermutlich wurde sie deshalb (noch) nicht geliefert. Allerdings haben wir schon am 25-07-17 unsere Lokaldaten an die Zeitschriftengesamtaufnahme angehängt, und die Aufsätze von Brill wurden am 08-08-17 verknüpft. Sollte da nicht längst eine Lieferung der Titel ohne Lokaldaten erfolgt sein?

**Comment by thefass** [comment]
scheint durch das neue Lieferverfahren behoben zu sein. Auf ptah ok
