### ISSUE TITLE
HBZ Gateway-Anzeige verwirrend

### ISSUE THREAD

**Issue by ghost** [ubtue/tuefind#1092]
Bei Klick auf "Verfügbarkeit prüfen / HBZ GAteway" kommen manchmal verwirrende Meldungen. Beispiel: ppn 1688880992 'Orte und Räume reformatorischer Kunstdiskurse...'
kommt zunächst dies: 
![grafik](https://user-images.githubusercontent.com/16898788/73843809-a5bc7980-481f-11ea-9990-fb90fcbb802c.png)
Danach erscheint folgendes:
![grafik](https://user-images.githubusercontent.com/16898788/73844087-254a4880-4820-11ea-9e96-e34c911e1179.png)
Diese Hinweise sind verwirrend und teilweise falsch (in besagtem Beispiel gibt es nämlich eine ISBN!) 
und man verliert leicht aus den Augen, dass unten drunter dann die eigentliche lokale Verfügbarkeit abgerufen werden kann.
Kann man da irgendwas machen?

**Comment by jriedl** [comment]
Als Voraberläuterung: Im konkreten Fall enthält der Datensatz zwei 020-Felder mit ISBN. Da in der Vergangenheit bei der Suche nach nur einer ISBN nicht alle Bestände gefunden wurden und die Schnittstelle des HBZ-Gateways eine Suche auf mehrere ISBNs nicht unterstützt wird in diesem Fall eine Suche nach dem Titel durchgeführt, was zu dem beschriebenen Verhalten führt.

**Comment by thefass** [comment]
ok, Danke, dann schließe ich
