### ISSUE TITLE
RelBib Newsfeed als RSS abonnierbar machen

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#1105]
Heute im FID-Meeting besprochen:
https://relbib.de/RssFeed/Full

Hier soll direkt ein Link auf den RSS-Feed zur Verfügung gestellt werden, damit er von Benutzern direkt mit einem RSS-Reader abonniert werden kann.

(es gelten die selben technischen Voraussetzungen wie bei #939)

**Comment by mtrojan-ub** [comment]
@relhei + @Gazeller: Gibt es genauere Vorgaben wie das genau angeizeigt werden soll, einen Hilfstext o.Ä.?

![grafik](https://user-images.githubusercontent.com/26873381/74245399-3644ff00-4ce3-11ea-8686-38c48a21903d.png)

**Comment by relhei** [comment]
Wenn möglich, würden wir gerne einen Button zum Abonnieren des Feeds auf dem Panel des Newsaggregators auf Homepage plazieren, etwa so:
![grafik](https://user-images.githubusercontent.com/25769591/76747047-cfe74c80-6778-11ea-9616-ed699b5cea71.png)
Einen kurzen Text für die Feed-Seite schicke ich noch per Mail.

**Comment by mtrojan-ub** [comment]
Kann auf ptah angeschaut werden (Button ist ggf. noch suboptimal bei niedriger Auflösung, hat jemand dazu einen Vorschlag?)

**Comment by relhei** [comment]
Für den Button hätte ich eine einfache Lösung: Statt "RSS-Feed abonnieren" nur "Abonnieren". Das sollte doch aussagekräftig genug sein, oder? Danke!

**Comment by thefass** [comment]
"Feed abonnieren" fände ich eindeutiger. Was für die jetzige Lösung spräche, wäre, dass die Nutzer gleich wissen, dass es das RSS Format ist.

Frage: ist die Aktualisierung auf Relbib gerade angehalten? der aktuellste Feed ist vom 3.3.2020

**Comment by relhei** [comment]
Und wenn man statt der Glocke das RSS-Feed Symbol benutzt? Und dann so was wie "Folgen" bzw. "Follow us"? Oder bei "Abonnieren" bleiben?

**Comment by thefass** [comment]
RSS Symbol und Abonnieren ist gut

**Comment by mtrojan-ub** [comment]
Icon habe ich ausgetauscht, bitte stellt mir noch eine DE+FR Übersetzung für "Abonnieren" zur Verfügung.

**Comment by relhei** [comment]
Danke, das sieht jetzt gut aus. Englisch evt. besser: "Subscribe to RSS Feed"? Die französische Übersetzung habe ich auch so bei Deepl gefunden. Passt.

**Comment by ruschein** [comment]
"Subscribe to RSS Feed" ist gutes English! :-)

**Comment by mtrojan-ub** [comment]
Das ist ja dann die lange Version. Aktuell gibt es im Standard-VuFind folgenden Text:
- EN: "Get RSS Feed"
- DE: "RSS-Feed abonnieren"
- FR: "S'abonner aux flux RSS"

Der Punkt ist, der Text sollte so kurz wie möglich sein da es sonst bei geringer Auflösung ein Darstellungsproblem mit dem 2. Button "Weiterlesen" in der selben Zeile gibt.

Also entweder lassen wir es so, dann brauchen wir nichts ändern, oder wir verwenden einen kürzeren Text wie "Abonnieren", dann sollte der EN+FR Text aber auch kurz sein.

**Comment by relhei** [comment]
Ok, das ist ein Argument dafür, es so zu belassen. Und verständlich ist es allemal. Danke!
