### ISSUE TITLE
Trennung von Hauptitel und Untertitel in der Volltitelanzeige

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#1112]
> In Vufind wird allerdings der Zusatztitel mit $b nur in der Kurztitelanzeige als Doppelpunkt dargestellt, aber nicht in der Volltitelanzeige. https://ixtheo.de/Record/1688138382. Siehe https://github.com/ubtue/DatenProbleme/issues/635#event-3035356503

Auch in der Volltitelanzeige soll wie in der Kurztitelanzeige Haupttitel und Untertitel : getrennt werden:
Leiderfahrungen als Ort des Aufbrechens der Gottesfrage? : Erkundungen in der Gegenwartsliteratur 

In diesem Fall wäre das zwar nicht so relevant, da eine Trennung durch ? gegeben ist. In vielen Fällen ist es aber seltsam, da Hauptitel und Untertitel semantisch gar nicht zusammenpassen und ohne Trennzeichen sehr selten aussieht

z.B. hier:
Christlicher Antisemitismus im 20. Jahrhundert der Tübinger Theologe und "Judenforscher" Gerhard Kittel 

richtig wäre:
Christlicher Antisemitismus im 20. Jahrhundert : der Tübinger Theologe und "Judenforscher" Gerhard Kittel 

Trenner: Leerschritt Doppelpunkt Leerschritt

**Comment by ruschein** [comment]
Scheint mittlerweile zu tun, auch auf IxTheo.

**Comment by IxTheoKm** [comment]
Wird jetzt korrekt angezeigt
