### ISSUE TITLE
Fehlende Datensätze und Abrufzeichen

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#1125]
Ich finde im K10plus mit dem Abrufzeichen f abl ixzg 946 Treffer, mit f abl ixze 472 Treffer.
Im IxTheo sind es aber nur rs:916 bzw. rs:469 Treffer. 
(Zur Info: ixzg: Zeitschriften- oder Schriftenreihengesamtaufnahmen gedruckt, ixze: … online).

Bei folgenden Abrufzeichen, die wir seit einer Weile nicht mehr verwenden, so dass die Anzahl statisch sein müsste, finde ich folgende Differenzen:
ixfs (=Festschrift):  28 Treffer.
ixks (=Kongressschrift): 20 Treffer.

Beim Abrufzeichen ixst (=Stücktitel) gibt es sogar eine Differenz 406 Treffern. Allerdings sind hier im VuFind mehr vorhanden als in K10plus!

Ich frage mich, ob die Datensätze im VuFind fehlen oder ob es im K10plus und/oder VuFind ein Indexierungsproblem ist und bitte um Abgleich der PPN-Listen für die Abrufzeichen ixze und ixzg.

[ppnliste_ixze.txt](https://github.com/ubtue/tuefind/files/4249086/ppnliste_ixze.txt)
[ppnliste_ixzg.txt](https://github.com/ubtue/tuefind/files/4249087/ppnliste_ixzg.txt)

**Comment by ruschein** [comment]
Also, die Datensätze sind fast alle vorhanden.  Es fehlt nur 1015243649 aus ppnliste_ixze.txt.  Alle anderen sind da.  D.h., es fehlen vermutlich Abrufzeichen in Solr.  Das Problem ist jetzt mindestens einen Datensatz zu identifizieren, der ein Absrufzeichen haben solle es aber nicht hat!

**Comment by ruschein** [comment]
Also der Grund warum z.B. 129081256 nicht gefunden wird wenn man nach ixzg sucht da wir den Datensatz ohne Lokalsatz ausgeliefert bekommen haben.

**Comment by IxTheoKm** [comment]
Vielen Dank! Dann müsste es sich also bei den Differenz-Titeln um alle Datensätze handeln, die wegen der zu großen Menge ohne Lokalsätze geliefert wurden. Mir war nicht klar, dass die TUUB- oder IxTheo-Lokalsätze dann auch nicht mitgeliefert werden.

Grundsätzlich muss man dann brücksichtigen, dass für alle Sätze ohne Lokaldaten (das könnten auch Monographien sein) IxTheo-Klassifikationen keinen Sinn machen, da diese dann nicht mitgeliefert werden!

Gibt es irgendwo eine einsehbare "Ablage" mit PPNs der Datensätze, die ohne Lokaldaten geliefert werden? Dann man bei Tests ggf. prüfen, ob man sie überhaupt einbeziehen kann.

(Die große Überzahl beim Abrufzeichen "ixst" ist mir inzwischen klar: ich finde in K10plus nur die eigenen Lokalsätze. Das Theologicum hat aber auch für uns mit diesem Abrufzeichen katalogisiert. Deren Lokalsätze sind auch im IxTheo vorhanden.)

**Comment by ruschein** [comment]
@IxTheoKm Hier sind die PPN-Listen für die Datensätze, die keine Lokaldaten haben.
[ixze_missing_local_data.txt](https://github.com/ubtue/tuefind/files/4249833/ixze_missing_local_data.txt)
[ixzg_missing_local_data.txt](https://github.com/ubtue/tuefind/files/4249834/ixzg_missing_local_data.txt)

**Comment by IxTheoKm** [comment]
Okay danke, damit sind die Differenz-Zahlen für ixzg und ixze geklärt:
bei ixze sind zwei Datensätze ohne Lokaldaten und ein Satz wurde gar nicht geliefert: PPN 1015243649 (ich ändere daher den Titel des Issues wieder). 
Der Satz war mit **mtex** versehen, weil er als Dublette zu PPN 1015242839 in der ZDB zur Löschung/Umlenkung beantragt wurde, was aber seit Jahren aussteht. Ich habe mtex wieder rausgenommen.

Meine Frage nach der Ablage für Datensätze ohne Lokaldaten war allgemeiner gemeint. Dafür lege ich ein neues Issue an und schließe dieses, weil das Problem geklärt ist.
