### ISSUE TITLE
Titeldaten ohne Lokalsätze

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#1128]
Datensätze die durch zu viele Lokalsätze für die MARC-Auslieferung zu groß sind, werden ohne Lokalsätze geliefert. Das kann sowohl Zeitschriften, Schriftenreihen als auch Monographien betreffen. Wieviele Datensätze sind denn überhaupt davon betroffen?

Dies hat zur Folge, dass ggf. erfasste IxTheo-Notationen oder lokale Abrufzeichen nicht geliefert werden, weil schenbar auch unsere eigenen Lokalsätze davon betroffen sind (vgl. "BSZ Datenabzüge" im Tuefind Wiki und https://github.com/ubtue/tuefind/issues/1125). Ob das ein vernachlässigbares Problem ist, lässt sich nur einschätzen, wenn man weiß um wieviele Daten es geht.

Kann irgendwo z.B. im Wiki an einsehbarer Stelle die PPN-Liste von Datensätzen abgelegt werden, um bei Tests feststellen zu können, ob ein Datensatz von der Nicht-Lieferung der Lokalsätze betroffen ist?

**Comment by ruschein** [comment]
Hier ist die Liste der PPNs für Datensätze ohne Lokaldaten.
[no_lok.txt](https://github.com/ubtue/tuefind/files/4250467/no_lok.txt)

**Comment by IxTheoKm** [comment]
@ruschein Leider kann ich das Problem damit doch nicht einschätzen. War ein Denkfehler: in der Liste stecken ja auch alle Datensätze, die ganz korrekt ohne Lokaldaten geliefert werden, weil sie keine Tübinger Exemplardaten haben. 

Ich verstehe leider nicht genau, wie die Daten in https://github.com/ubtue/tuefind/wiki/BSZ-Datenabz%C3%BCge gelisteten Komplett- und Teilabzüge mit und ohne Lokaldaten aussehen. 

Waren diese Abzüge nicht dazu gedacht, das Problem der zu großen MARC-Datensätze zu löschen, so dass diese auf jeden Fall mit unseren Tübinger Lokaldaten eingespielt werden können?

**Comment by ruschein** [comment]
@IxTheoKm Die Problematik mit verlorenen Datensätzen oder Lokaldaten sollte es nicht mehr geben.  Ursprünglich wurden uns Datensätze die übergroß waren nicht ausgeliefert.  Seit geraumer Zeit bekommen wir zwei Lieferungen: Eine mit allen Datensätzen, die unseren Abzugskriterien entsprechen, ohne Lokaldaten und eine zweite, die nur Datensätze enthält, die unseren Abzugskriterien entsprechen und Tübinger Lokaldaten enthalten.  Wir schmeißen dann die Duplikate weg, und zwar, die Datensätze, die keine Lokaldaten enthalten.  In der Resultatmenge sind also alle Tübinger Lokaldaten enthalten.  Falls das nicht der Fall sein sollte ist es vermutlich ein Problem beim BSZ.

**Comment by IxTheoKm** [comment]
@ruschein Der Hintergrund meiner Frage ist, dass ich im K10plus mit lokalen Abrufzeichen mehr Datensätze finde als im IxTheo.

Bsp.:
**rs:ixzg** 936 Treffer im IxTheo, 
**f abl ixzg** 946 Treffer im K10plus (an der Zahl hat sich seit letztem Jahr so gut wie nichts mehr geändert):
[download.txt](https://github.com/ubtue/tuefind/files/4689566/download.txt)

Ich hatte vermutet, dass möglichweise nur die Lokaldaten fehlen. Aber das scheint mir doch nicht die Ursache zur sein.

Weitere Beispiele:
IxTheo / K10plus:
ixfs: 1692 / 1715
ixks: 2840 / 2857
ixst: 4649 / 4242 (umgekehrt!)

**Comment by ruschein** [comment]
Dann müssten Sie eine PPN finden, die im IxTheo fehlt.  Die sollten Sie mir melden.  Ich werde Ihnen dann sagen ob wir die erhalten haben oder nicht.

**Comment by IxTheoKm** [comment]
Mit dem lokalen Abrufzeichen ixzg sind folgende 10 Datensätze ohne Lokaldaten im IxTheo, daher nicht mit rs:ixzg auffindbar:

129070661
129079928
129292699
129304018
129469858
129480630
129556505
130122769
166756865
171084195

**Comment by IxTheoKm** [comment]
@ruschein Die Differenz beim Abrufzeichen ixfs beträgt 22:

1604990147
--
161344379X
1616800453
196194296
238201198
301442452
303297557
341776718
359643361
364321679
387843418
391428721
506312836
511995326
512668639
522181694
522899897
525485473
53090909X
567030695
611907658
626476984

**Comment by IxTheoKm** [comment]
@ruschein Die Differenz beim Abrufzeichen **ixks** beträgt 17:

1173385916
160736588X
1611334772
269469028
319370410
321257502
34286162X
352647566
388544589
391830228
479062374
502310952
512668388
517390981
528630970
555680193
605364028

**Comment by IxTheoKm** [comment]
Ich habe nur die überschaubaren Treffermengen verglichen, da der Export sonst zu lange und aufwändig ist (nacheinander je 500 Treffer als PPN-Liste). 
Abrufzeichen ixst im IxTheo (4649) und K10plus (4242) konnte ich daher nicht vergleichen.

Vielleicht lässt sich aber aus o.g. Datensätzen das Problem eingrenzen. Es wären ja ggf. auch alle anderen Datensätze mit anderen oder ohne lokale Abrufzeichen betroffen. 
Wenn die Lokaldaten fehlen, fehlen wie gesagt z.B. die IxTheo-Klassifikationen.

**Comment by ruschein** [comment]
@IxTheoKm Ich habe das BSZ wegen dieser Problematik kontaktiert da aber Herr K. zur Zeit krank geschrieben ist müssen wir leider bis mindestens den 8.6. warten bevor wir endgültig klären können was da passiert.
Meine Vermutung ist, dass wenn es keine Änderung an den Lokaldaten gibt, aber eine Änderung an den Titeldaten, dann wird der Datensatz nur ohne Lokaldaten an uns ausgeliefert.  D.h., wir verlieren dann die Lokaldaten!  Eine mögliche Lösungsstrategie (wir halten uns die Lokaldaten in einer neuen Datenbank und hängen sie immer an die Titeldaten) habe ich aber wir sollten erst über eine Implementation nachdenken wenn Herr K. vom BSZ wieder zur Verfügung steht und meinen Verdacht bestätigen kann bzw. wenn es nicht möglich sein sollte die Datenauslieferungen so zu gestalten, wie wir das alle angenommen hatten.

**Comment by IxTheoKm** [comment]
Zum Test habe ich eine **Korrektur in den Lokaldaten** der jeweils ersten Aufnahme o.g. PPNs  durchgeführt. Diese sollten dann _mit_ Lokaldaten geliefert werden:

https://ixtheo.de/Record/129070661#details [nur Lokaldaten korrigiert]

https://ixtheo.de/Record/1604990147#details [hier musste ich wg. Validationsfehler den Titelsatz _und_ Lokaldaten korrigieren]

https://ixtheo.de/Record/1173385916#details [nur Lokaldaten korrigiert]


Willkürlich herausgegriffen und **Korrekturen im Titelsatz** _ohne Korrektur im Lokalsatz_ durchgeführt:

https://ixtheo.de/Record/1646995872#details 

https://ixtheo.de/Record/319441180#details

Am 29.05.2020 sind in VuFind Lokaldaten von IxTheo bzw. IxTheo und THEOLDI vorhanden.

Wenn Ihre Vermutung stimmt, müssten die beiden Datensätze nach der Korrekturlieferung ohne Lokaldaten eingespielt werden.

**Comment by IxTheoKm** [comment]
Fehlende Lokaldaten mit Abrufzeichen **ixst**

023024402
1587830310
1617265896
304356166
894542397

**Comment by IxTheoKm** [comment]
In allen am 29.05. testweise korrigierten Datensätzen sind die Lokaldaten vorhanden,
auch bei Titeldatenkorrektur _ohne_ Lokaldatenkorrektur:
PPN 1646995872, 319441180: Lokaldaten sind weiterhin vorhanden.

Das scheint gegen die o.g. Theorie zu sprechen (es sei dann, das BSZ hat schon eine Änderung vorgenommen).

**Comment by IxTheoKm** [comment]
@ruschein Ist mit der neuen Lokaldatenstrategie dieses Issue erledigt, d.h. die Klärung mit Herrn K. erfolgt?

Ich habe zum Vergleich die lokalen Abrufzeichen im K10plus und im IxTheo verglichen. Sie stimmen weitgehend überein (bei denen mit  täglich neuen Datensätzen kann ich das nicht prüfen).

@jriedl Stimmt dann die Übersicht im Wiki https://github.com/ubtue/tuefind/wiki/BSZ-Datenabz%C3%BCge noch?

Dann könnte ich dieses Issue schließen.

**Comment by ruschein** [comment]
Ja, die Klärung mit Herrn K ist erfolgt.

**Comment by jriedl** [comment]
Es gab keine Änderung an den Abzugkriterien. Die Frequenz für die Hinweis-Abzüge wurde korrigiert.

**Comment by IxTheoKm** [comment]
Danke, ich schließe!
