### ISSUE TITLE
Mehrsprachige Suche :: unerwartete Ergebnisse

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#1129]
Bei der Schlagwortsuche sollten mit den mahersprachigen Äquivalenten annähernd gleiche Ergebnisse erzielt werden. Das ist momentan nicht mehr der Fall.
Beispiele folgen nach der Beiratssitzung.
Diskusiieren wir im nächsten IT Meeting

**Comment by thefass** [comment]
Suchaspekt: Schlagwort:
Suche nach Dogma > 776 Treffer
+++++++
nach doctrine > 40.751 https://www.ixtheo.de/Search/Results?lookfor=doctrine&type=Subject
Problem: Wie kommt in https://www.ixtheo.de/Record/1686895429 in STA und STB doctrines zustande, obwohl das normierte SW nicht in 689 vorhanden ist
![Bildschirmfoto 2020-02-27 um 22 16 00](https://user-images.githubusercontent.com/14169098/75487531-d4f18100-59ae-11ea-872a-a0cfc710c115.png)

Problematisch auch die vielen Wiederholungen

**Comment by jriedl** [comment]
Abschließende Klärung erst nächste Woche möglich, aber mit hoher Wahrscheinlichkeit handelt es sich um ein MACS-Synonym (!) (nicht die ursprüngliche MACS-Übersetzung) aus den Normdaten. Da so bei "XXX Theology" wohl häufig auch "XXX/YYY Church - Doctrine (z.B.  https://ixtheo.de/Record/1678252506#details) einfließt, ergeben sich bei der Suche nach dem englischen/französischen Term (neben des deutlich breiteren Bedeutungsspektrums von "doctrine" im Vergleich zu "Dogma"  (vgl. u.a. "Lehre" und "Glaubenslehre") deutlich höhere Trefferzahlen.

**Comment by thefass** [comment]
Vielleicht wäre eine Lösung, dass wir bei SW auch eine Suche mit und ohne Synonyma einführen. Analog zur Volltextsuche

**Comment by jriedl** [comment]
Ursprüngliche MACS-Übersetzungen wurden zwischenzeitlich als Synonyma mitgeführt. Das ist nun nicht mehr der Fall. Im konkreten obigen Beispielt sinkt damit die Treffermenge auf ca. 25.000.

**Comment by jriedl** [comment]
Die Synonym-Behandlung der Volltextsuche setzt auf einem völlig anderen Ansatz auf, bei dem die Synonyma in den Token-Strom der Abfrage eingespeist werden. Abgesehen vom Aufwand erscheint eine zu starke Differenzierung der Suchaspekte aus Nutzersicht eventuell unvorteilhaft, da damit die ohnehin bereits hohe Anzahl der Suchaspekte noch weiter erhöht würde und die Ergebnismengen noch weiter fragmentiert würden.

**Comment by thefass** [comment]
kann sich durch AP 1.2 der laufenen FID Periode 2012-2023 entschärfen.
