### ISSUE TITLE
Mehrfache Wiederholung von Angaben (ISSN-Blöcke in JOP)

### ISSUE THREAD

**Issue by AleAprile** [ubtue/tuefind#1130]
Die online Verfügbarkeit der "Zeitschrift für die alttestamentliche Wissenschaft" wird in IxTheo mehrfach wiederholt (siehe Langtitelanzeige https://ixtheo.de/Record/129461423). 
Sind vielleicht andere Zeitschriften von diesem Fehler betroffen?

**Comment by ruschein** [comment]
Ich sehe 2 Themen hier.  Terminologie:  Ich nenne die Zeilen mit den Icons mal "Kopfzeilen" eines Blocks.  1) Ich würde vorschlagen die Kopfzeilen zu kombinieren, also untereinanderscheiben, wenn alle weitern Zeilen eines Blocks indentisch sind.
2) Man hat als Suchender keine Ahnung was man anklickt (z.B,. welchen Veröffentlichungszeitraum).  Da der Datensatz vermutlich keine Zuordnung von Zusatzinformationen zu den jeweiligen ISSNs zulässt, ist die Frage ob das JOP-API etwas Nützliches zurückliefert.

**Comment by IxTheoKm** [comment]
Die Mehrfachangaben haben unterschiedliche ISSNs (siehe auch https://github.com/ubtue/tuefind/issues/804)

![JOP](https://user-images.githubusercontent.com/17004223/75988762-6488b980-5ef2-11ea-9526-ad3c4c3dc0a3.JPG)

**Comment by mtrojan-ub** [comment]
Heute in der FID-Runde besprochen, ISSNs fett hervorheben + Blöcke bilden

**Comment by IxTheoKm** [comment]
Hier weitere Beispiele:
https://ptah.ub.uni-tuebingen.de/Record/129457280
https://ptah.ub.uni-tuebingen.de/Record/169137066
https://ptah.ub.uni-tuebingen.de/Record/170643255
https://ptah.ub.uni-tuebingen.de/Record/356884376

**Comment by thefass** [comment]
Ja, sieht gut aus, wenn man eingelogt ist.

**Comment by thefass** [comment]
Wenn man nicht eingelogt ist, hat man drei gleichlautende Links
<img width="473" alt="Bildschirmfoto 2022-03-09 um 16 54 55" src="https://user-images.githubusercontent.com/14169098/157479132-8012cb51-13b1-4da0-94e2-05bf47035746.png">

Hier wäre gut, wenn noch die ISSN mit angegeben wird.

Beispiel: 
Verfügbarkeit prüfen (0934-2796)

**Comment by mtrojan-ub** [comment]
@thefass: Das können wir nicht reproduzieren, bzw. der Login-Zustand sollte keinen Unterschied machen. Auch mit der genannten ISSN können wir das nicht nachvollziehen.

Kannst Du uns bitte einen konkreten Link auf einen Datensatz auf ptah nennen?

**Comment by thefass** [comment]
sorry, hatte ich vergessen mit zu posten:
https://ptah.ub.uni-tuebingen.de/Record/129461423

**Comment by mtrojan-ub** [comment]
ready for testing auf ptah

**Comment by thefass** [comment]
ok
