### ISSUE TITLE
URL in Alerting Mail

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#1133]
Dem Nutzer wird als URL ub26 angezeigt.
![Bildschirmfoto 2020-02-29 um 13 57 15](https://user-images.githubusercontent.com/14169098/75607948-92898a80-5afb-11ea-96ab-59ef014d1aa2.png)

Bitte wieder https://www.ixtheo.de/ verwenden. Das stärkt die Identifikation

**Comment by ruschein** [comment]
Sollte ab morgen behoben sein.

**Comment by thefass** [comment]
Ist behoben.
