### ISSUE TITLE
BEACON Weiterleitung aus Wikipedia Personensuche 

### ISSUE THREAD

**Issue by socheres** [ubtue/tuefind#1139]
Link https://ixtheo.de/Search/Results?lookfor=author_id:115684336
aus https://tools.wmflabs.org/persondata/p/Erich_Zenger
führt zu keinem Treffer in IxTheo.
[BEACON-Datei](https://ixtheo.de/docs/ixtheo-beacon.txt) muss angepasst werden. 
`#TARGET: https://ixtheo.de/Search/Results?lookfor=author_id:{ID}
` 
ohne Präfix "author_id"
`#TARGET: https://ixtheo.de/Search/Results?lookfor={ID}
`

**Comment by jriedl** [comment]
Die Target-Abfrage ist korrekt, allerdings enthielt das author_id-Feld eine Normdaten-PPN und nicht die GND-Nummer. Das haben wir jetzt auf ptah behoben. Bitte aber zukünftig wieder die ursprünglich getroffene Vereinbahrung beachten, dass die Bearbeiterzuweisung abteilungsintern erfolgt.

**Comment by socheres** [comment]
Hast du die gesamte Datei aktualisiert? Vielleicht sind andere IDs auch davon betroffen. Von der intern getroffene Vereinbarung hatte ich bislang keine Kenntnis. Aber jetzt weiß ich.

**Comment by jriedl** [comment]
Die Datei ist korrekt, nur die Suche innerhalb des author_id-Felds führte zu keinem Ergebnis, da hier keine nicht die GND-Nummern hinterlegt waren.

**Comment by socheres** [comment]
https://tools.wmflabs.org/persondata/p/Karl_Ludwig_Michelet führt auch zu keinem Ergebnis

**Comment by jriedl** [comment]
Doch: Auf ptah liefert die Suche nach author_id:11858216X 9 Treffer. Auf ixtheo funktioniert das natürlich erst nach dem nächsten Update.

**Comment by relhei** [comment]
Muss das gfs. auch für die RelBib-BEACON-Datei angepasst / behoben werden? Bitte prüfen, falls nötig. Danke!

**Comment by jriedl** [comment]
Da die Änderungen nicht an der BEACON-Datei vorgenommen wurden, sondern am Inhalt des Zielfeldes, sind für RelBib keine weiteren speziellen Anpassungen nötig. Die Suche nach Erich Zenger https://relbib.de/Search/Results?lookfor=author_id:115684336 liefert offenbar plausible Ergebnisse (bei Records, bei denen er nicht unmittelbar unter den Autoren auftaucht, ist er anderweitig in den 700 Feldern hinterlegt, z.B. als "hnr" ("=Geehrter")).

**Comment by thefass** [comment]
dürfte erledigt sein. Ich schließe
