### ISSUE TITLE
URN-Link auf doi.org-Seite

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#1142]
Wir weisen seit heute viele Volltext-Dokumente aus MENAdoc (GBV) nach. Klick auf URN-Link unter "Persistent Identifiers" führt immer auf die doi.org-Seite und erzeugt entsprechend Fehlermeldung. 
![grafik](https://user-images.githubusercontent.com/25769591/75974185-aa378900-5ed6-11ea-8fea-ea5a5fb8e476.png)
Hier noch der Link auf den record:
https://www.relbib.de/Record/803230265
Bitte URN-Link richtig auflösen, wenn Fehler auffindbar.

**Comment by mtrojan-ub** [comment]
Scheint so als hätten wir die Basis-URL von DOIs und URNs versehentlich vertauscht gehabt. Ist jetzt auf ptah behoben:
https://134.2.67.9/Record/803230265

**Comment by relhei** [comment]
Funktioniert - danke!
