### ISSUE TITLE
Suchabfrage nach Sammlungen möglich?

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#1143]
In Feld 935 $a stehen Codes von Sammlungen und für Testzwecke oder auch Verlinkungen speziell auf diese Sammlungen benötigen wir eine Abfrage in RelBib. Wir bitten daher um Einrichtung einer entsprechenden Abfrage à la rs:xxxx (nach den Abrufzeichen). Beispiel in WinIBW für Sammlung menadoc:
![grafik](https://user-images.githubusercontent.com/25769591/75976721-42377180-5edb-11ea-9db3-00c684ac3737.png)

https://www.relbib.de/Record/1689652071

**Comment by IxTheoKm** [comment]
@relhei 
Funktioniert schon, allerdings ist Groß- und Kleinschreibung erforderlich:
rs:MENAdoc

**Comment by relhei** [comment]
Ja, das ist lt. @jriedl das Testbeispiel. Die anderen Titel der Slg. können dann nach der nächsten Einspielung (?) auf diese Art abgerufen werden.

**Comment by jriedl** [comment]
Ausgangsfrage hat im Vorfeld schon funktioniert. Durch Übernahme des ursprünglich auf Krimdok beschränkten "abr" ist jetzt (derzeit auf ptah) auch eine Suche ausschließlich auf 935$a (ohne 935a-Lokaldatenfeld) möglich, falls sich hier zukünftig ein Anwndungsbereich ergibt.

**Comment by relhei** [comment]
Vielen Dank. Die Suchabfrage auf ptah abr:MENAdoc ergibt aktuell 181 Treffer. Es sollten aber wesentlich mehr sein (647). Kommen die anderen Titel noch in den nächsten Tagen? Sie wurden bereits am Freitag für RelBib gekennzeichnet (084$a0).

**Comment by jriedl** [comment]
Ptah liefert bei mir 188 Treffer. Der Datenstand auf ptah ist allerdings derzeit wegen Pipelineproblemen nicht aktuell, sondern auf dem Stand von letzter Woche. Sollte nach dem nächsten erfolgreichen Import behoben sein. Für den ursprünglichen Anwendungsfall läßt sich auch die rs-Abfrage auf RelBib verwenden (652 Treffer).

**Comment by relhei** [comment]
Funktioniert jetzt bestens - danke!
