### ISSUE TITLE
Datensätze nicht aktuell

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#1146]
Siehe https://github.com/ubtue/fid/issues/8

Korrekturen wurden nicht geliefert/umgesetzt?

**Comment by Gazeller** [comment]
Auch gestern vergebene GND Schlagwörter werden nicht in RelBib angezeigt. Zum Beispiel: ppn 1685893589

**Comment by jriedl** [comment]
Anfrage bei BSZ läuft.

**Comment by jriedl** [comment]
Antwort vom BSZ ist erfolgt: Titel, die aus dem Digitalen Assistenten angereichert wurden, wurden mit einer Einstellung in die BSZ-Datenbank gespielt, die dazu geführt hat, dass diese Daten nicht in die Abzüge übernommen wurden. Von Seiten des BSZ werden jetzt Scheinkorrekturen vorgenommen, so dass für die geänderten Daten voraussichtlich am Donnerstag die Korrekturen vorliegen.

**Comment by jriedl** [comment]
Update durch das BSZ: Scheinkorrekturen abgeschlossen, sollten also mit den Teilabzügen von heute Nacht eingespielt werden.

**Comment by jriedl** [comment]
Für die ursprüngliche angesprochene PPN 1570617538 ist die zusätzliche Schlagwortfolge jetzt vorhanden.

**Comment by IxTheoKm** [comment]
Ein Datensatz, der am 19.03.2020 korrigiert wurde und im IxTheo einen Stand vom 19.03.2020 hat, ist die Bibelstelle angekommen: https://ixtheo.de/Record/152318504X#details
Funktioniert also.
