### ISSUE TITLE
Erweiterte Suche: unterschiedliche Trefferzahlen auf Ptah und RelBib

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#115]
Bei identischer Suchanfrage erscheinen unterschiedliche Trefferzahlen.

RelBib:
https://relbib.de/Search/Results?sort=relevance&join=AND&lookfor0%5B%5D=Islam&type0%5B%5D=AllFields&lookfor0%5B%5D=Hinduismus&type0%5B%5D=AllFields&bool0%5B%5D=OR&lookfor1%5B%5D=Geschlechterrolle&type1%5B%5D=AllFields&bool1%5B%5D=AND&daterange%5B%5D=publishDate&publishDatefrom=&publishDateto=&limit=20
Ptah:
https://134.2.67.9/Search/Results?sort=relevance&join=AND&lookfor0%5B%5D=Islam&type0%5B%5D=AllFields&lookfor0%5B%5D=Hinduismus&type0%5B%5D=AllFields&bool0%5B%5D=OR&lookfor1%5B%5D=Geschlechterrolle&type1%5B%5D=AllFields&bool1%5B%5D=AND&daterange%5B%5D=publishDate&publishDatefrom=&publishDateto=&limit=20

**Comment by mtrojan-ub** [comment]
Suche liefert aktuell 136 auf ptah und 144 auf relbib.

Beispiele für Datensätze die nur auf relbib im Suchergebnis enthalten sind:

![grafik](https://user-images.githubusercontent.com/26873381/34212089-809eb656-e59b-11e7-9fb2-432b964d5b01.png)

![grafik](https://user-images.githubusercontent.com/26873381/34212328-4203fa90-e59c-11e7-99ca-1e3fd6724ea4.png)

![grafik](https://user-images.githubusercontent.com/26873381/34212453-94f8a4c6-e59c-11e7-991c-8120f96be0a7.png)

![grafik](https://user-images.githubusercontent.com/26873381/34212791-ba08dd0c-e59d-11e7-820b-49c9106b882b.png)


(Nummerierung kommt von Sortierung nach Titel bei 100 Treffern pro Seite)

https://134.2.67.9/Search/Results?sort=title&join=AND&bool0%5B%5D=OR&lookfor0%5B%5D=Islam&lookfor0%5B%5D=Hinduismus&type0%5B%5D=AllFields&type0%5B%5D=AllFields&bool1%5B%5D=AND&lookfor1%5B%5D=Geschlechterrolle&type1%5B%5D=AllFields

https://relbib.de/Search/Results?join=AND&bool0%5B%5D=OR&lookfor0%5B%5D=Islam&lookfor0%5B%5D=Hinduismus&type0%5B%5D=AllFields&type0%5B%5D=AllFields&bool1%5B%5D=AND&lookfor1%5B%5D=Geschlechterrolle&type1%5B%5D=AllFields&sort=title

(nur ein Zwischenstand, ich schau's mir noch weiter an)

**Comment by mtrojan-ub** [comment]
Es scheint daran zu liegen dass in den Datensätzen auf ptah die Felder 184 und 186 nicht vorhanden sind. Die Ursache ist bisher noch unklar.

**Comment by mtrojan-ub** [comment]
Ich vermute, dass das etwas mit den Änderungen von November zu tun hat (cpp/add_synonyms.cc => translated synonyms).

@jriedl : Die Änderungen waren doch recht komplex, kannst Du Dir das bitte selbst anschauen?

**Comment by jriedl** [comment]
Problem war die Behandlung deutschsprachiger Synonyme. Diese werden jetzt wieder ausgewertet. Weiterhin fließen jetzt auch fremdsprachige Synonyme ein.

**Comment by relhei** [comment]
Passt. Vielen Dank!
