### ISSUE TITLE
Anzeige der Lizenzinformationen

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#1159]
In der Kurz- und Vollanzeige werden ggf. Links zum Volltext angezeigt. Diese können teilweise kostenfrei, lizenzpflichtig u.ä. sein.
Die entspr. Informationen stehen in 856 $z

Lt. Formatdokumentation (ausgeliefert wird Klartext; Buchstaben sind nur Erfassungscodes):
LF = **Kostenfrei**
KF = **Kostenfrei, registrierungspflichtig**
KW = **Teilw. kostenfrei**
NL = **Deutschlandweit zugänglich**
PU = **Pay-per-Use-Zugang, kostenpflichtig**
EL = **Einzellizenz**

Alternativ, **falls $z nicht vorhanden ist**, kann **$x** herangezogen werden:
H = Verlag
A = Agentur
D = Digitalisierung
F= EZB
C = Archivierung
G = Aggregator
L = Langzeitarchivierung
N = Langzeitarchivierung Nationalbibliothek
R = Resolving-System
T = DBIS

Bsp.: PPN 1523156384
https://ptah.ub.uni-tuebingen.de/Record/1523156384#details
https://ixtheo.de/Record/1523156384#details

856 40$uhttp://dx.doi.org/10.15496/publikation-36718$xResolving-System$z**Kostenfrei**$3Volltext
856 40$uhttp://hdl.handle.net/10900/95335$xResolving-System$z**Kostenfrei**$3Volltext
856 40$uhttp://dx.doi.org/10.1515/nzsth-2012-0009$xResolving-System$xVerlag$z**Lizenzpflichtig**$3Volltext

Kann/soll $z jeweils hinter "Volltext" in der Kurz- und Vollanzeige aufgeführt werden, oder gibt es da "Wettbewerbsaspekte" zu berücksichtigen?

![Lizenz](https://user-images.githubusercontent.com/17004223/77414451-57f4d400-6dc1-11ea-950d-d3e21f25ad84.JPG)

![Lizenz2](https://user-images.githubusercontent.com/17004223/77414469-5f1be200-6dc1-11ea-8d5a-4d64122a52c8.JPG)

**Comment by IxTheoKm** [comment]
Es sind noch weitere Aspekte zur Anzeige/Auswertung von MARC 856 (Indikator 40 und 42 und entspr. Unterfelder) im Rahmen der Zweitveröffentlichungsprojekte aufgetaucht, die geklärt werden müssen

**Comment by IxTheoKm** [comment]
Für mich sieht es so aus, als sei das ursprüngliche Anliegen umgesetzt.

> Es sind noch weitere Aspekte zur Anzeige/Auswertung von MARC 856 (Indikator 40 und 42 und entspr. Unterfelder) im Rahmen der Zweitveröffentlichungsprojekte aufgetaucht, die geklärt werden müssen

Sind für die Zweitveröffentlichungen noch weitere Aspekte zu berücksichtigen?
Der entspr. Hinweis kam damals nach meiner Erinnerung von @IxKo und @relhei.

**Comment by IxKo** [comment]
Danke, ich habe nichts hinzuzufügen.

**Comment by relhei** [comment]
Ja gerne, alle angesprochenen Punkte wurden bearbeitet. Danke!
