### ISSUE TITLE
Darstellung der Bibelstelle in der Kurztitelanzeige

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#116]
Eine Suche nach Gen 22,1-19 ergibt folgende Liste:

Ab dem Titel 310 werden die Stellen ohne Trennung falsch dargestellt:
![bildschirmfoto 2017-12-19 um 23 31 23](https://user-images.githubusercontent.com/14169098/34182045-09de7f96-e515-11e7-8938-9e8b8c117369.png)
falsch: Rom 832
richtig Rom 8,32
In den Marcdaten ist das auch richtig umgesetzt, nicht aber in der Anzeige
Ab Titel 313 sind richtige und falsche gemischt. Was ist der Grund dafür?

**Comment by thefass** [comment]
Bitte auch generell den Punkt durch ein Komma ersetzen
falsch Gen 22.1-19
richtig Gen 22,1-19
Der Punkt hat nämlich die Bedeutung, Verse voneinander abzusetzen.

**Comment by ruschein** [comment]
@thefass Ready for testing.  Auf Ptah.

**Comment by thefass** [comment]
funktioniert
