### ISSUE TITLE
Anzeige von Verleger/Drucker in der Facette Verfasser

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#1161]
PPN 1522029095
**710** 2 $aFrères de Tournes **$4prt**
Bei Personennamen auch in Feld **700** möglich

Normierter **Verleger/Drucker** (VD 18) in Nicht-RDA-Sätzen wird in der Facette Verfasser angezeigt.
(Das zweite Beispiel kann ich nicht aufrufen. Es kommt die Fehlermeldung "Keine Ergebnisse")

![Drucker](https://user-images.githubusercontent.com/17004223/77890208-69c9f180-726f-11ea-948b-2f0195139eea.JPG)

**Comment by ruschein** [comment]
Ready for testing auf Ptah

**Comment by IxTheoKm** [comment]
Für 710 ... $4prt ist es jetzt okay.

**700 ... $4prt** wird noch in der Facette Verfasser angezeigt.

Bsp.:
https://ptah.ub.uni-tuebingen.de/Record/1493529080#details
**700** 1 $aCramer, Johann Heinrich **$4prt**
Hier steht Cramer, Johann Heinrich noch in der Facette "Verfasser"

Die Vollanzeige des Datensatzes ist im Prinzip okay. Da ist nur leider die einleitende Wendung "Weitere Verfasser" nicht gut, weil dort alle möglichen beteiligten Personen drin stecken, die _nicht_ Verfasser sein können
(siehe auch https://github.com/ubtue/tuefind/issues/625):

![Drucker2](https://user-images.githubusercontent.com/17004223/84904798-0a31f400-b0b0-11ea-950a-b8296e734084.JPG)

**Comment by ruschein** [comment]
Auf Ptah + IxTheo.

**Comment by IxTheoKm** [comment]
Keine Änderung:
700  $4prt steht weiterhin in der Facette "Verfasser":
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=id%3A1493529080&type=AllFields&limit=20&botprotect=
https://ixtheo.de/Search/Results?lookfor=id%3A1493529080&type=AllFields&botprotect=

![prt](https://user-images.githubusercontent.com/17004223/103548803-a1bd2f80-4ea6-11eb-8d72-b2f570a49c4a.JPG)


https://ptah.ub.uni-tuebingen.de/Record/1493529080#details

![prt2](https://user-images.githubusercontent.com/17004223/103548940-d4ffbe80-4ea6-11eb-8b6b-e9d25bf0bae7.JPG)

![prt3](https://user-images.githubusercontent.com/17004223/103549030-037d9980-4ea7-11eb-970c-2874f0ca5f32.JPG)

**Comment by ruschein** [comment]
Tut jetzt, sogar auf ub16.

**Comment by IxTheoKm** [comment]
Jetzt passt es, vielen Dank!
