### ISSUE TITLE
Quantitative Angaben in den Volltext "Facetten" 

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#1169]
Eine Suche nach "Heidentum" w/o Syn. hat 411 Treffer. 
https://ptah.ub.uni-tuebingen.de/Search2/Results?lookfor=heidentum&type=FulltextOnly&hiddenFilters%5B%5D=has_fulltext%3A1&limit=20&botprotect=
Wenn man auf Inhaltsverzeichnis einschränkt, werden 363 Treffer angezeigt. 
Könnten die Treffer wie bei den anderen Facetten in der unechten Facette angezeigt werden?

**Comment by jriedl** [comment]
Nein, aus den dargelegten Gründen: Die Anzeige der Anzahl setzt voraus, dass die Facettierung eine Einschränkung einer identischen Suche ist. Genau das ist aber in diesem Kontext nicht der Fall. Im Prinzip ist die "Facette" implizit ein Searchhandler (die Bereichsauswahlbox oben im Suchfeld).

**Comment by thefass** [comment]
ok, verstanden.
