### ISSUE TITLE
rss_aggregator: Keine neuen Einträge seit 3.3.2020

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#1173]
_Originally posted by @thefass in https://github.com/ubtue/tuefind/issues/1105#issuecomment-611613684_

Frage: ist die Aktualisierung auf Relbib gerade angehalten? der aktuellste Feed ist vom 3.3.2020

**Comment by mtrojan-ub** [comment]
In einem neu hinzugekommenen Feed (Religion in American History) gibt es ein Timestamp-Problem das zu einem Crash im Prozess führt. Das Problem haben wir bereits behoben, allerdings können wir ub16 erst nach der Urlaubszeit wieder aktualisieren.

Ich habe bis dahin den Feed aus der Config-Datei entfernt, so dass wenigstens die anderen Feeds aktualisiert werden. ("Natur des Glaubens" habe ich ebenfalls ausgesetzt da ein ähnliches Problem aufgetreten ist).

**Comment by thefass** [comment]
ok, Danke für die Info

**Comment by mtrojan-ub** [comment]
Es sind jetzt wieder neuere RSS-Einträge gelistet.

Die beiden Feeds Religion in American History und Natur des Glaubens sind ebenfalls wieder aktiv. Religion in American History taucht aber aktuell nicht mehr auf, der letzte Eintrag im Feed ist vom November 2019.

=> Ready for Testing

**Comment by thefass** [comment]
@relhei kannst Du das Testen bitte übernehmen und evt. schließen

**Comment by relhei** [comment]
Auf dem Produktivsystem sind die neuesten Beiträge noch vom 21. April. Das kann so nicht stimmen. Hab stichprobenartig geprüft und bei einigen Blogs gibt es definitiv neuere Einträge! Z. B. Religion in Piblic, Religion and Urbanity etc. Es wäre super, wenn es da bald eine Lösung gäbe, weil wir den Aggregator auch etwas stärker bewerben und gfs. ausbauen wollen.

**Comment by mtrojan-ub** [comment]
OK, habe gesehen dass auf dem Liveserver noch veraltete Einstellungen für den cronjob aktiv waren. Das habe ich behoben. Trotzdem funktioniert es noch nicht und ich bleibe weiter dran (das Abgreifen aus den Feeds funktioniert, aber beim Generieren des neuen RSS-Feeds schlägt wohl noch etwas fehl).

Cronjob-Änderungen beziehen sich auf:
- https://github.com/ubtue/ub_tools/commit/03fcb9ececc8d1304d6c2ee354b39e8486597868#diff-d7fb0e52d2ae453e726935aa52090537
- https://github.com/ubtue/ub_tools/commit/caa65de2d2c86ff378851e7bd16ec279070fbf33#diff-d7fb0e52d2ae453e726935aa52090537

**Comment by mtrojan-ub** [comment]
Der Fehler wurde behoben, bitte morgen nochmal drauf schauen => dann sollten die Einträge im Feed wieder aktuell sein.

**Comment by relhei** [comment]
Scheint jetzt alles auf dem aktuellen Stand zu sein. Vielen Dank!
