### ISSUE TITLE
Newsfeed-Aggregator: Links zu Blogs funktionieren nicht

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#1183]
Bei Klick auf die einzelnen Blogs funktionieren die Links nicht:
![grafik](https://user-images.githubusercontent.com/25769591/80570194-ac135980-89fa-11ea-9ed2-2e0cf82e5dcc.png)
Dann kommt z. B. diese Fehlermeldung:
https://www.relbib.de/RssFeed/https%3A%2F%2Fmarginalie.hypotheses.org%2Ffeed
Bitte beheben, danke!

**Comment by mtrojan-ub** [comment]
Kann auf ptah getestet werden

**Comment by relhei** [comment]
Jetzt wird man bei Klick auf die Links auf den Feed weitergeleitet. Als Nutzer*in hätte ich jetzt eher eine Weiterleitung auf den Blog erwartet, oder? Falls ihr das auch so seht, bitte noch ändern. Ansonsten bitte kurzen Kommentar schicken.

**Comment by mtrojan-ub** [comment]
Wir pflegen in unserer Ini-Datei momentan nur die URL des RSS-Feeds und nicht die des Blogs, siehe auch: https://github.com/ubtue/ub_tools/blob/master/cpp/data/rss_aggregator.conf

Wenn wir eine andere URL für den Link hinterlegen wollen dann solltest Du uns die genaue URL pro Feed mitteilen (oder ist das in 100% der Fälle immer nur die Domain ohne den Pfad am Ende?)

Außerdem: Betrifft das auch alle anderen Stellen an denen wir bisher auf den Feed und nicht auf den Blog verlinken?

![grafik](https://user-images.githubusercontent.com/26873381/80940547-6979c480-8de0-11ea-98ab-63f005329054.png)

![grafik](https://user-images.githubusercontent.com/26873381/80940629-a8a81580-8de0-11ea-82b4-206ad032f9ce.png)

**Comment by relhei** [comment]
Bitte nur an der eingangs hervorgehobenen Stelle (also unter der Erklärung, was der RelBib Newsfeed-Aggregator ist, die URLs zu den Blogs verlinken. Alles andere soll so bleiben wie bisher. Mail mit URLs kommt gleich.

**Comment by mtrojan-ub** [comment]
Das wurde umgestellt + kann jetzt getestet werden.

**Comment by relhei** [comment]
Vielen Dank, sieht jetzt gut aus! Einzig: kann man diese überdimensional großen Bilder vom Blog "Natur des Glaubens", die auf der "Weiterlesen-Seite" zu sehen sind, abstellen oder wenigstens verkleinern? Die stören etwas...

**Comment by mtrojan-ub** [comment]
Auf ptah werden die Bilder jetzt für die Anzeige entfernt, bitte nochmal testen

**Comment by relhei** [comment]
Sieht jetzt viel besser aus. Vielen Dank!
