### ISSUE TITLE
Kein Treffer mit Autosuggest

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#1185]
Bei der Eingabe eines Titels ("Arbeitstexte / Evangelische Zentralstelle...") wird der Vorschlag von Autosuggest übernommen und gesucht - "kein Ergebnis". Wenn der Titel über die einfache Suche gesucht wird (ohne Autosuggest), funktioniert es hingegen - Titel ist also enthalten und wird angezeigt.
Mit Autosuggest:
https://www.relbib.de/Search/Results?lookfor=Arbeitstexte+%2F+Evangelische+Zentralstelle+f%C3%BCr+Weltanschauungsfragen*&type=AllFields&botprotect=
Ohne Autosuggest:
https://www.relbib.de/Search/Results?lookfor=Arbeitstexte&type=AllFields&limit=20&botprotect=
(=Treffer Nr. 2)
Liegt es möglicherweise an dem Slash? Bitte Fehler beheben bzw. Autosuggest anpassen.

**Comment by jriedl** [comment]
Auf ptah.

**Comment by relhei** [comment]
Funktioniert jetzt wieder. Lag das Problem am Slash? Jetzt steht nämlich bei der Ergänzung durch Autosuggest an dessen Stelle ein V nach "Arbeitstexte".

**Comment by jriedl** [comment]
Ja, der Slash muss in diesem Zusammenhang "escaped" werden, deshalb das "\".

**Comment by relhei** [comment]
Alles klar. Danke!
