### ISSUE TITLE
Autosuggest vervollständigt Autorennamen nicht korrekt

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#1186]
Wenn man auf Suchaspekt "Autor" einschränkt und im Suchschlitz den Namen "Kleine, " eintippt, schlägt Autosuggest nur Autorennamen "Klein, xxx" vor. 
![grafik](https://user-images.githubusercontent.com/25769591/80940954-6a5f2600-8de1-11ea-8ce0-1c7e311f3b92.png)

Gesucht ist: "Kleine, Christoph"
Wenn man nur "Kleine" eintippt, kommt dieser Name zuerst, wenn man "Kleine, C" eintippt, wird auch korrekt vorgeschlagen, aber eben nicht bei dem eingangs geschilderten Tippverhalten. Lässt sich das beheben?

**Comment by jriedl** [comment]
Auf ptah.

**Comment by relhei** [comment]
Sieht jetzt definitv besser aus, aber es werden auch noch Namen gezeigt, die nichts mit dem eingegebenen Wortanfang zu tun haben:
![grafik](https://user-images.githubusercontent.com/25769591/81528034-13ff6380-935c-11ea-831d-e47ab390fbee.png)
Wenn sich das nicht einfach beheben lässt, wäre das in der jetzigen Form m. E. aber akzeptabel.

**Comment by jriedl** [comment]
Leider kann man da im Prinzip immer nur rumschieben - es werden sich immer Anwendungsfälle finden lassen, bei denen es mit dieser Einstellung nicht passt. Habe den autor2 wieder runtergeranked, um damit den Effekt, dass die Vorschlagfunktion auf den Hauptautor geht wieder etwas einzudämmen.

**Comment by relhei** [comment]
Ja, klar. Für das Beispiel sieht es jetzt gut aus. Hab noch ein paar mehr Namen getestet, da gab es auch keine Probleme. Vielen Dank!
