### ISSUE TITLE
Datensätze nicht aktualisiert?

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#1198]
Ein am 30.03.2020 korrigierter Datensatz hat noch den Stand 02.07.2019.
Wurde die Korrektur nicht ausgeliefert oder die Korrekturlieferung nicht umgesetzt?

Korrektur am 30.03.2020:
Löschung von 655 $a DA3:
655 |a Aufsatzsammlung |a **DA3** |0 (DE-588)4143413-4 |0 (DE-627)105605727 |0 (DE-576)209726091 |2 gnd-content

Das Feld ist unverändert im IxTheo

https://ixtheo.de/Record/1001221052#details
![Korr](https://user-images.githubusercontent.com/17004223/82021904-04e62180-968c-11ea-836f-a0e2a04ca740.JPG)

**Comment by jriedl** [comment]
Eine PPN 1001221052 ist im Web-Frontend des SWB nicht (mehr) zu finden. Stattdessen gibt es für diesen Titel die PPN 1564474143 (auch im IxTheo vorhanden), diese hat allerdings in der K10+-Ansicht das Änderungsdatum 14.03.19: 005 $020190314081816.0. Keine der PPNs taucht in einem Teilabzug seit dem 30.3. oder den uns vorliegenden Löschlisten auf.

**Comment by IxTheoKm** [comment]
Es handelt sich um Dubletten, die beide vorhanden sein müssen. Ich finde auch beide:
https://ixtheo.de/Record/1001221052#details
https://ixtheo.de/Record/1564474143#details

Titel PPN 1564474143 ist eine SWB-Aufnahme, die mit der SSG-Nummer ausgezeichnet ist und ausgeliefert wurde.
PPN 1001221052 hat in der WinIBW einen mit SSG-Nummer ausgezeichneten Aufsatz PPN 1662874189 und wurde deswegen ausgeliefert

**Comment by jriedl** [comment]
Ja, im IxTheo sind sie natürlich zu finden, aber in der Weboberfläche des BSZ (http://swb.bsz-bw.de/) liefert eine PPN-Suche nach 1001221052 keine Ergebnisse und eine Suche nach 
'"Frau Merkel hat mich eingeladen"!?' genau einen Treffer mit PPN 1564474143.

**Comment by IxTheoKm** [comment]
In der Produktionsdatenbank ist er noch mit 5 Exemplardaten vorhanden:
![Datensatz](https://user-images.githubusercontent.com/17004223/82823067-2a9ed200-9ea7-11ea-953c-37e108e8b9a6.JPG)

**Comment by jriedl** [comment]
Anfrage beim BSZ läuft.

**Comment by IxTheoKm** [comment]
Ich gehe davon aus, dass dieser Titel nicht im SWB nachgewiesen wird, weil er nur GBV-Bestandsdaten hat. Im GBV-Katalog ist er vorhanden:
https://wiki.bsz-bw.de/display/SWB/SWB-+und+K10Plus-Online-Kataloge
https://kxp.k10plus.de/

**Comment by IxTheoKm** [comment]
Siehe auch https://opac.k10plus.de/DB=2.299/

Hier sind beide Datensätze nachgewiesen

**Comment by IxTheoKm** [comment]
Ein Datensatz wird an den IxTheo ausgeliefert, wenn er 0575 mteo oder 5056 0 oder 1 enthält 
Außerdem werden alle verknüpften übergeordneten Aufnahmen auch ohne diese Selektionskriterien mitgeliefert.
Wenn in z.B. ein Aufsatz mit Selektionskriterien neu erfasst oder korrigiert wird, muss theoretisch in der übergeordneten Aufnahme (Zeitschrift, Sammelwerk) 5056 oder 0575 nicht vorhanden sein. 

Wenn ein Aufsatz _mit_ Selektionskriterien korrgiert wird, kommt automatisch ein übergeordnetes Werk _ohne_ Selektionskriterium mit in die Korrekturlieferung.

Wird aber nur dieser übergeordenete Datensatz korrigiert, muss dort das fehlende Selektionskriterium eingetragen werden, sonst kommt es nicht in die Datenlieferung. Die Korrektur würde erst mit einer neuen Gesamtlieferung ausgeliefert.
