### ISSUE TITLE
Doppelte Ergebnisdarstellung in der Volltextsuche

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#1209]
Das Ergebnis auf pdf-Seite [2] wird zweimal dargestellt. Warum?
https://ptah.ub.uni-tuebingen.de/Search2/Results?hiddenFilters%5B%5D=has_fulltext%3A%221%22&lookfor=konfessionslosigkeit&type=FulltextWithSynonyms&filter%5B%5D=%7Elanguage%3A%22English%22

![Bildschirmfoto 2020-05-27 um 18 28 10](https://user-images.githubusercontent.com/14169098/83046944-04646800-a048-11ea-954b-f1a528f4ccf5.png)

**Comment by thefass** [comment]
dito
![Bildschirmfoto 2020-05-27 um 18 38 50](https://user-images.githubusercontent.com/14169098/83048052-62de1600-a049-11ea-8c4a-e7a1f46c42ee.png)

**Comment by jriedl** [comment]
Auf ptah.

**Comment by thefass** [comment]
OK
