### ISSUE TITLE
Katalog Browsen: Anzeige "Datensätze ansehen" bitte anpassen

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#121]
Im Modus "Katalog Browsen" wird derzeit "Datensätze ansehen" optisch anders dargestellt als auf RelBib. Wenn möglich, bitte wieder zu der Darstellungsweise wie auf RelBib anpassen.

RelBib:
![grafik](https://user-images.githubusercontent.com/25769591/34252881-a0bf8d7a-e645-11e7-85ca-c1b90226420a.png)

Ptah:
![grafik](https://user-images.githubusercontent.com/25769591/34252858-8bb2ad04-e645-11e7-9ba7-92b9bcf2a6d9.png)

**Comment by mtrojan-ub** [comment]
Die CSS-Klassen im Browse-Template hatten sich mit VuFind 4 geändert und unser Template war noch nicht darauf angepasst. Das wurde jetzt nachgeholt.

Bitte nochmal testen!

**Comment by relhei** [comment]
Passt. Vielen Dank!
