### ISSUE TITLE
Babylonische Sprachverwirrung in der Volltextsuche

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#1210]
Die Suche nach Religionslosigkeit wurde auf Englisch eingeschränkt. Allerdings hat kener der 9 Treffer einen englischen Begriff. Die Sprachfacette eng wurde vergeben, da es in den Werken auch englische Aufsätze gibt. Das ist verwirrend. Gibt es dafür eine Lösung?

https://ptah.ub.uni-tuebingen.de/Search2/Results?hiddenFilters%5B%5D=has_fulltext%3A%221%22&lookfor=konfessionslosigkeit&type=FulltextWithSynonyms&filter%5B%5D=%7Elanguage%3A%22English%22

**Comment by jriedl** [comment]
Wäre es zur Vermeidung von Missverständnissen sinnvoll, die Facette "Sprache" in "Werksprache" umzubenennen?

**Comment by IxTheoKm** [comment]
Wenn es denn eine Änderung geben sollte: 
m.E. spricht man eher von "Dokumentsprache" (zumindest im Regelwerkskontext)

**Comment by thefass** [comment]
Sprache ist halt so schön einfach. Bin mir nicht sicher, ob die Nutzer mit spezielleren Ausdrücken etwas anfagen können.
Wir bleiben jetzt erstmal dabei. Und müssen das Phänomen vielleicht in den Erklärungen aufgreifen
