### ISSUE TITLE
Link zum übergeordneten Werk bei Aufsätzen

### ISSUE THREAD

**Issue by Gazeller** [ubtue/tuefind#1218]
In der Listenanzeige gibt es bei Aufsätzen zwei Links zum übergeordneten Werk. Der eine führ auch tatsächlich dorthin, der zweite aber ins Leere bzw. löst irgendeine andere Suche aus. Beispiel Autor Burhkhard Gladigow
![grafik](https://user-images.githubusercontent.com/16898788/84239370-ad0cd000-aafc-11ea-96ac-7e56cebeebfe.png)

Klick auf "In: Menschenrechte für Menschanaffen" bringt korrektes Ergebnis. -
Klick auf "Veröffentlicht in Menschenrechte für Menschenaffen" ergibt
![grafik](https://user-images.githubusercontent.com/16898788/84239511-e34a4f80-aafc-11ea-914c-959565829b89.png)
 Das gleiche geschieht auch bei den anderen Titeln

**Comment by jriedl** [comment]
Auf ptah.

**Comment by Gazeller** [comment]
Passt! Danke
