### ISSUE TITLE
RSS feed zeigt HTML code

### ISSUE THREAD

**Issue by Gazeller** [ubtue/tuefind#1219]
Suche nach buddhism* dialog* -> Suchergebnis per RSS feed abonnieren bingt diese Ansicht

![grafik](https://user-images.githubusercontent.com/16898788/84486772-23950380-ac9e-11ea-8c50-8d57bef6e6c6.png)

**Comment by mtrojan-ub** [comment]
Sorry, da hatte ich Dich am Telefon wohl falsch verstanden :sweat_smile: Es hat sich so angehört als würde auf der Seite irgendwo mitten im Layout auf einmal ein Schnipsel als HTML-Code auftauchen. In dem Fall ist es aber gewünschtes Verhalten.

Ein RSS Feed ist ja nichts anderes als eine XML Datei. Dass Du den Quelltext angezeigt bekommst liegt daran dass Dein Browser kein RSS unterstützt.

**Comment by Gazeller** [comment]
Okay, dann schließe ich das issue wieder.
Gruß Gaby

-----------------
Dr. Gabriele Zeller
Tel. 29-74030
Zi. H 228 - UB Hauptgebäude

Von: Mario Trojan <notifications@github.com>
Gesendet: Freitag, 12. Juni 2020 13:06
An: ubtue/tuefind <tuefind@noreply.github.com>
Cc: Gazeller <gabriele.zeller@ub.uni-tuebingen.de>; Author <author@noreply.github.com>
Betreff: Re: [ubtue/tuefind] RSS feed zeigt HTML code (#1219)


Sorry, da hatte ich Dich am Telefon wohl falsch verstanden 😅 Es hat sich so angehört als würde auf der Seite irgendwo mitten im Layout auf einmal ein Schnipsel als HTML-Code auftauchen. In dem Fall ist es aber gewünschtes Verhalten.

Ein RSS Feed ist ja nichts anderes als eine XML Datei. Dass Du den Quelltext angezeigt bekommst liegt daran dass Dein Browser kein RSS unterstützt.
