### ISSUE TITLE
Suchfilter: "Unzugewiesen" fehlt zum Teil

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#122]
Auf Ptah erscheint bei manchen Filtern nicht mehr ganz oben "unzugewiesen". In der Thema-Facette gibt es aber auf jeden Fall Titel, die keine Sachschlagwörter enthalten, also "unzugewiesen" sind.
Ptah:
https://134.2.67.9/Search/Results?filter%5B%5D=dewey-tens%3A%22200+-+Religion%22&filter%5B%5D=dewey-hundreds%3A%22200+-+Religion%22&filter%5B%5D=dewey-ones%3A%22290+-+Other+religions%22&type=AllFields&sort=year+asc

Im Vergleich dazu RelBib, bei identischer Suchanfrage:
https://relbib.de/Search/Results?filter[]=dewey-tens:%22200+-+Religion%22&filter[]=dewey-hundreds%3A%22200+-+Religion%22&filter[]=dewey-ones:290+-+Other+religions&sort=dewey-sort

Außerdem - das betrifft aber sowhl Ptah als auch RelBib - ist die rechnerische Logik in der Facette "RelBib-Klassifikation" nicht ganz nachvollziehbar: Bei einer Gesamttrefferzahl von 220 sind 210 unzugewiesen, ein Titel ist zugewiesen (AX)?

![grafik](https://user-images.githubusercontent.com/25769591/34253525-4a34109a-e648-11e7-8470-fc4107e11029.png)

Nur am Rande: Im Unterschied zu RelBib werden die unzugewiesenen Titel im Ptah nicht mehr prozentual, sondern numerisch angegeben. Ist das so gewollt?

**Comment by mtrojan-ub** [comment]
Ich habe die Vermutung, dass durch Änderungen am solrmarc-Mixin vor 2 Monaten bestimmte Solr-Felder nicht mehr mit "[Unassigned]" befüllt werden, wenn sonst keine Werte gefunden wurden.

Beispiel:
topic_facet (bzw. topic_facet_de, topic_facet_en, usw)
PPN: 495356026 (auf ub16 sind die Felder mit "[Unassigned]" befüllt, auf ptah fehlen sie bei diesem Datensatz komplett)
TueLibMixin::getTopicFacetTranslated

@jriedl : Kannst Du Dir das bitte mal anschauen?

**Comment by jriedl** [comment]
Die Schlagwortfacetten enthalten jetzt "Unzugewiesen".

**Comment by relhei** [comment]
Passt. Vielen Dank!
