### ISSUE TITLE
Links in den Volltextsnippets

### ISSUE THREAD

**Issue by jriedl** [ubtue/tuefind#1223]
Es tauchen fehlerhafte interne Links aus der PDF-Konvertierung in den Snippets auf.

**Comment by jriedl** [comment]
Auf ptah. @Gazeller: Bitte noch einmal kurz überprüfen.

**Comment by Gazeller** [comment]
Beispiel autor: Kleine, Christoph - Volltexte durchsuchen "Pluralismus" bringt richtige Treffer, aber unvermittelt eine stark vergrößerte Zeile
![grafik](https://user-images.githubusercontent.com/16898788/84665045-ac6ea200-af1f-11ea-9dca-34fcb022236f.png)

**Comment by jriedl** [comment]
Das ist offenbar die Titelseite - insofern erscheint das plausibel.
