### ISSUE TITLE
ungewöhnliche Darstellung der Volltextergebnisse

### ISSUE THREAD

**Issue by AleAprile** [ubtue/tuefind#1225]
Bei folgender Abfrage: https://ptah.ub.uni-tuebingen.de/Search2/Results?lookfor=modernismus&type=FulltextOnly&hiddenFilters%5B%5D=has_fulltext%3A1&limit=20&botprotect= werden  drei  Textabschnitte ein wenig ungewöhlich angezeigt. Siehe Treffer Nr. 5, 7 und 14.
Suche ich bei allen drei immer nach "modernismus", dieses mal in der Volltitelanzeige, bekomme ich dieselbe fehlerhafte Darstellung des Textes. Hier ein Beispiel von 7:
Woran liegt es? An der Vorlage oder an der Aufbereitung des Volltextes?
![Screenshot_2020-06-16 Beschreibung Der Modernismus als Gefährdung des christlichen Glaubens](https://user-images.githubusercontent.com/41292389/84785136-697a0080-afeb-11ea-8a94-d86b54c07cc7.png).

**Comment by jriedl** [comment]
Das ist ein OCR-Problem. Die zugrundeliegenden Texte sind Scans ohne eingebetteten Text. Bei Betrachtung der verlinkten Inhaltsverzeichnisse erkennt man, dass das für die Textextraktion verwendete Programm _tesseract_ die Trennungspunkte nicht korrekt zuordnen kann und wilde Buchstabenkombinationen einfügt. Ob sich hierfür eine befriedigende Lösung finden lässt, ist momentan offen.

**Comment by AleAprile** [comment]
Ok, ich verstehe. 
Die schlechte OCR-Erfassung führt auch dazu, dass  das Inhaltsverzeichnis sehr unstrukturiert anzegeigt wird und mithin die Zuordnung des gesuchten Wortes in dem hinterlegten Volltext sehr mühsam erfolgen kann. Bei den anderen Inhaltsverzeichnissen lässt sich ziemlich schnell erkennen, auf welcher Seite oder in welchem Kapitel das gesuchte Stichwort vorkommt, was sehr gut ist.

**Comment by jriedl** [comment]
Umgesetzt wie besprochen.
