### ISSUE TITLE
Volltextsuche freigeschaltet?

### ISSUE THREAD

**Issue by AleAprile** [ubtue/tuefind#1227]
Bei folgendem Record ist eine Volltextsuche schon möglich: https://www.ixtheo.de/Record/024108936  
und funktioniert auch sehr gut. Ich frage mich aber, ob es sich nicht um einen Fehler handelt. Wir wollten ja diese neue Funktion intern weiter testen.

**Comment by jriedl** [comment]
Vgl. Benachrichtigung über die IxTheo-Mailingliste vom 7.5., 10:50.
