### ISSUE TITLE
Katalog Browsen: "unassigned" statt "unzugewiesen"

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#123]
Beim  Katalog Browsen steht an mehereren Stellen in der deutschen Version noch "unassigned" statt unzugewiesen. Bsp.:
![grafik](https://user-images.githubusercontent.com/25769591/34254519-ce76b868-e64c-11e7-85f6-329a776e665e.png)

https://134.2.67.9/Browse/Publisher?findby=relbib-classification&category=&query=%22VA%22&query_field=relbib_notation_facet&facet_field=publisher_facet

Das betrifft sowohl RelBib als auch Ptah.

**Comment by relhei** [comment]
Das Problem tritt noch auf, hier z. B.:
https://134.2.67.9/Browse/Topic?findby=publisher&query_field=topic_facet
![grafik](https://user-images.githubusercontent.com/25769591/34380065-187474c6-eaff-11e7-8936-4e4a85e56e2a.png)

**Comment by relhei** [comment]
Passt. Vielen Dank!

**Comment by IxTheoKm** [comment]
Auch hier steht wieder "Unassigned" statt "Unzugewiesen".
