### ISSUE TITLE
abr:redo - ein Titel fehlt

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#1240]
Die Sammlung des Leipziger Kooperationspartners Archiv mit Dokumentatiopnsstelle "Religiöser und weltanschaulicher Pluralismus" hat mit der Katalogisierung des monografischen Bestands in K10+ begonnen. De Sammlung lässt sich mit dem Abrufzeichen redo (abr:redo) in RelBib aufrufen. Bei Gegenprobe in der WinIBW habe ich einen Treffer mehr erhalten, obwohl die Felder ganz gleich belegt sind. PICA: 0575 redo = Marc 935 $aredo

WinIBW: 
![grafik](https://user-images.githubusercontent.com/25769591/86232833-d5846900-bb94-11ea-8956-581bee366492.png)

RelBib:
https://www.relbib.de/Record/1608151042#details

Das Beispiel zeigt, dass aus irgend einem Grund bei der Einspielung in RelBib das Feld 935 verloren gegangen ist. Bei den anderen beiden Titeln ist es allerdings da, z. B. hier:

https://www.relbib.de/Record/1698549032#details

Bitte prüfen und 935 einfügen!

**Comment by ruschein** [comment]
Wir haben den Datensatz nicht mit der PPN 05342932X.  Das hat also nichts mit einem fehlenden 935er Feld zu tun.

**Comment by IxTheoKm** [comment]
Der Datensatz hat K10plus-PPN 1608151042 (mit SWB-PPN 05342932X).
In Relbib ist er mit Datenstand 005 20171213... vohanden, im K10plus aber mit 005 20200519 ...
Das heißt, die Ergänzung von redo ist nicht angekommen.

**Comment by IxTheoKm** [comment]
Datensatz PPN 1698549032 wurde vom Archiv ganz neu katalogisiert, also nicht nur das Abrufzeichen redo in einem vorhandenen Satz ergänzt.

**Comment by ruschein** [comment]
Also ich finde mittlerweile die PPN 1698549032 in der Trefferliste von abr:redo.  D.h., wir werten 935 für "abr" schon aus.  Ich vermute, da gibt es keinen Handlungsbedarf für die IT.

**Comment by relhei** [comment]
Nein, das Problem ist immer noch da. Es fehlt PPN 1608151042.

**Comment by ruschein** [comment]
@relhei Wir haben den Datensatz ohne 935 vom BSZ bekommen.  Vermutlich haben wir das Update nicht bekommen.  In den nächsten Wochen sollten wir einen neuen Komplettabzug erhalten.  Damit dürfte dann das Problem behoben sein.

**Comment by IxTheoKm** [comment]
@relhei Jetzt sind alle 16 Titel in RelBib mit redo nachgewiesen, auch PPN 1608151042.
Ich schließe.
