### ISSUE TITLE
Autoren-Familienname verloren gegangen

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#1250]
Bei nicht verknüpftem Autorennamen in 100 und 700 fehlt der Familienname, der aber in den Originaldaten vorhanden ist.
Bei mit Normdaten verknüpften Namen passiert das nicht

Beispiele:
https://www.ixtheo.de/Record/1702856356#details
https://www.ixtheo.de/Record/1703792130#details [100 und 700; mit und ohne Verknüpfung]
https://www.ixtheo.de/Record/1713911272#details [100 und 700]
https://www.ixtheo.de/Record/1713939673#details
https://www.ixtheo.de/Record/1713939649#details

cab a22 4500
001 1702856356
003 DE-627
005 20200709165754.0
007 tu
008 200629s2020 xx ||||| 00| ||ger c
035 $a(DE-627)1702856356
035 $a(DE-599)KXP1702856356
040 $aDE-576$bger$cDE-576$erda
041 $ager
084 $a1$2ssgn
**100 1 $aFasthuber, Eva$eVerfasserIn$4aut**
245 10$aGottes hörender Diener$bBeobachtungen zur literarischen Gestalt von 1Sam 3$cEva Fasthuber

![FamName](https://user-images.githubusercontent.com/17004223/87127109-a73a1400-c28d-11ea-890c-22c65c58c391.JPG)

![FamName2](https://user-images.githubusercontent.com/17004223/87127117-aa350480-c28d-11ea-8bcc-b9919f88fc9a.JPG)

https://www.ixtheo.de/Record/1703792130#details
![FamName3](https://user-images.githubusercontent.com/17004223/87128263-a0140580-c28f-11ea-8a21-7d0a78e2e9a6.JPG)

**Wenn 100 und 700 (unverknüpft) identische Vornamen haben, wird nur _einer_ angezeigt:**

https://www.ixtheo.de/Search/Results?lookfor=id%3A171393955X&type=AllFields&limit=20&botprotect=
https://www.ixtheo.de/Record/171393955X#details

![FamName4](https://user-images.githubusercontent.com/17004223/87128703-5e378f00-c290-11ea-913f-b9fdd8b8a776.JPG)

![FamName5](https://user-images.githubusercontent.com/17004223/87129497-b8851f80-c291-11ea-8523-9e0c2823c3af.JPG)

**Comment by jriedl** [comment]
Offenbar Folge von Änderungen im Zusammenhang mit #874. Durch Entfernung des zusätzlichen `marc_filter`-Parameters derzeit auf ptah und ub16 behoben.

**Comment by ruschein** [comment]
Sollte morgen auf Ptah behoben sein.

**Comment by IxTheoKm** [comment]
Namen sind jetzt wieder vollständig, danke!
