### ISSUE TITLE
Alertmail-Sprache

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#1254]
Die Sprache der Alertmail ist Englisch. Sollte sie nicht der Sprache entsprechen, die im Nutzerkonto eingestellt ist? (Bei mir ist es Deutsch.) Zumindest, wenn sie einer der Sprachen entspricht, die in der Datenbank im Menü angeboten werden.

![Alertmailsprache](https://user-images.githubusercontent.com/17004223/88142346-a42c1580-cbf5-11ea-93db-8fbd17535228.JPG)

**Comment by ruschein** [comment]
Das wurde bisher nicht berücksichtigt.  Es ist natürlich technisch realisierbar aber lohnt sich der Aufwand?  Wir brächten dann auch Übersetzungen für alles außer Deutsch und Englisch.  Um beim Englischen zu bleiben, das klingt für mich nach Overkill!

**Comment by thefass** [comment]
es wäre natürlich schön, aber angesichts der vielen anderen noch anstehenden Aufgaben, können wir mit Englisch bei diesem Service leben. 
DfD
