### ISSUE TITLE
bsbo: wundersame Vermehrung

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#1257]
Wie ist es möglich, dass gestern, 29.07.2020 im IxTheo 16.227 Treffer mit LOK 935 bsbo vorhanden waren, heute aber mit rs:bsbo 16.229 ?

https://ixtheo.de/Search/Results?lookfor=rs%3Absbo&type=AllFields&limit=20&botprotect=

Im K10plus sind es heute weiterhin 16.227.
Kann es sein, dass da Lokal- und/oder Titeldaten gedoppelt wurden?

**Comment by thefass** [comment]
Wir hatten vor langer Zeit einmal Problem mit der Zählung. Kann das erneut sein?

**Comment by jriedl** [comment]
Die folgenden zwei PPNs  finden sich neu in den Abzügen: `1656049554` `1696681871`

**Comment by IxTheoKm** [comment]
An PPN 1656049554 wurden die Lokaldaten von PPN **769133304** umgehängt!
An PPN 769133304 hängen im K10plus **keine Lokaldaten** mit bsbo mehr, im VuFind sind sie aber noch vorhanden:
https://ixtheo.de/Record/769133304#details
![bsbo_LOK](https://user-images.githubusercontent.com/17004223/88911323-fefce700-d25d-11ea-9510-027a10497383.JPG)

Dito bei PPN 1696681871: hierhin wurden Lokaldaten mit bsbo von PPN **820979171** umgehängt.
Im K10plus sind **keine Lokaldaten** mehr an diesem Satz, im VuFind schon:
https://ixtheo.de/Record/820979171#details
![bsbo_LOK2](https://user-images.githubusercontent.com/17004223/88911694-7f234c80-d25e-11ea-83bd-f490f47bffe7.JPG)

Werden die Lokaldaten-Umhängungen später nachvollzogen?
Das kommt laufend bei Dublettenbearbeitungen mit dem Transferbefehl vor.

**Comment by ruschein** [comment]
Diese Probleme könnten etwas mit unserer bisherigen Strategie wie wir mit Updates vom BSZ umgehen.  Das zu verflogen lohnt sich aber nicht, da wir in ca. 2 Wochen auf eine ganz andere Strategie wechseln.  Ich vermute, dass dann so ein Fehler nicht mehr möglich wäre.  Auf Sobek haben wir schon die neue Strategie und auf Path werden wird sie vermutlich am kommenden Dienstag implementiert haben.

**Comment by IxTheoKm** [comment]
Da die Anzahl der Abrufzeichen bsbo nun im K10plus und im IxTheo identisch ist, hat sich dieses Problem  mit der neuen Strategie wohl erledigt. Ich schließe daher
