### ISSUE TITLE
"Bände / Aufsätze anzeigen": ohne Ergebnis

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#1261]
Bei Klick auf "Bände / Aufsätze anzeigen" kommt kein Ergebnis. Hier sind auch keine anhängenden Aufsätze für RelBib markiert worden. Bitte, wenn nichts zum Anzeigen vorhanden ist, die Zeile "Bände / Aufsätze anzeigen" entfernen.
https://www.relbib.de/Record/768576423
![grafik](https://user-images.githubusercontent.com/25769591/89035554-72285b00-d33b-11ea-8a97-538ffbe73df4.png)

https://www.relbib.de/Search/Results?lookfor=superior_ppn:768576423

**Comment by relhei** [comment]
Für dieses Weblog hat sich das Issue erledigt, weil nun Aufsätze mit SSG-Nr. 0 markiert wurden und damit in RelBib angezeigt werden sollten. 
Aber generell: Falls Aufsätze / Bände zwar im K10+ anhängen, aber (noch) nicht für RelBib ausgezeichnet sind, sollte die Zeile "Bände / Aufsätze" auch nicht angezeigt werden.

**Comment by ruschein** [comment]
Sollte jetzt allgemein behoben sein, auf Ptah.

**Comment by ruschein** [comment]
Bitte testen.

**Comment by relhei** [comment]
Funktioniert bei diesem Beispiel noch nicht: 
https://www.relbib.de/Record/16579934X#details

Auch hier kommt wieder die Fehlermeldung bei Klick auf "Bände / Aufsätze anzeigen":
https://www.relbib.de/Search/Results?lookfor=superior_ppn:16579934X

**Comment by ruschein** [comment]
Danke für das Testen, tut es auf Ptah?


Gruß,

Johannes

--
Dr. Johannes Ruscheinski
Universitätsbibliothek Tübingen - IT-Abteilung -
Wilhelmstr. 32, 72074 Tübingen

Tel: +49 7071 29-72820
FAX: +49 7071 29-5069
Email: johannes.ruscheinski@uni-tuebingen.de

 The Sophisticate:  "The world isn't black and white.  No one does pure good or pure bad. It's all gray.  Therefore, no one is better than anyone else."
    The Zetet:  "Knowing only gray, you conclude that all grays are the same shade.  You mock the simplicity of the two-color view, yet you replace it with a one-color view..."
      —Marc Stiegler, David's Sling


________________________________

**Comment by relhei** [comment]
Sorry, hab natürlich nicht auf ptah getestet. Dort funktioniert es. Danke! Damit schließe ich.
