### ISSUE TITLE
Newsfeed-Aggregator: Anpassung der Anzeige

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#1268]
Bitte um Anpassung der Anzeige (Vollansicht) der RelBib-Newsfeeds in Anlehung an den Blog-Aggregator von FID Recht:
https://vifa-recht.de/informieren/blog-aggregator/

1. max. 10 Einträge pro Seite und Einfügen einer Seitennavigationsleiste ober- und unterhalb der gelisteten Blogeinträge
2. kleinere Schriftgröße für Titel der einzelnen Blogbeiträge
3. Liste der aggregierten Blogs auf rechte Seite verschieben, quasi in eine gesonderte Spalte
4. Erklärungstext zu Newsfeedaggregator bleibt unter der Überschrift links und wird auf Spaltenbreite der Blogeinträge komprimiert
![Newsfeedaggregator_Neugestaltung](https://user-images.githubusercontent.com/25769591/89513801-53134880-d7d5-11ea-9682-5cc187ced8b3.JPG)

Vielen Dank!

**Comment by mtrojan-ub** [comment]
Soll dann ein Teil des Texts auch mit nach rechts wandern? (z.B. "aktuell aggregieren wir die folgenden Blogs")

**Comment by relhei** [comment]
Bitte diesen Satz streichen und in der rechten Spalte oberhalb der Liste stattdessen eintragen: "Liste der aggregierten Blogs"

**Comment by mtrojan-ub** [comment]
Ready for testing auf ptah

**Comment by relhei** [comment]
Sieht schon gut aus. Englisch ist ok, Französisch sind wir noch nicht so weit...
Bitte mittelfristig noch die pagination (10 Blogeinträge pro Seite) einbauen.
Vielen Dank!

**Comment by mtrojan-ub** [comment]
Pagination jetzt auch auf ptah

**Comment by relhei** [comment]
Das sieht alles schon sehr gut aus - vielen Dank!
