### ISSUE TITLE
Korrekturen nicht ausgeliefert oder nicht umgesetzt?

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#1280]
Wegen eines fehlenden Abrufzeichens 935 $aGIRA aufgefallen:
https://ixtheo.de/Record/1636476198#details

![GIRA](https://user-images.githubusercontent.com/17004223/91965810-4f5ddd80-ed11-11ea-83f3-ffc494cd326f.JPG)

Der Datensatz hat einen Stand von 05.04.2016, wurde aber 07.08.2020 korrigiert. 
Ebenso wurden am 07.08.2020 lokale Notationen ergänzt, die noch fehlen

cab a22 2 4500
001 46421839X
003 DE-576
005 **20200807**204223.0
007 tu
008 160405s1993 xx ||||| 00| ||ger c
035 $a(DE-627)1636476198
035 $a(DE-576)46421839X
035 $a(DE-599)BSZ46421839X
040 $aDE-576$bger$cDE-576$erakwb
041 $ager
084 $a1$2ssgn
100 1 $aLewek, Antoni$d1940-2010$0(DE-588)103419721$0(DE-627)720801923$0(DE-576)369715594$4aut
245 10$aAlternative Entwürfe einer europäischen Pastoral aus polnischer Sicht
246 1 $iRubrikentitel$aZur Theologie in Europa
264 1$c1993
336 $aText$btxt$2rdacontent
337 $aohne Hilfsmittel zu benutzen$bn$2rdamedia
338 $aBand$bnc$2rdacarrier
591 $aIMD-Felder und 1131 maschinell ergänzt (SWB)
610 27$0(DE-588)16332167-X$0(DE-627)677748531$0(DE-576)354150383$aArchidiocèse$gLuxembourg$bPastorale Biblique Dicoćesaine$2gnd
651 7$0(DE-588)4015701-5$0(DE-627)104289007$0(DE-576)208913092$aEuropa$2gnd
773 08$iIn$aEuropäische Gesellschaft für Katholische Theologie$tBulletin$dMünster : Lit-Verl., 1990$g4(1993), 1, Seite 98-106$w(DE-627)170461661$w(DE-600)1061019-4$w(DE-576)025094378$x0939-3897
889 $w(DE-576)518831345
889 $w(DE-627)1588831345
935 $a**mteo**$a**GIRA**
936 uw$d4$j1993$e1$h98-106
951 $aAR
...
$0936ln$0372044085$aHA
$0936ln$0372053009$aRA
$0936ln$0372053157$aRF
$0936ln$037205319X$aRG

**Comment by IxTheoKm** [comment]
Weiteres Beispiel (eines von vielen aus dem Zweitveröffentlichungsprojekt):
die DOIs, die im Zweitveröffentlichungsprojekt ergänzt wurden, sind nicht angekommen, auf PTAH sind die Korrekturen aber vorhanden.

PPN 1681562464
https://ixtheo.de/Record/1681562464#details
Stand 11.11.2019 ohne DOI

https://ptah.ub.uni-tuebingen.de/Record/1681562464#details
Stand 19.08.2020 mit DOI

**Comment by jriedl** [comment]
Auf ptah offenbar korrekt. Auf ub16 scheinen auch Pipelinetags wie BIB und die STX-Felder zu fehlen. @ruschein Evtl. Zusammenhang mit neuem Lokaldatenhandling?

**Comment by IxTheoKm** [comment]
Die Zweitveröffentlichungen lassen sich leider in manchen Fällen nicht weiter bearbeiten, da dadurch der Link auf die Volltexte fehlt!

**Comment by jriedl** [comment]
Durch Änderungen in der letzten Woche sind Teilabzüge nicht hinzugefügt worden. Er erfolgt jetzt die Erstellung eines neuen Pseudokomplettabzugs, so dass die Problematik voraussichtlich nach dem letzten Import behoben sein sollte.

**Comment by jriedl** [comment]
Scheint behoben.

**Comment by AleAprile** [comment]
Ich kann es bestätigen, zumindest aus meiner Sicht. Die Daten, die wir gestern vermisst haben, sind nun aufrufbar.

**Comment by IxTheoKm** [comment]
https://ixtheo.de/Record/1636476198#details ist ebenfalls vollständig. Vielen Dank, ich schließe.
