### ISSUE TITLE
Indexierung und Anzeige der Sprache des Originals

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#1281]
MARC 041 $h = PICA 1500 $c

Bei Übersetzungen kann neben der Sprache des vorliegenden Textes (041 $a) in MARC **041 $h** auch die Sprache des Originals erfasst werden. 
Da der Text beim vorliegenden Dokument aber nicht in dieser Sprache vorliegt, ist die Indexierung für die Sprachfacette und die Anzeige derzeit nicht korrekt!

Bitte daher 041 $h nicht für die Sprachfacette indexieren!

In der Vollanzeige des Dokuments müssen die Sprachen mit den jeweiligen einleitenden Wendungen angezeigt werden:
**Sprache:** ...
**Sprache des Originals:** ...

Bsp.:
https://ixtheo.de/Search/Results?lookfor=id%3A1587894076&type=AllFields&limit=20&botprotect=
041 **$a**spa
041 **$h**ita

![sprache](https://user-images.githubusercontent.com/17004223/91969301-2a1f9e00-ed16-11ea-9d76-71a471261fd9.JPG)

https://ixtheo.de/Record/1587894076
![sprache2](https://user-images.githubusercontent.com/17004223/91969411-589d7900-ed16-11ea-99e9-c4d510e53e05.JPG)

**Comment by jriedl** [comment]
Wie im FID-Meeting besprochen: Lösung durch Ausschluss von 41$h aus der TueFind-Indizierung. Umgesetzt, sollte nach dem nächsten Import sichtbar sein.

**Comment by AleAprile** [comment]
Sehr gut, danke für die Rückmeldung und die Umsetzung.

**Comment by jriedl** [comment]
Auf ptah.

**Comment by AleAprile** [comment]
Es sieht gut aus. Die Filterung der Ergebnisse nach Sprachen funktioniert deutlich besser.
Von Prio15 auf "schon umgesetzt" ist ein guter Sprung :-).  Erneut vielen Dank. Ich schließe anschließend das Issue.

**Comment by IxTheoKm** [comment]
Unsere Antworten haben sich überschnitten.
Die Indexierung und Anzeige in der Sprachfacette sind korrekt, vielen Dank!

Ich weiß nicht, was im Meeting besprochen wurde: sollte "Sprache des Originals" - wie oben vorgeschlagen - in der Vollanzeige nicht auftauchen?

**Comment by AleAprile** [comment]
Sorry, Frau Kellmeyer. Ich war einfach zu schnell...
Die ursprünglich angedachte Lösung hätte deutlich mehr Zeit in Anspruch genommen als diese hier, wenn ich  das gestrige Gespräch trotz Wirrwarr richtig verstanden habe. Zudem halte ich persönlich diese Lösung für benutzerfreundlicher. Der Hinweis auf eine zweite Sprache würde sicherlich die Nutzer ein wenig verwirren. Nichtsdestotrotz ist der Verweis auf das Original da und anklickbar.

**Comment by IxTheoKm** [comment]
Vielen Dank, dann ist das Issue damit vollständig erledigt. Ich schließe.
