### ISSUE TITLE
Problemanzeige: temporäres Sortierungsproblem

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#1292]
Wenn man auf ptah die Zss "Nederlands archief voor kerkgeschiedenis" nach neueste und älteste sortiert, dann ist das Ergebnis umgekehrt.
siehe Screenshots:
![Bildschirmfoto 2020-09-09 um 10 51 09](https://user-images.githubusercontent.com/14169098/92577724-43cb6300-f28b-11ea-94b3-a852c178520c.png)
![Bildschirmfoto 2020-09-09 um 10 51 22](https://user-images.githubusercontent.com/14169098/92577728-462dbd00-f28b-11ea-83f9-d9eb17a7be8a.png)

Das Problem tritt aber nur temporär auf. Jetzt wird wieder richtig sortiert. Das Verhalten ist irritierend. Gibt es eine Erklärung für ein solch temporäres Verhalten?

**Comment by jriedl** [comment]
Ohne eine Schritt-für-Schritt-Beschreibung, wie der Fehler reproduziert werden kann, kann das leider momentan nicht nachvollzogen werden.

**Comment by thefass** [comment]
Ich wollte das nur mal dokumentieren, weil auch bei mir nun die Sortierung ja wieder richtig ist.
ich hatte folgende Schritte:
Suche nach "Nederlands archief voor kerkgeschiedenis" (und zwar mit Anführungszeichen)
Einschränkung in der Facette auf Zeitschrift
Dann Änderung der Sortierung von Relevanz auf neueste, dann auch älteste.
Wenn ich keine Screenshots gemacht hätte, würde ich selbst zweifeln :-)
