### ISSUE TITLE
IxTheo Notationen 

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#1293]
Nachtrag zu geschlossenem #909 (Suche nach IxTheo Notation funktioniert!)

Bitte 2 Kleinigkeiten korrigieren:
1. Suchaspekt IxTheo Notationen soll in der einfachen Suche und in der erweiterten Suche jeweils in derselben Reihenfolge auftauchen und zwar immer vor dem Suchaspekt DDC Klassifiaktion
2. in der einfachen Suche bei Sprache Deutsch auch "IxTheo Notationen" verwenden wie bei der erweiterten Suche

siehe screenshots:
![ixthnot_issue909_a](https://user-images.githubusercontent.com/14169098/92592005-2d2f0700-f29f-11ea-9bd4-8ef92fa7a14e.jpg)
![ixthnot_issue909](https://user-images.githubusercontent.com/14169098/92592015-30c28e00-f29f-11ea-8fd9-9bd0115872b7.jpg)

**Comment by jriedl** [comment]
Auf ptah.

**Comment by IxTheoKm** [comment]
Passt jetzt, danke!
