### ISSUE TITLE
Zwitter: Zusammenführung der Datensätze von Parallelausgaben

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#1296]
Siehe Dokumentation https://github.com/ubtue/tuefind/wiki/Zwitter

Absprachen mit @thefass und Fragen an @ruschein zur Dokumentation:
[Zwitter_Zusammenführung20200922.pdf](https://github.com/ubtue/tuefind/files/5260371/Zwitter_Zusammenfuhrung20200922.pdf)

Formattabelle Beziehungen von ZDB-Datensätzen (Stand 22.09.2020):
[Zwitter-Auswertung_Tabelle20200922.pdf](https://github.com/ubtue/tuefind/files/5268689/Zwitter-Auswertung_Tabelle20200922.pdf)

Einzelbeispiele siehe Formattabelle und unten separat:

**Comment by IxTheoKm** [comment]
**Beispiel 1:**

PPN 1694497941 (Elektronisch, 22.2019-)
PPN 1689201134 (Gedruckt, 22.2019-)
PPN 183938542 (Gedruckt, Vorgänger 1.1994-21.2017)

**Zusammenführung von PPN 1694497941 und 1689201134:**

**PPN 1694497941**
**776** 08$iErscheint auch als$nDruckausgabe$tQuaderni di storia religiosa medievale$dBologna : Il Mulino, 2019$w(DE-627)**1689201134**$w(DE-600)3007323-6$x1126-9200

**PPN 1689201134**
**776** 08$iErscheint auch als$nOnline-Ausgabe$tQuaderni di storia religiosa medievale$dBologna : Il Mulino, 2019$hOnline-Ressource$w(DE-627)**1694497941**$w(DE-600)3016157-5
_**780**_ 00$iFortsetzung von$tQuaderni di storia religiosa$dCaselle di Sommacampagna : Cierre Edizioni, 1994$w(DE-627)_**183938542**_$w(DE-600)1227601-7$w(DE-576)044357877

_**Keine Zusammenführung mit PPN 183938542**_ 

https://ixtheo.de/Search/Results?lookfor=%22quaderni+di+storia+religiosa+medievale%22&type=AllFields&filter%5B%5D=%7Eformat%3A%22Journal%22

https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=%22quaderni+di+storia+religiosa+medievale%22&type=AllFields&filter%5B%5D=%7Eformat%3A%22Journal%22

**Comment by IxTheoKm** [comment]
**Beispiel 2:**

PPN 860042200 (Elektronische Reprod., 14.1981-42.2010)
PPN 166827401 (Gedruckt, 14.1981-45.2013)
PPN 166755524 (Gedruckt, Vorgänger 1.1968-8.1975)

**Zusammenführung von PPN 860042200 und 166827401:**

**PPN 860042200**
**776** 08$iElektronische Reproduktion von$tAshland theological journal$dAshland, Ohio : Seminary, 1981$w(DE-627)**166827401**$w(DE-600)312137-9$w(DE-576)01528008X$x1044-6494

**PPN 166827401**
**776** 08$iElektronische Reproduktion$tAshland theological journal$d[Erscheinungsort nicht ermittelbar] : BiblicalStudies.org.uk, 2015$hOnline-Ressource$w(DE-627)**860042200**$w(DE-600)2857209-9$w(DE-576)470114983
_**780**_ 00$iVorg.$tAshland theological bulletin$dAshland, Ohio, 1968$w(DE-627)_**166755524**_$w(DE-600)301786-2$w(DE-576)015192148$x0888-2185

_**Keine Zusammenführung mit PPN 166755524**_ 
_**785**_ 00$iForts.$tAshland theological journal$dAshland, Ohio : Seminary, 1981$w(DE-627)_**166827401**_$w(DE-600)312137-9$w(DE-576)01528008X$x1044-6494

https://ixtheo.de/Search/Results?lookfor=%22ashland+theological+journal%22&type=AllFields&filter%5B%5D=%7Eformat%3A%22Journal%22&limit=20&botprotect=

https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=%22ashland+theological+journal%22&type=AllFields&filter%5B%5D=%7Eformat%3A%22Journal%22&limit=20&botprotect=

Stand 11.09.2020:
**Kein zusammengeführter "Zwitter-Satz" trotz Feld 776!**

**Comment by IxTheoKm** [comment]
### **Beispiel 3:**

Analog zu Beispiel 2 Stand 11.09.2020 trotz Feld 776 derzeit keine Zusammenführung der Druckausgabe mit elektronischer Reproduktion:
**PPN 1009605070 und 166519529**

### **Bitte solche Fälle auch zusammenführen!**

https://ixtheo.de/Search/Results?lookfor=didaskalia+revista+faculdade+teologia+lisboa&type=AllFields&filter%5B%5D=%7Eformat%3A%22Journal%22&limit=20&botprotect=

https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=didaskalia+revista+faculdade+teologia+lisboa&type=AllFields&filter%5B%5D=%7Eformat%3A%22Journal%22&limit=20&botprotect=

**Comment by IxTheoKm** [comment]
### **Beispiel 4:**

PPN 233519270 (Gedruckt, 1.1997-2.1998)
PPN 165726288 (Gedruckt, Vorgänger und Fortsetzung, 4.1979-16.1990, 17.2005-21.2009, N.F. 1.2014)

### **Keine Zusammenführung von 780 und 787:**

**PPN 233519270**
_**787**_ 0 $iVorg. u. Forts.$tReinhold-Schneider-Blätter$dPassau : Ralf Schuster Verlag, 1979$w(DE-627)_**165726288**_$w(DE-600)8052-4$w(DE-576)01443363X$x2198-3208

**PPN 165726288**
_**780**_ 00$iFortsetzung von$aReinhold-Schneider-Gesellschaft$tReinhold-Schneider-Gesellschaft e.V., Freiburg$dFreiburg, Br. : Ges., 1977$w(DE-627)_**16572627X**_$w(DE-600)8051-2$w(DE-576)014433621
_**787**_ 0 $i1997 - 1998$tWesen und Widerstand$dPaderborn : Schöningh, 1997$w(DE-627)_**233519270**_$w(DE-600)1392856-9$w(DE-576)060440791$x1436-8641
_**787**_ 08$i14=2 von$tChristlicher Glaube und Literatur$dPaderborn : Bonifatius-Druck-Buch-Verl., 1987$w(DE-627)_**168042398**_$w(DE-600)625245-X$w(DE-576)01824548X$x0934-1846

**Comment by IxTheoKm** [comment]
### **Beispiel 5:**

PPN 872851052 (Gedruckte englische Ausgabe)
PPN 667475753 (Gedruckte deutsche Ausgabe)

### _**Keine Zusammenführung von parallelen Sprachausgaben über 775:**_

**PPN 872851052**
_**775**_ 08$iParallele Sprachausgabe$ndeutsch$t**Religion & Gesellschaft in Ost und West**$dZürich : G2W, 2011$w(DE-627)_**667475753**_$w(DE-600)2626109-1$w(DE-576)350044155$x0254-4377

**PPN 667475753**
**_775_** 08$iParallele Sprachausgabe$nenglisch$t**Religion & society in East and West**$dZürich : Institut G2W, 2016$hBände$w(DE-627)**_872851052_**$w(DE-600)2875244-2$w(DE-576)479971994
**776** 08$iOnline-Ausg.$t**Religion & Gesellschaft in Ost und West**$dZürich : G2W, 1972$hOnline-Ressource$w(DE-627)**750090049**$w(DE-600)2720492-3$w(DE-576)38377313X
**_780_** 00$iVorg.$aG2W - Ökumenisches Forum für Glauben, Religion und Gesellschaft in Ost und West$t**G2W**$dZürich : G2W, 2008$w(DE-627)**_572415508_**$w(DE-600)2437832-X$w(DE-576)284442232$x0254-4377

[Ist Nachfolgezeitschrift von zwei Vorgängern, die alle drei _zusammen_ elektronisch publiziert werden; siehe Beispiel 6:]

**Comment by IxTheoKm** [comment]
### **Beispiel 6:**

### **Was passiert, wenn die gedruckte Ausgabe aus _MEHREREN_ Datensätzen (Vorgänger/Nachfolger mit unterschiedlichen Titeln) besteht, die NICHT zusammengeführt werden, aber nur _EINE_ elektronische Ausgabe parallel zu diesen gesplitteten gedruckten Ausgaben vorliegt?**


PPN 667475753\*** (Gedruckte deutsche Ausgabe) 
[ist Nachfolgezeitschrift von zwei Vorgängern, die alle drei _zusammen_ elektronisch publiziert werden:]

### **Zusammenführung von elektronischer und gedruckter Ausgabe über 776.**
PPN **750090049** (Deutsche Ausgabe, Elektronisch 1972-)
PPN 167416766 (Gedruckte deutsche Ausgabe 1.1973-36.2008,6)
PPN 572415508 (Gedruckte Deutsche Ausgabe 36.2008,7/8-39.2011,7/8)
PPN 667475753\*** (Gedruckte Deutsche Ausgabe 39.2011,9-)

**PPN 750090049**
**776** 08$iDruckausg. bis 36.2008,2$aGlaube in der 2. Welt$t**Glaube in der 2. Welt**$dZürich : G2W, 1973$w(DE-627)**167416766**$w(DE-600)518999-8$w(DE-576)015708063$x0254-4377
**776** 08$iDruckausg. 36.2008,7/8 - 39.2011,7/8$aG2W - Ökumenisches Forum für Glauben, Religion und Gesellschaft in Ost und West$t**G2W**$dZürich : G2W, 2008$w(DE-627)572415508$w(DE-600)2437832-X$w(DE-576)284442232$x0254-4377
**776** 08$iDruckausg. ab 39.2011,9$t**Religion & Gesellschaft in Ost und West**$dZürich : G2W, 2011$w(DE-627)**667475753**$w(DE-600)2626109-1$w(DE-576)350044155$x0254-4377
856 40$uhttps://www.g2w.eu/zeitschrift/rgow-archiv$xVerlag

**PPN 667475753**\***
**_775_** 08$iParallele Sprachausgabe$nenglisch$t**Religion & society in East and West**$dZürich : Institut G2W, 2016$hBände$w(DE-627)**_872851052_**$w(DE-600)2875244-2$w(DE-576)479971994
**776** 08$iOnline-Ausg.$t**Religion & Gesellschaft in Ost und West**$dZürich : G2W, 1972$hOnline-Ressource$w(DE-627)**750090049**$w(DE-600)2720492-3$w(DE-576)38377313X
**_780_** 00$iVorg.$aG2W - Ökumenisches Forum für Glauben, Religion und Gesellschaft in Ost und West$t**G2W**$dZürich : G2W, 2008$w(DE-627)**_572415508_**$w(DE-600)2437832-X$w(DE-576)284442232$x0254-4377

https://ixtheo.de/Search/Results?lookfor=id%3A872851052+OR+id%3A667475753+OR+id%3A750090049+OR+id%3A167416766+OR+id%3A572415508+&type=AllFields&limit=20&botprotect=

https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=ids%3A872851052+OR+ids%3A667475753+OR+ids%3A750090049+OR+ids%3A167416766+OR+ids%3A572415508&type=AllFields&limit=20&botprotect=

Stand: 11.09.2020:
### **Derzeit zusammengeführter "Zwitter-Satz" einschl. Vorgänger und Nachfolger:**
https://ptah.ub.uni-tuebingen.de/Record/750090049

![Zwitter20200911](https://user-images.githubusercontent.com/17004223/92930331-34dae100-f442-11ea-9d86-1e2156992168.JPG)

**Comment by IxTheoKm** [comment]
### **Grundsätzliche Problematik zu 780/785/787 "Vorgänger/Nachfolger/Zwischenzeitlich erschienen":**
4244 |f|
4244 |s|
4244 |z|

Ursprünglich war vorgesehen, auch 780 und 785 zusammenzuführen. So ist es derzeit auf PTAH eingerichtet.
Nach RDA werden auch Schlagwortsätze für Werktitel so behandelt und der neueste Titel als bevorzugter Titel verwendet.

**Vorschlag wegen der Problematik von Beispiel 6 daher: 
Wie ursprünglich vorgesehen 780 und 785 weiter einbeziehen.**
Lediglich 787 ausnehmen, da dieses Feld in RAk und RDA unterschiedliche Inhalte transportieren, die aus RDA-Aufnahmen _nicht_ einbezogen werden dürfen!

**Comment by ruschein** [comment]
@IxTheoKm Es gibt zur Zeit keine Datensätze vom BSZ, die ein Feld 260 oder das Unterfeld 022$2 enthalten. So wie ich meinen Text im Wiki verstehe würde 022$9 von uns eventuell erzeugt, das ist aber anscheinend nie passiert. 775er Felder wurden anscheinend nie zusammengeführt.  Bei "Derzeitiger Stand auf Path", haben Sie mir da bitte jeweils mindestens einen PPN als Beispiel?

**Comment by ruschein** [comment]
@IxTheoKm Haben Sie eine Beispiel von zwei PPNs die über 780 und 785 verlinkt sind und im IxTheo vorkommen?

**Comment by IxTheoKm** [comment]
@ruschein Je zwei Beispiele für "Derzeitiger Stand auf PTAH", darin auch Beispiele mit 780 und 785

### **Beispiele PTAH Stand 16.09.2020)**

### **Keine Zusammenführung von 776** (Link s.a. unter Beispiel 2: Ashland theological bulletin):

a)
- PPN 860042200
- PPN 166827401

b)

- PPN 1009605070
- PPN 166519529

### **Fehlende Verlinkungen zu Beziehungen in den Zwitteraufnahmen** (Link s.a. unter Beispiel 1: Quaderni di storia religiosa medievale)

a)
- PPN 1694497941 zusammengeführt mit
- PPN 1689201134 [hat eine Beziehung in 780 mit PPN 183938542, die hier fehlt]
- PPN 183938542 [hat eine Beziehung in 785 mit PPN 1689201134, die nicht funktioniert - wohl weil sie mit 1694497941 zusammengeführt wurde]

b)
- PPN 1725177439 [hat eine Beziehung in 780 mit PPN 517160005, die hier fehlt] zusammengeführt mit
- PPN 1725176564 [hat eine Beziehung in 780 mit PPN 166616605, die hier fehlt]

**Weitere Beispiele mit 780 und 785:** 

- PPN 821522280 [hat Beziehungen in 780 mit PPN 357169565 und PPN 826105785, darin jeweils 785]


### **Die Unterscheidung von Druck-Ausgabe und elektronischer Ausgabe erfolgt nicht**:
[_rot unterstrichen = elektronische Ausgabe; nur gelb markiert = Druckausgabe; "veröffentlicht:" ist allerdings in beiden Fällen in MARC identisch, hier unterschiedlich aufgeführt, was ich nicht verstehe_]

a)
- PPN 1694469573 zusammengeführt mit
- PPN 1694469565

![Zwitter20200916](https://user-images.githubusercontent.com/17004223/93306012-9662cd00-f7ff-11ea-9f42-f34fa2c059dc.JPG)

b)
- PPN 1682186393 zusammengeführt mit
- PPN 129543608

![Zwitter20200916b](https://user-images.githubusercontent.com/17004223/93306609-6831bd00-f800-11ea-8a07-67ee735345f6.JPG)

### **In der „Zwitter-Aufnahme“ werden nur die Lokaldaten der elektronischen Ausgabe angezeigt** (Link s.a. unter Beispiel 1: Quaderni di storia religiosa medievale):

a)
- PPN 1694497941 zusammengeführt mit
- PPN 1689201134

b)

- PPN 881388572 zusammengeführt mit
- PPN 1028846045

**Comment by ruschein** [comment]
@IxTheoKm Ich bin etwas verwirrt.  Sie haben Beispiele wo Sie monieren, dass Verlinkungen via 785er-Felder nicht ausgewertet werden.  Im PDF-Document steht aber "MARC 780/785/787 = PICA 4244 Vorgänger/Nachfolger werden nicht zusammengeführt."  Ein Beispiel ist der Datensatz mit der PPN 183938542.

**Comment by ruschein** [comment]
@IxTheoKm Sollen Verknüpfungen über 787 überhaupt berücksichtigt werden?  Hier sind die häufigsten Einträge in 787$i:
<code>
163299 Rezension von
  81529 Rezension
   8782 Rezensiert in
   7287 Bezugnahme auf
   1618 Kritik in
   1513 Kritik von
    650 Einzelne Bd. zugl. Bd. von
    482 Vorg. u. Forts.
    297 Erweitert durch
    156 In Beziehung stehende Ressource
    124 Zugl. einzelne Bd. von
    122 Zugl. Bd. von
    114 Kommentar zu
    105 Kritisiert in
     90 Kommentar in
     86 Errata zu
     83 Errata
     74 Rezension:
     60 In Beziehung stehendes Werk
     53 Überarbeitung von
     49 1=1 von
     48 Überarbeitet als
     48 Freie Übersetzung von
     43 Ergänzung zu
     36 Gekürzt als
     35 Frei übersetzt als
     34 Kurzfassung von
     33 Ergänzung
     31 Online-Ausg. d. Rezension
     28 5=1 von
     27 4=1 von
     24 Zugl. alle Bd. von
     24 Alle Bd. zugl. Bd. von
     24 3=1 von
     23 8=1 von
     22 Bd. zugl. Bd. von
     22 2=1 von
     21 2=2 von
     21 1=3 von
     21 14=1 von
     19 6=1 von
</code>

**Comment by IxTheoKm** [comment]
Wie besprochen und oben https://github.com/ubtue/tuefind/issues/1296#issuecomment-691166450 vorgeschlagen:
Feld 787 wird ausgenommen!
Nur Vorgänger/Nachfolger aus 780 und 785 werden berücksichtigt.

**Comment by IxTheoKm** [comment]
Test 23.09.2020:
### **Zusammenführung** von Beispiel 1 https://github.com/ubtue/tuefind/issues/1296#issuecomment-691012608 samt Aufsätzen und Bänden **funktioniert**.

### Lokaldaten: 
LOK an der Zwitteraufnahme stammen nur von PPN 183938542.
Die **Lokaldaten** von PPN 1694497941 und PPN 1689201134 **fehlen**, lokale Abrufzeichen sind dadurch nicht selektierbar.

### Anzeige:
Die Unterscheidung durch "Elektronisch", "Druck", oder "Elektronisch/Druck" an den jeweils gekennzeichneten Positionen fehlt

![Zwitter20200923](https://user-images.githubusercontent.com/17004223/94029043-b32d7080-fdbc-11ea-9f22-f2f046e940e5.JPG)

![Zwitter20200923b](https://user-images.githubusercontent.com/17004223/94029056-b6c0f780-fdbc-11ea-929a-a89a03a307e1.JPG)

**Comment by IxTheoKm** [comment]
Test 23.09.2020:

### Zusammenführung von Beispiel 2 https://github.com/ubtue/tuefind/issues/1296#issuecomment-691021328 funktioniert.

Lokaldaten und Anzeige wie bei Beispiel 1 noch nicht umgesetzt.

**Comment by IxTheoKm** [comment]
Test 24.09.2020:

### Nicht-Zusammenführung von Beispiel 4 https://github.com/ubtue/tuefind/issues/1296#issuecomment-691033090 über 787 funktioniert.

**Anzeige** von 780 in PPN 165726288 ist ein anderes Problem, das auch in Nicht-Zwitter-Zeitschriften existiert.
Dafür mache ich ein gesondertes Issue auf:
780 00$iFortsetzung von$aReinhold-Schneider-Gesellschaft$tReinhold-Schneider-Gesellschaft e.V., Freiburg$dFreiburg, Br. : Ges., 1977$w(DE-627)**_16572627X_**$w(DE-600)8051-2$w(DE-576)014433621 **[PPN 16572627X = dangling!]**

**Comment by IxTheoKm** [comment]
Test 24.09.2020:

### Beispiele 5 https://github.com/ubtue/tuefind/issues/1296#issuecomment-691100082 und 6 https://github.com/ubtue/tuefind/issues/1296#issuecomment-691102545:
Nicht-Zusammenführung von 775 und Zusammenführung von 776 und 780/785 funktioniert.

**Comment by IxTheoKm** [comment]
Test 24.09.2020:

ids:1725177439 OR ids:517160005 OR ids:1725176564 OR ids:166616605

https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=ids%3A1725177439+OR+ids%3A517160005+OR+ids%3A1725176564+OR+ids%3A166616605&type=AllFields&limit=20&botprotect=

### Die Datensätze wurden nicht zusammengeführt obwohl sie Beziehungen über 776, 780 und 785 haben

**Comment by IxTheoKm** [comment]
Test 24.09.2020:

ids:881388572 OR ids:1028846045 OR ids:167245333 OR ids:167134272 OR ids:130518581 OR ids:129087661

https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=ids%3A881388572+OR+ids%3A1028846045+OR+ids%3A167245333+OR+ids%3A167134272+OR+ids%3A130518581+OR+ids%3A129087661&type=AllFields&limit=20&botprotect=

### 6 Datensätze korrekt über 776, 780 und 785 zusammengeführt

**Comment by IxTheoKm** [comment]
Test 24.09.2020:

ids:872851052 OR ids:667475753 OR ids:750090049 OR ids:167416766 OR ids:572415508

https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=ids%3A872851052+OR+ids%3A667475753+OR+ids%3A750090049+OR+ids%3A167416766+OR+ids%3A572415508&type=AllFields&limit=20&botprotect=

**Zwitteraufnahme, die mit  PPN 667475753, 572415508 und 167416766 zusammengeführt wurde:**
https://ptah.ub.uni-tuebingen.de/Record/750090049

Korrekte Anzeige des Links zur parallelen Sprachausgabe https://ptah.ub.uni-tuebingen.de/Record/872851052
"Parallele Ausgabe:     Nicht-elektronisch"

**In der parallelen Ausgabe PPN 872851052 fehlt der Link "Parallele Ausgabe:..."** zu PPN 667475753, da diese nun unter PPN 750090049 steckt
https://ptah.ub.uni-tuebingen.de/Record/872851052

![Zwitter20200924](https://user-images.githubusercontent.com/17004223/94154478-34007100-fe7e-11ea-835e-6cbfbf336e89.JPG)

**Comment by IxTheoKm** [comment]
**Problem:**
### Titel und Datensatz der _Vorgängerzeitschrift_ wird als "Haupttitel" verwendet:

id:16675739X OR id:167935348
https://ixtheo.de/Search/Results?lookfor=id%3A16675739X+OR+id%3A167935348&type=AllFields&limit=20&botprotect=

![Zwitter20200925](https://user-images.githubusercontent.com/17004223/94282121-c02e9900-ff4f-11ea-9f8d-341da2232b39.JPG)

ids:16675739X OR ids:167935348
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=ids%3A16675739X+OR+ids%3A167935348&type=AllFields&limit=20&botprotect=

![Zwitter20200925b](https://user-images.githubusercontent.com/17004223/94282300-f0763780-ff4f-11ea-9c7a-1c12af9466c6.JPG)

https://ptah.ub.uni-tuebingen.de/Record/**167935348**

![Zwitter20200925c](https://user-images.githubusercontent.com/17004223/94282447-21ef0300-ff50-11ea-8bed-eeac1781e7a9.JPG)


### Die in MARC 785 verlinkte _Nachfolgezeitschrift_ sollte als Hauptzeitschrift angezeigt werden:
**785** 00$iAufgeg. in$tBibel und Liturgie$dKlosterneuburg : Österr. Kath. Bibelwerk, 1926$w(DE-627)**16675739X**$w(DE-600)302060-5$w(DE-576)01519440X$x0006-064X

**Comment by ruschein** [comment]
> Test 24.09.2020:
> 
> ### Die Datensätze wurden _NICHT_ zusammengeführt obwohl sie Beziehungen über 776, 780 und 785 haben:
> ids:1725177439 OR ids:517160005 OR ids:1725176564 OR ids:166616605
> 
> [ptah.ub.uni-tuebingen.de/Search/Results?lookfor=ids%3A1725177439+OR+ids%3A517160005+OR+ids%3A1725176564+OR+ids%3A166616605&type=AllFields&limit=20&botprotect=](https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=ids%3A1725177439+OR+ids%3A517160005+OR+ids%3A1725176564+OR+ids%3A166616605&type=AllFields&limit=20&botprotect=)
> 
> **Weiteres Beispiel:**
> 
> ids:129487023 OR ids:1733544097
> 
> [ptah.ub.uni-tuebingen.de/Search/Results?lookfor=ids%3A129487023+OR+ids%3A1733544097&type=AllFields&limit=20&botprotect=](https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=ids%3A129487023+OR+ids%3A1733544097&type=AllFields&limit=20&botprotect=)

In beiden Fällen wurde nicht gemergt weil Verweise nicht in unseren Abzügen sind, im ersten Fall fehlt die PPN 166619736 und im zweiten Fall die PPN 104757960X.  Zur zweit mergen wir nur wenn alle Verweise in einer Gruppe existieren.

**Comment by IxTheoKm** [comment]
@thefass Soll es so bleiben, dass Datensätze nur gemerged werden, wenn wirklich **_alle_** Verweise einer Gruppe existieren? 
Für diejenigen Verweise, die nicht im VuFind existieren, habe wir normalerweise auch keine Bände oder Aufsätze selektiert. 
Eigentlich reicht es doch, diejenigen Fälle zusammenzuführen, die im VuFind vorhanden sind.

**Comment by ruschein** [comment]
Ist jetzt so implementiert, dass auch denn gemergt wird wenn manche Verweise nicht in unserem Abzug sind.  Das sollte morgen dann auf Ptah sichtbar sein.

**Comment by ruschein** [comment]
@IxTheoKm Bitte nochmals überprüfen ob ich alle Problem reparieren konnte und/oder ob das jetzt in einem Zustand ist in dem man es in die Produktionssysteme übernehmen kann.  Danke.

**Comment by IxTheoKm** [comment]
@ruschein 
Unterscheidende Hinweise für gedruckte und elektronische Ausgaben sind noch nicht eingefügt.
Das halte ich aber anfangs für noch nicht so gravierend. Das könnte man evtl. später "nachbessern". 
@thefass Wie sehen Sie das?

Was aber gravierend ist und m.E. vor der Übernahme in die Produktionssysteme behoben werden muss:
Die Lokaldaten der zusammengeführten Datensätze gehen leider immer noch verloren.

**Comment by thefass** [comment]
> @ruschein
> Unterscheidende Hinweise für gedruckte und elektronische Ausgaben sind noch nicht eingefügt.
> Das halte ich aber anfangs für noch nicht so gravierend. Das könnte man evtl. später "nachbessern".
> @thefass Wie sehen Sie das?

 das wird vermutlich nur eine Kleinigkeit sein, die auch gleich mit erledigt werden kann. Die gravierenden Punkte müssen aber gelöst sein

**Comment by ruschein** [comment]
> 167935348

@IxTheoKm Sollte jetzt auf Ptah behoben sein.

**Comment by ruschein** [comment]
Können wir das jetzt auf Ub16 übernehemen?

**Comment by IxTheoKm** [comment]
Zu https://github.com/ubtue/tuefind/issues/1296#issuecomment-712906723 
Die Zusammenführung klappt jetzt:
https://ptah.ub.uni-tuebingen.de/Record/167935348 ist jetzt okay. Von daher kann man es jetzt m.E. übernehmen.

Was https://github.com/ubtue/tuefind/issues/1296#issuecomment-713081964 betrifft, müsste @thefass sich äußern. 
Ich meine, es kann auch nachträglich noch erfolgen.

**Comment by IxTheoKm** [comment]
Ich muss mich korrigieren: 

**Die Lokaldaten der zusammengeführten Datensätze gehen leider immer noch verloren.**
Das muss erst behoben sein!

**Comment by IxTheoKm** [comment]
Ich habe mehrere Beispiele überprüft. Wenn ich nichts übersehen habe, sind jetzt alle Lokaldaten vorhanden!

**Comment by ruschein** [comment]
@thefass Ich denke das ist jetzt so wie wir es besprochen hatten.  Bitte werfe mal einen Blick auf die PPN und lass mich wissen ob wir das jetzt in die Production übernehmen können oder nicht.

**Comment by IxTheoKm** [comment]
Weitere Beispiele mit Ergänzung der Erscheinungsverläufe:
https://ptah.ub.uni-tuebingen.de/Record/881388572
https://ptah.ub.uni-tuebingen.de/Record/517160005

**Comment by IxTheoKm** [comment]
Jetzt gibt es leider wieder das alte Problem   :-(

- Es wird nicht der neueste Titel angezeigt.
- Die Titel der zusammengeführten Zeitschriften werden gar nicht angezeigt und sind nicht mehr recherchierbar.

Bsp.
Der Titel "Quaderni di storia religiosa medievale" PPN 1694497941 der zusammengeführten Zeitschrift (Beispiel 1) wird _nicht_ mehr angezeigt und ist nicht recherchierbar. Man findet nur noch "Quaderni di storia religiosa" https://ptah.ub.uni-tuebingen.de/Record/183938542

Siehe
https://github.com/ubtue/tuefind/issues/1296#issuecomment-691012608

Analog das alte Problem:
https://ptah.ub.uni-tuebingen.de/Record/167935348

**Comment by ruschein** [comment]
@IxTheoKm Können Sie sich das bitte nochmal auf Ptah anschauen?  Das alte/neue Problem mit den Titeln ist jetzt hoffentlich wieder behoben.

**Comment by IxTheoKm** [comment]
### Anzeige der **Jahresangaben/Erscheinungsverläufe korrekt**, allerdings wird **264 $b nicht vollständig angezeigt**:

### **Beispiele:**
https://ptah.ub.uni-tuebingen.de/Record/517160005#details

### **Hier bei Herndon, Va. 1985-[2019] und bei Herndon, Va -2013**:

![Zwitter20201104a](https://user-images.githubusercontent.com/17004223/98087870-08ab7180-1e81-11eb-9452-9c5f4ace1277.JPG)

![Zwitter20201104b](https://user-images.githubusercontent.com/17004223/98087891-0ea15280-1e81-11eb-94db-4c897a64632f.JPG)

https://ptah.ub.uni-tuebingen.de/Record/183938542#details

### **Hier beim letzten Eintrag Bologna 2019-**:

![Zwitter20201104c](https://user-images.githubusercontent.com/17004223/98088267-87a0aa00-1e81-11eb-906b-34d627593439.JPG)

![Zwitter20201104d](https://user-images.githubusercontent.com/17004223/98088285-8cfdf480-1e81-11eb-83a5-497bf1dd5d33.JPG)

**Comment by ruschein** [comment]
Ich denke das ist immer so und hat nichts mit dem Zusammenführen von Datensätzen zu tun.  Also sollte uns das auch nicht davon abhalten, das Zusammenführen in unsere Produktionssysteme zu übernehmen.

**Comment by IxTheoKm** [comment]
@thefass 
Die z.T. fehlende Anzeige von Verlagen in der Anzeige ist tatsächlich schon in den einzelnen Aufnahmen so. Wäre also ein eigenes Issue und ist für die Zwitterfrage nicht relevant.

Ich habe vorsichtshalber noch die Lokalsätze, Bände und Aufsätze überprüft: in den getesteten Beispielen okay!
Da jetzt auch das Problem neue/alte Titelfassungen behoben ist, **steht m.E. einer Übernahme nichts mehr im Weg**.

**Comment by thefass** [comment]
Ich schaue heute nachmittag nochmal drüber und mache mir Gedanken wie wir das Kommunizieren und würde dann das ok geben.

**Comment by IxTheoKm** [comment]
Liveschaltung 02.12.2020, darum schließe ich.
