### ISSUE TITLE
Newsfeed-Aggregator - Fehlermeldung

### ISSUE THREAD

**Issue by Gazeller** [ubtue/tuefind#1300]
Der neue Beitrag (heute ganz oben) von Religion Dispatches 
https://religiondispatches.org 
![grafik](https://user-images.githubusercontent.com/16898788/93573188-1cfde280-f997-11ea-8702-bb7cbee4626b.png)

führt zu einer "Not Found" Meldung.

**Comment by mtrojan-ub** [comment]
Ist auf einen Fehler auf C++ Seite im rss_aggregator bzw. XmlWriter zurückzuführen.
@ruschein, kannst Du es Dir bitte anschauen? Details siehe E-Mail.

**Comment by mtrojan-ub** [comment]
Doppeltcodierung der Entites in XmlWriter behoben (wurde auf ptah eingespielt), allerdings scheint es immer noch ein Problem auf PHP-Seite zu geben.

**Comment by mtrojan-ub** [comment]
ready for testing auf ptah

**Comment by Gazeller** [comment]
Klappt jetzt auch auf relbib.de

**Comment by mtrojan-ub** [comment]
Vorsicht, von dem Problem sind nur bestimmte Datensätze betroffen. Das Update war noch gar nicht auf relbib.de eingespielt.

Ursache für das Problem auf PHP-Seite war die Übertragung der Ziel-URL an die Umleitungsseite im base64-Format. Da aber base64 bei manchen URLs Sonderzeichen wie z.B. Slashes "/" beinhaltet, wurde dadurch das Routing beeinträchtigt. Es wurde durch Umstellung auf eine spezielle Art von base62 gelöst in der keine Slashes mehr vorkommen.

Ich habe vorhin ub16 auf den aktuellen Stand gebracht, jetzt sollte es bei allen Links funktionieren
