### ISSUE TITLE
Unvollständige Anzeige von religiösen Würdenträgern als Körperschaften

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#1302]
Religiöse Würdenträger (Bischof, Abt, Rabbi, Synodalpräsident, Mullah, Patriarch, Papst) werden teilweise als körperschaftliche Verfasser, Herausgeber usw. in **MARC 110** oder **MARC 710** (PICA 3100 oder 3110) erfasst.

Entdeckung von @IxGe:
### **Bitte in Kurzanzeige, Vollanzeige und Facette vollständig anzeigen!**

Bsp.:
### https://ptah.ub.uni-tuebingen.de/Record/1729131433#details
110 2 $aKatholische Kirche$bPapst **$g2013- : Franziskus**

![110Verf](https://user-images.githubusercontent.com/17004223/93769268-d9b3a600-fc1a-11ea-859d-618318afb1a5.JPG)

![110Verf2](https://user-images.githubusercontent.com/17004223/93769280-dd472d00-fc1a-11ea-8328-7457df8706ed.JPG)

### https://ptah.ub.uni-tuebingen.de/Record/1555170323#details
110 2 $aKatholische Kirche$bDiözese Rottenburg-Stuttgart$bBischof **$g2000- : Fürst**

![110Verf3](https://user-images.githubusercontent.com/17004223/93769288-e0dab400-fc1a-11ea-8d37-6adafc66c62d.JPG)

![110Verf4](https://user-images.githubusercontent.com/17004223/93769299-e46e3b00-fc1a-11ea-83c5-28cc1afce249.JPG)

**Comment by jriedl** [comment]
Auf ptah.

**Comment by IxTheoKm** [comment]
Unterfeld $g wird jetzt überall mit angezeigt. Vielen Dank.
