### ISSUE TITLE
Fehlende Anzeige von weiteren Körperschaften

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#1303]
### **MARC Feld 710 = PICA 3110 fehlt zum Teil in der Anzeige.**

Bsp.:
### **https://ptah.ub.uni-tuebingen.de/Record/1691055212#details**

![710](https://user-images.githubusercontent.com/17004223/93772203-d7534b00-fc1e-11ea-9f02-99174ac2397f.JPG)

![710d](https://user-images.githubusercontent.com/17004223/93774717-d53ebb80-fc21-11ea-9bd0-a5481ee3c168.JPG)

### **https://ptah.ub.uni-tuebingen.de/Record/1575293048#details**
700 0 $aBenedikt$bXVI.$cPapst$d1927-$eVerfasserIn$0(DE-588)118598546$0(DE-627)324757344$0(DE-576)162664710$4aut
700 1 $aAzzaro, Pierluca$d1970-$eHerausgeberIn$0(DE-588)130546119$0(DE-627)503372382$0(DE-576)250211998$4edt
700 1 $aGranados García, Carlos$d1974-$eHerausgeberIn$0(DE-588)141574992$0(DE-627)629960925$0(DE-576)324791895$4edt
700 0 $aFranziskus$cPapst$d1936-$eSonstige Person, Familie und Körperschaft$0(DE-588)1032307897$0(DE-627)738225649$0(DE-576)379966689$4oth
710 2 $aKatholische Kirche$bPapst$g2005-2013 : Benedikt XVI.$eVerfasserIn$0(DE-588)1113905956$0(DE-627)867965266$0(DE-576)477159931$4aut
710 2 $aKatholische Kirche$bPapst$g2013- : Franziskus$eVerfasserIn eines Vorworts$0(DE-588)1077781172$0(DE-627)837499860$0(DE-576)446671797$4wpr

![grafik](https://user-images.githubusercontent.com/17004223/93773177-12a24980-fc20-11ea-9f7d-240ded85aebf.png)

**Comment by jriedl** [comment]
710 $g ist jetzt ebenfalls Teil der Auswertung (für die beiden Bespieldatensätze ab sofort, für alle anderen nach Abschluss des nächsten Imports morgen früh). Eine Aufnahme von 710 bei vorhandenem 700 geschaltet sich jedoch schwierig - 
das hängt mit dem in VuFind für die Autoren vorhandenen Ansatz für die Feldextraktion zusammen. Es wird hier eine Liste der zu prüfenden Felder und Unterfelder und diese werden übernommen, sobald das Feld existiert und dann die Auswertung beendet. Eine Anpassung würde aufwändige Eingriffe in das Autorenhandling erfordern, weshalb hier wahrscheinlich der Aufwand nicht im Verhältnis zum Nutzen steht.

**Comment by IxTheoKm** [comment]
Ich weiß nicht, worauf sich "Aufwand" und "Nutzen" bezieht (reine _Anzeige_? _Rechercherchierbarkeit_ als Autor?)
Heißt das, sobald es eine Person in MARC 700 gibt, fallen weiterer Körperschaftliche Verfasser oder Beteiligte unter den Tisch?

Bestimmte religiöse Würdenträger _müssen_ seit RDA als Körperschaften erfasst werden (siehe https://github.com/ubtue/tuefind/issues/1302). Dann kann es auch vorkommen, dass Körperschaften und Personen gleichzeitig in einem Datensatz genannt sind.

@IxGe Hast Du weitere Beispiele?

Für die Migration der DaKaR-Daten wurden jedenfalls diese religiösen Würdenträger ausdrücklich als Körperschaften in der GND erfasst, weil das offensichtlich im Kirchenrecht besonders relevant ist.

**Comment by jriedl** [comment]
Eventuell sollten wir das dann noch einmal besprechen.

**Comment by jriedl** [comment]
Besprochene Liste findet sich [hier](https://github.com/ubtue/tuefind/files/5365145/ppns_700_and_710_or_711.txt). Weitere Analyse hat gezeigt, dass das Problem mit einem Rollenfilter bei der Auswahl der Köprerschaftsautoren zusammenhing. Es wurde jetzt "Honoree" und "Issuing body" hinzugefügt. Weitere notwendige Rollen bitte hier im Issue hinterlegen. Die aktuelle Konfiguration findet sich unter [hier](https://github.com/ubtue/tuefind/blob/91218b596d43e8b574d85bac1f617e516bd6d062/local/tuefind/author-classification.ini). Für PPN 169105521hat ein manueller Import stattgefunden, ein Vollimport ist nach Abschluss von Problemen im Zusammenhang mit dem Merging wieder möglich.

**Comment by IxTheoKm** [comment]
Vollständige Liste der Beziehungskennzeichen:
[Liste_Beziehungskennzeichnungen_3010_3110.pdf](https://github.com/ubtue/tuefind/files/5409137/Liste_Beziehungskennzeichnungen_3010_3110.pdf)

**Comment by jriedl** [comment]
Auf ptah.

**Comment by IxTheoKm** [comment]
Perfekt, vielen Dank!
