### ISSUE TITLE
Link auf rezensiertes Werk verursacht einen Fehler

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#1304]
Klick auf den Link in der Zeile "Rezension von" verursacht Fehlermeldung
https://www.ixtheo.de/Record/1450837778
![Bildschirmfoto 2020-09-25 um 08 53 37](https://user-images.githubusercontent.com/14169098/94236086-e8e16f00-ff0c-11ea-8df3-b59e78c13164.png)

**Comment by thefass** [comment]
Mir ist klar geworden, warum der Link nicht funktioniert.
Der verlinkte Datensatz mit PPN 1150593512 ist nicht im IxTheo, da kein Anbzugskriterium im Datensatz vorhanden ist.

**Comment by thefass** [comment]
Das kommt vermutlich öfter vor, gerade bei Rezensionen mit Link auf rezensierte Werke. Müssen wir strategisch in einem Projekt angehen.

**Comment by IxTheoKm** [comment]
Wie in heutigem Meeting besprochen:

@ruschein 
Bitte erstellen Sie eine PPN-Liste von Datensätzen rezensierter Werke, die nicht im IxTheo sind. 
Sie wurden nicht ausgeliefert, weil sie selber keine Selektionskriterien für den IxTheo haben. 
Feld 787 $i **Rezension von**... $w...

Der umgekehrte Fall, fehlende Datensätze von Rezensionen, die im rezensierten Werk verlinkt sind, ist ebenso möglich:
Feld 787 $i **Rezensiert in**... $w [einleitende Wendung in RDA-Aufnahmen mit 040 $e rda]
oder
Feld 787 $i **Rezension**... $w [einleitende Wendung in RAK-Aufnahmen ohne 040 $e rda]

Je nach Umfang dieser Liste soll ein Verfahren besprochen werden, die betreffenden Datensätze entweder mit Selektionskriterien auszuzeichnen oder die Möglichkeit der Auslieferung durch das BSZ zu klären.
Derzeit werden nur übergeordnetet Datensätze automatisch mitgeliefert, auch wenn sie keine IxTheo-Selektionskriterien aufweisen. Siehe https://github.com/ubtue/tuefind/issues/1075#issuecomment-656109781

(Anzeige von Rezensionen s.a. https://github.com/ubtue/tuefind/issues/502)

**Comment by ruschein** [comment]
Mein erster Versuch.
[missing_references.list.zip](https://github.com/ubtue/tuefind/files/5334774/missing_references.list.zip)
Die PPNs vor dem "<-" sind die, die fehlen und die danach sind die, die die fehlenden referenzieren.

**Comment by IxTheoKm** [comment]
Es sind 13.380 Datensätze die fehlen.
Die meisten werden wohl auch für den IxTheo relevant sein.

Es werden auch **Rezensionen zu übergeordneten Werken** dabei sein, die insgesamt nicht unbedingt theologisch sind, aber ausgeliefert wurden, weil mindestens ein untergeordneter Datensatz ein IxTheo-Selektionskriterium hat.
Damit muss man dann leben oder sie beim Wiederaufgreifen mit mtex versehen.

Bsp. (gleich die ersten drei Fälle):

**151255376X** <- **1609893468**:

PPN **1609893468** 
"Bausteine zur Greifswalder Universitätsgeschichte : Vorträge anlässlich des Jubiläums "550 Jahre Universität Greifswald""
[wurde ohne IxTheo-Selektionskriterie geliefert wegen:]

PPN **1508061238** [mit SSG-Nr. 1 in Feld 084]

PPN **151255376X** ist eine Rezension zum übergeordneten Werk PPN 1609893468. 
Diese Rezension wurde nicht geliefert, da sie keine IxTheo-Selektionskriterien hat. Sie ist aber eigentlich auch nicht relevant.

**1504268628** <- **1377203123**
Von 36 Aufsätzen, die mit PPN 1377203123 verknüpft sind, hat einer die SSG-Nr. 1. 
Das übergeordnete, rezensierte Werk ist nicht theologisch.

**1381343627** <- **1188392336**
Von 82 Aufsätzen haben zwei die SSG-Nr. 1. 
Das übergeordnete, rezensierte Werk ist nicht theologisch.

**Comment by ruschein** [comment]
@IxTheoKm Wurde das BSZ benachrichtigt um die Kriterien für unsere Abzüge anzupassen oder werden die referenzierten Werke von uns gepatcht werden?

**Comment by IxTheoKm** [comment]
Nein, die Frage, ob und welche zusätzlichen PPNS aus welchen Feldern ausgeliefert werden sollen, ist noch offen bei @thefass
Siehe https://github.com/ubtue/tuefind/issues/1075#issuecomment-656109781

**Comment by ruschein** [comment]
@thefass Wie soll ich hier weiter verfahren?

**Comment by IxTheoKm** [comment]
Das Grundsatzproblem, dass nicht alle PPNs ausgeliefert werden, die in Querverweisen stecken, ist nicht gelöst. Da hat noch keine Rücksprache mit dem BSZ stattgefunden.
Nur ein Beispiel:
682369020 -> 684761734
Die parallele Online-Ausgabe PPN 684761734 wurde nicht ausgeliefert, weil sie kein IxTheo-Selektionskriterium enthält.

@thefass 
Die Entscheidung ist offen, _welche_ der Querverweise vom BSZ automatisch mitgeliefert werden sollten.
Siehe verlinkte Datei in https://github.com/ubtue/tuefind/issues/1075#issuecomment-656109781

**Comment by thefass** [comment]
> @thefass
> Die Entscheidung ist offen, _welche_ der Querverweise vom BSZ automatisch mitgeliefert werden sollten.
> Siehe verlinkte Datei in [#1075 (comment)](https://github.com/ubtue/tuefind/issues/1075#issuecomment-656109781)

Entscheidung wurde gerade getroffen. In vielen Fällen funktioniert es auch jetzt schon.
