### ISSUE TITLE
Fehlende Quelle in Volltextsuche

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#1312]
Zu diesem Titel gibt es in der Volltextsuche nur die Zusammenfassung, nicht aber den eigentlichen Volltxt:
https://ixtheo.de/Record/1649141629

**Comment by thefass** [comment]
dito: https://www.ixtheo.de/Record/1654576077#fulltextsearch

diese Quelle ist auf unserem DSpace

**Comment by jriedl** [comment]
Auf ptah.

**Comment by thefass** [comment]
ok funkioniert in beiden Fällen
