### ISSUE TITLE
Korrekturen nicht ausgeliefert oder nicht umgesetzt?

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#1321]
Wieder ein Zufallsfund, da ein bereits korrigierter Fehler immer noch im Datensatz vorhanden ist
(vgl. https://github.com/ubtue/tuefind/issues/1280):

https://www.ixtheo.de/Record/1733569731#details
![Korrektur](https://user-images.githubusercontent.com/17004223/96457189-bed75000-121f-11eb-941b-bf2fda82b5cc.JPG)

655  7 $a!104798521!Beispielsammlung$22 gnd-content

**Im K10plus korrigiert am 09.10.2020:**

cam a22 2 4500
001 1733569731
003 DE-627
005 **20201009**164232.0
007 tu
008 200922s1996 gw ||||| 00| ||ger c
...
655 7$aBeispielsammlung$0(DE-588)4144384-6$0(DE-627)104798521$0(DE-576)209733659$2gnd-content

**Comment by jriedl** [comment]
Die Korrektur vom 22.9. findet sich in den Teilabzügen, in weiteren Teilabzügen oder Löschlisten kommt sie nicht vor. Anfrage ans BSZ gestellt. Seltsamerweise findet sich die PPN auch nicht im K10Plus-Verbundkatalog (Eine 1996-Auflage des Werks ist hier nicht vorhanden).

**Comment by IxTheoKm** [comment]
Der Datensatz ist vermutlich nicht im K10plus-OPAC, da er keine Exemplardaten hat.

**Comment by IxTheoKm** [comment]
Weitere Beispiele (am 9.10. korrigiert):
PPN 165710575X 
PPN 1659168341
PPN 104017244X

Nicht-Auslieferung wurde vom BSZ geklärt:

Datensatz PPN 1733569731 hat keine IxTheo-Selektionskriterien. Er wurde ursprünglich ausgeliefert, da er als übergeordnetes Werk mit einem Aufsatz verlinkt ist. Bei Korrektur müsste er selber mit den Selektionskriterien versehen oder auch der Aufsatz nochmals (schein-)korrigiert werden.

Die anderen Datensätze wurden maschinell durch die Verbundzentralen korrigiert. Diese maschinellen Läufe gingen vermutlich nicht in den Datendienst.

Scheinkorrektur ist bei den genannten Fällen jetzt erfolgt. 
Bei einem neuen Gesamtabzug würden solche Korrekturen auch mitgeliefert.
