### ISSUE TITLE
Falsche Anzeige von Funktionsbezeichnungen beteiligter Personen

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#1325]
An Publikationen beteiligte Personen, die nach alten Regelwerksstand _keine_ Funktionsbezeichnungen haben, werden ausgeliefert in 
**Feld 700 $4 oth** ohne Unterfeld $e (=Sonstige Person, Familie und Körperschaft)

Alle diese sonstigen Personen... werden fälschlich mit "(BerichterstatterIn)" angezeigt! 
In manchen Fällen wird trotz $4 oth gar keine Funktion angezeigt. Augenscheinlich immer dann, wenn 700 $d mit Geburtsjahr belegt ist.

**700 $4 oth ohne Unterfeld $e sollte mit "(BeteiligteR)" angezeigt werden.**

@thefass Alternativ käme "(SonstigeR BeteiligteR)" in Frage. 
Das könnte m.E. aber wieder zu Irritationen bei (Haupt-)Beteiligten führen, so lange nach altem Regelwerksstand keine Funktionsbezeichnungen erfasst sind. Ich halte "BeteiligteR" für neutraler.

Bsp.:
https://ixtheo.de/Record/1009870688
![Beteiligte Personen2](https://user-images.githubusercontent.com/17004223/96593090-6cfafc80-12e9-11eb-97ef-b0cda2eebb7c.JPG)

### Vgl. auch https://github.com/ubtue/tuefind/issues/625

**Comment by thefass** [comment]
BeteiligteR reicht aus.

**Comment by jriedl** [comment]
Für PPN 1009870688 ab sofort, für alle weiteren Records nach Abschluss des nächsten Imports auf ptah.

**Comment by IxTheoKm** [comment]
Für die Personen ohne Geburtsjahr stimmt es jetzt. Bei denjenigen mit Geburtsjahr (Unterfeld $d) fehlt die Funktionsbezeichnung.

![BeteiligteR](https://user-images.githubusercontent.com/17004223/103902913-7b440200-50fb-11eb-9faa-3c8f8f7b9809.JPG)

**Comment by jriedl** [comment]
Auf ptah.

**Comment by IxTheoKm** [comment]
Sieht jetzt gut aus, vielen Dank!
