### ISSUE TITLE
Unvollständige Anzeige von weiteren Kongresskörperschaften

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#1326]
Analog zu 111 (Kongresskörperschaften als Verfasser) können auch Konferenzen als beteiligte Körperschaften in **711** vorkommen.

**Die Unterfelder von 711 müssen in der Kurzliste, der Vollanzeige und der Facette Verfasser mit angezeigt werden:**
$e
$n
$g
$d
$c

Vgl.  https://github.com/ubtue/tuefind/issues/1030

Beispiel:
https://ixtheo.de/Record/81566995X#details

710 2 $aKatholische Kirche$bDeutsche Bischofskonferenz$0(DE-588)1001564-4$0(DE-627)102974438$0(DE-576)191141542$4oth
711 2 $aKatholische Kirche **$e** Bischofssynode **$d** 2014 **$c** Rom$0(DE-588)1051357535$0(DE-627)786059648$0(DE-576)406395306$4oth
![Beteiligte Kongresskörperschaft](https://user-images.githubusercontent.com/17004223/96698897-ef3cfc80-138d-11eb-9326-64eb1da46754.JPG)

![Beteiligte Kongresskörperschaft2](https://user-images.githubusercontent.com/17004223/96700182-7474e100-138f-11eb-978e-1c6d6c3c2cd7.JPG)

**Comment by jriedl** [comment]
Auf ptah.

**Comment by IxTheoKm** [comment]
Wird jetzt vollständig angezeigt, danke!
