### ISSUE TITLE
Fehlermeldungen Blog-Aggregator

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#1335]
Bei Klick auf Blogbeiträge oder Blog-Links im RelBib Blogaggregator gibt es reihenweise Fehlermeldungen. Bitte schnell anschauen und nach Möglichkeit beheben.
Beispiel:

https://www.relbib.de/redirect/aHR0cHM6Ly93d3cuY291bnRlcnBvaW50a25vd2xlZGdlLm9yZy9wb2xpdGljYWwtY291bnRlcnBvaW50LWZvci10aGUtZWxlY3Rpb24tYW5kLWJleW9uZC8./relbib-rss-short

**Comment by jriedl** [comment]
Behoben.

**Comment by relhei** [comment]
Vielen Dank!
