### ISSUE TITLE
Platzierung "unzugewiesen" in Facetten

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#1336]
Bei einer Suchanfrage ist aufgefallen, dass in einer Facette  die unzgewiesenen Titel nicht ganz oben in der Sortierung erscheinen, sondern mittendrin. Lässt sich das so optimieren, dass "unzugewiesen" immer oben steht, also nicht in die Sortierung einbezogen wird? Aktuell sieht es etwas merkwürdig aus.
![grafik](https://user-images.githubusercontent.com/25769591/97843526-be43bc80-1ce9-11eb-90cb-c745d0303801.png)

Beispiel Suchanfrage:
https://www.relbib.de/Search/Results?lookfor=space+exploration&type=AllFields&limit=20&botprotect=

**Comment by thefass** [comment]
Sollten wir in dr nächsten IT Sitzung besprechen

**Comment by relhei** [comment]
Geklärt.
