### ISSUE TITLE
Volltextsuche: Anzeige "IxTheo-Klassifikation"

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#1338]
Bei einer Volltextsuche in RelBib wird aktuell in der Facette "IxTheo-Klassifikation" statt "RelBib-Klassifikation" angezeigt. Auch werden hier wieder alle Notationen angezeigt und nicht die RelBib-spezifische Auswahl. Bitte anpassen.
![grafik](https://user-images.githubusercontent.com/25769591/97992601-304bfc80-1de3-11eb-8e37-38fd918e084a.png)

https://www.relbib.de/Search2/Results?lookfor=religious+coping&type=FulltextOnly&hiddenFilters%5B%5D=has_fulltext%3A1&botprotect=#

**Comment by jriedl** [comment]
Auf ptah.

**Comment by relhei** [comment]
Passt. Vielen Dank.
