### ISSUE TITLE
Falsche Anzeige von Verlagen

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#1339]
Bitte unter "Veröffentlicht" in allen Erscheinungsvermerken 264 $b anzeigen.
Ist im u.g. Beispiel in den falschen Erscheinungsvermerk zu "Plainfield..." verschoben.

Bsp.:
https://ixtheo.de/Record/166616605#details

![264_Verlag](https://user-images.githubusercontent.com/17004223/98093309-0dbfef00-1e88-11eb-985f-7e8f7534896c.JPG)

![264_Verlag2](https://user-images.githubusercontent.com/17004223/98093396-2e884480-1e88-11eb-898b-65e4e728fb0e.JPG)

**Comment by mtrojan-ub** [comment]
Beim zweiten Eintrag ist kein $b vorhanden, daher kann auch keins angezeigt werden.

Der Code hierzu stammt zum Großteil aus vufind-org. Dort geht man davon aus, dass es sich bei 264$b um ein Pflichtfeld handelt. Es gibt dazu ein Beispiel im MARC21-Standard, dort wird der Platzalter "[publisher not identified]" verwendet:
https://www.loc.gov/marc/bibliographic/concise/bd264.html

Sollen wir auch einen solchen Platzhalter einfügen, falls keiner vorhanden ist? (Das wäre technisch relativ einfach machbar)

**Comment by IxTheoKm** [comment]
Soweit ich das ZDB-Regelwerk richtig verstehe, muss tatsächlich immer auch ein Verlag in $b stehen. Ich habe die Korrektur beantragt. 

Ich halte es aber für möglich, dass es noch mehr Fälle gibt. Daher fände ich einen Platzhalter für solche Fälle gut, da es technisch einfach machbar ist.

**Comment by mtrojan-ub** [comment]
Kann voraussichtlich ab morgen auf ptah getestet werden

**Comment by IxTheoKm** [comment]
Anzeige ist jetzt mit Platzhalter korrekt (die Korrektur des Satzes steht noch aus).
Vielen Dank, ich schließe.
