### ISSUE TITLE
zwitter: neues Problem

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#1341]

**Comment by thefass** [comment]
Gerade telefonisch mit @ruschein besprochen.
zusammenführung bei 
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=ids%3A1726608921&type=AllFields&limit=500&sort=year+desc%2C+volume_sort+desc%2C+issue_sort+desc%2C+start_page+asc%2C+first_indexed+desc&botprotect=
und
https://www.ixtheo.de/Record/1726608921
klappt noch nicht

**Comment by IxTheoKm** [comment]
@thefass Scheint behoben.
Ist in https://ptah.ub.uni-tuebingen.de/Record/828842965 aufgeführt und recherchierbar:
![Zwitter20201106](https://user-images.githubusercontent.com/17004223/98359622-cfae0100-2028-11eb-907e-974d7c7446ac.JPG)

![Zwitter20201106b](https://user-images.githubusercontent.com/17004223/98359804-0f74e880-2029-11eb-8c2a-00e1f14b3a34.JPG)

**Comment by thefass** [comment]
nein noch nicht. Das Problem besteht darin, dass die aktuelle zss = Zeitschrift für Theologie und Philosophie nicht der Gewinner ist.

**Comment by ruschein** [comment]
Auf Path

**Comment by IxTheoKm** [comment]
Die aktuelle Zeitschrift Zeitschrift für Theologie und Philosophie ist jetzt Gewinner:
https://ptah.ub.uni-tuebingen.de/Record/828842965

**Nochmal neues Problem:**
Ich kann mit "ids" jetzt nicht mehr nach den PPNs der anderen Zeitschriften recherchieren.
![Zwitter20201111](https://user-images.githubusercontent.com/17004223/98794825-ca2a2f80-2409-11eb-9ab3-2d762e40a658.JPG)

**Comment by ruschein** [comment]
Das Problem scheint auf Ptah gelöst zu sein.   Falls es sonst keine schwerwiegenden Problem gibt würde ich das Zusammenführen jetzt auf unser Produktionssystem übernehmen.

**Comment by IxTheoKm** [comment]
Jetzt sind alle PPNs mit ids bzw. "Gewinner-PPN" mit id und ids recherchierbar.

@thefass Geben Sie den Startschuss?

**Comment by IxTheoKm** [comment]
Ich trau mich fast nicht...

Wenn die die **180** Bände mit den Verknüpfungen mit K10plus vergleiche, fehlen einige in der zusammengeführten Aufnahme.
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=superior_ppn%3A828842965&type=AllFields&filter%5B%5D=%7Eformat%3A%22Book%22

Es fehlen 4 PPNs:
1335978062
1376791153
1376791757
1445655950

**Comment by IxTheoKm** [comment]
@ruschein 
Ergänzend zur telefonischen Klärung hier ein paar weitere Beispiele für Bandsätze die parallel in zwei Zeitschriften/Reihen erschienen sind (nicht unbedingt "Zwitter"-Kandidaten, aber das Problem ist ja auch für Nicht-Zwitter relevant):
PPN 1128091798
PPN 1348358068 
PPN 472318659
PPN 361648286

Transport außer in MARC 773, 830 auch in 810.

Falls erforderlich, mache ich ein eigenes Issue auf!

**Comment by ruschein** [comment]
Guten Morgen, Frau Kellmeyer,


ich denke schon, dass wir da ein neues Issue benötigen.

Danke für die Recherche.


VG,

Johannes Ruscheinksi

--
Dr. Johannes Ruscheinski
Universitätsbibliothek Tübingen - IT-Abteilung -
Wilhelmstr. 32, 72074 Tübingen

Tel: +49 7071 29-72820
FAX: +49 7071 29-5069
Email: johannes.ruscheinski@uni-tuebingen.de

 The Sophisticate:  "The world isn't black and white.  No one does pure good or pure bad. It's all gray.  Therefore, no one is better than anyone else."
    The Zetet:  "Knowing only gray, you conclude that all grays are the same shade.  You mock the simplicity of the two-color view, yet you replace it with a one-color view..."
      —Marc Stiegler, David's Sling


________________________________

**Comment by thefass** [comment]
Zwitter ist ja zurückgestellt, weil wir schauen wollen, was VuFind 7.1. dazu an Board Mitteln mitbringt
