### ISSUE TITLE
Matomo-Tracking für Volltextsuche

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#1342]
Wie beim FID-Meeting am 3.11. besprochen sollen Aufrufe für die Volltextsuche separat neben "basic" und "advanced" als "fulltext" gezählt werden.

**Comment by mtrojan-ub** [comment]
... ist experimentell auf ptah aktiviert

![grafik](https://user-images.githubusercontent.com/26873381/99362097-55e10780-28b3-11eb-8fee-4284f90de9ff.png)

![grafik](https://user-images.githubusercontent.com/26873381/99362167-6c875e80-28b3-11eb-80ce-85de7f4842f0.png)

**Comment by mtrojan-ub** [comment]
@AleAprile wie besprochen im FID Meeting am Di wolltest Du Dir ja anschauen ob die Auswertung passt, falls ja bitte auch diesen Issue schließen.

**Comment by thefass** [comment]
@mtrojan-ub Kannst du bitte den Pfad in Matomo angeben, wo man die Search Categories und Custom variable value findet.

**Comment by mtrojan-ub** [comment]
Visitors => Custom Variables => SearchType
