### ISSUE TITLE
Abweichende Treffermenge bei thematischem Browsen

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#1351]
Wenn ich im Modus "Thema browsen" den Begriff "Asia" eingebe, erhalte ich neben dem weiter unten aufgeführten Schlagwort "Asien" die Anzeige 53 Treffer:
![grafik](https://user-images.githubusercontent.com/25769591/100601603-14187e00-3303-11eb-876d-300eb1816bdf.png)
Bei Klick auf "Datensätze ansehen" erhalte ich allerdings eine Trefferliste mit 182 Titeln:
https://www.relbib.de/Search/Results?lookfor=%22Asien%22&type=Keywordchains

Zum Vergleich: Beim Browsen mit Eingabe von "Asien" erhalte ich die Anzeige, dass 182 Datensätze gefunden wurden:
![grafik](https://user-images.githubusercontent.com/25769591/100601446-e0d5ef00-3302-11eb-8fc9-a239d87567ed.png)

Das sieht aus wie ein Bug - bitte korrigieren.

**Comment by ruschein** [comment]
Liebe Mareike,


die Daten sind keine validen MARC-21 Daten da sie anscheinend einen BOM (byte order marker) am Anfang haben.


Viele Grüße,

Johannes

--
Dr. Johannes Ruscheinski
Universitätsbibliothek Tübingen - IT-Abteilung -
Wilhelmstr. 32, 72074 Tübingen

Tel: +49 7071 29-72820
FAX: +49 7071 29-5069
Email: johannes.ruscheinski@uni-tuebingen.de

 The Sophisticate:  "The world isn't black and white.  No one does pure good or pure bad. It's all gray.  Therefore, no one is better than anyone else."
    The Zetet:  "Knowing only gray, you conclude that all grays are the same shade.  You mock the simplicity of the two-color view, yet you replace it with a one-color view..."
      —Marc Stiegler, David's Sling


________________________________

**Comment by relhei** [comment]
@ruschein: Deinen Kommentar zu diesem Issue verstehe ich leider nicht. Könntest du bitte kurz erklären? Danke!
Viele Grüße

**Comment by ruschein** [comment]
@relhei Da gab es auch nichts zu verstehen da das eigentlich ein Kommentar zu den Daten aus Marburg war.  Ich weiß nicht warum das hier hereingerutscht war.  Ich habe den Kommentar gelöscht.

**Comment by relhei** [comment]
Sorry - hätte ich auch drauf kommen können. Hab jetzt erst deine Mail an Frau H. gelesen. Danke!

**Comment by mtrojan-ub** [comment]
Die Trefferliste die in "Thema browsen" für "Asia" angezeigt wird, enthält nur Treffer im Kontext "Asia". Der Eintrag für "Asien" mit aktuell 57 Treffern bezieht sich also nur auf die Treffer für "Asien" im Kontext "Asia".
https://www.relbib.de/Keywordchainsearch/Results?lookfor=Asia&type=KeywordChainSearch

Beim Klicken auf den Link für "Datensätze anzeigen" neben dem Treffer "Asien" erfolgt eine Suche nach "Asien", aber der Kontext "Asia" geht verloren. Daher erhält man dann deutlich mehr Treffer als in der Liste angezeigt wurden (189).
https://www.relbib.de/Search/Results?lookfor=%22Asien%22&type=Keywordchains

Vermutlich muss man im Link den ursprünglichen Suchkontext mit übergeben. Ich bin mir aber nicht sicher ob das ohne Weiteres möglich ist, da hier relativ komplexe Solr-Abfragen im Einsatz sind und das Ziel-Suchformular das auch unterstützen muss.

@jriedl, kannst Du bitte einen Blick drauf werfen? Du kennst Dich von uns allen bei solchen Baustellen am Besten aus!

**Comment by jriedl** [comment]
Vermutlich hat man da wenig Chancen. Die Zahlen im `KeywordChainBrowsing` kommen zustande, indem die Ergebnismenge facettiert wird (also Suche nach _Asia_ und Facettierung der Ergebnisse). In dem Augenblick, wo die Ergebnisse eben nicht mehr innerhalb einer Baumstruktur unterhalb der Ausgangssuche liegen, hat man im Prinzip verloren. 
Habe jetzt einmal testweise "Asia" und "Asien" auf ptah in die Liste der "protected words" eingetragen, d.h. sie werden nicht mehr gestemmed und sollten damit disjunkte Ergebnisse liefern.

**Comment by relhei** [comment]
Ich habe da jetzt keinen Unterschied zur beschriebenen Ausgangssituation feststellen können. Wenn ich richtig verstehe, müssen wir das einfach so hinnehmen. Kann ich dann schließen?

**Comment by jriedl** [comment]
Ja.
