### ISSUE TITLE
RelBib Newsfeed-Aggregator

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#1354]
Der Eintrag zu dem Blog "Religión y sociedad civil" vom 1.12.20 ist sehr lang. 
![grafik](https://user-images.githubusercontent.com/25769591/100987531-efb0e180-354e-11eb-9396-fdc70f9be325.png)

Wir können festlegen, dass die Teaser auf der RelBib-Oberfläche max. 500 Zeichen lang sind. Das sollte reichen.
Das Gleiche bitte auch für den abonnierten RSS-Feed umsetzen.

Danke!

**Comment by mtrojan-ub** [comment]
Ich kümmer mich drum. Da die Texte allerdings ja auch theoretisch HTML-Tags beinhalten können, müssen wir darauf achten, dass die HTML-Struktur beim Kürzen nicht kaputt geht.

**Comment by mtrojan-ub** [comment]
Ptah wurde aktualisiert, die Änderung kann voraussichtlich ab morgen getestet werden

**Comment by mtrojan-ub** [comment]
... aus meiner Sicht sieht's gut aus, siehe Screenshot.

@relhei, kannst Du bitte nochmal einen Blick drauf werfen?

![grafik](https://user-images.githubusercontent.com/26873381/101758846-1f289680-3ad9-11eb-9c90-ec0e4ac5fad2.png)

**Comment by relhei** [comment]
Vielen Dank - das sieht gut aus. Ich schließe.
