### ISSUE TITLE
Falscher Export im RIS-Format

### ISSUE THREAD

**Issue by AleAprile** [ubtue/tuefind#1358]
Folgender Datensatz wird im RIS-Format als Zeitschriftenartikel (TY=Jour) exportiert, obwohl er eine Monographie ist (erschienen in einer Schriftenreihe). Im K10plus ist alles korrekt erfasst.

https://www.ixtheo.de/Record/1725156628 

Kursorisch habe ich mir auch andere Publikationen dieser Reihe angeschaut. Dabei bin ich auf weitere ähnliche Fehler gestoßen.  

Lässt sich klären, wie es passieren kann, dass korrekt erfassten Datensätzen einmal im RIS-Format vorhanden ein falscher Entry Types zugeordnet wird?

**Comment by ruschein** [comment]
Ready for testing auf ptah!

**Comment by AleAprile** [comment]
Der Export scheint nun richtig zu funktionieren. Ausprobiert habe ich mit mehreren Records dieser Reihe. 
Es ist schön, dass der Fehler doch korrigiert werden konnte. 

Verständnisfrage: Kannst Du mir erklären, wie diese Art von Fehlern überhaupt entstehen?

**Comment by ruschein** [comment]
@AleAprile Es ist die moderat komplexe Art wie wir Datensätze in diesem Fall kategorisiert haben.  Die relevante Änderung von mir ist hier: https://github.com/ubtue/tuefind/pull/1357/files

**Comment by ruschein** [comment]
@AleAprile Gibt es einen Grund dieses Issue noch nicht zu schließen?

**Comment by AleAprile** [comment]
@ruschein Der Grund war schlicht und ergreifend der Beginn meines Urlaubs bereits am 18.12.2020. Jetzt bin ich wieder im Dienst und kann das Issues schließen.
