### ISSUE TITLE
Biblstellensuche Bug

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#1363]
In den Konkordanzen gibt es einen Fehler, so dass keine Suche nach klgl durchgeführt werden kann.

In https://github.com/ubtue/ub_tools/blob/master/cpp/data/bibleRef/books_of_the_bible_to_canonical_form.map
werden die möglichen Such-Varianten auf klageliederjeremias referenziert.

In https://github.com/ubtue/ub_tools/blob/master/cpp/data/bibleRef/books_of_the_bible_to_code.map
wird aber auf "klagelieder=52" referenziert.
Bitte verbessern in "klageliederjeremias=52" 
*******
Bitte in https://github.com/ubtue/ub_tools/blob/master/cpp/data/bibleRef/books_of_the_bible_to_canonical_form.map folgende Variante aufnehmen:
klagelieder=klageliederjeremias

**Comment by ruschein** [comment]
Bitte auf Ptah testen.

**Comment by thefass** [comment]
Die Zeile  429 ist falsch:
klageliederjeremias=klageliederjeremias

es muss heißen : klagelieder=klageliederjeremias

> Bitte in https://github.com/ubtue/ub_tools/blob/master/cpp/data/bibleRef/books_of_the_bible_to_canonical_form.map folgende Variante aufnehmen:
> klagelieder=klageliederjeremias

**Comment by thefass** [comment]
Dieser Datensatz mit PPN 1468247417 müßte mit einer Bibelstellen-Suche nach klgl 5 gefunden werden:
https://ptah.ub.uni-tuebingen.de/Record/1468247417#details
BIR |   |   | \|a 52000000_52999999,52005000_52005999    \|b biblesearch
-- | -- | -- | --

Er wird aber nicht gefunden.

![Bildschirmfoto 2021-01-13 um 10 04 42](https://user-images.githubusercontent.com/14169098/104430327-d310bc00-5586-11eb-99c8-77bfb5f0c5d2.png)

**Comment by ruschein** [comment]
Problem behoben auf IxTheo und ptah.

**Comment by thefass** [comment]
ja, funktioniert. Danke. Woran lag es?

**Comment by ruschein** [comment]
Wir hatten 2 Einträge für klageliederjeremias, einmal für 52 und weiter unten für 84.  Habe jetzt versucht das Problem für immer zu beheben indem ich Duplikate im Code abfange und anmeckere dabei habe ich gefunden, dass wir bei den Einträgen für "es" zwei Werte haben und zwar "exodus" und "jesaja" in books_of_the_bible_to_canonical_form.map.  Was soll ich beibehalten?

**Comment by thefass** [comment]
ok, also doch ein logischer Fehler :-)

Es für Jesaja muss raus (gut, dass Du das gefunden hast), für exodus beibehalten

Bitte auch gleich die neue Liste der zugelassenen Abkürzungen unter A-Z einstellen. Die alte hatte auch (andere) Fehler.
[Bible_abbreviation.pdf](https://github.com/ubtue/tuefind/files/5809345/Bible_abbreviation.pdf)

**Comment by ruschein** [comment]
@thefass Die Anpassung für "es" etc. sind jetzt auf IxTheo aber die Anpassungen im PHP-Code und das neue PDF sind noch nicht auf IxTheo da Mario Bedenken hatte weil damit noch andere Änderungen mitkämen.  Alle Anpassungen sind aber auf Path und werden beim nächsten TueFind-Update auch auf IxTheo landen.

**Comment by thefass** [comment]
ok.
Könnte aber die pdf zeitnah ausgetauscht werden? Da muss ja nur die alte Datei durch die neue ersetzt werden. Denn darin sind einfach peinliche Fehler.

**Comment by mtrojan-ub** [comment]
Ich habe die PDF jetzt übergangsweise von Hand auf ub16 aktualisiert.

**Comment by thefass** [comment]
@mtrojan-ub Vielen Dank!

**Comment by thefass** [comment]
komisch: Suche nach klgl geht nicht mehr. Das hat doch schon funktioniert auf ptah und ixtheo

**Comment by ruschein** [comment]
Das liegt nicht an klgl sondern daran, dass wir noch viele duplizierte Schlüssel in der Datei books_of_the_bible_to_canonical_form.map haben.  Ein ernstes Problem ist dabei der Schlüssel ab, der einmal auf obadja und ein anderes Mal auf habakuk gemappt wird.  Was soll ich da bevorzugen?

**Comment by thefass** [comment]
Bitte bevorzugen: ab=obadja
Bei habakuk löschen

Wo gibt es noch Doppelungen?

**Comment by ruschein** [comment]
@thefass https://github.com/ubtue/ub_tools/pull/3739

**Comment by ruschein** [comment]
Tut jetzt auf Ptah.

**Comment by thefass** [comment]
ja, funktioniert

**Comment by thefass** [comment]
wann wird es auf ixtheo sein?

**Comment by ruschein** [comment]
@thefass Vermutlich morgen nachdem die MARC-Pipeline dort durchgelaufen ist.

**Comment by thefass** [comment]
prima, Danke

**Comment by ruschein** [comment]
@thefass Tut jetzt auch IxTheo.

**Comment by thefass** [comment]
ja, ok
