### ISSUE TITLE
Anzeige von OA-Lizenzen

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#1366]
In PICA-Feld 4980 können Rechteinformationen zu einzelnen Werken in standardisierter Form inkl. Verlinkung auf den ausführlichen Inhalt der Lizenz eingetragen werden. Das ist genau das, was wir für die Zweitveröffentlichungsprojekte gesucht haben. 
https://swbtools.bsz-bw.de/cgi-bin/k10plushelp.pl?cmd=kat&val=4980&katalog=Standard
Dank an @socheres für den Hinweis!
In VuFind-Internformat wird diese Information im Feld 540 inkl. Unterfeldern angezeigt. Hier ein Beispiel:
https://www.relbib.de/Record/1735956244#details
Nun wäre es wünschenswert, die Information zur Lizenz, falls diese eingetragen ist, auch in der Haupttitelanzeige in VuFind zu verankern. Z. B. in einer neuen Zeile "Lizenz" (dt.) bzw. "License" (engl.).
Hier ein Beispiel, wie das beim FID Benelux gelöst wurde:
https://search.fid-benelux.de/Record/35fac0c7-a2a4-4576-a252-3fd59169ba47

Ihr benötigt für die Anzeige der Lizenzen vmtl. eine Liste bzw. Konkordanz, was im Fall welcher Feldbelegung / Lizenz angezeigt werden soll?

**Comment by IxKo** [comment]
Falls es weiterhilft: Ich hatte mal ein Beispiel zur Nachverfolgung der neuen Kategorie 4985 erstellt gehabt.
https://ixtheo.de/Record/1662687761

Eintrag in der WinIBW:
4985 [DE-Tue135]Open Access$gControlled Vocabulary for Access Rights$uhttp://purl.org/coar/access_right/c_abf2

**Comment by IxKo** [comment]
Hier noch ein anderes Beispiel: https://ixtheo.de/Record/169845192X

4980 [DE-Tue135]Namensnennung 4.0 International$cCC BY 4.0$gCreative Commons$uhttps://creativecommons.org/licenses/by/4.0/legalcode
4985 [DE-Tue135]Open Access$gControlled Vocabulary for Access Rights$uhttp://purl.org/coar/access_right/c_abf2
führt zur VuFind-Anzeige:

Beschreibung: | Version 1
-- | --
Open Access

**Comment by relhei** [comment]
Uppdate: Die Angabe der Lizenz / Rechteinformation ist nicht ganz einfach, weil aufgrund des Tübinger Vorgehens bei der Aufsatzkatalogisierung von Zweitveröffentlichungen Konflikte mit Verlagsversionen entstehen können. Ziel ist es, ein einfach umsetzbares Prozedere zu finden, ohne viele Sonderfälle.
Ich habe dazu einige Informationen zusammengetragen, die wir zunächst auf Projektleitungsebene (Zweitveröffentlichungsservices der drei FID) besprechen. Danach dann noch mal im Meeting der FID-IT-Runde.

**Comment by relhei** [comment]
Beispiel für Fall 1 (Urheberrechtsschutz 1.0): PPN 176148740X - nicht von uns katalogisierter Titel!
Beispiel für Fall 2 (CC BY 4.0): PPN 1752456440
Beispiel für eine andere CC-Lizenz (CC BY-NC-ND 4.0): PPN 167574629X
Wird für jede Lizenzart ein eigenes Beispiel benötigt? 

Die Entscheidung, ob die Rechteinformation in einer Facette eingebunden werden soll, müssten wir gemeinsam entscheiden - for meeting discussion.

**Comment by mtrojan-ub** [comment]
Gibt es eigentlich einen Zusammenhang zu #1159?

**Comment by relhei** [comment]
Nicht direkt, da es hier um die Anzeige von Informationen zu konkreten **Nutzungsrechten** geht (also wie bzw. unter welchen Umständen darf ein verfügbarer Volltext genutzt und weiterverwertet werden). In #1159 hingegen geht es um die Anzeige von Informationen zum **Zugriff** (also wie bzw. unter welchen Umständen sind Volltexte verfügbar).

**Comment by mtrojan-ub** [comment]
ready for testing: 
- ptah: https://ptah.ub.uni-tuebingen.de/Record/1735956244
- sobek: https://sobek.ub.uni-tuebingen.de/Record/815914806

Sitzt das Feld auch an der richtigen Stelle? (z.B. beim ptah-Beispiel erscheint erst der Link zur Parallelausgabe vor der Lizenz. Wollen wir es ggf. an einer anderen Stelle anzeigen?)

In IxTheo gibt es übrigens ca. 3500 Datensätze mit diesem Feld. In KrimDok sind es ca. 50.

**Comment by thefass** [comment]
sinnvoll ist sicher, wenn Lizenz direkt unter "online unter" kommt, da das ja inhaltlich zusammengehört

**Comment by thefass** [comment]
da es ein Link ist, der nach außen führt, sollte die Lizenz Info in einem eigenen Tab geöffnet werden

**Comment by mtrojan-ub** [comment]
Ist angepasst!

**Comment by thefass** [comment]
sieht gut aus. Wenn @relhei einverstanden ist, kann das Issue m.E. geschlossen werden

**Comment by relhei** [comment]
Super - danke!

**Comment by relhei** [comment]
Ah, nein: Jetzt ist dochn noch was aufgefallen.
Bitte die Zeile nicht "Lizenz" bezeichnen, sondern "Rechteinformation" bzw. "rights information". Denn streng genommen ist InC 1.0 keine Lizenz. 
Außerdem habe ich mal das o.g. Beispiel für InC 1.0 (PPN PPN 176148740X) auf ptah getestet und es kommt eine Fehlermeldung:
https://134.2.67.9/Search/Results?lookfor=ids%3A176148740X&type=AllFields&limit=20&sort=year+desc%2C+volume_sort+desc%2C+issue_sort+desc%2C+start_page+asc%2C+first_indexed+desc&botprotect=

**Comment by mtrojan-ub** [comment]
Fehler ist behoben, um die Umbenennung kümmere ich mich noch

**Comment by mtrojan-ub** [comment]
ready for testing

**Comment by relhei** [comment]
Jetzt wird mir aber bei diesem Beispiel keine Rechteinformation mehr angezeigt?
![grafik](https://user-images.githubusercontent.com/25769591/141453781-3d3917f0-4d3f-4137-9f8b-0e65570df9a0.png)
Hing der Fehler möglicherweise mit der Anzeige genau dieser Info zusammen?

**Comment by mtrojan-ub** [comment]
Im 540er-Feld fehlt das Unterfeld f, daher wird nichts angezeigt.

**Comment by relhei** [comment]
Das Unterfeld f darf nur belegt werden, wenn es einen standardisierten Code für die Lizenz gibt. Das ist bei InC 1.0 momentan nicht der Fall (wurde schon mit Verbund geklärt). S. Kommentar vom 19.10. (24 days ago). Ist das wie oben beschrieben umsetzbar?

**Comment by mtrojan-ub** [comment]
Wie wäre die Logik dann genau?

Wenn das Unterfeld `f` fehlt, sollen wir dann prüfen ob in `a` der Wert "Urheberrechtsschutz 1.0" steht oder in `u` die URL http://rightsstatements.org/vocab/InC/1.0/ (ist `a` oder `u` wichtiger?), und dann als Wert `InC 1.0` indexieren/anzeigen?
Falls wir stattdessen die Langform wie z.B. `Urheberrechtsschutz 1.0` anzeigen sollen, dann müssten wir das auf Englisch in Solr indexieren (bitte genaue Bezeichnung nennen) und dann für die Anzeige in sämtlichen Sprachen rückübersetzen.

Bitte möglichst genau definieren was die Anforderung ist

**Comment by relhei** [comment]
Genau: Wenn das Unterfeld f fehlt, sollte das Unterfeld u auf den o.g. Link hin geprüft werden. Theoretisch könnte man auch das Unterfeld a auslesen, aber dann müsste sichergestellt werden, dass genau und nur dieser Ausdruck "Urheberrechtsschutz 1.0" im Feld steht, da es noch ähnlich lautende Feldinhalte gibt. Sicherer und weniger fehleranfällig ist m. E. das Auslesen von Unterfeld u.
Bitte dann, wenn der o.g. Link in Unterfeld u steht, den Wert InC 1.0 anzeigen.

**Comment by mtrojan-ub** [comment]
ready for testing auf ptah

**Comment by relhei** [comment]
Das sieht schon sehr gut aus. Nur eine Kleinigkeit noch: Kann bei dem Fall "Urheberrechtsschutz 1.0" bitte generell bei der Anzeige InC 1.0 auf die englische Seite verlinkt werden? Die entsprechende URL lautet: https://rightsstatements.org/page/InC/1.0/?language=en 
Wir müssen dabei an unsere internationalen Nutzer*innen denken ;)

**Comment by mtrojan-ub** [comment]
Ist angepasst, siehe ptah

**Comment by relhei** [comment]
Passt jetzt. Vielen Dank!
Bitte noch testen für KrimDok und IxTheo: @JMeister01 @ja-bre @coeh

**Comment by JMeister01** [comment]
Passt auch für KrimDok, danke!

**Comment by ja-bre** [comment]
@relhei Passt auch für uns, dankeschön!
