### ISSUE TITLE
Invalid Server response

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#1377]
In der Zeile Buchbeschaffung
https://ixtheo.de/Record/1699828415#details

![Bildschirmfoto 2021-01-18 um 15 02 25](https://user-images.githubusercontent.com/14169098/104924979-7b1af080-599e-11eb-9216-1f6196eb4c0f.png)

**Comment by jriedl** [comment]
Momentan nicht reproduzierbar.

**Comment by thefass** [comment]
ja, geht wieder. gut, dass ich einen Screenshot gemacht habe, sonst denkt man manchmal, ob man so richtig tickt ;-)
