### ISSUE TITLE
JOP Fehlermeldung

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#1381]
Auf beiden Datenbanken kommt eine Fehlermeldung:
Bsp.:
https://ixtheo.de/Record/1645497291
https://ptah.ub.uni-tuebingen.de/Record/1645497291

![JOP](https://user-images.githubusercontent.com/17004223/105319025-8e0f0a00-5bc4-11eb-9659-0e3f070cbe09.JPG)

**Comment by jriedl** [comment]
Stichprobenartig scheint JOP im Prinzip zu funktionieren: https://ixtheo.de/Record/1743968965, https://ptah.ub.uni-tuebingen.de/Record/1744705143, https://ixtheo.de/Record/1744661804. In dem konkreten Fall ist die Fehlermeldung, dass kein Seitenbereich angegeben wird. Grund ist, dass im Datensatz nur eine einzelne Seite hinterlegt ist. Scheinbar gab es hier JOP-seitig Änderungen an der Verarbeitung. Wir werden das für solche Fälle entsprechend anpassen.

**Comment by jriedl** [comment]
Auf ptah und ub16.

**Comment by IxTheoKm** [comment]
Danke. Wird im Vergleich zu vorher mit einer ganz kleinen Verzögerung geladen, aber es funktioniert wieder. Daher schließe ich.
