### ISSUE TITLE
Unvollständige Anzeige von Schlagwort-Unterfeldern

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#1390]
In der Facette Thema (Schlagwort) werden bei Kongress-/Körperschaften mehrere Unterfelder von Feld 689 nicht angezeigt, in der Vollanzeige fehlt $e.

$b
$c
$d
$e
$g
$n

Beispiel:
https://ixtheo.de/Search/Results?lookfor=id%3A173649399X&type=AllFields&limit=20&botprotect=
https://ixtheo.de/Record/173649399X#details

https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=id%3A173649399X&type=AllFields&limit=20&botprotect=
https://ptah.ub.uni-tuebingen.de/Record/173649399X#details

![SW_UF](https://user-images.githubusercontent.com/17004223/106628912-924f0600-657a-11eb-874b-bbf2c729374b.JPG)

![SW_UF2](https://user-images.githubusercontent.com/17004223/106628925-967b2380-657a-11eb-8023-434fc94a9db3.JPG)

![SW_UF3](https://user-images.githubusercontent.com/17004223/106628947-9aa74100-657a-11eb-95ec-516c15050e3a.JPG)

**Comment by mtrojan-ub** [comment]
Sieht so aus als wäre dieser Issue "ready for testing"

**Comment by IxTheoKm** [comment]
> In der Facette Thema (Schlagwort) werden bei Kongress-/Körperschaften mehrere Unterfelder von Feld 689 nicht angezeigt, in der Vollanzeige fehlt $e.

Ist nur zum Teil umgesetzt: die Vollanzeige ist in Ordnung.
Die Facette "Thema (Schlagwort)" ist weiterhin unvollständig.

**Comment by jriedl** [comment]
Der aktuelle Stand findet sich auf ptah. Anmerkung: In der Vollanzeige wird viel Speziallogik verwendet um aufeinanderfolgende $c und $d-Felder entsprechend zu formatieren und mit Klammern zusammenzufassen. Bei der Extraktion der Facetten handelt es sich jeweils um generische Funktionen.

**Comment by IxTheoKm** [comment]
Ich weiß nicht genau, was mit "generische Funktionen" gemeint ist. Ich vermute, dass darum die Klammerung usw. der Vollanzeite nicht in der Facette auftaucht. Die halte ich dort auch für verzichtbar. Jedenfalls werden auf ptah nur alle Elemente des Schlagworts angezeigt (sowohl in der Vollanzeige als auch in der Facette). Vielen Dank, ich schließe
