### ISSUE TITLE
Abweichende Sortierung bei Neuzugängen zw. Test- und Produktivsystem

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#1393]
RelBib: Neuzugänge der letzten 60 Tage = 13.410 Treffer
https://www.relbib.de/Search/NewItem?range=60&submit=Suchen&botprotect=
Testsystem: Neuzugänge der letzten 60 Tage = 13.577 Treffer
https://134.2.67.9/Search/NewItem?range=60&submit=Suchen&botprotect=

Warum weicht die Sortierung ab? Bei "Neuzugänge der letzten 14 Tage" keine Abweichung. Nicht klar, ob durch VuFind-Update bewirkt.

**Comment by mtrojan-ub** [comment]
Nach mehreren Stichproben bin ich der Ansicht, dass es sich nicht um einen Bug handelt.

Beispiel-Datensatz:
https://relbib.de/Record/1725646374

Taucht stand heute in der Liste auf ptah auf, aber nicht auf ub16. Der Hintergrund ist ein unterschiedliches first_indexed Datum in Solr.

ptah: "first_indexed":"2020-12-11T03:05:32Z"
ub16: first_indexed":"2020-12-10T04:00:53Z"

=> Also ein Tag Unterschied dazwischen.

Auf ptah machen wir ja öfters Änderungen an der Pipeline. Das führt manchmal auch zum Abbrechen der Pipeline, was dazu führt dass manche Datensätze erst ein paar Tage später zum ersten Mal im Index landen und somit auch erst später+länger als Neuzugänge gelistet werden.

**Comment by relhei** [comment]
Alles klar. Vielen Dank für die Erläuterung!
