### ISSUE TITLE
Fehlermeldung in Kurztitelanzeige wenn 773g / 773w fehlt

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#1394]
Wenn man bei diesem Suchergebnis die Facette / Auswahl "Sprache: Französisch" wieder entfernt, gibt es auf dem Testsystem eine Fehlermeldung (Whoops...):
https://134.2.67.9/Search/Results?filter%5B%5D=is_open_access%3A%22open-access%22&filter%5B%5D=%7Elanguage%3A%22French%22&filter%5B%5D=%7Edewey-hundreds%3A%22900+-+History+%26+geography%22&filter%5B%5D=%7Eformat%3A%22Article%22&type=AllFields
Fehlermeldung:
https://134.2.67.9/Search/Results?filter%5B%5D=is_open_access%3A%22open-access%22&filter%5B%5D=%7Edewey-hundreds%3A%22900+-+History+%26+geography%22&filter%5B%5D=%7Eformat%3A%22Article%22&type=AllFields
Auf RelBib besteht das Problem unter gleichen Auswahlbedingungen nicht.

**Comment by mtrojan-ub** [comment]
Das Problem ist reproduzierbar, ich kümmere mich gleich drum.

**Comment by mtrojan-ub** [comment]
Das Problem kommt daher, dass bei diesem Datensatz zwar 773t gesetzt ist, aber weitere Informationen zum übergeordneten Werk fehlen (773g und 773w).

Ich werde das Template so anpassen dass es diesen Fall besser abfängt und zumindest keinen Fehler produziert, vermutlich sollte aber auch der Datensatz korrigiert werden.

**Comment by mtrojan-ub** [comment]
ready for testing auf ptah

**Comment by IxTheoKm** [comment]
Zur Info:
Das Beispiel PPN 1653302054 "Sonderdruck aus..." ist korrekt erfasst: 
Sonderdrucke werden wie Monographien und unverknüpft, also ohne 773 g und w erfasst.

**Comment by relhei** [comment]
Passt. Danke!
