### ISSUE TITLE
Problem mit Helvetica?

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#1410]
Im RelBib-Theme wird aktuell folgende Direktive verwendet:
`font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;`

"Helvetica Neue" ist eine Schriftart, die standardmäßig nicht mehr auf Windows-Systemen ausgeliefert wird (ggf. da sich mittlerweile die Lizenz verändert hat?)

Standardmäßig sieht ja die RelBib-Startseite so aus:
![grafik](https://user-images.githubusercontent.com/26873381/109474781-270f2b80-7a75-11eb-95af-47571955cb18.png)

Für diverse Arbeiten in GIMP habe ich auf meinem Windows-System "Helvetica Neue" von Hand nachinstalliert. Jetzt sieht die Start seite so aus:
![grafik](https://user-images.githubusercontent.com/26873381/109474836-37270b00-7a75-11eb-9413-f70fa212e6c2.png)

Ich bin mir nicht sicher ob es sich um ein lokales Problem auf meinem Rechner handelt... jedenfalls finde ich die erste Version deutlich leserlicher. Vermutlich wird hier als Fallback Arial verwendet, da Helvetica nicht verfügbar ist. 

1) Kann jemand anders bitte dieses Verhalten bestätigen?
2) Falls ja, sollten wir entweder a) Helvetica aus der Definition entfernen und nur Standardschriftarten verwenden oder b) Die passende Schriftart mit in die Website einbetten und an die Clients mit ausliefern, wobei hier die Lizenzrechtlichen eigentschaften der Schriftart berücksichtigt werden müssen (müssen wir also ggf. auf eine gemeinfreie Schriftart wechseln?)

**Comment by mtrojan-ub** [comment]
IxTheo ist ebenfalls betroffen

**Comment by ruschein** [comment]
https://freefontsfamily.com/helvetica-neue-font-free/

[https://freefontsfamily.com/wp-content/uploads/2021/02/Helvetica-Neue-Font.jpg]<https://freefontsfamily.com/helvetica-neue-font-free/>

Helvetica Neue Font Family<https://freefontsfamily.com/helvetica-neue-font-free/>
freefontsfamily.com
We shared Helvetica Neue Font that includes light, medium, and thin styles. It is famous google fonts. You can use it in any adobe software.





--
Dr. Johannes Ruscheinski
Universitätsbibliothek Tübingen - IT-Abteilung -
Wilhelmstr. 32, 72074 Tübingen

Tel: +49 7071 29-72820
FAX: +49 7071 29-5069
Email: johannes.ruscheinski@uni-tuebingen.de

 The Sophisticate:  "The world isn't black and white.  No one does pure good or pure bad. It's all gray.  Therefore, no one is better than anyone else."
    The Zetet:  "Knowing only gray, you conclude that all grays are the same shade.  You mock the simplicity of the two-color view, yet you replace it with a one-color view..."
      —Marc Stiegler, David's Sling


________________________________

**Comment by mtrojan-ub** [comment]
Im Moment glaube ich eher, dass auf meinem Windows-Rechner bei der Installation eines Helvetica Fonts aus mir unerfindlichen Gründen einige Standardfonts mit dem dem falschen Font überschrieben wurden. Da das Problem bislang noch niemand sonst auf dieses Problem gestoßen ist, werde ich den Issue wieder schließen.
