### ISSUE TITLE
Mehrere ISNIs/ORCIDs/VIAFs im selben Normdatensatz

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#1418]
In den aktuell importierten Normdaten tauchen immer wieder Einträge mit doppelten IDs auf, was aktuell dazu führt dass diese nicht importiert werden können.

**Beispiel ORCID:**
```
001 519033175
003 DE-627
005 202101112125.5
008 120419n||aznnnabbn           | aaa    |c
024 7 $a0000-0001-7247-190X$2orcid
024 7 $a0000-0002-6629-2558$2orcid
024 7 $ahttp://d-nb.info/gnd/132194651$2uri
035   $z(DE-588a)132194651$9v:zg
035   $a(DE-576)16540924X
035   $a(DE-627)519033175
035   $a(DE-588)132194651
043   $cXE-AU
079   $ag$bp$cv$qf$vpiz
100 1 $aGascoigne, John$d1951-
375   $a1$2iso5218
548   $a1951-$4datl$wr$iLebensdaten
548   $a20.01.1951-$4datx$wr$iExakte Lebensdaten
550   $0(DE-627)104675276$0(DE-576)208959203$0(DE-588)4025098-2$aHistoriker$4berc$wr$iCharakteristischer Beruf
670   $aLCAuth
678   $bBA Syd., MA Prin., Ph. D., Cambridge. Lecturer, School of History, Univ. of New South Wales
692   $aCambridge in the age of the Enlightenment. - 1989
692   $aThe Enlightenment and the origins of European Australia. - 2002
700 1 $aGascoigne, John$0(DLC)n 92003352$2naf$9v:Ph. D.
```

Davon gehört z.B. nur die zweite ORCID tatsächlich zu John Gascoigne
https://orcid.org/orcid-search/search?searchQuery=a0000-0001-7247-190X
https://orcid.org/orcid-search/search?searchQuery=a0000-0002-6629-2558

Können die Daten korrigiert werden? Falls nicht, wie gehen wir damit um?

**Beispiel ISNI**
```
001 697767388
003 DE-627
005 202010192124.2
008 120419n||aznnnabbn           | aaa    |c
024 7 $a0000000061506639$2isni
024 7 $a0000-0000-6150-6639$2isni
024 7 $ahttp://d-nb.info/gnd/172837766$2uri
035   $z(DE-588a)172837766$9v:zg
035   $a(DE-576)133693589
035   $a(DE-627)697767388
035   $a(DE-588)172837766
040   $aDE-627$bger$cDE-627$erda
043   $cXA-NL
079   $ag$bp$cv$qf$vpiz
100 1 $aVree, Jasper$d1943-2020
400 1 $aVree, Jasper Az.$d1943-2020
400 1 $aVree, J.$d1943-2020$9v:LCAuth
510 2 $0(DE-627)101557906$0(DE-576)190498072$0(DE-588)80108-2$aVrije Universiteit Amsterdam$4affi$wr$iAffiliation$eAffiliation
548   $a08.05.1943-09.07.2020$4datx$wr$iExakte Lebensdaten
548   $a1943-2020$4datl$wr$iLebensdaten
550   $0(DE-627)191672858$0(DE-576)21202485X$0(DE-588)4398113-6$aKirchenhistoriker$4berc$wr$iCharakteristischer Beruf
550   $0(DE-627)104452013$0(DE-576)209132140$0(DE-588)4059756-8$aTheologe$4beru$wr$iBeruf
667   $aTü 135
670   $aKBNL-online
692   $aDe Vereniging van 1892 en haar geschiedenis
692   $aDe Groninger godgeleerden
```
=> Zwei unterschiedliche Schreibweisen: 0000000061506639 und 0000-0000-6150-6639. Welche nehmen wir auf?

**Beispiel VIAF**
```
001 060922117
003 DE-627
005 202101132126.5
008 120419n||aznnnabbn           | aaa    |c
024 7 $a31432428$2viaf
024 7 $an86140996$2viaf
024 7 $ahttp://d-nb.info/gnd/11876439X$2uri
035   $z(DE-588c)4107588-2$9v:zg
035   $z(DE-588a)11876439X$9v:zg
035   $a(DE-576)209424753
035   $a(DE-627)060922117
035   $a(DE-588)11876439X
040   $aDE-627$bger$cDE-627$erda
043   $cXD-US
065   $a16.5p$2sswd
065   $a8.4p$2sswd
079   $ag$bp$cv$qa$qf$qs$qz$qd$vpiz
100 1 $aWashington, George$d1732-1799
375   $a1$2iso5218
400 1 $aWashington, Geo.$d1732-1799
400 1 $aWashington, Giorgio$d1732-1799
400 1 $aWashington, Georg$d1732-1799
400 1 $aVašington, Džordž$d1732-1799
500 1 $0(DE-627)224565079$0(DE-576)211577774$0(DE-588)119191466$aWashington, Martha$d1731-1802$4bezf$wr$iBeziehung familiaer$eBeziehung familiaer$9v:Ehefrau
500 1 $0(DE-627)1672351383$0(DE-588)1193607116$aWashington, Mary Ball$d1708-1789$4bezf$wr$iBeziehung familiaer$eBeziehung familiaer$9v:Mutter
510 2 $0(DE-627)862199980$0(DE-576)472920243$0(DE-588)1104852101$aUSA$bPräsident$g1789-1797 : Washington$4affi$wr$iAffiliation$eAffiliation
548   $a22.02.1732-14.12.1799$4datx$wr$iExakte Lebensdaten
548   $a1732-1799$4datl$wr$iLebensdaten
550   $0(DE-627)104591668$0(DE-576)209941987$0(DE-588)4172227-9$aOberbefehlshaber$4beru$wr$iBeruf
550   $0(DE-627)105812986$0(DE-576)209494697$0(DE-588)4115611-0$aPräsident$4beru$wr$iBeruf
550   $0(DE-627)106197711$0(DE-576)209069961$0(DE-588)4046517-2$aPolitiker$4berc$wr$iCharakteristischer Beruf
551   $0(DE-627)105815772$0(DE-576)209491655$0(DE-588)4115250-5$aMount Vernon, Va.$4orts$wr$iSterbeort
551   $0(DE-627)104981695$0(DE-576)21030359X$0(DE-588)4225093-6$aWakefield$4ortg$wr$iGeburtsort
667   $aOENAK
667   $aPacelli-Edition
667   $aDBSM
667   $a7
667   $a12
670   $aWikipedia$uhttps://de.wikipedia.org/wiki/George_Washington
670   $aHomepage$bStand: 25.11.2019$uhttp://www.pacelli-edition.de/Biographie/25025
670   $aLCAuth
678   $bAmerikan. General und 1. Präsident der USA (1789-1797)
678   $b1749 Tätigkeit als Geometer, 1752 Initiation als Freimauer, 1754-1763 Teilnahme am        Franzosen- und, 1759 Mitglied des Abgeordnetenhauses in Virginia und Tätigkeit als        Plantagenbesitzer, 1774 Mitglied des Kontinentalkongresses, 1775 Kommandeur der        Kontinentalarmee im Amerikanischen Unabhängigkeitskrieg, 1787 Präsident des        Verfassungskonvents in Philadelphia, 1788 "Meister vom Stuhl" der Freimaurerloge        "Alexandria" in Virginia, 1789-1797 erster US-Amerikanischer Präsident.$uhttp://www.pacelli-edition.de/Biographie/25025
692   $aWashington, George: The Journal of George Washington sent by the Hon. Rob. Dinwiddie ... - 1754
692   $aWashington, George: 3 Messages from the President of the United States
692   $aWashington, George: Official letters to the honorable American Congress ..
692   $aWashington, George: Message from the President of the U.S. ...
692   $aWashington, George: A message from the President of the United States of America ... - 1797
692   $aWashington, George: A collection of the speeches of the President of the United States ... - 1796
692   $aWashington, George: Farewell address to the people of the United States of America. - 1850
692   $aWashington, George: The President's address to the people of the United States ...
692   $aWashington, George: Vie, correspondance et écrits de Washington. - 1840
692   $aWashington, George: Official letters to the honorable American Congress ...
692   $aWashington, George: A message of the President of the United States to congress ... - 1795
692   $aWashington, George: Message from the President of the U.S. ..
692   $aWashington, George: The President's address to the people of the United States ..
```

https://viaf.org/viaf/31432428/ => erreichbar
https://viaf.org/viaf/n86140996/ => Fehler, aber wenn man das n weglässt landet man auf einer gültigen Seite. Hat der Buchstabe eine besondere Bedeutung, oder handelt es sich um einen Datenfehler? Müssen hier mehrfache Werte zugelassen werden?

**Comment by IxTheoKm** [comment]
Die Erfassungsform für die anderen IDs werden in den Beispielen der Formatdokumentationen so angegeben:
DNB:
024 orcid: 0000-0003-1684-6994
024 orcid: 0000-0003-3397-2087$vHerkunft: orcid
024 orcid: 0000-0002-2248-9914$vHerkunft: cg001
024 orcid: 0000-0002-0733-8982$vHerkunft: mm001
024 isni: 0000 0000 3483 4055

K10plus:
024 orcid: 0000-0003-1427-7329
024 isni: 0000 0000 2368 8144
024 rid: L-8167-2014
024 scopus: 22735718100

024 viaf: 13172298
024 orcid: 0000-0003-4496-3100


Zum ersten Fall **Gascoigne**:
ich habe die Autorenredaktion benachrichtigt.

**ISNI**: 
Offensichtlich ist die Form in Viererschritten - aber ohne Bindestriche - korrekt. Ich muss bei der Autorenredaktion anfragen, ob auch andere Formen möglich sind.

**VIAF**: 
die n-Nummer hat eine falsche Einleitende Kennung! Es handelt sich um die Nummer der LoC. Korrektur wird veranlasst.

**Comment by thefass** [comment]
Ich bin überrascht, dass die ISNI ohne Bindestriche eingegeben werden und die ORCIDs mit. Denn die ORCID ist ja eine reservierte Untermenge aus der ISNI.
Aber das klärt ja @IxTheoKm 
ORCIDS ohne Bindestriche völlig zusamenngschrieben sind mir noch nie begegnet

**Comment by IxTheoKm** [comment]
https://isni.org/page/search-database/

**Anzeigeform bei isni.org:**
![isni](https://user-images.githubusercontent.com/17004223/110953224-66782a80-8347-11eb-9d2d-f765acbe1492.JPG)


**Erfassungsform bei isni.org**:
![isni2](https://user-images.githubusercontent.com/17004223/110953002-29ac3380-8347-11eb-8680-3101de4286d3.JPG)

**Comment by mtrojan-ub** [comment]
Unabhängig davon ob die einzelnen Nummernschemas korrekt sind oder nicht: Sind grundsätzlich mehrere ISNIs, ORCIDs und VIAFs im selben Normdatensatz erlaubt? (Falls ja, so könnte ich hier schonmal Anpassungen in die Wege leiten, damit es keine Fehler mehr beim Import gibt).

**Comment by thefass** [comment]
Ob es erlaubt ist, müßte @IxTheoKm klären.
Sinnvoll ist es natürlich nicht, wenn diese Nummern gedoppelt werden. Es wird aber zumindest bei der ORCID vorkommen, da in der Anfangszeit der ORCID auch andere Trustees für Autoren eine ORCID anlegen konnten und wenn das der Autor dann nochmal machte, weil er davon nichts wußte, war das Kind in den Brunnen gefallen.
Vielleicht könnte man in diesen Fällen eine Benachrichtigung setzen, so dass wir die richtige Nummer eruieren könnten? Kommt auch etwas darauf an, wieoft das vorkommt

**Comment by IxTheoKm** [comment]
Zwischenstand: Anfrage an Autorenredaktion am 12.03.2021 gestellt. Wurde ans BSZ weitergereicht. Bisher keine Klärung (26.03.21)

**Comment by IxTheoKm** [comment]
Der erste Teil der Frage wurde soeben vom BSZ nach Rücksprache mit der DNB beantwortet:
"die korrekte Angabe der **ISNI**-Nr. ist die mit Leerzeichen, wie in unserer Format-Doku und dem Erfassungsleitfaden (isni: 0000 0000 6150 6639)".

Die ORCID hat lt. Formatdokumentation Bindestriche. Siehe https://github.com/ubtue/tuefind/issues/1418#issuecomment-797512636

Die zweite Frage bzgl. Wiederholbarkeit muss noch von der DNB beantwortet werden.

**Comment by IxTheoKm** [comment]
Hier die BSZ-Antwort zur Wiederholbarkeit:

"Eine **ORCID**, **Wikidata** und eine **ISNI**-Nr. sollten immer eindeutig sein, allerdings können Dubletten bei ISNI vorkommen (auf deren Bereinigung haben wir auch keinen Einfluss). Alle anderen sind teilweise nicht eindeutig (scopus, ResearcherID...)."

Das bedeutet also:
wenn es Doppelungen gibt, müssen sie im Einzelfall geprüft werden, ob es tatsächlich fehlerhafte Erfassungen sind
(wie im ersten Beispiel ORCID PPN 519033175 Gascoigne; Prüfung ist veranlasst. 
Zweites Beispiel zweiten Beispiel ISNI PPN 697767388 Vree; Korrektur ist beantragt.
Drittes Beispiel VIAF PPN 060922117 Washington; Korrektur ist erfolgt.)

Wenn ein und dieselbe Standardnummer in mehreren Varianten vorkommt, von denen eine die lt. Erfassungsformat die korrekte Version ist, könnte diese verwendet werden.
Bsp.:
024 isni: 0000-0000-2368-8144
024 isni: 0000000023688144
024 isni: 0000 0000 2368 8144 [korrekte Erfassungsform]

024 orcid: 0000-0003-1684-6994 [korrekte Erfassungsform]
024 orcid: 0000000316846994
024 orcid: 0000 0003 1684 6994

**Comment by mtrojan-ub** [comment]
Können wir den Import auf die korrekten Erfassungsformen beschränken? Das wäre technisch einfacher und auch konsistenter als eine andere Form zu importieren, falls keine korrekte Erfassungsform dabei ist (oder sie sogar beim Import zu normalisieren).

**Comment by thefass** [comment]
Falsche Schreibweisen mit oder ohne Bindestriche, mit oder ohne Leerraum werden immer wieder vorkommen, da die Erfassungsregeln zu kompliziert sind. Es wäre aber sehr schade, wenn wir aus diesen Gründen auf eine Orcid oder ISNI verzichten. 
Es wäre ein weiterer Schritt in der Pipeline ...
Den Fall, dass zwei unterschiedliche orcids oder isnis vorkommen, müßtet ihr sowieso auffangen. Ich würde den Import dadurch aber nicht abbrechen, sondern einen solchen Fall protokoliieren

**Comment by mtrojan-ub** [comment]
Wir haben in der Zwischenzeit folgende Änderung auf ptah eingespielt:
- ORCIDs + ISNIs werden nun allesamt normalisiert (also auch wenn es nur eine einzige ORCID oder ISNI für den Datensatz gibt wird diese normalisiert)
- Falls nach der Normalisierung mehr als eine ORCID oder mehr als eine ISNI übrig bleibt, wird das entsprechende Feld nicht importiert und eine Warnung im Log ausgegeben (siehe Beispiel oben / 519033175 bzw. John Gascoigne)

Können wir die VIAFs noch genauer abprüfen? Also z.B. ausschließlich Dezimalzahlen mit einer Länge von 8 Zeichen?

**Comment by IxTheoKm** [comment]
Ich glaube nicht, dass man VIAF anhand der Zeichen-Anzahl abprüfen kann: ich habe auch IDs mit 7 Zeichen gefunden. 
Bsp.: https://viaf.org/viaf/7667131/

**Comment by IxTheoKm** [comment]
https://viaf.org/viaf/175125527/ ist ein Werktitel, nicht die Person:

Valentini, Michael Bernhard, 1657-1729. | Polychresta exotica
VIAF ID: 175125527 (Werktitel)
Permalink: http://viaf.org/viaf/175125527

Ich habe in der Redaktion angefragt, ob diese ID überhaupt im Personennormsatz stehen darf.

**Comment by IxTheoKm** [comment]
Der Fall PPN 519033175 Gascoigne wurde heute auch in der GND bereinigt.

**Comment by mtrojan-ub** [comment]
In der Log sind weitere Fälle aufgetaucht:
583288588
866433430
788446711
696582694
524718458
880465336
1749519828
495820741

**Comment by IxTheoKm** [comment]
> 583288588 [bereits korrigiert]
> 866433430 [tatsächlich für eine Person zwei ISNI nachgewiesen; Anfrage an Redaktion geschickt]
> 788446711 [Korrektur erledigt]
> 696582694 [tatsächlich für eine Person zwei ISNI nachgewiesen; Anfrage an Redaktion geschickt]
> 524718458 [Möglicherweise ISNIs zweier Personen; Anfrage an Redaktion geschickt]
> 880465336 [tatsächlich für eine Person drei ISNI nachgewiesen; Anfrage an Redaktion geschickt]
> 1749519828 [tatsächlich für eine Person zwei ISNI nachgewiesen; Anfrage an Redaktion geschickt]
> 495820741 [tatsächlich für eine Person zwei ISNI nachgewiesen; Anfrage an Redaktion geschickt]

**Comment by IxTheoKm** [comment]
Rückmeldung der Redaktion/Verbundzentrale: die DNB hat keine Validation und wird sie voraussichtlich auch nicht einrichten, obwohl normalerweise jeweils nur eine Standardnummer erlaubt ist. Solche Fälle werden wahrscheinlich immer wieder mal vorkommen.

**Comment by mtrojan-ub** [comment]
Ich nehme an es ist am besten wenn wir doch doppelte Werte erlauben und im Zweifelsfall anzeigen.

**Comment by mtrojan-ub** [comment]
Wurde umgestellt + funktioniert auf ptah.
https://ptah.ub.uni-tuebingen.de/Authority/719865778
