### ISSUE TITLE
Journal Online Print (JOP) Anzeige

### ISSUE THREAD

**Issue by socheres** [ubtue/tuefind#1422]
Jetzige Implementierung:
JOP wird nur dann aktiviert, wenn im MARC-Feld 022 (=PICA3 2010) eine ISSN steht. Bei der elektronischen Titlelaufnahme steht aber die eISSN im MARC-Feld 776  (=PICA3 2013), weshalb die JOP-Anzeige sowohl auf Gesamtaufnahme als auch auf Aufsatzebene nicht aktiviert wird.

Bsp:
https://ixtheo.de/Record/772489270 (elektronisch)
https://ixtheo.de/Record/129080373 (druck)
 
https://ixtheo.de/Record/518103242 (elektronisch)
https://ixtheo.de/Record/166761273 (druck)

https://ixtheo.de/Record/129884596 (elektronisch)
https://ixtheo.de/Record/1025365895 (druck)

**Comment by ruschein** [comment]
ISSNs aus 776$x werden importiert:

marc.properties:issn = 022a:440x:490x:730x:773x:776x:780x:785x
marc_ixtheo.properties:issn = 022a:029a:440x:490x:730x:773x:776x:780x:785x
marc_local.properties:issn = 022a:029a:440x:490x:730x:773x:776x:780x:785x

D.h., das sieht nach einem anderen Problem aus.

**Comment by socheres** [comment]
@jriedl 776$x  werden doch importiert.

**Comment by jriedl** [comment]
Es geht um die für die Bestimmung der ISSN innerhalb der JOP-Logik ausgewerteten Felder. Dies sind momenten 22 und 29 (wobei bei letzerem die Frage ist, ob es überhaupt noch mit ausgespielt wird). Elektronische Parallelausgaben haben deshalb keine JOP-Anzeige (da kein 22-Feld mit ISSN). Es stellt sich nun die Frage, ob 776x innerhalb der JOP-Logik dafür verwendet werden soll. Eventuelle Seiteneffekte sollten nächsten Dienstag besprochen werden.

**Comment by socheres** [comment]
hier die Info zu den ISSN-Felder von @IxTheoKm 

> hier nochmal die Mail vom letzten Jahr. Sie betraf aber tatsächlich nur die Erfassung der Vorgänger-/Nachfolger-ISSNs in Feld 2010.
Die parallelen Ausgaben stehen weiterhin in Feld 2013
2010: ISSN [MARC 022]
2013: ISSN paralleler Ausgaben [MARC 776]
2019: Formal falsche ISSN [MARC 022]
Sprich:
in der Aufnahme für die gedruckte Ausgabe steht neben Feld 2010 das Feld 2013 |o|... für die parallele Online-Ausgabe,
in der Aufnahme für die Online-Ausgabe steht neben Feld 2010 das Feld 2013 |p|... für die parallele Druckausgabe.
Natürlich jeweils sofern vorhanden.
a	ISSN für parallele Ausgaben auf einem anderen Datenträger
o	ISSN für parallele Ausgaben im Fernzugriff
p	ISSN für parallele Druckausgaben
f	fehlerhafte ISSN der parallelen Ausgabe
Damit dürften durch Auswertung von 022 und 776 alle Fälle erwischt werden.

@jriedl @ruschein es scheint so, dass für JOP-Anzeige elektronischer Zeitschriften 776x zusätzlich ausgewertet werden muss.

**Comment by jriedl** [comment]
Auf ptah

**Comment by thefass** [comment]
gelöst
