### ISSUE TITLE
RelBib Account: fehlende Übersetzung von "Meine Favoriten"

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#1427]
In der englischen Version fehlt im RelBib-Konto noch die englische Übersetzung für "Meine Favoriten":
![grafik](https://user-images.githubusercontent.com/25769591/112060623-b633ce80-8b5d-11eb-9a4b-23734dada8f9.png)

Vorschläge?
"My saved items" oder ...?

**Comment by mtrojan-ub** [comment]
Das liegt nicht an der Übersetzung, sondern die Liste heißt so. Wenn man als Benutzer zum ersten Mal einen Favoriten speichert, so wird man gebeten eine neue Liste dafür anzulegen. Der Name den man dafür eingibt wird zu diesem Zeitpunkt als defaultwert mit der Oberflächensprache angezeigt, die man in diesem Moment eingestellt hat. Der Namen bleibt dann mit der Liste gespeichert, egal welche Oberflächensprache man in Zukunft einstellt. Man kann ihn allerdings über die Funktion "Liste bearbeiten" ändern.

**Comment by relhei** [comment]
Ah, sorry - da hatte ich anscheinend die Liste so benannt. :-) Ist dann klar.
