### ISSUE TITLE
IHV nicht in Voltextsuche integriert

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#1428]
Bei diesem Titel ist nur die Zusammenfassung in der Volltxtsuche, obwohl es ein IHV gibt.
Warum ist das so?
https://www.ixtheo.de/Record/630715033#fulltextsearch

**Comment by jriedl** [comment]
Der Eintrag scheint in einem inkonsistenten Zustand gewesen zu sein. IHV nun durchsuchbar.

**Comment by thefass** [comment]
ok, Danke

**Comment by thefass** [comment]
Nachfrage: war das ein Zufallsfund oder können solche inkonsistenten Zustände auch bei anderen IHV vorkommen?

**Comment by jriedl** [comment]
Es lässt sich nicht natürlich ausschließen, dass weitere Fälle existieren. Nach einem Entfernen des Eintrags und einem manuellen Neuimport hat sich der Fehler nicht reproduzieren lassen.Sollten weitere Fälle bekannt werden, müsste man dem noch einmal nachgehen.

**Comment by thefass** [comment]
ok
