### ISSUE TITLE
Vermehrte SPAM-Mails über IxTheo-Feedback

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#1435]
Derzeit kommen vermehrt v.a. Werbe-Mails. Zum Teil mehrere täglich.
Zur Analyse werden ab jetzt die eingehenden Mails angehängt.

Vgl. 
https://github.com/ubtue/tuefind/issues/875
https://github.com/ubtue/tuefind/issues/295

**Comment by IxTheoKm** [comment]
[IxTheo Feedback_2021-03-24.txt](https://github.com/ubtue/tuefind/files/6195493/IxTheo.Feedback_2021-03-24.txt)

**Comment by ruschein** [comment]
Das ist eine seltsame Kodierung!  Alle Zeichen mit diakritischen Zeichen sind kaputt.


VG,

Johannes Ruscheinski

--
Dr. Johannes Ruscheinski
Universitätsbibliothek Tübingen - IT-Abteilung -
Wilhelmstr. 32, 72074 Tübingen

Tel: +49 7071 29-72820
FAX: +49 7071 29-5069
Email: ***@***.***

 The Sophisticate:  "The world isn't black and white.  No one does pure good or pure bad. It's all gray.  Therefore, no one is better than anyone else."
    The Zetet:  "Knowing only gray, you conclude that all grays are the same shade.  You mock the simplicity of the two-color view, yet you replace it with a one-color view..."
      —Marc Stiegler, David's Sling


________________________________

**Comment by IxTheoKm** [comment]
Bei mir funktioniert die Datei "IxTheo Feedback_...txt" mit Notepad++, Editor und WordPad problemlos

**Comment by IxTheoKm** [comment]
Bitte nochmals probieren: ich habe jetzt mit Unterstützung die Datei mit UTF8 kodiert und hoffe, dass es nun klappt.

**Comment by ruschein** [comment]
Sieht jetzt gut aus, danke!

**Comment by IxTheoKm** [comment]
[IxTheo Feedback3.txt](https://github.com/ubtue/tuefind/files/6219620/IxTheo.Feedback3.txt)

**Comment by IxTheoKm** [comment]
Feedback zu Derivat ...churchlaw.de
[IxTheo Exegetics Feedback.txt](https://github.com/ubtue/tuefind/files/6219625/IxTheo.Exegetics.Feedback.txt)

**Comment by IxTheoKm** [comment]
[IxTheo Feedback4.txt](https://github.com/ubtue/tuefind/files/6226970/IxTheo.Feedback4.txt)

[IxTheo Feedback5.txt](https://github.com/ubtue/tuefind/files/6226974/IxTheo.Feedback5.txt)

**Comment by IxTheoKm** [comment]
[IxTheo Feedback9.txt](https://github.com/ubtue/tuefind/files/6262875/IxTheo.Feedback9.txt)

[IxTheo Feedback8.txt](https://github.com/ubtue/tuefind/files/6262876/IxTheo.Feedback8.txt)

[IxTheo Feedback7.txt](https://github.com/ubtue/tuefind/files/6262877/IxTheo.Feedback7.txt)

[IxTheo Feedback6.txt](https://github.com/ubtue/tuefind/files/6262878/IxTheo.Feedback6.txt)

**Comment by mtrojan-ub** [comment]
Es kommt immer darauf an ob wir davon ausgehen, dass die Mail von einem Bot stammt oder nicht.
Da wir überall CAPTCHAs verwenden haben wir natürlich die Möglichkeit, die Komplexität des CAPTCHA weiter zu erhöhen. Somit wird es schwieriger zu entziffern und die Wahrscheinlichkeit dass sie durch Bots erkannt werden, verringert sich (also z.B. mehr "Rauschen"). Es kann natürlich auch sein dass solche Bots mittlerweile auch Machine Learning einsetzen und immer besser werden.
Alternativ sollten wir vielleicht auch irgendwann in Betracht ziehen, doch auf Google CAPTCHA umzusteigen. In der aktuellsten Version der Uni-Datenschutzerklärung sind mittlerweile auch Google-Cookies erlaubt. Evtl beinhaltet ja dann auch die Verwendung von reCAPTCHA, das wäre aber noch zu prüfen.

Wenn die Bots zu gut sind oder manche Firmen evtl auch Praktikantenim Marketing einsetzen um solche Mails zu verschicken, dann bringt so etwas natürlich nichts... in dem Fall könnte man evtl einen herkömmlichen Junk Filter verwenden um solche Mails auszusortieren. Das wäre dann aber wahrscheinlich eher etwas für den Mail-Client (z.B. Thunderbird) und weniger etwas für uns auf der Serverseite.

**Comment by IxTheoKm** [comment]
[IxTheo Feedback10.txt](https://github.com/ubtue/tuefind/files/6295295/IxTheo.Feedback10.txt)

[IxTheo Feedback11.txt](https://github.com/ubtue/tuefind/files/6295297/IxTheo.Feedback11.txt)

[IxTheo Feedback12.txt](https://github.com/ubtue/tuefind/files/6295300/IxTheo.Feedback12.txt)

[IxTheo Feedback13.txt](https://github.com/ubtue/tuefind/files/6295301/IxTheo.Feedback13.txt)

**Comment by IxTheoKm** [comment]
[IxTheo Feedback14.txt](https://github.com/ubtue/tuefind/files/6301985/IxTheo.Feedback14.txt)

**Comment by IxTheoKm** [comment]
[IxTheo Feedback15.txt](https://github.com/ubtue/tuefind/files/6304417/IxTheo.Feedback15.txt)

**Comment by IxTheoKm** [comment]
[IxTheo Feedback16.txt](https://github.com/ubtue/tuefind/files/6308685/IxTheo.Feedback16.txt)

**Comment by IxTheoKm** [comment]
[IxTheo Feedback17.txt](https://github.com/ubtue/tuefind/files/6323387/IxTheo.Feedback17.txt)

[IxTheo Feedback18.txt](https://github.com/ubtue/tuefind/files/6323389/IxTheo.Feedback18.txt)

**Comment by IxTheoKm** [comment]
[IxTheo Feedback19.txt](https://github.com/ubtue/tuefind/files/6333977/IxTheo.Feedback19.txt)

**Comment by IxTheoKm** [comment]
[IxTheo Exegetics Feedback2.txt](https://github.com/ubtue/tuefind/files/6375088/IxTheo.Exegetics.Feedback2.txt)

[IxTheo Feedback20.txt](https://github.com/ubtue/tuefind/files/6375090/IxTheo.Feedback20.txt)

[IxTheo Feedback21.txt](https://github.com/ubtue/tuefind/files/6375092/IxTheo.Feedback21.txt)

**Comment by IxTheoKm** [comment]
[IxTheo Feedback22.txt](https://github.com/ubtue/tuefind/files/6389551/IxTheo.Feedback22.txt)

**Comment by ruschein** [comment]
Mir ist aufgefallen, dass wir eventuell einen Teil der Email unterdrücken könnten und zwar die, die als Emailadresse XYZ@ixtheo.de eintragen.  Oder, was meint Ihr?

**Comment by IxTheoKm** [comment]
[IxTheo Feedback23.txt](https://github.com/ubtue/tuefind/files/6396668/IxTheo.Feedback23.txt)

**Comment by IxTheoKm** [comment]
[IxTheo Feedback24.txt](https://github.com/ubtue/tuefind/files/6413182/IxTheo.Feedback24.txt)

[IxTheo Feedback25.txt](https://github.com/ubtue/tuefind/files/6413183/IxTheo.Feedback25.txt)

[IxTheo Feedback26.txt](https://github.com/ubtue/tuefind/files/6413184/IxTheo.Feedback26.txt)

**Comment by IxTheoKm** [comment]
[IxTheo Feedback28.txt](https://github.com/ubtue/tuefind/files/6419351/IxTheo.Feedback28.txt)

[IxTheo Feedback29.txt](https://github.com/ubtue/tuefind/files/6419352/IxTheo.Feedback29.txt)

**Comment by IxTheoKm** [comment]
[IxTheo Feedback31.txt](https://github.com/ubtue/tuefind/files/6426613/IxTheo.Feedback31.txt)

**Comment by IxTheoKm** [comment]
[ReTurcite Supplier.txt](https://github.com/ubtue/tuefind/files/6432765/ReTurcite.Supplier.txt)

**Comment by IxTheoKm** [comment]
[IxTheo Feedback34.txt](https://github.com/ubtue/tuefind/files/6439322/IxTheo.Feedback34.txt)

**Comment by IxTheoKm** [comment]
[IxTheo Exegetics Feedback3.txt](https://github.com/ubtue/tuefind/files/6456904/IxTheo.Exegetics.Feedback3.txt)

**Comment by IxTheoKm** [comment]
[CP-S900C cheap manual thermal paper slitting machine --- from Havesino Agnes.txt](https://github.com/ubtue/tuefind/files/6466172/CP-S900C.cheap.manual.thermal.paper.slitting.machine.---.from.Havesino.Agnes.txt)

**Comment by IxTheoKm** [comment]
[IxTheo Feedback37.txt](https://github.com/ubtue/tuefind/files/6477005/IxTheo.Feedback37.txt)

[IxTheo Feedback38.txt](https://github.com/ubtue/tuefind/files/6477007/IxTheo.Feedback38.txt)

[Re  ixtheo.de  Digital Marketing Services....txt](https://github.com/ubtue/tuefind/files/6477008/Re.ixtheo.de.Digital.Marketing.Services.txt)

**Comment by IxTheoKm** [comment]
[IxTheo Feedback39.txt](https://github.com/ubtue/tuefind/files/6492248/IxTheo.Feedback39.txt)

**Comment by IxTheoKm** [comment]
[IxTheo Feedback40.txt](https://github.com/ubtue/tuefind/files/6501012/IxTheo.Feedback40.txt)

**Comment by IxTheoKm** [comment]
[IxTheo Feedback41.txt](https://github.com/ubtue/tuefind/files/6506691/IxTheo.Feedback41.txt)

**Comment by IxTheoKm** [comment]
[IxTheo Feedback43.txt](https://github.com/ubtue/tuefind/files/6537708/IxTheo.Feedback43.txt)

**Comment by IxTheoKm** [comment]
[IxTheo Feedback46.txt](https://github.com/ubtue/tuefind/files/6561097/IxTheo.Feedback46.txt)

**Comment by IxTheoKm** [comment]
[IxTheo Feedback47.txt](https://github.com/ubtue/tuefind/files/6574563/IxTheo.Feedback47.txt)

**Comment by IxTheoKm** [comment]
Ich habe jetzt über einen Zeitraum von gut zwei Monaten über 50 Beispiele von Spam-Mails gespeichert.
Wir sind also jetzt über Moskitonetze, Sonnenbrillen, Strandmatten, Leggings, Papierschneidemaschinen und vielerlei andere "nützliche" Dinge im Bilde. 

Ich denke, es braucht keine weiteren Beispiele mehr.

Die meisten enthalten, wie @ruschein schon bemerkt hat, tatsächlich ...@ixtheo.de
Wenn die unterdrückt werden könnten, wäre schon einiges gewonnen.
Für andere, die regelmäßig kommen (z.B. von einem Eric Jones) habe ich schon einen Filter gesetzt.

**Comment by mtrojan-ub** [comment]
Auf ptah kann jetzt die Änderung getestet werden => Wird als Absenderadresse eine Adresse angegeben die auf `@ixtheo.de` endet, so wird eine Fehlermeldung angezeigt und das Senden verhindert.

**Comment by ruschein** [comment]
> Auf ptah kann jetzt die Änderung getestet werden => Wird als Absenderadresse eine Adresse angegeben die auf `@ixtheo.de` endet, so wird eine Fehlermeldung angezeigt und das Senden verhindert.

Das halte ich für gefährlich denn dadurch lernen die Spammer solche Adressen nicht zu verwenden und verwenden dann andere.  Warum nicht einfach einen Filter der die stillschweigend wegwirft?

**Comment by mtrojan-ub** [comment]
Es wird eine Fehlermeldung angezeigt, aber kein HTTP Fehlercode generiert => wenn es sich um einen Bot handelt bekommt er es nicht mit. Ich würde vorschlagen dass wir es mal so ausprobieren und dann können wir ja noch weitere Verbesserungen vornehmen falls es dann immer noch zu viele Mails gibt.

**Comment by IxTheoKm** [comment]
Nach meinem Eindruck kommen nach anfänglichem Rückgang wieder mehr Spam-Mails.
Soll ich wieder "sammeln", oder müssen wir es hinnehmen?

**Comment by mtrojan-ub** [comment]
Hat das Filtern von `@ixtheo.de` Absendern geholfen bzw. funktioniert das korrekt?
Es hängt natürlich schon vom Muster der Mails ab, daher könnte Sammeln helfen, aber wir können auch keinen Spam-Filter mit vollem Funktionsumfang einbauen oder integrieren.

**Comment by IxTheoKm** [comment]
Das Filtern von @ixtheo.de Absendern scheint zu funktionieren. 

Was jetzt kommt, scheint mir kein Muster zu bieten (yahoo-, msn-Mails über IxTheo-Feedback; Business-Absender direkt an die IxTheo-Mailadresse). Ich sammle einfach mal weiter, um zu sehen, wieviel jetzt noch kommt. 
Dieses Issue schließe ich vorest und kann es ja wieder öffnen, falls die Mails überhandnehmen.

**Comment by relhei** [comment]
RelBib wird in letzter Zeit wieder häufiger über die Formulare "RelBib Feedback" und "Acquisition Request" mit Spam-Mails attackiert. Hier ein paar Beispiele:

[RelBib Feedback.txt](https://github.com/ubtue/tuefind/files/7302661/RelBib.Feedback.txt)
[RelBib Feedback1.txt](https://github.com/ubtue/tuefind/files/7302662/RelBib.Feedback1.txt)
[Acquisition Request.txt](https://github.com/ubtue/tuefind/files/7302663/Acquisition.Request.txt)
[Acquisition Request1.txt](https://github.com/ubtue/tuefind/files/7302664/Acquisition.Request1.txt)
[Acquisition Request2.txt](https://github.com/ubtue/tuefind/files/7302665/Acquisition.Request2.txt)
[Acquisition Request3.txt](https://github.com/ubtue/tuefind/files/7302666/Acquisition.Request3.txt)
[Acquisition Request4.txt](https://github.com/ubtue/tuefind/files/7302667/Acquisition.Request4.txt)
[Acquisition Request5.txt](https://github.com/ubtue/tuefind/files/7302668/Acquisition.Request5.txt)

**Comment by mtrojan-ub** [comment]
Für Mails die von außerhalb der Uni geschickt werden, betreibt das ZDV einen Spamfilter:
https://uni-tuebingen.de/einrichtungen/zentrum-fuer-datenverarbeitung/dienstleistungen/serverdienste/mail/viren-und-spamschutz/spamfilter/

Mails aus den Feedback-Formularen werden jedoch von unserem Server verschickt und haben daher bereits einen internen Absender. Wir werden uns mit dem ZDV abstimmen und prüfen, ob sich die Feedback-Mails so kennzeichnen lassen, dass sie vom ZDV Spamfilter als externe Mails eingestuft und ggf. ebenfalls gefiltert werden.

**Comment by mtrojan-ub** [comment]
Laut dem ZDV wäre es möglich Mails über den Spamfilter laufen zu lassen wenn wir sie über einen anderen Mailserver verschicken. Wir werden also in diese Richtung verschiedene Tests durchführen.

Außerdem wollen wir ja nicht pauschal für alle Mails den Spamfilter nutzen (da es ja z.B. schlecht wäre wenn die Status-Mails unserer cronjobs gefiltert werden). Daher müssen wir hier eine technische Trennung durchführen.

**Comment by mtrojan-ub** [comment]
Hinweis: Ptah ist noch nicht ganz fertig aufgesetzt, wir sind immer noch am Serverumzug, es stehen ggf. noch nicht alle anderen Funktionen zur Verfügung.

**Comment by thefass** [comment]
@IxTheoKm Wollen Sie nochmal testen oder könnte das Issue geschlossen werden?

**Comment by IxTheoKm** [comment]
Siehe auch https://github.com/ubtue/tuefind/issues/2210#issuecomment-1148805627 
Ich schließe daher.
