### ISSUE TITLE
Krimdok-Schlagwort-Facetten

### ISSUE THREAD

**Issue by jriedl** [ubtue/tuefind#1436]
Lokale 689-Schlagwörter werden nicht in den Facetten angezeigt: https://krimdok.uni-tuebingen.de/Search/Results?lookfor=id%3A1737748649&type=AllFields&limit=20&botprotect=. In Analogie zu den lokalen 650-Schlagwörtern sollten diese innerhalb der Pipeline in die regulären 689-Felder verschoben werden.

**Comment by thefass** [comment]
Einverstanden.
@IxTheoKm bitte verifizieren

**Comment by IxTheoKm** [comment]
Im Prinzip ist die Verschiebung in die regulären 689er Felder okay.

Nur sind Schlagwörter in 650 nicht lokal. Also: in Analogie zur den 650er Schlagwörtern auf Titelsatzebene:
Marc 650 = Pica 5520 (u.a.) Sachbegriff |s|
