### ISSUE TITLE
Tausendertrenner im Browse anders als in Facetten

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#1437]
Beispiel (Browse):
https://krimdok.uni-tuebingen.de/Browse/Author?findby=topic&query_field=topic_facet
![grafik](https://user-images.githubusercontent.com/26873381/112505363-004ec700-8d8d-11eb-89a5-954f55a0401c.png)

Beispiel (Facetten):
https://krimdok.uni-tuebingen.de/Search/Results?lookfor=&type=AllFields
![grafik](https://user-images.githubusercontent.com/26873381/112505469-19577800-8d8d-11eb-997e-778ecea22d6f.png)

Die Beispiele beziehen sich auf die Sprache Deutsch, hier sollte immer `.` und kein `,` als Tausendertrenner verwendet werden.

(Gemeldet per E-Mail durch @KStelzel)

**Comment by mtrojan-ub** [comment]
Das scheint auch in der offiziellen VuFind Demo ein Bug zu sein:
https://vufind.org/advanced_demo/Browse/LCC
https://vufind.org/advanced_demo/Search/Results?lookfor=&type=AllFields

**Comment by thefass** [comment]
@mtrojan-ub Willst du nochmal nachhacken oder leben wir damit. Sehr tragisch finde ich das nicht

**Comment by mtrojan-ub** [comment]
Hab den Fehler gefunden und bei uns lokal behoben, ready for testing auf ptah, ich stelle auch noch einen Pull Request an vufind-org.

**Comment by thefass** [comment]
sieht auf ptah gut aus. Ich schließe

**Comment by mtrojan-ub** [comment]
Der Bugfix PR für vufind-org wurde übrigens gestern bereits gestellt und übernommen.
