### ISSUE TITLE
VerfasserIn in der Vollanzeige

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#1438]
Bitte analog zu "VerfasserInnen" in der Vollanzeige "1. VerfasserIn" aufführen.

Bsp.:
https://ixtheo.de/Record/1751745988
![VerfasserInnen](https://user-images.githubusercontent.com/17004223/112976840-a156cc80-9155-11eb-9e27-a368092877b6.JPG)

https://ixtheo.de/Record/1668015145
![VerfasserIn](https://user-images.githubusercontent.com/17004223/112977144-03173680-9156-11eb-82fe-6742cd785c54.JPG)

**Comment by mtrojan-ub** [comment]
Ready for testing auf ptah

**Comment by IxTheoKm** [comment]
Danke, auf ptah in Ordnung
