### ISSUE TITLE
RelBib Newsfeed nicht aktuell

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#1446]
Der neueste Eintrag im RelBib Newsfeed datiert noch vom 29.3. 
https://www.relbib.de/RssFeed/Full
Bitte unbedingt aktualisieren, da von Fachseite (über die Mailingliste) jüngst auf den Aggregator aufmerksam gemacht wurde. Da macht sich eine so starke zeitliche Verzögerung nicht gut.

**Comment by mtrojan-ub** [comment]
Ich schau's mir heute an, habe aber viele Meetings

**Comment by mtrojan-ub** [comment]
OK, ist jetzt behoben.

(Der RSS Aggregator befindet sich auf ub16 in einem Zwischenzustand. Nach dem Einspielen der letzten Updates wurde der Aufruf im cronjob nicht angepasst => habe ich jetzt nachgeholt).

**Comment by relhei** [comment]
Das passt jetzt wieder. Danke!
