### ISSUE TITLE
Frage zu Lebensdaten in Normdaten

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#1452]
https://ptah.ub.uni-tuebingen.de/Authority/Record?id=706200489

![grafik](https://user-images.githubusercontent.com/26873381/114880456-5ea61d00-9e02-11eb-967c-61a4c44a0232.png)

Speziell zu 400d: `v1019-v1068`
Da beide Angaben vor Christus sind, ist ja eigentlich v1068 das frühere Jahr. Ist das dann trotzdem aus bibliothekarischer Sicht so richtig eingetragen, oder müsste es eigentlich als `v1068-v1019` hinterlegt werden?

**Comment by thefass** [comment]
@IxTheoKm Können Sie das bitte beantworten.

**Comment by IxTheoKm** [comment]
Das ist eindeutig eine Falscherfassung und muss im Normsatz korrigiert werden. Wird veranlasst.

**Comment by ruschein** [comment]
@IxTheoKm Im IxTheo ist es noch falsch.

**Comment by IxTheoKm** [comment]
Der Normsatz wurde am 22.04.2021 korrigiert. Ich weiß nicht, wie die Auslieferung von korrigierten Normsätzen läuft.
Durch Normsatzkorrekturen werden die damit verknüpften Titel aber m.W. nicht automatisch korrigiert. Greifen da nicht die sog. "Sekundärkorrekturen"? Ich weiß nicht, was technisch dabei abläuft. Aber wenn ein Normsatz mit hunderten oder gar tausenden verknüpften Titelsätzen korrigiert wird, kann man ja nicht alle Titelsätze aktualisieren, um sie neu auszuliefern.

**Comment by mtrojan-ub** [comment]
Es könnte sein, dass auf unserer Seite ein Problem beim Mergen der sekkor-Daten vorliegt.

Ausschnitt aus `WA-MARCk10comb-sekkor-210423.tar.gz`:

```
706200489:001:706200489
706200489:003:DE-627
706200489:005:202104222138.4
706200489:008:120427n||aznnnaabn           | aaa    |c
706200489:024:7 ahttp://d-nb.info/gnd/1231915212uri
706200489:035:  a(DE-627)706200489
706200489:035:  a(DE-588)123191521
706200489:035:  z(DE-588c)4651001-19v:zg
706200489:035:  z(DE-588a)1231915219v:zg
706200489:035:  a(DE-576)214663833
706200489:043:  cXR
706200489:065:  a16.5p2sswd
706200489:079:  agbpcvqsvpiz
706200489:100:0 aSalmanassarbII.cAssyrien, Königdv1068-v1019
706200489:400:0 aShalmanesarbII.cAssyria, Kingdv1068-v1019
706200489:400:0 aSalmanasserbII.cAssyrien, Königdv1068-v1019
706200489:400:0 aSchalman-eserbII.cAssyrien, Königdv1068-v1019
706200489:400:0 aShulmanu-asharidbII.cAssyrien, Königdv1068-v1019
706200489:548:  av1068-v10194datlwriLebensdaten
706200489:670:  aPauly, Cambridge Ancient Hist.
706200489:678:  bAssys. König, regierte 1031-1020 v.Chr.
```
Offenbar haben wir die Korrektur vom BSZ erhalten. Da der Datensatz scheinbar trotzdem in der Oberfläche auf dem alten Stand ist, müssen wir prüfen ob unsererseits ein Problem beim Merge vorliegt.

**Comment by mtrojan-ub** [comment]
Es gab unsererseits ein Problem beim Einspielen der Sekkor-Daten vom BSZ. In einer unserer Konfigurationsdateien war ein Dateinamensschema noch nicht auf k10plus umgestellt. Die Dateien wurden zwar heruntergeladen, aber beim merge in unseren Datenstand nicht berücksichtigt.

Wir müssen noch prüfen ob neue Korrekturen jetzt tatsächlich ankommen. Ich nehme an, dass wir die nächste sekkor-Datei am 14.05. erhalten werden und dann am 17.05. prüfen können ob die Änderung erfolgreich übernommen wurde.

Danach stellt sich die Frage was mit dem aktuellen Datenstand passiert. Wir könnten z.B. entweder mal wieder einen neuen Komplettabzug vom BSZ anfordern (letzter SA ist vom 04.08.2020), die Daten selbst neu aufbereiten (mühselig) oder noch einige Wochen warten bis wir die Normdatensuche offiziell live schalten und kurz vorher nochmal einen SA anfordern, sofern uns die fehlenden Änderungen bisher noch nicht allzu sehr stören.

**Comment by mtrojan-ub** [comment]
Beim Test sollten wir auch prüfen, ob die Änderung aus #1418 angekommen ist (PPN 519033175 Gascoigne). Mir ist noch aufgefallen, dass die sekkor-Dateien im Dateiname zwar immer den Freitag enthält (z.B. WA-MARCk10comb-sekkor-210507.tar.gz), aber erst mehrere Tage später bei uns ankommst, in diesem Fall z.B. hat die Datei auf ptah einen Download-Timestamp vom 11.05., also 4 Tage später.

**Comment by IxTheoKm** [comment]
https://ptah.ub.uni-tuebingen.de/Authority/Record?id=519033175

Korrektur vom 12.05.2021 ist im Datensatz umgesetzt

**Comment by IxKo** [comment]
@mtrojan-ub 
Es gibt ein sehr ähnliches Problem mit den Datensätzen von Herrn Lidke https://ixtheo.de/Search/Results?lookfor=lidke&type=Author&botprotect=
Sowohl hier als auch auf [ptah ](https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=lidke&type=Author&limit=20&botprotect=) werden seine Veröffentlichungen unter der nicht mehr aktuellen Namensansetzung angezeigt.
Der Normsatz wurde am 14.06. (also vor einer Woche) im K10plus als Ansetzungsform "Lidke, Jeffrey S." aktualisiert, aber auf VuFind wird er noch mit der alten Ansetzung "Lidke, Jeff" angezeigt.

**Comment by mtrojan-ub** [comment]
> Das ist eindeutig eine Falscherfassung und muss im Normsatz korrigiert werden. Wird veranlasst.

Bitte auch bei diesem Datensatz korrigieren:
706200489

Vom BSZ haben wir für diesen Datensatz folgende Änderungen erhalten:

WA-MARCk10comb-sekkor-210611.tar.gz (sekkor-aut.mrc):
```
1020491795:001:1020491795
1020491795:003:DE-627
1020491795:005:202106112139.1
1020491795:008:180506n||aznnnabbn           | aaa    |c
1020491795:024:7 ahttp://d-nb.info/gnd/115841112X2uri
1020491795:035:  a(DE-627)1020491795
1020491795:035:  a(DE-588)115841112X
1020491795:035:  a(DE-576)503944858
1020491795:040:  aDE-627bgercDE-627erakwbfrswk
1020491795:043:  cZZ
1020491795:079:  agbpcvqfvpiz
1020491795:100:1 aLidke, Jeff
1020491795:400:1 aLidke, Jeffrey S.
1020491795:400:1 aLidke, Jeffrey Stephen
1020491795:670:  aCDMARC names
1020491795:692:  aVishvarupa Mandir. - 1996
```

WA-MARCk10comb-sekkor-210618.tar.gz (sekkor-aut.mrc)
```
1020491795:001:1020491795
1020491795:003:DE-627
1020491795:005:202106142119.0
1020491795:008:180506n||aznnnabbn           | aaa    |c
1020491795:024:7 ahttp://d-nb.info/gnd/115841112X2uri
1020491795:035:  a(DE-627)1020491795
1020491795:035:  a(DE-588)115841112X
1020491795:035:  a(DE-576)503944858
1020491795:040:  aDE-627bgercDE-627erda
1020491795:043:  cXD-US
1020491795:065:  a4.7p2sswd
1020491795:065:  a3.1p2sswd
1020491795:079:  agbpcvqfqsvpiz
1020491795:100:1 aLidke, Jeffrey S.
1020491795:375:  a12iso5218
1020491795:377: 7aeng2iso639-2b
1020491795:400:1 aLidke, Jeffrey Stephen
1020491795:400:1 aLidke, Jeff
1020491795:550:  0(DE-627)2346028560(DE-576)2127644890(DE-588)4469962-1aReligionswissenschaftler4bercwriCharakteristischer Beruf
1020491795:550:  0(DE-627)1917529910(DE-576)2120431610(DE-588)4398864-7aReligionsphilosoph4beruwriBeruf
1020491795:670:  aLCAuth
1020491795:678:  bAssociate professor of religion am  Berry College in Rome, GA
1020491795:692:  aVishvarupa Mandir
```

Normdatenkorrekturen erhalten wir als "sekkor"-Daten. Diese erhalten wir nur einmal in der Woche. Außerdem werden diese erst immer einige Tage später vom BSZ bereit gestellt, also z.B. die Datei WA-MARCk10comb-sekkor-210618.tar.gz stand nicht wie der Dateiname vermuten lässt am 18.06. für uns zur Verfügung, sondern erst am 22.06 (und die mit Dateiname 11.6. erst am 15.6.).

**Comment by IxTheoKm** [comment]
>  > Das ist eindeutig eine Falscherfassung und muss im Normsatz korrigiert werden. Wird veranlasst.
> 
> Bitte auch bei diesem Datensatz korrigieren:
> 706200489
> 

Korrektur von PPN 706200489 wurde bereits am 22.04.2021 erledigt: 548 $av1068-v1019$4datl$wr$iLebensdaten

**Comment by mtrojan-ub** [comment]
Korrekturen soweit vorhanden. Momentan werten wir allerdings nur 400d aus. Es gibt Fälle in denen man hier kein brauchbares Ergebnis bekommt, ggf. sollte dann 548a mit einbezogen werden.

Beispiel:
https://ptah.ub.uni-tuebingen.de/Authority/1006354166/

**Comment by andreas-ub** [comment]
Hier ist z.B. (auch im 400er Feld) eine Zeitspanne von 1915-201 eingetragen:
http://ptah.ub.uni-tuebingen.de/Authority/691767920/Details#tabnav

Desweiteren gibt es viele 4-und-2-stellige Kombinationen, z.B.:
http://ptah.ub.uni-tuebingen.de/Authority/73087091X/Details#tabnav

Daher würde ich zusätzlich eine Plausibilitätsprüfung für Zeitspannen < 110 Jahre einbauen.

**Comment by IxTheoKm** [comment]
> Hier ist z.B. (auch im 400er Feld) eine Zeitspanne von 1915-201 eingetragen:
> http://ptah.ub.uni-tuebingen.de/Authority/691767920/Details#tabnav
> 
> Desweiteren gibt es viele 4-und-2-stellige Kombinationen, z.B.:
> http://ptah.ub.uni-tuebingen.de/Authority/73087091X/Details#tabnav

Beides sind Falscherfassungen. Die habe ich korrigiert.

**Comment by IxTheoKm** [comment]
> Momentan werten wir allerdings nur 400d aus. Es gibt Fälle in denen man hier kein brauchbares Ergebnis bekommt, ggf. sollte dann 548a mit einbezogen werden.
> 
> Beispiel:
> https://ptah.ub.uni-tuebingen.de/Authority/1006354166/

Wenn ich es richtig sehe, wird **400d** aus **548a $4datl** erzeugt.
Dieser Fall ist korrekt, da das Geburtsjahr unbekannt ist und nur das Sterbejahr erfasst werden kann.

Es gibt in diesem Fall zwar noch _zusätzlich_ Wirkungsdaten: i548 $av726-v722$4datw$wr$iWirkungsdaten
Das muss aber in unbedingt immer der Fall sein.

Auf jeden Fall scheint es mir sinnvoll, 548a auch noch mit einzubeziehen.

**Comment by mtrojan-ub** [comment]
548a wird nun ebenfalls einbezogen.

**Comment by mtrojan-ub** [comment]
Der neue SA wurde nun ebenfalls eingespielt. Da auch die Änderung hinsichtlich 400/548 bereits vor einiger Zeit vorgenommen wurde, würde ich den Issue schließen und einen neuen öffnen falls der Fehler erneut auftritt.
