### ISSUE TITLE
Frage zu Normdaten => Mehrfacheinträge

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#1453]
Die suche nach Autoren befindet sich derzeit noch im Aufbau. Gemäß Definition sollen nur Einträge angezeigt werden, die Personen, Körperschaften oder Tagungen sind (also entweder über Feld 100, 110 oder 111 verfügen).

Es gibt jedoch Einträge wie z.B. für Wolfgang Amadeus Mozart, in denen seine einzelnen Werke (z.B. "Die Zauberflöte") ebenfalls mit 100 gekennzeichnet sind. Diese werden dann ebenfalls mit angezeigt, Beispiel:
https://ptah.ub.uni-tuebingen.de/Authority/Search?hiddenFilters[]=type%3A%22*%22&lookfor=Mozart%2C+Wolfgang+Amadeus+1756-1791&type=AllFields

Gibt es ein zusätzliches Feld mit dem solche Einträge erkannt + ausgeschlossen werden können?

**Comment by IxTheoKm** [comment]
Werke habe das Unterfeld $t

![Werktitel](https://user-images.githubusercontent.com/17004223/115044012-5ff44a00-9ed5-11eb-81b7-a5ebd2be32af.JPG)

**Comment by mtrojan-ub** [comment]
@andreas-ub, kannst Du bitte wie besprochen die Unterscheidung einbauen?

**Comment by andreas-ub** [comment]
wurde mit Rückgabewert "work" eingebaut.

**Comment by mtrojan-ub** [comment]
Wird jetzt gefiltert

**Comment by IxTheoKm** [comment]
> Die suche nach Autoren befindet sich derzeit noch im Aufbau. Gemäß Definition sollen nur Einträge angezeigt werden, die Personen, Körperschaften oder Tagungen sind (also entweder über Feld 100, 110 oder 111 verfügen).

Auch Datensätze mit Feld 110 und 111 sind davon betroffen und können Werktitel sein (Werktitel mit Körperschaften oder Konferenzen als geistige Schöpfer).
Für diese müssen ebenfalls Datensätze mit $t gefiltert werden.

Bsp. für eine falsche Anzeige:
https://ptah.ub.uni-tuebingen.de/Authority/1014804396

![Werktitel_Kor](https://user-images.githubusercontent.com/17004223/134509672-04b99c04-ae13-4248-81ef-c22550343b22.JPG)

110 2 $aKatholische Kirche$4aut1$wr$iVerfasserschaft1$eVerfasserschaft1 **$t** Codex Iuris Canonici$f1917

Es könnten auch die Entitätencodierungen (s.u.) für Werktitel herangezogen werden. Es gibt allerdings immer wieder "Ausreißer" mit Falscherfassungen.
Entitätencodes für Werktitel:
![079_Werktitel_Entitätencodes](https://user-images.githubusercontent.com/17004223/134510940-c4590f16-ddde-4ead-aeb0-db9a8006ed1d.JPG)

**Comment by mtrojan-ub** [comment]
@andreas-ub, kannst Du das bitte übernehmen?

**Comment by mtrojan-ub** [comment]
Ab morgen ready for testing auf ptah

**Comment by mtrojan-ub** [comment]
@IxTheoKm: Die Autorensuche ist ja mittlerweile live. Gibt es zu diesem Issue noch etwas zu tun (insbesondere hinsichtlich 079) oder können wir den Issue schließen?

**Comment by IxTheoKm** [comment]
Ich habe keine Werktitel mehr in der Autorensuche gesehen. Da Unterfeld $t die Werktitel hoffentlich zuverlässig kennzeichnet, können wir auf 079 verzichten. Ich schließe daher.
