### ISSUE TITLE
Codexsuche CCEO funktioniert nicht

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#1455]
dieser Daten satz müßte mit der Codexsuche CCEO 881 gefunden werden:
https://www.ixtheo.de/Record/1646988930

tut aber nicht:
![Bildschirmfoto 2021-04-15 um 23 38 02](https://user-images.githubusercontent.com/14169098/114941631-b153f900-9e43-11eb-813a-4b6a66ffca9a.png)

**Comment by jriedl** [comment]
Bei diesem record sind die CCEO-Information in den 610-Feldern hinterlegt. Wir werten derzeit nur 689-Felder aus.

**Comment by IxTheoKm** [comment]
Sollte das nicht analog zur Bibelstellensuche funktionieren?
Bibelstellen werden ja sehr umfangreich in 610 (= PICA 5580) abgelegt.

**Comment by ruschein** [comment]
Auf Ptah.

**Comment by IxTheoKm** [comment]
Mit allen CCEO-Einträgen von PPN 1646988930 getestet: jetzt in Ordnung, danke!
