### ISSUE TITLE
Email Versand von Suchergebnissen funktioniert nicht

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#1456]
Ich habe bei folgender Suchabfrage 20 Titel markiert und per Mail verschickt
![Bildschirmfoto 2021-04-16 um 08 36 13](https://user-images.githubusercontent.com/14169098/114981831-e174b980-9e8e-11eb-98c8-461929e0642b.png)

Folgende Mail kommt:
![Bildschirmfoto 2021-04-16 um 08 37 17](https://user-images.githubusercontent.com/14169098/114981920-02d5a580-9e8f-11eb-8f9a-dfdb3ef8e745.png)

Wenn man dann auf den Link in der Mail klickt, kommt folgende Fehlermeldung:
![Bildschirmfoto 2021-04-16 um 08 38 11](https://user-images.githubusercontent.com/14169098/114981990-200a7400-9e8f-11eb-9e7a-d3638934a2bb.png)

**Comment by thefass** [comment]
@mtrojan-ub Könntest Du bitte mal schauen, ob sich das schnell beheben läßt. Wurde uns von einer französischen Kollegin gemeldet, die am Montag eine IxTheo Schulung durchführt

**Comment by mtrojan-ub** [comment]
Ich schaus mir schnellstmöglich an, muss allerdings heute auch eine Schulung vorbereiten + halten, daher kann es dauern.

**Comment by mtrojan-ub** [comment]
Problem ist reproduzierbar, vermutlich besteht das Problem seit dem VuFind 7 Upgrade.

**Comment by mtrojan-ub** [comment]
Habe das Problem auf die Schnelle behoben damit es wieder funktioniert (bitte ausprobieren).

Allerdings haben wir an dieser Stelle beim Upgrade einige Änderungen in VuFind 7 übersehen, die wir uns bei Gelegenheit noch im Detail näher anschauen sollten (hinsichtlich der Methode wie der Redirect genau funktioniert, als z.B. per HTTP oder HTML meta redirect.) Für den Live-Betrieb sollte das aber zunächst kein Problem mehr darstellen.

**Comment by derclou** [comment]
Ich habe es mit einer Liste mit 20 Ergebnissen probiert, hat funktioniert. Vielen Dank!

**Comment by thefass** [comment]
Prima, danke an @mtrojan-ub und @derclou 
@derclou : Bitte an die französische Kollegin kommunizieren
