### ISSUE TITLE
Alertpakete: irreführende Anzeige "Druck"

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#1460]
In der Anzeige der Alertpakete ist immer "Druck" enthalten:
https://www.relbib.de/Search/Results?type=AllFields&filter%5B%5D=%7Eformat%3A%22Subscription+Bundle%22
Das ist besonders irreführend bei dem Paket "Open Access Zeitschriften. 
Kann diese Anzeige entfernt bzw. korrigiert werden, falls der Aufwand nicht zu hoch? Z. B. so:
1. Anzeige "elektronisch", wenn nur elektronische Zss im Paket enthalten
2. Anzeige "elektronisch / Druck", wenn sowohl Druck- als auch elektronische Zss enthalten
3. Anzeige "Druck", wenn nur Druck-Zss enthalten
Das müsste dann natürlich dynamisch funktionieren.

**Comment by mtrojan-ub** [comment]
"Druck" wurde aus dem Template entfernt, der Rest kann ab dem nächsten Import geprüft werden (ab morgen früh).

**Comment by relhei** [comment]
Passt. Vielen Dank!
