### ISSUE TITLE
PPN-Listen von THEOLDI-Aufsätzen ohne Autor

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#1462]
Bei der THEOLDI-Migration wurden Datensätze migriert, bei denen die Autoren aus der STAR-Datenbank nicht mitgeliefert wurden. Diese müssen ausfindig gemacht und die Autorennamen nacherfasst werden.

Ich bitte dafür um die Ausgabe von PPN-Listen der Datensätze mit folgenden lokalen Abrufzeichen:

$0935 $a**iFSA**
$0935 $a**iSWA**
$0935 $a**iZSA**

Darin nur diejenigen Datensätze **ohne Autor in Feld 100**.

Bsp.:
iFSA: https://ixtheo.de/Record/1590007603#details
iSWA: https://ixtheo.de/Record/1589594177#details
iZSA: https://ixtheo.de/Record/1650161395#details

**Comment by ruschein** [comment]
Liste enthält 5740 Einträge.
[missing_authors_list.txt](https://github.com/ubtue/tuefind/files/6390762/missing_authors_list.txt)

**Comment by IxTheoKm** [comment]
Vielen Dank!
Ich habe nun ein paar Stichproben durchgeführt. Um die fehlenden Autoren aus der STAR-Datenbank nachführen zu können, brauchen wir eine neue Konkordanzliste, die außer der PPN die entsprechende ID aus der STAR-Datenbank enthält (PICA 7811, MARC 035 $a)

Können Sie uns diese bitte mit PPN und der ID aus Feld LOK 035 erstellen.
Bsp.:
https://ixtheo.de/Record/1589804678#details
 $0035 $a(DE-Tue135-1)**224927**

Benötigt wird jeweils nur die ID _ohne_ die ISIL (DE-Tue135-1)
![78011](https://user-images.githubusercontent.com/17004223/118233537-53422200-b492-11eb-81ff-e0a68d910b2d.JPG)

**Comment by ruschein** [comment]
@IxTheoKm Hier sind die Listen.
[iFSA+iSWA+iZSA.list.txt](https://github.com/ubtue/tuefind/files/6623664/iFSA%2BiSWA%2BiZSA.list.txt)
[iMON.list.txt](https://github.com/ubtue/tuefind/files/6623665/iMON.list.txt)

**Comment by IxTheoKm** [comment]
Vielen Dank!
Listen am 15.06.2021 an INIXTH verschickt zur Ergänzung der Autorennamen.

Nächste Schritte:
-Ergänzung der Autorennamen zu den K10plus-PPNs / IDs der STAR-Datenbank durch INIXTH
-Abgleich mit GND: ggf. Ergänzung der GND-Nummern (TUIXTH oder BSZ?)
-Lieferung der Konkordanzlisten ans BSZ
-Nachführung der 3000er Felder im K10plus ggf. mit PPN-Verknüpfung, sonst verbaler Erfassung der Autorennamen

**Comment by IxTheoKm** [comment]
Siehe https://github.com/ubtue/DatenProbleme/issues/1640:
Mit der Einspielung der fehlenden Autoren ist die Bereinigung, soweit sie maschinell möglich war, abgeschlossen. Ich schließe.
