### ISSUE TITLE
keine Alerts seit Ende März

### ISSUE THREAD

**Issue by Gazeller** [ubtue/tuefind#1463]
Am 29.3. erhielt ich zum letzten Mal eine Nachricht zu neuen Zeitschriftenaufsätzen der von mir alerteten Zeitschriften (full pack). Fiel mir leider erst jetzt auf. Vielleicht ein Fehler nach dem Vufind update?

**Comment by jriedl** [comment]
Es gab einen Fehler in der Generierung der Abfragen. Dieser sollte jetzt sowohl auf ptah als auch auf ub16 behoben sein, d.h. heute Abend das `new_journal_alert` auf beiden Systemen wieder ausgeführt werden.

**Comment by Gazeller** [comment]
Hat geklappt, gleich gestern Nacht kamen alerting mails. Ich schließe.
