### ISSUE TITLE
Reihenfolge falsch

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#1465]
Sortiert man nach Neueste zuerst, stimmt die Reihenfolge nicht:
https://krimdok.uni-tuebingen.de/Search/Results?lookfor=superior_ppn%3A630361657&type=AllFields&sort=year+desc%2C+issue_sort+desc%2C+start_page+asc&botprotect=

![Bildschirmfoto 2021-04-30 um 10 12 17](https://user-images.githubusercontent.com/14169098/116667562-a0a39700-a99c-11eb-95e5-43a8490c8b71.png)

**Comment by ruschein** [comment]
Ich vermute es wird einfach nach dem Jahr sortiert und das ist bei all diesen Datensätzen gleich.  Die Band- und Heftangaben sind im Nichtstandardfeld 936 welches vom Standard-VuFind bestimmt nicht berücksichtigt wird.  Das ist ein "interessantes" Problem! :-)

**Comment by thefass** [comment]
Das hat auf jeden Fall schonmal funktioniert, zumindest in IxTheo

**Comment by ruschein** [comment]
Ok, vielleicht liegt es dann an einem VuFind Update.

**Comment by mtrojan-ub** [comment]
Die Änderung ist jetzt testweise auf sobek aktiv. Allerdings ändert sich dadurch die URL:
https://sobek.ub.uni-tuebingen.de/Search/Results?lookfor=superior_ppn%3A630361657&type=AllFields&limit=20&sort=year+desc%2C+volume_sort+desc%2C+issue_sort+desc%2C+start_page+asc&botprotect=

**Comment by thefass** [comment]
Reihenfolge im Beispiel ist ok
