### ISSUE TITLE
Fehlende Übersetzung (+fehlerhafte Anzeige aus 780t?)

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#1472]
Auf der deutschen Oberfläche wird in der Volltitelanzeige die Zeilenbezeichnung für "Nachfolgender Titel" noch auf Englisch angezeigt: 
![grafik](https://user-images.githubusercontent.com/25769591/117015376-f4daae00-acf1-11eb-8f89-5a8d2fd27623.png)
https://www.relbib.de/Record/500571090?lng=de#details
Bitte anpassen. Danke!

Außerdem (ist aber nur bei diesem Beispiel aufgefallen) enden Nachfolgertitel und Vorgängertitel in der Anzeige mit .s bzw. .f. 
Das scheint nur in den Marc-Daten vorzukommen, nicht in den PICA-Daten, @socheres: Gibt es dafür eine Erklärung?

**Comment by mtrojan-ub** [comment]
Das scheint ein vufind-org Problem zu sein. Sowohl "Previous Title" als auch "Following Title" werden in vufind-org verwendet, wobei es nur ini-Einträge + Übersetzungen für "Previous Title" gibt. Ich melde es weiter.

**Comment by mtrojan-ub** [comment]
Sieht so aus als ob in den neueren Versionen der Text für "Following Title" durch "New Title" ersetzt wird. Ich ändere das entsprechend ab.

**Comment by mtrojan-ub** [comment]
Ready for testing auf ptah

**Comment by relhei** [comment]
Das passt jetzt. Danke!
Noch unklar ist, warum in MARC-Feld 780 Unterfeld |t am Ende .s steht bzw. in 785 |t am Ende .f
Diese "Endungen" sind nicht in der WinIBW nachvollziehbar.

**Comment by mtrojan-ub** [comment]
Die Datensätze haben wir so vom BSZ erhalten. Siehe auch:
https://swb.boss.bsz-bw.de/Record/(DE-627)500571090

![grafik](https://user-images.githubusercontent.com/26873381/120998067-05b28f80-c788-11eb-8886-aa2f0a17cf4e.png)

**Comment by relhei** [comment]
Dann wurden diese möglicherweise zwischenzeitlich korrigiert und wir warten den nächsten Abzug ab?
Mir fällt auf: Das BSZ verwendet "Späterer Titel" anstelle von "Nachfolgender Titel". Klingt etwas eleganter. Sollen wir uns anschließen?

**Comment by mtrojan-ub** [comment]
Von mir aus gerne, da "Späterer Titel" dem VuFind-Standard entspricht. Soll ich das ändern?

**Comment by relhei** [comment]
Ja, bitte.

**Comment by mtrojan-ub** [comment]
Die Übersetzung wurde auf ptah geändert.

"Dann wurde diese möglicherweise zwischenzeitlich korrigiert" => kann ich so nicht nachvollziehen. Gibt es einen Zeitstempel in der WinIBW? Es liegt jedenfalls bei uns kein Fehler vor, ich setze es mal auf "data problem".

**Comment by relhei** [comment]
Hab noch mal recherchiert und doch eine Angabe im Pica-Format gefunden, die damit korreliert: 
![grafik](https://user-images.githubusercontent.com/25769591/121009471-7e1f4d80-c794-11eb-826e-7902544240a5.png)

Es handelt sich lt. K10plus-Format-Dokumentation um eine "codierte Angabe für die Art der Vorgänger-Nachfolge-Beziehung".
https://swbtools.bsz-bw.de/cgi-bin/k10plushelp.pl?cmd=kat&val=4244&kattype=Standard

Komischerweise geht diese Info beim Umschalten in MARC-Format in der WinIBW verloren:
![grafik](https://user-images.githubusercontent.com/25769591/121010820-2a156880-c796-11eb-9476-c8056b3133e2.png)

Sollte nicht so in RelBib angezeigt werden. Es scheint, als ob es da ein Problem bei der Datenlieferung vom BSZ gibt?

Weiteres Beispiel mit dieser fehlerhaften Anzeige (. f) in RelBib:
https://www.relbib.de/Record/1744754586#details

Möglicherweise sind noch mehr Fälle zu erwarten.

**Comment by mtrojan-ub** [comment]
Ich werde eine Mail an Herrn Kühn schreiben und setze Dich in CC

**Comment by mtrojan-ub** [comment]
Es gab eine Antwort vom BSZ:

> Lieber Herr Trojan,
> 
> der Fehler im MARC-Export ist inzwischen repariert, wir nutzen diesen Indikatoren eigentlich nur für das Zuordnen des richtigen MARC-Feldes. Den betroffenen Titel habe ich scheinkorrigiert, sodass er mit dem nächsten Update bei Ihnen korrekt importiert werden sollte.
> 
> Viele Grüße
> Gerlind Ladisch

Der Fehler wurde also bestätigt + bereits behoben, und der Datensatz 500571090 wird voraussichtlich morgen früh erneut an uns ausgespielt. Falls es weitere Titel gibt müsste das dann wahrscheinlich direkt ans BSZ gemeldet werden. Da hier unsererseits kein Fehler vorliegt würde ich den Issue jetzt schonmal auf ready for testing setzen.

**Comment by relhei** [comment]
Hier nochmals die Frage, evt. auch @IxTheoKm: Sollen wir beim  BSZ anfragen, ob auch die anderen entsprechenden Fälle bereinigt werden können? Lassen sich diese Fälle irgendwie herausfiltern, um zu sehen, wie oft das vorkommt?

**Comment by IxTheoKm** [comment]
Wenn das ein Fehler im MARC-Export ist, kann das vermutlich nur das BSZ filtern.
@mtrojan-ub war diesbezüglich ja schon im Kontakt und könnte die Bitte um Bereinigung nachschieben. Ich kann nicht ermessen, wie viele Fälle es gibt, weil ich das nicht recherchieren kann.

**Comment by mtrojan-ub** [comment]
Ich habe mittels marc_grep eine Liste verdächtiger Datensätze erstellt und werde diese ans BSZ weiterleiten (ca. 1200 Einträge).
[780_785.txt](https://github.com/ubtue/tuefind/files/7097594/780_785.txt)

**Comment by mtrojan-ub** [comment]
Die Datensätze wurden durch das BSZ scheinkorrigiert und bei uns aktualisiert. Gibt es noch weitere Problemfälle?

**Comment by relhei** [comment]
Fehler nun nicht mehr bemerkt. Danke!
