### ISSUE TITLE
Times: fehlender Zeitstempel TIM

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#1474]
Ich habe einen Datensatz gefunden (zufällig),  der kein TIM hat:
https://www.ixtheo.de/Record/644602368#details

Verschlagwortet ist mit:
689     0     2     |q z  |2 gnd  |a Geschichte 586 v. Chr.-70

Könnten Sie dem bitte auf den Grund gehen, warum die Umsetzung in TIM fehlt

Evt. sind alle Zeiträume, die über die Zeitenwende hinüber gehen, betroffen.

**Comment by andreas-ub** [comment]
Die Bereichskonvertierung funktioniert offenbar nicht für Bereiche bc - ad, nur bc-bc und ad-ad

**Comment by andreas-ub** [comment]
Bereichskonvertierung ist angepasst, wird beim nächsten update aktiviert.

**Comment by thefass** [comment]
ok auf ptah und ixtheo. Super!
