### ISSUE TITLE
Times: Fehler bei Suche vor der Zeitenwende / über die Zeitenwende hinaus

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#1475]
Die Suche vor der Zeitenwende funktioniert nicht (oder vielleicht habe ich eine falsche Syntax?)
Implementiert war die Zeitsuche vor der Zeitenwende durch ein vorangestelltes v vor der Jahreszahl.

Wurde auf @ als Zeichen vor der Jahreszahl umgestellt?

Eine Suche mit z.B. @218-@201 funktioniert, bringt aber falsche Ergebnisse. 
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=%40218-%40201&type=TimeRangeSearch&limit=20&botprotect=
> Treffer *1 - 20* von *176.372* für Suche '*@218-@201*', Suchdauer: 17,30s 

Eine Suche nach v586-70 bringt auch seltsame Ergebnisse:
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=v586-70&type=TimeRangeSearch
> Treffer *1 - 20* von *176.372* für Suche '*v586-70*', Suchdauer: 17,31s 

Da die Treffermenge immer gleich ist, vermute ich ein allgemeines Problem bei einer Suche vor / über die Zeitenwende hinaus

**Comment by andreas-ub** [comment]
Hier gab es einen Unterschied zwischen Live-Umgebung und Testumgebung.
Die Codierung in der Vorverarbeitung für v.Chr.-Werte wurde angepasst (12 stellig mit führender 0), sodass die anschließende Einschränkung funktioniert. Ptah Server ist aktualisiert.
Die Zeitbereichssuche v9000-v800 liefert nun Treffer.

**Comment by andreas-ub** [comment]
Bei Suchen v700-700 scheint die Trefferanzahl und Auswahl nicht zu passen (ixtheo und ptah)

**Comment by andreas-ub** [comment]
Die Bereichskonvertierung funktioniert offenbar nicht für Bereiche bc - ad, nur bc-bc und ad-ad

**Comment by thefass** [comment]
Ja, die Suche bc-bc klappt.

**Comment by andreas-ub** [comment]
Bereichskonvertierung ist angepasst, wird beim nächsten update aktiviert.

**Comment by thefass** [comment]
ok auf ptha und ixtheo
