### ISSUE TITLE
Times: Sortierung

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#1476]
Die Suche nach 1548 hat in den Treffern 32-35 folgende Sortierung:

32: Geschichte 1546-1551
33: Geschichte 1544-1549
34: Geschichte 1543-1548
35: Geschichte 1546-1551

![Bildschirmfoto 2021-05-05 um 09 48 57](https://user-images.githubusercontent.com/14169098/117116172-52243d00-ad8e-11eb-8b91-58e2ffd4e861.png)

Das sind alles 5 Jahreszeiträume, insgesamt stehen sie im Ranking richtig. Ich hätte nur erwartet, dass 32 und 35 untereinander kommen und nicht getrennt werden.
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=1548&type=TimeRangeSearch

**Comment by andreas-ub** [comment]
Die generierten TIM-Einträge sind identisch bei Treffer 32 und Treffer 35:
   868546526 - TIM 			|a 100015460101_100015511231 
 1602412987-  TIM 			|a 100015460101_100015511231

Der Scoring-Wert wird anhand der Zahlendifferenzen zischen Bereich und Vergleichsbereich berechnet, der Start- und Endwert des Bereichs spielen zunächst keine Rolle für den Scoring-Wert. Wenn mehrere gleiche Scoring-Werte existieren ist die Sortierreihenfolge nicht definiert.

Die Sortierreihenfolge konnten wir jedoch in der Anzeige so anpassen, dass die Sortierreihenfolge 1. Scoring, 2. time_ranges_asc lautet.

Wird beim nächsten Update aktiviert.

**Comment by thefass** [comment]
auf ptah und ixtheo ok
