### ISSUE TITLE
Times: SW mit Zeitangaben noch nicht umgesetzt

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#1478]
Es gibt Sachschlagwörter mit einer Zeitangabe in der Verweisungsform 450

Beispiel:
PPN des Normdatensatzes: 209142537
150 $aUrchristentum
450 $aKirchengeschichte 30-100 

Siehe: https://github.com/ubtue/tuefind/wiki/Times#sachschlagw%C3%B6rter <br>
Die 450 wird noch nicht ausgewertet.

Beispiel: In https://www.ixtheo.de/Record/1640843515#details fehlt TIM

**Comment by andreas-ub** [comment]
Momentan beruht die Auswertung auf Feld 548:
Wenn ein Unterfeld 'i' mit 'Zeitraum' vorhanden ist, wird der Inhalt aus Unterfeld 'a' verwendet.

**Comment by andreas-ub** [comment]
Normdaten-ID (627): 10445198X

Zusätzlich zu der bisherigen 548-Auswertung müssten Normdaten für die Ermittlung verwendet werden, die
- ein Feld 450 mit einem gültigen Schlagwort enthalten
- hinter diesem Schlagwort muss eine gültige Zeitangabe stehen.

Solange keine Mehrfachbereichsinterpretation umgesetzt ist, könnte die 450 Auwertung hinter der 548 Auswertung erfolgen (d.h. 450 Auswertung, wenn 548 Auswertung keinen Treffer ergab).

**Comment by mtrojan-ub** [comment]
Für dieses Thema ist eine konzeptionelle Überarbeitung an mehreren Baustellen notwendig. Diese ist relativ zeitaufwendig und kann daher nicht unmittelbar umgesetzt werden. Wir müssen das Thema also priorisieren und werden es angehen wenn es die Zeit zulässt.

**Comment by mtrojan-ub** [comment]
Sorry, falscher Issue => gemeint war #1477.

Für den aktuellen Issue 1478 werden wir schauen was sich machen lässt, da aber die Präsentation schon am Montag statt findet wissen wir noch nicht ob die Umsetzung bis dahin klappt, außerdem würden wir es maximal bis dahin auf ptah einspielen um Überraschungen bei der Präsentation am Montag zu vermeiden.

**Comment by thefass** [comment]
ok. DAnke!

**Comment by andreas-ub** [comment]
- TIM-Feld in Test-Umgebung nun vorhanden: http://ptah.ub.uni-tuebingen.de/Record/1640843515#details

- Anezigefeld TIMb erweitert, z.B. steht nun "Mittelalter 500-1500 " bei http://ptah.ub.uni-tuebingen.de/Record/1576115968#details

**Comment by andreas-ub** [comment]
Die Zeitbereichssuche auf der Testumgebung nach 68-72 enthält nun ggf. ein Schlagwort im Anzeigetext

Shedding light on judean refugees
Strange, James Riley 1963- (Author)
in: Biblical archaeology review, 46 (2020), 2, Seite 18-19
**Jüdischer Krieg** 66-70

**Comment by thefass** [comment]
sehr gute Lösung

**Comment by relhei** [comment]
Wird die Entwicklung auch auf RelBib nachgezogen? Das wäre wünschenswert :-)

**Comment by thefass** [comment]
ja, das müssen wir auf jeden Fall machen. Auch in KrimDok wäre das sinnvoll. Allerdings nicht Bibelstellen und Codices, sondern nur Zeitsuche

**Comment by mtrojan-ub** [comment]
Für RelBib lässt sich das wahrscheinlich relativ schnell freischalten. Für KrimDok steckt um einiges mehr Aufwand dahinter, da Anpassungen an mehreren Stellen notwendig sind die im Falle von IxTheo+RelBib schon erfolgt sind (Pipeline, Solr-Index, RecordDriver, etc.)

**Comment by thefass** [comment]
ok, dann doch erstmal für relbib. krimdok kann dann in der prioritätenliste festgelegt werden

**Comment by mtrojan-ub** [comment]
Die Zeitbereichssuche ist jetzt auf ptah auch für RelBib aktiv und kann dort getestet werden.

**Comment by thefass** [comment]
@relhei Übernimmst du das bitte?

**Comment by relhei** [comment]
Ja gerne.

**Comment by relhei** [comment]
Ich habe mal ein Beispiel auf dem Testsystem von RelBib recherchiert, das das Sachschlagwort "Römerzeit" enthält.
Die Anzeige stimmt noch nicht:
![grafik](https://user-images.githubusercontent.com/25769591/125599316-9ec676fa-59d3-4a0a-bacb-ca76cbfbff1c.png)

![grafik](https://user-images.githubusercontent.com/25769591/125599290-f826b970-84e1-403e-8011-c5b346c8a256.png)

Und hierzu noch der Datensatz zum Sachschlagwort:
![grafik](https://user-images.githubusercontent.com/25769591/125599683-69cfed48-9674-4816-a36d-860c1bf6be1b.png)

**Comment by thefass** [comment]
@relhei Dass in Relbib kein Titel mit exakt 50-1000 gefunden wird, ist kein Fehler, sondern hat damit zu tun, dass es keinen solchen Titel gibt. Die Suche mit 50-1000 fördert im IxTheo auch nur 5 Titel zu Tage, die alle kein SSG 0 haben. Insofern sind die Titel mit 30-1000 dann die am nächsten gelegenen und werden angezeigt.

**Comment by thefass** [comment]
Die Autosuggest Vorschläge sind in der Tat irritierend. Selbst wenn sie einen brauchbaren Treffer haben, den der Nutzer dann in den Schlitz übernimmt, führt die Suche zu keinem Ergebnis, denn der Nutzer müßte den Suchaspekt auf alle Felder ändern. Bei voreingestelltem Suchaspekt "Zeitbereiche" funktioniert ja nur eine Zeitrange
Vielleicht wäre es das beste, beim Suchaspekt "Zeitbereiche" ganz auf ein Autosuggest zu verzichten

**Comment by mtrojan-ub** [comment]
Autosuggest für die Zeitbereichssuche ist jetzt auf ptah deaktiviert.

**Comment by thefass** [comment]
ja, funktioniert
