### ISSUE TITLE
Ptah bug

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#1485]
Ptah kann zwar aufgerufen werden, eine Suche führt aber zu einem Fehler:

"/usr/local/var/log/tuefind/vufind.log" cannot be opened with mode "a"

**Comment by thefass** [comment]
geht wieder. Gibt es einen erkennbaren Grund?

**Comment by jriedl** [comment]
Zugriffsrechte am Samteg angepasst.

**Comment by thefass** [comment]
Danke
