### ISSUE TITLE
Probleme mit responsive design

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#1490]
In einer bestimmten Skalierung (bei mir etwas mehr als der halbe Bildschirm) der Portalwebsite kann man den Pfeil der Dropdownliste der "Sortieren"-Funktion nicht anklicken, vmtl. weil er in die Facette "Erscheinungsjahr" hineinragt:
![grafik](https://user-images.githubusercontent.com/25769591/117817423-df243600-b267-11eb-9e87-35fd25e83d7c.png)
Mit Bitte um Anpassung.

**Comment by mtrojan-ub** [comment]
Bei mir nicht reproduzierbar. Welcher Browser wurde in welcher Version verwendet?

**Comment by relhei** [comment]
Ok, auf dem Arbeitsrechner in der UB auch nicht mehr nachvollziehbar.
Aber dieses Problem besteht hier noch (bzw. neu):
![grafik](https://user-images.githubusercontent.com/25769591/122540250-be9a8900-d028-11eb-96e9-c4dab0ea93e4.png)

Die Trefferzahlen springen an manchen Stellen aus der Facette heraus.
Lässt sich da noch was nachjustieren?

**Comment by mtrojan-ub** [comment]
OK, ich schau's mir an, das scheint aber nur bei Bildschirmbreiten >= 768px und <= 992px der Fall zu sein.

**Comment by mtrojan-ub** [comment]
Liegt an langen Wörtern wie z.B. "Sozialwissenschaften". Ich habe jetzt auf ptah die automatische Silbentrennung in Facetten aktiviert => ready for testing.

![grafik](https://user-images.githubusercontent.com/26873381/122573019-9f165700-d04e-11eb-9c6f-2ac424d6b014.png)

**Comment by relhei** [comment]
Sieht jetzt sauber aus. Danke!
