### ISSUE TITLE
Codexsuche: Kurztitelanzeige

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#1491]
Bitte auch bei der Codexsuche die Codexangaben wie bei der Bibelstellensuche in der Kurztitelanzeige anzeigen.
siehe: https://github.com/ubtue/tuefind/wiki/Codices

**Comment by andreas-ub** [comment]
Beispieldatensatz Bibelstellensuche: http://ptah.ub.uni-tuebingen.de/Record/1745834966#details

Anzeigetext: Mt, Mt 9:20–22, Mk, Mk 5:25–34, Lk, Lk 8:43–48

BIR-Feld: 

\|a 01000000_01999999,01009020_01009022,02000000_02999999,02005025_02005034,03000000_03999999,03008043_03008048    \|b biblesearch

Der decodierte Anzeigestring ist nicht direkt im Record bzw. Solr vorhanden, vermutlich passiert er im ixTheo / vufind - Viewbereich.

**Comment by andreas-ub** [comment]
bei den Canones ist das Bereichsfeld "CAL"

hier ist z.B. beim Datensatz http://ptah.ub.uni-tuebingen.de/Record/1468880608#details

CAL \|a 207900000_207909999

enthalten.

**Comment by mtrojan-ub** [comment]
Beispiel-URL für Suchergebnis:
http://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=CIC83+790%2C1-2&type=CanonesRangeSearch&limit=20

**Comment by mtrojan-ub** [comment]
Kann jetzt auf ptah getestet werden

**Comment by thefass** [comment]
funktioniert sehr gut.
Könnten die Angaben wie bei der Bibelstellensuche in eine kommaseparierte Zeile? Würde den Kurztitel  nicht so aufblähen.

![Bildschirmfoto 2021-05-12 um 15 31 42](https://user-images.githubusercontent.com/14169098/117983523-570d6180-b337-11eb-95b0-99c9e15e59ce.png)

**Comment by thefass** [comment]
Bitte nicht nur auf ixtheo, sondern auch auf https://canonlaw.ixtheo.de und https://bible.ixtheo.de implementieren

**Comment by mtrojan-ub** [comment]
Anzeige wurde auf komma-separiert umgestellt. Die Änderung ist auch für bible+canonlaw aktiv, das lässt sich auch auf ptah testen:
https://ptah.ub.uni-tuebingen.de:4443/Search/Results?lookfor=CIC83&type=CanonesRangeSearch&limit=20
https://ptah.ub.uni-tuebingen.de:4447/Search/Results?lookfor=CIC83&type=CanonesRangeSearch&limit=20

**Comment by thefass** [comment]
funktioniert auf allen drei
