### ISSUE TITLE
Medienart "Software": Titel falsch zugeordnet

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#1492]
Der Medienart "Software" sollten nur Titel zugeordnet werden, die in Marc-Feld 336 die Bezeichnung "Computerprogramm" enthalten. Aktuell werden da auch andere Feldinhalte als Medienart "Software" ausgelesen - das ist falsch. 
Wir haben einen Workshop mit DH-affinen Religionswissenschaftler*innen, die das verwirren könnte...

Hier die beiden Suchabfragen in RelBib und IxTheo:
https://www.relbib.de/Search/Results?type=AllFields&filter%5B%5D=%7Eformat%3A%22Software%22

https://ixtheo.de/Search/Results?lookfor=&type=AllFields&filter%5B%5D=%7Eformat%3A%22Software%22&limit=20&botprotect=

Bitte prüfen und nachjustieren.

**Comment by mtrojan-ub** [comment]
Hierzu wurde soeben eine Änderung auf ptah eingespielt. Diese kann ab dem nächsten Import geprüft werden, also frühestens morgen Vormittag.

**Comment by mtrojan-ub** [comment]
Kann jetzt auf ptah getestet werden:

IxTheo (160/1,350):
https://ptah.ub.uni-tuebingen.de/Search/Results?type=AllFields&filter%5B%5D=%7Eformat%3A%22Software%22
https://ixtheo.de/Search/Results?type=AllFields&filter%5B%5D=%7Eformat%3A%22Software%22

RelBib (88/364):
https://ptah.ub.uni-tuebingen.de:4448/Search/Results?type=AllFields&filter[]=~format%3A%22Software%22
https://relbib.de/Search/Results?type=AllFields&filter%5B%5D=%7Eformat%3A%22Software%22

"Software" war immer ein ziemlich harter Fallback. Von daher wäre noch die Frage offen, ob die rausgefallenen Datensätze jetzt mit einer anderen Medienart gekennzeichnet werden müssen?

**Comment by relhei** [comment]
Mit Stichprobe habe ich jetzt in den verlinkten Titellisten auf Anhieb keinen Titel gefunden, der tatsächlich als "Software" (Computerprogramm) bezeichnet werden könnte. Jeder der aufgeführten Titel hat auch noch eine andere Medienart - Zeitschrift, Buch o.ä. In Kombination mit Medientyp "elektronisch" ist das dann eigentlich klar. Überlegenswert wäre eher, das Feld 338 auszulesen und entsprechend in die Facette Medienart zu übernehmen: Einige der Titel sind nämlich CD-ROM. Dann wüssten Nutzende, mit welchem Medium sie zur rechnen haben. 

Ich plädiere weiterhin dafür, dass nur Titel als Medienart "Software" angegeben werden sollten, die in Marc-Feld 336 die Bezeichnung "Computerprogramm" enthalten. 

Wie sieht das @IxTheoKm?

**Comment by relhei** [comment]
@thefass und @IxTheoKm bitte noch mal anschauen und rückmelden.

**Comment by IxTheoKm** [comment]
> Ich plädiere weiterhin dafür, dass nur Titel als Medienart "Software" angegeben werden sollten, die in Marc-Feld 336 die Bezeichnung "Computerprogramm" enthalten.

Sehe ich genauso.

**Comment by thefass** [comment]
sehe ich auch si

**Comment by mtrojan-ub** [comment]
@relhei: Kann der Issue also geschlossen werden?

**Comment by relhei** [comment]
Ja, danke!

**Comment by IxTheoKm** [comment]
Auf ptah scheint das aber noch nicht umgesetzt zu sein:
https://ptah.ub.uni-tuebingen.de/Search/Results?type=AllFields&filter%5B%5D=%7Eformat%3A%22Software%22

Im K10plus gibt es nur ca. 10 Datensätze mit 336 Computerprogramm

**Comment by relhei** [comment]
O, da hab ich gar nicht geprüft diesmal - sorry!

**Comment by mtrojan-ub** [comment]
Die Menge der als "Software" eingestuften Datensätze hat sich durch die erste Änderung bereits stark reduziert.
Die restlichen Fälle scheinen basierend auf ihrer Kennzeichnung in 007 in verschiedene andere Kategorien eingestuft zu werden, die dann aufgrund der format_map.properties dennoch auf "Software" gemappt werden:

https://github.com/ubtue/tuefind/blob/master/import/translation_maps/format_map.properties

```
CDROM
ChipCartridge
DiscCartridge
FloppyDisk
TapeCartridge
TapeCassette
TapeReel
```
Wenn diese nicht als "Software" eingestuft werden sollen, als was sollen sie dann stattdessen eingestuft werden? Oder soll die Kennzeichnung in diesen Fällen komplett entfernt werden?

https://ptah.ub.uni-tuebingen.de/Record/68032531X

**Comment by thefass** [comment]
Wir haben ja ansonsten noch CD, DVD, blue-raydisc
Was wäre, wenn wir obige Fälle unter "CDROM u.a." zusammenfassen?

**Comment by mtrojan-ub** [comment]
Gibt es noch weitere Meinungen dazu, z.B. von @thefass?

**Comment by relhei** [comment]
Eine geeignetere Bezeichnung fällt mir auch nicht auf Anhieb ein. Würde ebenfalls eine Zusammenfassung dieser Fälle unter CD-ROM u.a.befürworten.

**Comment by mtrojan-ub** [comment]
Heute im Meeting besprochen => "Datenträger" wäre ein guter Begriff.
Was wäre die passende englische Entsprechung? "data medium"?

**Comment by mtrojan-ub** [comment]
Wir haben es mal so entsprechend eingetragen. Ab morgen ready for testing auf ptah.

**Comment by relhei** [comment]
Passt. Vielen Dank!
