### ISSUE TITLE
Anzeige von Codex-Paragraphen in SW aus 610 fehlt

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#1498]
https://ptah.ub.uni-tuebingen.de/Record/1650139438#details

Vermutlich wird aus der ersten 610 |p 6 in der ersten Zeile in "weitere Schlagwörter" nicht angezeigt (aber in der Codexsuche verwendet). Bitte mit anzeigen

![Bildschirmfoto 2021-05-12 um 16 02 03](https://user-images.githubusercontent.com/14169098/117988291-9047d080-b33b-11eb-8bcd-beb3367a584c.png)

![Bildschirmfoto 2021-05-12 um 16 04 22](https://user-images.githubusercontent.com/14169098/117988583-d8ff8980-b33b-11eb-9c24-02e7a7253ba4.png)

**Comment by jriedl** [comment]
Sollte auf ptah nach dem nächsten Import behoben sein.

**Comment by thefass** [comment]
ist ok.
Kann die Darstellung bitte so erfolgen:
Katholische Kirche Codex iuris canonici 1983, §6
Katholische Kirche Codex iuris canonici 1983, §§1-203 (wenn das zu kompliziert, dann:
Katholische Kirche Codex iuris canonici 1983, §1-203

**Comment by jriedl** [comment]
Auf ptah. Da für $p das Standardtrennzeichen '.' ist, wird es auch hier verwendet.

**Comment by thefass** [comment]
ok. Punkt ist auch ok
