### ISSUE TITLE
"Keine Ergebnisse" bei Trefferauswahl aus Facette

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#150]
Ich möchte gerne den falsch erfassten Eintrag in der Primärquelle korrigieren, kann aber keinen Treffer dazu finden, da nur die Meldung "Keine Ergebnisse" kommt:
![aufsatzsammlung](https://user-images.githubusercontent.com/17004223/34823374-6a8eda0e-f6ca-11e7-8273-15bf4493e747.png)

**Comment by ruschein** [comment]
@IxTheoKm Es handelt sich um die PPN 343536757.

**Comment by IxTheoKm** [comment]
Danke! Habe den Datensatz korrigiert.
