### ISSUE TITLE
Fehlende Anzeige von Unterfeld g beim Volltitel und in der Facette Region (Schlagwort)

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#151]
Bsp.:
https://ptah.ub.uni-tuebingen.de/Record/314113908#details
https://ptah.ub.uni-tuebingen.de/Record/041036190#details

![region](https://user-images.githubusercontent.com/17004223/34833346-70e1fb64-f6ef-11e7-9a0d-c55a7e7c56d8.png)

Die Anzeige für das Unterfeld g (Ort) muss sowohl in der Facette als auch in der Vollanzeige des Titels mit runden Klammern erfolgen:
2000 Jahre Christentum (Braunschweig)
7000 Eichen (Kassel)

(Die Einträge 2013 und 2014 in der Facette sind Falscherfassungen und bereits korrigiert.)

**Comment by jriedl** [comment]
Auf ptah behoben.

**Comment by IxTheoKm** [comment]
Auf ptah jetzt o.k. Danke
