### ISSUE TITLE
Glocke-Symbol: auch bei Zeitschriften ohne Aufsatzerschließung

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#1521]
![grafik](https://user-images.githubusercontent.com/25769591/122560365-d120bc80-d040-11eb-8c5b-66248afdd945.png)

Das Glocke-Symbol wird bei ALLEN Zeitschriften angezeigt, unabhängig davon, ob wir diese auf Aufsatzebene erschließen oder nicht. Kann das evt. auch dynamisch angepasst werden? Also dass das Abonnieren erst möglich ist, wenn es Aufsätze gibt? Evt. über ZEDER-Spalte "kat"?
Denn so könnte es sein, das Nutzer*innen eine Zeitschrift abonnieren und sich wundern, da nie eine Meldung kommt.

**Comment by mtrojan-ub** [comment]
- Besteht die Möglichkeit, dass wir für bestimmte Zeitschriften neue Artikel erhalten die von anderen Institutionen erschlossen werden? (Beispielsweise in IxTheo umfasst die Facette "Schriftenreihe/Zeitschrift" ja allein ca. 40.000 Datensätze. Erhalten alle wirklich nur dann neue Aufsätze, wenn wir diese hausintern erschließen?)
- Zeder wäre umständlich. Ist Information auch in MARC21 einsehbar ob wir eine Zeitschrift auf Aufsatzebene erschließen? (Lokaldaten o.Ä.)
- Wäre eine Alternative evtl. dass unterhalb einer Zeitschrift bereits mindestens 1 Aufsatz existieren muss, bevor man die Alertingfunktion für diese Zeitschrift nutzen kann?

**Comment by relhei** [comment]
Zu 1.: Es gibt auch extern erschlossene Zeitschriften. Das ist auch in ZEDER festgehalten. Wenn in kat "IxTheo" steht, umfasst das aber im Normalfall auch diese. Nur bei den Lieferungen von der BSB bin ich mir nicht so sicher, wobei ich da auch den aktuellen Stand nicht kenne, @thefass 
Zu 2.: Zeitschriften in der hausinternen Aufsatzerschließung erhalten m.W. das lokale Abrufzeichen "ixze", die anhängenden Aufsätze "ixzs". Allerdings würden wir damit möglicherweise die extern erschlossenen Ausätze ausschließen (außer bei den Kooperationspartnern? @IxTheoKm)
Zu 3.: Den letzten Vorschlag finde ich auf Anhieb gut, klingt auch relativ einfach in der Umsetzung. Allerdings müssten wir damit leben, dass auch eingestellte Zeitschriften dann noch abonnierbar bleiben.

**Comment by IxTheoKm** [comment]
Zu 1.: In kat steht nur "IxTheo", wenn von irgendjemandem diese Zeitschrift aktiv ausgewertet wird (wir oder Kooperationspartner). Diejenigen, die noch nicht aktiv ausgewertet werden aber vorgesehen sind, sollten eigentlich in kat "Prio..." haben. Wenn man das an Spalte kat festmachen würde, würde man diejenigen Zeitschriften ausschließen, die von anderen Verbundteilnehmern regelmäßig ausgewertet werden. Da muss m.E. entschieden werden, ob das gewollt ist

Zu 2.: Wir haben für unsere eigenen Zeitschriftengesamtaufnahmen "ixzg" (gedruckte Ausgabe) oder "ixze" (elektronische Ausgabe) vergeben. Leider wurde das nicht immer zuverlässig gehandhabt. Bei den Kooperationszeitschriften ist das nicht (durchgängig) der Fall. Nur dann, wenn die Partner eine Zeitschrift von uns übernommen haben, die wir früher ausgewertet haben. Neue Zeitschriften der Kooperationspartner haben diese Abrufzeichen meist nicht.

Zu 3.: Wenn eine Zeitschrift das Erscheinen eingestellt hat, gibt es einen Abschlussjahrgang und manchmal auch den Hinweis "...Erscheinen eingestellt":
Bsp.:
PPN 636680096
362 0 $a30. Jahrgang, 1 (2010)-36. Jahrgang, 2 (2016)
PPN 617510075
362 0 $a1.2009 - 5.2013; damit Ersch. eingest.

**Comment by thefass** [comment]
Alerting macht m.E. nur Sinn, wenn die Zss regelmäßig und zuverlässig ausgewertet werden (egal ob vollständig oder selektiv). Das können wir nur für "uns" (mitgemeint sind auch unsere festen Kooperationspartner) garantieren. Insofern wäre das Merkmal "IxTheo" in der Zeder Spalte kat richtig.
Wenn Zss von anderen Bibliotheken (regelmäßig) ausgewertet werden, könnten wir mit ihnen eine Kooperation absprechen und das dann in Zeder festhalten.
****
Zss, in denen irgendeine Bibliothek mal einen Aufsatz katalogisiert, z.b. im Rahmen einer Hochschulbibliographie, sollten wir nicht alerten. Das könnte zu Enttäuschungen führen
****
Beim Alerting von Reihen sollten wir so vorgehen, dass nur Reihen, die wir durch das Bibliographietool regelmäßig erfassen, alertet werden können.

**Comment by thefass** [comment]
@mtrojan-ub : wegen Zeder. Man könnte doch mit einem Cronjob die PPNs der Zeitschriften, die wir auswerten entnehmen und ihr tragt dann einen entsprechenden Hinweis in SOLR ein. Nur wenn dieser Hinweis da ist, erscheint die Glocke. 
Denkbarer Weg?

**Comment by mtrojan-ub** [comment]
Ja, das wäre grundsätzlich möglich. Wir müssten dann aber auch einen zusätzlichen Zwischenspeicher einbauen, damit die Pipeline nicht stehen bleibt falls Zeder down ist. Wie genau soll demnach in Zeder gefiltert werden? Alle mit `kat=IxTheo`, oder gibt es noch weitere Regeln?

**Comment by thefass** [comment]
ja, nur `kat=IxTheo`

**Comment by mtrojan-ub** [comment]
In der Zwischenzeit hat sich herausgestellt, dass es zusätzlich die Möglichkeit gibt verschiedene Zeitschriftenreihen zu abonnieren. Diese sind darüber gekennzeichnet, das sie in MARC21 008 an den Stellen 11-14 den Wert "9999" haben. 

Sind diese Zeitschriftenreihen ebenfalls in Zeder gepflegt?

Außerdem müssten wir sobald wir die PPNs extrahieren können noch eine Abfrage gegen die bestehenden Benutzer-Einstellungen machen um sicherzugehen, dass es keine Benutzer gibt die bereits Zeitschriften abonniert haben die in Zukunft nicht mehr fürs Alerting zur Verfügung stehen. Hier könnte man ja dann individuell entscheiden ob man den Benutzer anschreibt oder die Zeitschrift vielleicht sogar in Zukunft mit aufnimmt?

**Comment by mtrojan-ub** [comment]
Es gibt ca. 240 Zeitschriften, die bereits von IxTheo-Benutzern fürs Alerting gekennzeichnet wurden, aber in Zeder nicht vorhanden bzw. nicht mit kat=IxTheo gekennzeichnet sind. Wie gehen wir damit um?

[subscriptions.txt](https://github.com/ubtue/tuefind/files/6868110/subscriptions.txt)

**Comment by relhei** [comment]
Wir sollten für die Auswahl der abonnierbaren Zeitschriften noch mal genau auf die ZEDER-Spalten schauen: In kat werden auch extern erschlossene Zeitschriften auf "IxTheo" gesetzt, wenn bereits Aufsätze für die Übernahme in die Bibliografien gekennzeichnet wurden. Es befnden sich auch Zeitschriften darunter, die nicht von festen Kooperationspartnern bzw. nur tw. ausgewertet werden. Die Spalte efor unterscheidet, wer die Zeitschriften formal erschließt. Möglicherweise wäre das dann die richtige Spalte für die Alerting-Funktion: Dann müssten wir nur definieren, welche Feldinhalte neben IxTheo ausgewertet werden sollen (z. B. Bildi, Kaldi...).
Alternativ könnten wir die externen "Übernahme-Zeitschriften" aus dem Verbund in Feld kat anders kennzeichnen...

**Comment by mtrojan-ub** [comment]
> Es wäre möglich, dass die vorbereitenden Änderungen hierzu schon auf dem Liveserver eingespielt wurden, bevor sie ausgiebig genug getestet wurden. 

=> High Priority

**Comment by relhei** [comment]
> 
> 
> Wir sollten für die Auswahl der abonnierbaren Zeitschriften noch mal genau auf die ZEDER-Spalten schauen: In kat werden auch extern erschlossene Zeitschriften auf "IxTheo" gesetzt, wenn bereits Aufsätze für die Übernahme in die Bibliografien gekennzeichnet wurden. Es befnden sich auch Zeitschriften darunter, die nicht von festen Kooperationspartnern bzw. nur tw. ausgewertet werden. Die Spalte efor unterscheidet, wer die Zeitschriften formal erschließt. Möglicherweise wäre das dann die richtige Spalte für die Alerting-Funktion: Dann müssten wir nur definieren, welche Feldinhalte neben IxTheo ausgewertet werden sollen (z. B. Bildi, Kaldi...). Alternativ könnten wir die externen "Übernahme-Zeitschriften" aus dem Verbund in Feld kat anders kennzeichnen...

@thefass Welches Feld in ZEDER sollen wir für die Anzeige der abonnierbaren Zeitschriften verwenden? 
@mtrojan-ub Was würde denn mit den nicht mehr gültigen Abos zu den 240 Zeitschriften passieren? Werden diese automatisch gelöscht? Falls ja, würde ich eine kurze E-Mail-Benachrichtigung an die betreffenden Nutzer*innen für sinnvoll halten.

**Comment by mtrojan-ub** [comment]
Wenn es eine bestehendes Abo gibt, wird dieses nicht automatisch gelöscht. Es taucht noch in der Liste der aktiven Abos im Benutzerkonto auf. Allerdings wird aktuell auch der Button zum Entfernen des bestehenden Abos nicht mehr angezeigt, falls es sich um eine nicht abonnierbare Zeitschrift handelt => hier sollten wir noch nachbessern.

(Außerdem fehlt ja noch die verbesserte Felddefinition aus Zeder.)

**Comment by mtrojan-ub** [comment]
Auf ptah ist jetzt der Bugfix aktiv, d.h. man ist jetzt in der Lage, bereits abonnierte Zeitschriften wieder abzubestellen, auch wenn sie nicht aktiv von uns ausgewertet werden.

**Comment by relhei** [comment]
Ergebnis aus Sitzung: Nur Zeitschriften mit Felddefinition kat:ixtheo werden ins Alerting übernommen.

**Comment by relhei** [comment]
Ist umgesetzt, danke!
