### ISSUE TITLE
Normdatenanzeige

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#1525]
In der Affiliation wird das Unterfeld **$b** nicht angezeigt:
https://ptah.ub.uni-tuebingen.de/Authority/14206081X

510 2 $0(DE-627)102155607$0(DE-576)191768057$0(DE-588)2024175-6$a**Christian-Albrechts-Universität zu Kiel**$4affi$wr$iAffiliation$eAffiliation
510 2 $0(DE-627)101097255$0(DE-576)193281228$0(DE-588)2106175-0$a**Christian-Albrechts-Universität zu Kiel$bTheologische Fakultät**$4affi$wr$iAffiliation$eAffiliation

![Baethgen](https://user-images.githubusercontent.com/17004223/122953411-fbdf7d80-d37e-11eb-9c7a-2e3c44effaf8.JPG)

**Comment by mtrojan-ub** [comment]
Der Code wurde angepasst, es wird allerdings einige Zeit dauern bis die Änderung in den master einfließt und somit auf ptah auftaucht, da zur Zeit im Authority-Bereich an vielen Dingen parallel entwickelt wird. Ich melde mich dann nochmal.

**Comment by mtrojan-ub** [comment]
Die Änderung kann nun auf ptah getestet werden.

**Comment by IxTheoKm** [comment]
Jetzt in Ordnung, danke!
