### ISSUE TITLE
"Neues Konto anlegen": Formularelemente sind seltsam angeordnet

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#153]
![grafik](https://user-images.githubusercontent.com/26873381/34835454-28bb5e7e-f6f5-11e7-94a4-d26aaa1e1dd6.png)

**Comment by mtrojan-ub** [comment]
Außerdem noch festgestellt:
- Nutzt man im eingeloggten Zustand die Maske "Persönliche Angaben" kann man dort nichtmal sein Passwort ändern, da nur eine Untermenge der Felder angezeigt wird (wichtig für diesen Issue, da dort das selbe Template verwendet wird)
- Das Speichern von Änderungen bei einem existierenden Benutzer schlägt aktuell fehl

**Comment by mtrojan-ub** [comment]
Bei Passwort ändern habe ich mich leider geirrt, dafür gibts ja eine separate funktion... trotzdem muss sichergestellt werden dass das Template an beiden Stellen gut dargestellt wird.

**Comment by thefass** [comment]
Der Anmelde- und Änderungsprozess ist elementar. Bitte prioritär dieses Issue behandeln

**Comment by mtrojan-ub** [comment]
auf ptah jetzt besser:

![grafik](https://user-images.githubusercontent.com/26873381/34871917-80d5e29c-f78f-11e7-9901-388f6e88e473.png)

und 

![grafik](https://user-images.githubusercontent.com/26873381/34871989-ad082b7c-f78f-11e7-8549-3a2bb6ec0c8c.png)

außerdem kommt beim Aktualisieren jetzt auch kein Fehler mehr.

**Comment by mtrojan-ub** [comment]
Die Änderung wurde jetzt auch live (auf ub16) eingespielt.
