### ISSUE TITLE
Normdatenanzeige - Titelverknüpfungen

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#1539]
Bei "Show all titles" kommt die Fehlermeldung 
"Keine Ergebnisse!
Für Ihre Suchanfrage - author_corporate_id:..."

Es soll vermutlich author_id heißen

**Comment by mtrojan-ub** [comment]
Das Problem wurde behoben => ready for testing auf ptah.

Zur Erklärung: In VuFind gibt es ein 3-teiliges Autorenkonzept: Primary, Secondary, Corporate. Für die "Newest Titles" Ansicht werden momentan alle 3 Arten von Bezügen zu Titeln zusammengefasst, daher sollte der Link auf alle 3 Felder verlinken (es handelt sich um den selben View für alle Arten von Normdaten, also sowohl Personen als auch Körperschaften).

In der Kurztitelanzeige wird aber bei der Suche nach Titel für einen Autor eine Titelsuche über das Heading ausgelöst. Da ist noch die Frage ob man das ggf. ändert falls es sich um einen Autor mit Normdaten handelt, damit das Verhalten einheitlich ist. Es war auch mal im Gespräch ob man die Suche vom Normdatensatz aus gar nicht über IDs sondern auch über das Heading durchführt, da selbst normierte Autoren ggf. in den Titeldaten nicht flächendeckend gepflegt sind. Allerdings hat man dann auch eine unscharfe suche die ggf. mehr liefert als erwartet.

**Comment by IxTheoKm** [comment]
Aus der Mail vo @thefass vom 21.06.2021:
> eine Suche über das normierte PersonenSW wäre natürlich treffsicherer.
>
> Allerdings hat @jriedl Recht, so dass ich eher zu einer unscharfen 
> Suche tendiere. Könnten wir in der Relevanz Sortierung einstellen, 
> dass die sicheren Treffer weiter oben sind als die unscharfen?

Das ist richtig: wir bemühen uns zwar um Individualisierung, allerdings gibt es massenhaft unverknüpfte Datensätze. Eine Bereinigung wird nie möglich sein.

**Comment by IxTheoKm** [comment]
"Show all titles" funktioniert jetzt.

**Comment by mtrojan-ub** [comment]
Soeben wurde ein Update auf ptah eingespielt. Die Verknüpfung vom normierten Autor zum Titel und umgekehrt wurde an verschiedenen Stellen vereinheitlicht:
- Kurztitelanzeige
- Volltitelanzeige
- Normdatensatz
  - Newest Titles
  - Show all Titles

Die damit verbundene Suchabfrage verwendet sowohl die IDs als auch die Headings über verschiedene Felder (author, author2, author_corporate).

**Comment by IxTheoKm** [comment]
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=author_id:%22694655333%22%20OR%20author2_id:%22694655333%22%20OR%20author_corporate_id:%22694655333%22%20OR%20author:%22Weicker,%20Karl%20Gustav%20Adolf%201804-1842%22%20OR%20author2:%22Weicker,%20Karl%20Gustav%20Adolf%201804-1842%22%20OR%20author_corporate:%22Weicker,%20Karl%20Gustav%20Adolf%201804-1842%22

### Die Anzeige ist "verrutscht". Sollte das in ein eigenes Issue, oder ist das in diesem Issue korrekt?

![authAnzeige](https://user-images.githubusercontent.com/17004223/125632375-3e0f61bc-ed24-45ec-b891-d3ab96927555.JPG)

https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=author_id:%22061939080%22%20OR%20author2_id:%22061939080%22%20OR%20author_corporate_id:%22061939080%22%20OR%20author:%22K%C3%BCng,%20Hans%201928-2021%22%20OR%20author2:%22K%C3%BCng,%20Hans%201928-2021%22%20OR%20author_corporate:%22K%C3%BCng,%20Hans%201928-2021%22

![authAnzeige](https://user-images.githubusercontent.com/17004223/125633136-91482176-16c1-4ded-87bd-7609634cc18b.JPG)

**Comment by mtrojan-ub** [comment]
Das Layout-Problem wurde behoben und kann jetzt auf ptah getestet werden.

**Comment by IxTheoKm** [comment]
Layout stimmt jetzt, danke!
Ich schließe.
