### ISSUE TITLE
Datensätze mit mehreren Titeln

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#1555]
PPN: 176124132X

Diesen Datensatz erhalten wir vom BSZ geliefert, können ihn aber nicht importieren, da er über mehr als ein 245 Feld verfügt:
https://swb.boss.bsz-bw.de/Record/(DE-627)176124132X#details

> 245 | 1 | 0 | \|a RYTUAŁ POGRZEBOWY GREKÓW W STAROŻYTNOŚCIW ŚWIETLE EPIGRAMÓW NAGROBNYCH
> 245 | 1 | 0 | \|a Funerary Ritual of Greeks in Antiquity as Reflected in Funerary Epigrams

Laut dem MARC21 Standard ist 245 non-repeatable.

**Comment by mtrojan-ub** [comment]
Ähnliches Problem bei:
1761241346
1761241389

**Comment by IxTheoKm** [comment]
Wurde mit Zotero falsch erfasst.
Paralleltitel müssen in PICA 4002 = Marc 246 stehen.

Bsp.:
PPN 
1761904191
1761904167
1761904132

**Comment by IxTheoKm** [comment]
Korrektur erledigt. Wurden vermutlich bei der Nachbearbeitung übersehen.
Gibt es weitere Fälle?

**Comment by mtrojan-ub** [comment]
Folgende weitere Fälle tauchen aktuell noch im Log auf:
1747955353
1747955396

**Comment by IxTheoKm** [comment]
In diesen Fällen ist die Wiederholung von PICA 4000 = Marc 145 erlaubt:
Erfassung des Haupttitels zusätzlich in nicht-lateinischen Schriften.

$T enthält einen zweistelligen Zählfaktor zur Zuordnung der Felder untereinander
$U enthält den Schriftcode
$L enthält den Sprachencode (nicht immer vorhanden)

Bsp. PPN 1747955396:
245 10$a**T01**$$UCyrl$$Lrus%%София Премудрость Божья$bПрекрасная Дама русского символизма (Новая христианская парадигма у младосимволистов)
245 10$aSofija Premudrost' Bož'ja$bPrekrasnaja Dama russkogo simbolizma (Novaja christianskaja paradigma u mladosimbolistov)

**Comment by mtrojan-ub** [comment]
Selbst wenn in PICA eine Wiederholung des 4000er Feldes erlaubt ist, dann bedeutet das nicht automatisch, dass beim Export nach MARC21 diese Felder alle als 245 ausgespielt werden dürfen. Wahrscheinlich wäre es laut dem MARC21 Standard gültig, wenn das erste 4000er als 245 und alle weiteren als 246 ausgespielt werden.

Siehe auch: https://www.loc.gov/marc/bibliographic/bd246.html

Ich werde hierzu mal beim BSZ nachfragen.

**Comment by mtrojan-ub** [comment]
Das BSZ hat den ersten Datensatz behoben: 176124132X
Ich habe jetzt auch die beiden anderen PPNs 1747955353 und 1747955396 weitergeleitet.

Hier die Aussage von Frau Ladisch:
> Es handelt sich hier um einen Erfassungsfehler. Am Beginn von Pica3 4000 wurde ein Leerzeichen zu viel erfasst. Das hat dazu geführt, dass die originalschriftlichen Felder nicht in den richtigen Unterfeldern im Pica-Internformat gelandet sind. Ich habe den Satz korrigiert, mit der nächsten Änderungslieferung wird er korrekt bei Ihnen ankommen.

**Comment by mtrojan-ub** [comment]
Laut Frau Ladisch wurden die beiden Datensätze jetzt ebenfalls korrigiert.
1747955353 passt, 1747955396 wurde erst heute korrigiert, müsste also voraussichtlich mit dem nächsten Teilabzug bei uns ankommen und kann somit ab Montag getestet werden.
