### ISSUE TITLE
Problem mit dem Laden von snippets

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#1557]
In der Volltextsuche werden die Snippets nicht geladen
![Bildschirmfoto 2021-07-05 um 10 43 34](https://user-images.githubusercontent.com/14169098/124443538-0d148b00-dd7e-11eb-80d2-fb4dfd5e3aa5.png)

Siehe den Hinweis im Datensatz: "Lade..."

**Comment by jriedl** [comment]
Wird wieder angezeigt.

**Comment by thefass** [comment]
ok
