### ISSUE TITLE
Datensätze mit fehlender Jahresangabe

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#1563]
https://ptah.ub.uni-tuebingen.de/Record/1748012843#details

Der Datensatz an sich wird importiert, aber bei der Ermittlung der Jahresangabe gibt es einen Fehler:
SEVERE: getDatesBasedOnRecordType ["    " is not a valid year for PPN 1677511893]

Die Jahreszahl wird bei diesem Feld aus 008 Positionen 7-10 extrahiert, die bei diesem Datensatz leer sind. Außerdem fällt der Datensatz nicht in andere Kategorien, für die das Jahr aus anderen Feldern ausgewertet werden kann (534, 936, 190).

**Comment by mtrojan-ub** [comment]
Weitere Datensätze, bei denen dieses Problem auftritt:
1669218082
1669645045
1677511893
169025226X
1695785460
1695789326
1695794257
1695799917
1695801032
1725070669
172507334X
1747864900
1747903272
1748079158
175763326X

**Comment by IxTheoKm** [comment]
Einige der PPNs gibt es nicht mehr im K10plus, andere habe ich mit mtex ausgesteuert (Werke und Briefe von Eduard Mörike; evtl. für IxTheo ausgesteuert, durch ehem. Bestand Theologicum?)

Einige sind noch gar nicht erschienen ("Erscheinungstermin unbestimmt"; als Erscheinungsjahr ist z.T. "20" erfasst). Die habe ich vorerst mit mtex ausgesteuert und wie andere Fälle per K10plus-Mailbox an tuixth/mtex-2019-2021 adressiert.

Der Rest ist korrigiert.

**Comment by mtrojan-ub** [comment]
Für folgende PPNs tauchen weiterhin Fehler im Log auf:
1747903272
1748079158
1748012843
1747864900
1677511893
169025226X

Soll die Fehlermeldung nach bestimmten Kriterien unterdrückt werden? (also z.B. wenn sie noch nicht erschienen sind? Und wenn ja => wie erkennen wir das genau?)

**Comment by IxTheoKm** [comment]
PPN 1747903272 habe ich korrigiert. Die folgenden 5 PPNs gibt es nicht mehr im K10plus.

Ein eindeutiges Kriterium kann man nicht definieren. In manchen Fällen steht "Erscheinungstermin unbestimmt" in einer Anmerkung in den Titeldaten, in manchen nur in Exemplardaten verschiedener Bibliotheken.

**Comment by mtrojan-ub** [comment]
Da die Fälle korrigiert wurden bzw zu den anderen die PPNs nicht mehr existieren, schließe ich diesen Issue.
