### ISSUE TITLE
Personalisierte Seite - Link Symbol

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#1568]
Wenn der erste Autor (Oorschot) nicht individualisiert ist (also keinen Normsatz hat), dann rutscht das runde Personen-Symbol in der Kurztitelanzeige, das eigentlich zum zweiten Autor (Cruz) gehört, nach vorne.
![Bildschirmfoto 2021-07-13 um 15 23 27](https://user-images.githubusercontent.com/14169098/125459741-2d43509c-4ce5-4fb4-a1de-f129c6b41708.png)
 
http://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=iapt.cs&type=AllFields&limit=500&botprotect=
Hier der zweite Treffert: Preface

**Comment by mtrojan-ub** [comment]
Sehr gutes Beispiel! Sieht man auch in der Detailansicht (dann ist die URL eindeutiger):
http://ptah.ub.uni-tuebingen.de/Record/176271616X

Hängt damit zusammen, dass VuFind die Werte für die Autoren in verschiedenen Solr-Feldern speichert und im Anschluss wieder zusammenführt. Da einer der Autoren keinen Normsatz hat sollte vermutlich ein leerer Wert gespeichert werden, damit man es wieder korrekt zusammenführen kann. Ich schau's mir an.

**Comment by mtrojan-ub** [comment]
Die Änderung wurde auf ptah eingespielt + kann dort getestet werden

**Comment by thefass** [comment]
ok

**Comment by thefass** [comment]
Hier sind die Links vertauscht:
https://ptah.ub.uni-tuebingen.de/Record/1733587179

**Comment by mtrojan-ub** [comment]
Kann ich auf ptah bestätigen, wobei das bei mir lokal nicht mehr auftaucht. Hängt vermutlich mit noch nicht fertiggestellten Änderungen im Rahmen von #1575 zusammen.

**Comment by mtrojan-ub** [comment]
Änderungen wurden zwischenzeitlich auf ptah eingespielt. Personen-Link scheint korrekt, aber Link für die Titel sieht merkwürdig aus.

**Comment by mtrojan-ub** [comment]
Fehler in der Konfiguration für den Solr-Import, sollte nach dem nächsten Import behoben sein (ab morgen früh erneut testbar).

**Comment by IxTheoKm** [comment]
Ich habe anhand von 
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=id%3A1766724930&type=AllFields&limit=20&botprotect= und https://ptah.ub.uni-tuebingen.de/Record/1766724930 
getestet 
(erste Person uverknüpft ohne Normsatz, zwei Personen mit Normsatz):

Sieht in der Kurz- und Vollanzeige korrekt aus, und die Links führen auf die richtigen Daten.

Test anhand von
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=id%3A176672065X&type=AllFields&limit=20&botprotect=
https://ptah.ub.uni-tuebingen.de/Record/176672065X
(sieben beteiligte Personen, davon die zweite und siebte mit Normsatz):

Kurzanzeige listet vier Personen mit folgenden drei Punkten korrekt auf, Links sind korrekt.

**Vollanzeige:**
Für sechs Personen ist alles korrekt, für die siebte Person fehlt das Symbol / der Link zum Normsatz:

![authNormsatz](https://user-images.githubusercontent.com/17004223/130196163-84fd76d9-01f1-47be-a4a2-64bdfa819a90.JPG)

**Comment by mtrojan-ub** [comment]
Das liegt vermutlich nicht am Verlinkungsmechanismus, sondern daran, dass Jeremy Bailenson (PPN 703464558) nicht in unserem Normdatenabzug vorhanden ist.

**Comment by thefass** [comment]
was könnte der Grund sein, dass sie nicht im Normdatenabzug vorhanden ist?
die GND 139789723 wird ja im Titelsatz angegeben


700 | 1 |   | \|a Bailenson, Jeremy    \|e VerfasserIn    \|0 (DE-588)139789723    \|0 (DE-627)703464558    \|0 (DE-576)351716262    \|4 aut
-- | -- | -- | --

**Comment by mtrojan-ub** [comment]
Interessanterweise war der Datensatz in folgendem TA enthalten: TA-MARC-ixtheo-210816.tar.gz
Ich werde weiter prüfen, wieso er aktuell nicht mehr vorhanden ist

**Comment by mtrojan-ub** [comment]
Durch die Änderungen im Bezug auf sekkor (erwähnt in #1452 und anderen) wurde wohl etwas zuviel gefiltert. Das Softwareproblem wird schnellstmöglich behoben, allerdings werden einige Datensätze fehlen bis zum nächsten BSZ-Komplettabzug den wir ja ohnehin in den nächsten Wochen anfordern wollten.

**Comment by mtrojan-ub** [comment]
Der neue SA wurde heute importiert, jetzt wird auch der Link auf Jeremy Bailenson korrekt angezeigt:
https://ptah.ub.uni-tuebingen.de/Record/176672065X

Kann der Issue nun geschlossen werden?

**Comment by IxTheoKm** [comment]
Ich habe noch andere Beispiele getestet. Sieht jetzt gut aus, danke. Ich schließe.
