### ISSUE TITLE
Normdatenanzeige: Autorenumfeld

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#1572]
Autor => Titel => Weitere Autoren

**Comment by mtrojan-ub** [comment]
Kann auf ptah getestet werden, Beispiel:
https://ptah.ub.uni-tuebingen.de/Authority/035286210

![grafik](https://user-images.githubusercontent.com/26873381/125789918-8db8ad73-c642-4a49-af29-6bbf7350cb21.png)

**Comment by thefass** [comment]
sieht gut aus
Kann die Anzahl der related authors noch angezeigt werden (ähnlich wie bei Titeln

**Comment by thefass** [comment]
Die related Authors unterscheiden sich. Auf ptah fehlt Löning
https://ptah.ub.uni-tuebingen.de/Authority/081707754
![Bildschirmfoto 2021-07-16 um 07 52 17](https://user-images.githubusercontent.com/14169098/125898928-0a7dbc9d-3a1c-451a-beb2-cdb71e5478d9.png)

https://www.ixtheo.de/Search/Results?lookfor=martin+Fa%C3%9Fnacht&type=Author&botprotect=
![Bildschirmfoto 2021-07-16 um 07 52 07](https://user-images.githubusercontent.com/14169098/125898960-97de09ff-0a43-4ddd-bdde-bd46327b4a0e.png)

**Comment by mtrojan-ub** [comment]
Kann getestet werden, Löning taucht jetzt auf.

**Comment by thefass** [comment]
ok, perfekt
