### ISSUE TITLE
Normadatenanzeige: by - about

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#1576]
Bitte die Anzeige der Titel unterscheiden in 

Newest titles from (=Person ist Verfasser)
und
Newest titles about
(=Person ist Schlagwort)
Bsp: https://www.ixtheo.de/Search/Results?lookfor=Erich+zenger&type=Subject&limit=20&botprotect=

@mtrojan-ub evt. nebeneinander in zwei Spalten?

**Comment by mtrojan-ub** [comment]
Anpassung ist in Arbeit. Nebeneinander ist vermutlich schwierig:
1) Aufgrund Responsive Design
2) Da beide Sektionen theoretisch auch fehlen können falls es keine Treffer gibt

**Comment by mtrojan-ub** [comment]
Wird voraussichtlich Mitte der Woche auf ptah eingespielt.
Von der Formulierung her wäre aber "by" zutreffender als "from", von daher werde ich das noch anpassen.

**Comment by thefass** [comment]
ja, ist ok …-)

**Comment by mtrojan-ub** [comment]
Kann jetzt auf ptah getestet werden. Beispiel:
https://ptah.ub.uni-tuebingen.de/Authority/035286210

![grafik](https://user-images.githubusercontent.com/26873381/126630057-959df67d-56b4-4074-803f-d99ef6434862.png)

**Comment by thefass** [comment]
ok
