### ISSUE TITLE
Pipeline-Problem mit Canones

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#1586]
110p = `1274,2,3,4`

Das Format wird bislang noch nicht unterstützt. Siehe auch:
https://github.com/ubtue/ub_tools/blob/79839f08ecdd2860b7333787ab7b717c47af2963/cpp/lib/src/RangeUtil.cc#L553
https://github.com/ubtue/tuefind/wiki/Codices

```
1722753099:001:1722753099
1722753099:003:DE-627
1722753099:005:202007092123.4
1722753099:008:200709n||aznnnaabn           | ana    |c
1722753099:024:7 ahttp://d-nb.info/gnd/12134651332uri
1722753099:035:  a(DE-627)1722753099
1722753099:035:  a(DE-588)1213465133
1722753099:040:  aDE-627bgercDE-627erda
1722753099:065:  a7.132sswd
1722753099:065:  a3.6a2sswd
1722753099:079:  agbucvqsvwit
1722753099:110:2 aKatholische Kirche4aut1wriVerfasserschaft1eVerfasserschaft1tCodex iuris canonicif1983p1274,2,3,4
1722753099:510:2 0(DE-627)1056946810(DE-576)2096277190(DE-588)4131491-8aKatholische KirchetCodex Iuris Canonicif19834obpawriOberbegriff partitiv9v:Enthalten in
1722753099:510:2 0(DE-627)1016592610(DE-576)1916445010(DE-588)2009545-4aKatholische Kirche4aut1wriVerfasserschaft1eVerfasserschaft1
1722753099:667:  aCIC5DE-21
1722753099:670:  aanalog
1722753099:ORI:  aTA-MARC-ixtheoc001.raw
```

Vermutlich haben sich die Normdaten verändert und wir haben diese Schreibweise so bisher nicht bekommen.
High priority, da auch auf dem Liveserver die Pipeline nicht erfolgreich durchlaufen kann, solange das Problem nicht behoben ist.

**Comment by IxTheoKm** [comment]
Ich weiß nicht, ob ich das richtig verstehe, aber unter https://github.com/ubtue/tuefind/wiki/Codices#teile-eines-canon-pars ist doch ein Beispiel mit dieser Struktur aufgeführt:

Beispiel c. 1044,2,2 in der OGND
Marc Struktur: 110 2 $aKatholische Kirche$tCodex iuris canonici$f1983$p1044,2,2

Oder ist hier das dritte Komma das Problem?

Ich finde weitere Beispiele in dieser Form und muss @IxGe fragen, ob 110p = 1274,2,3,4 so korrekt ist oder evtl, 1274,2-4 lauten muss.

**Comment by ruschein** [comment]
Liebe Frau Kellmeyer,


ja, das 3. Komma ist das Problem.


Viele Grüße,

Johannes Ruscheinski

--
Dr. Johannes Ruscheinski
Universitätsbibliothek Tübingen - IT-Abteilung -
Wilhelmstr. 32, 72074 Tübingen

Tel: +49 7071 29-72820
FAX: +49 7071 29-5069
Email: ***@***.***

 The Sophisticate:  "The world isn't black and white.  No one does pure good or pure bad. It's all gray.  Therefore, no one is better than anyone else."
    The Zetet:  "Knowing only gray, you conclude that all grays are the same shade.  You mock the simplicity of the two-color view, yet you replace it with a one-color view..."
      —Marc Stiegler, David's Sling


________________________________

**Comment by mtrojan-ub** [comment]
> kann man diese Verknüpfung einstweilen aus Ihren Daten rausnehmen, damit die Pipeline keine Schwierigkeiten hat? Der Datensatz wird dann ja durch die Korrektur wieder geliefert.

Grundsätzlich ja, wobei dann die Funktionalität der Codexsuche bis zur Einspielung der Korrektur beeinträchtigt sein wird.

**Comment by mtrojan-ub** [comment]
Die Lieferung des Datensatzes könnte ja nach der Korrektur noch ca 1 Woche dauern. Die Frage ist, ob wir den Wert für diesen Datensatz mit dieser PPN bei uns intern hardcoded überschreiben, bis die Korrektur geliefert wurde. Dafür müssen wir aber sicher wissen ob `1274,2-4` der korrekte Wert wäre.

**Comment by ruschein** [comment]
Liebe Frau Kellmeyer,


vielen Dank, dann ist ja alles geklärt!


Viele Grüße,

Johannes Ruscheinski

--
Dr. Johannes Ruscheinski
Universitätsbibliothek Tübingen - IT-Abteilung -
Wilhelmstr. 32, 72074 Tübingen

Tel: +49 7071 29-72820
FAX: +49 7071 29-5069
Email: ***@***.***

 The Sophisticate:  "The world isn't black and white.  No one does pure good or pure bad. It's all gray.  Therefore, no one is better than anyone else."
    The Zetet:  "Knowing only gray, you conclude that all grays are the same shade.  You mock the simplicity of the two-color view, yet you replace it with a one-color view..."
      —Marc Stiegler, David's Sling



________________________________

**Comment by mtrojan-ub** [comment]
Die anderen beiden Datensätze sehen ebenfalls inkorrekt aus:
```
don't know how to parse codex parts "1600,1,2,3"! (PPN: 1722804866)
don't know how to parse codex parts "844,3,4,5"! (PPN: 1722891734)
```

Bitte ebenfalls prüfen / korrigieren!
Wir haben uns nun doch dafür entschieden erstmal keine lokale Korrektur durchzuführen und lediglich den Pipeline-Abbruch zu verhindern, werden die Änderung aber erstmal bis morgen auf ptah testen (d.h. es ist möglich dass die Pipeline auf ub16 morgen früh nochmal fehlschlägt).

**Comment by mtrojan-ub** [comment]
Die Änderung auf ptah war erfolgreich. Wir haben soeben auch die Liveserver aktualisiert, d.h. die Pipeline wird ab morgen früh dort wieder durchlaufen. Allerdings bleibt die Canones Suche beeinträchtigt bis die Korrekturen bei uns angekommen sind.

**Comment by IxTheoKm** [comment]
Vielen Dank! Das ist m.E. kein Problem. Es sind nur drei Canones-Stellen, die kurzfristig nicht suchbar sind.

**Comment by IxTheoKm** [comment]
Alle drei Normsätze wurden von @IxGe korrigiert, und die Titelsätze PPN 1763312402, 1763245209 und 1650151977 sind jetzt nachgewiesen. 

Die CIC-Einträge in den jeweilgen Kurzanzeigen sehen für mich allerdings merkwürdig aus. Muss ich noch prüfen und ggf. ein neues Issue aufmachen.

**Comment by mtrojan-ub** [comment]
OK, dann werde ich diesen Issue schließen.
