### ISSUE TITLE
Nicht unterstützte Zeitbereichsangaben in Normdaten

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#1587]
Aktuell gibt es auffällig viele Warnungen bei der Auswertung von Zeitbereichen aus 548a (i=Zeitraum) in den Normdaten (augment_time_aspects).

Hier einige Beispiele:
| Zeitraum        | PPN  | 
| ------------- |-------------| 
| 529-   | 100669190 | 
| -1806  | 102542864 | 
| 20.08.1901 | 1747627402 | 
| 25.12.1991- | 104251980 | 
| -01.05.1974 | 785932976 | 
| XX.12.1991- | 104252782 | 
| -XX.12.2007 | 1759425915 | 
| XXXX-2016 |  184172322 | 
| XX.XX.1947-XX.06.2001 |  103086935 |
| 5XX-1818 | 1762988607 | 
| 1923-25.12.1991 | 104152052 | 
| ca. 16. Jh.- | 101961707 | 
| ca. 18./19. Jahrhundert | 1762792141 |

**Comment by mtrojan-ub** [comment]
siehe auch: https://github.com/ubtue/ub_tools/blob/79839f08ecdd2860b7333787ab7b717c47af2963/cpp/lib/src/RangeUtil.cc#L689

**Comment by thefass** [comment]
Sind das Zeitangaben, die so in "einem" 548a Feld vorkommen?
Also steht da: 529- -1806 oder kommt 529- in einem Feld vor und in einem anderen Feld -1806?
Hast Du evt. PPNs?

**Comment by mtrojan-ub** [comment]
Diese angaben stehen alle so direkt in 548a, z.B. 100669190 für 529-. Beispiel für -1806 wäre 102542864. Die anderen kann ich bei Bedarf raussuchen.

**Comment by ruschein** [comment]
Da das Bereiche sein sollen macht das nicht viel Sinn.  Man könnte zusätzliche Regeln aufstellen, z.B.

529- bedeutet 529 bis akutelles Jahr.
-1806 bedeutet seit dem Big Bang bis 1806.
ca. 16. Jh.- bedeutet 1.1.1500 bis aktuelles Jahr.
ca. 18./19. Jahrhundert bedeutet 1.1.1700 - 31.12-1800.
etc.

Aber lohnt sich das?

**Comment by thefass** [comment]
Der Datensatz mit 529- ist der Benediktiner Orden. 529 ist das Gründungsjahr, den Orden gibt es noch, deswegen gibt es kein Abschlussjahr, sondern das -
548 $a529-$4datb$wr$iZeitraum
Zeiträume, die also in die Gegenwart hin offen sind, könnten auf jeden Fall mit der Logik 529- bedeutet 529 bis akutelles Jahr behandelt werden.
Auch die Umsetzung der ca. Angaben lohnt.
+++++
Schwieriger zu interpretieren sind die Angaben -1806
Das Beispiel ist das "Heiliges Römisches Reich Deutscher Nation" und da ist halt der Anfang offen, es ist aber sicherlich nicht der Big Bang. Wie wir das handhaben, weiß ich gerade auch nicht

**Comment by ruschein** [comment]
Ready for testing auf Ptah ab morgen.

**Comment by thefass** [comment]
Bitte ein paar Beispiel PPNs nennen.
z.B. in dem -529 vorkommt etc.

**Comment by mtrojan-ub** [comment]
Die PPNs wurden im 1. Beitrag dieses Issues ergänzt, siehe Tabelle. Manche der PPNs tauchen später nicht unmittelbar in der Suche auf, z.B. 102542864 - Heiliges Römisches Reich Deutscher Nation.

**Comment by IxTheoKm** [comment]
Was ist mit "Nicht unterstützte Zeitbereichsangaben" gemeint? 
In Bezug auf Relevanz für die Recherche oder für die Anzeige?

Ist das die Ursache für die falsche Anzeige z.B. von 
https://ptah.ub.uni-tuebingen.de/Authority/695735993/Other%20Names#tabnav ?

100 |a Hahn |c Familie, Theologe |d ca. 18.-20.Jd.

![authZeit_Hahn](https://user-images.githubusercontent.com/17004223/129727738-967cac4d-00bb-4cb9-99a6-418d7eb93395.JPG)

**Comment by ruschein** [comment]
@IxTheoKm Nur in Bezug auf die Relevanz für die Recherche.  Und nein, das hat vermutlich nichts mit dem Problem von der falschen Anzeige zu tun.

**Comment by IxTheoKm** [comment]
Danke, ich habe für die Anzeige ein eigenes Issue aufgemacht: https://github.com/ubtue/tuefind/issues/1629

**Comment by thefass** [comment]
seltsam:
eine Zeitsuche nach 1801- funktioniert (wenn auch sehr langsam > 23 Sek)
![Bildschirmfoto 2021-09-16 um 15 45 00](https://user-images.githubusercontent.com/14169098/133623610-685c4115-2c7b-478c-b033-58095831b579.png)


eine Zeitsuche nach 529- funktioniert nicht
![Bildschirmfoto 2021-09-16 um 15 44 12](https://user-images.githubusercontent.com/14169098/133623560-00150a69-6f39-43c1-8cfa-ac4f3070cab0.png)

**Comment by mtrojan-ub** [comment]
Wir prüfen derzeit, ob sich die Suche ggf. über Solr anders abbilden lässt (Stichwort "BBox") um die Performance zu verbessern und trotzdem eine vernünftige Relevanzsortierung zu gewährleisten.

**Comment by mtrojan-ub** [comment]
Es ist bislang ein Solr-Timeout von 30 Sekunden aktiv. Alle Abfragen die länger laufen, produzieren einen Fehler. So auch bei `529-`: Da hier für viel mehr Datensätze eine Relevanz berechnet werden muss, kommt der Algorithmus über die 30 Sekunden Grenze und läuft in den Timeout.

Wir haben die technische Realisierung der Zeitbereichssuche überarbeitet (ist jetzt um ein Vielfaches schneller) und setzen hierfür einen neuen Solr-Datentyp ein. Die neue Suche ist auf ptah aktiv (zusätzlich zur alten), somit können beide Verfahren parallel getestet werden:

1810-:
alt: https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=1810-&type=TimeRangeSearch
neu: https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=1810-&type=TimeRangeBBox

529-:
alt: https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=512-&type=TimeRangeSearch
neu: https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=512-&type=TimeRangeBBox

![grafik](https://user-images.githubusercontent.com/26873381/135088036-42bf8027-71c5-4ed1-ac9e-fd87911963b6.png)

Bitte um Feedback! Falls es keine Probleme gibt, würden wir den alten Algorithmus komplett durch den Neuen ersetzen. Evtl wäre das neue Verfahren dann sogar einen Lightning Talk auf der nächsten VuFind Anwenderkonferenz wert.

**Comment by thefass** [comment]
Die Geschwindigkeit ist ja wenigstens um den Faktor 10 höher. Das ist fantastisch. Vielen Dank.

**Comment by thefass** [comment]
Die Ergebnisse sind nicht gleich
Test-Suche
![Bildschirmfoto 2021-10-05 um 13 10 45](https://user-images.githubusercontent.com/14169098/136012671-426ea087-2bc5-4089-8992-08f5c5502ee0.png)

jetzige Zeitsuche
![Bildschirmfoto 2021-10-05 um 13 11 08](https://user-images.githubusercontent.com/14169098/136012713-50658bda-b575-4961-8722-357145155446.png)


Ich vermisse in der Testsuche (Zeitraum 68-70) die Titel, die mit 66-70 erschlossen sind. Die müßten m.E. vor Ergebnisse mit 64-90 (== vierter Treffer in der Testsuche) kommen. Die Ergebnisse in der jetzigen Suche sind also besser.

**Comment by mtrojan-ub** [comment]
Wir haben das Ergebnis in der Zwischenzeit optimiert => bitte nochmal testen. Allerdings wird es mit dem neuen Verfahren nicht möglich sein, 100%ig die gleiche Ergebnis-Reihenfolge wie vorher zu erreichen. Die Frage ist also, ob die jetzige Version gut genug ist um die alte abzulösen.

**Comment by thefass** [comment]
ja, die Version ist jetzt gut genug, so dass wir das live schalten können
