### ISSUE TITLE
Matomo-Probleme in Chrome (Content Security Policy)

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#1588]
Ausgelöst durch eine Anfrage von @relhei wieso die Matomo-Benutzerzahlen derzeit stark herunter gehen.

Google Chrome hat angeblich einen Marktanteil von ca. 70%, siehe auch: 
https://de.statista.com/statistik/daten/studie/157944/umfrage/marktanteile-der-browser-bei-der-internetnutzung-weltweit-seit-2009/

Öffnet man z.B. ixtheo.de in Chrome, so tauchen in der Log folgende Meldungen auf:
![grafik](https://user-images.githubusercontent.com/26873381/126491224-7ecea1fa-e693-456a-84ff-e59dbbb692aa.png)

Das könnte dazu führen, dass der Großteil der Chrome-Benutzer laut Matomo gar nicht gezählt wird.
=> Weiter prüfen ob das eher am Matomo-Server oder an der Einbindung auf unseren Webseiten liegt.

**Comment by thefass** [comment]
Meinst Du mit "dass der Großteil der Chrome-Benutzer laut Matomo gar nicht gezählt wird", dass die Chrome-Benutzer **nicht mehr** gezählt werden. Sonst müßten die Zahlen ja viel früher heruntergegangen sein, da die Dominanz con Chrome ja schon seit Jahren besteht

**Comment by mtrojan-ub** [comment]
In den Matomo-Auswertungen taucht Chrome zwar z.B. bei ixtheo.de auf, hat aber eher einen Anteil von 37% (Chrome) + 13% (Chrome Mobile) + 1% (Chrome Mobile iOS). Sind zwar weniger als 70%, deutet aber nicht darauf hin dass der in diesem Issue beschriebe Fehler tatsächlich die Ursache des Problems ist. Wir werden trotzdem nach einer Lösung suchen und schauen ob es eine Auswirkung hat (bezogen auf benutzerspezifische Einstellungen).

**Comment by thefass** [comment]
was tatsächlich auffällt, dass die Kurven in allen drei VuFinds so identisch sind. (Bei IxTheo ist das nur nicht so leicht sichtbar, weil die Gesamtzahl so viel höher ist und dadurch die Kurve flacher aussieht.

**Comment by mtrojan-ub** [comment]
Die Fehlermeldungen haben vermutlich etwas mit einem neuen Feature zu tun, welches in VuFind 7.0 eingeführt wurde:
https://vufind.org/wiki/administration:security:content_security_policy

Allerdings ist der Modus dafür per default "report_only", so dass eigentlich nur Warnungen ausgegeben werden sollten ohne dass Fehler ausgelöst werden. Wir werden hierzu eine Konfiguration anlegen und weitere Tests durchführen.

**Comment by mtrojan-ub** [comment]
Der Fehler wurde nun zunächst für ixtheo.de und relbib.de behoben (ist auch für die anderen Domains bereits in Vorbereitung). Der Piwik-Fehler ist nun zumindest aus dem Log verschwunden. Es gibt noch weitere Fehler und Warnungen, diese beziehen sich jedoch auf andere Punkte (z.B. Virtuelle Tastatur) die aber beim direkten Test zu funktionieren scheinen.

**Comment by mtrojan-ub** [comment]
Weiterhin hat sich herausgestellt, dass es im Kontext CSP Probleme bei der direkten Einbindung von Javascript-Snippets geben kann die nicht in eine separate Datei ausgelagert sind. Insgesamt sind ca. 30 verschiedene Templates davon betroffen. Wir werden es entsprechend beheben.

**Comment by mtrojan-ub** [comment]
Die CSP-bezogenen Probleme sind gelöst, daher würde ich den Issue schließen.
Es gibt allerdings hinsichtlich Benutzungszahlen weitere Auffälligkeiten in der Google Search Console, für die ich ein separates Issue öffnen werde.
