### ISSUE TITLE
Canones in der Kurzanzeige und Vollanzeige

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#1589]
Die Anzeige der Canones in der Titelkurzanzeige ist etwas merkwürdig und sollte m.E. der Vollanzeige entsprechen.
Allerdings ist m.W. auch beim Volltitel die Anzeige nicht ganz korrekt. 

Sie wird so ausgeliefert:
610 27$0(DE-588)1213467608$0(DE-627)1722891734$0(DE-576)191644501$aKatholische Kirche$tCodex iuris canonici$f1983$p844,3-5$2gnd

Im IxTheo sieht sie im Internformal so aus:
|t Codex iuris canonici  |f 1983  |p **§844,§3-5**

Es müsste m.E. lauten
Codex iuris canonici 1983. 844, §3-5

@thefass @IxGe 
ist das richtig?

Bsp.:
https://ixtheo.de/Search/Results?lookfor=id%3A1763245209&type=AllFields&limit=20&botprotect=

![canones1](https://user-images.githubusercontent.com/17004223/126641127-81968680-5749-40b1-b846-34f264aab324.JPG)

https://ixtheo.de/Record/1763245209
![canones2](https://user-images.githubusercontent.com/17004223/126641147-a2a9cf8e-a536-493d-bdaf-dc46b05ee085.JPG)

**Comment by thefass** [comment]
es sollte m.E. so dargestellt werden:
Codex iuris canonici 1983. can. 844, §3-5

**Comment by thefass** [comment]
Falsch ist auch die Darstellung 1044,2,2 als 10442,2-2,2
https://ixtheo.de/Search/Results?lookfor=cic83+1044%2C2%2C2&type=CanonesRangeSearch&limit=20&botprotect=

![Bildschirmfoto 2021-07-22 um 15 05 08](https://user-images.githubusercontent.com/14169098/126643717-dfafba41-dee1-412a-a4e3-21f7f7ee8c07.png)

Korrekt wäre Codex iuris canonici 1983, can. 1044, §2 n. 2

in der Kurztitelanzeige so: CIC83 can. 1044, §2 n. 2

**Comment by thefass** [comment]
Falsch ist auch die Darstellung 3443,0-5,0
https://ixtheo.de/Search/Results?lookfor=id%3A1763245209&type=AllFields&limit=20&botprotect=

![Bildschirmfoto 2021-07-22 um 15 16 21](https://user-images.githubusercontent.com/14169098/126645219-352719a5-45cf-4b65-ac14-26572a1c8cc0.png)

@IxGe Das scheint mir aber ein Erfassungsfehler im GND Satz zu sein. Können Sie das bitte prüfen

**Comment by IxGe** [comment]
Der GND-Satz wurde korrigiert und ist nun korrekt https://ixtheo.de/Record/1763245209/Description
bis auf die Anzeige des doppelten § §.
Die Weiterleitung per eMail an mich hat nicht funktioniert - ich habe das Issue nur zufällig gesehen.
I.d.R. sehe ich die Issues nicht.

**Comment by jriedl** [comment]
Bedeutet das, dass im Gegensatz zu #1498 das Paragraphzeichen nur vor den in den ursprünglichen Daten durch Komma abgetrennten Daten angezeigt werden soll und und bei Vorkommen nur einer Zahl immer `can.` davorstehen soll?

**Comment by jriedl** [comment]
Kurztitelanzeige auf ptah.

**Comment by jriedl** [comment]
Volltitelanzeige nun auch umgesetzt.

**Comment by IxTheoKm** [comment]
> es sollte m.E. so dargestellt werden:
> Codex iuris canonici 1983, can. 844, §3-5
> 
> in der Kurztitelanzeige so: CIC83 can. 844, §3-5
Lt. https://github.com/ubtue/tuefind/issues/1498#issuecomment-878998917 aber mit §§, wenn es mehrere Paragrafen gibt

### Die Vollanzeige ist korrekt, _die Kurzanzeige nicht_:

https://ptah.ub.uni-tuebingen.de/Record/1763245209
![cic_844,3-5voll](https://user-images.githubusercontent.com/17004223/130044441-ef53f91c-3666-4871-b385-b86b70f595e1.JPG)


https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=id%3A1763245209&type=AllFields&botprotect=
![cic_844,3-5](https://user-images.githubusercontent.com/17004223/130044397-fa58e327-1834-4dd4-940c-60ef3519c593.JPG)


### https://github.com/ubtue/tuefind/issues/1498 ist zwar schon geschlossen, aber die Vollanzeige ist nicht korrekt ("can." fehlt; die Kurzanzeige ist korrekt):

https://ptah.ub.uni-tuebingen.de/Record/1650139438
![cic_1-203](https://user-images.githubusercontent.com/17004223/130048331-2a36f26c-f9bb-4de9-b070-7afc41a6f74c.JPG)


https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=id%3A1650139438&type=AllFields&limit=20&botprotect=


### Diese Anzeige passt:

> Korrekt wäre Codex iuris canonici 1983, can. 1044, §2 n. 2
> 
> in der Kurztitelanzeige so: CIC83 can. 1044, §2 n. 2

https://ptah.ub.uni-tuebingen.de/Record/1637685017
![cic_1044,2,2voll](https://user-images.githubusercontent.com/17004223/130045651-5505c5b4-5262-4c31-90fd-caafa158c030.JPG)


https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=cic83+1044%2C2%2C2&type=CanonesRangeSearch&limit=20&botprotect=
![cic_1044,2,2](https://user-images.githubusercontent.com/17004223/130045806-9e8947ec-3d86-4b41-8715-54325b32d67c.JPG)

**Comment by IxTheoKm** [comment]
### Weiteres Beispiel, das sowohl in der Vollanzeige, als auch in der Kurzanzeige nicht stimmt ("can." und "§§" fehlen, in der Kurzanzeige fehlt der Eintrag vollständig):

https://ptah.ub.uni-tuebingen.de/Record/1763312402
![cic_1600,1,2-3voll](https://user-images.githubusercontent.com/17004223/130050657-4e49a766-9927-49eb-92f3-3bc77785c0e8.JPG)

https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=id%3A1763312402+&type=AllFields&limit=20&botprotect=
![grafik](https://user-images.githubusercontent.com/17004223/130050862-9d214ba6-52c0-4103-8f93-ee877b5ef052.png)

**Comment by jriedl** [comment]
ad https://github.com/ubtue/tuefind/issues/1589#issuecomment-901778878: PR mit Workaround ist geöffnet.
ad https://github.com/ubtue/tuefind/issues/1589#issuecomment-901788356: Diese Notation wird derzeit von der Konvertierungsroutine für die Canones nicht unterstützt. Bedeutet das, dass nur die Absätze, 2 und 3 des Paragraphen 1 relevant sind? Da die Kurztitelanzeige aus den Bereichen selbst zurückgerechnet wird und hier kein Bereich existiert, erfolgt auch keine Anzeige. Falls diese Notation tatsächlich so unterstützt werden soll: @ruschein Können wird das noch einmal kurz besprechen?

**Comment by jriedl** [comment]
Die Unterstützung für Absatzbereiche ist nun integriert. Sollte auf ptah nach dem nächsten erfolgreichen Import sichtbar sein.

**Comment by jriedl** [comment]
Ist hier noch etwas offen?

**Comment by IxTheoKm** [comment]
Ich habe die verschiedenen Fälle nochmals durchgesehen. Wenn mir vor lauter "CIC", "can.", "§§" und "n." nichts durchgerutscht ist, passt es jetzt. Ich schließe.
