### ISSUE TITLE
Neue IxTheo-Klassifikation: ZG

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#1594]
> Die Runde der Fachreferenten im FID Theologie hat sich darauf geeinigt, eine neue Klassifikation für den IxTheo einzuführen:
> 
> ZG = Medienwissenschaft; Digitalität; Kommunikationswissenschaft
> 
> Auf Englisch: Media studies; Digital media; Communication studies
> 
> Weitere Beschreibung: "Betrifft alle Medien und alle Kommunikationsformen einschließlich der digitalen Medien und der Digital Humanities".
> 
> Unsere Bitte wäre jetzt, dass jemand aus Ihrem Team diese Klassifikation in allen Facetten, Menüs, Benutzeroberflächen und sontigen Kontexten auf den Webseiten von IxTheo, RelBib und weiteren damit verbundenen Webseiten hinzufügt. Vielen Dank im Voraus! 

Nachtrag: Beispiel-PPN wurde angefordert

**Comment by mtrojan-ub** [comment]
> Lieber Herr Trojan,
> 
> in den folgenden Datensätzen wurde die neue Klassifikation bisher benutzt:
> PPN 1760557765
> PPN 1756654093
> PPN 1756635528
> PPN 1756635501
> PPN 1756635463
> 
> Die letzten vier wurden gerade erst geändert.
> 
> Herzliche Grüße
> David Cloutier

**Comment by thefass** [comment]
Lierber @mtrojan-ub Kannst du bitte die Klarnamen noch entfernen

**Comment by mtrojan-ub** [comment]
Sorry, ich hatte nicht drauf geachtet... sind entfernt, wobei das natürlich in der History immer noch auftaucht.

Die neue Klassifikation wurde eingetragen und die Änderung auf ptah gepullt. Ich bin mir aber nicht sicher ob das schon auftaucht. Wir lesen die Klassifikationen aus dem Feld 652. Bei anderen Datensätzen taucht das sowohl in 652 als auch in LOK936 auf. Bei den o.g. Beispielen scheint das aber ausschließlich in LOK936 und nicht in 652 aufzutauchen. Gibt es dafür einen besonderen Grund?

Beispiel ZD (alt, 652 + LOK936): https://ixtheo.de/Record/1761423614#details
Beispiel ZG (neu, nur 652): https://ixtheo.de/Record/1760557765#details

**Comment by mtrojan-ub** [comment]
Auf ptah taucht jetzt auch im zweiten Beispiel das ZG-Feld auf. Außerdem findet man die neue Kategorie jetzt auch in der Facette "IxTheo-Klassifikation".
=> ready for testing

**Comment by thefass** [comment]
wenn man in der Erweiterten Suche auf eine Klasse eingrenzt, dann tauchen in der Facette alle? aber viel zuviele andere Klassen mit komsichen Prozentzahlen auf. Das ist aber nicht nur ptah so, sondern auch auf ixtheo. Deswegen dürfte das nichts mit der neuen Klasse zu tun haben

https://ptah.ub.uni-tuebingen.de/Search/Results?join=AND&lookfor0%5B%5D=&type0%5B%5D=AllFields&bool0%5B%5D=AND&filter%5B%5D=%7Eixtheo_notation_facet%3A%22ZG%22&limit=20&daterange%5B%5D=publishDate&publishDatefrom=&publishDateto=&botprotect=

![Bildschirmfoto 2021-07-29 um 22 12 59](https://user-images.githubusercontent.com/14169098/127559475-b64cb23d-5fad-4bc6-aa72-dcdcf516d55c.png)

**Comment by thefass** [comment]
ok ist: ZG in der Facette und auch unter A-Z

**Comment by mtrojan-ub** [comment]
Interessant! Scheint aber auch für andere Werte so zu sein. Dann schließe ich diesen Issue und verschiebe das mit den Prozentzahlen in einen separaten Issue.
