### ISSUE TITLE
Seltsames Highlighting

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#1599]
Bei einer erweiterten Suche nach  "(Verfasser:"Diözese limburg" UND Verfasser:"bischof")"
werden die Treffer gehighlightet:
https://canonlaw.ixtheo.de/Search/Results?sort=year+desc%2C+volume_sort+desc%2C+issue_sort+desc%2C+start_page+asc%2C+first_indexed+desc&join=AND&bool0%5B%5D=AND&lookfor0%5B%5D=%22Di%C3%B6zese+limburg%22&lookfor0%5B%5D=%22bischof%22&type0%5B%5D=Author&type0%5B%5D=Author

meistens ist das so: “...Katholische Kirche **Diözese Limburg Bischof** 2016- : Bätzing...”

Beim ersten Treffer aber nicht. Warum?
![Bildschirmfoto 2021-07-30 um 09 59 33](https://user-images.githubusercontent.com/14169098/127622447-4c8e12b0-7c5a-4251-b23c-bfd873c05f59.png)

Seltsam sind auch Treffer 20-25 und viele weitere der selben Art
![Bildschirmfoto 2021-07-30 um 10 11 41](https://user-images.githubusercontent.com/14169098/127622759-73ed0974-dd00-403d-8160-0a3c8e2729ae.png)

Es sieht so aus als ob 6xx für das Highlighting höher bewertet wird als 110

**Comment by jriedl** [comment]
Im Bezug auf den ersten Treffer liegt das wahrscheinlich daran, dass bei mehreren Highlight-Treffern in unterschiedlichen Feldern nur das erste in VuFind angezeigt wird. In Solr erkennt man, dass der zweite Highlight-Teil ebenfalls vorhanden ist, 
![image](https://user-images.githubusercontent.com/13135579/128038819-0e4fabac-7b5b-41e3-862c-0ea57723f0e5.png). 

Das scheint auch die Erklärung für Treffer 20 zu sein:
![image](https://user-images.githubusercontent.com/13135579/128039587-bee63784-226f-44ca-b546-79c50accc617.png)

MARC-Felder spielen beim Highlighting nur noch indirekt über die Solr-Felder, in die extrahiert wird, eine Rolle und haben keinen Einfluss auf die Match-Reihenfolge.
