### ISSUE TITLE
Auswahl per E-Mail versenden 

### ISSUE THREAD

**Issue by AleAprile** [ubtue/tuefind#1607]
Wenn ich versuche, ausgewählte Records an meine im Konto hinterlegte Email-Adresse zu schicken, bekomme ich eine Fehlermeldung.

![Screenshot_2021-08-04 Suchergebnisse - deeg](https://user-images.githubusercontent.com/41292389/128191897-ee3d25af-8c2b-4429-9f0a-b7e9f838fbfa.png)

Darauf hat mich eine Kollegin aus Heidelberg aufmerksam gemacht. Hängt das mit den technischen Problemen zusammen, die neulich aufgetreten sind? Oder ist was anderes?

**Comment by mtrojan-ub** [comment]
Ist vermutlich etwas anderes. In der Log-Datei auf ub16 findet man folgenden Fehler:

> 2021-08-04T15:45:07+02:00 CRIT (2): Laminas\Db\Adapter\Exception\RuntimeException : Duplicate entry 'Bu' for key 'shortlinks_hash_idx'

Dann wäre es weniger ein Problem mit dem Mailversand an sich, sondern eher ein Problem beim Generieren von Shortlinks.

**Comment by mtrojan-ub** [comment]
Interessant => auf ptah kommt da keine Fehler- sondern eine Erfolgsmeldung, aber die Mail kommt trotzdem nie an obwohl sie laut maillog korrekt von unserem Server an den Mailserver weitergegeben wurde.
```
Aug  4 16:45:21 ptah postfix/smtpd[863878]: connect from localhost[::1]
Aug  4 16:45:21 ptah postfix/smtpd[863878]: discarding EHLO keywords: CHUNKING
Aug  4 16:45:21 ptah postfix/smtpd[863878]: 4C521380E2146: client=localhost[::1]
Aug  4 16:45:21 ptah postfix/cleanup[863881]: 4C521380E2146: message-id=<20210804144521.4C521380E2146@ptah.ub.uni-tuebingen.de>
Aug  4 16:45:21 ptah postfix/qmgr[419994]: 4C521380E2146: from=<no-reply@ub.uni-tuebingen.de>, size=930, nrcpt=1 (queue active)
Aug  4 16:45:21 ptah postfix/smtpd[863878]: disconnect from localhost[::1] ehlo=1 mail=1 rcpt=1 data=1 commands=4
Aug  4 16:45:21 ptah postfix/smtp[863882]: 4C521380E2146: to=<mario.trojan@uni-tuebingen.de>, relay=mx05.uni-tuebingen.de[134.2.5.215]:25, delay=0.2, delays=0.05/0/0.15/0.01, dsn=2.0.0, status=sent (250 2.0.0 Ok: queued as 7B6FD40095EB)
Aug  4 16:45:21 ptah postfix/qmgr[419994]: 4C521380E2146: removed
```

**Comment by mtrojan-ub** [comment]
Nach vielen weiteren Tests kam dann doch die total unerwartete Ursache ans Tageslicht. Die Tabelle hat die falsche Zeichencodierung (latin1). Damit geht eine Collation einher, die nicht zwischen Groß- und Kleinschreibung unterscheidet (latin1_swedish_ci). War also schon ein base62 Hash mit Wert "BU" enthalten, so konnte kein neuer Hash mit Kleinschreibung "Bu" hinzugefügt werden.

D.h. aber auch => es hat immer eine Zeit lang funktioniert, dann wieder eine Zeit lang nicht, usw.

Wir werden die Tabelle entsprechend anpassen und auf utf8_bin umstellen.

**Comment by mtrojan-ub** [comment]
Anpassung auf ptah+ub16 durchgeführt => ready for testing.

**Comment by AleAprile** [comment]
Getestet mit 3, 20 und 500 Records. Es scheint alles richtig zu funktionieren. Vielen Dank für die schnelle Fehlerbehebung!
