### ISSUE TITLE
Normdaten: unvollständige Anzeige

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#1629]
100 $d wird unvollständig angezeigt:

https://ptah.ub.uni-tuebingen.de/Authority/695735993/Other%20Names#tabnav ?

100 |a Hahn |c Familie, Theologe |d ca. 18.-20.Jd.

![authZeit_Hahn](https://user-images.githubusercontent.com/17004223/129727738-967cac4d-00bb-4cb9-99a6-418d7eb93395.JPG)

**Comment by mtrojan-ub** [comment]
Ready for testing auf ptah

**Comment by IxTheoKm** [comment]
Die Anzeige ist zwar jetzt korrekt, aber nach genauerer Sichtung der Regeln ist die Erfassung von "Theologe" und der Zeitangaben in _100 |a Hahn  |c Familie, Theologe  **|d** ca. 18.-20.Jd._ nicht korrekt.
Anfrage in der Redaktion läuft.

**Comment by IxTheoKm** [comment]
Nach Korrektur ist der Datensatz jetzt in Ordnung. Ich schließe.
