### ISSUE TITLE
Alerting-Liste ist verschwunden

### ISSUE THREAD

**Issue by derclou** [ubtue/tuefind#1639]
Es geht um die Alerting-Funktion für das Konto "Sacherschliessung_neu" in IxTheo. Heute morgen war die Liste der schon abonnierten Zeitschriften auf einmal leer, und man konnte keine Zeitschrift abonnieren, weil das entsprechende Button weg war. Am Mittag ging es wieder, und die Liste war wieder vorhanden. Jetzt ist die Liste wieder leer, aber die Buttons zumindest vorhanden.

**Comment by mtrojan-ub** [comment]
Hängt vermutlich mit #1521 zusammen

**Comment by derclou** [comment]
Jetzt ist die Alerting-Liste wieder da. Herr Riedl meinte, ich könnte mich aus Versehen auf "ptah" statt auf dem richtigen IxTheo eingeloggt haben. Ich kann es nicht ausschließen. Deshalb mache ich erst mal die Labels weg, und werde die Sache in den kommenden Tagen genau beobachten. Wenn das Problem nicht mehr auftaucht, werde ich das Issue schließen.

**Comment by mtrojan-ub** [comment]
@derclou: Da das Problem seit über 2 Monaten nicht mehr aufgetreten ist, würde ich diesen Issue schließen.
