### ISSUE TITLE
TAD - bug?

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#1640]
Bei folgendem Titel wird trotz Einloggen (uni-Tübingen email vorhanden) kein TAD angezeigt:
https://www.ixtheo.de/Record/1767097441
Gibt es ein Erklärung dafür?

![Bildschirmfoto 2021-09-05 um 11 45 30](https://user-images.githubusercontent.com/14169098/132122529-8368c9cc-e21a-47aa-b7e2-8f7990a2af01.png)

**Comment by jriedl** [comment]
Bestand laut Lokaldaten Theologikum (DE-21-35) in 852. Für TAD freigeschaltet wird lediglich der unmittelbare UB-Bestand (DE-21).

**Comment by thefass** [comment]
Hätte ich wissen können ;-)
