### ISSUE TITLE
Umlenkungen

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#1643]
Am 3.9.2021 wurden Umlenkungen von Dubletten im K10plus umgesetzt. Im IxTheo sind sie auch nachvollzogen, d.h. die Lokalsätze sind alle am jeweiligen Zielsatz vorhanden. Ursprüngliche Dubletten sind aber weiterhin vorhanden. Wann verschwinden sie aus dem IxTheo?

Bsp.:
https://ixtheo.de/Record/781505399
Nach Umlenkung der Dubletten sind von 45 Aufsätzen noch 24 im K10plus.
Im IxTheo sind noch 45 vorhanden:

https://ixtheo.de/Search/Results?sort=title&lookfor=superior_ppn%3A781505399&type=AllFields

**Comment by IxTheoKm** [comment]
Weiteres Beispiel:
https://ixtheo.de/Record/780011090
64 / 32 Aufsätze:

https://ixtheo.de/Search/Results?lookfor=superior_ppn%3A780011090&type=AllFields&sort=title&botprotect=

**Comment by mtrojan-ub** [comment]
Wenn ich das richtig verstanden habe, sollen wir diese Information über die Löschlisten erhalten. Da wir nicht jeden Tag Löschlisten erhalten, kann es bis zu 1 Woche dauern bis die alten Einträge verschwinden.

Dazu folgender Hinweis: Dies wird dazu führen, dass die alten Datensätze verschwinden. Es kann aber nach wie vor sein, dass jemand alte Datensätze in seinen Favoritenliste oder anderen Teilen der Datenbank (Alerting o.Ä.). gespeichert hat. Diese werden bislang nicht umgeschrieben (ähnliches Problem wie bei der K10plus-Umstellung, darauf hatten wir bereits hingewiesen als die Umlenkungen erstmals angekündigt wurden).

Wir brauchen also entweder eine Mapping-Liste oder eine Information darüber, wie wir ein solches Mapping selbst erzeugen können.

**Comment by IxTheoKm** [comment]
Bei Umlenkungen werden alle PPNs (GBV, SWB) in den Zielsatz übertragen in Feld 889 $w

Bsp.:
https://ixtheo.de/Record/1475213417#details

![889_w](https://user-images.githubusercontent.com/17004223/132357163-706604a8-e785-472f-9940-d81bd10532f7.JPG)


Bei Mehrfachumlenkungen können es auch mehr sein.

**Comment by mtrojan-ub** [comment]
Anpassung in Arbeit. Ich habe auf ptah einen Testfall konstruiert der beim nächsten Pipeline-Durchlauf nach Einspielen der Anpassung migriert werden sollte:

![grafik](https://user-images.githubusercontent.com/26873381/132477195-4dcc43aa-29e4-458a-b476-ac176fb92bfa.png)

**Comment by mtrojan-ub** [comment]
Wurde heute auf ptah noch nicht eingespielt, aus folgenden Gründen:
- Pull wurde gestern durchgeführt, aber binary nicht gebaut (behoben)
- Tool in pipeline läut standardmäßig im --report-only Modus. Ich werde es mir morgen nochmal anschauen bevor --report-only entfernt wird.

**Comment by mtrojan-ub** [comment]
Heute haben wir eine Löschliste mit Datum von gestern erhalten (LOEKXP-210909). Diese wurde entsprechend verarbeitet, daher sind nun auch die "alten" Datensätze entfernt worden. DB-Korrekturen durch unser internes Programm (Favoritenlisten, ...) stehen aber noch aus.

**Comment by mtrojan-ub** [comment]
Das bestehende Migrationstool konnte bislang nicht richtig funktionieren. In der MARC-Pipeline werden an einer bestimmten Stelle alle Querverweise entfernt, zu denen die Quell-PPN nicht mehr in den Daten vorhanden ist. Das Migrationstool wurde bisher DANACH ausgeführt und hatte nur wenig Treffer. Führt man es auf die Gesamt-Datenmenge aus, so meldet es ca. 20.000 ausstehende Migrationen.

Wir erweitern derzeit erstmal den report_only-Modus um zu sehen, welche Teilmenge nun beim Abgleich gegen die Datenbanken (User-Alerts etc.) tatsächlich noch migriert werden würde.

**Comment by mtrojan-ub** [comment]
Anpassung des Tools abgeschlossen. Für ub16 wurde das Tool rückportiert, da der Live-Server nicht auf dem aktuellen Stand ist und wir insbesondere die DbConnection-Schnittstelle seit dem letzten Update stark überarbeitet haben.

Hier die Ergebnisse mit --report-only ohne Migration.

ptah:

> Would update 0 entries in "/usr/local/var/lib/tuelib/ixtheo_notified.db".
> Would update 0 entries in "/usr/local/var/lib/tuelib/relbib_notified.db".
> Would replace 2 rows in vufind.resource.
> Would replace 0 rows in vufind.record.
> Would replace 344 rows in vufind.change_tracker.
> Would replace 0 rows in ixtheo.keyword_translations.
> Would replace 0 rows in vufind.ixtheo_journal_subscriptions.
> Would replace 0 rows in vufind.ixtheo_pda_subscriptions.
> Would delete 0 entries from "/usr/local/var/lib/tuelib/ixtheo_notified.db".
> Would delete 0 entries from "/usr/local/var/lib/tuelib/relbib_notified.db".
> Would delete 0 rows from vufind.resource.
> Would delete 0 rows from vufind.record.
> Would delete 0 rows from vufind.change_tracker.
> Would delete 0 rows from ixtheo.keyword_translations.
> Would delete 0 rows from vufind.ixtheo_journal_subscriptions.
> Would delete 0 rows from vufind.ixtheo_pda_subscriptions.

ub16:

> Would update 0 entries in "/usr/local/var/lib/tuelib/ixtheo_notified.db".
> Would update 0 entries in "/usr/local/var/lib/tuelib/relbib_notified.db".
> Would replace 1 rows in vufind.resource.
> Would replace 0 rows in vufind.record.
> Would replace 346 rows in vufind.change_tracker.
> Would replace 0 rows in ixtheo.keyword_translations.
> Would replace 0 rows in vufind.ixtheo_journal_subscriptions.
> Would replace 0 rows in vufind.ixtheo_pda_subscriptions.
> Would delete 0 entries from "/usr/local/var/lib/tuelib/ixtheo_notified.db".
> Would delete 0 entries from "/usr/local/var/lib/tuelib/relbib_notified.db".
> Would delete 0 rows from vufind.resource.
> Would delete 0 rows from vufind.record.
> Would delete 0 rows from vufind.change_tracker.
> Would delete 0 rows from ixtheo.keyword_translations.
> Would delete 0 rows from vufind.ixtheo_journal_subscriptions.
> Would delete 0 rows from vufind.ixtheo_pda_subscriptions.

Die Umlenkungen haben also vorwiegend Auswirkung auf den change_tracker, aber es gibt kaum Auswirkungen auf Alerts oder Favoriten.

**Comment by mtrojan-ub** [comment]
Migration wurde auf beiden Servern durchgeführt.

**Comment by mtrojan-ub** [comment]
@IxTheoKm: Sind aus Ihrer Sicht die Änderungen in den Datensätzen vollständig angekommen?

**Comment by IxTheoKm** [comment]
Ich kann nur sagen, dass die Aufsätze der oben genannten Beispiele korrekterweise nicht mehr dublett sind. 

Ein am 24.09.2021 umgelenkter Datensatz ist noch dublett, aber da steht vermutlich die Löschliste noch aus:
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=Die+definitiv+vorgelegten+Wahrheiten+im+Sinne+der+%22Professio+fidei%22+1989%3A+Untersuchungen+zum+Motu+Proprio+%22Ad+tuendam+fidem%22&type=AllFields&botprotect=

Was mir auffällt:
in den zusammengeführten Datensätzen ist nur noch _einmal_ **889 $w** für DE-576 vorhanden. 
So lange der umgelenkte Datensatz noch im IxTheo vorhanden ist, gibt es noch das zweite Feld 889 $w für DE-627.

Was Sie sonst zu Ihrem Migrationstool schreiben, verstehe ich leider nicht. Daher kann ich dazu nichts sagen.

**Comment by IxTheoKm** [comment]
Ja, die Dublette ist aus ptah verschwunden.

**Comment by mtrojan-ub** [comment]
OK danke, dann würde ich den Issue schließen!
