### ISSUE TITLE
Normdatenseite zeigt unscharfe Ergebnisse

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#1649]
Kurze Zusammenfassung des Telefonats mit @thefass

Beispiel:
https://ptah.ub.uni-tuebingen.de/Authority/1725304600

![grafik](https://user-images.githubusercontent.com/26873381/132523414-a4c096a4-23c9-46e7-8c9e-9897408b66b3.png)

1) Das Bild gehört definitiv nicht zu diesem Autor
2) Newest Titles (by) => Nur einer der Titel (British freemasonry, 1717-1813) gehört tatsächlich zu diesem Autor

Die Fälle scheinen durch eine unscharfe Suche verursacht zu werden, wie sie im vufind-org Standard implementiert wurde. Derlei falsche Einträge sollen vermieden werden. Die einzige technische Möglichkeit dies zuverlässig zu tun ist, die Fuzzy-Algorithmen abzuschalten. Es sollten also nur dann Inhalte angezeigt werden, wenn tatsächlich eine exakte Verlinkung über eine ID vorhanden ist.

**Comment by mtrojan-ub** [comment]
Hinweis: Bislang hatten wir eine Tendenz zur Unscharfen Suche (siehe z.B. Aussagen in #1539) die also hierdurch wo immer möglich abgeschaltet wird.

**Comment by thefass** [comment]
was heißt "wo immer möglich"?

**Comment by mtrojan-ub** [comment]
=> Wo immer eine exakte ID zur Verfügung steht. Wenn wir also von der Normdatenseite auf Titel verlinken dann ist das möglich, wenn wir aber von den Titeln ausgehend nach weiteren Titeln desselben Autors suchen, und es sich um einen nicht normierten Autor handelt (ohne ID), dann wird dennoch eine String-basierte Suche erfolgen.

**Comment by mtrojan-ub** [comment]
Kann auf ptah getestet werden

**Comment by thefass** [comment]
ok
