### ISSUE TITLE
Archivmaterial bzw. "Literary Remains": Titel- und Normdaten

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#1654]
Aktuell rufen wir über das BEACON-Verfahren die Titelsätze vom Archivportal-D bzw. Kalliope ab und hängen diese im Rahmen der Pipeline an unsere Titeldaten an.

Bei manchen Fällen gibt es hierzu bereits Normdatensätze bei uns:
- Beispiel-Titel: https://ptah.ub.uni-tuebingen.de/Record/LR104066407#details
- Beispiel-Normdaten: https://ptah.ub.uni-tuebingen.de/Authority/076893081

Diese Normdatensätze sind jedoch aufgrund eines früheren Fehlers bei uns eingefügt worden (im Bezug auf sekkor, siehe #1567). Wenn wir also einen neuen Komplettabzug vom BSZ anfordern, werden diese Normdatensätze wieder verschwinden, weil sie ja BSZ-seitig mit keinem IxTheo-Titel verknüpft sind.

Frage 1) Ist das etwas, was auch im Rahmen von #1573 berücksichtigen müssen (GND-Nummern stehen uns ja über BEACON zur Verfügung), oder gibt es hier noch andere Möglichkeiten?
Frage 2) Die Normdatensätze sehen teilweise nicht unbedingt theologisch relevant aus (z.B. Juristen / Hochschullehrer, aber teilweise auch Heimatschriftsteller o.Ä.). Sind tatsächlich alle derzeitigen Archivmaterialien theologisch relevant oder müssen diese durch weitere Kriterien gefiltert werden?

**Comment by thefass** [comment]
Haben wir hier vielleicht einen Zirkelschluß? 
ad 2) Wir holen aus Kalliope und Archivportal-D ja nur Daten, wenn die GND der Person bei uns im IxTheo/Relbib vorhanden ist.
Wenn nun durch frühere Fehler aufgrund von sekkor zu viele falsche GNDs reingekommen sind, dann würde wir natürlich auch zuviele falsche Archivmaterial-Daten hereinholen.

**Comment by mtrojan-ub** [comment]
Stimmt! Dieser Teil würde sich dann also ebenfalls durch einen neuen SA beheben lassen.

**Comment by mtrojan-ub** [comment]
Heute wurde der neue SA auf ptah eingespielt.

Die o.g. beiden Datensätze existieren nun nicht mehr. Wie erwartet gibt es jetzt auch insgesamt weniger Normdaten und auch weniger Archivmaterial (vorher 58.000 => jetzt 44.000).

Sieht also gut aus, ich schließe.
