### ISSUE TITLE
Authority-Links zwischen Subsystemen

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#1656]
As discussed yesterday with @thefass:

If an author is listed in multiple subsystems, each subsystem should link to the entries in the other subsystems.

Example (IxTheo/RelBib):
- IxTheo: https://ptah.ub.uni-tuebingen.de/Authority/035286210
- RelBib: https://ptah.ub.uni-tuebingen.de:4448/Authority/035286210

Example (All Subsystems):
- IxTheo: https://ptah.ub.uni-tuebingen.de/Authority/07741571X
- RelBib: https://ptah.ub.uni-tuebingen.de:4448/Authority/07741571X
- BibStudies: https://ptah.ub.uni-tuebingen.de:4443/Authority/07741571X
- Churchlaw: https://ptah.ub.uni-tuebingen.de:4447/Authority/07741571X

(Note: Should we also do this for titles?)

**Comment by mtrojan-ub** [comment]
Ready for testing on ptah. @thefass, please have a look!

The logic seems to work fine. The question is if it would be better to display it in a different way (e.g. change labels of "IxTheo / KALDI / DaKaR", use some kinds of icons instead, ...)

**Comment by relhei** [comment]
@Gazeller: For subsystem RelBib the question is, if we want to list the multiple subsystems. Is that relevant to our user community?

**Comment by mtrojan-ub** [comment]
It will increase the ranking for all platforms in search engines like google if you do, so i'd highly recommend that!

**Comment by Gazeller** [comment]
Well, the ixtheo subsystem could be relevant for all those scholars who work at the fringes of Study of Religion and Christian Studies, i.e. Theology. Whether the other subsystems are relevant I doubt. But if the ranking in search engines were enhanced by showing those subsystems I'd agree with Mario.

**Comment by relhei** [comment]
Ok, got it :-)

**Comment by mtrojan-ub** [comment]
@AleAprile wanted us to put link in the new ixtheo2-Theme to the other subsystems as well. The question is: Do we need to design some logos for all of our subsystems which we can then use when linking between them?

**Comment by mtrojan-ub** [comment]
Logos for subsystems are already in work. However, for the authority links we leave it without a logo.
But: The link to "BILDI-IxTheo" should be renamed to "Index Biblicus", as discussed in the meeting.

**Comment by mtrojan-ub** [comment]
@thefass: Der Link auf "Index Biblicus" wurde umbenannt. Sollen wir dann der Konsistenz halber auch die anderen Links durch die lange Bezeichnung ersetzen? Also IxTheo => Index Theologicus, RelBib => Religionswissenschaftliche Bibliografie (ggf. übersetzt je nach gewählter Sprache) und IxTheo / KALDI / DaKaR so lassen bis es eine Einigung auf eine lange Namensform gibt?

**Comment by thefass** [comment]
wurde IxTheo schon auf Index Theologicus umgestellt? Bei mir sehe ich noch IxTheo. Oder bezieht sich ready for testing auf was anderes?

**Comment by mtrojan-ub** [comment]
Stimmt, sorry! Jetzt wurde es umgestellt!

**Comment by thefass** [comment]
ok

**Comment by IxTheoKm** [comment]
> IxTheo/KALDI/DaKaR lassen bis es eine endgültige Namensform gibt

Heißt jetzt Index Canonicus.
@thefass Soll das angepasst werden?

**Comment by thefass** [comment]
ja, bitte anpassen

**Comment by mtrojan-ub** [comment]
Wurde angepasst, siehe ptah

**Comment by IxTheoKm** [comment]
Passt, vielen Dank!
