### ISSUE TITLE
Volltextsuche auch für BibStudies + Churchlaw freischalten

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#1657]
Wunsch von @thefass.

@jriedl: Wieviel Aufwand steckt dahinter?

**Comment by jriedl** [comment]
Auf ptah. PS: Eventuell könnte die Bezeichnung des Gesamtbestandtabs noch einmal angepasst werden, z.B. grunsätzlich in allen Ansichten "Gesamtbestand" oder "Titel".

**Comment by mtrojan-ub** [comment]
@thefass: Ich bin zwar der Autor des Issues auf GitHub, aber die Anforderung stammte von Dir. Kannst Du es bitte testen und ggf. den Issue schließen? Vielen Dank!

**Comment by thefass** [comment]
Die Suche scheint zu tun, aber:
es werden nur in den ersten beiden Treffern und dann wieder ab Treffer 7 die Snippets angezeigt. Für die Treffer dazwischen fehlen sie. Bei Treffer 10-13 fehlen sie ebenfalls

https://ptah.ub.uni-tuebingen.de:4447/Search2/Results?lookfor=kanonisches%20recht&type=FulltextAllSynonyms&hiddenFilters%5B0%5D=has_fulltext%3A1&limit=20&botprotect=&lng=en

![Bildschirmfoto 2021-11-30 um 20 53 32](https://user-images.githubusercontent.com/14169098/144118341-4d2abd74-ae00-4df6-a483-245e38223042.png)

**Comment by thefass** [comment]
auf Index Biblicus scheint das nicht so zu sein

**Comment by jriedl** [comment]
Es besteht in der Behandlung der Abfragen kein technischer Unterschied zwischen Churchlaw und Bibstudies. Das "Problem" scheint der Suchterm zu sein, der aus zwei Wörtern besteht. Gesucht wird ja eigentlich nach "kanonisches recht" (als Phrase). Hier kommen jetzt subtile Unterschiede zwischen Solr (das die Ergebnismenge erzeugt) und Elasticsearch (das die Snippets liefert) ins Spiel. Solr ist offenbar in der Lage, die Synonyme standardmäßig auch mit mehreren Tokens aufzulösen. In ES ist hier hierfür eine Phrasensuche nötig, d.h. mit Anführungszeichen verhält es sich wie gewünscht (mit den "echten" Synonymen für "kanonisches Recht" und nicht nur für "Recht"): https://ptah.ub.uni-tuebingen.de:4447/Search2/Results?lookfor=%22kanonisches+recht%22&type=FulltextAllSynonyms&hiddenFilters%5B%5D=has_fulltext%3A1&limit=20&botprotect=.

**Comment by thefass** [comment]
ok
