### ISSUE TITLE
Normdatensuche - Treffer pro Seite

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#1665]
Bitte auch in den Normdatenseiten die Funktion "Treffer pro Seite" aktivieren

![Bildschirmfoto 2021-09-17 um 15 38 22](https://user-images.githubusercontent.com/14169098/133791927-348c5945-f2af-4d5a-b4c1-c558156394c8.png)

**Comment by mtrojan-ub** [comment]
ready for testing auf ptah

**Comment by thefass** [comment]
ok
