### ISSUE TITLE
Versteckte Zeichen bei der Titelsortierung

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#167]
Beim Testen der Sortierung von Titeln bin ich auf Zeichen gestoßen, die möglicherweise im Hintergrund existieren, aber für mich nicht sichtbar sind.
https://www.ixtheo.de/Search/Results?sort=title&limit=100&page=17903&type=AllFields

Nach Titeln mit "z" folgen noch _vor_ den Titeln, bei denen Sonderzeichen offensichtlich mitordnen, weitere Titel ohne Sonderzeichen. Es ist nicht erkennbar, warum sie an dieser Stelle stehen. Ruft man diesen Einzeltitel im Browser in einem neuen Tab auf, sieht man oben in den "Registerkarten" ein zusätzliches Zeichen, das bei anderen Titeln, die korrekt geordnet werden, nicht auftaucht. Auffällig: alle Stichproben sind elektronische Publikationen, deren Metadaten von irgendwoher in den SWB übernommen wurden:
![sortierung3_li](https://user-images.githubusercontent.com/17004223/35386150-45919cd0-01cb-11e8-9b53-9c76a9bf2742.jpg)

**Comment by IxTheoKm** [comment]
![sortierung4_li](https://user-images.githubusercontent.com/17004223/35390255-0c15c8d6-01db-11e8-9266-367daddb4503.jpg)

**Comment by mtrojan-ub** [comment]
bitte mal auf ptah ausprobieren

https://ptah.ub.uni-tuebingen.de/Search/Results?sort=title&limit=100&page=18097&type=AllFields

**Comment by IxTheoKm** [comment]
Auf ptah tauchen diese Titel nach "zz..." nun nicht mehr auf. 
Dafür allerdings die Titel mit einführenden spanischen Satzzeichen, die bei der Sortierung übergangen werden müssen, dann kommen die Titel mit Paragraphenzeichen.
Das ist bei IxTheo nicht der Fall. Da folgen direkt die Titel, die mit Paragraphenzeichen beginnen.

https://www.ixtheo.de/Search/Results?sort=title&limit=100&page=18098&type=AllFields
https://ptah.ub.uni-tuebingen.de/Search/Results?sort=title&limit=100&page=18097&type=AllFields
![sortierung2](https://user-images.githubusercontent.com/17004223/37822045-a73d5834-2e85-11e8-96d7-78a21f4ab631.png)

**Comment by mtrojan-ub** [comment]
scheinbar war die Importlogik auf ptah doch nicht ganz auf dem neuesten Stand.
habe das jetzt aktualisiert und als Test 094814767 neu importiert (¡Ayudadme a ser hombre....), es taucht jetzt nicht mehr an der o.g. Stelle auf.

Das sollte am Montag mit dem nächsten Gesamt-Import auf ptah gelöst sein, bitte dann nochmal testen

**Comment by IxTheoKm** [comment]
Sieht jetzt gut aus, danke!
