### ISSUE TITLE
"Alphabetisch browsen, Nach Thema" findet normierte Personennamen nicht

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#168]
Folgender Titel wird nicht gefunden:
https://www.ixtheo.de/Record/346968348 [Schlagwort in 689: Simon-Pierre, Schwester]

![thema_browsen](https://user-images.githubusercontent.com/17004223/35394828-068fd240-01e9-11e8-8def-67e72d4acfcd.png)

Wird aber gefunden über "Thema browsen" 
[Was ist der Unterschied zw. "Alphabetisch Browsen, Nach Thema" und "Thema browsen"?]:
https://www.ixtheo.de/Keywordchainsearch/Results?lookfor=simon-pierre&type=KeywordChainSearch

![thema_browsen2](https://user-images.githubusercontent.com/17004223/35394971-602552ee-01e9-11e8-877e-c64c31bd09c9.png)

Folgende Titel werden nicht gefunden:
https://www.ixtheo.de/Record/059197048 [Schlagwort in 689: Maria Lucia, Schwester]
https://www.ixtheo.de/Record/326415572

![thema_browsen3](https://user-images.githubusercontent.com/17004223/35395116-c21f83ca-01e9-11e8-841d-601cd69872d2.png)
Aufgeführt wird nur der Titel mit dem nicht-normierten Schlagwort in 600!

Über "Thema browsen" setzt die Suche in diesem Fall an falscher Stelle auf:

Wenn ich innerhalb der Trefferliste weiterblättere oder gezielt bestimmte Seiten aus der angezeigten Liste anklicke, wird die Sortierung völlig undurchsichtig und wechselt die Zahl der Seiten (zuerst sind es 97, dann ändert sich die Anzahl abhängig davon, welche angeklickt wird:
https://www.ixtheo.de/Keywordchainsearch/Results?lookfor=maria+lucia&type=keywordChainSearch&page=97
![thema_browsen5](https://user-images.githubusercontent.com/17004223/35395930-f013472e-01eb-11e8-96bb-ff3793ea0ad8.png)

Nach Klick auf Seite 97:
![thema_browsen6](https://user-images.githubusercontent.com/17004223/35396149-6dd56476-01ec-11e8-89f8-fbf96a9d9c59.png)

Nach Klick auf Seite 55:
![thema_browsen7](https://user-images.githubusercontent.com/17004223/35396280-b635f500-01ec-11e8-8844-113747944cb3.png)

**Comment by jriedl** [comment]
Das hängt mit der den ausgewerteten Ausgangsfeldern zusammen (vgl. #63). Maria Lucia Schwester wird jetzt gefunden (auf ptah). Das Problem der springenden Ergebnismengen beim Klick auf die letzte Seite ist ebenfalls behoben.

**Comment by jriedl** [comment]
Zum alphabetischen Browsen allgemein: Dieses ist inbesondere nützlich, wenn ein Überblück über vorhandene Einträge ohne eine konkrete Suchvorstellung verwendet wird. Technisch ist es jedoch völlig anders implementiert, als die üblichen Suchen. Für das alphbetische Browsen werden bestimmte Felder aus Solr extrahiert, aufbereitet und in einer SQLite (das ist eine Art Mini-SQL-Datenbank) gespeichert. Erst die Suche der dazugehörigen PPNs erfolgt dann wieder durch VuFInd in Solr. Deshalb sind hier in Solr mit vertretbarem Aufwand umzusetzende Anpassungen nicht möglich, da es sich um eine reine Term-Suche ohne weitere Aufbereitung wie bei Solr handelt.

**Comment by IxTheoKm** [comment]
Danke, funktioniert jetzt. Danke auch für die Erklärungen!
