### ISSUE TITLE
Autorenverlinkung mit kleinem "x" in PPN

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#1681]
Es gibt in der Pipeline ca. 400 Fehler nach folgendem Schema:
> Unable to find offset for authority PPN 70674442x referenced in title PPN 1086498402

[Hier eine Liste der betroffenen Verlinkungen](https://github.com/ubtue/tuefind/files/7242240/x.log)

Beispiel:
https://ixtheo.de/Record/1086498402#details
700 | 1 |   | \|a Singh, Wazir    \|d 1927-    \|e Hrsg.    \|0 (DE-588)124944876    \|0 (DE-627)70674442x    \|0 (DE-576)294581804    \|4 edt
-- | -- | -- | --

Der Datensatz mit großem X existiert aber.
Ist das kleine `x` in der PPN ein Exportproblem oder wurde es falsch gepflegt?

**Comment by thefass** [comment]
> Was meinen Sie mit "toleriert"?
> Wo toleriert?

Damit meinte ich, dass im Pica System keine Einheitlichkeit besteht, so dass sowohl kleines x als auch großes X erzeugt werden kann / erzeugt wurde.

**Comment by IxTheoKm** [comment]
Die Verbundzentrale schreibt, dass sie schon einmal "geputzt" hätten. Wir sollten ihnen die Liste zum nochmaligen Putzen schicken. (Das betrifft dann wohl nur Datensätze, die an uns geliefert werden. Ich vermute, dass es darüber hinaus mehr gibt.)

Daraus entnehme ich indirekt, dass es ein großes "X" sein soll.
Auf meine Frage, wie das klein "x" zustande kommt, habe ich keine Antwort bekommen. Ich könnte mir nur vorstellen, dass es sich um manuell eingetragene (und dann evtl. kopierte) PPN-Verknüpfungen handelt.

**Comment by thefass** [comment]
@mtrojan-ub Können wir das vielleicht so lösen, dass es egal ist, ob das x klein oder groß ist?

**Comment by mtrojan-ub** [comment]
An allen Stellen bei denen wir PPNs auslesen ein Uppercase durchzuführen halte ich für Fehleranfällig (das sind ziemlich viele, und wenn man eine neue Stelle einführt vergisst man das schnell).
Theoretisch könnten zwar eine weitere Phase in der MARC Pipeline einführen die das normalisiert, aber da die IxTheo-Pipeline schon 45 Einzelphasen hat und wir in jeder Phase ca. 10GB Daten durch die Gegend schieben wäre mir ehrlich gesagt die Lösung mit dem "Putzen" deutlich lieber. (Liste siehe oben)

**Comment by thefass** [comment]
ok, Danke für das Feedback @mtrojan-ub 
Dann soll das BSZ mal putzen

**Comment by IxTheoKm** [comment]
> (Am Allerliebsten wäre mir noch wenn die Verbundzentrale verhindert dass überhaupt ungültige Werte in solche Felder eingetragen werden können)

Gegen Validationen sperrt sich aus unerfindlichen Gründen regelmäßig der GBV ...

**Comment by IxTheoKm** [comment]
Rückmeldung aus der Verbundzentrale: alle Fälle sind maschinell durch ein Programm entstanden, das jetzt angepasst wird. Danach soll ein Putzprogramm laufen.

**Comment by IxTheoKm** [comment]
Rückmeldung BSZ 30.11.2021: die VZG hat inzwischen das Programm korrigiert, dass das fehlerhafte kleine x erzeugt hat, nachdem schon ca. 20.000 Datensätze korrigiert waren. In den nächsten Tagen werden mit einem neuen Putzlauf die letzten Fälle bereinigt. Damit dürfte das Problem gelöst sein. Ich schließe daher.
