### ISSUE TITLE
Normdaten: Anzeige von Affiliationen (+Wirkungsorten)

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#1687]
![grafik](https://user-images.githubusercontent.com/25769591/135243348-6c7f29f4-ea00-4d79-b921-ad141b65313c.png)
https://134.2.67.9/Authority/690570848

Die Darstellung der Corporate Relations finde ich aktuell noch nicht optimal: In dem Beispiel hier steht in Klammern (Affiliation), das müsste meiner Meinung nach nicht unbedingt erscheinen: Besser wäre es, die Art der Afiliation anzuzeigen ("wiss. Mitarbeiterin") - oder sie ganz wegzulassen, wenn wir das schlank halten wollen.
Bei der ersten Affiliation fehlt zudem der Ort (Universität Leipzig) - hier müsste vmtl. das entsprechende Unterfeld noch ausgelesen werden. 
Warum die Körperschaften so unterschiedlich erfasst sind, weiß ich auch nicht - Frage an @IxTheoKm: Ist das so korrekt? Im vorliegenden Fall steht bei der ersten Affiliation das Institut an erster Stelle, im Unterfeld die Universität, bei der zweiten Affiliation steht zuerst die Universität, in einem Unterfeld dann die (zugeordnete) Einrichtung.

**Comment by IxTheoKm** [comment]
Das hängt an der Erfassung des Körperschaftssatzes in der GND. Manche Einrichtungen sind selbständig, manche unselbständig angelegt. Das ist auch abhängig vom Regelwerksstand bei der Erfassung des Körperschaftssatzes in der GND. Daran können wir nichts ändern. Es gibt massenhaft Datensätze, die nach heutigem Stand anders aussehen würden.

Affiliations sind sowieso problematisch. Manche Personennormsätze sind heillos veraltet. Wir können bei der Katalogisierung auch nicht jeden für Personenormsatz die Affiliations prüfen/aktualisieren. Dann kämen wir mit der Aufsatzerfassung nicht voran.
Wir können also nur die vorhandenen Daten so wie sie sind anzeigen.

Die Art der Affiliation ist zwar im o.g. Fall erfasst, aber oft ist das gar nicht der Fall.

**Comment by mtrojan-ub** [comment]
Nach welchem Muster sollen also die Unterfelder genau für die Anzeige aufbereitet werden? (z.B. "Universität Leipzig" kommt ja bei der ersten Affiliation gar nicht vor, sondern nur "Leipzig").

**Comment by mtrojan-ub** [comment]
Im Meeting besprochen: @relhei bespricht das Thema telefonisch mit @IxTheoKm

**Comment by IxTheoKm** [comment]
Sieht für mich auch okay aus.

Bei den Affiliations sind die Orte - je nach Erfassungsform der Körperschaften - teilweise angezeigt.
Ich weiß nicht, ob über den Umfang der Informationen zur Person im Detail gesprochen wurde.
Es gibt auch z.T. Wirkungsorte (manchmal zsätzlich zu den Affiliations, manchmal _nur_ Wirkungsorte ohne Affiliations). 
Sollen die bewusst nicht angezeigt werden?

Bsp.:
https://ptah.ub.uni-tuebingen.de/Authority/690570848

551 $0(DE-627)106319795$0(DE-576)208931325$0(DE-588)4019947-2$aGelsenkirchen$4**ortg**$wr$iGeburtsort
551 $0(DE-627)106374028$0(DE-576)208869697$0(DE-588)4007328-2$aBochum$4**ortw**$wr$iWirkungsort

https://ptah.ub.uni-tuebingen.de/Authority/08175681X

551 $0(DE-627)106363174$0(DE-576)208882065$0(DE-588)4009352-9$aCambridge, Mass.$4**ortw**$wr$iWirkungsort
551 $0(DE-627)106122509$0(DE-576)209154780$0(DE-588)4064682-8$aWashington, DC$4**ortw**$wr$iWirkungsort

https://ptah.ub.uni-tuebingen.de/Authority/539938793

551 $0(DE-627)105952516$0(DE-576)209343052$0(DE-588)4098416-3$aKirchberg (Hunsrück)$4**ortw**$wr$iWirkungsort

**Comment by mtrojan-ub** [comment]
"Geografischer Bezug" wurde bisher nur bei Tagungsbeiträgen angezeigt. Jetzt wird es immer angezeigt, siehe ptah.

**Comment by thefass** [comment]
ok
