### ISSUE TITLE
Erweiterte Suche: Filtermöglichkeiten fehlen

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#1688]
In RelBib werden in der erweiterten Suche aktuell die Filtermöglichkeiten (RelBib-Klassifikation, Medienart, Sprache, Erscheinunsgjahr) NICHT angezeigt. Bitte wieder hinzunehmen.

![grafik](https://user-images.githubusercontent.com/25769591/135439439-c040665a-2bfa-4c27-970d-fdb43d9855a7.png)

https://www.relbib.de/Search/Advanced

Im Vergleich dazu sind diese Filtermöglichkeiten im IxTheo weiterhin vorhanden:

https://www.ixtheo.de/Search/Advanced

**Comment by mtrojan-ub** [comment]
Ready for testing auf ptah

**Comment by relhei** [comment]
Passt. Danke!
