### ISSUE TITLE
Falsche Anzeige persönlicher Namen als Verfasser

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#169]
https://www.ixtheo.de/Record/059197048#details

Bitte alle Personennamen (100, 700) analog zum Schlagwort (689) jeweils mit Komma vor |b und |c anzeigen 

![maria_lucia_li](https://user-images.githubusercontent.com/17004223/35397220-37c2b8ae-01ef-11e8-8f01-23ff914d7106.jpg)

Betrifft die Vollanzeige und die Kurzliste:
https://www.ixtheo.de/Search/Results?lookfor=id%3A059197048&type=AllFields&limit=20&sort=year+desc%2C+issue_sort+desc%2C+start_page+asc

Weiteres Beispiel:
https://www.ixtheo.de/Search/Results?lookfor=id%3A465579868&type=AllFields&limit=20&sort=year+desc%2C+issue_sort+desc%2C+start_page+asc

Es gibt allerdings ein Problem:
|d Lebensdaten sollten vermutlich bei den Personen angezeigt werden. 
In manchen Fällen stehen die Lebensdaten zusätzlich in |c und werden dadurch gedoppelt. 

Momentan wird |d in 100 und 700 angezeigt, nicht aber in 689:
https://www.ixtheo.de/Record/494600446#details
![benedikt_li](https://user-images.githubusercontent.com/17004223/35398770-09e772fe-01f3-11e8-979d-b66e840dc3fe.jpg)

@thefass Soll das so bleiben?

**Comment by jriedl** [comment]
Kommata vor b und c werden jetzt auf ptah bei beim Import eingefügt. Bezüglich des Problems der Doppelung der Lebensdaten bei PPN 059197048 scheint nach einer Stichprobenprüfung dieser Problem nicht häufig aufzutreten. Lasen sich hier einfach die Lebensdaten aus dem c-Feld entfernen?

**Comment by jriedl** [comment]
Ist hier noch etwas offen?

**Comment by IxTheoKm** [comment]
$c und $d werden jetzt in 100, 700  und 689 nach $a angezeigt (allerdings ohne trennendes Komma zwischen $c und $d. Das finde ich aber okay).
Beispiel:
https://www.ixtheo.de/Record/874065992

![PersName](https://user-images.githubusercontent.com/17004223/56952141-dd342200-6b39-11e9-821e-577fe9cc0049.JPG)

Inzwischen festgestellt:
Namen tauchen auch in Feld 800 auf. Bitte auch hier analog umsetzen, also Komma zwischen $a und $c und zusätzlich zwischen $d und $t, um den Titel abzutrennen.
Beispiel:
https://ptah.ub.uni-tuebingen.de/Record/1576321622#details

![PersName2](https://user-images.githubusercontent.com/17004223/56952683-29339680-6b3b-11e9-9089-d68cb8fafaed.JPG)

**Comment by jriedl** [comment]
Auf ptah jetzt so umgesetzt.

**Comment by IxTheoKm** [comment]
Jetzt in Ordnung, vielen Dank!
