### ISSUE TITLE
Übersetzungen für Alertpakete

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#1693]
Aus Mail von @relhei:
[Übersetzungen Alertpakete.docx](https://github.com/ubtue/tuefind/files/7259616/Ubersetzungen.Alertpakete.docx)

**Comment by jriedl** [comment]
Das würde voraussetzen, dass wir allgemein auf Titelebene einen Filter in Abhängigkeit von der gewählten Sprache implementieren. Das ist möglich, aber wahrscheinlich aufwändig und es stellt sich die Frage, ob so ein Ansatz im allgemeinen Fall wünschenswert ist. Was mit überschaubarem Aufwand machbar ist, wäre die Auszeichnung der entsprechenden Records mit einem Sprachcode, der ja dann auch über eine Facette auswählbar und verlinkbar ist.

**Comment by relhei** [comment]
Das funktioniert. Ist ein akzeptabler Kompromiss. Danke!
