### ISSUE TITLE
IxTheo A-Z Dokument fehlt

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#170]
Der Link auf "Zweitveröffentlichung" im Menü "IxTheo A-Z" führt ins Leere:
https://ptah.ub.uni-tuebingen.de/docs/Zweitveroeffentlichung_FAQ.pdf
bzw.
https://www.ixtheo.de/docs/Zweitveroeffentlichung_FAQ.pdf

**Comment by jriedl** [comment]
Ist auf ptah und ixtheo behoben.

**Comment by IxTheoKm** [comment]
Danke, jetzt o.k.
