### ISSUE TITLE
BEACON für BibStudies + Churchlaw + KrimDok generieren

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#1707]
- siehe bestehende cronjobs `generate_beacon_file.py` auf IxTheo-Systemen.
- Für die beiden Systeme muss ein header-template generiert werden (siehe cpp/data/ixtheo-beacon.header und relbib-beacon.header). Änderungen zu #1019 sollten hier ebenfalls berücksichtigt werden.
- Ggf. muss sowieso der Parameter `--filter-field=REL` angepasst werden, damit es in Zukunft statt `REL` auch mit `SUBa == "relbib"` usw. funktioniert.
- Sobald die Generierung aktiv ist müssen die Files auch in den Oberflächen verlinkt werden (typischerweise auf A-Z-Seiten, falls vorhanden)

**Comment by socheres** [comment]
der Targetlink mit `author_id` führt nicht zu einem Trefferergebnis.
https://ixtheo.de/Search/Results?lookfor=author_id:115684336

**Comment by mtrojan-ub** [comment]
Ist bekannt + wird hauptsächlich in einem anderen Issue bearbeitet: #1019

**Comment by thefass** [comment]
Stichproben sind in allen drei subsysteme passend

**Comment by thefass** [comment]
Infos für die Beacon Datei BibStudies:

#NAME: INDEX BIBLICUS (BILDI-IxTheo)
#MESSAGE: INDEX BIBLICUS: Publikationen im Index Biblicus
#DESCRIPTION: Die Datenbank "Index Biblicus" (https://bibel.ixtheo.de) ist eine internationale, open access Bibliographie für die Bibelwissenschaften, herausgegeben von der Universtitätsbiblitohek Tübingen und der Katholisch-Theologischen Fakultät Innsbruck (BILDI). Ausgewertet werden alle Mediengattungen wie Monographien, Aufsätze, Rezensionen, Websites, Weblogs, Datenbanken, Archivmaterial und Nachlässe, Forschungsdaten etc.
Statistik: ca. 450.000 Einträge (Stand März 2022).

****
Infos für A-Z auf https://bibel.ixtheo.de:

Die mit der GND-Nummer ausgezeichneten Katalogisate des Index Biblicus stehen im BEACON-Format zur Verfügung und können in andere Datenbanken verlinkt werden.
Weitere Infos siehe: [Wikipedia](https://de.wikipedia.org/wiki/Wikipedia:BEACON) oder [Github](http://gbv.github.io/beaconspec/beacon.html)

**Comment by thefass** [comment]
Infos für die Beacon Datei Canonlaw:

#NAME: INDEX CANONICUS (KALDI-IxTheo-DaKaR)
#MESSAGE: INDEX CANONICUS: Publikationen im Index Canonicus
#DESCRIPTION: Die Datenbank "Index Canonicus" (https://canonlaw.ixtheo.de oder https://churchlaw.ixtheo.de) ist eine internationale, open access Bibliographie für das Fach "Kanonisches Recht" und "Kirchenrecht", herausgegeben von der Universitätsbibliothek Tübingen, der Katholisch-Theologischen Fakultät Innsbruck (KALDI) und dem Institut für Kanonisches Recht (DaKaR). Ausgewertet werden alle Mediengattungen wie Monographien, Aufsätze, Rezensionen, Lexikonartikel, Websites, Weblogs, Datenbanken, Archivmaterial und Nachlässe, Forschungsdaten etc.
Statistik: ca. 160.000 Einträge (Stand März 2022).

Infos für A-Z auf https://canonlaw.ixtheo.de oder https://churchlaw.ixtheo.de

Die mit der GND-Nummer ausgezeichneten Katalogisate des Index Canonicus stehen im BEACON-Format zur Verfügung und können in andere Datenbanken verlinkt werden.
Weitere Infos siehe: [Wikipedia](https://de.wikipedia.org/wiki/Wikipedia:BEACON) oder [Github](http://gbv.github.io/beaconspec/beacon.html)

@mtrojan-ub in den txt Dateien sind die Umlaut nicht richtig dargestellt
<img width="1397" alt="Bildschirmfoto 2022-03-21 um 12 29 48" src="https://user-images.githubusercontent.com/14169098/159252704-ca4458aa-00f0-45fc-a613-9d354d6b7bfe.png">

**Comment by thefass** [comment]
Bitte auch die Desciption in der IxTheo Beacon Datei anpassen. Ist veraltet.

#DESCRIPTION: Die Datenbank "Index Theologicus" (IxTheo: https://ixtheo.de) ist eine internationale, open access Bibliographie für Theologie und Religionswissenschaft. Ausgewertet werden alle Mediengattungen wie Monographien, Aufsätze (aus mehr als 1.000 theologischen und religionswissenschaftlichen Zeitschriften sowie Aufsätze aus Sammelschriften, z.B. Festschriften und Kongressschriften), Rezensionen, Lexikonartikel, Websites, Weblogs, Datenbanken, Archivmaterial und Nachlässe, Forschungsdaten etc.
Statistik: mehr als 390.000 Personen- und Körperschafts-GND, mehr als 2,8 Mio Titel (Stand März 2022).

**Comment by thefass** [comment]
@KStelzel : trägst Du bitte noch die Vorgaben für die Krimdok Beacon Datei hier ein. Oben ein paar Beispiele aus dem IxTheo Kontext

**Comment by mtrojan-ub** [comment]
@KStelzel und @JMeister01, könnt Ihr bitte in diesem Issue noch die Infos für die KrimDok BEACON Datei eintragen?

**Comment by KStelzel** [comment]
Die Datenbank "KrimDok" (https://krimdok.uni-tuebingen.de/) ist eine internationale, open access Bibliographie für Kriminologie. Ausgewertet werden alle Mediengattungen wie Monographien, Aufsätze (aus mehr als 200 kriminologischen und bezugswissenschaftlichen Zeitschriften sowie Aufsätze aus Sammelschriften, z.B. Festschriften und Kongressschriften), Rezensionen, Websites, Statistiken, Forschungsdaten etc.
Derzeit beinhaltet KrimDok rund 300.000 kriminologische (Stand November 2022).

**Comment by mtrojan-ub** [comment]
Der letzte Satz liest sich etwas seltsam, es scheint ein Wort zu fehlen... auf was bezieht sich das Wort `kriminologische`? Titel? Einträge?

**Comment by KStelzel** [comment]
Oh ja, da fehlt das Wort "Nachweise".

Danke!

**Comment by mtrojan-ub** [comment]
Die Texte wurden nun angepasst. Allerdings ist uns aufgefallen, dass beim Abruf über die Server die Zeichenkodierung kaputt zu sein scheint:
https://ixtheo.de/docs/ixtheo-beacon.txt

![grafik](https://user-images.githubusercontent.com/26873381/207053790-dbaefcaa-16c0-4146-bc93-b82258aaf72b.png)


Das müssen wir uns also nochmal anschauen.

**Comment by mtrojan-ub** [comment]
@steven-lolong, as discussed: please modify the cronjob in a way that it adds a UTF8-BOM when generating the output file.

**Comment by mtrojan-ub** [comment]
Wurde auf ptah angepasst, ich schau's mir dort morgen nochmal an wenn die cronjobs durch sind

**Comment by mtrojan-ub** [comment]
Die BEACON-Dateien an sich werden nun erzeugt und sehen auf den Testservern gut aus (Kodierungsprobleme wurden behoben). Allerdings zeigen die Links im Index Biblicus und Index Canonicus noch auf die Datei vom Index Theologicus, das müssen wir noch anpassen.

**Comment by mtrojan-ub** [comment]
Die links wurden angepasst, siehe ptah => ready for testing.

**Comment by thefass** [comment]
ok
