### ISSUE TITLE
BEACON für "External Ressources"

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#1708]
Wie im Meeting besprochen: Weitere Beacon-Dateien harvesten und mit Normdaten abgleichen, bei Treffer einen Link in "External References" aufnehmen.

Beachten: Wenn #1706 umgesetzt wird muss es in der passenden Untersektion landen.

@socheres, wie besprochen: BEACONs bitte in diesem Issue posten.

**Comment by mtrojan-ub** [comment]
Erste Version jetzt auf ptah => ready for testing, Beispiel:
https://ptah.ub.uni-tuebingen.de/Authority/035286210

Ein paar Hinweise dazu:
- Offenes TODO: beacon.findbuch.de in ub16 firewall freischalten (80+443) für Live-Betrieb
- Design OK? (z.B. Grafiken sind jetzt kleiner geworden, da der Platz an der Seite benötigt wird)
- Sortierung OK? (nach Anzahl absteigend, dann alphabetisch aufsteigend)
- Was passiert mit dem alten "External Ressources"? rausnehmen?
- Über die API kommen auch verschiedene Referenzen auf IxTheo und RelBib mit. Sollen diese gefiltert werden?

**Comment by thefass** [comment]
> * Design OK? (z.B. Grafiken sind jetzt kleiner geworden, da der Platz an der Seite benötigt wird)

Ja, ist ok

> * Sortierung OK? (nach Anzahl absteigend, dann alphabetisch aufsteigend)

Ja, ist ok

> * Was passiert mit dem alten "External Ressources"? rausnehmen?

nein, sondern in der Spalte rechts ausschließen. Diese sollen hervorgehoben werden


> * Über die API kommen auch verschiedene Referenzen auf IxTheo und RelBib mit. Sollen diese gefiltert werden?

Ja, auf jeden Fall

**Comment by thefass** [comment]
Insgesamt kommen sehr viele Links mit, die Mist sind. 
Wir müßten viel ausfiltern
m.E. alle Bibliothekslinks (manche sind zweimal da, z.B. HBZ-Verbundkatalog)
Mist ist z.B. discogs, allmusic.com etc.
dann die ganzen ID-Beacon wie Cultureel Woordenboek ID etc.
Dann gibt es etliche mit 404 Fehler:

Es stellt sich die Frage, ob wir nicht doch lieber eine kleine, gepflegte Beacon Sammlung anbieten. Das wäre ein Mehrwert für den Nutzer, da er sich nicht durch viele sinnlose klicken muss.

Meinungen? @socheres

**Comment by socheres** [comment]
Zu. 1. Oder besser statt beacon-datei zu ändern nur vorhandene Target-URL ein- bzw. ausschließen. @mtrojan-ub Sind diese Target-URL irgendwo hinerlegt?

**Comment by socheres** [comment]
> @mtrojan-ub wenn du diese Ressourcen in die "Biographische Referenzen" aufgenommen hast, bitte aus der Spalte "Externe Ressourcen" ebenfalls ausschließen.
> 
> ```
> #388785	adbreg
> #407074	bbkl@ap
> #240158	gersac_brabis
> #409242	leobw-kglbio
> #409815	orcid@wd
> #406308	wikidata
> ```
@mtrojan-ub die oben geannten Quellen außer orcid sind noch nicht im Bereich "Biographische Referenzen" aufgeführt. Z.B.:https://www.deutsche-biographie.de/sfzZ0682-5.html
https://ptah.ub.uni-tuebingen.de/Authority/077404084
Kannst du diese hinzufügen?
Außerdem bitte `#411548	mghopac` `#216384	unibib_rub` in die EXCLUSION_LIST aufnehmen.

**Comment by mtrojan-ub** [comment]
ORCID / VIAF / ISNI usw sind schon vorhanden, sofern es in den Daten hinterlegt ist. Beispiel:
https://ptah.ub.uni-tuebingen.de/Authority/077255976

**Comment by mtrojan-ub** [comment]
> wenn du diese Ressourcen in die "Biographische Referenzen" aufgenommen hast, bitte aus der Spalte "Externe Ressourcen" ebenfalls ausschließen.

Beim Versuch das umzusetzen bin ich über ein Problem gestolpert. Die Bezeichnungen sind nicht exakt gleich.
z.B. "Wikipedia" => "Wikipedia-Artikel". Wenn ich das z.B. fuzzy mit einem Substring matche, dann wird auch folgendes gefiltert:
"GND" => "REGESTA IMPERII RI OPAC GND", was wir dann wahrscheinlich behalten wollen.

Somit wäre der einzig sichere Ansatz eine Mapping-Liste. Ich schau mal was sich machen lässt.

**Comment by mtrojan-ub** [comment]
Für das Wikipedia-Beispiel habe ich jetzt einen Filter hinterlegt. Die Anderen konnte ich bei Stichproben nicht in den Externen Ressourcen finden.

=> ready for testing

Falls noch etwas auffällt, bitte Beispiel-PPN nennen.

**Comment by socheres** [comment]
> ORCID / VIAF / ISNI usw sind schon vorhanden, sofern es in den Daten hinterlegt ist. Beispiel:
> https://ptah.ub.uni-tuebingen.de/Authority/077255976

Was bedeutet, "sofern in den Daten hinterlegt ist"? Wurde eine Liste erstellt bzw. wo finde ich diese bereits hinterlegten biographischen Quellen?  Z.B. `#388785	adbreg` ADB/NDB Deutsche Biographie fehlt im Bereich "Biographische Referenzen".

**Comment by mtrojan-ub** [comment]
GND: 035
ISNI/LOC/ORCID/VIAF/Wikidata: 024
Wikipedia: 670

BEACONs sind in Biographische Referenzen bislang technisch nicht möglich.
Wo genau in den MARC-Daten steht denn der ADB/NDB-Verweis?

**Comment by relhei** [comment]
Beispiel einer Autorin aus unserem Zweitveröffentlichungsservice:
![grafik](https://user-images.githubusercontent.com/25769591/142405719-ab332b80-63f3-4c17-8afb-430b99081e8f.png)
https://134.2.67.9/Authority/690570848
Link auf die markierte externe Ressource führt nicht zum gewünschten Ergebnis. Evt. ausschließen?

**Comment by socheres** [comment]
> GND: 035 ISNI/LOC/ORCID/VIAF/Wikidata: 024 Wikipedia: 670
> 
> BEACONs sind in Biographische Referenzen bislang technisch nicht möglich. Wo genau in den MARC-Daten steht denn der ADB/NDB-Verweis?

ADB/NDB ist nur in BEACONs enthalten. Kann man keine BEACONs in Biographische Referenzen integrieren? Welcher Lösungsansatz könnte es denn geben?

**Comment by mtrojan-ub** [comment]
Da es diese Anforderung nicht von Anfang an gab, müssten dafür beide Bereiche (Externe Ressourcen+Biografische Referenzen) nochmals komplett technisch überarbeitet werden, so dass zunächst die BEACON Abfrage per AJAX durchgeführt wird und dann basierend auf dem Ergebnis beide Teilbereiche nachträglich per JS in die Seite eingefügt werden...

**Comment by mtrojan-ub** [comment]
Nachdem dieser Issue im letzten FID-Meeting besprochen wurde, haben wir die Maschinerie erweitert.

Die betroffene BEACON-Datei wird nun in der Pipeline heruntergeladen und die Normdaten entsprechend gekennzeichnet.
"Deutsche Biographie" taucht nun auch unter "Biografische Referenzen" auf.
Als Nebenprodukt gibt es jetzt auch einen Eintrag für "Deutsche Biographie" in der Facette "Externe Referenzen".

=> ready for testing auf ptah

**Comment by mtrojan-ub** [comment]
Wie in FID-Runde besprochen: Im vorigen Kommentar war nicht die "Facette" gemeint, sondern der rechte Bereich der von Findbuch abgefragt wird.

**Comment by mtrojan-ub** [comment]
@socheres: Das kommt daher, weil uns die Findbuch API für diese Datensatz-ID nichts brauchbares zurück liefert.

Beispiel:
http://beacon.findbuch.de/seealso/pnd-aks/-archivportal/-commons@pd/-cultword/-heidi/-ixtheo/-kalliope/-mghopac/-pw_allmusic/-pw_discogs/-pw_eb/-pw_imslp/-pw_munzinger_pop/-relbib/-unibib_rub/?format=seealso&id=118547909

Beispiel für einen anderen Datensatz, bei dem es funktioniert (Martin Luther King):
http://beacon.findbuch.de/seealso/pnd-aks/-archivportal/-commons@pd/-cultword/-heidi/-ixtheo/-kalliope/-mghopac/-pw_allmusic/-pw_discogs/-pw_eb/-pw_imslp/-pw_munzinger_pop/-relbib/-unibib_rub/?format=seealso&id=118562215

**Comment by mtrojan-ub** [comment]
Wie besprochen, wir schließen, falls es bei anderem Datensatz wieder auftritt bitte neuen Issue aufmachen.
