### ISSUE TITLE
Autorenanzeige mit PPN

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#1749]
Statt nur der Autorennamen werden gerade auch die PPNs angezeigt. Das war bisher nicht so:

https://ixtheo.de/Search/Results?lookfor=Maeir%2C+Aren+M.&type=Author&filter%5B%5D=%7Eauthor_facet%3A%22Maeir%2C+Aren+M.+1958-%22&limit=20&botprotect=

![maeir](https://user-images.githubusercontent.com/17004223/137891535-a12257c1-9f32-4f89-9806-5b3464e33622.JPG)

**Comment by mtrojan-ub** [comment]
Ready for testing auf ptah
