### ISSUE TITLE
Anzeige der "Weiteren Schlagwörter" 

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#175]
Bitte einleitende "gnd" usw. aus der Anzeige entfernen
![weitere_sww](https://user-images.githubusercontent.com/17004223/35636130-7e18724c-06b0-11e8-8c96-9b3af560eff6.png)

**Comment by jriedl** [comment]
Ist auf ptah behoben.

**Comment by IxTheoKm** [comment]
Leider nur die Anzeige o.k. Manche Titel lassen sich aber nicht aufrufen:

![region](https://user-images.githubusercontent.com/17004223/35682352-b3535642-0760-11e8-9537-25e3deba2827.png)

![region2](https://user-images.githubusercontent.com/17004223/35682356-b80d09ee-0760-11e8-9634-906e26cbbe25.png)

**Comment by jriedl** [comment]
Auf ptah gefixed.

**Comment by IxTheoKm** [comment]
Funktioniert jetzt auf ptah, danke!
