### ISSUE TITLE
Anzeige Feld 772

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#1751]
Die Beschreibung "Enthält" ist für die Bezüge in Feld 772 nicht korrekt. Kann wie bei 770 "Bezug" verwendet werden? Die spezifischen einleitenden Wendungen werden durch $i angezeigt. 
Vgl. https://github.com/ubtue/tuefind/issues/423
Außerdem muss der zeitliche Bezug in $n mit angezeigt werden in der Form "Supplement zu: (-2019):"
(Rückmeldung des Herausgebers zur Anzeige der Zeitschrift).

Beispiel:
https://ixtheo.de/Record/1742737412

Die Zeitschrift "Tidsskrift for praktisk teologi" **_ist_** bis 2019 ein Supplement zu "Luthersk kirketidente". Sie enthält nicht das Supplement.

**772** 08 **$i** Supplement zu **$n** -2019$tLuthersk kirketidende$dOslo : Luther Forlag, 2010$hOnline-Ressource$w(DE-627)1742732844$w(DE-600)3048487-X

![772](https://user-images.githubusercontent.com/17004223/138040733-e53f2ce3-26c6-48f2-8b40-91ce3d9efe67.JPG)

**Comment by mtrojan-ub** [comment]
Wurde auf ptah angepasst, siehe: https://ptah.ub.uni-tuebingen.de/Record/1742737412
Unterfeld n wird nun ebenfalls angezeigt falls vorhanden, wobei es wohl in den Titeldaten aktuell erst 2 Datensätze gibt bei denen das Unterfeld 772n tatsächlich existiert (das genannte Beispiel, sowie 1529365481).
