### ISSUE TITLE
Personenseite Layout

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#1772]
Wenn auf der Personenseite kein Bild aus Wikipedia/Wikidata angezeigt wird (weil es dort nicht vorhanden ist), bleibt der dafür vorgesehene Platz rechts frei. Erst weiter unten kommen dann die Externen Ressourcen.

Das ist unschön. Könnte man die Externen Ressourcen hochziehen, wenn kein Foto zur Verfügung steht?

Issue ist nicht high prioritär und sollte die Freischaltung nicht verzögern

![Bildschirmfoto 2021-10-27 um 09 16 02](https://user-images.githubusercontent.com/14169098/139018039-0ff0b1a8-fd5c-4825-91f3-8d49562c86f8.png)

**Comment by mtrojan-ub** [comment]
Verhalten wurde verbessert => ready for testing

**Comment by thefass** [comment]
ok

**Comment by mtrojan-ub** [comment]
Kann der Issue dann also geschlossen werden?

**Comment by thefass** [comment]
ja, habe ich vergessn
