### ISSUE TITLE
Tagungsbeiträge - Anzeige des Titels

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#1781]
Beispiel: https://ptah.ub.uni-tuebingen.de/Authority/885108949

Der Titel wird so angezeigt:
Der Tempel als Ritueller Raum Veranstaltung Heidelberg 2015

Das ist schwer zu lesen, vor allem für nicht deutschsprachige Nutzer.

Die Infos kommen aus:
111 | 2 |   | \|a Der Tempel als Ritueller Raum    \|g Veranstaltung    \|d 2015    \|c Heidelberg

Bitte Titel so anzeigen:
Der Tempel als Ritueller Raum. Veranstaltung Heidelberg (2015)

**Comment by mtrojan-ub** [comment]
Tagungsbeitrag wurde umbenannt in `Tagungs(band)` und `Conference (Proceeding)`

**Comment by IxTheoKm** [comment]
Müsste nicht auch im Info-Text auf der Startseite die Bezeichnung angepasst werden?

![Personen](https://user-images.githubusercontent.com/17004223/141084265-4150a2a4-16a5-41e3-9c81-2aba043da8be.JPG)
