### ISSUE TITLE
VuFind Anzeige Volltext bei Online-Ressourcen

### ISSUE THREAD

**Issue by IxKo** [ubtue/tuefind#1782]
Für Volltext-Links im Pica-Feld 4950 (=URL zum Volltext) soll die Anzeige nicht mehr mit Unterfeld $3Volltext gesteuert werden, da dieses Unterfeld fakultativ ist und hier sowieso nur der Wert Volltext eingetragen werden kann.
Demnach kann es häufig vorkommen, dass das Unterfeld fehlt. Dennoch handelt es sich hier immer um einen Link zum Volltext.

Dies entspricht Marc 856 4 0 

Das Pica-Unterfeld $4 (= Marc $z) soll weiterhin zusätzlich ausgewertet werden, da hier die Lizenz-Information steht.

PS:
Ich hoffe die Labels stimmen so, sonst bitte ändern, danke!

**Comment by IxTheoKm** [comment]
Ich verstehe die Formatdokumentation so, dass in 4951 = Marc 856 41 in **$y** weitere Online-Ressourcen erfasst werden können (obwohl es dafür auch das Feld 4960 und 4961 gibt):
https://swbtools.bsz-bw.de/cgi-bin/k10plushelp.pl?cmd=kat&val=4951&katalog=Standard#$y
Inhaltsverzeichnis, Table of contents, Volltext, fulltext, Rezension, review, Verlagsangaben, Publisher description

Nur wenn es sich um einen Volltext handelt, wird $3Volltext und $5 erfasst.

Wenn man 4951 = Marc 856 41 ebenfalls auswertet - was ich richtig finde - muss aber $3Volltext herangezogen werden.

Bsp. mit $3Volltext:
PPN 1752741870, 1752740742, 1752740394, 1752740203, 1752739949, 1757174109, 1757173706 ...

Bsp. mit $3Inhaltsverzeichnis:
PPN 173619397X
**856 41**$uhttps://www.transcript-verlag.de/978-3-8376-5648-0/radikalislamische-youtube-propaganda/?number=978-3-8394-5648-4$xVerlag$yInhaltsverzeichnis

**Comment by thefass** [comment]
@IxKo Können Sie bitte testen?

**Comment by IxKo** [comment]
Es wird nun bei Online-Ressourcen, die keine Unterfelder $3Volltext $534 (Feld 4950) im VuFind-System "Volltext" angezeigt und zusätzlich wird die Lizenzinformation in Klammern dargestellt.
