### ISSUE TITLE
Normdatensuche: Sortierung nach Jahr aufsteigend / absteigend

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#1806]
Wie gestern mit @thefass im Meeting besprochen:
- Bei Personen: Geburtsjahr
- Bei Körperschaften / Tagungen: Jahr der Gründung / Tagung

**Comment by mtrojan-ub** [comment]
@thefass: Kann jetzt auf ptah getestet werden (Sortieren => "Neueste zuerst" bzw. "Älteste zuerst"). Dazu folgende Anmerkungen:

1) Die Bezeichnung habe ich verwendet, weil es dazu schon einen übersetzten Displaytext gab. Vielleicht ist das aber mißverständlich. Brauhen wir eine bessere Bezeichnung?
2) Es gibt verschiedene Fälle, in denen die Metadaten aus unserer Sicht unbrauchbar sind. Daher haben wir einen Mechanismus eingebaut der verschiedene Fälle erkennt und von der Sortierung ausnimmt oder anderweitig normalisiert. Anbei einige Beispiele. 

> 
> ID: 817501851:
> 548             |a 02.08.2919-  |4 datx  |w r  |i Exakte Lebensdaten
> 
> ID: 240079361
> 548             |a 19.05.7121-15.12.1771  |4 datx  |w r  |i Exakte Lebensdaten
> 
> weitere Beispiele (ohne ID):
> - 6.-7.Jhd : würde durch "-" geteilt, wird aber ignoriert, da nicht 0 oder 2 Punkte im Datum
> - 02.03.19681987 (andere Werte aber dieses Format): wird ignoriert, da Jahreszahl > 2099
> Hier ist die Prüfung nun: bei v-Jahren: nur bis 8000, bei Jahren ohne v-Bezeichnung: bis 2099
> 
> weitere Prüfungen:
> - 00 bei Tag oder Monat wird durch 01 ersetzt
> - XX. und xx. werden durch 01 ersetzt
> - ca. wird entfernt

**Comment by thefass** [comment]
Das ist erstmal so ok. Verbesserungn können wir nach User Feedback und Live Schaltung angehen
