### ISSUE TITLE
Alphabetische Sortierung in der Facette "Genre (Schlagwort)" - und anderen Facetten

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#181]
Gibt es eine Erklärung für diesen merkwürdigen "Einschub"?
![genre_alphabetisch_li](https://user-images.githubusercontent.com/17004223/35909143-f1c1c440-0bf2-11e8-9da8-e1c5019cc8ae.jpg)

**Comment by jriedl** [comment]
Für einen Teil der Facetten erfolgt die Übersetzung bereits auf der Solr-Seite, bei anderen werden die Vufind-seitigen Übersetzungsdateien verwendet. Deshalb durchlaufen die Facetten nach der Rückgabe der Werte durch Solr noch einmal eine Sortierung (auf Seitenbasis). Deshalb wurden die Werte an den Anfang dieser Seite sortiert.

**Comment by jriedl** [comment]
Die alphabetische Sortierung der Facetten auf der Solr-Seite ist fix: Sie folgt der sog. "natürlichen" Sortierung, das entspricht der "englischen" Sortierung, so dass Sonderzeichen an den Schluss sortiert werden., Es werden zunächst 500 Werte abgefragt, durch "mehr..." dann die nächsten 500 und so weiter. Vufind sortiert die Facetten jetzt noch einmal selber. Vor diesem Issue erfolgte das in Abhängigkeit von den Spracheinstellungen (also bei Auswahl der deutschen Sprache anhand der deutschen Sortierregeln". Das Problem ist nun, dass Vufind für die Sortierung nicht alle Facetten "sehen" kann, und so kam es zur Sortierung innerhalb der 500-Einträge-Grenze und zu dem ursprünglichen Ausreißer mit der "predigtsammlung". Um dies zu vermeiden, wird in VuFind jetzt die gleiche "natürliche" Sortierung zugrundegelegt wie in Solr, damit die Ergebnisse konsistent bleiben. Mir erscheint die Sortierung im gestrigen Beispiel auch plausibel.

**Comment by IxTheoKm** [comment]
Danke für die Erklärung! Damit ist auch das obige Beispiel (Sonderzeichen hinter "Zoologie") plausibel. Allerdings nicht die Reihenfolge "Cookbooks - **DV**D ... - **Da**nkrede". Sortierung von Großbuchstaben vor Kleinbuchstaben?

**Comment by jriedl** [comment]
Ja genau.

**Comment by IxTheoKm** [comment]
Danke, ist in die Hilfetext-Tabelle aufgenommen.
