### ISSUE TITLE
Normdatensuche: Einstellungen für Relevanz-Sortierung

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#1810]
... ist mir selbst beim Testen aufgefallen.

Beispiel: Wenn man nach "Martin Luther King" sucht, erhält man aktuell folgende Treffer:

![grafik](https://user-images.githubusercontent.com/26873381/140033751-0ab930f2-7982-4d95-a28d-16b67e168921.png)

D.h. es erscheinen verschiedene Körperschaften, Tagungen, der Vater, und dann erst an Stelle 6 der bekannte Bürgerrechtler.
Wie genau können / sollen wir das optimieren?

(man könnte z.B. die Anzahl der Titel die mit einem Normdatensatz verknüpft sind in ein Solr-Feld schreiben und als Sortierkriterium verwenden)

**Comment by thefass** [comment]
ja, gute Idee. Bitte einmal zum Testen umsetzen

**Comment by mtrojan-ub** [comment]
Zusammenhang mit #1840

**Comment by mtrojan-ub** [comment]
Nachdem wir die separate Sortierung nach "Anzahl Titel" eingeführt haben, habe ich nun die Feldprio für die herkömmliche Relevanz-Sortierung etwas angepasst (heading-Felder werden höher gewichtet).
