### ISSUE TITLE
"Publication Timeline" can contain non-integer values on the y axis

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#1821]
https://ptah.ub.uni-tuebingen.de/Authority/081707754

![grafik](https://user-images.githubusercontent.com/26873381/140091842-3be9543f-35da-484f-a93d-fc789db82c16.png)

**Comment by IxTheoKm** [comment]
Vgl. auch https://sobek.ub.uni-tuebingen.de/Authority/079562221

![Mugabe](https://user-images.githubusercontent.com/17004223/140277199-5f47b256-63a2-4067-ac32-a9fc98e49e1c.JPG)

**Comment by mtrojan-ub** [comment]
Ready for testing auf ptah+sobek

**Comment by thefass** [comment]
in beiden Testsystemen ok
