### ISSUE TITLE
Normdaten - Bug verbundene Autoren

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#1823]
das ist in Ordnung: alle drei Symbole sind da
https://www.ixtheo.de/Authority/080773184
![Bildschirmfoto 2021-11-03 um 19 17 34](https://user-images.githubusercontent.com/14169098/140169288-9d710ca2-5483-42ee-b289-b56504d2f2c7.png)

Wenn man auf "alle anzeigen klickt" dann fehlen das Ketten-Symbol für "Gemeinsame Titel mit dem Autor"
Dieser Fehler wurde eigentlich schon behoben.
![Bildschirmfoto 2021-11-03 um 19 20 09](https://user-images.githubusercontent.com/14169098/140169551-34560160-a402-479e-96e5-02e724750ec5.png)

Siehe: https://www.ixtheo.de/Author/Search?view=authorfacets&lookfor=Rahner%2C+Johanna+1962-&type=Author

**Comment by mtrojan-ub** [comment]
Ready for testing auf ptah, wobei sich der Link von der Personenseite aus geändert hat d.h. wenn man im oberen Beispiel den 2. Link klickt hat man noch das alte Verhalten, wenn man über die Personenseite kommt funktioniert es jetzt.

**Comment by thefass** [comment]
leider noch nicht ganz. 
https://ptah.ub.uni-tuebingen.de/Authority/080773184
In der Default Einstellung (20 Treffer) pro Seite alles ok. Sobald man aber die Treffer pro Seite erhöht, verschwinden die Ketten-Links wieder

![Bildschirmfoto 2021-11-04 um 16 40 25](https://user-images.githubusercontent.com/14169098/140364553-8eba7161-7187-42fc-846f-294b317eda64.png)
![Bildschirmfoto 2021-11-04 um 16 40 37](https://user-images.githubusercontent.com/14169098/140364790-d510eab8-8ee6-4c08-8717-44b9a9a2f0cf.png)

**Comment by thefass** [comment]
Auch wenn man weiterblättert auf Seite 2 fehlen die Kettenlinks

![Bildschirmfoto 2021-11-05 um 15 17 32](https://user-images.githubusercontent.com/14169098/140524856-e8c2c342-8dd9-4924-8208-8b95b99db0d2.png)

**Comment by thefass** [comment]
auf ptah ok
