### ISSUE TITLE
Normdaten: Out of Memory Problem bei Datensätzen mit vielen Verknüpften Titeln

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#1833]
Beispiel: Martin Luther
https://ptah.ub.uni-tuebingen.de/Authority/133813363

`Allowed memory size of 268435456 bytes exhausted (tried to allocate 138322816 bytes)`

**Comment by mtrojan-ub** [comment]
Ready for testing auf ptah

**Comment by thefass** [comment]
ok
