### ISSUE TITLE
Normdaten - falsche Zählung?

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#1837]

**Comment by thefass** [comment]
https://www.ixtheo.de/Authority/508490847
Das SW Brüdergemeine und Diakonisse soll jeweils zwei Treffer haben. Wenn man daruaf klickt, wird aber nur ein Treffer angezeigt
![Bildschirmfoto 2021-11-04 um 21 19 12](https://user-images.githubusercontent.com/14169098/140414030-ab122a4d-cdcf-4c19-a987-6d0e071443b0.png)

![Bildschirmfoto 2021-11-04 um 21 21 20](https://user-images.githubusercontent.com/14169098/140414125-4c837713-8623-437f-a470-f3fd44fa630e.png)

**Comment by thefass** [comment]
Scheint ein allgemeineres Problem zu sein
https://www.ixtheo.de/Authority/077404084

Das SW Christentum soll 85 Treffer haben, es werden dann aber nur 78 angeboten
![Bildschirmfoto 2021-11-04 um 21 25 06](https://user-images.githubusercontent.com/14169098/140414642-2a183dd0-bede-4b60-9485-c720b5de3695.png)

![Bildschirmfoto 2021-11-04 um 21 25 42](https://user-images.githubusercontent.com/14169098/140414708-550f1e5f-a552-4bb8-a239-7b27999fbdb5.png)

**Comment by mtrojan-ub** [comment]
Es gibt im ersten Beispiel tatsächlich nur 1 Titel mit dem Schlagwort "Brüdergemeine". Allerdings taucht das Schlagwort mehrmals im selben Solr-Feld auf und wird daher mehrfach gezählt. Wir kümmern uns drum.

**Comment by mtrojan-ub** [comment]
Ready for testing auf ptah

**Comment by thefass** [comment]
auf ptah  ist das ok
