### ISSUE TITLE
Normdaten SW

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#1838]
Bei Klick auf ein Schlagwort in der SW-Cloud geht im Browser ein neuer Tab auf. Nicht so beim Reiter "Alphabetisch" und beim Reiter "nach Häufigkeit".

Bitte das Verhalten vereinheitlichen wie beim Reiter "Cloud"

![Bildschirmfoto 2021-11-04 um 21 28 15](https://user-images.githubusercontent.com/14169098/140415068-55e6c9fd-e701-4b32-9777-74c961c06833.png)

**Comment by mtrojan-ub** [comment]
Eigentlich ist die Konvention die, dass nur dann ein neuer Tab aufgehen sollte, wenn der Link auf eine externe Webseite zeigt.

**Comment by thefass** [comment]
Ok, dann bleiben wir bei dieser Logik.
Dann bitte die Links im Reiter Cloud anpassen, so dass sie nicht in einem eigenen Tab aufgehen

**Comment by mtrojan-ub** [comment]
ready for testing auf ptah

**Comment by thefass** [comment]
auf ptha ok
