### ISSUE TITLE
Normdaten: Sortierung nach größter Anzahl an verknüpften Titeln

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#1840]
@thefass: Im Rahmen von #1833 kam uns die Idee, dass es auch sinnvoll wäre, wenn man das Suchergebnis nach Anzahl der meisten verknüpften Titel sortieren könnte (absteigend).

Hier mal ein kleiner Vorgeschmack:
![grafik](https://user-images.githubusercontent.com/26873381/140482219-5f880fd7-78fa-47f4-a23e-e55c7e6ad2f2.png)

Von daher wäre es meiner Ansicht nach sinnvoll, diese Sortierung für alle Benutzer zur Verfügung zu stellen.

**Comment by mtrojan-ub** [comment]
Auf ptah steht das jetzt testweise zur Verfügung. @thefass @relhei bitte mal ausprobieren!
(Die Sortierung heißt momentan "Anzahl Treffer", weil es dafür schon Übersetzungen gab. Evtl könnten wir es auch umbenennen. Oder wir ersetzen die Login hinter der Relevanz-Sortierung durch dieses Feld?)

Wir haben das so eingerichtet, dass die Anzahl der Titel für jede Instanz separat ermittelt wird. D.h. im IxTheo haben wir z.B. Martin Luther, Benedikt XVI, Johannes Paul II. ganz oben, aber in RelBib wären es Rudolf Steiner, Jan Assmann, Jacob Neusner usw.

(in KrimDok gibts die Sortierung in der Oberfläche auch schon, aber wir arbeiten noch an der Befüllung des Feldes.)

**Comment by thefass** [comment]
das ist brilliant.
Umso mehr als nicht klar ist was bei Relevanz eigentlich passiert. Relevanz würde ich das aber nicht nennen, da würde mir in einer wissenschaftlichen Bibliographie eher vorschweben, dass die Wissenschaftler als Erstes erscheinen. Aber darüber müssen wir nachdenken.

**Comment by relhei** [comment]
Prima, vielleicht so was wie "(Nach) Häufigkeit"? Vielen Dank für die Zutat :)

**Comment by mtrojan-ub** [comment]
`(Nach) Häufigkeit` finde ich nicht exakt genug. Es könnte ja auch die Häufigkeit von anderen Dingen als Titeln sein.
Wie wäre es mit `Anzahl Titel` bzw. `Title Count`?

**Comment by thefass** [comment]
ja, ich wäre einverstanden damit

**Comment by relhei** [comment]
Für mich auch in Ordnung.

**Comment by mtrojan-ub** [comment]
Wurde entsprechend umbenannt, siehe ptah
