### ISSUE TITLE
Normdaten: Text im Suchschlitz anpassen

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#1845]
Aktuell wird im Suchschlitz bei der Normdatensuche noch der Text angezeigt, der auch in der "normalen" RelBib-Suche verwendet wird. 
![grafik](https://user-images.githubusercontent.com/25769591/140709246-4280f2af-b2ef-4c95-b7a2-a40bcf932933.png)

![grafik](https://user-images.githubusercontent.com/25769591/140708494-df710c99-67fd-45e2-84e9-2785b2710df7.png)

Vorschläge für neuen Suchschlitztext:
Deutsch - Nach Normdaten suchen ODER Nach Person, Körperschaft, Konferenz suchen
Englisch - Search for authority data ODER Search for person, corporate, conference

Der erste Vorschlag ist kurz und bündig, aber vielleicht nicht so eingängig wie der zweite Vorschlag. Meinungen?

**Comment by mtrojan-ub** [comment]
Statt "Konferenz" sollte man auch hier "Tagung" verwenden, da es in der Facette auch so benannt ist.

**Comment by thefass** [comment]
der zweite Vorschlag ist eingängiger

**Comment by mtrojan-ub** [comment]
ready for testing

**Comment by relhei** [comment]
Sieht gut aus. Nur kleine Anmerkung: Kann man wirklich "corporate" zu Körperschaft sagen, oder müsste es nicht "corporate body" heißen? Ich hatte den Begriff aus der description zur Normdatensuche übernommen, war mir aber nicht ganz sicher..

**Comment by relhei** [comment]
Da keine Rückmeldung zur Frage kam: Ich schlage vor, dass im Hinweissatz "This page allows you to search for authors (persons, corporate, conferences, ...)" _corporate_ ersetzt wird durch _corporations_
Das würde auch der Bezeichnung im Reiter der Normdatensuche entsprechen.
Entsprechend müsste dann auch der Platzhaltertext angepasst werden (_corporation_ statt _corporate_)

**Comment by mtrojan-ub** [comment]
Können wir die kurze Form so drin lassen? Das ist besser für kleine Auflösungen, da sonst der halbe Satz fehlt.
"Search for person, corporate, conference" => "Search for person, corporation, conference"?

**Comment by relhei** [comment]
Mir nicht so ganz klar, an welcher Stelle welche Form jetzt bevorzugt ist. Einheitlich sollte es aber schon sein..
Lt. WB ist "corporate" ein Adjektiv, d.h. entweder "corporate body" oder "corporation" wäre die korrekte Übersetzung.

**Comment by mtrojan-ub** [comment]
... ist es nun auf ptah korrekt?

**Comment by relhei** [comment]
Ja, passt. Sollen wir den Hinweistext nun auch entsprechend anpassen? S.o.

**Comment by mtrojan-ub** [comment]
Ist jetzt ebenfalls angepasst, sorry! Gibt es noch weitere Stellen?

**Comment by relhei** [comment]
Ist mir nicht aufgefallen. Danke!
