### ISSUE TITLE
Einbindung virtuelle Tastatur

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#1849]
Bitte in das Subsystem Index Biblicus die virtuelle Tastatur für Griechisch und Hebräisch - analog zum IxTheo einbinden

![Bildschirmfoto 2021-11-08 um 12 33 30](https://user-images.githubusercontent.com/14169098/140734985-3fac5d0c-be23-4fcf-883d-65ea66103364.png)

**Comment by mtrojan-ub** [comment]
Ready for testing auf ptah

**Comment by thefass** [comment]
auf ptha ok
