### ISSUE TITLE
Neueste Titel (von) auf der Personenseite nicht anklickbar.

### ISSUE THREAD

**Issue by socheres** [ubtue/tuefind#1852]
Z.B. https://ixtheo.de/Authority/081135890

"Birte Platow: Religionspädagogik (Kompendien Praktische Theologie), Stuttgart: Verlag W. Kohlhammer, Stuttgart 2020, 132 S., ISBN: 978-3-17-034074-9, € 22,00"

**Comment by mtrojan-ub** [comment]
Ist aus meiner Sicht anklickbar bzw. ich kann das Problem nicht reproduzieren

**Comment by socheres** [comment]
Sorry, ich hatte Tampermonkey-Addon im Browser aktiviert gehabt, was den Fehler verursacht hat. Ich schliße das Issue.
