### ISSUE TITLE
Link auf Personenseite führt zu einem Fehler

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#1853]

**Comment by thefass** [comment]
https://ixtheo.de/Record/134905237

Wenn man auf das Symbol für die Person klickt, dann kommt folgende Fehlermeldung:
![Bildschirmfoto 2021-11-09 um 09 59 10](https://user-images.githubusercontent.com/14169098/140893896-4cb0bf01-f7b2-467e-b208-286a8514c9f2.png)

**Comment by thefass** [comment]
Seltsam: jetzt geht es wieder. 
Gut, dass ich den Screenshot gemacht habe. Könnt Ihr Euch das erklären?

**Comment by mtrojan-ub** [comment]
ID der Person ist: 079539378
Du hast den Fehler ca. um 10 Uhr gemeldet... um diesen Zeitraum findet sich folgender Log-Eintrag auf ub16 der diese ID betrifft:
`
2021-11-09T09:58:26+01:00 WARN (4): VuFind\Exception\RecordMissing : Record SolrAuth:079539378&hiddenFilters[]=first_indexed:[NOW-7DAY+TO+NOW]-id:LR* does not exist.`

Das sieht so aus, als ob im Hintergrund noch verschiedene Filter aktiv waren, z.B LR und gleichzeitig first_indexed (also Literary Remains und Neuzugänge). Mir ist allerdings schleierhaft, wieso sich das an dieser Stelle auswirken sollte. Wir werden mal versuchen das zu reproduzieren.

**Comment by mtrojan-ub** [comment]
@thefass: Da der Fehler nicht mehr auftritt habe ich den Issue geschlossen, falls er woanders nochmal auftritt kannst Du ihn ja gerne mit Beispiel wieder öffnen.

**Comment by thefass** [comment]
Danke!
