### ISSUE TITLE
WikidataProxyController Fehlermeldungen auf ub16

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#1859]
Im ub16 Log tauchen derzeit viele Fehlermeldungen nach folgendem Schema auf:
`[Wed Nov 10 10:33:23.164937 2021] [proxy_fcgi:error] [pid 1699227:tid 140167088154368] [client 134.2.66.63:44798] AH01071: Got error 'PHP message: PHP Notice:  Undefined property: stdClass::$entities in /usr/local/vufind/module/TueFind/src/TueFind/Controller/WikidataProxyController.php on line 112\nPHP message: PHP Warning:  Invalid argument supplied for foreach() in /usr/local/vufind/module/TueFind/src/TueFind/Controller/WikidataProxyController.php on line 112\n', referer: https://ixtheo.de/Authority/696401916`

**Comment by mtrojan-ub** [comment]
ready for testing auf ptah

**Comment by thefass** [comment]
@mtrojan-ub das testet Ihr ITler, oder?

**Comment by mtrojan-ub** [comment]
Ja das testen wir => ist ja auch im Frontend nicht testbar bzw. man sieht halt kein Bild aber die genaue Ursache (also ob interner Fehler oder kein Wikidata Eintrag gefunden usw.) kann von einem normalen User nicht nachvollzogen werden.

**Comment by mtrojan-ub** [comment]
Live server wurde am Montag aktualisiert, tritt nicht mehr auf
