### ISSUE TITLE
Suche Personen / Körperschaften auf Sobek

### ISSUE THREAD

**Issue by KStelzel** [ubtue/tuefind#1862]
1. optisch:
- festen Rahmen um beide Elemente in KrimDok ("Titel" + "Personen / Körperschaften")
2. Aktivierung:
- nicht auf "Titel" als Voreinstellung stellen
- wenn angewählt, nicht wieder autmatisch zurückspringen lassen
3. Piktogramme:
- sind nicht bei allen Titeln derselben Verfassenden (z.B. Katrin Höffler)
- Bezeichnung und Schreibweise: "verfasserin" und "VerfasserIn" - passen nicht immer zum Autor

gestestet: Kinzig, Kerner, Stelzel (bei mir nur wenige Angaben - GND-Eintrag unvollständig?)

PS: wir haben bei der Suchzeile zwei Lupen als Symbol für die Suche - die nur optische Lupe ist redundant und könnte entfernt werden (so wie bei IxTheo)

**Comment by mtrojan-ub** [comment]
Gehört zu #1546

**Comment by mtrojan-ub** [comment]
An 1) und 2) wird derzeit gearbeitet.

Bei 3) "Piktogramme" handelt es sich um ein Datenproblem:
https://sobek.ub.uni-tuebingen.de/Search/Results?lookfor=Katrin+Höffler&type=Author
![grafik](https://user-images.githubusercontent.com/26873381/141956596-97370d0c-7376-4653-9794-52ca3f8016ed.png)

Das liegt daran, dass in den Titeldaten nicht immer der vollständige Verweis (inkl. ID) auf den Autor hinterlegt ist.

https://sobek.ub.uni-tuebingen.de/Record/1770779264
![grafik](https://user-images.githubusercontent.com/26873381/141956851-41b745cc-f552-4cbe-940d-4f72d88d3984.png)

https://sobek.ub.uni-tuebingen.de/Record/1742008747
![grafik](https://user-images.githubusercontent.com/26873381/141957035-153d5052-550c-42af-9fa5-1eb6d6e3909f.png)

**Comment by mtrojan-ub** [comment]
Die Anpassungen zu 1) und 2) wurden nun auf sobek eingespielt.

Ready for testing!

**Comment by thefass** [comment]
ad 3) in den Fällen, in denen die Person innerhalb eines Katalogisates nicht mit der ID (PPN) des Normsatzes verknüpft ist, muss das nacherschlossen werden
