### ISSUE TITLE
Normdatensuche: Zweifache Angabe des Geburtsorts

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#1863]
Der Geburtsort wird aktuell an zwei Stellen angezeigt: In der obersten Zeile "Geboren:" (neben dem Geburtsjahr) sowie in der Zeile "Geografischer Bezug:" 
Beispiel:
![grafik](https://user-images.githubusercontent.com/25769591/141302616-44b0a24c-2469-4849-ab8b-08429b1440a4.png)
https://134.2.67.9/Authority/690570848?id=690570848&tab=0&lng=de

M.E. könnte eine der beiden Anzeigen entfernt werden. Meinungen? Ich wäre dafür, dass die Angabe des Geburtsorts unter "geografischer Bezug" bestehen bleibt.

**Comment by IxTheoKm** [comment]
Die Kurzliste müsste dabei wohl auch berücksichtigt werden. Dort ist die Angabe "1981, Gelsenkirchen" berücksichtigt.
Im Grunde sind hier die Lebensdaten gedoppelt:
![weiss](https://user-images.githubusercontent.com/17004223/141319803-8d0ce94e-2064-41a6-af9a-d30953cf03e5.JPG)

**Comment by mtrojan-ub** [comment]
Kann so bleiben, wie in FID-Runde besprochen
