### ISSUE TITLE
Personenseite: Ausschluss der Formschlagwörter aus der Word-Cloud

### ISSUE THREAD

**Issue by AleAprile** [ubtue/tuefind#1868]
Hiermit möchte ich nur den Beschluss unseres letzten IT-Treffens dokumentieren. Wir haben nämlich entschieden, dass  - sofern möglich - die Formschlagwörter aus dem PICA-Feld 1131 nicht mehr dazu beitragen sollten, die Word-Cloud zu generieren. Das hat den klaren Vorteil, dass diese dadurch eine reine thematische Wortwolke wird. @Gazeller

**Comment by AleAprile** [comment]
655

**Comment by mtrojan-ub** [comment]
Dazu wurde schon etwas vorbereitet / Änderung ist auf ptah. Sieht aber so aus, als ob nun einige Einträge fehlen (insb. 689). Wir schauen es uns nochmal an.

**Comment by mtrojan-ub** [comment]
@andreas-ub, hier ein Beispiel:

Dieser Normdatensatz:
https://ptah.ub.uni-tuebingen.de/Authority/1010646206

Ist z.B. mit diesem Titel verknüpft:
https://ptah.ub.uni-tuebingen.de/Record/279994826

Dieser Enthält als Schlagwort in 689 u.A. "Palästinensische Autonomiegebiete" / "Lebensbedingungen", was in der Cloud nicht vorkommt. Ich nehme an, obwohl es sich eigentlich um eine Kette handelt wäre es wohl für die Cloud gut beides separat bzw. flach /gleichberechtigt aufzunehmen.

**Comment by mtrojan-ub** [comment]
"Palästinensische Autonomiegebiete" taucht nun in der Liste auf, allerdings nicht in der Word Cloud (vermutlich gibt es sehr viele Schlagwörter mit niedriger Häufigkeit, irgendwann wird dann abgeschnitten damit die Cloud noch darstellbar bleibt).

Allerdings ist mir noch aufgefallen, dass an einer Stelle z.B. "Bergpredigt Bergpredigt" auftaucht, vermutlich aus diesem Titel:
https://ptah.ub.uni-tuebingen.de/Record/1640309861

@andreas-ub, lässt sich das noch verbessern?

**Comment by mtrojan-ub** [comment]
Der Sonderfall "Bergpredigt Bergpredigt" hängt weniger mit der Cloud-Logik zusammen, sondern eher mit der Problematik in folgendem Issue: #1202. 

Abgesehen von dieser separaten Problematik ist daher dieser Issue aus meiner Sicht "ready for testing".

**Comment by AleAprile** [comment]
Ich habe diese Anpassung ausführlich getestet und es sieht m. E. sehr gut aus. Jetzt werden in der Wortwolke ausschließlich Themenschlagwörter angezeigt und das vereinfacht erheblich die Nutzung dieser jüngst entwickelten Funkionalität. Die Formschlagwörter waren überhaupt nicht sachdienlich.  Vielen Dank für diese Änderungen! Von mir aus kann dieses Issue nun geschlossen werden.
