### ISSUE TITLE
BEACON - Brockhaus

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#1870]
der Brockhaus link sollte nicht unter Archivmaterial erscheinen
https://www.ixtheo.de/Authority/133773221?id=133773221&tab=0&lng=de

![Bildschirmfoto 2021-11-16 um 22 04 44](https://user-images.githubusercontent.com/14169098/142065544-46cca447-021e-4f70-846c-c24151b3d8b4.png)

**Comment by mtrojan-ub** [comment]
Das ist bereits im Rahmen von #1851 ready for testing auf ptah.

**Comment by mtrojan-ub** [comment]
@thefass: Für den genannten Datensatz funktioniert es ja. Kann der Issue damit geschlossen werden?
