### ISSUE TITLE
Überflüssige Anzeige von "verfasserin" in Trefferliste

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#1875]
In den Trefferlisten gibt es bei einigen Titeln die Angabe "verfasserin / VerfasserIn" hinter dem Namen eines Autors bzw. einer Autorin. Diese Doppelung betrifft sowohl die deutsche als auch die englische Oberfläche.
Beispiele:
![grafik](https://user-images.githubusercontent.com/25769591/142281561-300dd0b9-b201-4d3b-9a88-f22c20b58ced.png)
https://www.relbib.de/Search/Results?lookfor=&type=AllFields&limit=50&sort=last_indexed%20desc%2Crelevance%2C%20year%20desc&botprotect=&lng=de

![grafik](https://user-images.githubusercontent.com/25769591/142281319-e3acad05-e67d-43a6-89ad-2db05563ab0b.png)
https://www.relbib.de/Search/Results?lookfor=&type=AllFields&limit=50&sort=last_indexed+desc%2Crelevance%2C+year+desc&botprotect=

Bitte entdoppeln bzw. "verfasserin" entfernen.

**Comment by mtrojan-ub** [comment]
ggf. Zusammenhang mit #625

**Comment by relhei** [comment]
Stimmt, dazu gab es auch im Oktober ein Issue (Doppelbezeichnung von Autorenrollen #1724), was mit Verweis auf #625 geschlossen wurde. Mir kam die Thematik schon bekannt vor...
Da scheint es aber noch keine Lösung zu geben?
Soll ich hier schließen?

**Comment by mtrojan-ub** [comment]
Kann für den Moment gerne offen bleiben, da das Problem nach wie vor besteht und im anderen Issue mehrere unterschiedlichen Themen vermischt werden.

**Comment by ja-bre** [comment]
das Thema wurde gerade auch nochmal in der Runde der Theologie-Fachreferent*innen angesprochen; ich setze den Issue nach Absprache mit den Kolleg*innen auf high priority

**Comment by mtrojan-ub** [comment]
Wir arbeiten bereits daran, allerdings muss die Anpassung erst auf ptah getestet werden. Da wir kurz vor dem Update auf 7.1 stehen, wird eine Lösung dafür also voraussichtlich erst Anfang Dezember zusammen mit der 7.1er-Version live gehen können.

**Comment by mtrojan-ub** [comment]
Die Testserver wurden heute auf 7.1 migriert. Außerdem haben wir heute eine Änderung auf ptah eingespielt. Die Thematik kann ab dem nächsten Import (=morgen früh) auf ptah getestet werden.

**Comment by relhei** [comment]
Sieht jetzt gut aus. Danke!

**Comment by relhei** [comment]
Leider gibt es wieder ein Problem mit der Anzeige, siehe hier:
![grafik](https://user-images.githubusercontent.com/25769591/147113811-d7c42b39-94e6-4ed2-8ea2-3e60a85eda56.png)
https://www.relbib.de/Search/Results?lookfor=superior_ppn%3A787023558&type=AllFields&sort=year+desc%2C+volume_sort+desc%2C+issue_sort+desc%2C+start_page+asc%2C+first_indexed+desc&botprotect=
Allerdings scheint diesmal noch mehr im Argen zu liegen, weil bei der author-Bezeichnung im 2. Treffer noch die ORCID eingebaut wurde. Zudem zeigt der Blick auf den 3. Treffer, dass anscheinend die Doppelbezeichnung nicht immer auftritt?
Bitte prüfen.

**Comment by andreas-ub** [comment]
Auf ptah sieht es auf den ersten Blick gut aus.
Am 12.1. werden vorr. die Live-Server aktualisiert, ggf. tritt danach das Problem auf relbib.de nicht mehr auf.

https://ptah.ub.uni-tuebingen.de:4448/Search/Results?lookfor=superior_ppn%3A787023558&type=AllFields&sort=year%20desc%2C%20volume_sort%20desc%2C%20issue_sort%20desc%2C%20start_page%20asc%2C%20first_indexed%20desc&botprotect=

**Comment by IxTheoKm** [comment]
Die Doppelung tritt weiterhin auf IxTheo ptah auf:
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=first_indexed%3A%5B2022-01-12T00%5C%3A00%5C%3A00Z+TO+NOW%5D&type=AllFields&limit=20&botprotect=

Treffer 11:
https://ptah.ub.uni-tuebingen.de/Record/1785408828#details
"InterviewerIn" gehört zur zweiten Person in Feld 700

![I1875](https://user-images.githubusercontent.com/17004223/149097961-6f1a3e9a-64df-40e0-a061-ba4180207711.JPG)

**Comment by andreas-ub** [comment]
>> Am 12.1. werden vorr. die Live-Server aktualisiert, (...).
Für die korrekte Darstellung ist zudem ein Import mit akt. Softwarestand erforderlich, daher sollte es ab morgen ok sein (erfolgreicher Pipeline-Durchlauf vorausgesetzt).

**Comment by mtrojan-ub** [comment]
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=ids%3A1785408828

Ist ja auch auf ptah noch falsch, von daher müssen wir's uns nochmal anschauen.

**Comment by andreas-ub** [comment]
>> Treffer 11: (...)

hier passte die Anzahl der ermittelten Autorenrollen mit den ermittelten Autoren nicht zusammen, deswegen wurde das Mapping falsch angezeigt. Es ist eine Codeanpassung erfolgt, ptah wurde gestern aktualisiert und seit dem letzten Import sollte die Anzeige nun passen.

**Comment by IxTheoKm** [comment]
Auf ptah/IxTheo sieht es jetzt okay aus.

**Comment by relhei** [comment]
RelBib auch ok. Danke!
