### ISSUE TITLE
Normdaten: Ausschluss RVK

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#1890]
Bitte die RVK Klassen aus der Schlagwortwolke ausschließen
https://krimdok.uni-tuebingen.de/Authority/060055715

![Bildschirmfoto 2021-11-22 um 19 10 37](https://user-images.githubusercontent.com/14169098/142913401-34954f6d-9586-4941-bb4d-0e92d6467af7.png)

**Comment by thefass** [comment]
ebenso bkl ausschließne
https://krimdok.uni-tuebingen.de/Record/1013965086#details

![Bildschirmfoto 2021-11-22 um 19 13 09](https://user-images.githubusercontent.com/14169098/142913803-ebfaa64b-f6c5-4ed6-b411-e680f39c6d4f.png)

**Comment by mtrojan-ub** [comment]
Hierfür müssen wir erst ein passendes Solr-Feld anlegen. Aktuell landet alles im selben Topf und lässt sich später bei Generierung der Tag Cloud nicht mehr unterscheiden.

**Comment by andreas-ub** [comment]
Relevant für die Schlagwortwolke ist u.a. das 936a-Subfeld.

Krimdok-Authority: https://krimdok.uni-tuebingen.de/Authority/060055715
Beispiel-Titel: https://krimdok.uni-tuebingen.de/Record/477540589#details

Folgende Felder werden berücksichtigt: 600:610:611:630:650:653:656:689a:936a (ohne 0-Subfields), d.h. dass hier das 084-Feld nicht für die Topics bzw. Schlagwortwolke berücksichtigt wird.

Für eine Änderung der Schlagwortwolke gibt es nun mehrere Möglichkeiten:
- generell 936a von den zu analysierenden Feldern entfernen.
- 936a nicht berücksichtigen, falls es ein 0-Subfield gibt, das "rvk" enthält.
- 936a nicht berücksichtigen, falls Indikator 1 = r und Inidikator 2 = v ist.

Welche dieser wäre Möglichkeiten am besten geeignet?


Bsp. 936-Feld aus obigem Beispiel-Titel
936 | r | v | \|a MR 5100    \|b Allgemeine Darstellungen (Reader in modern Theory)    \|k Soziologie    \|k Sozialwissenschaftliche Theorien und Methoden    \|k Jüngere soziologische Theorie    \|k Allgemeine Darstellungen (Reader in modern Theory)    \|0 (DE-627)1271305135    \|0 (DE-625)rvk/123510:    \|0 (DE-576)201305135
-- | -- | -- | --

**Comment by andreas-ub** [comment]
bei bkl gibt es nur Möglichkeit 1 und 3


936 | b | k | \|a 71.02    \|j Theorie der Soziologie    \|0 (DE-627)106416189
-- | -- | -- | --

**Comment by mtrojan-ub** [comment]
Steht im Zusammenhang mit: #1868

**Comment by mtrojan-ub** [comment]
Aktuell wird auf sobek bei diesem Datensatz gar keine Cloud mehr angezeigt, ich kümmere mich drum.

**Comment by mtrojan-ub** [comment]
Die Cloud wird nun wieder angezeigt. Durch die Umstellung auf das neue topic_cloud Solr Feld sollten jetzt auch keine RVK Klassen mehr auftauchen.

Ready for testing auf sobek

**Comment by thefass** [comment]
rvk und bkl sind wie erwünscht raus.

**Comment by thefass** [comment]
Noch vorhanden sind "gnd" und "DE-289". Das sind Quellenangaben, die nicht in der Schlagwortwolke auftauchen sollen
Bitte entfernen
https://krimdok.uni-tuebingen.de/Authority/060055715

![Bildschirmfoto 2022-02-22 um 11 58 30](https://user-images.githubusercontent.com/14169098/155118976-32263c8f-c1c2-443e-bb90-6e4ff1135694.png)
****
DE-289
https://krimdok.uni-tuebingen.de/Record/022734635#details

650 |   | 0 | \|a Economics    \|2 DE-289
-- | -- | -- | --

****
gnd
https://krimdok.uni-tuebingen.de/Record/1697812430#details

650 | 0 | 7 | \|0 (DE-588)4079351-5    \|0 (DE-627)10448361X    \|0 (DE-576)20921225X    \|a Wirtschaftstheorie    \|2 gnd
-- | -- | -- | --

**Comment by andreas-ub** [comment]
Änderung auf sobek aktiv -> ready for testing

**Comment by thefass** [comment]
auf Sobek ok
