### ISSUE TITLE
Normdaten zwei Reiter

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#1891]
Bitte wie in Ixtheo / Relbib auch die Namesformen mit auslesen
![Bildschirmfoto 2021-11-22 um 19 23 14](https://user-images.githubusercontent.com/14169098/142915031-449f4d9b-d37f-49e4-88f2-a710d78b2796.png)

**Comment by mtrojan-ub** [comment]
War relativ schnell machbar, da der Tab nur per Konfiguration aktiviert werden musste.

=> ready for testing auf sobek

**Comment by thefass** [comment]
ok
