### ISSUE TITLE
Normdaten Wikipedia

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#1892]
Die Wikipedia Links kommen noch nicht
Siehe GDN 118629743
https://de.wikipedia.org/wiki/Max_Weber

https://krimdok.uni-tuebingen.de/Authority/060055715

**Comment by mtrojan-ub** [comment]
Im Beispiel taucht der Wikipedia-Link rechts unter "Externe Ressourcen" auf (über Findbuch). Im Bereich "Biografische Referenzen" werden nur Links angezeigt, die direkt in den MARC-Daten vorhanden sind.

"Integration von Externen Ressourcen in Biografischen Referenzen" => ist momentan nicht möglich, siehe auch #1708

**Comment by mtrojan-ub** [comment]
Es scheint sich hier um einen älteren Issue zu handeln. Der Wikipedia-Link taucht zwischenzeitlich auch im Bereich "Biografische Referenzen" auf, das gilt auch für das genannte Beispiel.

@thefass: Kann der Issue geschlossen werden?

**Comment by thefass** [comment]
ja
