### ISSUE TITLE
Normdaten + Archivmaterialien

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#1893]
Wir sollten analog zu den anderen auch Kalliope und Archivportal-D einbinden

@KStelzel spricht etwas dagegen?

**Comment by KStelzel** [comment]
Soweit ich das beurteilen kann, spricht nichts dagegen. Aber mir fehlen noch Informationen dazu. Können wir das in der nächsten IT-FIDs-Sitzung besprechen?

**Comment by thefass** [comment]
ok
