### ISSUE TITLE
bug bei Keywordchainsearch

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#191]
https://ixtheo-test.de/Keywordchainsearch/Results?lookfor=K%C3%B6nigsnovelle
Wenn man auf Datensätze klickt, kommt kein Ergebnis:

![bildschirmfoto 2018-02-14 um 16 27 40](https://user-images.githubusercontent.com/14169098/36212371-0ebd98e2-11a4-11e8-8245-4675b8ee9391.png)

Es sind aber Datensätze mit den beiden SW vorhanden:
https://ixtheo-test.de/Record/116549475
https://ixtheo-test.de/Record/031703135

**Comment by IxTheoKm** [comment]
Das Schlagwort lautet eigentlich |a Ägypten  |9 g:Altertum.
Die Anzeige ist nicht korrekt. Siehe auch #151. Das betrifft zwar die Facette, aber ist das evtl. derselbe Fehler?

**Comment by jriedl** [comment]
Auf ptah behoben

**Comment by thefass** [comment]
auf ptah in Ordnung
