### ISSUE TITLE
sehr merkwürdige Anzeige von "weitere Versionen"

### ISSUE THREAD

**Issue by AleAprile** [ubtue/tuefind#1916]
Wenn der Tab "Weitere Versionen" von https://ptah.ub.uni-tuebingen.de/Record/787578185 angeklickt wird, bekommt eine sehr merkwürdige Anzeige, siehe:
![Bild 29 11 21 um 14 01](https://user-images.githubusercontent.com/41292389/143873912-c0c96f88-ecbe-49d4-aaa8-89f593c2abd3.jpg)

Hängt das mit dem "Record Versions (FRBR)" zusammen?

**Comment by mtrojan-ub** [comment]
Das ist sehr gut möglich!

@LysogorAndGmail, could you please have a look?

**Comment by mtrojan-ub** [comment]
Problem ist behoben, ready for testing auf ptah+sobek!

**Comment by AleAprile** [comment]
ja, jetzt funktioniert es. Vielen Dank! In diesem Zusammenhang frage ich mich allerdings, ob diese neue Funktion nicht eine ( definitiv bessere) Darstellung von Records ist, die ohnehin unter "Parallele Ausgabe" anzeigt werden. Ferner frage ich mich, ob wie beide aktiv haben sollen/möchten. Diese Frage geht sicherlich über die rein technische Aspekten hinaus und soll vielleicht in der großen Runde besprochen werden. Oder?

**Comment by mtrojan-ub** [comment]
Grundsätzlich können wir das gerne in größerer Runde besprechen. Da die nächste größere Runde aber erst am 14.12. statt finden wird und wir die Version 7.1 am 7./8.12. live schalten wollen stellt sich die Frage, ob wir vorab noch etwas verbessern können bzw. ob wir das Feature für die Liveschaltung deaktivieren und dann erst zu einem späteren Zeitpunkt nachziehen.

**Comment by AleAprile** [comment]
Ja, der zeitliche Aspekt ist nachvollziehbar. Soweit ich sehen kann, funktioniert dieses Feature mittlerweile gut. Daher gibt es aus meiner Warte keinen weiteren Verbesserungsbedarf. @thefass und @socheres wollten es eigentlich noch testen. Vielleicht haben sie eventuell Änderungswünsche. 

Ich sehe, wie gesagt, da nur eine gewisse Ähnlichkeiten mit der anderen bereits vorhandenen Funktionalität. Das steht aber aus meiner Sicht einer Freischaltung technisch nichts im Wege.

**Comment by relhei** [comment]
> 

Wenn ich es richtig verstanden habe, funktioniert die Anzeige von "Parallele Ausgabe" etwas anders, nämlich basierend auf der Verknüpfung der PPN im Katalogisat. Diese Verknüpfung im K10plus liegt nicht immer vor. Und z. B. verschiedene Auflagen sind m. W. nicht verknüpft. 

Noch eine Frage dazu: Die neue Funktionalität "verschiedene Versionen" habe ich bisher nicht bei Zeitschriften gesehen. Ist das allgemein so oder nur zufällig aufgrund der Auswahl der Testbeispiele? Falls ersteres der Fall ist, wäre die Anzeige "Parallele Ausgabe" defintiv nicht redundant.

**Comment by mtrojan-ub** [comment]
Das liegt vermutlich eher an den Testdaten. Das verwendete Verfahren ist für alle Datensätze gleich und wird nicht gezielt für Zeitschriften übersprungen. Die Heuristik zur Ermittlung zusammenhängender Versionen basiert lediglich auf den Autor- und Titel-Feldern. Hier nochmal die Infos zum Standard-Verfahren:
https://vufind.org/wiki/configuration:record_versions

**Comment by mtrojan-ub** [comment]
Wird geschlossen, wie in FID-Runde besprochen
