### ISSUE TITLE
Externe Ressourcen (Personenseite): Verlinkung zur National Library of Israel

### ISSUE THREAD

**Issue by AleAprile** [ubtue/tuefind#1917]
Sowohl auf Ptah als auch auf dem Produktivsystem funktioniert die Verlinkung zur National Library of Israel nicht. Vermutlich liegt es nicht an uns, sondern an dem Service der Israelischen Nationalbibliothek, oder?

Siehe: https://ixtheo.de/Authority/134353447 und https://ptah.ub.uni-tuebingen.de/Authority/134353447

**Comment by mtrojan-ub** [comment]
Wenn ich z.B. im ersten Beispiel folgenden Link benutze:
http://uli.nli.org.il/F/?func=direct&local_base=nlx10&doc_number=000246539

Dann erscheint im Browser der HTTP Fehlercode `503 - Service Temporarily Unavailable`.

Das bedeutet ja nicht, dass die URL falsch ist, sondern dass z.B. gerade auf deren Seite Wartungsarbeiten durchgeführt werden und der Dienst bald wieder zur Verfügung steht.

**Comment by AleAprile** [comment]
ok, danke für Deine Rückmeldung - Dann ist die Sache klar. Soll dieses Issues offen bleiben, bis der Service wieder aktiv ist, oder kann geschlossen werden? Was denkst Du?

**Comment by mtrojan-ub** [comment]
Da 503 Fehler im Normalfall nur Kurzzeitig auftreten, hatte ich gehofft, dass sich das Problem bis heute von selbst erledigt, dann hätten wir es heute sowieso schließen können. Das ist aber leider nicht der Fall.

Da wir hier intern nichts aktiv tun können, würde ich dazu tendieren dass wir den Issue schließen, wobei Du natürlich gerne den Anbieter anschreiben kannst. Ist das OK aus Deiner Sicht?

**Comment by socheres** [comment]
Die BEACON stammen wahrscheinlich von Drittanbieter und nicht von National Library of Israel

**Comment by AleAprile** [comment]
Egal woher die Links kommen,  sie werden jeden Tag interessanter. Funktionieren sie zwar wieder, aber fuhren zu einer Anmeldeseite. Kurzum: Richtig weiterführend sind sie definitiv nicht. Wenn wir bei der Problembehebung weniger Handlungsspielraum haben, wäre ich für einen Ausschluss dieser Verlinkung.

**Comment by mtrojan-ub** [comment]
@socheres: Kannst Du mir bitte nochmal sagen wie die zum Namen passende auszuschließende ID für die API ermittelt? (ich weiß noch dass man das irgendwo nachschauen kann aber finde die URL leider nicht mehr), danke!

**Comment by mtrojan-ub** [comment]
Habe den Link zur Ermittlung der API ID wieder gefunden:
https://beacon.findbuch.de/status/pnd-aks.txt

Allerdings konnte ich darin das Kürzel für die National Library of Israel nicht finden...


Dafür sieht es in der Zwischenzeit so aus, als ob die Links wieder funktionieren, Beispiel:

https://ixtheo.de/Authority/134353447
http://uli.nli.org.il/F/?func=direct&local_base=nlx10&doc_number=000246539

**Comment by socheres** [comment]
Das Auffinden von Kürzel ist etwas knifflig, da nicht alle Kürzel so in der pnd-ask.txt direkt gefunden werden können. Außerdem zeigt dieses Beispiel gut, dass man eine Ressource nicht vorschnell ausschließen sollte; es sei denn, sie ist inhaltlich nicht relevant.

**Comment by mtrojan-ub** [comment]
Link funktioniert wieder, Issue wird geschlossen (wie in FID-Runde besprochen)
