### ISSUE TITLE
Zeitsuche Fehler bei Datum

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#1919]
Die Suche nach einem konkreten Datum (20.08.1901) verursacht einen Fehler:

https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=20.08.1901&type=TimeRangeBBox&limit=20&botprotect=

![Bildschirmfoto 2021-11-30 um 12 25 50](https://user-images.githubusercontent.com/14169098/144039102-df253c33-1e93-4320-a5e2-04c724285d9d.png)

**Comment by mtrojan-ub** [comment]
Das hätte aber vor der Änderung laut #1587 (also mit der alten Zeitbereichssuche) auch nicht funktioniert, richtig?

Der Eingabewert wird gegen verschiedene Schemata normalisiert und aus einem Einzelwert wird ein Zeitbereich gebildet. Da das Datum selbst kein Bereich ist schlägt die Normalisierung momentan fehl.

Gültige Werte wären z.B.:
`20.08.1901-` (ab diesem Datum)
`-20.08.1901` (vor diesem Datum)
`20.08.1901-20.08.1901` (exakt an diesem Datum)

Falls man allerdings ein Jahr eingibt, dann wird das schon automatisch normalisiert.
Z.B. wird aus der Eingabe `1901` dann so etwas wie `01.01.1901-31.12.1901`.
Sollen wir diesen Fall so hinzufügen, dass aus der Eingabe `20.08.1901` die Range `20.08.1901-20.08.1901` wird?
Was ist mit anderen Datumsformaten für unsere internationalen Benutzer, z.B. `1901-08-20`?

**Comment by thefass** [comment]
> Sollen wir diesen Fall so hinzufügen, dass aus der Eingabe `20.08.1901` die Range `20.08.1901-20.08.1901` wird?

Ja, bitte

> Was ist mit anderen Datumsformaten für unsere internationalen Benutzer, z.B. `1901-08-20`?

Bitte auch hinzufügen, so dass die Nutzer die beiden Formen eingeben können 20.08.1901 oder 1901-08-20

**Comment by mtrojan-ub** [comment]
@andreas-ub, kannst Du Dir das bitte bei Gelegenheit anschauen? Siehe RangeUtil::ConvertTextToTimeRange().

**Comment by andreas-ub** [comment]
dies wurde so erweitert, dass die beiden Datumswerte (ohne Bereiche) akzeptiert werden:
dd.mm.yyyy und yyyy-mm-dd.
Diese Erweiterung gilt nicht für v.Chr.
(ready for testing)

**Comment by thefass** [comment]
ok
