### ISSUE TITLE
Fehlende Aktualisierungen in KrimDok?

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#192]
Aufgefallen über URL-Probleme im FullTextCache, z.B. für PPN [000166847](https://krimdok.uni-tuebingen.de/Record/000166847#details)

Auf KrimDok gibt's in 856u einen Hyperlink der ins Leere geht (bzw. auf tocs.ulb.tu-darmstadt.de umgeleitet wird, was nicht erreichbar ist)
http://www.ulb.tu-darmstadt.de/tocs/27260402.pdf

Laut 005 in KrimDok erfolgte die letzte Änderung am Datensatz im Oktober 2016.
Schlägt man die PPN im SWB nach, so ist die URL dort nicht aufzufinden... allerdings verweist dort die letzte Änderung auf November 2017!

Wurde die URL im SWB evtl bereits korrigiert (oder entfernt) und das Update kam nicht in KrimDok an?

**Comment by mtrojan-ub** [comment]
Eine Prüfung auf sobek hat ergeben dass wir den Datensatz zuletzt mit dem Sonderabzug vom 5.5.17 erhalten haben, Wir werden dazu das BSZ kontaktieren.

**Comment by mtrojan-ub** [comment]
Das Problem umfasst derzeit 761 Datensätze. Das BSZ hat wohl die URLs der TU Darmstadt komplett entfernt. Wir werden voraussichtlich Ende dieser Woche Aktualisierungen erhalten.

**Comment by mtrojan-ub** [comment]
542 Datensätze enthalten wohl immer noch die alten URLs. Wir haben dazu erneut eine Anfrage ans BSZ geschrieben.

**Comment by mtrojan-ub** [comment]
Der Fehler lag diesmal bei uns, es gab Probleme beim Einspielen der Differenzabzüge. Ist jetzt auf sobek behoben.

**Comment by KStelzel** [comment]
Super!
