### ISSUE TITLE
Button "Abschicken" auf englischer Seite

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#1921]
Auf der Profilseite im Nutzerkonto gibt es auf der englischen Seite noch einen Button mit deutscher Beschriftung "Abschicken".
Bitte durch "Submit" ersetzen.
![grafik](https://user-images.githubusercontent.com/25769591/144047538-db8cfdad-9ec9-48bb-a089-b08aa255c4f8.png)

**Comment by mtrojan-ub** [comment]
ready for testing auf ptah

**Comment by relhei** [comment]
Passt. "Save" und "Speichern" sind natürlich besser ;) Danke!
