### ISSUE TITLE
Neuer Text für Alerting-Service

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#1925]
Wenn man eine Zeitschrift / Reihe / Paket für den Alerting-Service abonniert, gibt es derzeit ein Pop-up-Fenster mit diesem Text, sowohl auf der deutschen als auch der englischen Seite:
![grafik](https://user-images.githubusercontent.com/25769591/144222296-44c96b96-e816-4d7c-b28c-18eb31a7b09f.png)

Für die englische Seite bitte den Text in der Übersetzung anzeigen. Es wurden auch für die deutsche Fassung Anpassungen vorgenommen, daher hier beide Textvorschläge neu:

Deutsch (neu):
Mit dem Alerting-Service bleiben Sie über neu erschienene Aufsätze aus Zeitschriften und neu erschienene Bände in Reihen informiert.
Um diesen Titel oder dieses Zeitschriftenpaket für den Alerting-Service auszuwählen, klicken Sie auf den Button "Abonnieren".

Englisch (neu):
The alerting service keeps you informed about newly published articles from journals and newly published volumes in series.
To select this title or journal bundle for the alerting service, click on the button "Subscribe".

**Comment by mtrojan-ub** [comment]
Es gibt bereits ein englisches Template, allerdings kann ich nachvollziehen dass im Englischen trotzdem der deutsche Text angezeigt wird. Ich werde mich also auf Fehlersuche begeben und gleichzeitig den Text ändern.

**Comment by mtrojan-ub** [comment]
ready for testing auf ptah

**Comment by relhei** [comment]
Passt. Danke!
