### ISSUE TITLE
RelBib: unerwünschter Sprung von Normdatensuche in einfache Suche

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#1926]
Wenn man in RelBib in der Normdatensuche einen Treffer aufgerufen hat und dann wieder eine neue Normdatensuche in dem noch aktiven Reiter "Personen / Körperschaften" durchführen möchte, springt die Suche automatisch auf den "RelBib"-Reiter (= einfache Suche über alles) um. Bei IxTheo bleibt man unter gleichen Bedingungen korrekt in der Normdatensuche.
Bitte so beheben, dass man im einmal gewählten Suchmodus so lange bleibt, bis man aktiv einen anderen Reiter auswählt.

**Comment by mtrojan-ub** [comment]
Ist reproduzierbar. Ähnliche Baustelle wie #1902.
Es wird zwar der richtige Tab als aktiv angezeigt, aber das Suchformular zeigt aufs falsche Ziel. Wir kümmern uns drum.

**Comment by mtrojan-ub** [comment]
Es könnte sein, dass es sich hierbei sogar um ein vufind-org Problem handelt

**Comment by relhei** [comment]
Hab es auf dem Testsystem für RelBib angeschaut, aber es scheint immer noch nicht zu tun. Auch wenn man den Tab nochmal aktiv "anklickt", ändert sich nichts. Der Platzhaltertext gehört auch nicht zur Normdatensuche:
![grafik](https://user-images.githubusercontent.com/25769591/144847899-932d446b-cf48-4474-9461-fcd52cad0dac.png)

Auf IxTheo-ptah funktioniert es...

**Comment by mtrojan-ub** [comment]
Stimmt, das Template wurde auf einer ebene darunter überschrieben und dort musste der Fix ebenfalls hinzugefügt werden.

Jetzt bitte nochmal testen auf ptah

**Comment by relhei** [comment]
Jetzt passt es. Danke!
