### ISSUE TITLE
Zeitschlagwort in Facette "Thema (Schlagwort)"

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#193]
Die Zeitschlagwörter aus 648 sollten wie aus 689 auch in der Facette "Zeit (Schlagwort)" landen.

Bsp.:
https://www.ixtheo.de/Record/495542768#details
Geschichte 1900-2000 --> 689 | 0 | 1 | \|2 gnd    \|q **z**    \|a Geschichte 1900-2000

https://www.ixtheo.de/Record/497254824#details
Geschichte 1517-1559 --> 648 |   | 7 | \|2 gnd    \|a Geschichte 1517-1559

Problem: offensichtlich wird der Indikator z nicht ausgeliefert. Anfrage beim BSZ läuft

**Comment by IxTheoKm** [comment]
Korrektur:
Das Marc-Feld 648 steht an sich für "Zeit-Schlagwort", bitte daher 648 generell in die Facette "Zeit..." integrieren.

**Comment by jriedl** [comment]
648a ist bereits Teil der Zeitschlagwörter. 
https://www.ixtheo.de/Search/Results?lookfor=%22Bildung%2C+Schule+und+Universit%C3%A4t%22&type=AllFields
zeigt "Geschichte 1517-1559" in der "Zeit (Schlagwort)" an.

**Comment by IxTheoKm** [comment]
Danke, ist o.k.!
