### ISSUE TITLE
Personenseiten: Unterschiede in Darstellung der Word Cloud

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#1932]
Auf Testsystem und RelBib / IxTheo unterscheiden sich die Word Clouds, hier ein Beispiel. 
Testsystem:
![grafik](https://user-images.githubusercontent.com/25769591/144430921-912029b8-6a1e-414d-a03e-f15024faac48.png)
https://134.2.67.9/Authority/845041444

RelBib:
![grafik](https://user-images.githubusercontent.com/25769591/144430969-d868e8dd-9493-4ec2-917b-103577b010a4.png)
https://www.relbib.de/Authority/845041444

In beiden Fällen werden nicht alle vorhandenen (thematischen) Schlagwörter angezeigt - war auch schon mal Thema in der Besprechung.

**Comment by mtrojan-ub** [comment]
Das sollten wir Mitte Januar nochmal prüfen, nachdem die Live-Server aktualisiert wurden.

Vielleicht hängt es aber auch damit zusammen, dass es sehr viele Schlagwörter mit ähnlicher Häufigkeit gibt und nach einer maximalen Anzahl abgeschnitten wird. Ich setze mal @LysogorAndGmail mit drauf.

**Comment by mtrojan-ub** [comment]
Server sind aktuell, es scheint aber immer noch Unterschiede zu geben. 

@LysogorAndGmail: Maybe there is a way to make this more deterministic? (e.g. add sorting parameters to the involved solr queries)

**Comment by mtrojan-ub** [comment]
Testserver wurden aktualisiert. Es kann nun potenziell eine höhere Anzahl von Schlagwörtern angezeigt werden, wobei die Schriftgröße dann verkleinert wird. 

(Live-Server momentan noch nicht aktualisiert, daher noch nicht unbedingt vergleichbar.)

**Comment by relhei** [comment]
Danke - das sieht schon besser aus! Allerdings gibt es immer noch Abweichungen bei der Anzeige der häufigsten Schlagwörter.

Bei dem oben angegebenen Beispiel ist mir noch etwas aufgefallen: "verbundene Autoren" sind in der Zahl auf Test- und Liveserver identisch (6), auf dem Live-Server wird aber die Zahl "7" angezeigt. Wenn man auf "alle anzeigen" klickt, sind es tatsächlich aber nur 6. Auf dem Testserver scheint dies nach VuFind 8 Upgrade nun korrekt angezeigt zu werden (oben im Screenshot vor dem Upgrade noch "falsch"). Brauchen wir ein gesondertes Issue dazu?

**Comment by LysogorAndGmail** [comment]
Ursache war ein Bug in im Zusammenhang mit der Cloudbibliothek, der beim Resizing die Cloud ein weiteres mal geschrieben hat. Ist auf ptah ab sofort, auf ub16 nach dem nächsten Update behoben.

**Comment by relhei** [comment]
Danke - sieht gut aus.
