### ISSUE TITLE
Normdaten Anzeige "Also known as"

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#1933]
$b und $c fehlen bei der Anzeige.

Bsp.:
https://www.ixtheo.de/Authority/133773221
https://www.ixtheo.de/Authority/136125824

![Albertus](https://user-images.githubusercontent.com/17004223/144610162-936f9030-0778-4feb-aa8f-2b98d2a5ed9d.JPG)

![Friedrich](https://user-images.githubusercontent.com/17004223/144611053-546306f2-9353-4fa3-8b72-a4066f497d78.JPG)

**Comment by mtrojan-ub** [comment]
Ready for testing auf ptah

**Comment by IxTheoKm** [comment]
Danke, das passt jetzt. Ich schließe.
