### ISSUE TITLE
Formular "Titel vorschlagen": Kein Mailversand

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#1934]
Auf ptah wird aktuell keine Mail bei Benutzung des Formulars für den Titelvorschlag ("Suggest a title") versandt. Auf RelBib funktioniert es. Zusammenhang mit Update?

**Comment by mtrojan-ub** [comment]
Im Config-File auf ptah steht bei verschiedenen Einträgen als Empfänger @Gazeller drin, insbesondere bei PDA und beim Anschaffungsvorschlag. Soll das auf den selben Wert wie auf ub16 geändert werden? (relbib-pda@ub.uni-tuebingen.de)

**Comment by relhei** [comment]
Von einer Mailadresse relbib-pda@ub.uni-tuebingen.de wusste ich bisher nichts. Gibt es die tatsächlich? Falls ja, dann bitte noch mal abwarten, das müsste erst geklärt werden. Falls nein, bitte umstellen auf Empfänger relbib@ub.uni-tuebingen.de.

**Comment by IxTheoKm** [comment]
In unserer Übersicht der Funktionsadressen steht relbib-pda... drin.

**Comment by relhei** [comment]
Danke, dann bitte anpassen auf denselben Wert wie auf ub16.

**Comment by mtrojan-ub** [comment]
Wurde umgestellt, bitte nochmal testen.

**Comment by relhei** [comment]
"Titel vorschlagen": Es kommt aktuell immer noch keine Mail an die Funktionsadresse relbib@ub.uni-tuebingen.de
Bitte nicht an die RelBib-PDA-Mailadresse schicken, weil das etwas anderes als die PDA-Bestellung ist.

**Comment by mtrojan-ub** [comment]
Sorry dann hatte ich die Anforderung falsch verstanden. 

Ich habe es jetzt sowohl auf ptah als auch auf ub16 geändert zu relbib@ub.uni-tuebingen.de

**Comment by relhei** [comment]
Der Titelvorschlag auf ub16 hat funktioniert, auf ptah nicht (immer noch kein Mailversand).

**Comment by mtrojan-ub** [comment]
Dein letzter Kommentar war ja vor der Urlaubszeit am 21.12.2021 um 10:35.

In der Maillog auf ptah kann ich aber sehen, dass um 10:33 eine Mail an `relbib@ub.uni-tuebingen.de` verschickt wurde:
```
Dec 21 10:33:23 ptah postfix/smtpd[3190639]: connect from localhost[::1]
Dec 21 10:33:23 ptah postfix/smtpd[3190639]: discarding EHLO keywords: CHUNKING
Dec 21 10:33:23 ptah postfix/smtpd[3190639]: 7E390380E214F: client=localhost[::1]
Dec 21 10:33:23 ptah postfix/cleanup[3190642]: 7E390380E214F: message-id=<20211221093323.7E390380E214F@ptah.ub.uni-tuebingen.de>
Dec 21 10:33:23 ptah postfix/qmgr[1738]: 7E390380E214F: from=<no-reply@ub.uni-tuebingen.de>, size=1189, nrcpt=1 (queue active)
Dec 21 10:33:23 ptah postfix/smtpd[3190639]: disconnect from localhost[::1] ehlo=1 mail=1 rcpt=1 data=1 commands=4
Dec 21 10:33:30 ptah postfix/smtp[3190643]: 7E390380E214F: to=<relbib@ub.uni-tuebingen.de>, relay=a1541.mx.srv.dfn.de[194.95.232.90]:25, delay=7.3, delays=0.05/0.01/6.5/0.76, dsn=2.0.0, status=sent (250 2.0.0 from MTA(smtp:[127.0.0.1]:10059): 250 2.0.0 Ok: queued as C7D742A009A)
Dec 21 10:33:30 ptah postfix/qmgr[1738]: 7E390380E214F: removed
```

**Comment by relhei** [comment]
Funktioniert. Danke!
