### ISSUE TITLE
Link zum Artikel auf JSTOR in 856 anzeigen

### ISSUE THREAD

**Issue by helenanebel** [ubtue/tuefind#1946]
URL: https://ixtheo.de/Record/1776883284#details

Liebe Kollegen,
manche der Artikel aus dem RetroTheo-Projekt haben in 866 $x den Link zum JSTOR-Artikel in der Form JSTOR#[URL]
Es wäre wünschenswert, dass dieser Link (ohne den Zusatz vorne) in der Pipeline in ein Feld 856 geschrieben wird, sodass dieser dann unter "Online Zugang:" angezeigt wird.

Viele Grüße, Helena Nebel

**Comment by jriedl** [comment]
vgl. https://github.com/ubtue/ub_tools/pull/4138

**Comment by IxTheoKm** [comment]
Ich habe weitere Titel derselben Zeitschrift angesehen. Die JSTOR-Links werden jetzt angezeigt.
@helenanebel Das Issue könnte damit geschlossen werden, oder?

**Comment by helenanebel** [comment]
Liebe Kollegen,
der JSTOR-Link in https://ixtheo.de/Record/1808895061#details wird leider nicht korrekt angezeigt, sondern als "Unbekanntes Material" hinterlegt mit dem Link https://ixtheo.de/Record/1 (nicht auflösbar)
Viele Grüße, Helena Nebel

**Comment by jriedl** [comment]
Das ist auf ptah bereits behoben (https://ptah.ub.uni-tuebingen.de/Record/1808895061#details), Einspielung auf die Produktivsysteme erfolgt mit dem nächsten Update nach Abschluss der Testphase für VuFind 8.1

**Comment by helenanebel** [comment]
Lieber @jriedl ,
vielen Dank für die Mitteilung.
Viele Grüße, Helena Nebel

**Comment by thefass** [comment]
ok
