### ISSUE TITLE
Bug Aufruf von Personenseiten

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#1963]
Wwnn man von folgendem Volltitelsatz auf das runde Personenseiten-Symbol klickt, kommt eine Fehlermeldung
https://www.ixtheo.de/Search2Record/880340266

![Bildschirmfoto 2022-01-20 um 15 40 44](https://user-images.githubusercontent.com/14169098/150360207-56458e70-71bf-4b75-a6e8-a787e40ea58a.png)

Vom Kurztitelsatz aus funktioniert das aber:
https://www.ixtheo.de/Search/Results?lookfor=author_id:%22772985278%22%20OR%20author2_id:%22772985278%22%20OR%20author_corporate_id:%22772985278%22

**Comment by mtrojan-ub** [comment]
@LysogorAndGmail, can you please have a look & fix this?

Same behaviour on ptah
https://ptah.ub.uni-tuebingen.de/Search2Record/880340266

![grafik](https://user-images.githubusercontent.com/26873381/151203259-3374eda4-ad0c-48e3-9b81-c25b96b5273d.png)

The link to the authority page seems to contain a HiddenFilter-Parameter (has_fulltext)
https://ptah.ub.uni-tuebingen.de/Authority/772985278&hiddenFilters%5B%5D=has_fulltext%3A1

If the additional parameter is removed, it works.

**Comment by mtrojan-ub** [comment]
Ready for testing auf ptah: https://ptah.ub.uni-tuebingen.de/Search2Record/880340266

**Comment by thefass** [comment]
ok
