### ISSUE TITLE
Personenseite: verbundene Autoren

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#1972]
Bereffender Datensatz: https://ixtheo.de/Authority/082468117

Dort sind unter den verbundenen Autoren die Namen Heimbach-Steins, Hein und Höhn aufgelistet, die in der Liste "alle anzeigen" nicht mehr vorkommen.

![Bildschirmfoto 2022-01-26 um 15 02 06](https://user-images.githubusercontent.com/14169098/151177597-8aa08a78-22e2-4634-a352-293a59f2a4f0.png)
![Bildschirmfoto 2022-01-26 um 15 03 33](https://user-images.githubusercontent.com/14169098/151177670-e68762d9-ba3d-4f89-8689-d9a08d80f7d1.png)

Es sollten auch 109 sein, in der Liste "alle anzeigen" ist davon aber nur ein Bruchteil. Selbst wenn man die Zahl der angezeigten Titel auf 200 erhöht:
![Bildschirmfoto 2022-01-26 um 15 08 43](https://user-images.githubusercontent.com/14169098/151178040-51e39c7a-45ea-4be2-ab2b-25126f8e3ae3.png)

**Comment by mtrojan-ub** [comment]
@LysogorAndGmail arbeitet hier bereits an einer Änderung die heute auf ptah eingespielt wurde. Tritt es auf ptah noch auf?
https://ptah.ub.uni-tuebingen.de/Authority/082468117

**Comment by thefass** [comment]
auf ptah ist das ok.

**Comment by thefass** [comment]
auf ptah ok

**Comment by thefass** [comment]
ok
