### ISSUE TITLE
Virtuelle Tastaturen in IxTheo

### ISSUE THREAD

**Issue by AleAprile** [ubtue/tuefind#2010]
Beide virtuelle Tastaturen vom IxTheo lassen sich ein- aber nicht ausblenden. @thefass schlägt vor, dass das durch einen Klick auf einen beliebigen Blanko-Bereich erfolgen sollte. Ist das möglich? Welche anderen Möglichkeiten gibt es?

**Comment by jriedl** [comment]
Die virtuelle Tastatur lässt sich derzeit mit Escape, Enter oder durch Klicken einer der beiden blauen Tasten auf der virtuellen Tastatur wieder schließen. Wir werden schauen, ob das wie gewünscht umsetzbar ist.

**Comment by AleAprile** [comment]
Vielen Dank für Deine Rückmeldung, Johannes. Diese Möglichkeiten waren mir persönlich schlicht und ergreifend nicht bekannt. Vielleicht sind sie auch aussreichend. Was denkst Du @thefass?

**Comment by thefass** [comment]
Ich hatte in Erinnerung, dass man die virtuelle Tastatur irgendwie ausschalten kann. Die jetzigen Möglichkeiten sind aber alle nicht intuituv. Insofern wäre eine intuitivere Lösung angebracht. 
Klick auf einen beliebigen Blanko-Bereich und / oder ein X im Fenster der virtuellen Tatstur

**Comment by andreas-ub** [comment]
es ist nun die neue Version der virtuellen Tastatur eingebunden.
Dabei funktioniert das Verlassen der Tastatur (ohne Übernahme der Buchstaben) mit einem Klick außerhalb.
Auf ptah aktiv -> ready for testing.

**Comment by thefass** [comment]
ok
