### ISSUE TITLE
Volltextsuche KrimDok

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#2041]
Warum werden bei einer Suche nach "Wirtschaftsrecht" auf KrimDok die Treffer 1, 3, 5, 7 etc gefunden, obwohl es den Begriff im Volltext nicht gibt?
https://krimdok.uni-tuebingen.de/Search2/Results?hiddenFilters%5B%5D=has_fulltext%3A%221%22&lookfor=wirtschaftsrecht&type=FulltextOnly
Es wird in diesen Fällen auch kein Highlight un Snippet angezeigt
<img width="695" alt="Bildschirmfoto 2022-03-28 um 15 05 57" src="https://user-images.githubusercontent.com/14169098/160404355-d25c5e6f-c1a1-4767-bcb4-162fbc526165.png">
<img width="677" alt="Bildschirmfoto 2022-03-28 um 15 06 27" src="https://user-images.githubusercontent.com/14169098/160404358-3dc562a4-fcfb-4590-b5c6-afa9c9b85196.png">

**Comment by jriedl** [comment]
Auf sobek behoben.

**Comment by thefass** [comment]
ok
