### ISSUE TITLE
RSS-Feeds abonnieren: Usability-Problem

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#2045]
gemeldet von @thefass 

Wenn man unterhalb von "Mein Konto" den RSS-Menüeintrag verwendet und bei einem Feed auf "Abonnieren" klickt, springt die Ansicht ganz nach oben. Ärgerlich wenn man mehrere Feeds abonnieren möchte und jedes Mal wieder runter scrollen muss.

**Comment by mtrojan-ub** [comment]
@LysogorAndGmail: When you fix this one (clicking the "subscribe" button jumps to top of the page), please also add a column which contains the pub_date of the newest item which is linked to that feed (can be empty).

**Comment by mtrojan-ub** [comment]
![grafik](https://user-images.githubusercontent.com/26873381/161534001-ca114d40-ff4f-4817-ad4b-14e14fae89f0.png)

**Comment by mtrojan-ub** [comment]
ready for testing auf ptah

**Comment by thefass** [comment]
funktioniert: ok
