### ISSUE TITLE
Bibelstellensuche: "Recommend"-Funktion deaktivieren?

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#2048]
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=4+esra+1-6&type=BibleRangeSearch

![grafik](https://user-images.githubusercontent.com/26873381/161493539-9e85a34d-5bad-4b16-9d4b-0e960847ebbc.png)

In der Bibelstellensuche wird aktuell der Abschnitt "Häufige Schlagwörter innerhalb Ihrer Suche" angezeigt.
Macht der Abschnitt an dieser Stelle überhaupt Sinn bzw. wäre es besser ihn dort auszublenden?

**Comment by thefass** [comment]
Ist jetzt vielleicht nicht die sinnvollste Info. Aber hilfreich genug, dass wir das nicht ändern müssen.
