### ISSUE TITLE
Personenseite: seltsames Verhalten

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#2050]
Wenn man auf der zweiten Seite (Treffer 21-33) einer größeren Treffermenge (hier: insgesamt 33 Treffer) ist und dann die Default Treffermenge (20) auf z.B. 50 erhöht, um alle 'Treffer auf einer Seite angezeigt zu bekommen, kommt die Fehlermeldung: keine Ergebnisse. 
Wenn man die Treffer pro Seite aber auf der ersten Trefferseite erhöht ist alles ok.

Beispiel:
https://ixtheo.de/Author/Search?view=authorfacets&lookfor=author_id%3A37339201X+OR+author2_id%3A37339201X+OR+author_corporate_id%3A37339201X&type=Author&page=2
Beispiel Bild
<img width="899" alt="Bildschirmfoto 2022-04-05 um 16 36 50" src="https://user-images.githubusercontent.com/14169098/161779201-d28765e7-4ceb-4835-923c-c73b0a4f900e.png">

Seltsames Ergebnis:
<img width="923" alt="Bildschirmfoto 2022-04-05 um 16 37 38" src="https://user-images.githubusercontent.com/14169098/161779120-291336ac-1b81-4a31-884a-07b0dd70f9f1.png">

**Comment by mtrojan-ub** [comment]
Ready for testing auf ptah

**Comment by thefass** [comment]
auf ptah ok
