### ISSUE TITLE
Sortierung nach Bandnummer

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#2053]
Basierend auf einer Anfrage von @jjspp01 

Beispiel: https://sobek.ub.uni-tuebingen.de/Search/Results?lookfor=superior_ppn:798562986
Hier sind die Bandnummern teilweise durcheinander (gilt auch dann, wenn als Sortierung "Neueste zuerst" ausgewählt wird).
Auffällig ist, dass bei diesen Datensätzen die Solr-Felder "volume" und "volume_sort" nicht befüllt werden. 
(Das basiert bislang nur auf 936 und hat daher wohl nur bei Aufsätzen einen Effekt, aber nicht bei Monografien, ggf. müsste das auf 830 ausgeweitet werden).

Beispiel: https://sobek.ub.uni-tuebingen.de/Record/1796835358

**Comment by andreas-ub** [comment]
ist angepasst -> "ready for testing"

**Comment by mtrojan-ub** [comment]
funktionliert laut @jjspp01 jetzt, daher schließe ich.

**Comment by thefass** [comment]
Sioeht gut aus. Sind diese Sortierregeln auch in Relbib und IxTheo implementiert?

**Comment by andreas-ub** [comment]
ja, das Feld wird umgebungsunabhängig befüllt.

**Comment by thefass** [comment]
Danke für die Info
