### ISSUE TITLE
Blog-Aggregator Symbolanzeige

### ISSUE THREAD

**Issue by ja-bre** [ubtue/tuefind#2061]
Beim IxTheo Blog-Aggregator erfolgt auf der Startseite (im Moment bei zwei Blogs – einer aus der IxTheo- einer aus der RelBib-Liste) die Symbolanzeige vorne nicht korrekt:

<img width="1216" alt="Bildschirmfoto 2022-04-11 um 08 59 13" src="https://user-images.githubusercontent.com/83392048/162693597-cb76688a-6c10-4dcd-bb6c-99f9ce908af3.png">

**Comment by mtrojan-ub** [comment]
Die Anzeige ist in der Tat seltsam, kann ich aber nicht reproduzieren. Welchen Browser verwenden sie genau?

Nicht bei jedem Feed ist ein Icon hinterlegt. Wir haben vor wenigen noch ein Problem beim Auflösen des Fallback-Icons behoben. Sieht es ggf. auf Ptah bereits besser aus?

**Comment by ja-bre** [comment]
Auf ptah sieht es richtig aus. "feinschwarz" der Blog mit dem "Paulus, Andreas Bourani ..." Beitrag hat ein hinterlegtes Icon, das hier auch angezeigt wird.. Beim anderen Blog scheint es auch ein eigenes Icon zu sein ..

<img width="1258" alt="Bildschirmfoto 2022-04-11 um 10 29 13" src="https://user-images.githubusercontent.com/83392048/162696837-802faf29-054b-4fe7-860a-215db479643f.png">

**Comment by ja-bre** [comment]
Ich nutze Safari und habe es gerade auf dem Live-Serve noch mit Google Chrome ausprobiert; da scheinen es Platzhalter-Icons zu sein


<img width="1274" alt="Bildschirmfoto 2022-04-11 um 10 29 18" src="https://user-images.githubusercontent.com/83392048/162697001-2e063c39-d88f-4397-b29f-f8029ad7edf7.png">
s

**Comment by mtrojan-ub** [comment]
Sieht es jetzt besser aus? Die Liveserver wurden heute aktualisiert.

**Comment by ja-bre** [comment]
Sorry für die späte Antwort. Ich hatte eine Weile nicht von zu Hause aus mit Safari gearbeitet. Jetzt sieht es mit allen getesteten Browsern gut aus!

**Comment by mtrojan-ub** [comment]
OK, dann schließe ich den Issue!
