### ISSUE TITLE
Falsche Anzeige der parallelen Ausgaben

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#207]
Es sieht so aus als würde der Titel einer parallelen Druck-/Online-Ausgabe Feld 776 beim Titel des übergeordneten Werks "In: " angezeigt:
https://www.ixtheo.de/Record/455599483#details
https://www.ixtheo.de/Record/461199947#details

Es müsste mit den einleitenden Wendungen von 776 |i angezeigt werden:
Erscheint auch als  |n Druck-Ausgabe   bzw.  ... |n Online-Ausgabe 

![776_li](https://user-images.githubusercontent.com/17004223/36846839-831b93d8-1d5c-11e8-95a9-fa3b730b65a9.jpg)

![776_2_li](https://user-images.githubusercontent.com/17004223/36846816-70249a90-1d5c-11e8-837c-e0c002f84e8d.jpg)

**Comment by relhei** [comment]
#302

**Comment by IxTheoKm** [comment]
Die parallelen Ausgaben werden im IxTheo im Titelsatz nun gar nicht mehr angezeigt.

Auf PTAH finde ich die PPN 461199947 mit der Suche "id:461199947" nicht mehr. Nur noch als Freitextsuche.
Ich vermute, das hängt mit der Zusammenführung der gedruckten und elektronischen Ausgaben zusammen.

Es wird dadurch aber das übergeordnete Werk (Schriftenreihe) in 830 doppelt angezeigt, ohne dass erkennbar ist, welcher Eintrag zur gedruckten und welcher zur elektronischen Aufnahme der Schriftenreihe führt.
Diese beiden Aufnahmen der Schriftenreihen sind noch nicht dedupliziert. 
Wenn dies später der Fall sein wird, muss in der Aufnahme des untergeordneten Werks die "überlebende" PPN des übergeordneten Werks aus 830 angezeigt werden.

**Comment by mtrojan-ub** [comment]
Wir haben heute etwas an der Zusammenführung von gedruckten und elektronischen Ausgaben geändert. Das Ergebnis sollte morgen auf ptah zu sehen sein, dann schaue ich mir diesen Issue nochmal an.

**Comment by mtrojan-ub** [comment]
Die PPN 461199947 existiert nun wieder auf PTAH und kann mittels "id:461199947" gefunden werden.

Allerdings hat der Datensatz mehrere 830er Uplinks
![grafik](https://user-images.githubusercontent.com/26873381/44704880-40e2e880-aa9d-11e8-9fb2-d43b10c0cc6b.png)

Der erste davon zeigt ins leere (425370712, print), nur der zweite funktioniert (425482162, online).
Vermutlich wurden die beiden zusammengeführt und der erste uplink muss beim mergen entfernt werden.

**Comment by IxTheoKm** [comment]
Wenn die beiden übergeordneten Werke zusammengeführt werden, sollten weiterhin beide PPNs recherchierbar sein (wie bei den parallelen Ausgaben der untergeordneten Werke).

**Comment by mtrojan-ub** [comment]
"id" ist ein Standard VuFind Feld und es könnte kritisch sein dies als Mehrfachfeld zu definieren.
Daher haben wir stattdessen ein "**ids**" Feld definiert, in dem sowohl die eigene PPN als auch die zusammengeführten PPNs gespeichert werden (nur ixtheo). 
Da neu importiert werden muss, ist es voraussichtlich ab morgen früh testbar.

**Comment by IxTheoKm** [comment]
Suche mit id/s und Anzeige im Titelsatz funktioniert jetzt korrekt. Vielen Dank!
