### ISSUE TITLE
Sprache wird nicht richtig nach DSpace übernommen

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#2076]
Deutsch: https://ptah.ub.uni-tuebingen.de/Record/717772098
Englisch: https://ub07.uni-tuebingen.de/items/a046f246-b83c-4537-a533-5a281d61b89f/full

**VuFind:**
![grafik](https://user-images.githubusercontent.com/26873381/163944985-7e899753-e587-4f78-9d41-b0c4ab63c05d.png)

**DSpace:**
![grafik](https://user-images.githubusercontent.com/26873381/163945251-ef818465-f986-4a77-a94a-040f0c075287.png)

**Comment by mtrojan-ub** [comment]
Wurde angepasst. Auch Datensätze mit mehreren Sprachen werden nun korrekt übernommen.

Ready for testing auf ptah

Beispiel: 
IxTheo: https://ptah.ub.uni-tuebingen.de/Record/1762923564
DSpace: https://ub07.uni-tuebingen.de/items/5e839ea1-ca6b-456a-a597-7ea25fa4bc27/full

**Comment by thefass** [comment]
ok
