### ISSUE TITLE
Falsche Anzeige der Tags

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#208]
Die Tags werden abweichend von der Erfassung nur in Kleinbuchstaben angezeigt:
Erfasst wurden: DDA, Demand-driven acquisiton, Kundengesteuerte Erwerbung

![tags_li](https://user-images.githubusercontent.com/17004223/36847750-928dde68-1d5f-11e8-88c3-128e5229ca3a.jpg)

**Comment by jriedl** [comment]
Auf ptah jetzt mit Beachtung der Groß-/Kleinschreibung

**Comment by IxTheoKm** [comment]
Jetzt in Ordnung, danke!
