### ISSUE TITLE
Blog Aggregator: Beschreibung für E-Mail-Benachrichtigung fehlt

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#2083]
Im RelBib-Konto (Live-System) ist nun die Rubrik "RSS" enthalten, in der Nutzer*innen einzelne Blogs für die E-Mail-Benachrichtigung auswählen können. Bitte noch - analog zu ptah (s. Bild) - die Kurzbeschreibung unterhalb der Feed-Liste ergänzen. Danke!
![grafik](https://user-images.githubusercontent.com/25769591/166922040-f835f483-4a4b-4dbd-975b-c50bbfde9593.png)

**Comment by relhei** [comment]
Ergänzung: Hab gerade gesehen, dass dieses Feature noch gar nicht in IxTheo freigeschaltet ist. Bitte dann bei RelBib auch noch nicht im Konto anzeigen.

**Comment by mtrojan-ub** [comment]
Das Problem ist => Der Text wird erst dann angezeigt, wenn man mindestens einen Feed abonniert hat und danach von Hand die Seite neu lädt. Die Usability muss an dieser Stelle verbessert werden.

**Comment by mtrojan-ub** [comment]
In dem Kontext ist noch ein weiteres Problem aufgefallen, insbesondere wenn ein Benutzer seinen persönlichen Feed aufrufen möchte und dieser leer ist. Wir arbeiten bereits an einer Lösung.

**Comment by mtrojan-ub** [comment]
Das genannte Problem wurde gelöst (Fehler beim Aufrufen eines leeren persönlichen Feeds). Außerdem wird der hier im Issue genannte Bereich (siehe Screenshot im 1. Beitrag) in den Einstellungen nun immer angezeigt. Noch etwas ärgerlich: Beim Aktivieren der Mail-Benachrichtigung springt die Ansicht nach oben. Hier kümmern wir uns noch um eine Optimierung.

**Comment by mtrojan-ub** [comment]
Jetzt müsste alles passen. Außerdem haben wir auf User-Wunsch hin den Abschnitt "Möchten Sie eine E-Mail-Benachrichtigung über neue Blogeinträge erhalten?" von unten nach oben verschoben. => ready for testing.
