### ISSUE TITLE
PDA für KrimDok

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#209]
Wenn ein Datensatz dem MPI zugeordnet und nicht "in Tübingen available" ist, dann soll in der Detailansicht ein Link eingeblendet werden der das Formular "Anschaffungsvorschlag" aufruft und die Felder vorbefüllt.

![grafik](https://user-images.githubusercontent.com/26873381/37080985-58a5799e-21e8-11e8-845b-437374f86116.png)

(noch zu klären => wie erfolgt die Zuordnung zum MPI in MARC21?)

**Comment by mtrojan-ub** [comment]
Passt der Displaytext?

![grafik](https://user-images.githubusercontent.com/26873381/37095533-80980380-2216-11e8-97d2-8b4a20b10bae.png)

![grafik](https://user-images.githubusercontent.com/26873381/37095604-ae213ccc-2216-11e8-8b35-2d700b553277.png)

**Comment by ruschein** [comment]
Finde ich sehr gut.


--
Dr. Johannes Ruscheinski
Universitätsbibliothek Tübingen - IT-Abteilung -
Wilhelmstr. 32, 72074 Tübingen

Tel: +49 7071 29-72820
FAX: +49 7071 29-5069
Email: johannes.ruscheinski@uni-tuebingen.de

________________________________

**Comment by mtrojan-ub** [comment]
Beispiel: https://sobek.ub.uni-tuebingen.de/Record/409624381

**Comment by KStelzel** [comment]
Funktioniert gut! Nur den Displaytext finde ich irreführend: 1. könnte "Bestellung" auch als Fernleihbestellung verstanden werden und 2. wird suggeriert, dass wir (wenn der Text als Kaufanregung an den FID verstanden wird) das Werk dann auch ganz sicher kaufen (aber wir prüfen es ja nochmal - kaufen es dann zwar allerhöchstwahrscheinlich, aber eben nicht garantiert). Ich würde stattdessen sowas wie "Erwerb anregen für den Tübinger Fernleih-Bestand" vorschlagen. Ist leider ziemlich lang... Hat jemand eine griffigere Formulierungsidee?

**Comment by IxTheoKm** [comment]
Ist nicht "Anschaffungsvorschlag" der gängige Begriff? Der steht ja auch über dem Formular

**Comment by Gazeller** [comment]
Wie wär’s mit dem „guten alten“ Anschaffungsvorschlag? Oder „Vorschlag zur Anschaffung“?
Gruß von der Peripherie ☺
Gaby

Von: KStelzel <notifications@github.com>
Gesendet: Montag, 4. Juni 2018 16:19
An: ubtue/tuefind <tuefind@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [ubtue/tuefind] PDA für KrimDok (#209)


Funktioniert gut! Nur den Displaytext finde ich irreführend: 1. könnte "Bestellung" auch als Fernleihbestellung verstanden werden und 2. wird suggeriert, dass wir (wenn der Text als Kaufanregung an den FID verstanden wird) das Werk dann auch ganz sicher kaufen (aber wir prüfen es ja nochmal - kaufen es dann zwar allerhöchstwahrscheinlich, aber eben nicht garantiert). Ich würde stattdessen sowas wie "Erwerb anregen für den Tübinger Fernleih-Bestand" vorschlagen. Ist leider ziemlich lang... Hat jemand eine griffigere Formulierungsidee?

**Comment by thefass** [comment]
"Anschaffungsvorschlag" und im Englischen "book order suggestion" oder kürzer acquisition suggestion wären doch ganz gut

**Comment by mtrojan-ub** [comment]
![grafik](https://user-images.githubusercontent.com/26873381/40966049-b9b5e030-68af-11e8-8943-d0c0ee26567b.png)

Da es so im Wörterbuch steht haben wir bisher "Anschaffungsvorschlag" und "acquisition request" verwendet. Ist "acquisition suggestion" wirklich eine etablierte englische Benennung?

Ich schlage vor dass wir die Texte im heutigen Meeting besprechen

**Comment by thefass** [comment]
es gibt ein dt-eng Bibliotheksglossar:
http://www.bibliotheks-glossar.de/

Anschaffungsvorschlag m - book order suggestion n, purchase suggestion n, recommendation n
Anschaffungsvorschlag/Anfrage m - acquisition request n 

wir können also auch bei acquisition request bleiben

**Comment by obrandt** [comment]
Hallo,

auf der UB-Seite wird „Acquisition request“ benutzt. Da sollten wir konsistent sein.

Viele Grüße

Olaf

Von: thefass [mailto:notifications@github.com]
Gesendet: Dienstag, 5. Juni 2018 11:15
An: ubtue/tuefind <tuefind@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [ubtue/tuefind] PDA für KrimDok (#209)


es gibt ein dt-eng Bibliotheksglossar:
http://www.bibliotheks-glossar.de/

Anschaffungsvorschlag m - book order suggestion n, purchase suggestion n, recommendation n
Anschaffungsvorschlag/Anfrage m - acquisition request n

wir können also auch bei acquisition request bleiben

**Comment by mtrojan-ub** [comment]
Gibt's dann im Fließtext noch etwas anzupassen, oder kann der Issue geschlossen werden?

**Comment by KStelzel** [comment]
der Fließtext ist mE okay
