### ISSUE TITLE
"Zurücksetzen"-Button für Suche

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#2094]
Wunsch von @thefass, ähnlich wie bei google

![grafik](https://user-images.githubusercontent.com/26873381/167420571-51e8e6d2-5657-48ec-825b-ef2b0feb5ad5.png)

**Comment by mtrojan-ub** [comment]
Funktioniert in den meisten Subsystemen, allerdings noch nicht in IxTheo2. Das liegt aber daran dass die Suchbox im Header eingebunden wurde. Damit gehen Informationen verloren die technisch nicht im Header durchgereicht werden können. Ich werde mir das noch bei Gelegenheit anschauen wie sich das verbessern lässt.

**Comment by mtrojan-ub** [comment]
Besprochen mit @thefass: Es ist möglich, dass sich die Position der Suchbox noch mit den neuen Anforderungen verändern wird die wir im September/Oktober erhalten. Daher erstmal nur prüfen ob es Probleme mit der grundsätzlichen technischen Struktur gibt.

**Comment by mtrojan-ub** [comment]
@thefass: Der Zurücksetzen Button ist mittlerweile eingebunden. Kannst Du ihn bitte testen?

**Comment by thefass** [comment]
Hi, den nutze ich schon täglich und es ist total super, dass es ihn jetzt gibt.
Funktioniert einwandfrei.
