### ISSUE TITLE
"Feed abonnieren": Popup

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#2096]
Anfrage von @thefass (@relhei zur Info):
Sowohl auf IxTheo als auch auf RelBib gibt es diesen Button:

![grafik](https://user-images.githubusercontent.com/26873381/167428995-71c25b96-21cb-4194-81b7-17b6800d9a03.png)
![grafik](https://user-images.githubusercontent.com/26873381/167429145-13679290-d938-4554-a36f-29b7fe981818.png)

Dieser Button zeigt aktuell auf die Gesamt RSS Datei, die man nur mittels eines RSS Readers anschauen kann. Da nur wenige Benutzer einen RSS Reader bei sich installiert haben oder sich überhaupt mit RSS auskennen, kann dies zu Verwirrung führen. Daher soll die Funktionsweise verändert werden.

Beim Klicken auf den Button soll stattdessen ein Popup angezeigt werden. Hier ein erster Entwurf:
![grafik](https://user-images.githubusercontent.com/26873381/167429630-81a94831-264b-4a05-a068-388727c1f645.png)

Gibt es konkretere Anforderungen, wie der Text genau lauten soll?

**Comment by relhei** [comment]
Text für gut befunden. Kleiner Fehler: "Zum abonnieren.." Richtig heißt es: "Zum Abonnieren..." Könnte man eventuell noch als Beispiel Hinweise / Links auf RSS-Reader einbauen (icons)?

**Comment by thefass** [comment]
Ich würde die Überschrift ändern in: Feed abonnieren

sodann bitte die Strings "Rss-Reader" (Satz1 und in Satz 3 "Der persönliche ...) und "E-Mail" als bold hervorheben. 
Damit sind die drei Alternativen gut sichtbar.

sodann würde ich Satz eins umformulieren:
Sie können den gesamten Feed mit einem RSS-Reader abonnieren. Dazu benötigen Sie auf Ihrem System einen RSS-Reader.
Nur der erste Sting "RSS-Reader" soll boild hervorgehoben werden, die zweite Erwähnung in dem Satz nicht
****
Der Link auf rss-reader.org ist gut und m.E. ausreichend

**Comment by relhei** [comment]
Einverstanden mit @thefass 

Folgende Überlegung noch: Anstelle eines erklärenden Satzes zu RSS-Readern am Ende könnte man einfach den Begriff "RSS-Reader" bei der ersten Nennung auch entsprechend verlinken. 

Den zweiten Bullet Point würde ich mit "Alternativ verwenden Sie..." statt "Oder Sie verwenden..." beginnen. Denn bei Punkt 4 beginnt der Teilsatz auch wieder mit "oder".

**Comment by mtrojan-ub** [comment]
Neuer Entwurf:
![grafik](https://user-images.githubusercontent.com/26873381/167612460-433dcc3c-85d2-45ca-9c73-ddb535211dec.png)

**Comment by relhei** [comment]
Jetzt sieht es so aus, als ob im 3. Punkt RSS-Reader noch einmal verlinkt ist - hier reicht m.E. bold.
Kleinigkeiten fallen immer erst später auf... In den Buttons unten steht einmal "RSS-Feed" und einmal "Feed". Vorschlag: Text im ersten Button ändern zu "Gesamten Feed mit RSS-Reader abonnieren"

**Comment by mtrojan-ub** [comment]
Neuer Versuch:
![grafik](https://user-images.githubusercontent.com/26873381/167620004-9d49e061-8aee-4c1a-9ff0-165f0ef97408.png)

**Comment by relhei** [comment]
Danke! Passt für mich.

**Comment by mtrojan-ub** [comment]
Das Popup ist nun auf ptah aktiv => Bitte testen. Außerdem habe ich auf die Schnelle eine englische Übersetzung dafür angelegt, bitte ebenfalls um Feedback ob das so passt.

**Comment by relhei** [comment]
Sieht gut aus. Danke!
