### ISSUE TITLE
Alerts kommen nicht

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#210]
Ich habe testweise mehrere Zeitschriften abonniert, bekomme aber bisher keine Alerts.

Erster Versuch: 27.2.2018 (Aufsätze einer Zeitschrift wurden am 27.2. erfasst, am 28.2. im IxTheo angezeigt)

Zweiter Versuch: 6.3.2018 (Aufsätze von drei Zeitschriften wurden am 6.3. erfasst, am 7.3 im IxTheo angezeigt)

**Comment by jriedl** [comment]
Hier gab es seit Montag Schwierigkeiten mit der Abfrage der Titel, das nun behoben sein sollte. Heute Abend sollten die ausstehenden Alerts versandt werden. Bitte aber insbesondere den Titel vom Februar überprüfen.

**Comment by IxTheoKm** [comment]
Alert ist erfolgt für 12 Aufsätze (erfasst am 7.3. eingespielt am 8.3.2018) der Zeitschrift 093888538 Journal for the scientific study of religion (500616957, 500616949, 500617627, 500617619, 500617600, 500617597, 500617589, 500617570, 500617562, 500617554, 500617546, 500617538).

Alert nicht erfolgt für 
014399830 La civiltà cattolica (Aufsätze erfasst am 6.3.)

057735875 Lutheran theological review (Aufsätze erfasst am 27.2.)

015193551 Rivista di pastorale liturgica (1 Band PPN 500640076 erfasst am 8.3., ein Aufsatz PPN 500423296 erfasst am 6.3.)

**Comment by mtrojan-ub** [comment]
Auf ub16 war der Timestamp (max_last_modification_time) in der Datenbank für die genannten Zeitschriften zu hoch, habe diese zurückgesetzt. Auf ptah habe ich es simuliert und keine Fehler festgestellt, d.h. es sollte heute Abend verschickt und die max_last_modification_time korrekt eingetragen werden.

**Comment by thefass** [comment]
@mtrojan-ub Kann dieser Fehler auch noch bei anderen Zeitschriften vorkommen? Muss für jede Zeitschrift einzeln der Timestamp bestimmt/gesetzt werden?

**Comment by IxTheoKm** [comment]
Ich habe am 15.03.2018, 22:00 Uhr den Alert für Daten von 14. _und_ 15.3. bekommen. 
Am 14.03.2018, 22:00 Uhr habe ich rückwirkend teilweise die vermissten Daten (auch vom 27.02.) bekommen. Aber die Aufsätze vom 6.3. von 014399830 La civiltà cattolica fehlen weiterhin.

Das Prinzip ist mir unklar. Müsste es nicht für alle Zeitschriften gleich sein?
Insbesondere wenn wir den Alert-Service in irgendeiner Weise für die Meldung zur Sacherschließung nutzen wollen, brauchen wir einen zuverlässigen Alert-Service, der bei allen Zeitschriften gleich funktioniert.

**Comment by jriedl** [comment]
Das Verfahren ist für alle Zeitschriften identisch: Wenn eine Zeitschrift abonniert wird, wird die zugehörige PPN und der Abonnierzeitpunkt in der Datenbank gespeichert. Eine Benachrichtigung wird ausgelöst, falls für ein untergeordnetes Werk das first_indexed-Feld neuer ist als das Abonnement-Datum. first_indexed wird aus MARC 005 bzw. falls nicht vorhanden MARC 008 bestimmt. Bereits versandte untergeordnete Werke werden in einer gesonderten Datenbank gespeichert, um zu verhindern, dass sie bei Änderungen an diesem Datensatz erneut verschickt werden. Falls also die Erfassung der Aufsätze vor dem Abonnement erfolgte, wäre eine Nichtbenachrichtigung formal korrekt (Wert in 005 älter als Abonnementzeitpunkt). 
Dies scheint nach Stichproben für die "Lutheran theological review" und die "Rivista di pastorale liturgica" der Fall zu sein. 

In der Datenbank der bereits versandten untergeordneten Werke wurden Aufsätze der "La civiltà cattolica" am 7.3. eingetragen. Deshalb wurden sie jetzt auch nach dem manuellen Rücksetzen des Datums nicht noch einmal verschickt. Wäre es möglich, uns hier die Benachrichtigungsmail vom 7.3. weiterzuleiten?

**Comment by IxTheoKm** [comment]
Alerts sind unvollständig:

Am 22.3. abonniert:
094752656 Journal of beliefs and values
274589745 Journal for the study of religion, nature and culture
477218679 Missionalia

2 Alerts am 23. und 24.3 22:00 Uhr erhalten für 274589745 (Aufsätze erfasst am 22. und 23.3.)

Nicht erhalten: 
094752656 (50 Aufsätze am 22.3. erfasst)
477218679 (1 Aufsatz ppn 50133789X erfasst am 22.3.)

**Comment by jriedl** [comment]
Wie es aussieht, wurden für 094752656 und 477218679 erst die Aufsätze erfasst und dann das Abonnement eingetragen (Abonnementzeitpunkt 2018-03-22 16:04:35 bzw. 2018-03-22 16:07:24). Die Uhrzeit der aus MARC 005 ausgelesenen Zeiten scheint für alle diese Aufsätze davor zu liegen, deshalb erfolgte korrekterweise keine Benachrichtigung

**Comment by ruschein** [comment]
Ich fände es eher verwirrend wenn das Abonnement eine willkürliche Zeit in der Vergangenheit anfängt.  Warum sollte ein Anwender erwarten wenn er jetzt etwas abonniert, dass er dann Artikel die in der Vergangenheit in IxTheo eingespielt wurden bekommt?  Macht es auch schwerer für das Debuggen von Entwicklern in der Zukunft.  Ich kann mir so etwas nie merken und müsste mehr recherchieren um das wieder zu verstehen.

**Comment by mtrojan-ub** [comment]
nach weiterer telefonischer Abstimmung zwischen @thefass und @ruschein wird jetzt beim Eintragen eines neuen Alerts statt der aktuellen Stunde/Minute/Sekunde immer 00:00:00 am aktuellen Tag verwendet. Kann auf ptah getestet werden.

**Comment by IxTheoKm** [comment]
Für zwei Zeitschriften auf ptah getestet: Aufsätze am 03.04. erfasst, Alert am 04.04. 22:00 Uhr erhalten.

**Comment by IxTheoKm** [comment]
Mehrere Zeitschriften am 16.05.2018 in IxTheo, auf PTAH und in RelBib abonniert. Bisher kein Alert erhalten.

**Comment by ruschein** [comment]
Haben heute ein Problem behoben.

**Comment by ruschein** [comment]
Ich vermute, dass die älteren Titel heute nacht noch gemeldet werden.


Viele Grüße,

Johannes Ruscheinski

--
Dr. Johannes Ruscheinski
Universitätsbibliothek Tübingen - IT-Abteilung -
Wilhelmstr. 32, 72074 Tübingen

Tel: +49 7071 29-72820
FAX: +49 7071 29-5069
Email: johannes.ruscheinski@uni-tuebingen.de

 The Sophisticate:  "The world isn't black and white.  No one does pure good or pure bad. It's all gray.  Therefore, no one is better than anyone else."
    The Zetet:  "Knowing only gray, you conclude that all grays are the same shade.  You mock the simplicity of the two-color view, yet you replace it with a one-color view..."
      —Marc Stiegler, David's Sling


________________________________

**Comment by IxTheoKm** [comment]
Alert ist heute gekommen, aber unvollständig:

368309355 Moreana: 
Von 73 erfassten Titeln wurden 29 gemeldet (alle am 16.5. katalogisiert)

42547724X Journal of Holy Land and Palestine Studies: 
von 49 Titeln wurden 36 gemeldet (teilweise vom 16.5., teilweise vom 17.5.)

Da ich zufällig festgestellt habe, dass ich in RelBib eine Zeitschrift nicht zusätzlich abonnieren kann, wenn sie schon im IxTheo abonniert ist, habe ich testweise in beiden Datenbanken unterschiedliche Zeitschriften abonniert. Dazu lege ich ein eigenes Issue an.

**Comment by IxTheoKm** [comment]
Alert über **IxTheo** ist heute (29.5.) für Aufsätze gekommen, die am 16.5. erfasst wurden:
Vollständig für 
256620571 Journal of Anglican studies
020017219 The studia Philonica annual
014992124 Antonianum
322767741 Estudos de religião

Nicht geliefert wurden die Aufsätze von:
368309355 Moreana
42547724X Journal of Holy Land and Palestine Studies
(Diese wurden über RelBib schon unvollständig geliefert, über IxTheo-Alert gar nicht.)

**Comment by IxTheoKm** [comment]
Am 6.7. habe ich einen Alert über IxTheo zu 15 Aufsätzen der Zeitschrift "Estudos de religião" PPN 322767741 bekommen. Ich habe aber gar keine Zeitschrift mehr abonniert!

**Comment by jriedl** [comment]
Auf ptah ist diese Zeitschrift noch durch Sie abonniert.

**Comment by IxTheoKm** [comment]
Danke, dann also doch keine Geister am Werk!

**Comment by IxTheoKm** [comment]
Alerts sind unvollständig: von 122 Aufsätzen an PPN 273868179 (katalogisiert am 1.8.2018) wurden am 3.8.2018 von IxTheo und von ptah nur 85 gemeldet.

**Comment by mtrojan-ub** [comment]
Sind die restlichen Aufsätze mittlerweile via Alerting angekommen? (siehe #358)
Können Sie uns eine aktuelle Aufsatz-PPN nennen die noch fehlt?

**Comment by mtrojan-ub** [comment]
Aktuelle Beispiel-PPNs von @IxTheoKm:
alert vorhanden: 508150884
alert fehlt: 508141842

Beides sind Titel der selben Zeitschrift: 273868179
Beide wurden am 1.8. eingefügt

**Comment by mtrojan-ub** [comment]
Beim Alerting gibt es eine Beschränkung auf das Jahr (936j). Es erfolgen nur Alerts bei denen das Jahr im Bereich aktuelles Jahr bis aktuelles Jahr -2 Jahre liegt. (Also 2016-2018).
Mit dieser Einschränkung kommt man für die genannte Zeitschrift auf 85 Titel, ohne diese Einschränkung wären es 123.

Das wurde 2017 eingeführt, siehe auch: ubtue/ixTheo#463

**Comment by IxTheoKm** [comment]
Danke für die Erklärung! Das hat mein Gedächtnis nicht mehr hergegeben.
Eine Frage zur Diskussion an die Referenten füge ich in 463 ein.
