### ISSUE TITLE
Volltextsuche in Literaturverzeichnissen

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#2102]
Im LV dieses Datensatzes: https://ixtheo.de/Search2Record/173359339X
kommt der Ausdruck "national council of churches" vor. Wenn man im pdf des LV sucht wird das auch gefunden.

Allerdings findet man das nicht in der Volltextsuche:
https://ixtheo.de/Search2/Results?lookfor=%22national+council+of+churches%22&type=FulltextOnly&filter%5B%5D=fulltext_types%3A%22List+of+References%22&hiddenFilters%5B%5D=has_fulltext%3A1&limit=20&botprotect=
<img width="1175" alt="Bildschirmfoto 2022-05-11 um 14 42 24" src="https://user-images.githubusercontent.com/14169098/167852424-37435838-a872-4002-93f2-f93aef81b165.png">

**Comment by jriedl** [comment]
https://ptah.ub.uni-tuebingen.de/Search2/Results?lookfor=%22national+council+of+churches%22&type=FulltextOnly&filter%5B%5D=fulltext_types%3A%22List+of+References%22&hiddenFilters%5B%5D=has_fulltext%3A1&limit=20&botprotect=

**Comment by thefass** [comment]
auf ptah und ixtheo ok
