### ISSUE TITLE
Normdaten: Anzeige der Berufe bzw. Funktionsbezeichnungen

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#2107]
Aufgefallen über den Wunsch einer Theologin, ihren GND-Satz grundlegend zu korrigieren (u.a. Löschung der Beziehung zur Organisation, Löschung von "Ordensschwester" und "Autorin", Korrektur anderer Informationen):

https://ixtheo.de/Authority/815326920

### Werden die Berufe/Funktionsbezeichnungen in alphabetischer Reihenfolge angezeigt?

![Reisinger](https://user-images.githubusercontent.com/17004223/167867075-fd715970-632a-4e25-8b6f-e820a9d670b3.JPG)

Im GND-Satz wird normalerweise eine Bezeichnung an erster Position als **charakteristische/r Funktion/Beruf** mit **$4berc** hervorgehoben (in diesem Satz derzeit im GND-Satz noch hinter einem Beruf mit $4beru positioniert; das muss korrigiert werden).
Korrekte Reihenfolge im GND-Satz:

550 $0(DE-627)104535318$0(DE-576)209684437$0(DE-588)4138249-3$a**Theologin** **$4berc** $wr$iCharakteristischer Beruf
550 $0(DE-627)105373451$0(DE-576)209955937$0(DE-588)4174285-0$aPhilosophin$4beru$wr$iBeruf
550 $0(DE-627)104661348$0(DE-576)210574526$0(DE-588)4258697-5$aAutorin$4beru$wr$iBeruf
550 $0(DE-627)234602767$0(DE-576)21276439X$0(DE-588)4469951-7$aOrdensschwester$4beru$wr$iBeruf$9Z:**bis 2011**

### 2. Wird die zeitliche Gültigkeit $Z bewusst nicht angezeigt? Die Information ist doch z.T. durchaus wichtig. 
(Diese Zeile soll im Datensatz auf Wunsch der Autorin zwar vollständig gelöscht werden, ist aber in anderen Fällen relevant.)

**Comment by IxTheoKm** [comment]
Weitere Beispiele, bei denen die charakteristischen Berufe an letzter Stelle stehen:

https://ixtheo.de/Authority/13346704X 
Kafka, Franz: Jurist / Librettist / Schriftsteller

https://ixtheo.de/Authority/061939080
Küng, Hans: Hochschullehrer / Katholischer Theologe / Priester / Theologe

**Comment by mtrojan-ub** [comment]
Es wird zwar nicht bewusst umsortiert, aber in Java wird ein Datentyp verwendet der aus Performancegründen nicht auf die Sortierung achtet.

@andreas-ub kannst Du das bitte umstellen und statt Set<String> einen passenden Datentyp verwenden?

**Comment by mtrojan-ub** [comment]
Änderung auf ptah, greift nach dem nächsten Import (also ab morgen Vormittag), bitte danach ausprobieren - ready for testing!

**Comment by IxTheoKm** [comment]
Die Reihenfolge stimmt nun, danke.

Bitte in **550** noch die Zeitangaben von **$9Z** anzeigen:

https://ptah.ub.uni-tuebingen.de/Authority/324757344

Papst / Katholischer Theologe / Erzbischof / Kardinal --->
Papst (2005-2013) / Katholischer Theologe / Erzbischof (1977-1982) / Kardinal (1977)

**Comment by mtrojan-ub** [comment]
Die Zeitangaben wurden mit aufgenommen. Außerdem wurden die Übersetzungen verbessert. Bitte nochmal testen.

**Comment by IxTheoKm** [comment]
Zeitangaben sind jetzt okay, danke.
