### ISSUE TITLE
GND / ORCID Nummer anzeigen

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#2112]
Auf der Personenseite wird unter der Rubrik "Biographische Referenzen" ein Link auf GND und Orcid angeboten.
https://www.ixtheo.de/Authority/081707754

Bitte die entsprechende Nummer auch mit anzeigen:

GND (122054482)
ORCID (0000-0002-2672-4387)

**Comment by mtrojan-ub** [comment]
Soll das auch für die anderen Referenzen gelten die an dieser Stelle angezeigt werden? (insb. ISNI, LOC, VIAF, Wikidata?)

**Comment by obrandt** [comment]
Alter Tischlerspruch: Mein Bruder, den Splitter im Auge des IxTheo siehst du, den Balken in deinem Auge aber nicht (veralteter GND-Eintrag, nicht existente Webseite der Uni MS) ;-) Man könnte sich fragen, ob das nicht Overengineering ist?

**Comment by thefass** [comment]
> Soll das auch für die anderen Referenzen gelten die an dieser Stelle angezeigt werden? (insb. ISNI, LOC, VIAF, Wikidata?)

ja, auf jeden Fall. Ich hatte nur nicht mehr auf dem Schirm, was wir da alles so haben

**Comment by thefass** [comment]
> (veralteter GND-Eintrag, nicht existente Webseite der Uni MS

Deswegen gibt es ja die Personenseiten auf unseren VuFind Systemen. Ich bin sicherlich nicht der Einzige, der mehrmals in seinem Leben virtuell gelöscht wurde. Nach ein paar Jahren wird man nicht mal mehr als "Ehemaliger" geführt.

**Comment by obrandt** [comment]
Aus der Bibel habe ich es auch, nicht von der Baustelle ;-)
Aber mein Punkt war auch, dass wir kein Overengineering unserer Systeme für unsere Nutzer machen sollten. Im Ergebnis wird es dadurch für sie nur unübersichtlicher. Ganz im Steve Jobs Sinne: die Vereinfachung der Systeme ist die Kunst! :-)

**Comment by mtrojan-ub** [comment]
War ja vor der Diskussion im letzten Meeting bereits umgesetzt, siehe:
https://ptah.ub.uni-tuebingen.de/Authority/081707754

=> ready for testing

**Comment by thefass** [comment]
sieht gut aus. Danke
