### ISSUE TITLE
Normdaten: Anzeige Person als Körperschaft im Bezugsfeld der Person unvollständig

### ISSUE THREAD

**Issue by IxGe** [ubtue/tuefind#2115]
Beispiel : https://www.ixtheo.de/Authority/324757344

![Benedikt1](https://user-images.githubusercontent.com/17196047/168027713-370e31f2-08fb-41a1-9b4b-6bee793a1997.PNG)

Hier müsste korrekt stehen
**Katholische Kirche. Papst (2005-2013 : Benedikt XVI.)
Katholische Kirche. Erzdiözese München und Freising. Erzbischof (1977-1982 : Ratzinger)**

es fehlen also die Abschnitte $b

510 2 $0(DE-627)867965266$0(DE-576)477159931$0(DE-588)1113905956$aKatholische Kirche**$bPapst**$g2005-2013 : Benedikt XVI.$4vbal$wr$iVerwandter Begriff$eVerwandter Begriff
510 2 $0(DE-627)1676299203$0(DE-588)1194330266$aKatholische Kirche**$bErzdiözese München und Freising$bErzbischof**$g1977-1982 : Ratzinger$4vbal$wr$iVerwandter Begriff$eVerwandter Begriff[Katholische Kirche (2005-2013 : Benedikt XVI.)]

**Comment by mtrojan-ub** [comment]
Ready for testing auf ptah

**Comment by IxGe** [comment]
sieht gut aus. Danke
