### ISSUE TITLE
Feed Aggregator RelBib - dreifacher Email Alert an einem Tag

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#2118]
Der von mir eingerichtete Email Alert der Feeds auf RelBib kam gestern um 23.45 dreimal an

<img width="780" alt="Bildschirmfoto 2022-05-13 um 09 39 44" src="https://user-images.githubusercontent.com/14169098/168235367-9673c2da-b0e9-4072-b1d7-5a359af598ae.png">

Dabei waren in den ersten beiden Mails die Feeds identisch, allerdings teilweise in unterschiedlicher Reihenfolge.
<img width="1034" alt="Bildschirmfoto 2022-05-13 um 09 38 29" src="https://user-images.githubusercontent.com/14169098/168235659-fc5d141d-2a36-4e31-8643-76fdb84776c8.png">
****
<img width="1039" alt="Bildschirmfoto 2022-05-13 um 09 38 52" src="https://user-images.githubusercontent.com/14169098/168235728-c0ba2ea1-f266-4ed8-8403-a9dc441d4a53.png">

In der letzten Mail waren nur zwei Feeds, die allerdings auch in den ersten beiden enthalten waren.
Ich gehe von einem Bug aus
<img width="1036" alt="Bildschirmfoto 2022-05-13 um 09 39 06" src="https://user-images.githubusercontent.com/14169098/168235584-976809f6-e165-46b7-8a17-49e74fdc7e2c.png">

**Comment by mtrojan-ub** [comment]
Wie telefonisch besprochen: 2 dieser Mails stammen von ptah und eine von ub16. Wir prüfen nun in erster Linie, wieso alle Mails mit "RelBib" und nicht mit "IxTheo" genannt wurden.

**Comment by mtrojan-ub** [comment]
Aktuelle Vermutung:
Es gibt 2 verschiedene cronjobs, und RelBib wird zuerst ausgeführt. Da hier aber nicht nach Benutzern gefiltert wird, verschickt der RelBib-Cronjob die Mails für IxTheo mit und der IxTheo-cronjob hat dann nichts mehr zu tun. Somit sind die gelisteten Artikel zwar korrekt, aber Betreff usw. ist aktuell immer RelBib.

Wir arbeiten an einem Bugfix.

**Comment by mtrojan-ub** [comment]
Ready for Testing auf ptah. Der Hotfix wurde auch bereits auf ub16 eingespielt.

**Comment by thefass** [comment]
scheint gelöst. ich warte nun noch den Alert über das live System heute Nacht ab, und gebe dann hier Bescheid

**Comment by thefass** [comment]
Es kamen am 13.5. 23.50 drei Alerts an:
IxTheo live, IxTheo Ptah, RelBib Ptah
Texte / Betreff / Von stimmen
Issue ist damit ok
