### ISSUE TITLE
Links öffnen nicht in eigenem Tab

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#2121]
Das Anklicken eines externen Links wurde doch bisher immer in einem neuen Tab geöffnet. Fand ich auch sehr sinnvoll. Geht aber jetzt nicht mehr:
Beispiel: https://www.ixtheo.de/Record/79213091X

Hier gibt es drei Libks in der Kategorie: Online Zugang

**Comment by thefass** [comment]
sorry, in der obigen Volltitelanzeige öffnet sich ein neuer Tab.
Nicht aber in der Kurztitelanzeige (Klick auf Volltext):
https://www.ixtheo.de/Search/Results?limit=50&lookfor=numistral+NOT+id%3A898345901&type=AllFields&sort=title&botprotect=

**Comment by mtrojan-ub** [comment]
Die Aussage stimmt nicht ganz. Beide Links haben den gleichen HTML Quellcode. D.h. wenn Du die beiden Links in umgekehrter Reihenfolge öffnest, dann wird auch der erste einen neuen Tab öffnen und der zweite den Tab wiederverwenden.

Wir können das Verhalten an die anderen Links angleichen, indem wir von `target="new"` auf `target="_blank"` umstellen, so dass jedes Mal ein neuer Tab aufgeht und dieser nicht wiederverwendet wird.

**Comment by mtrojan-ub** [comment]
ready for testing auf ptah

**Comment by thefass** [comment]
ja, das ist sinnvoll und funktioniert
