### ISSUE TITLE
VuFind 8: GND / ORCID nicht mehr verlinkt

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#2124]
Hier scheint die Verlinkung von GND und ORCID weggefallen zu sein:
![grafik](https://user-images.githubusercontent.com/25769591/168580273-ad98014e-3a21-48b7-af53-2a9db93bb546.png)
https://134.2.67.9/Authority/684197855

**Comment by relhei** [comment]
Ja, Problem besteht nach wie vor. Habe in Firefox die neueste Chronik gelöscht, Browser neu gestartet.

**Comment by mtrojan-ub** [comment]
https://134.2.67.9/Authority/684197855

Bei mir sieht der Datensatz so aus:
![grafik](https://user-images.githubusercontent.com/26873381/169785811-9a1f3e11-5391-4a46-bc4e-7916f21062fa.png)

GND+ORCID vorhanden. Falls es noch auftritt => Kannst Du es mir bitte mal bei Gelegenheit bei Dir auf der Maschine zeigen? (z.B. entweder per Zoom oder ich komme kurz vorbei)

**Comment by mtrojan-ub** [comment]
Eben per VC besprochen => sah nach einem JavaScript-Problem aus. Es war nach Laden der Seite kurz da, flackerte kurz und dann waren die ersten beiden Links wieder weg.

**Comment by mtrojan-ub** [comment]
Interessant wäre auch ob sich etwas an dem JavaScript-Verhalten ändert, wenn wir die Änderungen zu #2130 vornehmen.

**Comment by mtrojan-ub** [comment]
Wir haben es eben an @relhei's Rechner zusammen angeschaut. Dort ist ein Browserplugin namens **Tampermonkey** aktiv, in dem ein Skript-Plugin ausgeführt wird. Es handelt sich um das **Unterstützungstool für Fachreferatsarbeit** das angeblich an der UB Mannheim gepflegt wird.

@socheres: Weißt Du, ob das Tool bereits solche GND/ORCID-Links auswertet? Es sieht im Moment danach aus, als ob das Plugin zu dem im Issue genannten Problem führt.

**Comment by relhei** [comment]
Ist geklärt: Für zukünftige Tests wird empfohlen, Plug-ins zu deaktivieren.
