### ISSUE TITLE
VuFind 8: "Titel vorschlagen" führt zu Fehlerseite

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#2125]
Klick auf "Titel vorschlagen" führt auf diese Fehlerseite:
![grafik](https://user-images.githubusercontent.com/25769591/168581292-f181e18f-e4d8-4179-b599-fc433fcee8ad.png)

https://134.2.67.9/Feedback/Form/AcquisitionRequest

**Comment by mtrojan-ub** [comment]
Ist behoben, ready for testing auf ptah+sobek.

**Comment by relhei** [comment]
Passt auf ptah - danke!
Bitte sobek testen und schließen, @KStelzel @JMeister01

**Comment by JMeister01** [comment]
Funktioniert, danke!
