### ISSUE TITLE
VuFind 8: Personenseiten - Anzeige von "Beziehungen zu Organisationen" unvollständig

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#2126]
In der Zeile "Beziehungen zu Organisationen" wird nicht mehr das Unterfeld 510 $b ausgewertet. In diesem Fall müsste in Klammern eigentlich noch stehen: Religionswissenschaftliches Institut
![grafik](https://user-images.githubusercontent.com/25769591/168582294-4418f268-ada1-4344-bc16-b4017ad27a68.png)

https://134.2.67.9/Authority/684197855

**Comment by IxTheoKm** [comment]
Siehe auch https://github.com/ubtue/tuefind/issues/2113

**Comment by mtrojan-ub** [comment]
Ist behoben! => Ready for testing auf ptah+sobek

**Comment by relhei** [comment]
Sieht gut aus auf ptah - danke!
Bitte noch auf sobek testen und dann schließen. @KStelzel @JMeister01

**Comment by IxTheoKm** [comment]
In https://sobek.ub.uni-tuebingen.de/Authority/1808545788 wird $b korrekt angezeigt:

![krim](https://github.com/ubtue/tuefind/assets/17004223/604703d3-0ec4-435e-a644-97055c648192)

Ich schließe daher.
