### ISSUE TITLE
Links zu externen Datenbanken sollen Favicons verwenden

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#2130]
Wie heute in der FID-Runde besprochen. Gilt insbesondere für "Biografische Referenzen", aber potenziell auch für "Archivmaterial".

Beispiel:
https://134.2.67.9/Authority/198371527

![grafik](https://user-images.githubusercontent.com/26873381/168621407-fe9edd0a-71de-4a6b-b6dd-c7ec65dbdbba.png)

(Das könnte aus HTML/CSS-Sicht ähnlich gelöst werden wie bei den RSS-Einträgen:)
![grafik](https://user-images.githubusercontent.com/26873381/168621897-4e868199-f210-4345-8ffc-df6e2e6db5d3.png) 
![grafik](https://user-images.githubusercontent.com/26873381/168622208-e8d7a627-fd40-47df-841a-6d3fc7b80fc8.png)

Im Fall von ORCID ist es sogar verboten, Links OHNE icon anzuzeigen:
https://info.orcid.org/brand-guidelines/#orcid-logos-and-icons
`We do not currently allow references to authorized ORCID iDs without using the iD icon.`

**Comment by mtrojan-ub** [comment]
Ready for testing, ggf. durch @thefass?

**Comment by mtrojan-ub** [comment]
Frage dazu: Beim GND Link wird aktuell das DNB Logo angezeigt, weil wir auf die DNB Seite verlinken.
Oder soll hier das GND Logo angezeigt werden?
https://de.wikipedia.org/wiki/Gemeinsame_Normdatei

**Comment by mtrojan-ub** [comment]
Logo wurde angepasst

**Comment by thefass** [comment]
ok
