### ISSUE TITLE
Upload request permission

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#2132]
Es sollte verhindert werden, dass man einen zweiten request absetzt, wenn man schon seine Person authorisiert hat.
Momentan ist das wohl noch möglich, obwohl zwischendurch eine Fehlermeldung kommt. Habe das bei folgendem Autorensatz ausprobiert:

<img width="831" alt="Bildschirmfoto 2022-05-16 um 21 55 31" src="https://user-images.githubusercontent.com/14169098/168672342-03146ab1-052b-4fcc-8925-0d0e62daaf20.png">

das füht dann zu folgender Fehlermeldung:
<img width="676" alt="Bildschirmfoto 2022-05-16 um 21 55 44" src="https://user-images.githubusercontent.com/14169098/168672428-cd5f8471-9fb9-4bc8-b1ea-a23d9ef8d8e6.png">

Schlussendlich wird einem aber das angezeigt:
<img width="824" alt="Bildschirmfoto 2022-05-16 um 21 55 58" src="https://user-images.githubusercontent.com/14169098/168672539-5d07176c-f7e6-4899-8ea2-4b591303b568.png">

Eine Mail ist bei mir aber nicht angekommen

**Comment by mtrojan-ub** [comment]
Es ist erlaubtes bzw. gewünschtes Verhalten, dass man von einem Benutzeraccount aus Zugriff auf mehrere Normdatensätze beantragen kann. (Falls nicht sollten wir nochmal in einem Meeting darüber sprechen).

**Comment by mtrojan-ub** [comment]
In einem der letzten Regelmeetings wurde besprochen, dass wir das Einreichen so limitieren dass es nur für 1 Person möglich ist. Dies sollte Softwareseitig umgesetzt werden, wobei die Datenbankstruktur theoretisch mehrere zulässt. 

Die Software-Anpassung wurde eigentlich schon durchgeführt, allerdings hat @thefass am 22.11. gemeldet dass es angeblich immer noch möglich ist, mehrere Requests abzusetzen.

=> Back to IT

**Comment by mtrojan-ub** [comment]
@thefass: Wir können das nicht reproduzieren. Ich habe auf ptah ebenfalls nach wie vor noch Rechte auf 2 Einträge:

![grafik](https://user-images.githubusercontent.com/26873381/203495670-fc3635d1-192f-40c4-aa11-189d7cd80f16.png)

Wenn ich nun auf einen weiteren Normdatensatz gehe, dann wird mir der "Request Access Rights" Button nicht angezeigt, sondern folgender Text:

![grafik](https://user-images.githubusercontent.com/26873381/203495783-b5c8bbe2-42a1-4d9d-b1fb-1d34977fd3bf.png)

Ich kann also keinen neuen Vorgang starten um noch weitere Rechte zu beantragen. Wie genau hast Du es denn gemacht?

**Comment by thefass** [comment]
Hat was mit dem Zeitpunkt des Loggins zu tun. Wurde gerade telefonisch mit @mtrojan-ub besprochen

**Comment by mtrojan-ub** [comment]
Beschreibung: Wenn man nicht eingeloggt ist wird der button trotzdem angezeigt. Klickt man darauf, so muss man sich erst einloggen, kann dann aber Rechte beantragen obwohl man bereits Rechte hat. Wir können es jetzt reproduzieren.

**Comment by mtrojan-ub** [comment]
@thefass: Wir haben es behoben, kannst Du es bitte nochmal testen?

**Comment by mtrojan-ub** [comment]
Gestern im Meeting besprochen: Funktioniert jetzt, ich schließe.
