### ISSUE TITLE
Upload Hinweis auf pdf

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#2133]
Wenn man eine word DAtei hochlädt, kommt eine Fehlermeldung:
<img width="664" alt="Bildschirmfoto 2022-05-16 um 22 06 07" src="https://user-images.githubusercontent.com/14169098/168673704-04b0cb13-d7a6-48ef-aeae-fb9d5d7a9254.png">
Hier sollte der Hinweis stehen, dass man nur pdf hochladen kann

++++
darauf könnte auch schon an dieser Stelle hingewiesen werden
<img width="329" alt="Bildschirmfoto 2022-05-16 um 22 06 17" src="https://user-images.githubusercontent.com/14169098/168674199-30940b6c-6808-4931-8241-b826ca3a0124.png">

**Comment by mtrojan-ub** [comment]
Wurde eingebaut, siehe ptah. Gibt es genauere Anforderungen zum Wortlaut oder Layout?

**Comment by mtrojan-ub** [comment]
wurde geändert, bitte nochmal testen

**Comment by thefass** [comment]
ist ok
