### ISSUE TITLE
VuFind 8: Time out beim Herunterladen, Drucken von Ergebnislisten bei Suche

### ISSUE THREAD

**Issue by RelBibRetroKat** [ubtue/tuefind#2144]
z.B Exportliste 500 PPN

**Comment by mtrojan-ub** [comment]
Ist reproduzierbar. Das hatten wir früher schonmal, siehe auch: #638
Normalerweise liegt das an der Server-Konfiguration. Evtl ist es durch den Umzug von CentOS auf Ubuntu wieder aufgetaucht (da geänderte Serverumgebung / Konfiguration) und hängt weniger mit VuFind 8 zusammen. Ich schau's mir mal genauer an.

![grafik](https://user-images.githubusercontent.com/26873381/169524634-4b924310-b12f-471e-b915-de22f249074a.png)

**Comment by mtrojan-ub** [comment]
Scheint jedenfalls nicht die selbe Ursache wie beim letzten Mal zu sein (LimitRequestLine ist auf ptah definitiv höher als die Länge der Anfrage.)

**Comment by mtrojan-ub** [comment]
Problem behoben => ready for testing auf ptah.

Hinweis zur Lösung: Auf ub16 ist das Problem nicht aufgetreten. Die Direktive LimitRequestLine war zwar auch hier aktiv, allerdings an einer anderen Stelle (VOR den VirtualHosts).

**Comment by RelBibRetroKat** [comment]
Getestet. Funktioniert.
