### ISSUE TITLE
VuFind 8: Ergebnisse Suche ohne Feld "Andere Suchmöglichkeiten" 

### ISSUE THREAD

**Issue by RelBibRetroKat** [ubtue/tuefind#2145]
Bei den Ergebnisse einer Suche fehlt das auf dem Bild gezeigte Feld "Andere Suchmöglichkeiten"
![VuFind 8_andere Suchmoeglichkeiten](https://user-images.githubusercontent.com/51993589/169325548-95bc1f19-6636-437b-bd12-e03988a72948.png)

**Comment by RelBibRetroKat** [comment]
Auch bei den Ergebnissen einer Suche "Browsen/Nach Verfasser" fehlt bei der Anzeige der Ergebnisse für einen Verfasser dieses Feld
![Uploading VuFind 8_Browsen_Verfasser_andere Suchmöglichkeiten.png…]()

**Comment by RelBibRetroKat** [comment]
Ebenso bei den Ergebnissen einer Suche "Browsen/Alphabetisch/LCC-Klassifikation"

**Comment by mtrojan-ub** [comment]
Zwischenstand: Es handelt sich scheinbar um ein Solr-spezifisches Problem. Der "Spellcheck"-Bereich im Solr-Suchergebnis ist leer. Allerdings ist das auf meiner lokalen Maschine nicht reproduzierbar. Solr-Konfiguration und Plug-Ins sind komplett identisch.

Beispiel ptah:
http://ptah.ub.uni-tuebingen.de:8983/solr/biblio/select?fl=*%2Cscore&lang=en&defType=multiLanguageQueryParser&df=allfields&spellcheck=true&spellcheck.dictionary=basicSpell&wt=json&json.nl=arrarr&rows=0&start=0&spellcheck.q=buddhismus&qf=title_short^750+title_full_unstemmed^600+title_full^400+title^500+title_alt^200+title_new^100+series^50+series2^30+author^300+author_fuller^150+author2^50+contents^10+topic_unstemmed^550+topic_all^500+geographic^300+genre^300+allfields_unstemmed^10+allfields+description+isbn+issn+key_word_chains+key_word_chain_bag&qt=edismax&mm=0%25&hl.fl=0%2Cseries%2Cseries2%2Cauthor%2Cauthor_fuller%2Cauthor2%2Cauthor_additional%2Ccontents%2Ctopic_unstemmed%2Ctopic_all%2Cgeographic%2Cgenre%2Callfields_unstemmed%2Callfields%2Cdescription%2Cisbn%2Cissn%2Ckey_word_chains%2Ckey_word_chain_bag%2Ctitle_short%2Ctitle_full_unstemmed%2Ctitle_full%2Ctitle%2Ctitle_alt%2Ctitle_new&q=buddhismus&fq=-exclude_ixtheo%3Atrue

![grafik](https://user-images.githubusercontent.com/26873381/171808203-5e44f333-f058-4ce4-bb5a-41706affc9b3.png)

Beispiel lokale Entwicklermaschine:
http://mb063.ub.uni-tuebingen.de:8983/solr/biblio/select?fl=*%2Cscore&lang=en&defType=multiLanguageQueryParser&df=allfields&spellcheck=true&spellcheck.dictionary=basicSpell&wt=json&json.nl=arrarr&rows=0&start=0&spellcheck.q=buddhismus&qf=title_short^750+title_full_unstemmed^600+title_full^400+title^500+title_alt^200+title_new^100+series^50+series2^30+author^300+author_fuller^150+author2^50+contents^10+topic_unstemmed^550+topic_all^500+geographic^300+genre^300+allfields_unstemmed^10+allfields+description+isbn+issn+key_word_chains+key_word_chain_bag&qt=edismax&mm=0%25&hl.fl=0%2Cseries%2Cseries2%2Cauthor%2Cauthor_fuller%2Cauthor2%2Cauthor_additional%2Ccontents%2Ctopic_unstemmed%2Ctopic_all%2Cgeographic%2Cgenre%2Callfields_unstemmed%2Callfields%2Cdescription%2Cisbn%2Cissn%2Ckey_word_chains%2Ckey_word_chain_bag%2Ctitle_short%2Ctitle_full_unstemmed%2Ctitle_full%2Ctitle%2Ctitle_alt%2Ctitle_new&q=buddhismus&fq=-exclude_ixtheo%3Atrue

![grafik](https://user-images.githubusercontent.com/26873381/171808275-ce7d66b8-9bb7-49b5-bb87-e03f774ab3bd.png)

**Comment by mtrojan-ub** [comment]
Auch nach dem Upgrade auf dem Produktivsystem scheinen dort die "Anderen Suchmöglichkeiten" in diesem Beispiel immer noch angezeigt zu werden. Es scheint also nicht unmittelbar etwas mit dem VuFind Upgrade zu tun zu haben.

**Comment by mtrojan-ub** [comment]
Das Feld scheint mittlerweile sowohl auf ptah als auch auf ub16 wieder vorhanden zu sein => ready for testing

**Comment by relhei** [comment]
Passt. Danke!
