### ISSUE TITLE
VuFind 8: Zitieren eines gefundenen Titels funktioniert nicht

### ISSUE THREAD

**Issue by RelBibRetroKat** [ubtue/tuefind#2146]
Meldung: Internal Server Error
![VuFind 8_Fehler Zitieren](https://user-images.githubusercontent.com/51993589/169325976-52bc028e-8e58-4726-a86a-4d35ff802dcf.png)

**Comment by relhei** [comment]
Habe mir die Stile anhand eines Beispiels angeschaut (journal article). Urteil insgesamt: Vieles sieht besser aus als vor dem Update!
Hier das Beispiel auf ptah:
![grafik](https://user-images.githubusercontent.com/25769591/171181742-3724e2a1-218f-45cc-a632-a1ca45eec2c9.png)
https://134.2.67.9/Record/1765982553

Folgende Abweichungen sind aufgefallen:
APA Style: Bei diesem Beispiel passt alles, nur vor dem Journal Title fehlt ein Spatium.
Chicago Style: Auch fast perfekt bei diesem Beispiel. Nach dem Aufsatztitel und nach den Seitenzahlen müsste statt eines Punktes ein Komma stehen.
MLA style: Der DOI fehlt. Dieser wird in Kurzform (mit doi.. beginnend) vor dem letzten Punkt mit Komma abgetrennt angegeben.

Hier zum Vergleich derselbe Eintrag auf RelBib:
![grafik](https://user-images.githubusercontent.com/25769591/171182910-1860eb54-7757-4ca7-afb5-6d7f510c83ee.png)
https://www.relbib.de/Record/1765982553

**Comment by mtrojan-ub** [comment]
Wurde angepasst, bitte auf ptah nochmal testen.

**Comment by mtrojan-ub** [comment]
Noch ein Hinweis dazu: VuFind verwendet separate Templates für Artikel und nicht-Artikel, bitte beides separat testen.

**Comment by mtrojan-ub** [comment]
Übrigens haben wir die Themen mit der fehlenden DOI und dem Punkt/Komma auch an VuFind gemeldet, dort wird es voraussichtlich ebenfalls Verbesserungen geben. (Allerdings werden Zitationen im Allgemeinen früher oder später durch CSL abgelöst, und dann müssen wir uns die Stile sowieso nochmal im Einzelnen anschauen).

**Comment by mtrojan-ub** [comment]
Mit den Änderungen in der aktuellen VuFind-Version wurde auch das Verhalten bezüglich der DOI angepasst (das haben wir im Kontext #2321 entdeckt) und kann nochmal getestet werden.

**Comment by relhei** [comment]
Für Aufsätze scheint das Zitieren überwiegend zu passen. Bei Chicago Style müsste nach dem Aufsatztitel und nach den Seitenzahlen statt eines Punktes ein Komma stehen.
![grafik](https://github.com/ubtue/tuefind/assets/25769591/5505ad89-6c33-4731-8e2d-2eab714f89da)
Für andere Medienarten müsste ich noch prüfen, aber das ist aufwändiger.

**Comment by mtrojan-ub** [comment]
Ready for testing auf ptah

**Comment by mtrojan-ub** [comment]
@relhei, wie geht's bei diesem Issue weiter? Kann er geschlossen werden oder gibt es noch weitere Fehlerfälle?

**Comment by mtrojan-ub** [comment]
Wie heute besprochen, Hauptproblem behoben, Verbesserungen gibt es erst im Rahmen von #578 daher schließen wir den Issue.
