### ISSUE TITLE
Suche einschränken nach Schlagwort: Werk doppelt sich

### ISSUE THREAD

**Issue by ja-bre** [ubtue/tuefind#2157]
Problem bestand auch schon vor VuFind8: 

In der "Thema (Schlagwort)"-Liste bei "Suche einschränken" taucht bei jedem Werk-Schlagwort der Urheber bzw. das übergeordnete Werk zweimal auf.

<img width="586" alt="Bildschirmfoto 2022-05-24 um 08 56 39" src="https://user-images.githubusercontent.com/83392048/169968163-c34f6832-7b05-47e1-abf1-09dbce9acd54.png">

![Unbenannt](https://user-images.githubusercontent.com/83392048/169968186-68080d48-8e5c-42d4-a627-5a2c15ade146.png)

**Comment by ja-bre** [comment]
@IxTheoKm Ah, dankeschön! Den Issue hatte ich nicht gesehen.. Dann schließe ich hier?

**Comment by IxTheoKm** [comment]
@ja-bre Ja, ich denke, dieser hier erübrigt sich damit.
