### ISSUE TITLE
VuFind 8: Problem bei Zeitschriften-Volltitelanzeige

### ISSUE THREAD

**Issue by ja-bre** [ubtue/tuefind#2162]
bei den Gesamtaufnahmen einzelner E-Zeitschriften Fehlermeldung: strpos() expects parameter 1 to be string, array given

Beispiel "Stimmen der Zeit" PPN 592068978; "Theologische Zeitschrift" PPN 1742830242

<img width="1427" alt="Bildschirmfoto 2022-05-24 um 10 31 02" src="https://user-images.githubusercontent.com/83392048/169987657-4e9f7b42-ceb5-414a-9d6f-dc915c9a0cf3.png">

**Comment by ja-bre** [comment]
Anzeige jetzt ohne Fehlermeldung möglich!

**Comment by mtrojan-ub** [comment]
Dann bitte den Issue schließen
