### ISSUE TITLE
Kurzanzeige von Personen mit mehreren Funktionen

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#2164]
Für eine Person können in Feld **100** und **700** mehrere Funktionen in **$e $4** vorkommen.
In der Kurzanzeige wird in diesem Fall derzeit jeweils eine abweichende Funktion angezeigt.

### Bitte in der Kurz- und Vollanzeige dieselbe Funktion anzeigen. 
**VerfasserIn / aut** hat dabei Vorrang. 

**Beispiel:**
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=id%3A1032688890&type=AllFields&limit=20&botprotect=
https://ptah.ub.uni-tuebingen.de/Record/1032688890

![Funktion3](https://user-images.githubusercontent.com/17004223/169998474-5ec76073-7476-4c73-9ad8-2f6f0938673d.JPG)

![Funktion](https://user-images.githubusercontent.com/17004223/169998545-b85dcfb6-4e6e-4f8e-9cbe-8cf9644aff11.JPG)

![Funktion4](https://user-images.githubusercontent.com/17004223/169999987-62e1f739-0276-4363-8eb2-9f319650b27c.JPG)

### Weitere Beispiele:
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=id%3A882657585&type=AllFields&limit=20&botprotect=
https://ptah.ub.uni-tuebingen.de/Record/882657585

https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=id%3A1031170855&type=AllFields&limit=20&botprotect=
https://ptah.ub.uni-tuebingen.de/Record/1031170855

Vgl. 
https://github.com/ubtue/tuefind/issues/625
https://github.com/ubtue/tuefind/issues/1325
https://github.com/ubtue/tuefind/issues/625#issuecomment-481253025
https://github.com/ubtue/fid/issues/1

**Comment by mtrojan-ub** [comment]
Ich halte es für ein vufind-org Problem und werde es weitermelden.

Technische Beschreibung:
Wenn ein Autor mit mehreren Rollen auftaucht, so wird er in Solr doppelt eingefügt und später dedupliziert. Bei der Deduplizierung erhält allerdings die "unwichtigere" Rolle den Vorzug.

**Comment by mtrojan-ub** [comment]
Ich habe dafür einen Bugfix geschrieben der schon in VuFind übernommen wurde, es ist im Moment noch unklar in welche Version er konkret einfließen wird.

**Comment by thefass** [comment]
@mtrojan-ub super. Ist das Nr 17 (#2811) auf GitHub?
https://github.com/ubtue/tuefind/wiki/Contributions-to-vufind-org

**Comment by mtrojan-ub** [comment]
Ja genau, der ist auch hier im Issue verlinkt.

**Comment by mtrojan-ub** [comment]
Der Bugfix ist in VuFind 9.0 eingeflossen, das bei uns im Dezember 2023 live gegangen ist. 

In der Kurztitelanzeige werden jetzt beide Rollen angezeigt, allerdings in der Volltitelanzeige keine der beiden. Muss hier noch etwas angepasst werden?

**Comment by thefass** [comment]
Es sollten die Rollen nun auch noch in der Volltitelanzeige angezeigt werden. Dann ist das Issue fertig

**Comment by thefass** [comment]
ja, paßt

**Comment by IxTheoKm** [comment]
>In der Kurztitelanzeige werden jetzt beide Rollen angezeigt, ...

Ist es möglich, dass hier (bewusst?) wieder etwas geändert wurde?

In der Kurzanzeige steht nur die vorrangige Funktion "VerfasserIn":
https://ixtheo.de/Search/Results?lookfor=id%3A1032688890&type=AllFields

In der Vollanzeige stehen beide:
https://ixtheo.de/Record/1032688890

(Ist kein "Auftrag", wirklich nur für mein Verständnis! Ich fände es okay, wenn in der Kurzanzeige nur die Hauptfunktion steht, wüsste nur gerne, ob da wieder etwas verschütt gegangen ist.)

**Comment by mtrojan-ub** [comment]
Den alten Issue hatte ich schon gar nicht mehr im Kopf, aber die Gesamtsituation klingt ja durchaus inkonsistent, so dass wir das nochmal prüfen müssen. Es könnte ggf. sein dass mit der Liveschaltung des neuen IxTheo-Designs bestimmte Template-Anpassungen nicht übernommen wurden.
