### ISSUE TITLE
VuFind 8: Zitieren - Leerzeichen, "pp.", ... fehlt

### ISSUE THREAD

**Issue by ja-bre** [ubtue/tuefind#2172]
Beim Zitieren fehlt beim Chicago-Stil Doppelpunkt und Leerzeichen; bei MLA ein Komma und die Angabe zur Seite "pp."

Beispiel: https://ptah.ub.uni-tuebingen.de/Record/1800243251 

VuFind8:
![Bild2](https://user-images.githubusercontent.com/83392048/170939064-ad80bb09-b351-44da-a3d9-e92947dae448.png)
 

Zuvor: 
![Bild3](https://user-images.githubusercontent.com/83392048/170939164-a34868f4-d955-441f-a868-6a8d90dc3569.png)

**Comment by mtrojan-ub** [comment]
Ausgabe wurde angepasst, bitte nochmal auf ptah ausprobieren

**Comment by ja-bre** [comment]
sieht gut aus auf ptah; ich schließe als abgeschlossen..
