### ISSUE TITLE
VuFind 8: PDF beim IxTheo A-Z nicht hinterlegt

### ISSUE THREAD

**Issue by ja-bre** [ubtue/tuefind#2179]
Beim IxTheo A-Z sind die PDF-Dokumente mit den entsprechenden Erläuterungen noch nicht hinterlegt.

<img width="823" alt="Bildschirmfoto 2022-05-31 um 10 03 26" src="https://user-images.githubusercontent.com/83392048/171123747-3712073a-adaf-491b-9fc8-3ed1f2ec10bf.png">

**Comment by mtrojan-ub** [comment]
wurde behoben, ready for testing auf ptah

**Comment by ja-bre** [comment]
die "IxTheo Klassifikation"en fehlen noch (in HTML); PDFs sind alle vorhanden

**Comment by ja-bre** [comment]
Jetzt werden auch die Klassifikationen korrekt angezeigt; ich schließe als abgeschlossen!
