### ISSUE TITLE
VuFind 8: Volltextsuche ohne Snippets und anderes

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#2186]
Folgende Abweichungen sind bei der Prüfung der Volltextsuche aufgefallen.
Hier Suche mit dem Begriff "Religiosität" unter der Bedingung "Volltext + mehrsprachige Synonyme" in beiden Systemen:
ptah:
![grafik](https://user-images.githubusercontent.com/25769591/171178819-f3650479-2b18-4ac6-9897-0836dbb8d2b0.png)
https://134.2.67.9/Search2/Results?lookfor=Religiosit%C3%A4t&type=FulltextAllSynonyms&hiddenFilters%5B%5D=has_fulltext%3A1&limit=20&botprotect=
RelBib:
![grafik](https://user-images.githubusercontent.com/25769591/171178941-ae72bf6e-c652-4211-9d20-5dd5157a9940.png)
https://www.relbib.de/Search2/Results?lookfor=Religiosit%C3%A4t&type=FulltextAllSynonyms&hiddenFilters%5B%5D=has_fulltext%3A1&limit=20&botprotect=

1. Das Ergebnis weicht numerisch leicht ab. 
2. Snippets fehlen auf ptah. 
3. Die blue box ("Andere Suchmöglichkeiten") fehlt auf ptah). S. a. #2145
4. Bei Einschränkung des Suchergebnisses unter gleichen Bedingungen (Volltextart: Zusammenfassung) weichen die Treffermengen deutlich voneinander ab:

ptah:
https://134.2.67.9/Search2/Results?hiddenFilters%5B%5D=has_fulltext%3A%221%22&lookfor=Religiosit%C3%A4t&type=FulltextAllSynonyms&filter%5B%5D=fulltext_types%3A%22Summary%22
RelBib:
https://www.relbib.de/Search2/Results?hiddenFilters%5B%5D=has_fulltext%3A%221%22&lookfor=Religiosit%C3%A4t&type=FulltextAllSynonyms&filter%5B%5D=fulltext_types%3A%22Summary%22

Desweiteren ist aufgefallen - aber in beiden Systemen - dass die Treffermengen sich nicht verändern, wenn man den Suchaspekt verändert. D.h. konkret, bei der o.g. Suche ergibt die Einschränkung auf "Volltexte ohne Synonyme", "Volltexte + Synonyme", "Volltexte + mehrsprachige Synonyme" jweils dieselbe Treffermenge. Auch für andere Suchbegriffe wurde das getestet. Funktioniert da elles richtig? Das scheint mir nicht so wie gewollt zu sein...

**Comment by jriedl** [comment]
Snippets werden angezeigt, Synonyme und mehrsprachige Synonyme verändern die Treffermenge (Achtung: wenn als Sprache z.B. Englisch eingestellt ist, ändert "Fulltext + Synonyms" die Ergebnismenge nicht, da es kein Englisches Synonym für "Religiosität" gibt.)
