### ISSUE TITLE
VuFind 8: Bandangabe in Feld "Schriftenreihe/Zeitschrift" unvollständig

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#2190]
Auf ptah bricht Angabe des Bandes bei Schriftenreihen in Feld "Schriftenreihe/Zeitschrift" vorzeitig ab:

![grafik](https://user-images.githubusercontent.com/25769591/171190822-4169eb3f-cc53-471d-98a0-8b0d78a1781f.png)
https://134.2.67.9/Record/1641845813

Korrekt auf RelBib:
![grafik](https://user-images.githubusercontent.com/25769591/171191294-3ea5d0a7-dd0e-42e2-a1b2-f4e310310e66.png)
https://www.relbib.de/Record/1641845813

Kein Einzelfall.

**Comment by coeh** [comment]
Das Problem tritt auf IxTheo ebenfalls auf. Hier ein Beispiel für die abbrechende Anzeige auf ptah:
![grafik](https://user-images.githubusercontent.com/83448862/171192566-a385d1b2-002e-48d2-9717-09ea31246f1c.png)
https://ptah.ub.uni-tuebingen.de/Record/600535371

Und hier die korrekte Anzeige im IxTheo:
![grafik](https://user-images.githubusercontent.com/83448862/171192717-97d820d8-79f5-4386-bad1-06908f66a90e.png)
https://ixtheo.de/Record/600535371

**Comment by mtrojan-ub** [comment]
wurde behoben, bitte auf ptah nochmal testen

**Comment by coeh** [comment]
Passt auf IxTheo auch. Danke!
