### ISSUE TITLE
VuFind 8: Fehler bei Volltitelanzeige nach Volltextsuche, wenn eingeloggt

### ISSUE THREAD

**Issue by ja-bre** [ubtue/tuefind#2197]
Leider gerade erst aufgefallen: Wenn man sich mit einem auf ptah angelegten IxTheo-Account einloggt, eine Volltextsuche durchführt und den Titel eines angezeigten Ergebnisses anklickt, um zur Volltitelanzeige zu gelangen, erscheint folgende Fehlermeldung: 

Undefined variable: user

![grafik](https://user-images.githubusercontent.com/83392048/171336659-7d0e6683-b2b7-4b5f-b924-e499cebb4189.png)

**Comment by jriedl** [comment]
Auf ptah behoben.

**Comment by ja-bre** [comment]
Keine Fehlermeldung mehr; ich schließe als abgeschlossen!
