### ISSUE TITLE
IxTheo-Klassifikationen in einzelnen Datensätzen anzeigen

### ISSUE THREAD

**Issue by derclou** [ubtue/tuefind#2208]
Wenn NutzerInnen einen Artikel anklicken und der Datensatz angezeigt wird, können sie zwar die Schlagwörter sehen, die für den Artikel vergeben wurden, aber nicht die IxTheo-Klassifikationen. Diese sind nur im Internformat zu finden, wobei NutzerInnen sie unter einer großen Menge bibliothekarischer Daten suchen müssen. Da die IxTheo-Klassifikationen recherchierbar sind und ein wichtiger Teil unseres Sacherschließungskonzepts sind, sollte man sie leichter sehen können. Wäre es nicht möglich, die IxTheo-Klassifikationen für den Artikel direkt unter den Schlagwörtern aufzulisten? Dabei wäre es wichtig, dass nicht nur die Kürzel angezeigt werden, sondern auch die Namen, z. B. "RG Seelsorge", damit die NutzerInnen gleich sehen können, welche Themen betroffen sind, ohne die einzelnen Kürzel auswendig lernen zu müssen.
Vielen Dank!

**Comment by LysogorAndGmail** [comment]
Auf ptah.

**Comment by thefass** [comment]
Danke! Bitte die Klassifikation noch anklickbar machen, so dass eine Recherche damit ausgelöst wird:

Bsp: HC Neues Testamtent
Link: https://www.ixtheo.de/Search/Results?join=AND&lookfor0%5B%5D=&type0%5B%5D=AllFields&lookfor0%5B%5D=&type0%5B%5D=AllFields&lookfor0%5B%5D=&type0%5B%5D=AllFields&bool0%5B%5D=AND&filter%5B%5D=%7Eixtheo_notation_facet%3A%22HC%22&limit=20&daterange%5B%5D=publishDate&publishDatefrom=&publishDateto=&botprotect=

**Comment by thefass** [comment]
ok

**Comment by obrandt** [comment]
Hallo zusammen,

interessiert das außer uns Bibliothekaren, also unsere wirkliche Nutzergruppe, überhaupt ernsthaft? Hat da jemals jemand danach gefragt? Es könnte ein wenig Overengineering sein, dass das Frontend noch weiter überlädt?

Viele Grüße

Olaf  Brandt

Von: derclou ***@***.***>
Gesendet: Freitag, 3. Juni 2022 09:19
An: ubtue/tuefind ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [ubtue/tuefind] IxTheo-Klassifikationen in einzelnen Datensätzen anzeigen (Issue #2208)


Wenn NutzerInnen einen Artikel anklicken und der Datensatz angezeigt wird, können sie zwar die Schlagwörter sehen, die für den Artikel vergeben wurden, aber nicht die IxTheo-Klassifikationen. Diese sind nur im Internformat zu finden, wobei NutzerInnen sie unter einer großen Menge bibliothekarischer Daten suchen müssen. Da die IxTheo-Klassifikationen recherchierbar sind und ein wichtiger Teil unseres Sacherschließungskonzepts sind, sollte man sie leichter sehen können. Wäre es nicht möglich, die IxTheo-Klassifikationen für den Artikel direkt unter den Schlagwörtern aufzulisten? Dabei wäre es wichtig, dass nicht nur die Kürzel angezeigt werden, sondern auch die Namen, z. B. "RG Seelsorge", damit die NutzerInnen gleich sehen können, welche Themen betroffen sind, ohne die einzelnen Kürzel auswendig lernen zu müssen.
Vielen Dank!

**Comment by derclou** [comment]
Soweit ich weiß, wurde das IxTheo-Klassifikationssystem für die Nutzer entwickelt, nicht für Bibliothekaren. Es bietet Informationen zu den inhaltlichen Themenbereichen an, die in einem Artikel angesprochen werden. Es hilft den Nutzern, Artikel inhaltlich einzuordnen, besonders wenn es sich um Zeitschriften handelt, die wir aus Kapazitätsgründen nicht mit Schlagwörtern erschließen können. Als diese Information noch im internen Bereich versteckt war, konnten nur die wenigsten Nutzer ahnen, dass sie vorhanden bzw. zugänglich war.

**Comment by thefass** [comment]
Nur die Reihenfolge sollten wir ändern:
IxTheo Klassifikation (bitte Klassifikation und nicht Notation)
normierte Schlagwort(-folgen)
weitere Schlagwörter

Sonst reißt die Klassifikation die SW Zeilen auseinander
<img width="682" alt="Bildschirmfoto 2022-10-11 um 15 04 20" src="https://user-images.githubusercontent.com/14169098/195098533-02ae904a-8917-4399-8512-50edd71b6afb.png">
