### ISSUE TITLE
Anpassung Impressum

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#2217]
Die Angabe des Rundfunkstaatsvertrags im Impressum aller drei Bibliografien ist veraltet. Hier ist der alte Text:
https://www.relbib.de/Content/Impressum?lng=de#content
![grafik](https://user-images.githubusercontent.com/25769591/173588496-256a316d-6a4b-4edf-963a-48bdcb42e31f.png)

Daher folgender Vorschlag zur Aktualisierung des Textes.

In der ersten Zeile müsste neu an Stelle des RStV erfasst werden:
"Impressum gem. §5 Telemediengesetz und §18 Medienstaatsvertrag (MStV)."

In der letzten Zeile sollte so geändert werden:
"Inhaltlich Verantwortliche für das Informationsangebot der Religionswissenschaftlichen Bibliographie gemäß §18 Abs. 2 MStV"

Passt das so? @thefass @KStelzel 

Dabei ist mir aufgefallen, dass unser Impressum bisher nur auf Deutsch vorhanden ist. Eine Übersetzung ins Englische wäre ein Desiderat.

**Comment by relhei** [comment]
Bitte um kurze Rückmeldung an @thefass und @KStelzel / @JMeister01, ob der Anpassungsvorschlag so passt.

Zwischenzeitlich habe ich mir auch mal die Impressa anderer FID angeschaut, die das zum Teil etwas anders realisiert haben. Hier ein paar Beispiele:
https://fid-move.tib.eu/de/impressum
https://katalog.fid-bbi.de/Content/impressum
https://www.musiconn.de/footermenue/impressum
https://www.fid4sa.de/impressum

Bei den letzten beiden Beispielen wurde komplett auf das Impressum der jeweiligen Bibliothek bzw. Trägerinstitution sowie deren Datenschutzerklärung verlinkt.

**Comment by mtrojan-ub** [comment]
In der FID-Runde besprochen: So umsetzen wie von Mareike vorgeschlagen

**Comment by mtrojan-ub** [comment]
wurde angepasst + kann auf ptah/sobek getestet werden

**Comment by relhei** [comment]
Danke! Gerade sind mir noch zwei Dinge aufgefallen:
1. Wir haben eine neue Rektorin... D. h. "Sie wird durch den Rektor Prof. Dr. Bernd Engler (E-Mail: bernd.engler@uni-tuebingen.de) gesetzlich vertreten." muss entsprechend angepasst werden: "Sie wird durch die Rektorin Prof. Dr. Karla Pollmann (E-Mail: rektorin@uni-tuebingen.de) gesetzlich vertreten."
2. (nur ganz kleine Korrektur) wir schreiben in RelBib "Bibliografie" immer mit "f" - also müsste hier ebenfalls angepasst werden bei "...Religionswissenschaftlichen Bibliographie..."

**Comment by mtrojan-ub** [comment]
Ist geändert. Ich frage mich allerdings, ob man den expliziten Hinweis auf Religionswissenschaftliche Bibliografie an der Stelle überhaupt braucht. Bei IxTheo steht auch ein expliziter Passus mit drin der aber auch für die Derivate genau so angezeigt wird, und bei KrimDok steht nichts in der Hinsicht, also einfach nur `Inhaltlich Verantwortliche für das Informationsangebot gemäß §18 Abs. 2 MStV`

**Comment by relhei** [comment]
Ja, wäre von meiner Seite auch in Ordnung, wenn wir es kurz halten. 
@thefass @KStelzel - was meint ihr?

**Comment by mtrojan-ub** [comment]
Ist es grundsätzlich sinnvoll dass wir uns bei solchen Dingen am Impressum der Uni orientieren, wie bei der Datenschutzseite auch?
https://uni-tuebingen.de/impressum/

Dort wäre allerdings stattdessen auf den `§ 55 RStVG` verwiesen.

**Comment by KStelzel** [comment]
Ich bin auch für kurz und analog zur Uni.

**Comment by thefass** [comment]
> Ja, wäre von meiner Seite auch in Ordnung, wenn wir es kurz halten.
> @thefass @KStelzel - was meint ihr?

ja, ok

**Comment by mtrojan-ub** [comment]
wurde angepasst, siehe ptah / sobek.

Es gibt übrigens auf der Uni-Tübingen Seite auch noch unterhalb des Impressums weitere Abschnitte zu Externen Links, Urheberrecht sowie Haftungsausschluss. Sollen Teile davon ebenfalls übernommen werden?

Falls ja müssten erst noch entsprechende Anpassungen definiert werden (insb. zum Urheberrecht, was sich ja bei Metadaten anders verhält, außerdem müsste da auch auf angezeigte Fremdinhalte wie insb. Wikidata-Bilder eingegangen werden.

**Comment by KStelzel** [comment]
Wenn ich es richtig verstanden habe, steht jetzt oben  § 55 RStVG und unten bei Frau Dörr § 18 Abs. 2 MStV, ja? Dann würde auf Sobek alles passen.
Was weitere Absätze betrifft, bin ich weiterhin grundsätzlich für analog zur Uni. Beim Urheberrecht kennt sich @JMeister01 besser aus als ich.

**Comment by thefass** [comment]
@obrandt Siehst du da noch Anpassungsbedarf, oder können wir das so belassen?

**Comment by relhei** [comment]
Ich wollte noch mal darauf aufmerksam machen, dass die Angaben auf der Uni-Seite veraltet sind, insofern m. E. nur bedingt zur Nachahmung geeignet. Jetzt hat sich bei uns die veraltete Version auch wieder einegschlichen.. Der Rundfunkstaatsvertrag wurde im November 2020 durch den Medienstaatsvertrag abgelöst: https://de.wikipedia.org/wiki/Rundfunkstaatsvertrag. 
Daher muss in der ersten Zeile des Impressums stehen:
"Impressum gem. §5 Telemediengesetz und §18 Medienstaatsvertrag (MStV)."
Aktuell sind beide (alter und neuer Vertrag) in unserem Impressum enthalten:
![grafik](https://github.com/ubtue/tuefind/assets/25769591/8e84b37f-e08b-4dd8-8836-ff5a60df0f2a)
Außerdem hatten wir für den Passus "Inhaltlich Verantwortliche für das Informationsangebot der Religionswissenschaftlichen Bibliografie gemäß §18 Abs. 2 MStV" bereits weiter oben entschieden, dass wir analog zu KrimDok die Kurzdarstellung verwenden, also "Inhaltlich Verantwortliche für das Informationsangebot gemäß §18 Abs. 2 MStV" 
- für RelBib und IxTheo bitte noch anpassen.
Was die anderen, zusätzlichen Passagen im Impressum der Uni anbelangt, würde ich die Empfehlung / Rückmeldung von @obrandt abwarten: Sollten diese auch noch in unsere Impressa aufgenommen werden und falls ja, mit welchen Anpassungen?

**Comment by JMeister01** [comment]
Die Anpassung ist auch in der KrimDok notwendig.

**Comment by mtrojan-ub** [comment]
Wir hatten aber auch mal entschieden dass wir uns bei Impressum und Datenschutzerklärung an der Uni-Website orientieren. Die stimmt mit unseren Webseiten überein. Könnt Ihr das bitte an die Hochschulkommunikation weitergeben?

**Comment by obrandt** [comment]
Ich habe den Änderungswunsch der HK zugesandt und um Rückmeldung gebeten, wenn sie es umgesetzt haben. Dann können wir es analog übernehmen.
