### ISSUE TITLE
Bibelstellen als Sachschlagwörter auf Englisch

### ISSUE THREAD

**Issue by derclou** [ubtue/tuefind#2226]
Wenn man sich die Schlagwörter für einen Artikel auf Englisch anschaut, erscheinen Bibelstellen folgendermaßen: "Einheitsübersetzung der Heiligen Schrift. [Bibelstelle]". Dieses Problem taucht in anderen Sprachen nicht auf.

**Comment by jriedl** [comment]
Das scheint ein Fehler im ursprünglichen Normdatensatz zu sein (PPN 104353740, GND-Nr. 4126864-7). Die Anzeige in der OGND des BSZ zeigt, dass dort ein Feld 730 (mit der Kennzeichnung als IxTheo-Übersetzung) existiert, in dem  "Einheitsübersetzung der Heiligen Schrift" als englische Übersetzung eingetragen ist. 
Nachvollziehbar durch: https://swb.bsz-bw.de/DB=2.104/SET=1/TTL=1/START_WELCOME, dann als Suchaspekt "GND-Nummer [NID]" auswählen und nach der GND-Nummer suchen.

**Comment by derclou** [comment]
> Das scheint ein Fehler im ursprünglichen Normdatensatz zu sein (PPN 104353740, GND-Nr. 4126864-7). Die Anzeige in der OGND des BSZ zeigt, dass dort ein Feld 730 (mit der Kennzeichnung als IxTheo-Übersetzung) existiert, in dem "Einheitsübersetzung der Heiligen Schrift" als englische Übersetzung eingetragen ist. Nachvollziehbar durch: https://swb.bsz-bw.de/DB=2.104/SET=1/TTL=1/START_WELCOME, dann als Suchaspekt "GND-Nummer [NID]" auswählen und nach der GND-Nummer suchen.

Ich verstehe nicht ganz. Wieso wird die Übersetzung für "Bibel" bei allen Bibelstellen-Schlagwörtern im Datensatz für die Einheitsübersetzung (PPN 104353740) und nicht im eigentlichen Datensatz für die Bibel (PPN 106377604) gesucht?

**Comment by jriedl** [comment]
Weil die Übersetzung nicht PPN-basiert, sondern anhand von aus den Normdaten extahierter Übersetzunglisten geschieht. Ansonsten könnten nicht-normierte Schlagwörter gar nicht übersetzt werden. Die einfließenden Unterfelder der deutschen Terme sind aktuell "100abcd:110abcd:111a:130ap:150ax:151a", d.h. 130g fließt nicht in den Ausgangswert ein und damit bleibt der Inhalt von $a. Habe 130g nun der Liste noch hinzugefügt, auf ptah sollte das nach dem nächsten Import voraussichtlich morgen früh sichtbar sein. Die Herkunft der deutschen Begrifflichkeiten in den Feldern der englischen Übersetzungen bleibt hiervon aber natürlich unberührt.

**Comment by jriedl** [comment]
In der OGND sieht der Datensatz folgendermaßen aus:
![image](https://user-images.githubusercontent.com/13135579/176129821-fe3f75ff-8c51-4728-9d6b-79dcca9233a4.png)
Wenn nun aus 130 das Unterfeld g mit extrahiert wird, bedeutet das, dass im Gegensatz zu vorher der Begriff "Bibel" nicht mehr damit übersetzt wird, weil der Ausgangsterm jetzt "Bibel (Einheitsübersetzung)" aus $a und $g und nicht mehr nur "Bibel" aus $a ist. In diesem konkreten Fall sollte die Änderung das Problem also lösen (falls nicht noch weitere Nordmatensätze mit 130 Feldern ins Spiel kommen, die nicht von der zusätzlichen Auswertung von $p und $g abgedeckt sind, aber in $a Bibel stehen haben). Es bleibt aber dabei, dass es offenbar eine Reihe von Fällen in den BSZ-Einspielungen der IxTheo-Übersetzungen gibt, bei denen eine deutsche Terminologie als englische Übersetzung firmiert und dies müsste geklärt/behoben werden.

**Comment by derclou** [comment]
Mein Punkt ist: Das ist der falsche Datensatz! Warum nicht einfach den richtigen Datensatz für die Übersetzung nutzen?

**Comment by jriedl** [comment]
> Weil die Übersetzung nicht PPN-basiert, sondern anhand von aus den Normdaten extahierter Übersetzunglisten geschieht. Ansonsten könnten nicht-normierte Schlagwörter gar nicht übersetzt werden

Es gibt auf der Ebene der Übersetzungen keine PPNs mehr, sondern Lookup-Tabellen Deutsch->Fremdsprache. Weil, wie erläutert, nur 130a der Ausgangsterm war, floss die in 730a gegebene Übersetzung in die Übersetzungen für "Bibel" ein. Dies ist mit der Änderung nicht mehr der Fall (vgl. Erklärung oben), insofern kommt der "falsche Datensatz" nicht mehr zur Anwendung. Dies ist aber unabhängig von den "falschen" Übersetzungen, die als eigenständiges Problem eigenständig adressiert werden müssen.

**Comment by derclou** [comment]
OK. Wenn ich richtig verstanden habe, wurde der Datensatz der Einheitsübersetzung für die Extrahierung der Übersetzung angewendet, weil das Feld $g in 130 beim "Matching" nicht berücksichtigt wurde, so dass dieser Datensatz für den "Bibel"-Datensatz gehalten wurde. Jetzt wird das "Matching"-Verfahren merken, dass dieser Datensatz nicht der richtige ist und hoffentlich weiter suchen, bis es den richtigen findet und daraus die Übersetzung extrahiert. Ich werde es auf ptah überprüfen und später auf ixtheo, und danach das Issue schließen. Vielen Dank!

**Comment by IxTheoKm** [comment]
Wenn ich es richtig in Erinnerung habe, wurden der TITEL "Einheitsübersetzung..." deswegen als "englisches" Pendant gewählt, weil es eben ein deutscher Titel einer Übersetzung ist, die es im Englischen nicht mit eigenem englischen Titel gibt. Wenn es die gäbe, würde dafür der Titel der englischen Übersetzung der deutschen Einheitsübersetzung dort stehen.

**Comment by IxTheoKm** [comment]
Sowas wurde z.B. auch gemacht, wenn nur der Autorenname übersetzt wurde, nicht aber der dazugehörige Titel (Bsp.: "Codex canonum ecclesiarum orientalium"). Früher waren die Ansetzungen mehrgliedrig ("Autor / Titel"), inzwischen sind die Autoren nur verlinkt. Dadurch sehen nun die IxTheo-"Übersetzungen" merkwürdig aus, weil die Übersetzung von "Katholische Kirche" nicht mehr Bestandteil von Feld 730 ist: 

001 210796898
...
110 2 $aKatholische Kirche$4aut1$wr$iVerfasserschaft1$eVerfasserschaft1$t**Codex canonum ecclesiarum orientalium**
410 2 $aKatholische Kirche$4aut1$wr$iVerfasserschaft1$eVerfasserschaft1$t**CCEO**$4abku$wr$iAbkuerzung
510 2 $0(DE-627)101659261$0(DE-576)191644501$0(DE-588)2009545-4$aKatholische Kirche$4aut1$wr$iVerfasserschaft1$eVerfasserschaft1
548 $a1990$4datj$wr$iErscheinungszeit
550 $0(DE-627)104608692$0(DE-576)210042222$0(DE-588)4186892-4$aUnierte Ostkirchen$4them$wr$iThema
550 $0(DE-627)106093029$0(DE-576)209189711$0(DE-588)4073199-6$aKanonisches Recht$4obin$wr$iOberbegriff instantiell
670 $aActa Apostolicae Sedis 83 (1991)
670 $aLThK (3. Aufl.)
678 $bIm Anschluß an CIC/1983 im Jahre 1990 in Kraft gesetztes Kirchenrecht für die Unierten Ostkirchen
730 7$a**Codex canonum ecclesiarum orientalium**$2IxTheo$9L:eng$9Z:AF
730 7$a**CCEO**$2IxTheo$9L:eng$9Z:VW


Teilweise wurden auch die _Ansetzung_sformen nicht übersetzt, sondern erhielten den identischen Titel als englische "Übersetzung". Dazu wurde eine alternative Benennung als weitere Übersetzung erfasst. Bsp.:

001 209762632
...
130 0$a**Codex Sinaiticus**
377 7$agrc$2iso639-2b
380 $0(DE-627)10457187X$0(DE-576)208948376$aHandschrift$2gnd
410 2 $aBritish Library$nMs. Add. 43725
410 2 $aBritish Library$nAdd. Ms. 43725
410 2 $aUniversitätsbibliothek Leipzig$nCod. gr. 1
410 2 $aRossijskaja Nacional'naja Biblioteka, Sankt Petersburg$nGreek 2, 259
410 2 $aRossijskaja Nacionalʹnaja Biblioteka, Sankt Petersburg$nGreek 2, 843
410 2 $aRossijskaja Nacionalʹnaja Biblioteka, Sankt Petersburg$nOLDP-O 156
410 2 $aSinaikloster$bBibliothek$nNew Finds 1
430 0$aKodex Sinaitikus
430 0$aSinaiticus
430 0$aCodex Friderico-Augustanus$9v:Teil UB Leipzig
430 0$aCodex Sinaiticus Petropolitanus$9v:Teil BL
...
730 7$a**Codex Sinaiticus**$2IxTheo$9L:eng$9Z:AF
730 7$a**Alef**$g**Codex**$2IxTheo$9L:eng$9Z:VW

**Comment by jriedl** [comment]
Ist es dann ein gangbarer Ansatz, dass wir einfach mit diesen "Übersetzungen" leben?

**Comment by IxTheoKm** [comment]
@derclou @thefass 
Die Entscheidung sollte auf Referentenebene fallen. Die Übersetzungen ehem. mehrgliedriger Schlagwörter und von manchen Werktiteln sind ja aus den alten Allegro-Strukturen entstanden. Ob sie den aktuellen Anforderungen entsprechen ist vermutlich fraglich. Manches ist evtl. auch nur im Einzelfall zu entscheiden.

**Comment by derclou** [comment]
Statt "Einheitsübersetzung..." steht jetzt "Vetus Latina..." bei den Bibelstellen auf Englisch. Das Problem ist also immer noch nicht gelöst.

**Comment by derclou** [comment]
Auf ptah ist das Problem nicht vorhanden, sondern nur auf die IxTheo-Webseite. Wenn noch keine Änderungen auf die IxTheo-Webseite angekommen sind, verstehe ich nicht, warum jetzt "Vetus Latina" statt "Einheitsübersetzung" dort steht.

**Comment by jriedl** [comment]
> Auf ptah ist das Problem nicht vorhanden, sondern nur auf die IxTheo-Webseite. Wenn noch keine Änderungen auf die IxTheo-Webseite angekommen sind, verstehe ich nicht, warum jetzt "Vetus Latina" statt "Einheitsübersetzung" dort steht.

Das hängt in diesem Fall von der Reihenfolge der Datensätze in den Normdaten ab, die sich durchaus ändern können. Update auf ub16 ist heute erfolgt, sodass die Anpassungen nach Abschluss des nächsten Imports, voraussichtlich morgen früh, sichtbar sein sollten.

**Comment by derclou** [comment]
Problem gelöst. Vielen Dank! Ich schließe das Issue.
