### ISSUE TITLE
Falsch verknüpfte IxTheo-Notationen

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#2228]
https://ixtheo.de/Record/130113212#details

Bei der K10plus-Migration wurde offensichtlich in diesem Fall die alte SWB-PPN 372042961 des Notationssatzes nicht korrekt in die K10plus-PPN 1442042966 umgesetzt:
![AA](https://user-images.githubusercontent.com/17004223/177142271-66f35017-987a-4a91-8e0f-06331af94158.JPG)

PICA: 6700 !372042961!**$7**372042961
MARC: $0936ln0372042961

Sie muss wie folgt lauten:
![grafik](https://user-images.githubusercontent.com/17004223/177142423-bff209ba-ad3d-435f-b73e-ae5caa324bbe.png)

PICA: 6700 !1442042966!AA
MARC: $0936ln$0372042961$aAA

Leider ist das für mich im K10plus nicht recherchierbar, so dass ich nicht feststellen kann, ob es ein Einzelfall ist oder gehäuft vorkommen.

### Kann man feststellen, ob es weitere Datensätze gibt, in denen in LOK 936ln das Unterfeld a fehlt?

**Comment by jriedl** [comment]
`marc_grep GesamtTiteldaten-post-pipeline-220703.mrc 'if "LOK0"=="936ln" extract "LOK"' control_number_and_traditional | grep '\$0936ln' | grep -v '\$a'`:
130113212:LOK:  $0936ln$0372042961
1639163530:LOK:  $0936ln$01550736167
1639645608:LOK:  $0936ln$01442044284
164016846X:LOK:  $0936ln$01550736167
1640169377:LOK:  $0936ln$01550736167
1641090634:LOK:  $0936ln$01550736167
1641121386:LOK:  $0936ln$01550736167
1641222964:LOK:  $0936ln$0104197412
1643424114:LOK:  $0936ln$01550736167
1644716828:LOK:  $0936ln$01550736167
1645034798:LOK:  $0936ln$01550736167
1645486435:LOK:  $0936ln$01550736167
164632577X:LOK:  $0936ln$01550736167
1646456106:LOK:  $0936ln$01442043520
1646655001:LOK:  $0936ln$01550736167
1646975863:LOK:  $0936ln$01550736167
1647060141:LOK:  $0936ln$01550736167
1647310857:LOK:  $0936ln$01550736167
