### ISSUE TITLE
Medienart: Weblog - unnötige Anzeigen im Volltitel

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#223]
Unter Einschränkung auf Medienart Weblog erscheinen bei Auswahl eines Titels die Zeilen "Verfügbarkeit prüfen" und "Subito Bestelldienst", obwohl sie nicht relevant sind für diese Medienart. Außerdem wird das Glocke-Symbol angezeigt - auch das macht keinen Sinn, da wir keine Postings aus Weblogs nachweisen. 
Hier ein Beispiel:
https://relbib.de/Record/494810459
Lässt sich da noch was optimieren an der Anzeige?

**Comment by jriedl** [comment]
Auf ptah werden in der Volltitelanzeige "Verfügbarkeit prüfen" und "Subito" jetzt unterdrückt. Wegen der Abbonierbarkeit. Diese wird angeboten, weil die jeweiligen Records nach den Einträgen in Leader und Feld 008 als unabgeschlossene Reihe gelten. Ein Lösung wäre, im Feld 008 das 9999 an Stelle 11-14 durch die Jahreszahl der jeweiligen Aufnahme zu ersetzen.

**Comment by thefass** [comment]
sieht gut aus.
Abonnierbarkeit: weblogs können eigentlich nicht abonniert werden, da wir sie ja nicht auswerten.
Über Abonnierbarkeit müssen wir nochmal intern nachdenken, was dabei sein soll und was nicht. Ich mache dazu ein Issue auf.

**Comment by relhei** [comment]
Vielen Dank! Da zum Thema "Alerting" ein anderes Issue eröffnet wurde, schließe ich hier.
