### ISSUE TITLE
Verlinkte Nebentitel

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#2230]
Bei diesem Titel sind sehr viele Nebentitel in der Vollanzeige verlinkt. Der Nebentitel "The way" führt dabei zu mehreren Treffern. Das sollte ja eigentlich nicht sein. Was ist denn der Hintergrund für die verlinkten Nebentitel? Muss diese Verlinkung überhaupt angeboten werden?
![grafik](https://user-images.githubusercontent.com/25769591/177571966-a3887139-f3eb-4b3a-ad93-34c774225e1d.png)
https://www.relbib.de/Record/643825339?lng=de

Hier die o.g. Trefferliste:
https://www.relbib.de/Search/Results?lookfor=%22The+way%22&type=Title

**Comment by mtrojan-ub** [comment]
Was bedeutet das für uns genau? Handelt es sich um ein Datenproblem, oder muss die Software angepasst werden? Oder wurde die Frage damit beantwortet und der Issue kann geschlossen werden?

**Comment by relhei** [comment]
Die Verlinkung der Nebentitel muss entfernt werden. Sie macht in doppelter Hinsicht keinen Sinn: Wenn korrekt verlinkt wäre, müsste Klick auf einen (beliebigen) der Nebentitel wieder zu genau dieser Volltitelanzeige führen. > kein Informationsgewinn Hier ist aber zudem "falsch" verlinkt, weil durch Klick auf einen der Nebentitel eine Titelsuche (über die Stichwörter der Nebentitel) ausgelöst wird. Das würden Nutzende aber auch nicht an dieser Stelle erwarten. D. h., bitte Nebentitel aus 246 ohne Verlinkung anzeigen.

**Comment by mtrojan-ub** [comment]
ready for testing auf ptah

**Comment by relhei** [comment]
Passt. Danke!
