### ISSUE TITLE
Übernahme von Autosuggest in den Suchschlitz führt zu keinen Ergebnissen

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#2239]
Bei einer Eingabe von "Proeven" in den Suchschlitz werden die richtigen Titel als autosuggest vorgeschlagen. Wenn man aus der Liste dann einen der Vorschläge in den Suchschlitz übernimmt, bekommt man allerdings die Meldung "Keine Ergebnisse"

<img width="770" alt="Bildschirmfoto 2022-07-19 um 15 19 33" src="https://user-images.githubusercontent.com/14169098/179760739-06c4d324-485d-4695-9e9a-bb51555e912a.png">
<img width="1102" alt="Bildschirmfoto 2022-07-19 um 15 19 41" src="https://user-images.githubusercontent.com/14169098/179760762-21bafdc7-2aec-45d9-8ca9-83e6bbc7df8e.png">

**Comment by thefass** [comment]
Es liegt vermutlich am /
Wenn ich ihn aus der Suchzeile lösche, findet er den Datensatz

<img width="829" alt="Bildschirmfoto 2022-07-19 um 15 24 07" src="https://user-images.githubusercontent.com/14169098/179761322-bf791cea-e33e-4bc6-a758-e268bfad2a9a.png">

**Comment by jriedl** [comment]
Betroffen waren Vorschläge, die einen Slash enthalten, plus noch eine weitere eher seltene Nebenbedingung erfüllen, im konkreten Fall, dass der Titel mit `.` aufhört... `/` wird im Autosuggest künftig grundsätzlich escaped. Aktuelle Version auf ptah.
