### ISSUE TITLE
Virtuelle Tastatur funktioniert nicht

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#224]
Im Firefox Browser gibt es nach Klick auf die virtuelle Tastatur keinerlei Reaktion, es passiert rein gar nichts. Woran kann das liegen?

In Opera und Safari klappt die Tastatur wie gewünscht aus.

Kann jemand bitte den Windows Explorer und Chrome prüfen

**Comment by IxTheoKm** [comment]
Bei mir funktioniert die Tastatur sowohl in Firefox als auch im Internet Explorer.
Ich vermisse nur ein X zum Schließen, oder den Hinweis, dass die Tastatur mit Escape wieder geschlossen werden kann.

**Comment by IxTheoKm** [comment]
Sind weitere virtuelle Tastaturen geplant (Chinesisch, Kyrillisch)? Ich denke an die chinesischen Übersetzungen der Schlagwörter, wenn sie dereinst eingespielt sein werden bzw. die russischen Übersetzungen.

**Comment by Gazeller** [comment]
Ich fände mindestens Kyrillisch, möglichst auch Chinesisch, Japanisch auch von Interesse, mittel-/langfristig gesehen.
Gaby

Von: IxTheoKm <notifications@github.com>
Gesendet: Freitag, 16. März 2018 08:40
An: ubtue/tuefind <tuefind@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [ubtue/tuefind] Virtuelle Tastatur funktioniert nicht (#224)


Sind weitere virtuelle Tastaturen geplant (Chinesisch, Kyrillisch)? Ich denke an die chinesischen Übersetzungen der Schlagwörter, wenn sie dereinst eingespielt sein werden bzw. die russischen Übersetzungen.

**Comment by ruschein** [comment]
@Gazeller @IxTheoKm Warum brauchen Chinesen und Russen virtuelle Tastaturen?  Die können doch auch so ihre Zeichen eingeben.  Ich lerne Japanisch und habe sogar mit einer US-Tastatur (ich verwende keine deutsche Tastatur) keine Probleme japanische Schriftzeichen einzugeben.

**Comment by IxTheoKm** [comment]
Ich bin nur von den angebotenen Sprachen/Schriftzeichen der verschiedenen IxTheo-Oberflächen ausgegangen. Wenn es auch ohne virtuelle Tastaturen geht, umso besser.

**Comment by thefass** [comment]
Die virtuellen Tastaturen brauchen wir in der Tat nur für die biblischen Sprachen.
