### ISSUE TITLE
Fehler bei Auswahl des Suchergebnisses

### ISSUE THREAD

**Issue by NMagin** [ubtue/tuefind#2242]
Wenn ich Suchergebnisse in RelBib anklicke und öffne bekomme ich in einigen Fällen die allgemeine Fehlermeldung "Es ist ein Fehler aufgetreten. Ein Fehler ist aufgetreten. Bitte versuchen Sie es später noch einmal. Bitte kontaktieren Sie ihre Bibliothek für weitere Hilfe". (Doppelung der Fehlermitteilung im Original).
Der Fehler tritt nicht bei allen Suchergebnissen auf, allerdings kann ich (noch) nicht genau sagen, womit er in Verbindung steht. Bei derselben Suche in IxTheo tritt der Fehler nicht auf. 

Konkret habe ich den Fehler bei den folgenden Suchen bemerkt:
https://relbib.de/Search/Results?lookfor=Theologisch-praktische+Quartalschrift+&type=AllFields&limit=50&botprotect=
https://relbib.de/Search/Results?lookfor=Yoga+in+Transformation.+Historical+and+Contemporary+&type=AllFields&limit=50&botprotect=
https://relbib.de/Search/Results?lookfor=Praxisbuch+Interreligi%C3%B6ser+Dialog+Begegnungen+initiieren+und+begleiten&type=AllFields&limit=50&botprotect=
https://relbib.de/Search/Results?lookfor=Religion++Imagination++%C3%84sthetik&type=AllFields&limit=50&botprotect=

**Comment by jriedl** [comment]
Ist derzeit leider bei keinem der oben angegebenen Links reproduzierbar. Waren eventuell zusätzlich noch Einstallungen (Facetten o.ä.) aktiv? Bitte das "High priority"-Flag auch nur in wirklich begründeten Ausnahmefällen verwenden.

**Comment by relhei** [comment]
Bei mir (Firefox) tritt der Fehler ebenso auf, ohne erkennbare Logik dahinter.
Produktivsystem:
![grafik](https://user-images.githubusercontent.com/25769591/180209705-de1f2a58-ecd6-4464-8e05-dbecf8e540da.png)

https://www.relbib.de/Record/1773813889

Testsystem:
![grafik](https://user-images.githubusercontent.com/25769591/180209959-900141b4-8520-46df-bc27-ac45e1601c40.png)

https://134.2.67.9/Record/1773813889

**Comment by jriedl** [comment]
Mit diesem Link ist es reproduzierbar. Das ist offenbar ein Seiteneffekt der Anzeige der IxTheo-Klassifikation in der Volltitelanzeige. Wir arbeiten an einer Lösung.

**Comment by jriedl** [comment]
Behoben auf ptah und ub16

**Comment by obrandt** [comment]
Sind noch irgendwelche Extensions o.ä. aktiv?

Von: jriedl ***@***.***>
Gesendet: Donnerstag, 21. Juli 2022 13:52
An: ubtue/tuefind ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: Re: [ubtue/tuefind] Fehler bei Auswahl des Suchergebnisses (Issue #2242)


Ist derzeit leider bei keinem der oben angegebenen Links reproduzierbar. Waren eventuell zusätzlich noch Einstallungen (Facetten o.ä.) aktiv? Bitte das "High priority"-Flag auch nur in wirklich begründeten Ausnahmefällen verwenden.

**Comment by NMagin** [comment]
Bei mir funktioniert es jetzt auch wieder. Vielen Dank!
