### ISSUE TITLE
Alertingservice

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#226]
Aus meiner Sicht kann der Nutzer momentan zuviel abonnieren, was eigentlich keinen Sinn macht:

1. Datenbanken
https://www.ixtheo.de/Search/Results?type=AllFields&filter%5B%5D=%7Eformat%3A%22Database%22
2. Weblogs
https://www.ixtheo.de/Search/Results?type=AllFields&filter%5B%5D=%7Eformat%3A%22Weblog%22
3. Zeitschriften, die wir gar nicht auswerten
4. Evt: Reihen, die wir nicht kaufen oder über das Bibliographietool die Metadaten beziehen

In all diesen Fällen suggeriert die Glocke, dass man das abonnieren kann. Wenn wir aber nichts auswerten, dann erhält der Nutzer darauf niemals ein Alerting und das frustriert und untergräbt die Zuverlässigkeit des Alerting.

Vielleicht ist es viel sinnvoller, eine Positivliste zu erstellen und nur für diese das Alerting anzubieten.

Meinungen dazu?

**Comment by IxTheoKm** [comment]
Das ist m.E. die Folge der Mischung aus bestandsabhängiger, aktiver Auswertung und dem Anspruch einer umfassenden, bestandsunabhängigen Bibliographie.
Letzteres weckt sicher die Erwartung, dass man sich über alles Aktuelle informieren kann, was der IxTheo _insgesamt_ anbietet. Dem Nutzer ist es egal, aus welcher Quelle die nachgewiesenen Beiträge im IxTheo landen. 
Eine Positivliste ist auf jeden Fall aufwändiger zu pflegen. Zudem sollte man dann m.E. nicht nur die eigenen (einschl. die der Kooperationspartner), aktiv ausgewerteten Zeitschriften erfassen. Manche Zeitschriften werden auch von Nicht-Kooperationspartnern ziemlich regelmäßig ausgewertet. Die sollten mit einbezogen werden. Das setzt aber voraus, dass man sie bemerkt und entspr. beobachtet.
Warum manche Zeitschriften abonniert werden können, manche aber nicht, muss dann sehr genau vermittelt werden.

**Comment by relhei** [comment]
Die Problematik sehe ich auch. Eine Positivliste wäre sicher die bessere Alternative, muss natürlich auch gepflegt / nach Bedarf erweitert werden. Oder lässt sich das u. U. automatisieren bzw. über Abrufzeichen o. ä. einrichten?

**Comment by jriedl** [comment]
Eine Heuristik wäre, zusätzlich zu den bestehenden Kriterien nur solche Einträge abonnierbar zu machen, für die sich aktuell bereits untergeordnete Werke im Datenbestand finden. Damit fallen Blogs und Datenbanken automatisch heraus.

**Comment by obrandt** [comment]
Hallo,

laut Antrag ist sowieso geplant, eine Liste mit abbonierbaren Zeitschriften zu erstellen.
Das sollten wir abwarten.

Viele Grüße

Olaf

Von: jriedl [mailto:notifications@github.com]
Gesendet: Dienstag, 20. März 2018 11:45
An: ubtue/tuefind <tuefind@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [ubtue/tuefind] Alertingservice (#226)


Eine Heuristik wäre, zusätzlich zu den bestehenden Kriterien nur solche Einträge abonnierbar zu machen, für die sich aktuell bereits untergeordnete Werke im Datenbestand finden. Damit fallen Blogs und Datenbanken automatisch heraus.

**Comment by mtrojan-ub** [comment]
Ist das eigentlich die gleiche Thematik wie bei #1521? Dann wäre es ja in der Zwischenzeit bereits gelöst, oder?

**Comment by mtrojan-ub** [comment]
Geschlossen, wie in der FID-Runde besprochen
