### ISSUE TITLE
Seltsames Ergebnis in Volltextsuche

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#2285]
Eine Volltextsuche nach einem String in Hochkommata führt zu zwei Treffern, die ich jedoch weder in der Zusammenfassung noch im Volltext finde. Es gibt auch kein Highlighting des Suchbegriffs in der Kurztitelanzeige.
Suche: "Mk 5,1-13"
https://www.ixtheo.de/Search2/Results?hiddenFilters%5B%5D=has_fulltext%3A%221%22&lookfor=%22Mk+5%2C1-13%22&type=FulltextOnly

<img width="1143" alt="Bildschirmfoto 2022-10-05 um 08 20 27" src="https://user-images.githubusercontent.com/14169098/193994931-85242f0d-28e8-41ce-9426-74d88299bc24.png">

**Comment by jriedl** [comment]
Das sind Grenzfälle, die sich aus dem gewählten gedoppelten Ansatz (Solr + Elasticsearch) and den vorkommenden Sonderzeichen ergeben: Die Ergebnismenge von Solr wird auf der Grundlage der Konvertierung ins Textformat vorgenommen. Was im PDF des Volltextes tatsächlich vorkommt, ist der Ausdruck "Mk 5:1–13" (auf Seite 37). Solr scheint das zu finden, weil auch bei einer Phrasensuche die Sonderzeichen wohl (weg-)normalisiert werden.
Warum Elatisticsearch keinen Treffer zurückliefert, sieht man, wenn man bei der (internen) ES-Anfrage die Anführungszeichen weglässt:
![image](https://user-images.githubusercontent.com/13135579/194047323-b276a3f0-2234-4013-a75e-3828da8b1c8f.png)
D.h. in der HTML-Konvertierung des PDFs enthält die HTML-Entity `&ndash`, hier hat der ursprüngliche Suchausdruck natürlich keine Chance mehr, das zu erkennen.

**Comment by thefass** [comment]
ok, es ist ja dann ein richtiger Treffer, auch wenn man das nicht erkennt
