### ISSUE TITLE
Seltsames Ergebnis in der Volltextsuche_02

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#2286]
Eine Volltextsuche ohne Hochkommata nach Mk 5,1-13 hat an erster Stelle einen Treffer, in dem der Suchbegriff (oder Teile des Suchbegriffs) nicht gehighlighted werden. Obwohl in der Zusammenfassung des Treffers sowohl Mk als auch 13 vorkommen.
https://www.ixtheo.de/Search2/Results?lookfor=Mk+5%2C1-13&type=FulltextOnly&hiddenFilters%5B%5D=has_fulltext%3A1&limit=20&botprotect=

<img width="1153" alt="Bildschirmfoto 2022-10-05 um 08 31 01" src="https://user-images.githubusercontent.com/14169098/193995612-7a3e156e-5c0a-46ea-a856-b06bfee8e745.png">

**Comment by jriedl** [comment]
Aufgrund der fehlenden Anführungszeichen kommen hier wieder die jeweiligen Tokenization und Analyzing-Strategien der einzelnen Systeme (Solr/ES) zum Tragen. Auf Solr-Ebene werden hier Wort-Teile generiert, also offenbar drei unterschiedliche Tokens "Mk", "5,1" und "13", die jeweils irgendwo innerhalb des Dokuments auftauchen können. Offenbar weil es in der Zusammenfassung den Punkt "5.1" gibt, ergibt sich der Titeltreffer.  Wirklich sinnvoll i.e.S. sind die Ergebnisse aber damit eigentlich ohnehin nicht mehr. Für die Abfrage an ES haben wir eine Vorverarbeitungslogik, die in diesem Fall, in "Mk" und "5,1-13" aufteilt (und wahrscheinlich später ES-intern noch einmal in 5,1 und 13, aber scheinbar wird das Komma nicht in exakt der gleichen Weise normalisiert, deshalb wahrscheinlich kein Treffer. 
Ich persönlich würde dringend davon abraten, hier nach Jahren wegen Einzel- und Spezialfällen noch einmal an der Verarbeitungslogik herumzuschrauben, alle diese "Optimierungen" sind uns nach relativ kurzer Zeit wieder auf die Füsse gefallen und im Bezug auf die Volltexte haben wir mittlerweile auch Fälle, in denen die Ausgangstexte ohnehin nicht mehr ohne weiteres zugänglich sind.

**Comment by thefass** [comment]
ok, einverstanden
