### ISSUE TITLE
Normalisation in der Facette Verlag

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#2287]
laut https://github.com/ubtue/ub_tools/blob/master/cpp/data/publisher_normalisation.map
mapt Oxford Univ[.]? Press auf Oxford University Press und de Gruyter auf De Gruyter etc.

Das funktioniert auf ptah, aber noch nicht auf IxTheo. bitte übernehmen.
Auch in die anderen Vufinds und Derivate

**Comment by jriedl** [comment]
Update auf Produktivsystemen hat gestern stattgefunden.

**Comment by thefass** [comment]
funktioniert

**Comment by thefass** [comment]
@jriedl Wo trage ich weitere Normalisationen ein? Direkt in das oben verlinkte Dokument publisher_normalisation.map oder Info an Dich per Mail?

**Comment by jriedl** [comment]
Direktes Editieren dürfte/sollte auf Grund der Zugriffsrechte nicht möglich sein. Am einfachsten ist wahrscheinlich, uns die angepasste Datei per Mail zu schicken, wir checken sie dann ein und dann geht es den normalen Weg über Test- und Livesystemeinspielungen.

**Comment by thefass** [comment]
ok, dann kommt gleich eine Mail :-)

**Comment by mtrojan-ub** [comment]
Hat das im Anschluss entsprechend geklappt? Kann der Issue geschlossen werden oder ist noch etwas offen?

**Comment by mtrojan-ub** [comment]
Bei diesem Issue ist die Änderung bereits vor ca 1,5 Jahren erfolgt und auf meine Frage vor einem Jahr ob noch etwas offen ist gab es keine Antwort, daher schließe ich.
