### ISSUE TITLE
Verfügbarkeitsanzeige Volltitelanzeige - keine Doppeleinblendung von HBZ und JOP

### ISSUE THREAD

**Issue by jriedl** [ubtue/tuefind#2298]
Ausgehend von einer Nutzeranfrage an @relhei hat sich herauskristallisiert, dass die gleichzeitige Anzeige des HBZ-  und JOP-Links bei Artikeln für die Nutzer verwirrend ist und das HBZ-Gateway für Artikel aufgrund der Abhängigkeit von der Auflösung des dahinterliegenden Linkresolvers auch zumindest z.T. keine sinnvollen Ergebnisse liefert. Vorschlag wäre, die HBZ-Zeile auszublenden, falls die JOP-Anfrage erfolgreich (d.h. ohne Fehler) abschließt. Gibt es Argumente, die gegen dieses Vorgehen sprechen?

**Comment by thefass** [comment]
JOP bedient halt nur die deutsche Community. International brauchen wir das HBZ Gateway, wenn auch dort leider nur wenige internationale Resolver registriert sind. Was wir aber sicherlich machen könnten, diese beiden Verfügbarkeitsdienste besser zu benennen, so dass klar wird, welcher für was zuständig ist.

**Comment by jriedl** [comment]
Klingt eigentlich nach einem Anwendungsfall für Geolocation, aber damit handelt man sich potentiell einen ganzen Rattenschwanz an Folgeproblemen ein. Denkbar wäre eventuell, bei Ausblenden und z.B. entsprechend gewählter Sprache in die JOP-Zeile einen Hinweis auf HBZ zu setzen.

**Comment by socheres** [comment]
HBZ ist die Verfügbarkeitsanzeige für Monos und JOP für Zeitschrfiten/Zss.-Artikel. Daher sollte HBZ-Zeile nicht generell ausgeblendet, sondern wenn beide Bedingungen erfüllt sind: 1. die JOP-Anzeige ist erfolgreich 2. der Datensatz ist ein Artikel.

**Comment by thefass** [comment]
HBZ ist nicht nur für Monos. Internationale Bibliotheken, die den JOP Dienst nicht nutzen können wie z.B. Universiteit Leiden fragen über ihre Resolver via HBZ Gateways auch Zeitschriften und Artikel ab
Kann man ausprobieren bei https://www.ixtheo.de/Record/1807827097

<img width="803" alt="Bildschirmfoto 2022-10-18 um 12 49 10" src="https://user-images.githubusercontent.com/14169098/196410220-d2587921-dd93-45a3-bdab-ff1522ab7da0.png">
<img width="1018" alt="Bildschirmfoto 2022-10-18 um 12 49 38" src="https://user-images.githubusercontent.com/14169098/196410231-a0832ba8-4f72-4a9d-8989-3e05510c4b8d.png">

**Comment by jriedl** [comment]
Auf ptah findet sich aktuell eine Umsetzung, die sich die Institutionen-Zuordnung von JOP zunutze macht: Falls von JOP Bestandsinformationen zurückkommen, wird die HBZ-Zeile vollständig ausgeblendet, falls JOP keine Zuordnung möglich ist, wird der HBZ-Link samt eines Hinweises im Kontext von JOP angezeigt:
![image](https://user-images.githubusercontent.com/13135579/196949363-bc0b3685-c036-4e14-aced-b2de7541672f.png)
Screenshot, da der Zugriff auf ptah mit einer IP außerhalb des Uni Tübingen-Bereiches natürlich nicht möglich ist.

**Comment by thefass** [comment]
> Auf ptah findet sich aktuell eine Umsetzung, die sich die Institutionen-Zuordnung von JOP zunutze macht: Falls von JOP Bestandsinformationen zurückkommen, wird die HBZ-Zeile vollständig ausgeblendet, falls JOP keine Zuordnung möglich ist, wird der HBZ-Link samt eines Hinweises im Kontext von JOP angezeigt: ![image](https://user-images.githubusercontent.com/13135579/196949363-bc0b3685-c036-4e14-aced-b2de7541672f.png) Screenshot, da der Zugriff auf ptah mit einer IP außerhalb des Uni Tübingen-Bereiches natürlich nicht möglich ist.

Bitte trotzdem mal eine PPN, so dass ich mir das live ansehen kann. Danke.

**Comment by jriedl** [comment]
Sollte sich einfach über ixtheo testen lassen, wenn der Zugriff auf einen Non-OA-Artikel von einer IP aus erfolgt, die nicht automatisch einer Institution zugeordnet werden kann, z.B. über Handy https://ixtheo.de/Record/1848744560.

**Comment by thefass** [comment]
Danke. Funktioniert und überzeugt.
