### ISSUE TITLE
Neuzugänge Feature

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#2299]
_Nutzer Anfrage zum "Bereich" (7 Tage etc.) der Neuerwerbungen.
Ist es nicht möglich, den "Bereich" um die Rubrik "1 Tag" zu erweitern. Da ich täglich die Neuerwerbungen intensiv studiere, wäre dies eine erhebliche Erleichterung. Denn jetzt stosse ich ja immer wieder beim Bereich "7 Tage" auf Titel, die ich schon gesehen habe, muss aber alle Seiten durchblättern, da ja irgendwo die Titel des letzten Tages versteckt sind._

Bitte noch einen Button "seit 1 Tag" einrichten

**Comment by jriedl** [comment]
Auf ptah. Hinweis: Der Nutzer kann sich (bis zu nicht auszuschließenden fundamentalen Änderungen in diesem Bereich) den Bookmark `https://ixtheo.de/Search/NewItem?range=1&submit=Suchen&botprotect=` speichern, dann muss er nicht einmal warten, bis die Änderung den Weg in Livesysteme gefunden hat :-)

**Comment by thefass** [comment]
ja wow, wie schnell. Danke @jriedl !
