### ISSUE TITLE
JOP Mehrsprachigkeit unterstützen

### ISSUE THREAD

**Issue by ruschein** [ubtue/tuefind#231]
Vorschlag:  Falls ein nichtdeutsches Interface verwendet wird soll immer auf die neue, englischsparchige JOP-Version umgeleitet werden.

[JOP_FIZE_Ankuendigung_V05_20180314.pdf](https://github.com/ubtue/tuefind/files/1833148/JOP_FIZE_Ankuendigung_V05_20180314.pdf)

**Comment by jriedl** [comment]
Auf ptah integriert.

**Comment by thefass** [comment]
funktioniert
