### ISSUE TITLE
Anzeige bei Facetten-Auswahl 

### ISSUE THREAD

**Issue by ja-bre** [ubtue/tuefind#2315]
wie bei #2314  - beim Laden einer Facetten-Auswahl

![Screenshot (15)](https://user-images.githubusercontent.com/83392048/200278810-7085478f-80b1-429e-a115-2af28f605800.png)

**Comment by mtrojan-ub** [comment]
Dieses Problem wurde ebenfalls auf ptah behoben, bitte nochmal testen

**Comment by ja-bre** [comment]
Vielen Dank! Problem ist behoben!
