### ISSUE TITLE
E-Mail-Verifikation bei bestehendem Konto

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#2319]
Bei bestehendem Konto erscheint aktuell folgende Anzeige mit Aufforderung zur E-Mail-Verifikation:
![grafik](https://user-images.githubusercontent.com/25769591/200550646-e994b42f-9ee3-4bc7-bb11-7355200493f6.png)

Die Verifizierungs-E-Mail ist zu diesem Zeitpunkt noch nicht eingetroffen (obwohl Aufforderung, dass man Spamfilter prüfen soll). Man muss aktuell also auf jeden Fall aktiv eine E-Mail anfordern. Kann das noch geändert werden auf automatischen Versand?

**Comment by thefass** [comment]
Bei IxTheo ptah wurde die Verifizierungsmail direkt geschickt. Das habe ich heute morgen bei meinem Konto ausprobiert

**Comment by mtrojan-ub** [comment]
Das hängt von verschiedenen Faktoren ab. Bei neu angelegten Benutzerkonten wird die Mail immer gleich verschickt. Bei einem bestehenden Benutzer wird sie beim 1. Loginversuch verschickt, dann erscheint zusätzlich eine Meldung:

![grafik](https://user-images.githubusercontent.com/26873381/200563564-6989898d-8fa2-41d6-9bab-54dc15ca863f.png)

Bei jedem weiteren Login-Versuch wird keine neue Mail verschickt und der blaue Kasten erscheint nicht. Dann kann man bei Bedarf den Versand neu auslösen.

**Comment by relhei** [comment]
Komisch, ich bin mir sicher, dass beim 1. Loginversuch kein automatischer Versand erfolgte, sondern ich diesen anfordern musste mit Klick auf "eine neue E-Mail anfordern". Kann ich nun allerdings nicht mehr reproduzieren.

**Comment by relhei** [comment]
Ja bitte.

**Comment by mtrojan-ub** [comment]
Dein Konto `akimh01` auf ptah wurde zurückgesetzt, kannst Du es bitte nochmal ausprobieren?

**Comment by relhei** [comment]
Es hat funktioniert. Danke!
