### ISSUE TITLE
Einzelne Titel in Trefferliste nicht anklickbar

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#2320]
Bei Aufruf der Aufsätze einer Zeitschrift ist folgendes Problem aufgetreten:
Einzelne Titel in der Trefferliste werden unverlinkt angezeigt, d.h. man gelangt nicht auf die Volltitelanzeige.

![grafik](https://user-images.githubusercontent.com/25769591/200566345-d95bcd89-ebd5-4a44-aa90-6bdcc100dabd.png)
https://134.2.67.9/Search/Results?lookfor=superior_ppn:331140446

**Comment by mtrojan-ub** [comment]
Das kann ich nicht reproduzieren bzw. bei mir ist ein Link auf der 9 hinterlegt:
https://134.2.67.9/Record/1807384756

Kann das ggf. an einem Browser-Plugin liegen?

**Comment by relhei** [comment]
Liegt an Tampermonkey, wie mir @socheres gerade mitteilte. Das hatte ich vergessen, den Fall gab es shcon mal. Sorry.
