### ISSUE TITLE
Fehlerhafte OA Zuordnung

### ISSUE THREAD

**Issue by jriedl** [ubtue/tuefind#2326]
Wie heute im Meeting besprochen: Der Record mit der Krimdok-PPN 1805280147 wird fehlerhaft als OA ausgezeichnet. Analyse: Ursache ist ein Datenproblem in Unpaywall: Hier ist für die zugehörige DOI `10.4324/9780429059735` folgendes hinterlegt: 
```json
{
    "doi": "10.4324/9780429059735",
    "best_oa_location": {
      "url": "https://swbplus.bsz-bw.de/bsz1805280147inh.htm",
      "pmh_id": "oai:aleph.bib-bvb.de:BVB01-033898486",
      "is_best": true,
      "license": null,
      "oa_date": "2022-10-19",
      "updated": "2022-10-22T04:59:43.058925",
      "version": "submittedVersion",
      "evidence": "oa repository (via OAI-PMH doi match)",
      "host_type": "repository",
      "endpoint_id": "5a4c71918fc62d3e4ce",
      "url_for_pdf": "https://swbplus.bsz-bw.de/bsz1805280147inh.htm",
      "url_for_landing_page": "https://swbplus.bsz-bw.de/bsz1805280147inh.htm",
      "repository_institution": null
    }
```
d.h. das Inhaltsverzeichnis wird als OA-Volltext angeboten. Da die identische URL für das Inhaltsverzeichnis bereits ursprünglich in den 856-Feldern hinterlegt ist, wird hier kein zusätzliches Unpaywallfeld erzeugt, aber der Record als OA-zugänglich gekennzeichnet. Eigentlich müsste das auf Unpaywall-Seite korrigiert werden. Zielführender scheint, swbplus-URLs bei unserer Generierung der Unpaywall DOI=>URL-Liste zukünftig einfach zu überspringen, falls wir übereinstimmend zu der Einschätzung kommen, dass auf dieser Seite niemals "echte" OA-Volltexte angeboten werden.

**Comment by thefass** [comment]
Ja, Dein Vorschlag ist zielführender, @jriedl Danke!
Vielleicht könntest du unpaywall trotzdem daraufhinweisen, dass sich hinter swbplus Links mit ...inh.htm immer Inhaltsverzeichnisse verbergen. Das kommt ja tausendfach vor :-)

**Comment by jriedl** [comment]
Aktueller Stand auf ptah und sobek, sollte nach dem nächsten Import sichtbar sein.

**Comment by thefass** [comment]
ok
