### ISSUE TITLE
Symbolische Kennzeichung der Sprachauswahl

### ISSUE THREAD

**Issue by jriedl** [ubtue/tuefind#2328]
Im Meeting besprochen: Zur besseren Identifizierbarkeit der Sprachauswahl soll das Auswahlmenü künftig grundsätzlich zusätzlich durch ein Globussymbol gekennzeichnet werden, wie derzeit im neuen Ixtheo2-Theme bereits der Fall ist.

**Comment by mtrojan-ub** [comment]
@LysogorAndGmail, can you please take care of this?
In ixtheo2, we have an icon at the top right language select:

![grafik](https://user-images.githubusercontent.com/26873381/202136396-e0564631-07a0-4257-8747-800911fdae77.png)

This icon is missing in the other themes so far and should be added there as well.

**Comment by mtrojan-ub** [comment]
ready for testing auf ptah+sobek.
Testing evtl durch @thefass? Bzw. mit wem wurde es im Meeting besprochen?

**Comment by mtrojan-ub** [comment]
wird geschlossen, wie in der FID-Runde besprochen
