### ISSUE TITLE
KrimDok: Fehlerhafter Link zu "Mantra"

### ISSUE THREAD

**Issue by frl-caspar** [ubtue/tuefind#2329]
Auf dieser Seite: https://sobek.ub.uni-tuebingen.de/Content/research_data_management#content führt folgender Link: https://sobek.ub.uni-tuebingen.de/Content/research_data_management#content auf eine Webseite, auf der "Die Verbindung ist nicht sicher" angegeben wird. Durch diesen Link ersetzen: https://mantra.ed.ac.uk/

**Comment by mtrojan-ub** [comment]
wurde auf sobek geändert und kann dort getestet werden, falls OK bitte issue schließen

**Comment by frl-caspar** [comment]
Vielen Dank, funktioniert jetzt :)
