### ISSUE TITLE
Abweichende Berichtsjahre von Zeitschriften sind über die Facette "Erscheinungsjahr" nicht suchbar

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#233]
Grundsatzproblem bei Unterschieden zwischen Berichts- und Erscheinungsjahren für Aufsätze und Rezensionen (siehe https://github.com/ubtue/ixTheo/issues/227):

will jemand eine Gesamtmenge auf bestimmte Jahre einschränken, hat er nur die Facette für Erscheinungsjahre zur Verfügung.
Sucht also jemand nach einem bestimmten Jahrgang einer Zeitschrift, wird er nicht wissen, dass Berichts- und Erscheinungsjahre - teilweise stark - voneinander abweichen können und seine Suche über die Facette "Erscheinungsjahr" einschränken.

Weitere Facette für Jahrgänge/Berichtsjahre von Zeitschriften einrichten?

**Comment by mtrojan-ub** [comment]
Dieser Issue wurde heute in der FID-Runde angesprochen. Bezieht sich der Inhalt des unterliegenden Solr-Feldes tatsächlich auf das Erscheinungsjahr? Im Meeting wurde zunächst um Klärung gebeten.

Es wird ein Fallback-Mechanismus mit verschiedenen Feldern abhängig von der Medienart verwendet. Siehe auch:
https://github.com/ubtue/tuefind/issues/1990#issuecomment-1047888576

Außerdem stand noch zur Diskussion, ob für den Endbenutzer nicht das Berichtsjahr wichtiger wäre (mit Hinweis auf 773, was aber angeblich nicht bei allen Datensätzen vorhanden ist). Es wurde auch diskutiert, ob die Facette dann ggf. ausgetauscht oder umbenannt werden müsste (evtl als Fallback-Mechanismus nur mit "Jahr"), wobei die weitere Vorgehensweise noch nicht final festgelegt wurde.

Gibt es dazu weitere Meinungen?

**Comment by IxTheoKm** [comment]
> Außerdem stand noch zur Diskussion, ob für den Endbenutzer nicht das Berichtsjahr wichtiger wäre (mit Hinweis auf 773, was aber angeblich nicht bei allen Datensätzen vorhanden ist).

Ich dachte, das war in https://github.com/ubtue/ixTheo/issues/227#issuecomment-222921734 schon entschieden worden.
Das Berichtsjahr ist bei ZSS-Aufsätzen m.E. für den Endnutzer definitiv wichtiger als das Erscheinungsjahr. Aber das ist in Issue 227 bereits diskutiert worden. 
Falls das Berichtsjahr fehlen sollte, wäre eine entspr. Liste unter "Datenbereinigungen" sinnvoll.

Übrig bleibt nur folgende Frage: wenn die Facette eine _Gesamtmenge_ von Datensätzen (Monografien und Zeitschriftenbeiträge) nach Jahr eingrenzt, grenzt sie dann nur nach Erscheinungsjahr ein? 
Für Monografien in der Treffermenge ist das okay, aber für die Zeitschriftenbeiträge müsste das Berichtsjahr herangezogen werden. 

Ich weiß nicht, welches Feld für welchen Datensatztyp in der Facette zur Eingrenzung der Jahre herangezogen wird.

**Comment by mtrojan-ub** [comment]
Hier eine Übersicht:

| Datensatztyp | Feld |
| --- | ----------- |
| Website | 008 |
| Reproduktion | 534c |
| Article/Review | 936j |
| Übergeordnete Werke ohne sinnvollen 008-Wert |190j => wird in der Pipeline generiert durch Abfrage des Ältesten Artikels |
| Rest | 008[7-11] |

**Comment by thefass** [comment]
@IxTheoKm noch relevant?

**Comment by IxTheoKm** [comment]
Geklärt ist jetzt die Frage, welches Feld für die Facette "Erscheinungsjahr" beim jeweiligen Datensatztyp ausgewertet wird.
Die Berichtsjahre sind nun über die Facette suchbar.

**Ungeklärt bleibt, ob die Bezeichnung "ERSCHEINUNGSjahr" so bleiben soll, weil sie zumindest bei Aufsätzen/Rezensionen nicht stimmt. Soll sie evtl. nur "Jahr" lauten?** 

Beispiel:
https://ixtheo.de/Record/1782515755#details
### Jahrgang 2015/16, erschienen 2018.

**Wird gefunden, wenn in der Facette "Erscheinungsjahr" 2015 angegeben wird, oder 2015-2016**
(die Erfassungsform "2015/16" muss heute "2015/2016" lauten, war aber früher mit zweistelligem Jahr richtig. 
Das führt leider dazu, dass die Einschränkung mit "2016" in der Facette Erscheinungsjahr nicht funktioniert!)

Es ist gewollt, dass bei Zeitschriftenbänden dieses **Berichtsjahr in 936j** ausgewertet wird.
https://ixtheo.de/Search/Results?sort=year+desc%2C+volume_sort+desc%2C+issue_sort+desc%2C+start_page+asc%2C+first_indexed+desc&lookfor=superior_ppn%3A358456061&type=AllFields&daterange%5B%5D=publishDate&publishDatefrom=2015&publishDateto=2016&botprotect=

Mit dem Erscheinungsjahr 2018 erzielt man in der Facette korrekterweise keine Treffer:
https://ixtheo.de/Search/Results?sort=year+desc%2C+volume_sort+desc%2C+issue_sort+desc%2C+start_page+asc%2C+first_indexed+desc&lookfor=superior_ppn%3A358456061&type=AllFields&daterange%5B%5D=publishDate&publishDatefrom=2018&publishDateto=2018&botprotect=

**Comment by thefass** [comment]
Das ist eine schwierige Frage. Berichtsjahr geht gar nicht, da kann sich keiner was drunter vorstellen. Unter Erscheinungsjahr Im Englischen year of publication) kann jeder etwas assozieren und das unterscheidet sich dann auch von einer allgemeinen Jahr-Suche. Das könnte halt dann die andere Fehlinterpretation sein, wenn man nur Jahr schreibt. Ich tendiere also dazu, bei Erscheinungsjahr zu bleiben und damit zu leben, dass es Publikationen gibt, die später als berichtet erschienen sind.

**Comment by IxTheoKm** [comment]
Da es sehr häufig auch nur um eine Differenz von _einem_ Jahr zwischen Berichts- und Erscheinungsjahr geht und es noch die Unschärfen der Doppel-/Mehrfachjahrgänge gibt, halte ich das auch für tolerabel. Sollen noch andere Meinungen abgewartet werden? Sonst schließe ich.

**Comment by thefass** [comment]
nein, wir können gerne schließen. Ich mache das gleich hiermit
