### ISSUE TITLE
KrimDok: Fehlerhafter Link zur University of Edinburgh

### ISSUE THREAD

**Issue by frl-caspar** [ubtue/tuefind#2330]
Auf der Seite https://sobek.ub.uni-tuebingen.de/Content/research_data_management#content führt der Link zu [Research Data Service (University of Edinburgh): Weitere Online-Kurse zu Forschungsdatenmanagement (engl.)](https://www.ed.ac.uk/information-services/research-support/research-data-service/training) auf eine Seite, die nicht mehr existiert. Löschen.

**Comment by mtrojan-ub** [comment]
wurde auf sobek geändert und kann dort getestet werden, falls OK bitte issue schließen

**Comment by frl-caspar** [comment]
Vielen Dank! Funktioniert jetzt.
