### ISSUE TITLE
KrimDok: "Show Admins"-View kann nicht geöffnet werden

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#2331]
![grafik](https://user-images.githubusercontent.com/26873381/203007251-ac5b1371-a089-46c2-ac49-9cd51cd14c95.png)

![grafik](https://user-images.githubusercontent.com/26873381/203007131-8def0935-b39f-4018-bde9-364fa658af90.png)

**Comment by mtrojan-ub** [comment]
This will most likely also occur in the other view for the publication service (show user authorities) in KrimDok (which is not available there yet), since the ixtheo_institution column does not exist there.

**Comment by mtrojan-ub** [comment]
ready for testing auf sobek+ptah

**Comment by mtrojan-ub** [comment]
Der View ist jetzt wieder aufrufbar, allerdings fehlt die Spalte z.B. in RelBib. (auf KrimDok ist es ok wenn sie nicht angezeigt wird, da die Spalte auf dem System gar nicht vorhanden ist.)

**Comment by thefass** [comment]
Auf ixtheo ptah sind beide Funktionen "Show admins" und "Show user authorities" vorhanden. Die Spalten können sortiert werden, das ist sehr gut.
Es war noch zwei requests von mir auf zwei andere GND Konto vorhanden, die ich an gefordert hatte, bevor der request auf maximal ein GND Konto eingeführt wurde. Ich habe damit zwei Tests durchgeführt:
1. Annahme eines dieser Requests
das funktionierrt einwandfrei. Dass ich jetzt für zwei GNDs publishen kann, kann ja zukünftig nicht mehr vorkommen, da ein Nutzer nur einen Request auf eine GND absetzen kann.
2. Ablehnung eines dieser Requests.
das funktioniert einwandfrei. Allerdings sollte der request dann mit Status "Abgelehnt" in der Liste user authorities erhalten bleiben, damit wir wissen, was wir schonmal abgelehnt haben. Das ist wichtig, falls weitere requests zu dieser GND eingehen.

Aus meiner Sicht funktioniert damit das Verfahren.

**Comment by thefass** [comment]
@mtrojan-ub Ist die publish Funktion in ptah relbib noch nicht freigeschaltet? Ich finde dort den publish Button nicht

**Comment by mtrojan-ub** [comment]
@thefass => Es ist gut zu wissen dass das Verfahren aus Deiner Sicht funktioniert, aber alle genannten Punkte haben eigentlich nichts mit diesem Issue zu tun.

Und ja, bislang ist die Publish Funktion auf ptah nur für IxTheo freigeschaltet, nicht für RelBib.

Da der ursprüngliche Issue jetzt gelöst ist würde ich ihn schließen, falls es noch etwas offenes gibt könnten wir ja gerne gleich im Meeting nochmal drüber sprechen und/oder es in einen separates Issue schieben.

**Comment by thefass** [comment]
> aber alle genannten Punkte haben eigentlich nichts mit diesem Issue zu tun.

Dann habe ich das aber gründlich mißverstanden :-)
