### ISSUE TITLE
Zusammenspiel Trefferanzahl / Sortierung

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#2332]
Wenn man einen Aspekt der Sortierung eingestellt hat (z.B. Verfasser), dann wird er zurück auf Relevanz-Sortierung gestellt, sobald man die Anzahl der Treffer erhöht oder erniedrigt.
<img width="807" alt="Bildschirm­foto 2022-11-22 um 07 41 01" src="https://user-images.githubusercontent.com/14169098/203243353-d5b46e32-36fd-402f-879d-fc167231149e.png">
<img width="805" alt="Bildschirm­foto 2022-11-22 um 07 41 13" src="https://user-images.githubusercontent.com/14169098/203243366-6e298f4d-18c2-4fe5-89e2-2c23549e33e1.png">

*****
Das Blättern in einer Treffermenge dauert gefühlt zu lange. Weiß aber nicht genau, ob das vor der Version 8.1 auch schon so war.

**Comment by mtrojan-ub** [comment]
Ready for testing auf ptah und sobek

**Comment by thefass** [comment]
passt auf ptah und sobek
