### ISSUE TITLE
"Gehighlightete Erscheinungsjahre" in der Anzeige

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#234]
Bei der Suche nach bestimmten Begriffen, werden diese hervorgehoben.
Bei der Einschränkung oder Sortierung nach Erscheinungsjahren nicht. 

Die Sortierung der Listen erscheint dadurch auf den ersten Blick z.T. fehlerhaft (vgl. https://github.com/ubtue/ixTheo/issues/227)

Im Beispiel unten: 1912, 2011, kein Erscheinungsjahr, 1912 ...
Ist eine Hervorhebung in der Anzeige möglich/nötig?

![grafik](https://user-images.githubusercontent.com/17004223/37825863-90f40a12-2e91-11e8-9630-6627835e4bdf.png)

**Comment by thefass** [comment]
durch die Relevanz-Sortierung ist m.E. keine Hervorhebung nötig
