### ISSUE TITLE
Personenseiten teils nicht erreichbar.

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#2341]

**Comment by thefass** [comment]
Wenn man hier auf das Symbol der Person klickt, dann kommt man zur Personenseite:
https://www.ixtheo.de/Record/1823670601

Wenn man jedoch hier drauf klickt (erster Treffer), dann gibt es eine Fehlermeldung:
https://www.ixtheo.de/Search/Results?lookfor=author_id:%22517895021%22%20OR%20author2_id:%22517895021%22%20OR%20author_corporate_id:%22517895021%22&hiddenFilters%5B%5D=first_indexed%3A%5BNOW-1DAY+TO+NOW%5D-id%3ALR%2A

<img width="610" alt="Bildschirm­foto 2022-11-26 um 21 55 39" src="https://user-images.githubusercontent.com/14169098/204108566-1f870e6a-a5e8-4f45-a4bb-7ddf66742cbf.png">
URL zur Fehlermeldung:

https://www.ixtheo.de/Authority/517895021&hiddenFilters%5B%5D=first_indexed%3A%5BNOW-1DAY+TO+NOW%5D-id%3ALR%2A

Von der Liste der Neuerscheinung aus geht auch nicht:
https://www.ixtheo.de/Search/NewItem?hiddenFilters%5B%5D=first_indexed%3A%22%5BNOW-1DAY+TO+NOW%5D-id%3ALR%2A%22&range=1&department=&filter%5B%5D=%7Eformat%3A%22Dictionary+entry%2Farticle%22

**Comment by mtrojan-ub** [comment]
Da scheint es eher ein Problem mit Deiner Sitzung zu geben. Die URLs die Du gepostet hast scheinen Dinge zu enthalten die da nicht hingehören (insb. hiddenFilters und so weiter). Die Dritte URL ("Url zur Fehlermeldung") enthält z.B. auch zwischen der ID und dem hiddenFilters ein `&` statt eines `?` und ist somit kaputt. 

Kannst Du näher beschreiben, wie Du im System navigiert hast damit die Sitzung bzw. URLs "kaputt" gehen? Also z.B. an welcher Stelle die "URL zur Fehlermeldung" in dieser Art angezeigt wurde.

(ich glaube dass es sich für Dich im Moment beheben lässt, wenn Du nochmal auf die Startseite gehst, dann ggf. auf "Filter zurücksetzen" unter dem Suchschlitz und dann nochmal von Hand dorthin navigierst, statt die kaputten URLs als Einstiegspunkte zu verwenden.)

**Comment by thefass** [comment]
Problem besteht nicht mehr
