### ISSUE TITLE
Wikidata-Link zeigt auf falschen Eintrag

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#2353]
Gemeldet von @IxKo per Mail

https://ixtheo.de/Authority/775659118

Ein Nutzer hat sich beschwert, dass es mehrere Personen mit Namen "Stefano Costa" gibt und der Wikidata-Link auf den falschen Eintrag zeigt.

Falsch: https://www.wikidata.org/wiki/Q55812637
Richtig: https://www.wikidata.org/wiki/Q115495143

Bei einer ersten Prüfung hat sich herausgestellt, dass bei uns intern eine Mapping-Datei vom Netzlaufwerk verwendet wird die ca. Mitte 2021 erstellt wurde. Es sollte also

1) geprüft werden, ob der Fehler verschwindet wenn man die Mapping-Datei neu generiert (vermutlich ja)
2) ein cronjob eingerichtet werden, der die Mapping-Datei regelmäßig aktualisiert

**Comment by mtrojan-ub** [comment]
@IxKo:

Als Datenquelle für die Wikidata Links nutzen wir folgende Daten aus der GND:
https://www.dnb.de/DE/Professionell/Metadatendienste/Datenbezug/Gesamtabzuege/gesamtabzuege_node.html#doc58272bodyText2

Die Daten laden wir extra von dort herunter, da sich die Information dazu nur in den JSON-LD Daten befindet (also nicht in den MARC-Daten). Der `sameAs`-Verweis zeigt im Moment noch auf den alten falschen Wikidata Eintrag, wobei die Daten wohl vom Stand Oktober / November sind und das nächste Mal erst im Februar / März aktualisiert werden.

Muss hierzu auch noch der Link in der GND aktualisiert werden? Auf der GND-Seite der Person sieht man den betreffenden Link jedoch nicht, daher lässt es sich nur schwer von außen nachvolziehen: http://d-nb.info/gnd/1046073265

_______________________________________

Außerdem haben wir bei der Analyse des bestehenden C++ Programms festgestellt, dass die Auswertung damit aktuell nicht mehr funktioniert und wir es überarbeiten müssen.

**Comment by IxKo** [comment]
@mtrojan-ub 
Ich weiß leider nicht weiter.
In den beiden GND-Sätzen ist kein Wikidata-Link eingetragen. 

![image](https://user-images.githubusercontent.com/57000004/212049521-4fadd343-a696-4083-ac50-8ef99f783ea6.png)

![image](https://user-images.githubusercontent.com/57000004/212049697-00f2ac8c-bcb9-489a-85f9-63fa82c4c82d.png)

Ob es außer diesen Daten noch versteckte gibt, weiß ich nicht, und wenn, dann könnte ich sie nicht ändern.
Aber beim Wikidata-Link des Archäologen  (https://www.wikidata.org/wiki/Q55812637) findet sich eine GND-Nummer, die auch korrekt ist. Aber damit scheint es ja nichts zu tun zu haben, sonst wären sie korrekt verwiesen.

**Comment by mtrojan-ub** [comment]
Ein Zwischenstand von unserer Seite: Unsere C++-Maschinerie wurde inzwischen überarbeitet. Wir haben die Daten auf unserer Seite aktualisiert (Stand 13.10.2022, das nächste DNB-seitige Update erfolgt im Februar). Testweise läuft das ab morgen auf ptah. Wir werden später auch einen Cronjob einrichten der die DNB-Updates automatisch bei uns einspielt, dafür muss aber erst die Festplatte auf dem ub28 Server vergrößert werden (werde ich noch beim ZDV beantragen).

Außerdem haben wir festgestellt, dass die Übernahme der Wikidata/Wikipedia-IDs bislang für KrimDok noch gar nicht aktiv war. Das werden wir nachholen sobald es für IxTheo stabil läuft.

Das löst aber vermutlich noch nicht das Problem für den genannten Einzelfall, solange die Daten in der Datenquelle nicht aktualisiert wurden. Gibt es einen Ansprechpartner bei der DNB den man dazu kontaktieren könnte?

**Comment by mtrojan-ub** [comment]
Nochmal ein Zwischenstand: Auf ptah sind durch das heutige Update in der Normdaten-Facette "Wikidata" nur mehr als 200.000 Personen verknüpft. Auf ixtheo.de sind es vor der Änderung noch 120.000. Die Änderung scheint also sehr effektiv zu sein! Für KrimDok haben wir heute ebenfalls die Änderung umgesetzt und auf sobek eingespielt, das Ergebnis sollten wir am dem nächsten Pipeline-Durchlauf am 20.1. prüfen können.

**Comment by IxKo** [comment]
Von einer Ansprechperson weiß ich leider nichts.
Eventuell wissen @IxTheoKm und @IxGe mehr.

**Comment by IxTheoKm** [comment]
Wer in der GND technisch(?) zuständig ist, weiß ich auch nicht.

**Comment by IxGe** [comment]
Technisch zuständig müssten dann ja diejenigen sein, die diese o.a. Seite https://www.dnb.de/DE/Professionell/Metadatendienste/Datenbezug/Gesamtabzuege/gesamtabzuege_node.html#doc58272bodyText2 produziert und zur Verfügung stellt - und so wie die Adresse aussieht, dann wohl jemand in der DNB

**Comment by mtrojan-ub** [comment]
Auf ub28 wurde nun die Festplatte vergrößert und der cronjob zur Aktualisierung der Metadaten eingerichtet (läuft jeweils am 1. jeden Monats). Da laut der DNB-Seite die Aktualisierung der Daten das nächste Mal im Februar/März passiert, wird die Übernahme also voraussichtlich entweder am 1.3. oder am 1.4. erfolgen.

**Comment by mtrojan-ub** [comment]
Zwischenstand für @KStelzel  und @JMeister01: Auf sobek ist das heute erfolgreich durchgelaufen. In der Suche nach Personen / Körperschaften gibt es nun also viel mehr Verweise auf Wikidata (438 => 21.862) und Wikipedia (3.200 => 14.315).

**Comment by mtrojan-ub** [comment]
Die Daten wurden mittlerweile aktualisiert. Auch der im Issue genannte Autor hat jetzt auf ptah den korrekten Verweis auf Wikidata. Auf ub16 wird die Änderung an diesem Autor voraussichtlich ab morgen sichtbar.

Somit setze ich diesen Issue auf ready for testing => bitte prüfen.

**Comment by IxKo** [comment]
Die Person ist seit heute im IxTHeo mit dem korrekten Wikidata-Eintrag verlinkt.
Danke!
