### ISSUE TITLE
Blättern in Facetten

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#2363]
Nach alphabetischer Sortierung von Facetten wird zum Weiterblättern "more_ellipsis" statt "mehr ..." angezeigt.

![facette](https://user-images.githubusercontent.com/17004223/208874595-f200311d-4e93-49ab-8e05-fd070fe4ef47.JPG)

**Comment by mtrojan-ub** [comment]
Das scheint nicht bei allen Facetten der Fall zu sein, aber z.B. den Schlagwort-Facetten, bei Verfasser und Verlag. Im Rahmen der Migration auf VuFind 8.1 hatten wir schon an anderen Stellen ähnliche Probleme behoben. Wir schauen es uns an.

**Comment by mtrojan-ub** [comment]
Wurde behoben, ready for testing auf ptah

**Comment by IxTheoKm** [comment]
Auf ptah in Ordnung, vielen Dank. Ich schließe.
