### ISSUE TITLE
PPN 1177536196: Fehler bei Titelsuche

### ISSUE THREAD

**Issue by JMeister01** [ubtue/tuefind#2371]
PPN 1177536196 wird bei der Titelsuche mit dem Suchbegriff "Christmas" angezeigt, obwohl Christmas nicht im Titel vorhanden ist, sondern im Namen des Autors / der Autorin.

**Comment by jriedl** [comment]
Liegt wie vermutet an der Angabe in 245$c. 
![image](https://user-images.githubusercontent.com/13135579/211556221-5c790b5f-8898-413d-be6b-17f078946508.png)
Dies ist in dieser VuFind-Standard-Verhalten. Soll 245$c dennoch grundsätzlich und für alle Systeme ausgeschlossen werden?

**Comment by jriedl** [comment]
Für den Volltitel werden nun nur noch 245abp extrahiert. Auf sobek ab sofort, auf ptah nach Abschluss des nächstens Imports sichtbar.

**Comment by thefass** [comment]
@JMeister01 bitte testen und dann schließen

**Comment by JMeister01** [comment]
@jriedl Ich finde den Titel leider nicht mehr über die PPN: "Für Ihre Suchanfrage - 1177536196 - wurde keine Übereinstimmung gefunden"

**Comment by jriedl** [comment]
Die Suche nach id:1177536196 liefert einen Treffer.

________________________________

**Comment by mtrojan-ub** [comment]
Dass man direkt die ID ohne Präfix suchen kann wäre mir neu (das war ja aber nur die Frage am Rande).

Da der Issue laut @JMeister01 geschlossen werden kann, schließe ich ihn hiermit.

**Comment by JMeister01** [comment]
Danke für die Info. Dann habe ich mir das wohl eingebildet :-D

MSSc. Janina Meister
Fachreferentin für Kriminologie (FID)

Universitätsbibliothek Tübingen
Wilhelmstraße 32 - 72074 Tübingen - Germany
Tel.: +49 / (0)7071 / 29-77855

Von: Mario Trojan ***@***.***>
Gesendet: Mittwoch, 16. August 2023 08:52
An: ubtue/tuefind ***@***.***>
Cc: Meister, Janina ***@***.***>; Mention ***@***.***>
Betreff: Re: [ubtue/tuefind] PPN 1177536196: Fehler bei Titelsuche (Issue #2371)


Dass man direkt die ID ohne Präfix suchen kann wäre mir neu (das war ja aber nur die Frage am Rande).

Da der Issue laut @JMeister01<https://github.com/JMeister01> geschlossen werden kann, schließe ich ihn hiermit.
