### ISSUE TITLE
Keine Volltexte bei Suche in allen Feldern

### ISSUE THREAD

**Issue by JMeister01** [ubtue/tuefind#2372]
Bei der Suche in allen Feldern sollen keine Titel angezeigt werden, die lediglich über die Volltextsuche gefunden werden würden.

Beispiel für fehlerhaftes Suchergebnis: PPN 1760373354 erscheint bei Suche in allen Feldern mit Suchbegriff "Christmas". "Christmas" ist nur im Volltext erhalten.

**Comment by jriedl** [comment]
`fulltext` und `fulltext_unstemmed` waren in der KrimDok-`searchspecs.yaml` noch hinterlegt, angepasste Version jetzt auf sobek.

**Comment by jriedl** [comment]
Das war - nach dunkler Erinnerung - in der Vergangenheit einmal Thema und es wurde entschieden, dass es miteinfließen soll.
