### ISSUE TITLE
Bibelreferenz auf Englisch mit Fehlermeldung

### ISSUE THREAD

**Issue by derclou** [ubtue/tuefind#2375]
Bei Bibelreferenzen in der englischen Sprache steht ein Doppelpunkt zwischen Kapitelnummer und Versnummer, z. B. "Mk 2:1-10". Wenn man aber gezielt nach einer Bibelstelle (d. h. nicht in der allgemeinen Suche, sondern mit der Option "Bible passages" selektiert) in der englischen Version unserer Webseite sucht, funktioniert eine solche Angabe nicht, sondern man bekommt eine Fehlermeldung, und der Doppelpunkt wird durch "\\:" ersetzt.
Es wäre wichtig, dass die Bibelstellensuche bei unserem kommenden englischen Webinar (am kommenden Mittwoch, 17 Uhr) funktioniert.

**Comment by thefass** [comment]
Ist - entgegen meiner Einschätzung - eine größere Sache. Ob das umsetzbar ist, müssen wir in Ruhe nach dem webinar besprechen.

**Comment by jriedl** [comment]
Aktueller Stand auf ptah. Unterstützt werden nun sowohl Komma als auch Doppelpunkt. In Abhängigkeit von der gewählten Sprache (Deutsch/andere Sprachen) wird der Suchstring passend zum Format der Bibelstellen in der Kurztitelanzeige angepasst.

**Comment by thefass** [comment]
funktioniert sehr gut. Vielen Dank!
