### ISSUE TITLE
Jahresangabe vor dem Autorennamen

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#2378]
**Einige Autorennamen werden in den Datensätzen und in den Facetten mit vorausgehender Jahresangabe angezeigt:**

**Bsp.:**
https://www.ixtheo.de/Search/Results?lookfor=author_id:%22698117352%22%20OR%20author2_id:%22698117352%22%20OR%20author_corporate_id:%22698117352%22

![Buckwalter](https://user-images.githubusercontent.com/17004223/212111584-ea9e1de4-d22e-46a0-b865-0eeb661d0ad1.JPG)

**Weitere:**

![Autor Jahr](https://user-images.githubusercontent.com/17004223/212111638-41b50983-f617-49b7-a478-837f32248eef.JPG)

![Autor 19XX](https://user-images.githubusercontent.com/17004223/212111703-7d05d3de-c246-46f5-94c7-2377885941c1.JPG)

https://www.ixtheo.de/Search/Results?lookfor=id%3A1649753748&type=AllFields

![Berger](https://user-images.githubusercontent.com/17004223/212112456-49a80996-e030-46fb-b49a-190481a122a8.JPG)

**Comment by IxTheoKm** [comment]
Nachtrag:
Das letzte Beispiel (Berger, Markus) wird nach einer Scheinkorrektur des Titeldatensatzes heute korrekt angezeigt.

**Comment by mtrojan-ub** [comment]
Etwas seltsam, aber: Mir ist aufgefallen, dass die Reihenfolge der MARC-Unterfelder in den Titeldaten in manchen Fällen durcheinander zu sein scheint. Beispiel:

https://www.ixtheo.de/Record/1667742523

![grafik](https://user-images.githubusercontent.com/26873381/212332058-b55c1234-7010-4cd8-9dce-0c8a80087404.png)

Daher vermute ich Folgendes:
1) Wenn die Felder in umgekehrter Reihenfolge enthalten sind, werden sie auch beim Import in umgekehrter Reihenfolge berücksichtigt und die Jahresangabe wandert nach vorne
2) Falls dies durch eine Scheinkorrektur gelöst werden kann, gab es vermutlich zu einem früheren Zeitpunkt einen Fehler beim BSZ, so dass die Reihenfolge anders ausgespielt wurde. Außerdem gab es zu einem bestimmten Zeitpunkt eine Anpassung am Export, aber die Daten werden erst nach einer Änderung (oder Scheinkorrektur) erneut korrekt ausgespielt

**Comment by IxTheoKm** [comment]
2. Nachtrag:
Betrifft auch Körperschaften: https://ixtheo.de/Record/129917915#details

> 2\. aber die Daten werden erst nach einer Änderung (oder Scheinkorrektur) erneut korrekt ausgespielt

Bedeutet, alle Fälle manuell korrigieren, richtig?

**Comment by mtrojan-ub** [comment]
Entweder das, oder => falls es uns nicht allzu sehr stört könnten wir auch warten bis wir das nächste Mal einen neuen Komplettabzug vom BSZ erhalten. Ursprünglich hatten wir das mal ca. März anvisiert (ist aber noch nicht final geplant / in die Wege geleitet). 

Ich würde jedenfalls davon abraten, dass wir z.B. in der Pipeline solche Unterfelder automatisch umsortieren. Laut dem MARC Standard kann es Fälle geben, in denen bestimmte Unterfelder bewusst in nicht-alphabetischer Sortierung auftreten dürfen. Von daher müssen wir uns darauf verlassen können, dass die Anordnung der Unterfelder in den vom BSZ gelieferten Daten korrekt ist.

https://www.loc.gov/marc/umb/um07to10.html

**Comment by IxTheoKm** [comment]
Wegen eines nicht mehr auftauchenden Fehlers würde ich auch auf keinen Fall irgendwas automatisch umsortieren!
Die meisten Fälle habe ich scheinkorrigiert (bis auf Herrn Buckwalter. Der muss auf den Komplettabzug warten).
Ich schließe.

**Comment by IxTheoKm** [comment]
Das Phänomen taucht wieder auf. Über diesen Fall bin ich evtl. auf die Ursache gestoßen (die dann ggf. trotzdem durch Komplettabzüge behoben werden muss).

### Das wird immer mal wieder vorkommen. Aber m.E. lohnt es sich nicht, dafür größeren Aufwand zu treiben.
**Das Scheint mit Umlenkungen von Normsätzen zu tun zu haben:**

https://ixtheo.de/Authority/1047770989

**PICA:**
Eingabe: 2012:31-01-19 Änderung: 2012:02-02-23 21:18:43 Status: 2012:08-03-19
Titel: [5](pica3://cbs.k10plus.de:1035-1036,1,3081730/?%5CREL%20TT%20%5CPPN%201047770989)   
005 Tpv3
006 http://d-nb.info/gnd/1176748599
008 piz
010 u
011 f
035 gnd/1176748599
039 gnd/1176975129
040 $erda
043 XA-DE
100 Baltes, Gisela
375 f
**682 [!379135817!](pica3://cbs.k10plus.de:1035-1036,1,3081730/?%5Czoe+IDN+379135817)Baltes, Gisela$vUmlenkung**
797 1047770989
798 516843958

**MARC:**
cz a22 n 4500
001 516843958
003 DE-576
005 202302022118.4
008 190131n||aznnnabbn | aaa |c
024 7 $ahttp://d-nb.info/gnd/1176748599$2uri
035 $a(DE-588)1176748599
035 $a(DE-627)1047770989
035 $a(DE-576)516843958
040 $aDE-576$bger$cDE-576$erda
043 $cXA-DE
079 $ag$bp$cv$qf$vpiz
100 1 $aBaltes, Gisela
375 $a2$2iso5218
**682 $iUmlenkung$0(DE-627)379135817$0(DE-576)183159624$0(DE-588)128762144$aBaltes, 183159624, Umlenkung**


https://ixtheo.de/Search/Results?sort=year+desc%2C+volume_sort+desc%2C+issue_sort+desc%2C+start_page+asc%2C+first_indexed+desc&type=AllFields&filter%5B%5D=%7Eauthor_facet%3A%221944-+Baltes%2C+Gisela%22

### Die Titelsätze sind noch mit PPN 1047770989 = gnd/1176748599 verknüpft, wo gar kein Geburtsjahr steht!
**Das Geburtsjahr steht nur im Ziel-Normsatz, an den die Umlenkung des dubletten Normsatzes noch erfolgt:**

https://ixtheo.de/Authority/379135817

**PICA:**
Eingabe: 2012:19-04-12 Änderung: 2012:02-02-23 21:25:37 Status: 2012:08-03-19
Titel: [9](pica3://cbs.k10plus.de:1035-1036,1,3081730/?%5CREL%20TT%20%5CPPN%20379135817)    Verknüpfungen mit Normsätzen: [4](pica3://cbs.k10plus.de:1035-1036,1,3081730/?%5CREL%20%5CPPN%20379135817)   
005 Tpv1
006 http://d-nb.info/gnd/128762144
008 piz
011 f
035 gnd/128762144
039 pnd/128762144$vzg
040 $erda
043 XA-DE
100 Baltes, Gisela
375 f
**548 1944$4datl**
550 [!104535318!](pica3://cbs.k10plus.de:1035-1036,1,3081730/?%5Czoe+IDN+104535318)Theologin ; ID: gnd/4138249-3$4berc
550 [!104661348!](pica3://cbs.k10plus.de:1035-1036,1,3081730/?%5Czoe+IDN+104661348)Autorin ; ID: gnd/4258697-5$4beru
550 [!181236109!](pica3://cbs.k10plus.de:1035-1036,1,3081730/?%5Czoe+IDN+181236109)Redakteurin ; ID: gnd/4352068-6$4berc
550 [!106249363!](pica3://cbs.k10plus.de:1035-1036,1,3081730/?%5Czoe+IDN+106249363)Lehrerin ; ID: gnd/4035097-6$4beru
672 Mit den Heiligen von Tag zu Tag$f2019
797 379135817
798 183159624

**MARC:**
cz a22 n 4500
001 183159624
003 DE-576
005 202302022125.3
008 120419n||aznnnabbn | aaa |c
024 7 $ahttp://d-nb.info/gnd/128762144$2uri
035 $a(DE-588)128762144
035 $a(DE-627)379135817
035 $a(DE-576)183159624
035 $z(DE-588a)128762144$9v:zg
040 $aDE-576$bger$cDE-576$erda
043 $cXA-DE
079 $ag$bp$cv$qf$vpiz
100 1 $aBaltes, Gisela$d1944-
375 $a2$2iso5218
548 $a1944-$4datl$wr$iLebensdaten
550 $0(DE-627)104535318$0(DE-576)209684437$0(DE-588)4138249-3$aTheologin$4berc$wr$iCharakteristischer Beruf
550 $0(DE-627)104661348$0(DE-576)210574526$0(DE-588)4258697-5$aAutorin$4beru$wr$iBeruf
550 $0(DE-627)181236109$0(DE-576)211535249$0(DE-588)4352068-6$aRedakteurin$4berc$wr$iCharakteristischer Beruf
550 $0(DE-627)106249363$0(DE-576)209010754$0(DE-588)4035097-6$aLehrerin$4beru$wr$iBeruf
692 $aMit den Heiligen von Tag zu Tag

### Wenn Einigkeit besteht, das auf Komplettabzüge zu verlegen, schließe ich.

**Comment by thefass** [comment]
> Wenn Einigkeit besteht, das auf Komplettabzüge zu verlegen, schließe ich

Ich bin dafür, das auf die Komplettabzüge zu verlegen
