### ISSUE TITLE
Liste der zuletzt erfassten Hefte aller laufenden IxTheo-Zeitschriften

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#238]
Wie besprochen bitten wir um eine Liste der IxTheo-Zeitschriften mit folgenden Spalten:
- PPN (001)
- Titel (245 $a)
- **neuester Jahrgang (936 $j)**

Bsp.:
014412705 | Evangelische Kommentare | _936 uw$d33$j**2000**$e9$h49-51_
PPN 087930706 | Zeitzeichen | _936 uw$d19$j**2018**$e3$h73_

PPN-Liste der IxTheo-Zeitschriften aus ZEDER (Stand 2018-03-27):
[IxTheo_ZSS.txt](https://github.com/ubtue/tuefind/files/1852566/IxTheo_ZSS.txt)

**Comment by IxTheoKm** [comment]
Ergänzung zum Verständnis: Wir wollen damit ermitteln, bei welchen Zeitschriften, die wir zur Zeit aktiv auswerten, wir im Auswertungsrückstand sind (unsere sogenannte "virtuelle Klagemauer"). 

Manche Zeitschriften sind gedruckt nicht mehr im Bestand. Diese müssen anhand der Online-Ausgaben weiter ausgewertet werden. Welche dies sind, können wir erkennen, wenn bei gedruckten Ausgaben nur ältere Jahrgänge erfasst sind, bei den Online-Zeitschriften aber noch keine.

Missverständlich ist meine Angabe von 936: wir benötigen nur das _Jahr_ aus 936 $j.

**Comment by Gazeller** [comment]
Ich finde eine solche Liste sehr gut! Sehr wichtig für die eigene Arbeit, weil man eben die aufgelaufenen „Hefte“ nicht mehr sieht und der Rückstand bei der Sacherschließung daher leicht ins Vergessen gerät. Aber auch gut, um nach außen unseren Stand der Aufsatzerschließung zu dokumentieren. Das wird ja hoffentlich für alle, also auch für die RelBib Zeitschriften gemacht?



Von: IxTheoKm <notifications@github.com>
Gesendet: Dienstag, 27. März 2018 17:46
An: ubtue/tuefind <tuefind@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [ubtue/tuefind] Liste der zuletzt erfassten Hefte aller laufenden IxTheo-Zeitschriften (#238)


Ergänzung zum Verständnis: Wir wollen damit ermitteln, bei welchen Zeitschriften, die wir zur Zeit aktiv auswerten, wir im Auswertungsrückstand sind (unsere sogenannte "virtuelle Klagemauer").

Manche Zeitschriften sind gedruckt nicht mehr im Bestand. Diese müssen anhand der Online-Ausgaben weiter ausgewertet werden. Welche dies sind, können wir erkennen, wenn bei gedruckten Ausgaben nur ältere Jahrgänge erfasst sind, bei den Online-Zeitschriften aber noch keine.

Missverständlich ist meine Angabe von 936: wir benötigen nur das Jahr aus 936 $j.

**Comment by IxTheoKm** [comment]
Ja, es sind alle IxTheo- und RelBib-Zeitschriften dabei. Bei der Katalogisierung macht es keinen Unterschied, ob IxTheo oder RelBib: sie werden alle gleich in derselben Primärquelle (SWB) von denselben KatalogisiererInnen erfasst.

Für die Sacherschließung gibt es allerdings die Übersicht über die Mailboxmeldungen im SWB.

Diese Liste ist vorerst als einmalige Aktion v.a. für das "Wiederauffinden" von Zeitschriften gedacht, für die wir keine gedruckten Hefte mehr bekommen, und für die wir die Katalogisierung der Online-Zeitschriften noch nicht begonnen hatten.

**Comment by ruschein** [comment]
[report.txt](https://github.com/ubtue/tuefind/files/1906306/report.txt)
Bitte evaluieren.

**Comment by IxTheoKm** [comment]
Datei wird sukzessive geprüft. Danke!
