### ISSUE TITLE
Doppelte Spracheinstellung

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#2383]
Im Benutzeraccount in IxTheo kann man von Hand eine Sprache einstellen:

![grafik](https://user-images.githubusercontent.com/26873381/212686752-d53a2fc6-671c-4261-b7ed-ded713f966ae.png)

Diese Sprache wird in der Datenbank beim Benutzer als `ixtheo_language` gespeichert. Allerdings gibt es dort auch ein Feld für die `last_language`. Dabei handelt es sich um die Sprache, die der Benutzer zuletzt im Frontend rechts oben ausgewählt hat.

Die Frage ist, ob man ggf. die `ixtheo_language` abschaffen und nur noch die `last_language` verwenden könnte. Es muss noch geklärt werden, wo genau die `ixtheo_language` aktuell noch verwendet wird (das könnte z.B. beim Versenden von E-Mails fürs Alerting, für RSS-Feeds o.Ä. der Fall sein).

**Comment by mtrojan-ub** [comment]
Besprochen in FID-Runde, kann entfernt werden.

**Comment by mtrojan-ub** [comment]
@relhei kannst Du bitte auch diesen Issue mittesten? Ist ja quasi die gleiche Stelle wie #2479

**Comment by relhei** [comment]
Länderbezeichnung wird automatisch je nach gewählter Spracheinstellung richtig ausgewählt. Für Chinesisch konnte ich die Länderbezeichnung prüfen, aber sicher wird das auch passen, zumindest wird die richtige Schrift angezeigt.
Scheint also - bis auf den bekannten Fehler im Deutschen ("Elliceanisch") - alles zu passen.

**Comment by mtrojan-ub** [comment]
… ich setze das ebenfalls nochmal auf "ready for testing" da der andere bekannte Issue im Bezug auf das Länderkürzel jetzt ebenfalls behoben sein müsste. Falls sonst alles passt könnte man aber auch diesen Issue schließen und das Länderkürzel-Thema im anderen Issue weiterverfolgen.
