### ISSUE TITLE
Abweichende Treffermenge Augustinus-Bibliografie

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#2386]
Im K10plus wurden am 15.12.2022 **37.421** Datensätze mit Abrufzeichen 935 $aAUGU und lokalem Abrufzeichen LOK 935 $awumi migriert. Die Auslieferung erfolgte in Etappen, weil nach der Einspielung teilweise noch Korrekturen erfolgt sind.

Im IxTheo sind bis dato nur **37.345** Datensätze angekommen:
https://ixtheo.de/Search/Results?lookfor=rs%3AAUGU&type=AllFields&limit=20&botprotect=
https://ixtheo.de/Search/Results?lookfor=rs%3Awumi&type=AllFields&limit=20&botprotect=

Leider habe ich keine Möglichkeit festzustellen, welche Datensätze nicht angekommen sind.
@thefass 
Soll ein Abgleich unternommen, oder ein neuer Gesamtabzug abgewartet werden, um dann nochmals die Vollständigkeit zu prüfen?

**Comment by IxTheoKm** [comment]
Die Abgleiche sind inzwischen erfolgt (auch für andere Datenbestände: wumi, msmi, ruy, ixbt).
Zum Teil mussten Fehler bei einzelnen Einspielungs-/Migrationsdaten korrigiert werden, die möglicherweise die Ursache für die Nicht-Auslieferung waren.

V.a. fehlende ixbt-Datensätze standen in der Löschliste und sind daher nicht in der Datenbank. 
Sie enthalten im K10plus aber IxTheo-Selektionskriterien und _kein_ Abrufzeichen mtex!
Falls mtex inzwischen gelöscht worden sein sollte (die Datensätze wurden zwischen dem 7. und 12. Juni korrigiert), müssten sie doch eigentlich jetzt nochmals geliefert worden sein:

102008331X
1614207313
1657047512
1657689069
1657689328
1657690598
1657690636
1657690679
1657697975
165769819X
1657698238
1657701131
1657702308
1657702391
1657702405
1657702553
1657704742
1657706680
165770680X
1657708306
1657720233
1657760995
1657761363
1767486766
176748707X
1767489269
1767493207
1767493282
1767494203
1767496656
1767496834
1767497075
887613861

**Comment by mtrojan-ub** [comment]
Am 11. Juni haben wir einen neuen Komplettabzug erhalten. 

102008331X sowie 1614207313 (Stichproben) waren im Komplettabzug enthalten. Hinsichtlich Löschlisten tauchen die IDs in mtex-Löschlisten vom 21.05., 28.05. sowie 4.6. auf. Es gibt eine Sonderregel die besagt, dass mtex Löschlisten immer am Ende des Merge-Prozesses angewendet werden sofern diese noch auf dem Server liegen, also selbst nach einem neuen Komplettabzug. (Wir hatten das Arbeitsverzeichnis auf dem Server nicht bereinigt und daher wurden diese neu angewendet). Somit wurden die Daten wieder entfernt.

Wahrscheinlich wäre die beste Lösung wenn wir die besagten Mtex Löschlisten wegwerfen und auf Basis der vorhandenen Daten seit dem SA einen neuen lokalen Pseudokomplettabzug erstellen. Das würden wir morgen früh anstoßen, wenn die nächsten Teilabzüge vom BSZ ausgespielt wurden.

**Comment by IxTheoKm** [comment]
Die o.g. PPNs sind jetzt da, die Anzahl der Datensätze für die Augustinus-Bibliografie stimmen im K10plus und IxTheo überein. Vielen Dank, ich schließe.
