### ISSUE TITLE
Anzeige von Unterfeldern in 655

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#2388]
https://ixtheo.de/Record/866875468#details

In Feld 655 werden die Unterfelder $k (Code des Generierungsverfahrens, Konfidenzwert) und $v (Datum der Generierung) in der Facette Genre (Schlagwort) und in der Vollanzeige des Titelsatzes angezeigt.

Ich gehe davon aus, dass das nicht gewünscht ist.

![655](https://user-images.githubusercontent.com/17004223/213433137-f78d9bf3-7622-431f-96fd-77dc8824567f.JPG)

Weiteres Beispiel:
https://ixtheo.de/Record/77499388X#details

**Comment by jriedl** [comment]
Nachtrag: Die implizite Annahme war bislang, dass die Unterfelder in 655 alle für die Anzeige relevant sind, d.h. die zugehörige Extraktionsfunktion für den Import arbeitet bislang nicht "unterfeldscharf", da hier eine ganze Reihe von Feldern zusammengefasst werden (600:610:630:648:650:651:653:655). Unkompliziert umsetzbar wäre die Löschung von 655k und 655v vor dem Import.

**Comment by IxTheoKm** [comment]
655 enthält GND-Verknüpfungen von Formschlagwörtern. Die werden nicht in 689 abgelegt.

Ich sehe diese Unterfelder auch zum ersten Mal und kann nicht sagen, wie häufig und in welchen Fällen das in Zukunft vorkommen kann.

@IxGe Ist das schon mal in der AG Sacherschließung angesprochen worden?
Bsp. (nicht im IxTheo): PPN 1814601996

**Comment by IxTheoKm** [comment]
Nach Rücksprache mit @IxGe, der auch keine Informationen zu diesen Unterfeldern hat, klingt die Löschung von 655k und 655v vor dem Import am besten.

**Comment by jriedl** [comment]
Auf ptah.
