### ISSUE TITLE
"Unbekanntes Material"

### ISSUE THREAD

**Issue by Gazeller** [ubtue/tuefind#239]
was bedeutet das?
https://relbib.de/Record/251571793 
Bei Klick auf Link kommt Fehlermeldung

**Comment by IxTheoKm** [comment]
Ich habe in den Daten korrigiert: es fehlt das Unterfeld mit dem Hinweis auf "Inhaltsverzeichnis". Außerdem wurden zwei Zeichen im Link falsch erfasst.

**Comment by Gazeller** [comment]
Oh, gut. Frage ist, ob man irgendwie solche Fehler herausfischen kann. Suche nach „Unbekanntes Material“?
Den issue kann ich dann wohl schließen.
Gruß Gaby

Von: IxTheoKm <notifications@github.com>
Gesendet: Mittwoch, 28. März 2018 12:05
An: ubtue/tuefind <tuefind@noreply.github.com>
Cc: Gazeller <gabriele.zeller@ub.uni-tuebingen.de>; Author <author@noreply.github.com>
Betreff: Re: [ubtue/tuefind] "Unbekanntes Material" (#239)


Ich habe in den Daten korrigiert: es fehlt das Unterfeld mit dem Hinweis auf "Inhaltsverzeichnis". Außerdem wurden zwei Zeichen im Link falsch erfasst.
