### ISSUE TITLE
Normdatenanzeige bei Kongressen ist unvollständig

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#2405]
https://www.ixtheo.de/Authority/1743278748
111 2 $aSessione di formazione ecumenica$n56a$d2019$cAssisi

Im Normsatz **$n** nicht angezeigt:
Sessione di formazione ecumenica. Assisi (2019)

Im Titelsatz wird angezeigt:
Sessione di formazione ecumenica 56a 2019, Assisi

https://www.ixtheo.de/Authority/1827061774
111 2 $aMormonen$eHerbst-Generalkonferenz$n192.$d2022$cSalt Lake City, Utah

Im Normsatz werden **$e** und **$n** nicht angezeigt:
Mormonen. Salt Lake City, Utah (2022)

Im Titelsatz wird angezeigt:
Mormonen 192. 2022, Salt Lake City, Utah (hier fehlt auch $e! Ebenso in der Facette "Autor".)

**Comment by mtrojan-ub** [comment]
ready for testing ab dem nächsten Import (morgen Vormittag)

**Comment by IxTheoKm** [comment]
Auf ptah in Ordnung, vielen Dank. Ich schließe.
