### ISSUE TITLE
Erweiterte Suche geht nicht

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#2419]
Die Eingabe eines Suchbegriffs in der Erweiterten Suche, z.B. Augustiner etc. führt zu einer Fehlermeldung

https://www.ixtheo.de/Search/Results?join=AND&lookfor0%5B%5D=Augustinus%2C+Aurelius%2C+Augustinus*&type0%5B%5D=Subject&lookfor0%5B%5D=&type0%5B%5D=AllFields&bool0%5B%5D=AND&limit=20&daterange%5B%5D=publishDate&publishDatefrom=&publishDateto=&botprotect=

<img width="840" alt="Bildschirm­foto 2023-03-07 um 08 55 57" src="https://user-images.githubusercontent.com/14169098/223359458-a5addaf3-b68a-4135-b47e-f833a09fa48f.png">

**Comment by jriedl** [comment]
Ist behoben.

**Comment by thefass** [comment]
ok
