### ISSUE TITLE
Einrichten von Feedback-Email-Adressen

### ISSUE THREAD

**Issue by ruschein** [ubtue/tuefind#243]
Zur Zeit misbrauchen wir die no-reply... Adressen auch für das Feedback.  Das sollten wir ändern.  Deswegen vielleicht ixtheo-feedback@, relbib-feedback@ und krimdok-feedback@.  Desweiteren sollten wir es schwieriger machen Spam- und Phishing-Emails über die Feedback-Adressen zu verschicken. (See https://stackoverflow.com/questions/2387496/how-to-prevent-robots-from-automatically-filling-up-a-form for ideas.)  Schließlich sollten wir die no-reply-Adressen nach /dev/null schicken.

**Comment by mtrojan-ub** [comment]
besprochen mit ruschein:

- Mehrere no-reply Adressen sind  unnötig (ixtheo-noreply etc.). Wir sollten eine no-reply@ub.uni-tuebingen.de einrichten und diese überall einheitlich verwenden
- Es soll geprüft werden ob es noch andere Arten von bestehenden no_reply (no_return) Adressen gibt die vereinheitlicht werden müssen (z.B. auch in ub_tools)
- die o.g. Feedback-Adressen existieren noch nicht, das Thema muss erst noch mit der IT-Leitung besprochen werden. Erst wenn die Adressen existieren kann die Umstellung erfolgen

**Comment by ruschein** [comment]
Hallo Mario,


bitte schicke die Liste von die Rollenadresse die gerade an Frau Kellmeyer geht an Armin, derv konnte Sie nämlich nicht finden und hat mit nicht geglaubt, dass sie existiert, bzw. hat vermutet, dass wir die intern auf einem eigenen Server aufgesetzt haben.


Danke.


Gruß,

Johannes

--
Dr. Johannes Ruscheinski
Universitätsbibliothek Tübingen - IT-Abteilung -
Wilhelmstr. 32, 72074 Tübingen

Tel: +49 7071 29-72820
FAX: +49 7071 29-5069
Email: johannes.ruscheinski@uni-tuebingen.de

________________________________

**Comment by mtrojan-ub** [comment]
Es gab hier wohl Inkonsistenzen. Kleinere Anpassungen siehe #253 

laut local_overrides gilt aktuell:

| System | Feedback Sender | Feedback Empfänger |
| ------------- |:-------------:|:-----:|
| ixtheo | ixtheo-noreply@ub.uni-tuebingen.de | ixtheo@ub.uni-tuebingen.de |
| relbib  | relbib-noreply@ub.uni-tuebingen.de | relbib@ub.uni-tuebingen.de |
| krimdok | qubob15@uni-tuebingen.de |  krimdok-team@ub.uni-tuebingen.de |

Wobei es für krimdok noch kein Feedback-Formular gibt.

**Comment by mtrojan-ub** [comment]
die noreply-Adressen existieren alle nicht, können aber trotzdem als Absender verwendet werden.

Armin hat bereits eine neue Adresse beantragt: no-reply@ub.uni-tuebingen.de. Was mit den Mails dahinter passiert kann dann eingestellt werden sobald die Adresse existiert.

Außerdem hat er krimdok@ub.uni-tuebingen.de beantragt, da es bisher nur die krimdok-team Adresse gibt.

Armin meldet sich sobald eine Rückmeldung vom ZDV vorliegt.

**Comment by mtrojan-ub** [comment]
krimdok@ub.uni-tuebingen.de: Empfänger wurden festgelegt, die Adresse wird im Impressum des neuen KrimDok-Theme verwendet.
no-reply@ub.uni-tuebingen.de: Lehnt sämtliche E-Mails ab

**Comment by mtrojan-ub** [comment]
code review geöffnet für @ruschein (ub_tools)
Thema Absicherung gegen Bots siehe #295.
