### ISSUE TITLE
Verweisungen bei Personennamen - Steckbrief

### ISSUE THREAD

**Issue by IxGe** [ubtue/tuefind#2430]
Ein Nutzer vermisst - zu Recht - die Verweisungsformen bei Personennamen im Personensteckbrief, bzw. hat die vorhandenen Formen in https://www.ixtheo.de/Authority/699469082 nicht gefunden
![wittig3](https://user-images.githubusercontent.com/17196047/227921346-ec17830d-0d4f-4f3d-b56e-6eb84d00a0a5.PNG)
![wittig2](https://user-images.githubusercontent.com/17196047/227921387-01591de1-db0c-4d4e-865f-dd9e5c0a6f2c.PNG)
Vielleicht lassen dies sich weiter oben unterbringen.
Problematisch sind dann natürlich Personen wie Benedikt XVI. 
Vorschlag, hier die ersten 3-5 übernehmen und dann mit .... abbrechen

**Comment by mtrojan-ub** [comment]
Im Meeting besprochen: Setzen wir um, ähnlich wie in der DNB Ansicht
https://portal.dnb.de/opac.htm?method=simpleSearch&cqlMode=true&query=nid%3D189454474

"Andere Namen"

Bei mehr als 5 wird ein Link zum springen nach unten angezeigt.

**Comment by IxGe** [comment]
Verstehe ich nicht ganz. Bei Anselm Grün wird gar keine Verweisungsform ("Andere Namen") "oben" angezeigt

**Comment by mtrojan-ub** [comment]
Ja, das ist das Beispiel für @LysogorAndGmail der sich um die Umsetzung kümmern wird.

**Comment by mtrojan-ub** [comment]
Die Änderung ist jetzt auf ptah aktiv + kann dort getestet werden:
https://ptah.ub.uni-tuebingen.de/Authority/07741571X

Befindet es sich an der richtigen Stelle?

**Comment by thefass** [comment]
Sieht gut aus und ist m.E. auch an der richtigen Stelle. Danke!

**Comment by thefass** [comment]
Doch noch eine Korrektur. Wenn ein Sterbedatum angegeben ist, dann sollten die anderen Namen darunter sein, so dass Geburts- und Sterbedatum direkt untereinander stehen. 
Siehe: https://ptah.ub.uni-tuebingen.de/Authority/324757344

**Comment by mtrojan-ub** [comment]
Ist auf ptah nun korrigiert

**Comment by thefass** [comment]
ok
