### ISSUE TITLE
Klick auf Personensymbol führt zu Fehler

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#2437]
Ein Klick in der Kurztitelanzeige auf das Personensymbol führt zu einer Fehlermeldung:
https://www.ixtheo.de/Search/NewItem?hiddenFilters%5B%5D=first_indexed%3A%22%5BNOW-1DAY+TO+NOW%5D-id%3ALR%2A%22&range=1&department=&filter%5B%5D=is_open_access%3A%22open-access%22
<img width="720" alt="Bildschirm­foto 2023-04-18 um 23 35 59" src="https://user-images.githubusercontent.com/14169098/232910987-19b17427-e47a-40e2-82b5-3429148706bb.png">

<img width="1122" alt="Bildschirm­foto 2023-04-18 um 23 39 41" src="https://user-images.githubusercontent.com/14169098/232911264-c684f393-fe18-41af-b9d3-2d49cf00f752.png">

https://www.ixtheo.de/Authority/77754721X&hiddenFilters%5B%5D=first_indexed%3A%5BNOW-1DAY+TO+NOW%5D-id%3ALR%2A

****
In derm Volltitelanzeige tritt der Fehler nicht auf

**Comment by mtrojan-ub** [comment]
Das haben wir vor Kurzem auch entdeckt / ist bereits in Bearbeitung. Wir hatten es ursprünglich für einen VuFind 9 bezogenen Fehler gehalten aber er scheint auch in der aktuellen 8.1 enthalten zu sein.

**Comment by mtrojan-ub** [comment]
Wir müssen hier zwar unseren eigenen Code anpassen aber es handelt sich eigentlich um ein vufind-org Problem, d.h. ich werde auch in der Community dazu nachfragen.

**Comment by mtrojan-ub** [comment]
Mit etwas Glück schafft es dieser Bugfix sogar noch ins 9.0-Release: vufind-org/vufind#2841

Da wir aber voraussichtlich erst im Herbst auf die 9.0 gehen, werden wir unseren 8.1 Code voraussichtlich auch schon deutlich vorher anpassen.

**Comment by mtrojan-ub** [comment]
Der Fix ist in die 9.0 eingeflossen, Backport in unsere aktuelle 8.1 ist noch in Arbeit.

**Comment by mtrojan-ub** [comment]
Ready for testing auf ptah

**Comment by thefass** [comment]
auf ptah ok
