### ISSUE TITLE
FAQ Zweitveröffentlichungsservice

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#244]
... bitte in RelBib A-Z einstellen - analog zu IxTheo. Hier das zu verlinkende Dokument:

[Zweitveroeffentlichung_FAQ.pdf](https://github.com/ubtue/tuefind/files/1879179/Zweitveroeffentlichung_FAQ.pdf)

Bezeichnung der Zeile:
**Zweitveröffentlichung**
Frequently Asked Questions (FAQ) zu urheberrechtlichen Fragen bei der Zweitveröffentlichung.

**Comment by ruschein** [comment]
@relhei Auf Ptah.

**Comment by relhei** [comment]
Super. Vielen Dank!
