### ISSUE TITLE
Fehlendes Button fürs Abonnieren / Alerting einer Zeitschrift

### ISSUE THREAD

**Issue by derclou** [ubtue/tuefind#2461]
Ich bin auf zwei Zeitschriften gestoßen, die ich gern für die Alerting-Funktion abonnieren würde (für die Sacherschließung in Verbindung mit MeisterTask), aber für diese Zeitschriften gibt es kein entsprechendes Button (bzw. kein "Glöckchen"-Icon). Es handelt sich um die Zeitschriften "The American Benedictine Review" und "Reformed World", beide in der elektronischen Version. Gibt es im allg. eine Möglichkeit, das Alerting für eine Zeitschrift zugänglich zu machen? Vielen Dank.

**Comment by jriedl** [comment]
Eine der Voraussetzungen für die Abonnierbarkeit einer Zeitschrift ist, dass das Erscheinen nicht abgeschlossen ist. Hierfür wird geprüft, ob in MARC 008 ab der Stelle 11 9999 und kein Enddatum steht.
Sowohl bei der elektronischen Ausgabe von "The American Benedictine Review" (PPN 632417129) als auch von "Reformed world" (PPN 175821256X) ist in 008 ein Enderscheidnungdatum 2013 bzw 2019 angegeben.  Diese Daten werden auch im Erscheinungsverlauf auch in der Volltitelanzeige angegeben.  Deshalb ist es überraschend, dass hier bei "The American Benedictine Review" neun aktuelle Aufsätze als untergeordnete Werke fungieren, vermutlich gehören diese ebenfalls an die Druckausgabe. Die Druckausgaben (166553670 + 166758434) sind jeweils abbonierbar.

**Comment by derclou** [comment]
Vielen Dank für diese Info, ich habe sie an die Katalogisierung weiter gegeben, die müssen dann die entsprechenden Angaben im Datensatz der Zeitschriften ändern.
