### ISSUE TITLE
PPNs Bochumer Reihe

### ISSUE THREAD

**Issue by JMeister01** [ubtue/tuefind#2472]
Bitte bei elektronischen Titeln der Bochumer Reihe Referenzen auf PPNs zuvor erschienener analoger Titel mitanzeigen.

Z.B.: 
1011814021 => 483669636
1006424857 => 336154828

**Comment by mtrojan-ub** [comment]
@LysogorAndGmail: Here's an example for KrimDok, but i assume that IxTheo should be affected by this issue as well:
https://sobek.ub.uni-tuebingen.de/Record/1011814021

The reference is part of 776. I guess we should add it to the `Related Items` section (see `RecordDataFormatterFactory`).

**Comment by mtrojan-ub** [comment]
Kann auf sobek + ptah getestet werden

**Comment by JMeister01** [comment]
Sieht gut aus! Vielen Dank!
