### ISSUE TITLE
Angabe "Land" im Benutzerkonto überarbeiten

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#2479]
Länder scheinen mischsprachig zu sein, z.B. "Germany" aber auch "Ägypten". Da die Information potenziell strukturiert für verschiedene Dienste genutzt werden soll (z.B. KfL, DoD) wäre es besser, in der DB ein ISO Länderkürzel zu speichern und für die Anzeige abhängig von der gewählten Benutzersprache dynamisch zu übersetzen.

Dafür könnte man entweder das PHP intl Modul verwenden, oder alternativ auch das symfony/intl modul (müsste per composer installiert werden):
https://symfony.com/doc/current/components/intl.html#country-names

![grafik](https://github.com/ubtue/tuefind/assets/26873381/224ac98f-8f4f-470f-a4fc-10a8ff03821b)

**Comment by mtrojan-ub** [comment]
In der FID-Runde besprochen: @relhei testet

**Comment by mtrojan-ub** [comment]
Noch ein Hinweis: Für IxTheo/Relbib und Derivate müsste das so funktionieren. Falls wir das auch eines Tages für KrimDok nutzen möchten, muss es aber von der ixtheo_ auf die tuefind_ ebene verschoben werden.

**Comment by mtrojan-ub** [comment]
Für die Sprachen wird die Bibliothek `symfony/intl` verwendet, aktuell in der Version 5.4.23. Wenn man die Benutzeroberfläche auf Englisch anschaut, dann steht an der Stelle "Tuvalu", im Deutschen aber "Elliceanisch" wie Du schon sagst => selbst wenn die Bezeichnung korrekt wäre, so wäre es falsch sortiert.

Wir könnten also höchstens mal prüfen ob es in der aktuellen 5er-Version (5.4.25) immer noch so ist und falls nicht es an den Hersteller kommunizieren.

**Comment by mtrojan-ub** [comment]
Wie sich herausgestellt hat war es in der Library doch korrekt, es wurde aufgrund eines Template-Problems nochmal durch die reguläre Übersetzungsroutine gejagt und dadurch kam der Fehler zustande.

Ist jetzt korrigiert + ready for testing auf ptah

**Comment by relhei** [comment]
Das passt jetzt. Danke!
