### ISSUE TITLE
Auto-complete funktioniert nicht

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#248]
![grafik](https://user-images.githubusercontent.com/25769591/38611939-72696044-3d85-11e8-9db4-fdd02975c983.png)

**Comment by jriedl** [comment]
Funktioniert auf ptah.

**Comment by jriedl** [comment]
Nachtrag: Dass die bereits gefixte Funktionalität noch nicht auf ub16 ist, liegt an grundlegenden, in der Entwicklung befindlichen Änderungen im Zusammenhang mit der Zusammenführung von Records. Deshalb bislang hier noch kein Update.

**Comment by Gazeller** [comment]
funktioniert heute!

**Comment by relhei** [comment]
Super, vielen Dank!
