### ISSUE TITLE
Doppelung bei der Anzeige der Bibelstellen

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#2482]
Es kommt teilweise zu einer Doppelung in der Anzeige 
z.B Bibel Bibel. Apostelgeschichte 10,34-43
in anderen Bibelstellen ist das korrekt: Bibel. Apostelgeschichte 15,1-29

siehe: https://ixtheo.de/Authority/37339201X
<img width="819" alt="Bildschirm­foto 2023-06-22 um 08 28 26" src="https://github.com/ubtue/tuefind/assets/14169098/56a8a1b0-5531-4c88-a9ac-af1e5c260f2c">

Wenn man auf die Stellen klickt, dann wird ja eine Suche ausgeführt. Bei der korrekten Stelle, ist die Suche erfolgreich:
<img width="1174" alt="Bildschirm­foto 2023-06-22 um 08 32 02" src="https://github.com/ubtue/tuefind/assets/14169098/3bd8aac1-5460-407c-b89b-b3d65fc3a2ff">
Bei der falschen Stelle, ist die Suche fehlerhaft:
<img width="1161" alt="Bildschirm­foto 2023-06-22 um 08 32 50" src="https://github.com/ubtue/tuefind/assets/14169098/d29d480f-bec5-4be7-aeb3-163dbfe30c52">

**Comment by IxTheoKm** [comment]
Das ist auch in https://github.com/ubtue/tuefind/issues/1202 thematisiert.

**Comment by jriedl** [comment]
Sollte im Rahmen der Anpassungen für #1202 auf ptah behoben sein.

**Comment by thefass** [comment]
Danke
