### ISSUE TITLE
Unvollständige Anzeige von 689 Unterfeld l

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#2485]
Sowohl in der Vollanzeige als auch in der Facette fehlt das Unterfeld $l

Bsp.: 
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=id%3A1799901955&type=AllFields

![Bibel_deutsch2](https://github.com/ubtue/tuefind/assets/17004223/915e7a8e-dc6d-4f4b-a574-5466c3aaffe2)

https://ptah.ub.uni-tuebingen.de/Record/1799901955#details

![Bibel_deutsch3](https://github.com/ubtue/tuefind/assets/17004223/ff10abe4-ae81-46ac-aef8-a1e26c24ee87)

![Bibel_deutsch](https://github.com/ubtue/tuefind/assets/17004223/9c50bc6c-b381-4437-8f32-06110bb48b26)

**Comment by jriedl** [comment]
Auf ptah.

**Comment by IxTheoKm** [comment]
Danke, wird jetzt angezeigt!
