### ISSUE TITLE
Neu eingespielte Brill Daten werden nicht als Review facettiert

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#249]
Der Datensatz https://ixtheo.de/Record/501845119 ist eine Rezension und in den Metadaten als solche in Feld 935 |c uwre auch gekennzeichnet.
Er taucht aber nicht in der Facette auf.

Hier ist er auf Platz 6: superior_ppn:271497904
Wenn man aber auf Review einschränkt, dann sind die letzten Reviews von 2017.

Wird 935 |c uwre ausgewertet?

**Comment by ruschein** [comment]
https://ptah.ub.uni-tuebingen.de/Record/501845119

**Comment by thefass** [comment]
ist ok
