### ISSUE TITLE
Vermerk "in" in der Titelbeschreibung

### ISSUE THREAD

**Issue by jjspp01** [ubtue/tuefind#250]
ppn 469199997: warum erscheint hier "in". Es handelt sich bei dem Titel um eine Monographie, die nicht in einer Schriftenreihe erschienen ist.  Kann es sein, dass durch die Kategorie 776 im Marcformat, welche auf die Druckausgabe verweist, dieses "in" erzeugt wurde? Ist mir bei anderen Einträgen auch aufgefallen.

**Comment by thefass** [comment]
Der Link nach in: funktioniert auch nicht

**Comment by ruschein** [comment]
Auf Sobek: https://sobek.ub.uni-tuebingen.de/Record/469199997

**Comment by thefass** [comment]
funktioniert
