### ISSUE TITLE
Angabe "Land" im Benutzerkonto (für KrimDok)

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#2506]
Follow-up für #2479 (sollte erst abgeschlossen werden)

Bisher steht diese Angabe nur in IxTheo-Systemen zur Verfügung. Da wir aber potenziell in allen FIDs die KfL-Funktionalität nutzen wollen wäre es sinnvoll, das auch in KrimDok freizuschalten (kann Auswirkungen auf die verfügbaren Lizenzen haben).

(Die Funktionalität sollte also von der IxTheo auf die TueFind-Ebene verschoben werden)

**Comment by mtrojan-ub** [comment]
Da es für die neue Förderperiode auf der Liste steht, habe ich das label "deferred" entfernt.

**Comment by mtrojan-ub** [comment]
ready for testing auf ptah+sobek

**Comment by thefass** [comment]
funktioniert auf ptah, sogar mehrsprachig

**Comment by mtrojan-ub** [comment]
Ich schließe diesen Issue, es funktioniert ja seit einiger Zeit bereits zuverlässig.
