### ISSUE TITLE
Änderung Formular "Titel vorschlagen" in KrimDok

### ISSUE THREAD

**Issue by JMeister01** [ubtue/tuefind#2508]
Bitte Text unter "Titel vorschlagen" auf der KrimDok-Oberfläche folgendermaßen ändern:

_Sie möchten einen Titel zur Anschaffung oder zur Aufnahme in KrimDok vorschlagen? Dies können Sie uns gerne auf dem folgenden Formular mitteilen. (Alle Bücher, die wir erwerben, werden in KrimDok nachgewiesen.)_

Zusätzlich zum Anklicken:

_Anschaffung (nur Bücher)
Aufnahme in KrimDok_

Dann darunter:

_Gerne können Sie auch Schlagwörter vergeben:_
_Leere Zeile für Schlagwörter einfügen_

Keine Änderung bei IxTheo oder RelBib (ist besprochen).

**Comment by mtrojan-ub** [comment]
Und wie genau lauten die Texte auf Englisch?

**Comment by JMeister01** [comment]
Entschuldigung. Hier die Englische Übersetzung:

You would like to suggest a title for acquisition or referencing in KrimDok? Please let us know using the following form. (All books we acquire are listed in KrimDok.)

Acquisition (books only) 
Referencing

You are also welcome to assign keywords.

**Comment by mtrojan-ub** [comment]
Habe sie euch beiden soeben weitergeleitet

**Comment by JMeister01** [comment]
Funktioniert. Vielen Dank!
