### ISSUE TITLE
Fehlende Zusätze beim Ort im Autorensteckbrief

### ISSUE THREAD

**Issue by IxGe** [ubtue/tuefind#2530]
Sowohl im Feld geboren wie im Feld Geographischer Bezug fehlt der Zusatz (Landkreis Ravensburg)
Wie es richtig aussieht, s. https://portal.dnb.de/opac.htm?method=simpleSearch&cqlMode=true&query=nid%3D13773039X

![gebhard](https://github.com/ubtue/tuefind/assets/17196047/cdb4e096-700a-4fca-90ac-76cadb988898)

**Comment by obrandt** [comment]
Wenn das nicht geolokalisiert ist, braucht es das definitiv nicht. Schafft nur Verwirrung und bläht das System nur unnötig auf. Und frisst zwischendrin wieder sehr viel Zeit fürs Entwickelkungsteam mit viel hin und her.🙄

Olaf Brandt
Fachreferent Informatik
Leiter IT-Abteilung
UB Tübingen
________________________________

**Comment by thefass** [comment]
Viele Daten (nicht alle) sind geolokalisert. Zumindest sehe ich die Koordinaten hier in diesem GND Satz:
http://gnd.eurospider.com/s?q=4065156-3&s=&p=1&e=g&i=sfA&sm=m&so=r
Rechts im Filter "Weitere Aktionen" sind Links auf GeoNames und GoogleMaps

**Comment by mtrojan-ub** [comment]
Ich kenne das Problem aus dem privaten Umfeld... meine Frau hat an der PH Weingarten studiert und da kam es mehrfach vor, dass ein Gastprofessor einen Vortrag halten sollte und nicht aufgetaucht ist da er ins falsche Weingarten gefahren ist...

Zum bereits erwähnten Beispiel:
https://ixtheo.de/Authority/696016818

Vorteil ist: Der Landkreis ist in diesem Fall bereits in 551g enthalten und könnten wir relativ einfach anzeigen. Alterativ (oder zusätzlich) könnte man auch relativ einfach (ähnlich wie auf der DNB Seite) auch auf die DNB Detailseite verlinken, wo auch Geo-Koordinaten usw vorhanden sind. 
Für alles andere müsste man erst die Referenz im Rahmen der Pipeline gegen die Normdaten auflösen und die Querverweise anreichern um es hier anzeigen zu können, davon würde ich abraten.

**Comment by mtrojan-ub** [comment]
Die "kleine" Anpassungsvariante ist jetzt auf ptah zu sehen (Landkreis wird mit angezeigt):
https://ptah.ub.uni-tuebingen.de/Authority/696016818

Bei Bedarf wäre wie gesagt das Hinzufügen eines Links auf die DNB Seite des Ortes auch relativ einfach möglich, aber auslesen von Geo-Koordinaten aus den Normdaten zwecks Link-Generierung auf eine Karte o.Ä. deutlich aufwendiger.

Ich setze es auf ready for testing und hoffe dass eine der kleineren Lösungen ausreicht.

**Comment by IxGe** [comment]
Das sieht gut aus und reicht aus meiner Sicht vollkommen.
