### ISSUE TITLE
Unerwünschter Titel in RelBib

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#254]
Nach Sichtung des Internformats ist nicht klar, warum dieser Titel in RelBib erscheint:
https://relbib.de/Record/482380403#details
- keine passende SSG-Nr.
- keine passende DDC
- keine passende Notation
??
Nach den Daten-Abzugskriterien (Wiki) dürfte der Titel nicht in RelBib landen, oder?

Hier einige weitere Fälle:
https://relbib.de/Record/450505170#details

https://relbib.de/Record/494233222#details

https://relbib.de/Record/50101358X#details

**Comment by relhei** [comment]
Sind im Wiki möglicherweise die falschen DDC-Gruppen angegeben? In Feld 082a: 400 statt (richtig) 300 und 800 statt (richtig) 900?

**Comment by jriedl** [comment]
Die Angaben zu im Wiki waren unpräzise/nicht korrekt. Ist jetzt aktualisiert. Für die o.g. Titel fallen die DDCs nicht unter die expliziten Ausschlusskriterien und finden sich deshalb in Relbib.

**Comment by relhei** [comment]
Ok, das erklärt diesen Fall. Die Ausschlusskriterien bedürfen nochmals Diskussion in einer Sitzung.
