### ISSUE TITLE
Kein Rückgriff mehr auf alle Titel nach Filtern der Neuzugänge

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#2548]
Schritte:
1. Neuzugänge gestern (547 Treffer)
<img width="1050" alt="Bildschirm­foto 2023-09-14 um 14 20 20" src="https://github.com/ubtue/tuefind/assets/14169098/70707d5a-8847-40a7-94f7-9c6cdd6e77e0">

2. Neuzugänge einschränken auf Verlag "EOS" (76 Treffer)
<img width="1166" alt="Bildschirm­foto 2023-09-14 um 14 33 05" src="https://github.com/ubtue/tuefind/assets/14169098/fb2ca3d4-2b8a-4e1b-8223-f8110e133eb6">

3. Klick auf Filter zurücksetzen (wieder 547 Treffer)
4. Klick auf Suchen: das  führt nun nicht mehr zur Gesamtmenge der IxTheo Treffer (3,71 Mio), sondern liefert wieder die 547 Treffer

**Comment by mtrojan-ub** [comment]
Das Problem ist so aktuell nicht mehr reproduzierbar. Kannst Du bitte prüfen ob es immer noch auftritt?

Nach "gestern" können wir aktuell nicht suchen, da wir aufgrund der Wartungsarbeiten im K10plus erst im Lauf der Woche wieder neue Daten erhalten. Alternativ haben wir es mit der Einstellung für 7 Tage getestet, wobei die Anzahl der Tage für die Problematik keine Rolle spielen sollte.

Man sieht es an dem Parameter "hiddenFilters" in der URL. Beim Wechseln in die Suche für Neuzugänge werden zusätzliche Informationen angehängt, z.B. `?hiddenFilters[]=first_indexed%3A"[NOW-7DAY+TO+NOW]`. 

Beim Klicken auf `Filter zurücksetzen` (Schritt 3) bleibt der Parameter in der URL erhalten. Das ist auch so gewollt. Ziel der Suche ist hier immer noch `Search/NewItem`. 

Klickt man dann aber wieder auf den `Suchen`-Button springt die Suche aktuell von `Search/NewItem` wieder auf die normalen `Search/Results` zurück. Somit hat man ja wieder das gewünschte Verhalten.

**Comment by thefass** [comment]
ja, jetzt ist alles in Ordnung. Ich kann den Fehler auch nicht mehr reproduzieren. Aber schon komisch, dass es ihn vor einiger Zeit gegeben hat :-)
