### ISSUE TITLE
Online-Zs nicht als "Medientyp: elektronisch" angezeigt

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#255]
Obwohl es sich um eine O-Aufnahme handelt, wird die Zs nicht als "elektronisch" angezeigt:
https://relbib.de/Record/501961550#details

**Comment by ruschein** [comment]
Das Problem dürfte behoben sein aber der Datensatz existiert nicht mehr auf Ptah, da er mit dem Datensatz mit der PPN 491021372 kombiniert wurde:

**Comment by relhei** [comment]
Warum steht nicht "elektronisch" dabei? Vmtl. stimmt irgend etwas mit der Aufnahme im SWB nicht. Ich habe schon die Frage weitergegeben. Issue bleibt vorerst offen.

**Comment by ruschein** [comment]
@relhei Ich dachte bei der Detailansicht wird elektronisch, bzw. nichtelektronisch nie angezeigt?

**Comment by relhei** [comment]
Hat sich erledigt. Danke!
