### ISSUE TITLE
Schlagwort aus Feld 611 wird nicht angezeigt

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#2582]
https://ixtheo.de/Record/1665440031
https://ixtheo.de/Search/Results?lookfor=superior_ppn:1665440031

Alle 18 Beiträge enthalten als Einzelschlagwort (PICA 5580) neben weiteren Schlagwörtern in MARC 650 das Schlagwort
**611** 27$0(DE-588)2024452-6$0(DE-627)102164738$0(DE-576)191770337 **$aVatikanisches Konzil$n1.$d1869-1870$cVatikanstadt** $2gnd

### 611 wird in den Einzeltreffern unter "weitere Schlagwörter" nicht angezeigt.

In der Facette "Thema (Schlagwort)" taucht es zwar auf, aber unvollständig ohne die Unterfelder:
![611_VatKon](https://github.com/ubtue/tuefind/assets/17004223/7148259d-7aea-47d8-93f3-6d9b20851f3d)

**Comment by IxTheoKm** [comment]
Ich prüfe das dann noch. 

Was die Zählung betrifft: nein, die muss nicht nach vorne geschoben werden. Die wird auch in anderen (Verbund-)Katalogen genau in der Reihenfolge angezeigt, wie sie erfasst ist.

**Comment by IxTheoKm** [comment]
Bsp.:
https://opac.k10plus.de/DB=2.299
![VatKon](https://github.com/ubtue/tuefind/assets/17004223/2692c245-b81d-4e76-af32-a7129014d2a7)

**Comment by IxTheoKm** [comment]
In der Facette werden die Zählungen jetzt überall angezeigt.

Allerdings fehlen alle Schlagwörter aus Feld 611 in den Vollanzeigen der Bände komplett, auch wenn sie in der Facette Schlagwort auftauchen:

https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=superior_ppn:1665440031
bzw.
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=superior_ppn%3A1665440031&type=AllFields&filter%5B%5D=topic_facet%3A%22Vatikanisches+Konzil+1.+%281869-1870%29+Vatikanstadt%22

**Comment by jriedl** [comment]
Wäre die Facettenanzeige dann in der aktuellen Umsetzung ok?

**Comment by jriedl** [comment]
> In der Facette werden die Zählungen jetzt überall angezeigt.
> 
> Allerdings fehlen alle Schlagwörter aus Feld 611 in den Vollanzeigen der Bände komplett, auch wenn sie in der Facette Schlagwort auftauchen:
> 
> https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=superior_ppn:1665440031 bzw. https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=superior_ppn%3A1665440031&type=AllFields&filter%5B%5D=topic_facet%3A%22Vatikanisches+Konzil+1.+%281869-1870%29+Vatikanstadt%22

611 ist aktuell tatsächlich nicht Teil der ausgewerteten Felder für die nicht-standardisierten Schlagwörter. Sobald die Anzeige in der Facette geklärt ist, erfolgt eine analoge Umsetzung.

**Comment by IxTheoKm** [comment]
> Wäre die Facettenanzeige dann in der aktuellen Umsetzung ok?

Ich finde ja. 
Die Klammerung "Kongressname Zählung. (Jahr : Ort)" entspricht auch derjenigen vom Feld 689 in der Vollanzeige (Bsp.: https://ixtheo.de/Record/1684437857)

Eigentlich wäre es auch gut, 689 in der Facette analog zu 611 klammern (Bsp.: https://ixtheo.de/Search/Results?lookfor=id%3A1684437857&type=AllFields). Dort sind bisher gar keine Klammern angegeben.

**Comment by jriedl** [comment]
Sowohl in der Facette als auch in der Volltitelanzeige wird nun $d in der Anzeige in Klammern gesetzt. Für PPN 1767230303 bereits jetzt auf ptah sichtbar, für alle weiteren nach Abschluss des nächsten Imports. Dass 689$d in der Facette nun ebenfalls geklammert wird, ist Folge der vorherigen Anpassung und deshalb auf ptah bereits vollständig umgesetzt (vgl. z.B. https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=id%3A1684437857&type=AllFields).

**Comment by IxTheoKm** [comment]
Was die Klammerung betrifft bin ich ehrlich gesagt leidenschaftslos. Sie soll die Anzeige ja nur etwas übersichtlicher erscheinen lassen. 
Aber gibt es einen Grund, warum die Facette anders behandelt wird als die Vollanzeige?

In der Vollanzeige sieht es so aus: "Kongressname Zählung. (Jahr : Ort)"  also $d und $c stehen in der Klammer getrennt durch Doppelpunkt.
https://ptah.ub.uni-tuebingen.de/Record/1684437857

In der Facette steht nur $d in der Klammer. Die würde ich analog zur Vollanzeige klammern.

**Comment by jriedl** [comment]
Das würde kompliziert: für die Facetten (die sowohl standardisierte als auch nicht-standardisierte Schlagwörter umfassen) wurde ein damals ein Ansatz umgesetzt, der ein einzelnes Feld behandeln kann, d.h. es kann definiert werden, mit welchem Zeichen ein Unterfeld abgetrennt wird und zusätzlich eben noch die Möglichkeit, ein einzelnes Feld zu klammern. Für die 689-Schlagwörter haben wir über die Jahre eine lange Reihe von Spezialbehandlungen implementiert, und darunter fällt auch, dass wenn $d von $c gefolgt ist, dann beides mit Doppelpunkt getrennt geklammert wird. Damit das in der Facette analog funktionieren würde, müssten wir alles aufschnüren, die gesamte Behandlungslogik der 689-Felder (die Schlagwortfolgen sind und deshalb beim Import auch als Folge aufgebaut werden) in der Darstellung von Unterfeldern auf die nicht-standardisierten Schlagwörter übertragen und analog neu implementieren, wobei noch nicht völlig sicher ist, dass sich die Feldbelegungen und -trenner zwischen 689 und den anderen 6XX-Feldern im Allgemeinen wirklich entsprechen.
