### ISSUE TITLE
Personenseiten: Visualisierung der Publikationen im Zeitverlauf

### ISSUE THREAD

**Issue by NMagin** [ubtue/tuefind#2584]
Momentan wird im nach Jahren sortierten Balkendiagram auf der Personenseite nicht zwischen Werken von den Autoren und über die Autoren unterschieden, sondern alle Publikationen von einem Autor in beiden Katergorien gezählt. Soweit ich das sehe, fallen die Werke über den Autor einfach weg.
So sieht es im Testsystem aus: 
![Screenshot 2023-11-02 at 17-44-12 Internformat Seiwert Hubert 1949-](https://github.com/ubtue/tuefind/assets/109666609/27d7dec2-2a3a-420f-a32e-fbc3eaace49c)
und so im Live-System:
![Screenshot 2023-11-02 at 17-46-49 Internformat Seiwert Hubert 1949-](https://github.com/ubtue/tuefind/assets/109666609/51f2f0a1-0f5a-44c9-8fe5-39dcf71ca057)

Die Personenseite, an der ich es getestet habe: https://134.2.67.9/AuthorityRecord/08049854X bzw. https://relbib.de/Authority/08049854X

Im IxTheo tritt das Problem auch auf. KrimDok konnte ich nicht prüfen, da dort der Zugriff auf die Personenseiten schon nicht funktioniert. Da mache ich ein gesondertes Issue auf.

**Comment by mtrojan-ub** [comment]
Wurde auf ptah behoben, bitte nochmal testen

**Comment by coeh** [comment]
Sieht auf IxTheo jetzt gut aus, danke! Wie ist es auf RelBib, @NMagin ?

**Comment by NMagin** [comment]
In RelBib sieht es jetzt auch gut aus. Dankeschön!

Ich mach dann mal hier zu.
