### ISSUE TITLE
Fehlermeldung im Feld "Veröffentlicht in" bei monografischen Reihen 

### ISSUE THREAD

**Issue by coeh** [ubtue/tuefind#2586]
In der Vollanzeige von Bänden aus monografischen Reihen erscheint bei Anklicken des Reihentitels im Feld "Veröffentlicht in" eine Fehlermeldung (Beispiel: PPN 1681820447, https://ixtheo.de/Record/1681820447).

Das Problem tritt sowohl auf ptah als auch auf dem Produktivsystem auf, ist also nicht durch das Upgrade verursacht. Es ist in #1799 bereits aufgefallen, wo sich die Diskussion aber auf andere Teilfragen verlagert hat.

Nach Diskussion und gemeinsamer Recherche mit @IxTheoKm scheint uns die Ursache zu sein, dass bei Anklicken eines Reihentitels im Feld "Veröffentlicht in" eine Suche mit &type=JournalTitle ausgelöst wird, im Beispielfall https://ixtheo.de/Search/Results?lookfor=%22Z%C3%BCrcher+Beitr%C3%A4ge+zur+Reformationsgeschichte%22&type=JournalTitle . Dies führt bei Zeitschriftenbänden zu korrekten Ergebnissen, Beispiel https://ixtheo.de/Search/Results?lookfor=%22Marburger+Jahrbuch+Theologie%22&type=JournalTitle. Bei monografischen Reihen müsste aber, damit korrekt die Reihe gefunden wird, mit &type=Series gesucht werden, wie es bei Anklicken des Reihentitels im Feld "Schriftenreihe/Zeitschrift" auch geschieht, im Beispiel: https://ixtheo.de/Search/Results?lookfor=%22Z%C3%BCrcher+Beitr%C3%A4ge+zur+Reformationsgeschichte%22&type=Series.

Vorschlag: Kann das Problem bis zu einer endgültigen Klärung von #1466 sowie #1799 , die aufgrund der Komplexität wohl noch einige Zeit in Anspruch nehmen wird, dadurch entschärft werden, dass bei Anklicken eines Titels im Feld "Veröffentlicht in" entweder bei monografischen Reihen mit &type=Series statt mit &type=JournalTitle gesucht wird, oder - falls eine Unterscheidung von Zeitschriften und monografischen Reihen hier technisch nicht ohne weiteres möglich ist - bei allen Zeitschriften und Reihen stets mit  &type=Series OR &type=JournalTitle ?

**Comment by mtrojan-ub** [comment]
Kann auf ptah getestet werden. Es wird jetzt ein Suchstring ähnlich wie in der erweiterten Suche generiert.
https://ptah.ub.uni-tuebingen.de/Record/1681820447

**Comment by coeh** [comment]
Vielen Dank! Das sieht mir jetzt viel besser aus - kannst du bitte auch noch einmal schauen, @IxTheoKm ? Es wird beim Anklicken des Felds zwar nicht nur die Gesamtaufnahme der Reihe angezeigt, sondern auch alle Einzelbände - und sogar auch Rezensionen über die Bände - , aber das ist bei einer Suche allein nach type=series (anders als bei type=JournalTitle) auch der Fall. M.E. stellt es für die Nutzenden auch kein Problem dar.

**Comment by IxTheoKm** [comment]
**Im Prinzip ist es so okay, finde ich (die Doppelung von #1799 muss dort aber noch geklärt werden).**

> Es wird beim Anklicken des Felds zwar nicht nur die Gesamtaufnahme der Reihe angezeigt, sondern auch alle Einzelbände - und sogar auch Rezensionen über die Bände -

### Das kann ich nicht bestätigen:
https://ptah.ub.uni-tuebingen.de/Record/1681820447

![ZürBei](https://github.com/ubtue/tuefind/assets/17004223/6f695555-ea6d-46fd-b4dc-8ff21c868d53)

### Unter "Veröffentlicht in:" mit den Suchbegriffen Serie... und JournalTitle... kommen nur die Bände (erkennbar auch in der Facette Medienart)

### Unter "In:" kommt man mit der entspr. PPN korrekt auf die übergeordnete Reihenaufnahme. ###

### Unter "Schriftenreihe/Zeitschrift:" kommt man auch nur auf Bände. ###

**Comment by coeh** [comment]
In Bezug auf die Rezensionen muss ich mich korrigieren - da hatte ich Treffer Nr. 11 zu hastig gelesen. In der Tat ist auch das ein Band (bei dem nur die Rezension mit in der Titelaufnahme verzeichnet ist). Entschuldigung!
Worauf ich hinaus wollte, war die Frage, über die wir mündlich gesprochen hatten: wird beim Klick auf "Veröffentlicht in:" wie bei "journalTitle" allein nur die Gesamtaufnahme der Zeitschrift angezeigt, oder eben, wie bei "series", auch die Einzelbände. Ich denke auch, das ist richtig. Wenn es auch nach deiner Einschätzung so in Ordnung ist, ist das im vorliegenden Issue diskutierte Problem gelöst (und es verbleibt nur noch die Frage bei #1799 )

**Comment by thefass** [comment]
Diese Issues wird obsolet, wenn wie in #1799 die Zeile "Veröffentlicht in" gelöscht wird. Ich schließe deswegen.
