### ISSUE TITLE
Falsche Beschriftungen auf Startseite

### ISSUE THREAD

**Issue by coeh** [ubtue/tuefind#2587]
Das dritte Feld von links unterhalb der Suchleiste ist auch bei Spracheinstellung deutsch mit „Need Help?“ statt „Hilfe“ beschriftet.
![grafik](https://github.com/ubtue/tuefind/assets/83448862/c9a567fc-e3ba-4d4f-b1d0-c08da029d0ab)

Ebenso steht ganz unten in der Fußleiste in der linken Spalte als Überschrift „Search Options“ statt „Suchoptionen“ und in der rechten Spalte als Überschrift „Need help?“ statt „Hilfe“.
![grafik](https://github.com/ubtue/tuefind/assets/83448862/15591cab-be4f-45a5-818a-ed1e59287b50)

**Comment by mtrojan-ub** [comment]
ready for testing auf ptah

**Comment by coeh** [comment]
Sieht gut aus, danke! Ich schließe daher.
