### ISSUE TITLE
Einzeltitelanzeige: Symbole auf Schaltflächen fehlen

### ISSUE THREAD

**Issue by coeh** [ubtue/tuefind#2588]
In der Einzeltitelanzeige fehlen in der Leiste oberhalb des Titels alle Symbole auf den Schaltflächen bzw. werden durch Platzhalter ersetzt. Beispiel: https://ptah.ub.uni-tuebingen.de/Record/164540840X 
Optik auf ptah:
![grafik](https://github.com/ubtue/tuefind/assets/83448862/7d7fc599-9fb9-4a4d-a0d4-5865e161fdb3)

Korrekt auf dem Produktivsystem:
![grafik](https://github.com/ubtue/tuefind/assets/83448862/60da39d2-b422-483a-a51d-d2f57550cc29)

**Comment by coeh** [comment]
Durch #2590 mit erledigt? (dort schon Ausführungen zu diesen Symbolen und nicht nur zu dem genannten. Mir sieht jetzt auch die Höhe gut aus.)

**Comment by mtrojan-ub** [comment]
Ja das ist im Wesentlichen die gleiche Baustelle. Wie gesagt, wir schauen gerade noch nach Browser-Kompatibilität aber ansonsten müsste das behoben sein

**Comment by mtrojan-ub** [comment]
ready for testing auf ptah
