### ISSUE TITLE
Personenseiten: Symbol auf Schaltfläche fehlt

### ISSUE THREAD

**Issue by coeh** [ubtue/tuefind#2590]
Ähnlich wie bei der Einzeltitelanzeige fehlt bei der Schaltfläche "Zugriffsrechte beantragen" auf den Personenseiten das Stern-Symbol.
Optik auf ptah:
![grafik](https://github.com/ubtue/tuefind/assets/83448862/e26a8a26-e00f-45c0-b063-86b3846ae6e1)

Korrekt auf dem Produktivsystem:
![grafik](https://github.com/ubtue/tuefind/assets/83448862/7b05eab3-1b20-4a9b-aa95-50e31c05c554)

**Comment by mtrojan-ub** [comment]
Das scheint auch viele andere Buttons + Symbole zu betreffen, z.B. in der Volltitelanzeige. Die Icons in den Buttons werden zwischenzeitlich wieder angezeigt bzw. haben wir repariert, allerdings scheinen die Icons vertikal nicht genau auf der gleichen Höhe zu sein wie die Schrift, das müssen wir nochmal prüfen:

![grafik](https://github.com/ubtue/tuefind/assets/26873381/dbb986c0-8325-4d48-9200-8f46c754f796)

**Comment by coeh** [comment]
Sieht gut aus, danke!
