### ISSUE TITLE
Bibelstellensuche/DDC-Suche: Anzeige Häufige Schlagwörter

### ISSUE THREAD

**Issue by coeh** [ubtue/tuefind#2591]
Nach Auslösen einer Bibelstellensuche (nur dann) wird unterhalb der Suchleiste das Feld „Häufige Schlagwörter innerhalb ihrer Suche“ angezeigt. Beispiel: https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=Mk+5%2C25-34+&type=BibleRangeSearch&limit=20&botprotect=
![grafik](https://github.com/ubtue/tuefind/assets/83448862/dce4d85a-fa2d-4913-b94f-fba9f2207555)

Nach meiner Erinnerung an unsere letzte Besprechung zum Design sollte dieses Feld überall ausgeblendet sein. Allerdings wird es nach Auslösen einer Bibelstellensuche auf dem Produktivsystem ebenfalls angezeigt. 

@thefass : Soll das geändert werden oder so bleiben?

**Comment by thefass** [comment]
Das sollte geändert werden

**Comment by mtrojan-ub** [comment]
Sieht so aus als wäre es nicht nur bei der Bibelstellensuche aktiv, sondern auch bei der Suche nach DDC-Klassifikation. Wir kümmern uns um die Anpassung.

**Comment by mtrojan-ub** [comment]
Wurde auf ptah/sobek angepasst und kann getestet werden

**Comment by coeh** [comment]
Sieht auf IxTheo jetzt gut aus, danke! Für RelBib und KrimDok verweise ich an @NMagin @JMeister01 (da anders als ursprünglich gedacht wohl nicht nur die - IxTheo-spezifische - Bibelstellensuche betroffen war).

**Comment by coeh** [comment]
@NMagin @JMeister01 bitte DDC-Suche auf euren Systemen noch prüfen.

**Comment by NMagin** [comment]
In RelBib wird das Feld nicht angezeigt, soweit ich sehe.

**Comment by JMeister01** [comment]
Wir hatten uns irgendwann bewusst gegen eine DDC-Suche in KrimDok entschieden.

**Comment by coeh** [comment]
@JMeister01 Ah, Entschuldigung - das hatte ich nicht im Kopf (ich hatte dich verlinkt, weil oben von sobek die Rede war). Dann können wir das Issue wohl als erledigt betrachten, vielen Dank!
