### ISSUE TITLE
IxTheo-Mastodon-Account hinzufügen

### ISSUE THREAD

**Issue by coeh** [ubtue/tuefind#2595]
Bislang ist auf der IxTheo Homepage (rechts unten) nur der Twitter-Account verknüpft. Wir würden hier gerne auch den IxTheo-Account bei Mastodon / im Fediverse einbinden: https://hcommons.social/@ixtheo

**Comment by mtrojan-ub** [comment]
Sollen wir eigentlich auch den Twitter Link und /oder das Logo austauschen (=> X)?

**Comment by coeh** [comment]
Politisch heikel. Ich würde es lieber vorläufig stehenlassen, so wie es ist - damit geben wir in keine Richtung ein Statement ab.

**Comment by thefass** [comment]
sehe ich genauso wei @coeh

**Comment by mtrojan-ub** [comment]
In dem Fall bitte ich auch um Prüfung durch @JMeister01 da wir das Symbol in KrimDok bereits ausgetauscht haben!

**Comment by JMeister01** [comment]
Wir haben das Symbol in KrimDok geändert, da die Plattform nun X heißt. Wenn man das Argument des politisches Statements anführen möchte, könnte man im Zuge der umfangreichen Überarbeitung von KrimDok ebenso eine politische Aussage unterstellen, wenn wir beim alten Logo geblieben wären.

**Comment by mtrojan-ub** [comment]
Zur initialen Anforderung / Mastodon: Ich habe den Mastodon-Link nun im IxTheo-Footer mit eingebunden. Da bislang auch im Index Biblicus und Index Canonicus der Link auf den IxTheo Twitter Kanal drin stand habe ich Mastodon auch in diesen beiden Systemen hinzugefügt. Passt das so?

Zum Thema Twitter / X: Wenn die Meinungen hier auseinander gehen, sollen wir das noch kurz in der FID-Runde besprechen?

**Comment by JMeister01** [comment]
Ja, das können wir gerne gleich besprechen.

**Comment by coeh** [comment]
Ich bin in der Runde gleich standardmäßig nicht dabei. Soll ich für dieses Thema dazukommen? (Dann bitte zoom-Link schicken.) Grundsätzlich stellt sich hier für mich auch die Frage, ob es auf allen Seiten einheitlich sein muss, zumal KrimDok seine Homepage aktualisiert hat, IxTheo bislang nicht.

**Comment by JMeister01** [comment]
Ich denke, das haben wir mit Martin schnell besprochen und du brauchst eigentlich nicht dabei zu sein. Wie es dir passt. Ich schicke dir trotzdem mal die Zugangsdaten: https://zoom.us/j/98490180317?pwd=UVRRei92WElHSW0wT245aUVoNko5QT09

Meeting-ID: 984 9018 0317
Kenncode: 483586

**Comment by mtrojan-ub** [comment]
Wie besprochen, Twitter / X soll erstmal so heterogen bleiben.

**Comment by coeh** [comment]
Verknüpfung Mastodon-Account auf IxTheo sieht mir jetzt gut aus und Link funktioniert. Danke!
