### ISSUE TITLE
Korrektur im Normsatz kommt nicht im Titelsatz an

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#260]
Vgl. https://github.com/ubtue/ixTheo/issues/503

Das Problem war schon gelöst. Es kommen aber wieder keine Änderungen an.

Bsp.:
https://www.ixtheo.de/Record/466977735
689  |a ʿalmā 
ʿalmā wurde am 26.3.2018 zu almah korrigiert

https://www.ixtheo.de/Record/465570291
689 |a Qasr el-Hallabat
Am 23.3.2018 korrigiert zu Qasr **al**-Hallabat 
Außerdem 6 Verweisungen ergänzt, die immer noch fehlen

Codex Iuris Canonici
Alle ca. 1300 Normsätze wurden Anfang April geändert und enthalten nun eine Jahreszahl in $f.
Korrekturen sind in den verknüpften Titeln nicht angekommen.
Bsp:
https://www.ixtheo.de/Record/467404577
689 |t Codex iuris canonici
jetzt 689 |a Katholische Kirche |t Codex Iuris Canonici |f 1983

https://www.ixtheo.de/Record/496811967
689 |t Codex iuris canonici  |p 838
jetzt |a Katholische Kirche |t Codex iuris canonici |f 1983 |p 838

**Comment by jriedl** [comment]
Hier wurde eine veraltete Datei ausgewertet - ist auf ptah jetzt behoben. Allerdings werden Sekundärkorrekturen nur in den Fällen verwendet, in denen wir die Normdaten direkt für die lokale Anreicherung der Titeldaten heranziehen, also z.B. für das Einfügen von Synonymen und Übersetzungen. Die Schlagwortfolgen in den 689-Feldern befinden sich aber direkt in den Titeldaten, so dass hier derzeit für eine Aktualisierung ein entsprechender (Komplett-)Abzug notwendig erscheint.

**Comment by IxTheoKm** [comment]
Betrifft das auch Sekundärkorrekturen von Autorennamen (Feld 100, 700)?

Generell bedeutet das dann wohl, dass regelmäßig/häufiger Komplettabzüge erfolgen müssen, damit Änderungen und Ergänzungen im IxTheo/RelBib ankommen.

**Comment by jriedl** [comment]
Nachfrage beim BSZ ist erfolgt: Wie vermutet besteht BSZ-seitig keine Möglichkeit, für Sekundärkorrekturen an den Normdaten automatisch die betroffenen Titelsätze zu erkennen und zu aktualisieren. Dies erfolgt nur, wenn explizit anderweitige Korrekturen am betroffenen Titelsatz vorgenommen wurden oder eben im Rahmen eines Komplettabzugs.

**Comment by thefass** [comment]
Komplettabzüge kosten uns Geld, so dass wir genau überlegen müssen, wann wir einen anfordern. Z.B. nach größeren Korrekturen wie jetzt in Bezug auf das CIC. Kleinere Korrekturen müssen dann leider etwas warten bis sie bei uns ankommen. Nicht schön, aber unvermeidlich.

**Comment by IxTheoKm** [comment]
Die o.g. Fälle und weitere sind jetzt auf PTAH behoben. Danke!
