### ISSUE TITLE
Unterfeld f wird in der Schlagwortfolge nicht angezeigt

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#261]
https://www.ixtheo.de/Record/48999279X#details
![cic](https://user-images.githubusercontent.com/17004223/39300607-89b5733c-494c-11e8-94b0-3a5b2b04f420.png)

689 |a Katholische Kirche |t Codex Iuris Canonici |f 1917

Muss angezeigt werden als Katholische Kirche, Codex Iuris Canonici (1917)

**Comment by jriedl** [comment]
Auf ptah behoben.

**Comment by IxTheoKm** [comment]
Jetzt in Ordnung, danke!
