### ISSUE TITLE
Navigation zwischen Suchergebnissen 

### ISSUE THREAD

**Issue by NMagin** [ubtue/tuefind#2619]
Im Testsystem wird beim Klick auf ein Suchergebnis derzeit nur auf die Volltitelanzeige verwiesen und eine Navigation zwischen den Suchergebnissen ist nicht möglich. Es fehlt auch die Zwischenstufe "Suche".

Ausgangspunkt war bei beiden eine reguläre Suche nach dem Begriff Buddhismus und die Auswahl eines der Suchergebnisse.
Testsystem:
![Screenshot 2023-11-16 at 10-02-35 Beschreibung Buddhismus RelBib](https://github.com/ubtue/tuefind/assets/109666609/fad7955b-83cb-4174-8a61-acfc525de857)

Live-System:
![Screenshot 2023-11-16 at 10-03-36 Beschreibung Buddhismus](https://github.com/ubtue/tuefind/assets/109666609/b5165c26-f626-423d-891d-46a94a88b15b)

Der Fehler tritt auch bei IxTheo auf. Bei KrimDok ist die Funktion auch im Live-System nicht aktiv, soweit ich das sehe.

**Comment by mtrojan-ub** [comment]
Ready for testing auf ptah.

Es hat uns einige Nerven gekostet => das Problem liegt nicht in der Volltitelanzeige selbst, sondern in der Art und Weise wie VuFind seit 9.0 die Links aus dem Suchergebnis zur Volltitelanzeige generiert (sieht man jetzt an der `sid` in der URL).

**Comment by NMagin** [comment]
Sieht soweit gut aus. Auf RelBib funktioniert es und auf IxTheo sowie den Subsystemen (KALDI & BILDI) taucht die Navigation auch wieder überall auf.
Danke euch für die Nerven und Lösung des Problems! :-)

Ich mache hier dann mal zu.
