### ISSUE TITLE
Doppelpunkt in zweisprachigen Titeln

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#262]
Bei der Zs PPN 094083746 ist folgendes aufgefallen:
Neuere Aufsatztitel werden immer in zwei Sprachen angezeigt, verbunden mit " = ". Wenn der Titel keinen Untertitel enthält, wird dennoch vor dem " = " auch noch ein Doppelpunkt angezeigt, der da nicht hingehört.
Beispiel:
https://relbib.de/Record/451549988

**Comment by IxTheoKm** [comment]
Dieser Fehler taucht bei allen Titeln mit Parelleltiteln (245 |b und 246 |a) auf. 
https://www.ixtheo.de/Record/501092315#details

Wenn sowohl in 245 als auch in 246 |b vorhanden ist, scheint es korrekt angezeigt zu werden:
https://www.ixtheo.de/Record/501090886

**Comment by relhei** [comment]
Passt. Danke!
