### ISSUE TITLE
Kleiner Übersetzungsfehler

### ISSUE THREAD

**Issue by derclou** [ubtue/tuefind#2621]
Auf das Button für "Self-Archive" auf Französisch soll "Republier" stehen, nicht "Repoublier". Vielen Dank!

**Comment by mtrojan-ub** [comment]
wurde behoben! ready for testing auf ptah

**Comment by coeh** [comment]
Sieht auf IxTheo jetzt gut aus, danke!

**Comment by coeh** [comment]
Auf RelBib passt es auch, ist also erledigt.
