### ISSUE TITLE
Lebensdaten werden bei Personen von Feld 700 nicht angezeigt

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#263]
In der Kurzanzeige und in der Vollanzeige werden "Weitere Verfasser" ohne die Lebensdaten angezeigt.
Bitte analog zu Feld 100 mit Lebensdaten anzeigen.

Bsp:
https://www.ixtheo.de/Record/486043401
https://www.ixtheo.de/Record/407409386

**Comment by jriedl** [comment]
Auf ptah integriert.

**Comment by IxTheoKm** [comment]
Auf PTAH jetzt o.k., vielen Dank!
