### ISSUE TITLE
Fehlermeldung bei Suche nach Verfassern in IxTheo und RelBib

### ISSUE THREAD

**Issue by NMagin** [ubtue/tuefind#2631]
Gerade noch bei der Prüfung der DDC-Suche (#2591) gefunden:
Die Suche nach Verfassern über das reguläre Suchfeld führt in IxTheo und RelBib zu Fehlermeldungen.
Suche RelBib
![Screenshot 2023-11-21 at 10-20-28 Suchergebnisse RelBib](https://github.com/ubtue/tuefind/assets/109666609/f86c650f-34c3-4a1a-9035-3752e7e9b967)

Fehlermeldung RelBib
![Screenshot 2023-11-21 at 10-16-13 Whoops! There was an error](https://github.com/ubtue/tuefind/assets/109666609/0c149a3b-beae-468c-974b-8920d0d06682)

Suche IxTheo
![Screenshot 2023-11-21 at 10-19-21 Suche IxTheo](https://github.com/ubtue/tuefind/assets/109666609/273ffee2-3e61-46eb-9995-d286808662b9)

Fehlermeldung IxTheo
![Screenshot 2023-11-21 at 10-18-55 Whoops! There was an error](https://github.com/ubtue/tuefind/assets/109666609/c616455e-5e8e-400d-adfb-9a733b9b2884)

KrimDok scheint nicht betroffen zu sein.

**Comment by coeh** [comment]
Hoppla. Das ist momentan tatsächlich auch bei Index Canonicus und Biblicus so. Das wäre eilig.

**Comment by mtrojan-ub** [comment]
Das scheint mit Änderungen am Highlighting in Solr 9 zu tun zu haben. Obwohl wir das nur bedingt nutzen bzw. es optisch an der Stelle auch schon auf dem alten Server nicht sichtbar ist, scheint es uns dort trotzdem auf die Füße zu fallen.

Um das nachhaltig zu lösen müssen wir Einstellungen in Solr-Feldern anpassen und die Daten dann neu importieren. Das schaffen wir heute vor dem Umzug nicht mehr. Wir versuchen das Highlighting übergangsweise zu deaktivieren sofern möglich, damit die Suchen wieder nutzbar sind bis das Problem nachhaltig gelöst wurde.

**Comment by mtrojan-ub** [comment]
Auf ptah ist nun übergangsweise die genannte Änderung aktiv (Highlighting deaktiviert, dafür Suche wieder nutzbar).

**Comment by mtrojan-ub** [comment]
Auf dem Liveserver ist das ebenfalls übergangsweise aktiv. 

Das Reindexing ist nicht ohne Unterbrechung des Betriebs möglich, da der Index einmal komplett gelöscht und neu importiert werden muss, ohne dass in dieser Zeit Restbestände aktiv sind. Wir führen das heute auf ptah durch (testen ist dann nur eingeschränkt möglich). Sobald der Index fertig ist übertragen wir ihn auf ub16 und tauschen ihn aus damit es zu keiner wesentlichen Beeinträchtigung des Live-Betriebs kommt.

**Comment by mtrojan-ub** [comment]
Das Reindexing auf ptah ist abgeschlossen. Mit der Übernahme auf ub16 warten wir zur Sicherheit noch bis morgen um sicherzustellen, dass auf ptah keine weiteren Probleme auftreten (insb. mit den Cronjobs über Nacht).

**Comment by NMagin** [comment]
Auf RelBib sieht es gut aus.
@coeh Wie sieht es bei den anderen drei Systemen aus?

**Comment by coeh** [comment]
In IxTheo, IxBib und IxCan sucht es jetzt korrekt. Allerdings wird oberhalb des Ergebnisses eine Auflistung von Normdatensätzen angezeigt, was mir nicht bekannt vorkommt. Bin mir nicht sicher, ob das neu ist oder ich das nur nicht kenne, weil ich fast nie so suche. Für Nutzende erscheint es mir nicht intuitiv, da nur Nummern und keine Namen angezeigt werden:
![grafik](https://github.com/ubtue/tuefind/assets/83448862/fceaaa79-0447-4afa-917f-48b40f8245e2)

**Comment by mtrojan-ub** [comment]
Ist auch in der VuFind Demo so, also vermutlich neu, Beispiel:
https://vufind.org/demo/Search/Results?lookfor=kindrick&type=Author&limit=20&sort=relevance

Die Frage ist also, ob wir das so behalten wollen oder nicht

**Comment by coeh** [comment]
Ich plädiere für nein, da wie gesagt für Nutzende nicht intuitiv. Es sei denn, man könnte Namen der Personen statt Nummern der GND-Sätze anzeigen, also "Janowski, Bernd" "Janowski, Christine" etc. - dann wäre es praktisch!  Wie sehen Sie das, @thefass ?

**Comment by thefass** [comment]
Die Nummern sind sinnlos, da man nicht weiß, wer sich dahinter verbirgt. Außerdem führt ein Klick auf die Nummern zu einer ergebnislosen Suche. Seihe unten screenshot
Bitte die Nummern in Namen auflösen.
<img width="649" alt="Bildschirm­foto 2023-11-28 um 21 16 47" src="https://github.com/ubtue/tuefind/assets/14169098/3b8112e4-293e-45cb-b4ff-5ae3d2ab8ccf">

**Comment by mtrojan-ub** [comment]
Die Nummern scheinen mittlerweile auch in der VuFind-Demo nicht mehr angezeigt zu werden, vermutlich wurde es mal bei einem Bugfix release behoben und wird gelöst wenn wir ohnehin auf eine der neuen Versionen aktualisieren. Ich lasse den Issue mal offen, würde aber das High Priority Label wieder entfernen weil das ursprünglich kritische Problem mit der Fehlermeldung nicht mehr auftritt.

**Comment by NMagin** [comment]
Vielleicht liegt es schon an der neuen VuFind-Version: Die Nummern werden noch/wieder angezeigt (RelBib, IxTheo, KrimDok). Hatte es mal funktioniert, sie in Namen umzuwandeln? 
Der Link auf "Alle anzeigen" scheint mir tatsächlich am hilfreichsten, da er eine namentliche Liste aller in Frage kommenden Autor*innen liefert. Wäre es möglich diese Liste in den Suchergebnissen anstatt der Nummern anzuzeigen? 
Alternativ (und übersichtlicher) wäre es auch eine Idee, die Nummern auszublenden und "Alles anzeigen" umzubenennen, bspw. in "Übersicht der Autoren" oder ähnliches.

**Comment by mtrojan-ub** [comment]
Die Umwandlung müsste nun wieder funktionieren, siehe ptah. Worauf der Link genau zeigt hängt davon ab, ob es sich um einen normierten oder nicht-normierten Autor handelt.

**Comment by NMagin** [comment]
Danke, das sieht in RelBib und IxTheo wieder gut aus. Kannst du es auch noch bei KrimDok anpassen? Dort wurde es auch zurückgesetzt.

**Comment by mtrojan-ub** [comment]
Die Änderung wurde nun auch auf sobek übernommen.

**Comment by NMagin** [comment]
Danke dir. Aus meiner Sicht funktioniert es wie es soll. Wenn @JMeister01 keine Einwände hat, kann das Issue m.E. geschlossen werden.

**Comment by JMeister01** [comment]
Alles in Ordnung, danke.
