### ISSUE TITLE
Mehrere Hauptverfasser werden zum Teil zusätzlich nochmal unter Weitere Verfasser angezeigt

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#264]
Bei zwei oder drei Hauptverfassern taucht der zweite oder der dritte in der Vollanzeige nochmal unter "Weitere Verfasser" auf. Bei **700 ... |4 aut** sollten die Autoren nur unter "Hauptverfasser" stehen und nicht nochmal in "Weitere Verfasser" auftauchen, zumal bei _drei_ Autoren offensichtlich nur _ein_ weiterer aufgeführt wird.

Bsp.:
https://www.ixtheo.de/Record/466923120
https://www.ixtheo.de/Record/357261143
https://www.ixtheo.de/Record/435147137

![700_aut](https://user-images.githubusercontent.com/17004223/39742973-bc98b082-529f-11e8-9b18-c77c1546f977.png)

![700_aut2](https://user-images.githubusercontent.com/17004223/39742982-c04a891c-529f-11e8-873b-9a67af678382.png)

![700_aut3](https://user-images.githubusercontent.com/17004223/39742985-c497b904-529f-11e8-8fa3-fc51155a0cf2.png)

**Comment by jriedl** [comment]
Auf ptah integriert.

**Comment by IxTheoKm** [comment]
Auf PTAH jetzt o.k., vielen Dank!
