### ISSUE TITLE
Default-Sortierung in Admin-Views anpassen

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#2642]
@LysogorAndGmail : Can you please change the default sort in the following Admin Views:

Show user authorities: Requested
Show user authority history: Requested User Date
Show user publications:  Date

(descending, so that the newest date is always at the top)

**Comment by mtrojan-ub** [comment]
Funktioniert aus meiner Sicht, daher schließe ich

**Comment by coeh** [comment]
Oh Entschuldigung, ja - ich hatte das Issue vergessen, aber es funktioniert. Danke!
