### ISSUE TITLE
Verschwundener Bereich mit Buttons

### ISSUE THREAD

**Issue by derclou** [ubtue/tuefind#2647]
![Image 2](https://github.com/ubtue/tuefind/assets/82641681/639ba2e8-0faf-4842-a94c-4829fd80c477)

Wenn man früher eine Publikation aus einer Trefferliste wählte, sah man dann nicht nur die Information über diese Publikation, sondern oben auch die Angabe "#X von Y Ergebnissen" (o.ä.), einen Button links von dieser Angabe, um zum vorherigen Treffer in der Liste zu gehen, und einen Button rechts davon, um zum nächsten Treffen zu gelangen. Das Bild wurde von einer französischsprachigen Nutzerin geschickt, die das Verschwinden dieser Funktionalität bemerkt hat, deshalb sind die Angaben darauf auf Französisch, aber man kann erkennen, dass oben zwei Buttons waren, die unten nicht mehr da sind.

**Comment by coeh** [comment]
Dafür haben wir schon ein Issue. Siehe #2619

**Comment by derclou** [comment]
Danke, dann mache ich es weg. Sorry für die Doppelung. ;)
