### ISSUE TITLE
Alternative Suchmöglichkeit nicht mehr vorhanden

### ISSUE THREAD

**Issue by derclou** [ubtue/tuefind#2648]
![Image 1](https://github.com/ubtue/tuefind/assets/82641681/2cfb8ab1-0b0e-431f-bf67-d4e0555eea02)

Früher wurden alternative Suchmöglichkeiten vorgeschlagen (im hellblauen Bereich im oberen Bild), die man anklicken konnte. Jetzt ist dieses Feature verschwunden. Dieser Fall wurde uns von einer französischsprachigen Nutzerin gemeldet, weshalb die Angaben auf dem Bild auf Französisch sind.

**Comment by coeh** [comment]
Wollen wir das denn behalten? Es ist mir beim Testen nicht aufgefallen, aber das hängt wahrscheinlich damit zusammen, dass mich diese Funktion zuvor als Nutzerin genervt hat, weil sie (im Deutschen jedenfalls) häufig Alternativen vorschlägt, die nicht sinnvoll sind.

**Comment by mtrojan-ub** [comment]
Soweit ich weiß wurde es nicht bewusst ausgeblendet, daher wäre es vermutlich eher als Bug einzustufen, es sei denn Sie wollen erst noch diskutieren ob die Funktion überhaupt sinnvoll ist.

**Comment by coeh** [comment]
Wir sollten noch die Meinung von @thefass dazu einholen, bevor wir etwas unternehmen.

**Comment by thefass** [comment]
Sollten wir wieder einschalten. Auch wenn die Vorschläge oft nicht so sinnvoll waren, könnte das ja vielleicht verbessert werden. immerhin vermisst aber die franz. Kollegin die Funktion, also wird sie als Power.Nutzerin das doch irgendwie nützlich finden

**Comment by mtrojan-ub** [comment]
Wir haben die Suche mit dem alten Server vor der VuFind 9 / Ubuntu Migration verglichen, dort fehlt die blaue Box ebenfalls bereits. Handelt es sich ggf. um ein Problem das schon länger besteht?

Andererseits kann man im Screenshot "Avant" nicht sehen welche Suchoptionen genau ausgewählt wurden. Bei "Maintenant" sieht man dass "Tous les champs" ausgewählt ist (also = Alle Felder). Wählt man auf dem alten Server ebenfalls Alle Felder aus, wird aber auch dort die blaue Box nicht angezeigt (hat sie den Screenshot aus einer alten Anleitung?)

Wir gehen trotzdem mal auf die Suche und prüfen ob es ggf. schon bei einer früheren Änderung abhanden gekommen ist.

**Comment by mtrojan-ub** [comment]
Aktuell sieht es so aus, als ob der Fehler etwas mit dem SpellChecker zu tun hat. Eine entsprechende Änderung befindet sich bereits in Vorbereitung.

**Comment by mtrojan-ub** [comment]
Die Änderung ist sowohl auf dem Test- als auch auf dem Liveserver aktiv => ready for testing

**Comment by derclou** [comment]
Die Funktion ist wiederhergestellt und funktioniert, soweit ich sehen kann, einwandfrei. Vielen Dank! Ich schließe das Issue.
