### ISSUE TITLE
PDA Nutzerkommunikation anpassen

### ISSUE THREAD

**Issue by ghost** [ubtue/tuefind#265]
Nach Aufrufen eines PDA Titels bitte Meldung anpassen
neu: "Liebe RelBib Nutzerin, lieber RelBib Nutzer, 
im Patron Driven Acquisition (PDA) Programm des Fachinformationsdienstes (FID) Religionswissenschaft können [...]

![grafik](https://user-images.githubusercontent.com/16898788/39819709-65bd102c-53a4-11e8-80d4-8e4ce24b79cc.png)

**Comment by jriedl** [comment]
auf ptah integriert.

**Comment by Gazeller** [comment]
Dialog jetzt okay. Verwirrend ist, dass PDA auch für bereits bestelltes Buch angeboten wird. 
![grafik](https://user-images.githubusercontent.com/16898788/40963645-6e9a03c0-68a9-11e8-9568-a97374b75f19.png)

![grafik](https://user-images.githubusercontent.com/16898788/40963743-a5a0a43c-68a9-11e8-88d7-d9149895e8c6.png)

Problem?

**Comment by Gazeller** [comment]
Dovh noch Fehler im Nutzerdialog gefunden. Muss heißen:
"Liebe RelBib Nutzerin, lieber..."

**Comment by jriedl** [comment]
Wie bereits angesprochen: Gilt noch als PDA-Kandidat, da der entsprechende Status im GVI Fernleihe nicht zulässt. Nutzerdialog ist korrigiert.
