### ISSUE TITLE
Albert-Krebs Bibliothek: Bestand/Signatur anzeigen

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#2650]
Besprochen im Meeting am 29.11.23

Signatur soll angezeigt werden, unterhalb von / ähnlich wie wie bei der jetzigen Anzeige "Bestand in Tübingen", in einer separaten Zeile "Bestand in Albert-Krebs Bibliothek".

Gilt für Datensätze mit Abrufzeichen kreb, die eine entsprechende Signatur in LOK "852 1" Unterfeld c haben.

Beispiel: https://sobek.ub.uni-tuebingen.de/Record/181860860X

**Comment by mtrojan-ub** [comment]
@JMeister01: Wir hatten vorhin im Meeting darüber gesprochen, ich habe daraufhin diesen Issue angelegt, er ist bereits ready for testing auf sobek.

**Comment by JMeister01** [comment]
Das ging aber schnell! Vielen Dank! 
Sieht gut aus!
