### ISSUE TITLE
Massenhafte Wiederholung von diversen Feldern

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#2655]
Beispiel: https://ixtheo.de/Record/334682436#details

Ich erspare mir hier einen Screenshot. Die MARC-Felder 084, 655, 787, 936 werden x-mal wiederholt. 
Das kommt in vielen Fällen vor. Aufgefallen über die Facette Genre (Schlagwort)

**Comment by jriedl** [comment]
Ggf. werden wir morgen eine Support-Anfrage stellen.
