### ISSUE TITLE
Anzahl der gesamten Nachweise bei RelBib & IxTheo zu gering

### ISSUE THREAD

**Issue by NMagin** [ubtue/tuefind#2657]
Aufgrund des Fehlers in IxTheo, den @IxTheoKm gerade über IxTheo2 geschickt hat, habe ich bei RelBib geschaut, ob die Suche dort funktioniert. Das tut sie, aber unsere Treffermenge der gesamten Nachweise (leere Suche) ist um knapp 200.000 Nachweise gefallen. Im Testsystem sind es noch 1.008.984, im Live-System nur noch 794.831.

Bei IxTheo habe ich die Zahlen nicht im Blick, aber dort könnte es ähnlich sein.

**Comment by thefass** [comment]
In IxTheo von 3,77 Mio auf 3,18 gefallen

**Comment by mtrojan-ub** [comment]
Es gab heute morgen Probleme beim Import, wir sind bereits dabei das zu beheben.

**Comment by thefass** [comment]
gelöst. Danke
