### ISSUE TITLE
Erweiterte Suche: Mehrfach-Auswahl IxTheo/RelBib Facetten funktioniert nicht

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#266]
In der erweiterten Suche führt die Auswahl mehererer IxTheo Notationen zu dem Ergebnis: Keine Ergebnisse!
![bildschirmfoto 2018-05-11 um 09 37 51](https://user-images.githubusercontent.com/14169098/39913711-29e3b60e-5503-11e8-9e87-14b3f35c435c.png)

Es müsste eine OR Suche und keine AND Suche durchgeführt werden

Das selbe Problem auch auf RelBiB
![bildschirmfoto 2018-05-11 um 10 09 22](https://user-images.githubusercontent.com/14169098/39913842-889f5946-5503-11e8-986b-4dd703465827.png)

**Comment by jriedl** [comment]
Soweit mir bekannt, wurde nach Diskussion für die IxTheo-Notationen in der erweiterten Suche bewusst die UND-Suche verwendet, da nur so für den Benutzer die Möglichkeit besteht, bei der Suche Schnittmengen zwischen Notationen zu bilden.

**Comment by thefass** [comment]
funktioniert
