### ISSUE TITLE
Subito Bestelldienst funktioniert nicht bei Zeitschriften

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#2669]
Wenn man in RelBib / IxTheo bei einer beliebigen Zeitschriftenaufnahme auf den Subito-Link "Jetzt bestellen" klickt, erscheint die Subito-Seite mit leerem Bestellformular und folgender Auskunft:
![grafik](https://github.com/ubtue/tuefind/assets/25769591/38954b98-8a47-4613-81a4-30b8d2706346)
https://www.subito-doc.de/search/journals/?RID=2&improve=1
(Bsp.: https://www.relbib.de/Record/331140446)
Wird evt. nicht der richtige Parameter übergeben?

**Comment by jriedl** [comment]
In MARC 035a ist die ZDB-Nummer mit dem Präfix "ZDB" hinterlegt - dies kann Subito offenbar nicht verarbeiten. Eine angepasste Version findet sich auf ptah.

**Comment by relhei** [comment]
Danke, das funktioniert wieder!
