### ISSUE TITLE
"Weitere Schlagwörter" werden nebeneinander ohne Trennzeichen angezeigt

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#267]
Weitere Schlagwörter, die bisher untereinander mit "B" für Browsen angezeigt wurden
(Beispiel siehe https://github.com/ubtue/tuefind/issues/175 )
stehen jetzt ohne Trennzeichen unübersichtlich nebeneinander.
Bsp.:
https://www.ixtheo.de/Record/491946716#details
![weitere_sw](https://user-images.githubusercontent.com/17004223/39926515-bb31a108-552f-11e8-8ccc-e5bc795993a6.png)

Bitte 650 |a |x entweder wieder untereinander oder jeweils getrennt mit Semikolon "B" anzeigen

**Comment by jriedl** [comment]
An der Behandlung der 6XX-Felder hat sich nichts geändert. Bei der PPN 465861229 stehen die Schlagwörter in unterschiedlichen 6XX Feldern und werden deshalb untereinander angezeigt. Für 491946716 gibt es nur ein einzelnes 650 Feld in dem alles zusammengeworfen wurde. Ein Einzelschlagwort kann durch direktes Anklicken ausgewählt werden. Wenn man jetzt die Einträge in den Nicht-689 auseinanderreißt, zerstört man damit eventuell vorhandene inhaltliche Gruppierungen in  "Weitere Schlagwörter" und die Möglichkeit, diese oder ähnliche über das Browsen zu finden.

**Comment by IxTheoKm** [comment]
Ist das evtl. eine Design-Frage?

**Comment by jriedl** [comment]
Eigentlich nur indirekt, weil die Darstellung aus der internen Struktur der Daten abgeleitet wird. Für 491946716 lässt sich eine "schönere" Darstellung erzielen, wenn man die Schlagwörter auf mehrere 650-Felder aufsplittet.

**Comment by thefass** [comment]
@IxTheoKm : wo kommen die SW in 650 her? aus 5580 oder 5520? Wenn die Herkunftskategorie Einzelschlagwörter wären, könnte man die auseinander nehmen und untereinander anzeigen lassen

**Comment by IxTheoKm** [comment]
Im o.g. Fal (jetzt https://www.ixtheo.de/Record/1561946710#details) stehen sie in _einem_ PICA-Feld 5520 (Verlagseinspielung):

5520 |s|paintings$aBanijurids$aKhuttal$aMa wara’al-nahr$aSamanids$amaterial-culture$aCentral Asia$aTajikistan$aHulbuk$apalaces

650 4$apaintings$xBanijurids$xKhuttal$xMa wara’al-nahr$xSamanids$xmaterial-culture$xCentral Asia$xTajikistan$xHulbuk$xpalaces

**Comment by thefass** [comment]
@IxTheoKm bitte prüfen, ob $x als Trenner verwendet werden kann:
wenn ja, bitte in der Anzeige $x mit Semikolon ersetzen
wenn nein, kann nichts gemacht werden > issue schließen

**Comment by IxTheoKm** [comment]
$x kann leider nicht als Trenner verwendet werden. Es gibt Fälle mit nicht-normierten "Schlagwortfolgen", deren Einzelbegriffe durch $x getrennt sind, die aber nicht auseinandergezogen werden dürfen.
Bsp.: 
https://ixtheo.de/Record/1578282551#details
650 4$aMissions$xMethodology
650 4$aMissions$xTheory

$x trennt also Einzelschlagwörter in einem Feld 650 ebenso wie Teile einer Schlagwortfolge.
Damit ist eine Unterscheidung nicht möglich. Ich schließe daher.
