### ISSUE TITLE
Unvollständige bibliografische Angabe für einen Artikel

### ISSUE THREAD

**Issue by derclou** [ubtue/tuefind#2709]
[Index theologicus-1.pdf](https://github.com/ubtue/tuefind/files/14177891/Index.theologicus-1.pdf)

Früher wurde bei einem einzelnen Artikel beim Feld "In" (bzw. "Dans" im Bild) nicht nur der Name der Zeitschrift gezeigt, in dem der Artikel erschien, sondern auch das Erscheinungsjahr, der Jahrgang, die Heftnummer und die Seitenzahlen. Die sind verschwunden. Könnte das auch mit einem Upgrade von ViewFind zusammenhängen? Vielen Dank für Ihre Hilfe!

**Comment by thefass** [comment]
Ist mit Issue #2730 erledigt
