### ISSUE TITLE
Angaben Bestand in KrimDok

### ISSUE THREAD

**Issue by JMeister01** [ubtue/tuefind#2710]
Bei Aufsätzen aus Zeitschriften aus dem AKB Bestand wird das Feld "Bestand in der Albert-Krebs Bibliothek" nicht angezeigt, z.B.:

https://krimdok.uni-tuebingen.de/Record/1067641599?sid=2617676
https://krimdok.uni-tuebingen.de/Record/1688927557?sid=2617676

Außerdem ist in beiden Beispielen in "Journals Online & Print" eine Information zum Bestand enthalten. Warum werden nicht alle Bestände unter Bestand aufgelistet? Zusätzlich ist es verwirrend, dass es einmal IFK und einmal Tübingen Inst. Kriminolog. heißt.

**Comment by jriedl** [comment]
Erläuterung zum zweiten Aspekt (JOP + Bestand in Tübingen): Im ersten Fall werden die Informationen von JOP heruntergeladen. Im zweiten Fall sind es Daten, die im Record hinterlegt sind (vgl. Interansicht  unten das Feld SIG). Das "Bestand in Tübingen" wird immer angezeigt, die JOP-Anzeige führt falls möglich eine IP Erkennung durch und zeigt den Bestand der erkannten (oder falls keine Zuordnung möglich manuell ausgewählten) Institution an - da kommt also nur das gleiche, wenn hier bei uns im Uni-Netz ist.

**Comment by JMeister01** [comment]
Danke für die Erläuterung! Noch eine Frage dazu (nur für mein Verständnis): Warum wird bei "Bestand in Tübingen" nicht z.B. auch das juristische Seminar angezeigt, wenn ein Titel dort (ebenfalls) vorhanden ist. Wurde in KrimDok diese Anzeige auf IFK und UB begrenzt?

**Comment by thefass** [comment]
Unsere Bibliographien sind ja international, insofern macht es keinen Sinn, den Bestand Tübinger Bibliotheken dauerhaft anzuzeigen. Eine Ausnahme haben wir gemacht für die Bibliotheken, die den FID Kriminologie veranworten: UB+IFK.

**Comment by JMeister01** [comment]
Danke! Dann wissen wir nun, warum die Darstellung so erfolgt.

**Comment by jriedl** [comment]
> Danke für die Erläuterung! Noch eine Frage dazu (nur für mein Verständnis): Warum wird bei "Bestand in Tübingen" nicht z.B. auch das juristische Seminar angezeigt, wenn ein Titel dort (ebenfalls) vorhanden ist. Wurde in KrimDok diese Anzeige auf IFK und UB begrenzt?

Vermutlich, weil er einfach in den Lokaldaten nicht vorhanden ist. In der Internansicht sehe ich nun auf Anhieb nur das ein LOK 852 Feld mit der IFK-Information. Laut Abzugskriterien in unserem Wiki sollten Lokaldaten des juristischen Seminars mitkommen. Das Tool, das in der Pipeline das SIG-Feld erstellt, geht tatsächlich auf UB und IFK-Bestände, allerdings sollte das Juristische Seminar als Teilbibliothek der UB dem Kriterium einer ISIL, die mit DE-21 anfängt, entsprechen, dass sollte also kein Problem darstellen. Im opac.k10plus.de scheint auch nur der Nachweis am IFK  + der Nachweis für Krimdok selbst hinterlegt zu sein.

**Comment by mtrojan-ub** [comment]
Zum Thema 1) "Bestand in der Albert-Krebs Bibliothek":

Das liegt daran, dass die entsprechenden Felder nicht so gesetzt sind wie erwartet. Die jetzige Implementierung holt sich die Information aus folgenden Feldern:

Bestand: LOK 86630 a
Signatur: LOK 852 1 c

Beides ist bei den o.g. PPNs nicht vorhanden.

**Comment by JMeister01** [comment]
Betroffen sind alle Aufsätze aus "Forum Strafvollzug" aus dem AKB-Bestand (das sind auch die einzigen Aufsätze aus dem AKB-Bestand). 
Dem Nachweis der Zeitschrift kann zwar entnommen werden, dass die Zeitschrift auch in der AKB zu finden ist: https://krimdok.uni-tuebingen.de/Record/52370271X
Aber Nutzende schauen in der Regel in den Nachweis des Aufsatzes. Wenn dort Bestand am IfK steht, wird nicht davon ausgegangen, dass man noch in den Nachweis der Zeitschrift schauen muss, um herauszufinden, ob das Werk auch in der AKB vorhanden sein könnte.

**Comment by JMeister01** [comment]
Wie heute morgen besprochen hier noch ein paar PPNs aus der Forum Strafvollzug:
1811034837
1757224890
1787046168
1735207497
1871473888

**Comment by mtrojan-ub** [comment]
Dazu gab es heute eine Änderung auf sobek die voraussichtlich ab morgen sichtbar sein wird
(im Artikel sollte dann der AKB Bestand aus dem übergeordneten Werk angezeigt werden)

**Comment by mtrojan-ub** [comment]
Mit der Anzeige auf sobek gab es noch ein Problem welches soeben behoben wurde. Jetzt wird auch der AKB Bestand bei Artikeln angezeigt => ready for testing.

**Comment by KStelzel** [comment]
Funktioniert. Super, vielen Dank!
