### ISSUE TITLE
RelBib: Alertpakete ohne Inhalt oder ganz fehlend

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#2719]
Wenn man die Übersichtsseite der Alertpakete in RelBib aufruft, werden nicht mehr alle angezeigt: in deutscher Sprache nur 6, in englischer Sprache 13. Es fehlen z. B. "Afrika", "Buddhismus" etc.:
https://www.relbib.de/Search/Results?filter%5B0%5D=%7Eformat%3A%22Subscription%20Bundle%22&type=AllFields&lng=de

Wenn man dann ein Alertpaket auswählt und sich die enthaltenen Zeitschriften anzeigen lassen möchte, erhält man keine Ergebnisse:
https://www.relbib.de/Search/Results?lookfor=bundle_id:%22Full%20pack%22

Ist die Kommunikation mit ZEDER fehlerhaft?

**Comment by jriedl** [comment]
Problem tritt nur auf ub16 auf - auf ptah gab es im Zusammenhang mit der Statistikerstellung der Pakete bereits Anfang Februar eine Anpassung. Vorher wurde hier die "kat"-Spalte in Zeder ausgewertet, offenbar wurden die Belegungungsmöglichkeiten dieser Spalte verändert. Diesbezüglich aktueller Stand jetzt auf ub16, Pakete und zugehörige Zeitschriften sollten nach Abschluss des nächsten Imports voraussichtlich morgen früh wieder vollständig sichtbar sein.

**Comment by jriedl** [comment]
Alertingpakete werden mit dem neuen Selektionskriterium teils doppelt angezeigt.

**Comment by jriedl** [comment]
Trtitt nur auf ptah auf unnd hängt mit einer Änderung der PPN-Generierung in der Bundles zusammen. Wurde nun reverted.

**Comment by jriedl** [comment]
Pakete auf ptah sollten nun wieder ok sein.

**Comment by relhei** [comment]
Sieht gut aus. Vielen Dank!
