### ISSUE TITLE
Glockensymbol für Alerting von Zeitschriften verschwunden

### ISSUE THREAD

**Issue by coeh** [ubtue/tuefind#2721]
Das Symbol Glocke, das sonst angeklickt werden konnte, um Alerts für Zeitschriften zu abonnieren, wird in IxTheo nicht mehr angezeigt, auch wenn man eingeloggt ist.

Beispiel Theologische Quartalschrift:
![grafik](https://github.com/ubtue/DatenProbleme/assets/83448862/f8d9cffe-e4eb-4ffd-8247-0df5ef722aaf)

Früher sah der Eintrag so aus (mit Glocke). Das sollte wieder so sein (die erste Datumszeile ist ok, die zweite ist der Fehler aus #2700 , der dort zu lösen ist. Es geht hier aber um die Glocke als Alertingsymbol):
![grafik](https://github.com/ubtue/DatenProbleme/assets/83448862/87079e45-3b82-45ff-bb80-b2b51850e19b)

**Comment by jriedl** [comment]
Das hängt wohl ebenfalls mit der Umbelegung der kat-Spalte in Zeder zusammen - seitdem hier nicht mehr der Typ (z.B. IxTheo) angegeben wird, schlägt die Auszeihnung der Records fehl. Aktuell wurde das nun so angepasst, dass _alle_ innerhalb der jeweiligen Zeder-Instanz vorhandenen Zeitschriften wieder abonnierbar sind, so im Bestand vorhanden. Falls das nicht wünschenwert ist, bitte Rückmeldung.

**Comment by jriedl** [comment]
> _alle_ innerhalb der jeweiligen Zeder-Instanz vorhandenen Zeitschriften wieder abonnierbar sind, so im Bestand vorhanden.

Nachtrag: Und natürlich die vorher bereit geltenden Bedingungen weiterhin erfüllt sind (Zeitschrift, nicht abgeschlossen)

**Comment by jriedl** [comment]
Nun so sichtbar auf ptah und ub26.

**Comment by coeh** [comment]
Sieht auf IxTheo und ptah jetzt gut aus, vielen Dank! In der Abonnierbarkeit von allen in ZEDER erfassten Zeitschriften sehe ich momentan kein Problem. Gibt es da andere Erfahrungen oder Punkte, die ich übersehe @thefass @socheres und @relhei ?

**Comment by relhei** [comment]
Wir hatten mal eingeschränkt, die Glocke nur bei Zeitschriften anzuzeigen, die in den Bibliografien auch regelmäßig ausgewertet werden, also wo auch neue Inhalte / Aufsätze erwartbar sind. Das halte ich nach wie vor für sinnvoll. Verstehe ich das richtig, dass das nun wieder aufgehoben ist?

**Comment by jriedl** [comment]
Genau deshalb ist ja damals das Kriterium, dass die Zeitschrift in Zeder sein muss, dazugekommen. Ist das für alle in Zeder hinterlegten Zeitschriften der Fall?

**Comment by jriedl** [comment]
Nachtrag: Oder anders gefragt: Sind durch die Umbelegung der "kat"-Spalte in Zeder und damit der Wegfall  des Filters "ixtheo" als Kriterium für uns nun möglicherweise Zeitschriften dazugekommen, die nicht zum Abonnement angeboten werden sollen?

**Comment by coeh** [comment]
Ah, das war der Punkt - dann verstehe ich es jetzt besser. Mit den Spalten kenne ich mich leider nicht gut genug aus. Das wissen @thefass und @IxTheoKm sicherlich genauer.

**Comment by relhei** [comment]
Ich kenne die genaue Definition der Abfrage aus ZEDER für die Einschränkung auch nicht (mehr), ich vermute aber, dass nur die Zeitschriften mit Glocke versehen werden, die in Spalte "kat" den Wert "ixtheo" haben. Mittlerweile wurde dieser Wert umbenannt in "jkl", das müsste dann gfs. in euren Einstellungen auch geändert werden.

**Comment by jriedl** [comment]
Ja, genau so war es auch - wir haben "ixtheo" vorher ausgewertet. Es wäre dann die dringende Bitte, zukünftig nicht ohne Rücksprache Felder umzubennen, damit wir uns alle den hier jetzt notwendigen Schweinezyklus "Dienst 1 funktioniert nicht mehr" (Alerting-Bundles), Anpassungen müssen gemacht werden, "Dienst 2 funktioniert nicht mehr" (Abbonierbarkeit),  Anpassungen müssen gemacht werden - Anpassungen müssen alle wieder rückgängig gemacht und wieder neu angepasst werden ersparen können.

**Comment by thefass** [comment]
jkl ist unmgesetzt. Können wir schließen @jriedl ?

**Comment by jriedl** [comment]
Der nochmals geänderte Ansatz ist erst mit dem Import von heute wirksam geworden (ptah, ub16) . Allerdings bietet THQ nun z.B. keine Alertmöglichkeit mehr.

**Comment by thefass** [comment]
Stimmt. Das ist tatsächlich so:
https://www.ixtheo.de/Search/Results?sort=title&limit=100&lookfor=THQ&type=AllFields&filter%5B%5D=%7Eformat%3A%22Journal%22
<img width="806" alt="Bildschirm­foto 2024-02-21 um 09 08 29" src="https://github.com/ubtue/tuefind/assets/14169098/dfa6b69d-e411-4d0a-a176-bbea590e26d1">

Die Frage ist allerdings, warum? Denn in Zeder kat steht jkl
<img width="827" alt="Bildschirm­foto 2024-02-21 um 09 10 15" src="https://github.com/ubtue/tuefind/assets/14169098/c1cb791a-6633-4f65-8615-c46a402b4d3d">

**Comment by jriedl** [comment]
Hängt damit zusammen, dass das Parsing des Zeder-JSON-Dumps in unserer Bibliothek nur dann korrekt filtert, wenn das zu filternde Feld explizit an anderer Stelle noch einmal in der Feldliste angegeben wird. Anpassungen jetzt auf ptah und ub16, sollte jeweils nach Abschluss der nächsten Importe sichtbar sein.

**Comment by thefass** [comment]
ok
