### ISSUE TITLE
Datenschutzerklärung: Aktualisierung notwendig

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#2724]
In der Datenschutzerklärung aller drei FID-Bibliografien steht noch Frau Dörr als Verantwortliche:

Bsp. RelBib:
![grafik](https://github.com/ubtue/tuefind/assets/25769591/3b0fc865-5d05-4e9b-82b2-97cb12ed5e2c)

https://www.relbib.de/Content/privacy#content

Kann das bitte noch aktualisiert werden?

**Comment by relhei** [comment]
Vielen Dank! Die Datenschutzerklärung passt nun. Bei Impressum müssten auch noch die Angaben zur Rektorin aktualisiert werden, ist mir gerade aufgefallen:
![grafik](https://github.com/ubtue/tuefind/assets/25769591/fd3ad082-5e4b-40d1-b3c7-11c16fccbbc4)
(Titel sind anders angegeben als in den Bibliografien)

**Comment by mtrojan-ub** [comment]
Diese Angaben wurden nun ebenfalls angepasst

**Comment by coeh** [comment]
Sorry vergesst bitte den Kommentar von eben - ich sollte nicht ptah und Livesystem nebeneinander offen haben und sie dann verwechseln! Auf ptah ist es auch für IxTheo richtig.

**Comment by relhei** [comment]
Perfekt - vielen Dank! Sollen wir mit dem Schließen des Issues noch warten, bis die Änderungen im Live-System umgesetzt sind?

**Comment by relhei** [comment]
Für RelBib müsste noch der Titelvorspann für Frau Prof. Pollmann angepasst werden, bei IxTheo ist es schon richtig. 
RelBib:
![grafik](https://github.com/ubtue/tuefind/assets/25769591/c9fb4e3d-d9b7-4986-ae59-48f1b24f738e)
https://www.relbib.de/Content/Impressum#content
IxTheo:
![grafik](https://github.com/ubtue/tuefind/assets/25769591/8a651830-36c7-45ae-b19e-7723482c6d4d)
https://www.ixtheo.de/Content/Impressum#content

**Comment by mtrojan-ub** [comment]
jetzt auch auf ptah geändert
