### ISSUE TITLE
Anzeige mehrerer Autorennamen ohne Trennzeichen

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#273]
Verschiedene Autorennamen werden wieder nur durch Komma getrennt. Das Problem war schon mal behoben:
https://github.com/ubtue/ixTheo/issues/124

Beim ersten Verfasser fehlt der Zusatz "(VerfasserIn). Es gibt zwar nicht das Unterfeld "aut", aber 100 ist immer der erste Verfasser.

Beispiel:
https://ixtheo.de/Record/041024249
Autoren Feld 100 und 101:
Hauptverfasser:  Mathieu, Joseph, Roos, Carl Alexander (VerfasserIn)

https://ixtheo.de/Record/031056733
Autoren Feld 100 und 700
Hauptverfasser:  Johannes, de Castello 1370-1426, Albertus, Magnus 1193-1280 (VerfasserIn), Gerson, Johannes 1363-1429 (VerfasserIn)

**Comment by IxTheoKm** [comment]
Auf PTAH ist die Anzeige mehrerer Personen in der Vollanzeige jetzt o.k.

In der Kurzanzeige wird jetzt nur noch eine Person angezeigt. Ist diese Änderung Absicht? 
Bisher wurden die Hauptverfasser in **100** und **700** **$4 aut** alle in der Kurzliste angezeigt:
https://ixtheo.de/Search/Results?lookfor=De+adherendo+deo%2C+nudato+intellectu+et+affectu+et+ultima+et+suprema+perfectione+hominis%2C+quantum+possibile+est&type=AllFields&limit=20&sort=year+desc%2C+issue_sort+desc%2C+start_page+asc

**Comment by jriedl** [comment]
Ist auf ptah jetzt angepasst.

**Comment by IxTheoKm** [comment]
Auf PTAH jetzt o.k., danke!
