### ISSUE TITLE
Zweitveröffentlichungsservice für Körperschaften

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#2733]
Besprochen mit @thefass:
Es ist bereits möglich dass Benutzer Zugriffsrechte auf Körperschaften beantragen. Allerdings war das bislang kein vorgesehener Fall. Beim Klick auf den Button "Self-Archive" ist jedoch im Anschluss kein Upload möglich, da es sich wie gesagt nicht um einer Person handelt. Das soll aber in Zukunft auch für Körperschaften möglich sein. Allerdings reicht es nicht das einfach im Uploadformular freizuschalten, sondern es muss ja auch gewährleistet sein dass die korrekte Information an der richtigen Stelle landet (Übertragung an DSpace, Meistertask und so weiter).

**Comment by mtrojan-ub** [comment]
Im Zuge dieses Issues sind wir noch auf einen Bug gestoßen: Die Verknüpfung vom Titel zur Körperschaft hat auch bei normierten Einträgen mit GND-Nummer bisher nicht korrekt funktioniert, weil die Nummern mit dem falschen Solr-Feld verglichen wurden (für Nebenautoren statt Körperschaften).

Beispiel: https://ptah.ub.uni-tuebingen.de/Record/1880323486

![grafik](https://github.com/ubtue/tuefind/assets/26873381/2afbad97-84c5-4ef6-b43d-6ebb8130400e)

**Comment by mtrojan-ub** [comment]
Der genannte Bugfix sowie ein erster "Schnellschuss" für den Upload als Körperschaft ist nun auf ptah aktiv. 

Dazu ein paar Hinweise:
- **Bitte ausführlich testen**! Sowohl ob ein Upload als Körperschaft möglich ist, als auch ob es bei dem Upload als Person keine Probleme gibt.
- Bislang war es nur möglich den Upload durchzuführen, wenn man bei den Primären Autoren gelistet war. Für Nebenautoren war und ist das auch weiterhin nicht möglich (da wird sogar ein passender Hilfstext angezeigt). Als Körperschaft wurde es bislang ohne Hilfstext verhindert bzw. es wurde nur der generische Text angezeigt. Jetzt ist der Upload sowohl als primärer Autor als auch als Körperschaft möglich.
- Die Metadaten für die Übertragung an DSpace + Meistertask werden erst nach DC konvertiert, danach wird das DC Feld `dc.contributor.author` sowohl an DSpace als auch später an Meistertask übertragen. Falls dieses feld NICHT genau 1 Eintrag hat bleibt es in DSpace leer. Was genau übertragen wird (Primärer Autor, Name der Körperschaft, etc.) hängt also auch davon ab ob es in den Titeldaten genau 1 Eintrag in diesem Feld gibt oder nicht. 
- Offen: Müssen ggf noch weitere Hilfstexte geschrieben werden? (z.B. Muss die FAQ um den Fall Self-Archive als Körperschaft ergänzt werden)
- Hinweis zur Liveschaltung (da High Priority): Auch wenn die Tests erfolgreich waren müssen wir erst noch prüfen wann die Änderung tatsächlich live geschaltet werden kann, damit es keine Konflikte mit anderen Änderungen gibt.

**Comment by thefass** [comment]
ok
