### ISSUE TITLE
BlueSky einbinden

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#2747]
https://bsky.app/profile/ixtheo.bsky.social
Biite bei den drei gelabelten VuFinds einbinden

**Comment by mtrojan-ub** [comment]
... ist jetzt auf ptah aktiv (jeweils im footer) / ready for testing

**Comment by thefass** [comment]
Sieht gut aus.
Kann die Reihenfolge bitte sein: Bluesky, Mastodon, Twitter.
Danke

**Comment by mtrojan-ub** [comment]
Ist auf ptah geändert

**Comment by thefass** [comment]
prima, ich schließe
