### ISSUE TITLE
Person / Körperschaft / Tagung

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#2753]
Teile des Issue #2589 sind hier aufgegriffen.

**Comment by mtrojan-ub** [comment]
@LysogorAndGmail, as mentioned via email: 

> Just search for "Personen / Körperschaften" in all themes (there might also be some whitespace variants right now like "Personen/Körperschaften"), normalize them and add transEsc() to it so the proper updated value is used from the language config in local/tuefind/languages.

**Comment by thefass** [comment]
<img width="962" alt="Bildschirm­foto 2024-03-08 um 11 28 30" src="https://github.com/ubtue/tuefind/assets/14169098/24e42275-2852-4649-9377-d485b52cf8f7">

Bitte den Reiter Personen/Körperschaften umbenennen in:
dt: Person / Körperschaft / Tagung
eng: Person / Corporation / Conference
fre: Personne / Société / Colloque
spa: Persona / Entidad / Reunión
it: Persona / Corporatione / Conferenza
griech: Άτομο / Εταιρεία / Συνέδριο

**Comment by thefass** [comment]
Es sollen auch noch die Suchaspekte in diesem Reiter verändert werden.
Ich kopiere den entsprechen Beitrag aus Issue #2589:

100 - Main Entry - Personal Name (NR) Full | Concise
110 - Main Entry - Corporate Name (NR) Full | Concise
111 - Main Entry - Meeting Name (NR) Full | Concise

Dieser Aspekt muss aber vermutlich noch (mündlich) besprochen werden
