### ISSUE TITLE
Sortierung von Aufsätzen

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#2759]
_Änderungen im Exportformat MARC 21 zum 27.02.2024
Die doppelte Auslieferung der differenzierenden Angaben zur Quelle bei Aufsätzen in MARC 773 18 und 936 uw wird mit diesem Release eingestellt. Ab heute wird nur noch Feld 773 18 ausgeliefert (vgl. dazu https://www.agkva.org/888242276.html). Für die Erfassung im K10plus ändert sich nichts._

Unsere Sortierung der Aufsätze erfolgt offenbar nach MARC 936. Jedenfalls wird jetzt z.B. das neue Heft 3 der Herder-Korrespondenz erst nach Heft 2 und 1 angezeigt, wenn man nach „Neueste zuerst“ sortiert:
https://ixtheo.de/Search/Results?lookfor=superior_ppn%3A592067602&type=AllFields&limit=100&sort=year+desc%2C+volume_sort+desc%2C+issue_sort+desc%2C+start_page+asc%2C+first_indexed+desc&botprotect=

Heft 1 und 2 wurden noch mit 936 ausgeliefert, Heft 3 nicht mehr.
Die Sortierung muss vermutlich nach Feld 773 umgestellt werden.

**Comment by mtrojan-ub** [comment]
Wir haben eine Änderung an der Befüllung der Sortierfelder vorgenommen, die Auswirkungen sollten ab morgen früh auf ptah sichtbar werden.

**Comment by IxTheoKm** [comment]
Auf ptah jetzt in Ordnung, vielen Dank! Ich schließe.
