### ISSUE TITLE
Unterfeld d wird in der Schlagwortfolge nicht angezeigt

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#277]
Bsp.:
https://www.ixtheo.de/Record/496288075#details

normierte Schlagwort(-folgen): 
| B | Panorthodoxes Konzil, Kolymbari, Die Sendung der Orthodoxen Kirche in der heutigen Welt

689 ... |a Panorthodoxes Konzil |d **2016** |c Kolymbari |t Die Sendung der Orthodoxen Kirche in der heutigen Welt

Korrekte Anzeige:
Panorthodoxes Konzil (2016 : Kolymbari), Die Sendung der Orthodoxen Kirche in der heutigen Welt

**Comment by jriedl** [comment]
Existiert eine abschließende Liste, welche Kombinationen von Unterfeldern relevant sind und wie sie beim Vorhandensein anderer Unterfelder dargestellt werden müssen?

**Comment by IxTheoKm** [comment]
Jetzt in Ordnung
