### ISSUE TITLE
Links zu Unpaywall werden nicht in Volltielanzeige dargestellt

### ISSUE THREAD

**Issue by NMagin** [ubtue/tuefind#2778]
Wie der Titel schon sagt werden die automatisch über Unpaywall generierten Links zum Volltext aktuell in der Trefferliste angezeigt, aber nicht in der Volltitelanzeige. Hier am Beispiel der PPN (1794100067).
Trefferliste
![Screenshot 2024-03-28 at 15-50-32 Suchergebnisse - Bruch und Kontinuität in Todesritualen RelBib](https://github.com/ubtue/tuefind/assets/109666609/93acc954-efa2-4fce-9008-dadd5a2561de)
Volltitel:
![Screenshot 2024-03-28 at 16-00-37 Beschreibung Bruch und Kontinuität in Todesritualen RelBib](https://github.com/ubtue/tuefind/assets/109666609/74785bc5-019a-4b4d-9ad4-e4c58e06f0c7)

Beide Links sind in Feld 856 abgelegt, aber nur der DOI ist im K10plus.

**Comment by jriedl** [comment]
Aktuell nur zur Info: Problem ist eher andersherum: Es existieren Änderungen vom August 2022, in denen der Unpaywalllink explizit unterdrückt wird, wenn ein anderer OA-Link vorhanden ist. Hintergrund war, dass nicht alle Unpaywall-Links wirklich zum Volltext führen. In der IxTheo-Ansicht wird der Link in beiden Fällen  nicht angezeigt, scheint also ein Problem der RelBib-Kurztitelanzeige zu sein.

**Comment by jriedl** [comment]
Angepasste Version auf ptah (vgl. PPN 1794100067 = Titel oben).

**Comment by NMagin** [comment]
Danke, jetzt wird nur noch der eine Link angezeigt. Ich fand aber die Anzeige beider Links nicht so schlecht, weil der Link aus dem K10plus kein Volltextlink ist, der von Unpaywall aber schon. 
Was waren denn die Gründe für das Unterdrücken des Unpaywall-Links und woran macht das System fest, ob es sich beim katalogisierten DOI um einen Volltextlink handelt?

**Comment by jriedl** [comment]
Das Argument war, dass die "Volltext"-Links von Unpaywall z.T. eben nicht auf den Volltext verweisen. Das Kriterium für OA ist "Kostenfrei" in 856$3. Im Fall von 1794100067  ist in 856$u ein DOI-Link hinterlegt. Der führt zum Volltext auf der Verlagsseite, allerdings wirkt es so, als wäre das nicht OA. Wenn die entsprechenden Angaben im K10 angepasst werden, würde der Unpaywalllink wieder angezeigt.

**Comment by jriedl** [comment]
Nachtrag: gemeint war oben 856$z - wurde angepasst

**Comment by NMagin** [comment]
Sieht jetzt gut aus. Ich mache mal zu. Dankeschön!
