### ISSUE TITLE
"sid" in IxTheo- und RelBib-URLs

### ISSUE THREAD

**Issue by coeh** [ubtue/tuefind#2794]
Aktuell wird bei IxTheo-Einträgen in der Adresszeile des Browsers zusätzlich zum faktisch stabilen Link, der die PPN enthält, eine Fortsetzung mit "?sid=" angezeigt, z.B. https://ixtheo.de/Record/1589793714?sid=95667328

Das war bis vor einigen Wochen/Monaten nicht so; damals stand auch in der Adresszeile des Browsers schlicht der (nicht formal, aber faktisch) stabile Link https://ixtheo.de/Record/1589793714

- Wozu dient die Veränderung?
- Besteht die Gefahr, dass der Link mit "sid" nach einiger Zeit nicht mehr funktioniert, wenn er von Nutzenden aus dem Browser herauskopiert wird, z.B. für eine Literaturliste? (hier können durchaus einige Monate/Jahre zwischen Abspeichern und Aufruf liegen)
- Insbesondere wenn letzteres zu befürchten ist: Lässt sich das wieder ändern?

**Comment by mtrojan-ub** [comment]
Die Links sind dennoch stabil.

`sid` bezieht sich auf eine Änderung die mit einer der letzten VuFind-Versionen eingeführt wurde. Damit wird der Suchkontext weitergegeben, wenn man aus dem Suchergebnis auf einen Titel klickt. Dies wird insb. dazu benötigt um die Navigation innerhalb der Volltitelanzeige zum nächsten Suchtreffer zu ermöglichen (ist insb. dann technisch notwendig wenn man mehrere Tabs mit unterschiedlichen Suchen gleichzeitig offen hat).

![grafik](https://github.com/ubtue/tuefind/assets/26873381/b5051bb7-5f2d-473f-8e3a-597c8be03038)

Wenn man den sid-Parameter entfernt oder eine ungültige sid angegeben ist hat man trotzdem einen stabilen Link, aber dieses Steuerelement wird ausgeblendet.

**Comment by mtrojan-ub** [comment]
Übrigens ist das bereits Ende 2023 aufgefallen, siehe #2619.

**Comment by coeh** [comment]
Ah prima, vielen Dank! Dass dies ein Teil des in #2619 behandelten Problems war, hatte sich mir leider nicht erschlossen. Dann hat sich das erledigt. Ich schließe.
