### ISSUE TITLE
Keine Seitenzahlen in Volltitelanzeige

### ISSUE THREAD

**Issue by coeh** [ubtue/tuefind#2795]
Aktuell werden in der Volltitelanzeige bei Aufsätzen keine Seitenzahlen angezeigt, z.B. bei https://ixtheo.de/Record/1735212466?sid=95667328:

![grafik](https://github.com/ubtue/tuefind/assets/83448862/1a5dcafe-c1b9-4cb1-a98a-73a7ce0fec49)

obwohl die Seitenzahlen korrekt erfasst sind und in der Kurztitelanzeige auch angezeigt werden:
![grafik](https://github.com/ubtue/tuefind/assets/83448862/7cb007cf-5cba-42b7-900c-42b99f6c98b3)

Bei Sammelbandaufsätzen ist es ebenso (z.B. https://ixtheo.de/Record/1589793714?sid=95667328). 

Das ist für den wissenschaftlichen Gebrauch ungünstig, da die Nutzenden für die vollständige Zitation jedes Mal zuerst auf die Kurztitelanzeige zurückschalten müssen (Nachsehen auf der Registerkarte Internformat wäre natürlich auch möglich, aber das macht außer Bibliothekar*innen vermutlich niemand ;). Nach meiner Erinnerung war es auch nicht immer so, aber ich kann leider zeitlich nicht festmachen, wann ich es das letzte Mal anders gesehen habe.

**Comment by mtrojan-ub** [comment]
Ich schließe diesen Issue da die Thematik im Rahmen von #2801 weiterverfolgt werden kann.
