### ISSUE TITLE
Fehlende Band-, Heft- und Seitennummer in der Volltitelanzeige 

### ISSUE THREAD

**Issue by socheres** [ubtue/tuefind#2801]
https://ixtheo.de/Record/1646456254?sid=96350311

In der Ergebnisliste (=Kurztitelanzeige) werden dagegen alle genannten bibliographischen Angaben angezeigt:
https://ixtheo.de/Search/Results?lookfor=Patripassianism&type=AllFields&limit=20&botprotect=

**Comment by coeh** [comment]
Vgl. #2795 (mir waren dort in einem anders gelagerten Fall nur die Seitenzahlen aufgefallen. Ist aber vermutlich das gleiche Problem.)

**Comment by mtrojan-ub** [comment]
Ready for testing auf ptah+sobek, ich schalte das auch gleich als Hotfix live. Es ist jetzt erstmal notdürftig behoben, wobei die ganze Thematik nach wie vor im Rahmen von #2730 (und weiteren) großflächiger überarbeitet werden muss.

**Comment by coeh** [comment]
Bei Sammelbandartikeln mit Reihe gibt es allerdings noch ein Problem: 
Hier wird nämlich jetzt der Band - der eine Zählung innerhalb der Reihe ist - beim Titel des einzelnen Bandes angezeigt. Das ist verwirrend und sollte nicht so sein, denn von dem Titel "Die Crucigers" im Beispiel gibt es natürlich keine 40 Bände (sondern vielmehr von den Leucorea-Studien als Reihe, in der der Band "Die Crucigers" die Nummer 40 darstellt). Die Reihe wird jetzt aber in der Volltitelanzeige zum einzelnen Aufsatz gar nicht mehr angezeigt. 
Beispiel https://ptah.ub.uni-tuebingen.de/Record/1760347604?sid=29216:
![grafik](https://github.com/ubtue/tuefind/assets/83448862/2f059a5a-d76f-43cd-b323-119e3951b529)

**Comment by socheres** [comment]
Band-, Heft-, Seitenzaheln werden, sofern im MARC vorhanden, in der Volltitelanzeige richtig angezeigt. Ich schließe das Issue.

**Comment by coeh** [comment]
Das Problem ist möglicherweise, dass die Angaben bei Zeitschriften- wie Sammelbandaufsätzen im gleichen Feld (936 in MARC bzw. 4070 in PICA) stecken. Bei Zeitschriftenaufsätzen ist die daraus generierte Anzeige korrekt, bei Sammelbandaufsätzen nicht. Die Frage wäre, ob sich das rein technisch unterscheiden lässt. 
Ansonsten könnte man vielleicht im Rahmen der aktuellen, vorübergehenden Lösung vorläufig die Anzeige des Bandes weglassen; das wäre dann zwar im Fall von Zeitschriften nicht ganz komplett (aber nicht inhaltlich uneindeutig, wenn das Jahr weiterhin dasteht), aber dafür bei den Sammelbänden nicht mehr falsch. Oder hat die Variante irgendein Problem, das ich gerade übersehe?

**Comment by socheres** [comment]
Die Bandangabe "40"  in der PPN 1760347604 ist vermutlich ein Erfassungsfehler. @IxTheoKm Können Sie dies bestätigen?
