### ISSUE TITLE
Falsche/unterschiedliche Anzeige der Unterfelder von Schlagwörtern

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#281]
Die Unterfelder von Werktiteln werden in 689 in unterschiedlicher Reihenfolge angezeigt.

Korrekt:
https://ptah.ub.uni-tuebingen.de/Record/501713727#details

689 |d u |0 (DE-588)4444802-8 |0 (DE-576)212506889 |2 gnd |**a** Katholische Kirche |**t** Codex iuris canonici |**f** 1983 |**p** 605

normierte Schlagwort(-folgen): | B | Katholische Kirche, Codex iuris canonici (1983). 605

Falsch:
https://ptah.ub.uni-tuebingen.de/Record/496811967#details

689 |d u |0 (DE-588)1126754439 |0 (DE-576)484767240 |2 gnd |**t** Codex iuris canonici |**p** 838 |**a** Katholische Kirche |**f** 1983

normierte Schlagwort(-folgen): | B | ... Codex iuris canonici. 838, Katholische Kirche (1983)

**Comment by jriedl** [comment]
Bislang wurden bereits existierende Felder ersetzt und neue am Ende eingefügt. Um die in den Normdaten vorgegebene Reihenfolge zu erhalten, werden jetzt in den Normdaten enthaltenen Unterfelder in den Titeldaten zunächst entfernt und dann in der Normdatenreihefolge geschrieben.

**Comment by IxTheoKm** [comment]
Auf PTAH jetzt korrekt. Vielen Dank!
