### ISSUE TITLE
Thema (Schlagwort) browsen: Verlag & RelBib-Klassifikation führen ins Leere

### ISSUE THREAD

**Issue by NMagin** [ubtue/tuefind#2810]
Wenn man im Bereich "browsen / nach Kategorien" auf "Thema (Schlagwort)" geht und dann weiter auf "Nach Verlag" oder "Nach RelBib-Klassifikation" einschränkt bekommt man keine Ergebnisse. Die Kategorien "Verfasser" und "Alphabetisch" funktionieren.
![Screenshot 2024-05-14 at 10-21-28 Katalog browsen RelBib](https://github.com/ubtue/tuefind/assets/109666609/ec900d37-80a8-4b79-90f8-04e712e6c454)

Das Problem tritt in Relbib und Ixtheo auf.

**Comment by jriedl** [comment]
Auf ptah.

**Comment by NMagin** [comment]
Danke, das Problem ist behoben und ich mache das Issue zu.
