### ISSUE TITLE
Bitte um Angleichung: Browsen nach Klassifikation

### ISSUE THREAD

**Issue by NMagin** [ubtue/tuefind#2811]
Momentan wird in RelBib im Browsen nach Kategorien in der Unterkategorie "RelBib-Klassifikation" nur dir Option "Nach Klassen" zur weiteren Einschränkung angeboten:
![Screenshot 2024-05-14 at 10-43-49 Katalog browsen RelBib](https://github.com/ubtue/tuefind/assets/109666609/1b275183-fdef-418e-b3c4-2d080419c37e)

Im IxTheo gibt es noch die zusätzlichen Kategorien "Nach Thema" und "Nach Verlag":
![Screenshot 2024-05-14 at 10-43-37 Katalog browsen IxTheo](https://github.com/ubtue/tuefind/assets/109666609/51955081-34e6-447a-b070-f8a3e9b52182)

Wäre es möglich diese Optionen auch in RelBib nachzuziehen?

**Comment by mtrojan-ub** [comment]
ready for testing auf ptah

**Comment by NMagin** [comment]
Sieht gut aus und funktioniert, soweit ich das beurteilen kann, wie es soll. Danke euch für die Anpassung.

Ich mach dann mal direkt zu.
