### ISSUE TITLE
Sprache bei Zeitschlagwörtern wechselt automatisch falsch

### ISSUE THREAD

**Issue by coeh** [ubtue/tuefind#2817]
Bei einer normalen Suche (Eingabe von Stichworten in die Suchleiste ohne zusätzliche Einschränkungen) im IxTheo wurden heute alle Zeitschlagwörter auf Griechisch angezeigt, obwohl ich nichts an den Spracheinstellungen verändert hatte. Nach expliziter Auswahl "Deutsch" in der Spracheinstellung oben rechts sprangen sie korrekt auf Deutsch zurück, bei der nächsten Suche werden aber nun alle Zeitschlagwörter auf Russisch angezeigt (siehe Screenshot).
![grafik](https://github.com/ubtue/tuefind/assets/83448862/f4596d63-2cf1-4a62-8746-be8460540fce)

**Comment by jriedl** [comment]
Ursache des Problems war offenbar eine sog. Race Condition im DocTransformer: Vor der Rückgabe des VuFind-Systems werden einige sprachabhängige Inhalte in Felder mit allgemeinen Bezeichnungen übertragen, um die Komplexität bei der weiteren Verarbeitung zu reduzieren. Race Condition bedeutet, dass zwei unterschiedliche Prozesse auf die gleiche Ressource zugreifen und je nach Zugriffsreihenfolge Inkonsistenzen auftreten können. Eine angepasste Version (https://github.com/ubtue/ub_tools/pull/4519) findet sich auf ptah und ub16.

**Comment by coeh** [comment]
Vielen Dank! Ich habe es gerade an beiden Stellen getestet und es funktioniert m.E. jetzt wieder "normal" d.h. die eingestellte Sprache bleibt erhalten.

**Comment by jriedl** [comment]
Falls diesbezüglich nichts mehr offen ist, bitte schließen, ein inhaltlicher Zusammenhang zu #2700 scheint nicht zu bestehen.

**Comment by coeh** [comment]
Entschuldigung, nein, hier ist nichts mehr offen. Ich schließe.
