### ISSUE TITLE
Anzeige ICON bei Körperschaften in Kurztitelanzeige

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#2820]
Die Personen und Körperschaften werden immer mit einem anklickbaren Symbol hinter dem Namen versehen.
In der Kurztitelanzeige bei Körperschaften fehlt das.
Beispiel Personen:
https://www.ixtheo.de/Search/Results?lookfor=(author_id:%22077404084%22%20OR%20author2_id:%22077404084%22%20OR%20author_corporate_id:%22077404084%22%20OR%20author3_id:%22077404084%22)
<img width="607" alt="Bildschirm­foto 2024-06-05 um 08 27 38" src="https://github.com/ubtue/tuefind/assets/14169098/81960aa0-4c84-40b3-9426-564915440269">

Beispiel Körperschaften:
https://www.ixtheo.de/Search/Results?lookfor=(author_id:%22381937348%22%20OR%20author2_id:%22381937348%22%20OR%20author_corporate_id:%22381937348%22%20OR%20author3_id:%22381937348%22)
<img width="614" alt="Bildschirm­foto 2024-06-05 um 08 27 45" src="https://github.com/ubtue/tuefind/assets/14169098/225a7d5f-a474-4867-8a1e-558b369b183d">

In der Langtitelanzeige tritt der Fehler nicht auf:
<img width="718" alt="Bildschirm­foto 2024-06-05 um 08 28 30" src="https://github.com/ubtue/tuefind/assets/14169098/31aafed2-d5f1-489c-b8f5-59dfd3daf495">

**Comment by LysogorAndGmail** [comment]
@thefass Auf ptah ist es jetzt provisorisch eingebunden. Kannst Du es bitte anschauen und Feedback geben?

**Comment by thefass** [comment]
Ja, sieht sehr gut aus. Danke, kann auf das Produktivsystem übernommen werden. Ich schließe
