### ISSUE TITLE
VuFind 9.1: Anzeige "Alle auswählen/Auswahl"

### ISSUE THREAD

**Issue by ja-bre** [ubtue/tuefind#2833]
Alle auswählen/Auswahl wird auf allen Sprachen als select_page | with_selected: angezeigt.

<img width="372" alt="Bildschirmfoto 2024-06-14 um 07 56 01" src="https://github.com/ubtue/tuefind/assets/83392048/d7ffc2b2-3cd7-409b-a52f-a87dd60cdaad">

**Comment by mtrojan-ub** [comment]
Habe ich bei mir lokal bereits korrigiert. Wir sammeln gerade einige kleinere Bugfixes und werden voraussichtlich Anfang nächster Woche nochmal ein kleineres Update einspielen, bei dem auch dieser Fehler behoben ist.

**Comment by mtrojan-ub** [comment]
Die Änderung wurde nun auf ptah+sobek eingespielt => ready for testing

**Comment by ja-bre** [comment]
Der Text weicht jetzt von der bisherigen Darstellung ab, die so aussieht:

![grafik](https://github.com/ubtue/tuefind/assets/83392048/90f5c3ea-b051-44df-9030-be072d746904)

![grafik](https://github.com/ubtue/tuefind/assets/83392048/b10604fb-e19a-445e-afda-afb1bd3848a2)

**Comment by mtrojan-ub** [comment]
Der bisher angezeigte Text stammt aus VuFind, wurde dort im Rahmen des Versionsupdates geändert und wir haben die Änderung übernommen (übliche Vorgehensweise).

**Comment by ja-bre** [comment]
Alles klar; dann passt alles und ich schließe. Dankeschön!
