### ISSUE TITLE
Weiterleitung von Personenseite auf Personenseite verbundener Autoren funktioniert nicht

### ISSUE THREAD

**Issue by NMagin** [ubtue/tuefind#2842]
Wenn ich in RelBib auf einer Personenseite auf den Button für die Personenseite (Bild 1) klicke, wird die daraus resultierende Suchabfrage nicht richtig ausgelöst und ich bekomme eine Fehlermeldung (Bild 2).
![Screenshot 2024-06-21 at 17-25-51 Internformat Antes Peter 1942- RelBib](https://github.com/ubtue/tuefind/assets/109666609/10ef6f5e-21fb-4f2d-b399-1f7ec1fa5219)
Bild 1
![Screenshot 2024-06-21 at 17-27-54 Suchergebnisse - 08217251X RelBib](https://github.com/ubtue/tuefind/assets/109666609/1143f629-d4b3-432c-89c3-f0d447309436)
Bild 2

Wenn sich ein Verlag in die Autorenliste mogelt, kommt zumindest ein Suchergebnis, aber keine Weiterleitung (Bild 3).
![Screenshot 2024-06-21 at 17-29-33 Suchergebnisse - 101684819 RelBib](https://github.com/ubtue/tuefind/assets/109666609/4ab092f9-0339-443e-8e5e-67fecf7325e8)
Bild 3

Im Live-System funktioniert es, der Fehler ist aber auch in den Tstsystemen von IxTheo und KrimDok reproduzierbar.

**Comment by mtrojan-ub** [comment]
wurde behoben, ready for testing auf ptah+sobek

**Comment by NMagin** [comment]
Sieht auf allen Systemen gut aus. Danke euch!
Ich mach dann mal hier zu.
