### ISSUE TITLE
Übergeordnetes Werk in Kurztitelanzeige ohne PPN

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#2846]
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=ids%3A087361124&type=AllFields

![grafik](https://github.com/ubtue/tuefind/assets/26873381/a151b319-fdde-4a9e-bd87-ebbef372c062)

Der Link auf Christentum und Wissenschaft enthält keine PPN sondern Seitenzahlen etc,:
https://ptah.ub.uni-tuebingen.de/Record/Jg.9,%204,%20Seite%20121-136

=> macht keinen Sinn

**Comment by mtrojan-ub** [comment]
Bezieht sich auf den Fall, wenn in 773 keine PPN vorhanden ist

**Comment by mtrojan-ub** [comment]
Ich denke wir sollten den Link entfernen und stattdessen die Heft/Seitennummer etc. anzeigen. Bugfix ist in Arbeit.

**Comment by thefass** [comment]
Ja, das macht keinen Sinn. In dem Fall sind das eingespielte Daten. Wenn es keine Verknüpfung zum übergeordneten Werk gibt, dann bitte literal ausgeben

**Comment by mtrojan-ub** [comment]
ready for testing auf ptah

**Comment by thefass** [comment]
sieht gut aus 
Bei diesem Beispiel fehlt allerdings die Info aus 773: https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=Doctor+Ulrich+Sitzinger+%281525-1574%29aus+Worms&type=AllFields&filter%5B%5D=%7Eformat%3A%22Article%22&limit=20&botprotect=

<img width="703" alt="Bildschirm­foto 2024-06-24 um 23 49 10" src="https://github.com/ubtue/tuefind/assets/14169098/bdb2917c-f01f-4a5d-9e58-bd5aac5a22dc">
<img width="701" alt="Bildschirm­foto 2024-06-24 um 23 49 37" src="https://github.com/ubtue/tuefind/assets/14169098/0c7afc1a-48c6-4dac-bf8c-3b03dedf26ca">

**Comment by mtrojan-ub** [comment]
Die Metadaten scheinen aber in diesem Fall nicht so auf die Unterfelder verteilt zu sein wie erwartet. Hier gibt es nur die Unterfelder i+a, normalerweise müssten die Band/Heft/Seitenangaben separat in Unterfeld g geliefert werden (siehe initiales Beispiel)

**Comment by IxTheoKm** [comment]
Das Beispiel PPN 878995498 ist ein Sonderdruck. 
Aber unabhängig davon kann man nicht davon ausgehen, dass Feld 773 immer mit korrekten Unterfeldern erfasst wurde. Dazu gibt es zu viele Altdaten und maschinelle Einspielungen. Da steht oft nur Fließtext.

**Comment by mtrojan-ub** [comment]
OK => jetzt wird in diesem Fall zumindest noch der Text angezeigt, siehe ptah

**Comment by thefass** [comment]
sieht gut aus.
