### ISSUE TITLE
Suche einschränken: zusätzlicher Text

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#2849]
Vmtl. durch das Upgrade wird jetzt zusätzlich zu "Suche einschränken" auf der rechten Seite oberhalb der Facetten noch der Text "Treffer weiter einschränken" angezeigt:
![grafik](https://github.com/ubtue/tuefind/assets/25769591/6fcc2198-c7f8-40e1-9f92-8253f067a1fe)
https://134.2.67.9/Search/Results?lookfor=&type=AllFields&botprotect=
Das ist im Live-System nicht der Fall:
![grafik](https://github.com/ubtue/tuefind/assets/25769591/7b294105-6abb-4d61-a21a-1d8eebd059cc)
https://relbib.de/Search/Results?lookfor=&type=AllFields&limit=20&botprotect=

Das ist sowohl bei RelBib als auch IxTheo der Fall, für KrimDok nicht getestet.

**Comment by jriedl** [comment]
Auf ptah.

**Comment by jriedl** [comment]
Auf sobek.

**Comment by relhei** [comment]
Danke, passt für RelBib :)

**Comment by relhei** [comment]
@JMeister01 Passt es auch für KrimDok?
