### ISSUE TITLE
Angabe zur Rechteinformation 

### ISSUE THREAD

**Issue by ja-bre** [ubtue/tuefind#2852]
Auf Ptah und im Live-System: Die Angabe zur Rechteinformation (vgl. #1366) wird nicht mehr bei allen fraglichen Einträgen angezeigt.

  Beispiel mit korrekter Anzeige: 
  https://ixtheo.de/Record/1839860154?sid=98420348 
  
Beispiel fehlende Anzeige: 
https://ixtheo.de/Record/1875177310?sid=98420348#details

Im Internformat sind in Feld 540 die gleichen Angaben zu finden.

**Comment by mtrojan-ub** [comment]
`Im Internformat sind in Feld 540 die gleichen Angaben zu finden.`

Die Aussage ist nicht 100%ig korrekt, da sich die URL unterscheidet (im Bezug auf den Slash `/` am Ende). Die Auswertung wurde soeben angepasst und ist nun etwas toleranter. Ready for testing auf ptah.

**Comment by ja-bre** [comment]
Super, vielen Dank! Die Angabe ist jetzt auf ptah in beiden Fällen vorhanden.
