### ISSUE TITLE
Meine Alerts: Löschen eines Abos nicht möglich

### ISSUE THREAD

**Issue by NMagin** [ubtue/tuefind#2854]
Momentan funktioniert im Testsystem auf der Unterseite "Meine Alerts" im Nutzerkonto das De-Abonnieren von Zeitschriften und Zeitschriftenpaketen nicht. Beim Klick auf "Löschen" erscheint zwar das Dropdown-Menü, der Klick auf "Ja" bleibt aber wirkungslos.
![Screenshot 2024-06-25 at 09-21-07 Meine Alerts RelBib](https://github.com/ubtue/tuefind/assets/109666609/41ea50b6-371d-4752-83ad-fa2368acc042)
Ein Löschen des Abos über die Volltitelanzeige der Zeitschrift/des Pakets ist weiterhin möglich. Es scheint also kein grundlegendes Problem des Alert-Systems zu sein.
Im Live-System tritt das Problem nicht auf.

**Comment by mtrojan-ub** [comment]
ready for testing auf ptah

**Comment by ja-bre** [comment]
Bei IxTheo war der Bug auch vorhanden, ich hatte das bei meinem ursprünglichen Test gar nicht bemerkt. Habe es gerade gestestet und es funktioniert ebenfalls wieder.

**Comment by NMagin** [comment]
@JMeister01 Wie sieht es bei KrimDok aus? Wenn da auch alles passt, kannst du hier zumachen.

**Comment by JMeister01** [comment]
KrimDok ist davon nicht betroffen, danke.
