### ISSUE TITLE
Alerting: Mailtext vereinheitlichen

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#2858]
Beim Zs-Alerting erhalte ich auf unterschiedliche Konten verschiedene Mailtexte:

Bsp. Konto auf Test-System mit Länderangabe "Gambia":
![grafik](https://github.com/ubtue/tuefind/assets/25769591/876e781c-c817-4bc0-85d5-35a1c07aa2f4)

Bsp. Konto auf Live-System mit Länderangabe "Vereinigtes Königreich" (andere Mailadresse hinterlegt:
![grafik](https://github.com/ubtue/tuefind/assets/25769591/9a80140d-a082-4e15-ab49-d3bd9f08f926)

Beim Feed-Alert erhalte ich wiederum eine andere Anrede:
(Konto: Test-System; Länderauswahl "Gambia")
![grafik](https://github.com/ubtue/tuefind/assets/25769591/bac4e974-a615-4a70-9779-047ca0f5f39d)

Die Anrede sollten vereinheitlicht werden. 
Vorschlag: "Sehr geehrte/r [Name von Nutzer*in]"

Welcher englische Text wird in den beiden Fällen (Zeitschriften-Alerting und Feed-Alerting) angezeigt? Wie könnten wir das testen?

**Comment by mtrojan-ub** [comment]
Folgende Email-Templates sind im System hinterlegt:
- [Zeitschriften (DE)](https://github.com/ubtue/ub_tools/blob/master/cpp/data/new_journal_alert_email.template.de)
- [Zeitschriften (EN)](https://github.com/ubtue/ub_tools/blob/master/cpp/data/new_journal_alert_email.template.en)
- [RSS (DE)](https://github.com/ubtue/ub_tools/blob/master/cpp/data/rss_email.template.de)
- [RSS (EN)](https://github.com/ubtue/ub_tools/blob/master/cpp/data/rss_email.template.en)

Zur Frage, wann welche Sprachvariante verschickt wird:
Ein `language`-Feld im Benutzerprofil bei dem man die Sprache bewusst auswählen könnte, gibt es aktuell nicht. Es gibt lediglich ein `country`-Feld, was ja nur indirekt etwas mit der Sprache zu tun hat.
Um zu ermitteln, welches Template an den Benutzer gesendet wird, wird ein VuFind-Standardfeld verwendet: `last_language`. Darin speichert VuFind die Sprache, die vom Benutzer zuletzt rechts oben im Benutzerinterface ausgewählt wurde. Im Falle von Deutsch verwenden wir das Deutsche Template, sonst immer das Englische.

**Comment by relhei** [comment]
Danke. Hab jetzt auch den Grund herausgefunden, wann "Subscriber" statt des Klarnamens erscheint: dann, wenn man keinen Namen im Kontoprofil hinterlegt hat. Im Deutschen schlage ich dann statt "Subscriber" die Verwendung von "Abonnent/in" vor.

**Comment by mtrojan-ub** [comment]
ready for testing auf ptah

**Comment by relhei** [comment]
Problem ist, dass es im Deutschen jetzt stimmt, aber im Englischen nun "Dear Abonnent/in" erscheint :)
![grafik](https://github.com/user-attachments/assets/f876b6dc-bf80-485f-a26a-eb9d8c0c9ab5)
Im Englischen kann "subscriber" ja beibehalten werden.

**Comment by mtrojan-ub** [comment]
Es sollte im Englischen auch Dear Subscriber sein und ist auch so implementiert, aber aus irgend einem Grund zieht er das an dieser Stelle nicht.

Ich habe gerade wenig Zeit dem selbst weiter nachzugehen, gebe es an @steven-lolong  weiter.

**Comment by mtrojan-ub** [comment]
Es gab ein Update dazu auf ptah, ist also wieder ready for testing, die nächsten Mails die verschickt werden müssten korrekt sein.

Die Platzhalter wurden zwar korrekt befüllt aber das falsche Template gezogen. Technisch gesehen wurde die Sprache des 1. Benutzers genommen und dazu das passende Template abgefragt und fälschlicherweise auf alle anderen Benutzer angewendet. Das war auf den Entwicklermaschinen nur schwer reproduzierbar, da wir ja normalerweise bei uns lokal nur 1 Benutzer anlegen.

**Comment by relhei** [comment]
Sieht jetzt gut aus. Danke!
