### ISSUE TITLE
Unvollständige Korrektur?

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#286]
Im Titel https://ixtheo.de/Record/465691080#details war urspr. dreimal dasselbe Schlagwort vorhanden. Zwei wurden im SWB gelöscht: jetzt 689 00$Du$0(DE-588)4134866-7$0(DE-576)209655860$2gnd$tGethsemane-Erzählung

Im Titel ist das Schlagwort nochmal mit Unterfeld a vorhanden und wird in der Schlagwortfolge doppelt angezeigt:
![gethsemane](https://user-images.githubusercontent.com/17004223/40602240-284badda-6258-11e8-9859-0f46c1d37690.png)

**Comment by jriedl** [comment]
Das kommt dadurch zustande, dass ja in den Normdaten das Unterfeld $a aber nicht $t existiert. Damit bleibt das in den Titeldaten vorhandene $t bestehen und $a wird neu (und damit doppelt) eingefügt.

**Comment by IxTheoKm** [comment]
Folgt daraus, dass löschen nichts nützt? 

Ich habe im Titelsatz / in der Schlagwortfolge überzählige Schlagwörter gelöscht. Wird die alte Schlagwortfolge 689 nicht komplett durch die neue, kürzere Schlagwortfolge überschrieben?

**Comment by jriedl** [comment]
Es werden die Unterfelder ersetzt, die in den jeweiligen Normdaten vorhanden sind - auch um vorhandene weitere Felder in 689 zu erhalten. Wenn die Unterfeld-Bezeichner in den Normdaten nicht zu den in dem im Titelfeld angegebenen passen (weil $a aus den Normdaten zu $t in den Titeldaten wird), kommt dieser Ersetzungsansatz an Grenzen, weil ja dann für jede Kombination von Unterfeldern Abbildungsregeln notwendig werden würden. Ist im konkreten Fall die Ersetzung von $t durch $a nicht zulässig?

**Comment by IxTheoKm** [comment]
Da bin ich absolut überfragt.

Ich erkenne nur im Titelsatz, dass die Schlagwortfolge mit
689 00$Du$0(DE-588)4134866-7$0(DE-576)209655860$2gnd$tGethsemane-Erzählung
ausgeliefert wird.

Der Schlagwortnormsatz hat zwar 130 0$aGethsemane-Erzählung
aber mir ist nicht klar, warum nur das Ansetzungsfeld aus dem Schlagwortnormsatz in 689 angefügt wird, wenn doch der ganze Titelsatz bzw. die ganze Schlagwortfolge im **Titel**satz korrigiert wurde.

Am Schlagwortnormsatz wurde nichts geändert.

Ich habe es so verstanden, dass Änderungen im (Schlagwort-)Normsatz über die Sekundärkorrekturen greifen müssen. Dann müssen sie in ein vorhandenes Feld 689 im Titelsatz "eingepasst" werden.

Aber warum werden Änderungen im Titelsatz - einschließlich der Änderungen in den Schlagwortfolgen in Feld 689 - nicht genauso übernommen? Warum / welche Felder sollen in 689 erhalten bleiben, wenn doch 689 im Titelsatz praktisch in neuer, korrigierter Form kommt?

**Comment by jriedl** [comment]
Mein Stand war bisher, dass das Ausgangsproblem war, dass Änderungen an den Normdaten nicht in die Titeldaten einfließen und die 689-Felder bei einem Komplettabzug auch jeweils aus den Normdaten erzeugt neu werden (deshalb ja auch der Verweis im 689-Feld auf die jeweilige Normdaten-PPN). In 689 finden sich ja z.B. noch die Unterfelder $D , $0 etc, die auch erhalten bleiben müssen, damit die Struktur unserer 689 Felder nicht kaputtgeht.  Unser Ansatz im Zusammenhang mit weiteren/korrigierten Unterfelden in den Normdaten ist nun, die in den Normdaten enthaltenen Unterfelder durch die hier befindlichen Einträge zu ersetzen. Wenn nun die 689-Felder von vorherein gar nicht aus den Normdaten generiert, sondern manuell in potentiell anderen Unterfeldern angelegt wurden, funktioniert dieser Ansatz einfach nicht mehr, weil die Ersetzungsroutine ja nicht wissen kann, dass es im einen Fall zusätzliche Felder einfügen soll, die in Normdaten hinzugekommen sind und im anderen nicht, da eine Bezeichung aus Unterfeld $a der Normdaten manuell in $t eingetragen wurde.

**Comment by jriedl** [comment]
Wie besprochen werden Werktitel jetzt gesondert behandelt.

**Comment by IxTheoKm** [comment]
Schwer zu testen, da Normsatzkorrekturen als Beispiele nötig wären. Die kann ich aber nicht herausfinden.
Die Gethsemane-Beispiele sind jetzt jedenfalls (bis auf Erfassungsfehler in den SWB-Daten, die ich heute korrigiert habe) korrekt. Ebenso weitere per Mail gemeldete Beispiele.

**Comment by jriedl** [comment]
Das ist die bereits besprochene Problematik. Wir versuchen ja aus den Normdaten augmentieren umd hier Änderungen abzubilden. Bei den oben angeführten Beispielen haben aber die 689 Felder $Du. Damit gelten Sie als Werktitel und das Unterfeld $a aus den Normdaten muss nach $t in den Titeldaten. Das führt dann zur Verdoppelung.

**Comment by IxTheoKm** [comment]
Ich schlage vor, diesen Zustand vorerst so zu belassen, da ich nicht weiß ob es bei Werktiteln möglicherweise Änderungen mit der Umstellung auf K10plus gibt. Dann kann man die Problematik nochmal anschauen. Einverstanden?

**Comment by jriedl** [comment]
Ok :-).

**Comment by IxTheoKm** [comment]
Die o.g. Beispiele sind jetzt in Ordnung. 
Kann es an der vollständigen Neulieferung der Daten nach K10plus liegen? 
Dann müsste das Problem eigentlich erledigt sein.

**Comment by jriedl** [comment]
Es scheint, dass durch den K10+-Komplettabzug die hinterlegten Daten bei Norm- und Titeldaten übereinstimmen. Das Problem scheint ja nur aufgetreten zu sein, wenn manuelle Änderungen an den Titeldaten und die Ersetzungsroutinen der Normdaten nicht zusammengepasst haben. Damit ist nicht ausgeschlossen, dass das Problem bei "Inkonsistenzen" zwischen manuellen Änderungen an Titeldaten und vorhandenen Normdaten zukünftig noch einmal auftaucht, aber da dafür momentan keine systematische möglich Lösung scheint und die momentan bekannten Fälle nun korrekt sind, würde ich ebenfalls vorschlagen, das Issue zu schließen.

**Comment by IxTheoKm** [comment]
Danke, ich schließe!
