### ISSUE TITLE
Personenseite - Funktionseinschränkung bei wenigen Titeln 

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#2868]
Auf der Personenseite werden die Ergebnisse in der Kategorie Neueste Titel (von) und Verbundene Autoren bei vielen Treffern abgeschnitten, durch einen Klick auf "Alle anzeigen" kann man sich alle anzeigen lassen
Bsp: https://ixtheo.de/AuthorityRecord/079607276
<img width="498" alt="Bildschirm­foto 2024-06-26 um 22 44 42" src="https://github.com/ubtue/tuefind/assets/14169098/1a5aa260-5899-4a90-b708-f7d723ae3299">

Wenn es nur wenige Treffer gibt, dann fehlt nach dieser Logik der Button "Alle anzeigen"
Bsp: https://ixtheo.de/AuthorityRecord/1839273410
<img width="723" alt="Bildschirm­foto 2024-06-26 um 22 46 53" src="https://github.com/ubtue/tuefind/assets/14169098/5f7cb18c-5d51-427d-9e33-2d4449e97dab">

Der Nachteil ist, dass man dann nicht an die Kurztitelliste kommt, wo man mit Facetten weitereinschränken kann (z.B. auf open access).

Deswegen sollte unabhängig von der Anzahl der Treffer der Button "Alle anzeigen" immer vorhanden sein.

Es ist zwar kein VuFind upgrade Problem, wäre aber schön wenn das noch bei der Freischaltung auf 9.1 dabei sein könnte.

**Comment by mtrojan-ub** [comment]
ready for testing auf ptah+sobek
