### ISSUE TITLE
(br) wird nicht richtig verarbeitet

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#2878]
im Erklärtext (blaues Kästchen) steht ein (br), das nicht richtig verarbeitet wird

https://ixtheo.de/Search/Results?lookfor=id%3A1870547802&type=AllFields&limit=20&sort=year+desc%2C+volume_sort+desc%2C+issue_sort+desc%2C+start_page+asc%2C+first_indexed+desc&botprotect=

<img width="892" alt="Bildschirm­foto 2024-07-03 um 09 20 10" src="https://github.com/ubtue/tuefind/assets/14169098/7a998785-ff01-44ba-a768-4f5aff7dcd8d">

**Comment by jriedl** [comment]
Auf ptah und ub16.

**Comment by coeh** [comment]
Auf ub16 sieht es mir jetzt gut aus, auf ptah erscheint weiterhin der gleiche Fehler (auch nach Löschen aller Browser-Cookies).

**Comment by jriedl** [comment]
Screenshot von ptah:
![image](https://github.com/ubtue/tuefind/assets/13135579/4e7c664e-2bfa-49c0-b4e1-9355fbb76c37)
Es wurden jetzt prophylaktisch auch noch einmal die serverseitigen Caches gelöscht. Funktioniert es jetzt?

**Comment by coeh** [comment]
Ja, jetzt funktioniert es. Vielen Dank!
