### ISSUE TITLE
SEO für Index Biblicus + Index Canonicus

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#2882]
Für diese beiden Instanzen werden aktuell noch keine Sitemaps generiert. Außerdem fehlen noch die wesentlichen robots.txt-Einstellungen im Vergleich zu IxTheo.

Siehe auch:
- https://ixtheo.de/robots.txt
- https://bible.ixtheo.de/robots.txt
- https://churchlaw.ixtheo.de/robots.txt

**Comment by mtrojan-ub** [comment]
Genau das haben wir vor! @LysogorAndGmail kümmert sich bei Gelegenheit drum.

**Comment by mtrojan-ub** [comment]
... übernehme ich doch selbst, da Andrii den kompletten August im Urlaub ist und es vorher nicht mehr schafft.

**Comment by mtrojan-ub** [comment]
Sitemap-Generierung läuft nun erstmal testweise auf ptah, wir warten bis es stabil läuft und übernehmen es dann bei Gelegenheit auf ub16

**Comment by mtrojan-ub** [comment]
... ist nun auf ub16 aktiv, ich werde das Issue noch offen lassen bis man in der Google Search Console sehen kann dass die Sitemaps auch von Google nachweislich gefunden werden.

**Comment by mtrojan-ub** [comment]
Die ersten URLs für die beiden Derivate werden nun von Google gelistet, daher => Einrichtung erfolgreich. Ich werde das natürlich weiter im Auge behalten, aber die initiale Einrichtung ist somit erfolgreich abgeschlossen. Daher schließe ich den Issue.

**Comment by thefass** [comment]
super. Danke!
