### ISSUE TITLE
WorldCat-Bestandssuche liefert Fehlermeldung

### ISSUE THREAD

**Issue by NMagin** [ubtue/tuefind#2885]
Die WorldCat-Bestandssuche aus RelBib (& IxTheo) heraus funktioniert noch nicht richtig und gibt nur eine Fehlermeldung aus ("We are unable to connect to this page, please try again."). 
Getest u.a. mit https://relbib.de/Record/1665416998 und https://relbib.de/Record/1670819612

Ich vermute ja fast, dass das Problem weniger bei uns und und mehr bei OCLC liegt, möchte es aber doch mal dokumentieren.

**Comment by obrandt** [comment]
Das Problem liegt bei OCLC. Zumindest konnte ich die Records eben im WorldCat sehen.

Von: NMagin ***@***.***>
Gesendet: Montag, 8. Juli 2024 11:09
An: ubtue/tuefind ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [ubtue/tuefind] WorldCat-Bestandssuche liefert Fehlermeldung (Issue #2885)


Die WorldCat-Bestandssuche aus RelBib (& IxTheo) heraus funktioniert noch nicht richtig und gibt nur eine Fehlermeldung aus ("We are unable to connect to this page, please try again.").
Getest u.a. mit https://relbib.de/Record/1665416998 und https://relbib.de/Record/1670819612

Ich vermute ja fast, dass das Problem weniger bei uns und und mehr bei OCLC liegt, möchte es aber doch mal dokumentieren.

**Comment by jriedl** [comment]
Aktuell hier nicht ebenfalls nicht reproduzierbar. Für beide oben angegebene Links liefert der in der Volltitelanzeige hinterlegte Worldcat-Link ein Ergebnis:
![image](https://github.com/ubtue/tuefind/assets/13135579/232237a7-5d6c-4bc6-a5f4-576601a04267)
![image](https://github.com/ubtue/tuefind/assets/13135579/cd9a6abc-ad34-4752-b41b-1c434437ad02)

**Comment by NMagin** [comment]
Kurzes Update von meiner Seite: Es scheint irgendwie mit dem Browser zusammenzuhängen. Chrome und Edge liefern Ergebnisse, Firefox (115.12.0esr (64-Bit)) nicht.

**Comment by jriedl** [comment]
Test oben war mit Firefox 126.0.1 unter Linux. Eventuell Firefox-Update?

**Comment by NMagin** [comment]
> Test oben war mit Firefox 126.0.1 unter Linux. Eventuell Firefox-Update?

Da mein PC durch das ZDV verwaltet wird, habe ich leider keinen Einfluss auf die Firefox-Version. Habe es auf meinem Privatrechner (127.0.2) aber nochmal getestet und hier funktioniert die Weiterleitung auch. Scheint also an älteren Firefox-Versionen zu hängen. 
Unsere Nutzer haben da hoffentlich mehr Kontrolle und ihre Browser aktualisiert.

Ich mache mal hier zu. Das Problem betrifft ja hoffentlich nicht viele Nutzende und ich weiß nicht, ob es von unserer Seite behebbar wäre.

**Comment by jriedl** [comment]
Problem tritt auch mit der Linuxversion von Firefox (115.12.0esr) auf.
