### ISSUE TITLE
Fehlermeldung bei Volltextsuche mit Synonymen

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#2887]
Vielleicht noch ein Bug nach dem Upgrade?

Bei Auslösen einer Volltextsuche mit Synonymen gibt es folgende Fehlermeldung:
![grafik](https://github.com/ubtue/tuefind/assets/25769591/7a798e9f-9c39-4ea8-8102-b0bbee3ba825)
https://relbib.de/Search2/Results?lookfor=Umweltschutz&type=FulltextWithSynonyms&hiddenFilters%5B%5D=has_fulltext%3A%221%22&limit=20&botprotect=

Die anderen beiden Modi der Volltextsuche funktionieren.

**Comment by jriedl** [comment]
Auf ptah und ub16. Ursache war, dass bei Relbib noch ein in diesem Kontext überflüssiges Highlighting aktiv war, das mit der Abstraktion der Feldbezeichnungen über die lokalisierten Inhalte nicht zurecht gekommen ist.

**Comment by relhei** [comment]
Sieht jetzt gut aus - danke!
