### ISSUE TITLE
Neues Selektionskriterium für IxBib

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#2894]
Bitte zusätzlich neben "BIIN" für den Index Biblicus auch "BiBIL" berücksichtigen:
BiBIL | 0575 | 935 $a[Wert]

https://github.com/ubtue/tuefind/wiki/Daten-Abzugs--und-Selektionskriterien#selektionskriterium-f%C3%BCr-das-subsystem-bibelwissenschaften-index-biblicus

**Comment by thefass** [comment]
In die Dokumentation habe ich das schon eingetragen.
@mtrojan-ub Wir bräuchten dann das Abrufzeichen BiBIL auch im Gesamtabzug. Ich habe das oben schon eingetragen. Kannst Du bitte das BSZ informieren?

**Comment by IxTheoKm** [comment]
Auf ptah ist es jetzt in Ordnung. Es werde alle Datensätze angezeigt!

**Comment by mtrojan-ub** [comment]
=> wurde soeben im Rahmen des Mailwechsels zu den neuen Komplettabzügen ans BSZ kommuniziert.

**Comment by IxTheoKm** [comment]
Rückmeldung aus dem BSZ ist erfolgt. BiBIL wird beim Abzug berücksichtigt.

Der Stand in K10plus stimmt mit IxTheo und IxBib ptah überein.
In IxBib fehlen 25 Datensätze.

**Comment by mtrojan-ub** [comment]
Da der neue Gesamtabzug mittlerweile vorliegt setze ich diesen Issue nun auf ready for testing

**Comment by IxTheoKm** [comment]
Jetzt stimmen die Datensätze für BiBIL und für BIIN überein. Ich schließe.
