### ISSUE TITLE
Sortierung fehlerhaft

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#290]
Wenn man die Ergebnisse nach "Neueste zuerst" sortiert, ist alles wie es sein soll:

https://ixtheo.de/Search/Results?limit=100&filter%5B%5D=%7Eformat%3A%22Article%22&filter%5B%5D=publishDate%3A%22%5B2002+TO+2002%5D%22&lookfor=superior_ppn%3A102037515&type=AllFields&sort=year+desc%2C+issue_sort+desc%2C+start_page+asc

![bildschirmfoto 2018-05-30 um 22 00 25](https://user-images.githubusercontent.com/14169098/40744527-192d3e46-6455-11e8-8148-05c84ea3c555.png)

Wenn man aber zur Sortierung "Älteste zuerst" wechselt, funktioniert die Sortierung nicht mehr. Die Seitenzahlen gehen dann wild durcheinander:

https://ixtheo.de/Search/Results?limit=100&filter%5B%5D=%7Eformat%3A%22Article%22&filter%5B%5D=publishDate%3A%22%5B2002+TO+2002%5D%22&lookfor=superior_ppn%3A102037515&type=AllFields&sort=year+asc

![bildschirmfoto 2018-05-30 um 22 00 57](https://user-images.githubusercontent.com/14169098/40744509-05476244-6455-11e8-879b-9443f171ccb5.png)

**Comment by thefass** [comment]
Hier gehen bei der Sortiereinstellung "Älteste zuerst" sogar teilweise die Bände durcheinander:
Treffer 82 aus 18 (2011), Treffer 83-87 aus 19 (2011) und Treffer 88 dann wieder aus 18 (2011)

https://ixtheo.de/Search/Results?limit=100&filter%5B%5D=%7Eformat%3A%22Article%22&lookfor=superior_ppn%3A102037515&type=AllFields

![bildschirmfoto 2018-05-30 um 22 08 14](https://user-images.githubusercontent.com/14169098/40744906-4ac54c54-6456-11e8-9784-bed07bdf2f75.png)

**Comment by jriedl** [comment]
Auf ptah angepasst.

**Comment by thefass** [comment]
ok
