### ISSUE TITLE
Neue IxTheo-Klassifikation

### ISSUE THREAD

**Issue by derclou** [ubtue/tuefind#2914]
Es gibt eine neue IxTheo-Klassifikation. Das Kürzel ist "YA", die Beschreibung ist "Naturwissenschaften" auf Deutsch, "Natural sciences" auf Englisch, und "Sciences naturelles" auf Französisch. Bitte in die entsprechenden Facetten und Suchfelder auf den IxTheo- und RelBib-Webseiten (+ Index Biblicus & Index Canonicus) einfügen. Vielen Dank!

**Comment by jriedl** [comment]
Bisher sind alle Unterklassifikationen Teil einer einbuchstabigen Oberklasse ( vgl. [IxTheo-Klassifikation](https://ixtheo.de/Content/IxTheoClassification#content)). Wie soll das hier gehandhabt werden? Ist davon auszugehen, dass in nächster Zeit noch weitere Klassifikationen hinzukommen?

**Comment by derclou** [comment]
> Bisher sind alle Unterklassifikationen Teil einer einbuchstabigen Oberklasse ( vgl. [IxTheo-Klassifikation](https://ixtheo.de/Content/IxTheoClassification#content)). Wie soll das hier gehandhabt werden? Ist davon auszugehen, dass in nächster Zeit noch weitere Klassifikationen hinzukommen?

Nein, es sind keine weiteren "Y-Kürzel" geplant. Die neue Klassifikation passt konzeptuell nicht in den bisher vorhandenen Oberklassen. Es wurde am Anfang überlegt, ob sie bei den Z-Kürzeln unterkommt, aber die Zs sind für Sozial-/Humanwissenschaften gedacht, die neue Klassifikation hätte also in dieser Systematik nicht gepasst. Das Kürzel wird als "Stand-alone" eine eigene Oberklasse definieren, ähnlich dem Kürzel XA für Recht. Es werden keine zusätzliche Kürzel in diese Oberklasse hineinkommen, wir brauchen halt ein Kürzel für alle Naturwissenschaften ohne irgendeinen zusätzlichen religiösen bzw. ethischen Bezug.

**Comment by jriedl** [comment]
Der aktuelle Stand findet sich auf ptah.

**Comment by derclou** [comment]
Die neue Klassifikation fehlt immer noch in der Facette "IxTheo-Klassifikation" in der normalen Suche und in der entsprechenden Liste der erweiterten Suche.

**Comment by jriedl** [comment]
Eine Suche auf unserem aktuellen Datenbestand enthält keine Records, die in MARC 652 die Notation YA haben. Damit kann es in der Facette nicht auftauchen. Wurden bereits Records im K10Plus damit ausgezeichnet und falls ja, welche?

**Comment by derclou** [comment]
Ja, PPN 189514650X und 1891132970.

**Comment by jriedl** [comment]
Vielen Dank für die Information. Die Notation musste noch explizit in eine Mappingdatei eingetragen werden, damit sie in aus den Lokaldaten in die 652-Felder übertragen wird. Eine angepasste Version findet sich auf ptah und sollte voraussichtlich morgen nach Abschluss des nächsten vollständigen Pipelinedurchlaufs dort sichtbar sein.

**Comment by IxTheoKm** [comment]
In den Facetten fehlt "Y...", in der Titelanzeige steht nur "Naturwissenschaften":
![Klass_Y](https://github.com/user-attachments/assets/87f8a507-6474-4209-9e05-eb3343b912eb)

**Comment by jriedl** [comment]
Auf ptah.

**Comment by IxTheoKm** [comment]
In der Facette und der Titelanzeige sieht das für mich jetzt korrekt aus (@derclou müsste das noch bestätigen).
Aber wenn ich über "Browsen, Katalog browsen" suche, fehlt es noch:
![Klass_Y](https://github.com/user-attachments/assets/8584920e-7651-442f-8c9a-c3026871ec77)

Wenn ich Y Naturwissenschaften über https://ptah.ub.uni-tuebingen.de/Content/IxTheoClassification#content anklicke, sieht es so aus (das kommt mir merkwürdig vor):
![Klass_Y_2](https://github.com/user-attachments/assets/0b5570b8-d6d4-4185-be76-315e01da22c8)

**Comment by jriedl** [comment]
Oberkategorie nun auf ptah jetzt für IxTheo und Relbib vorhanden. Da die Erzeugung der einbuchstabigen Oberkategorie statisch, d.h. ohne Rückgriff auf den Datenbestand erfolgt, ist die Y-Kategorie für RelBib  aktuell noch leer. Vielleicht wäre 189514650X auch Kandidat für den Relbib-Bestand?

**Comment by IxTheoKm** [comment]
"Katalog browsen" und https://ptah.ub.uni-tuebingen.de/Content/IxTheoClassification#content sehen für mich jetzt in Ordnung aus. 
PPN 189514650X für RelBib wurde bereits mit "YA" klassifiziert. 
Muss vermutlich hier noch ergänzt werden: https://relbib.de/Browse/RelBib-Classification?findby=alphabetical&query_field=relbib-classification

**Comment by jriedl** [comment]
Die Funktionalität ist aktuell auch für RelBib nur auf ptah. Die Y-Notationen mussten nun noch explizit für den RelBib-Kontext als zulässig gekennzeichnet werden. Testimport für 189514650X auf ptah:
![image](https://github.com/user-attachments/assets/6a84a107-0161-4645-88e3-49e0a9b823b7)

**Comment by IxTheoKm** [comment]
Dann sind jetzt @derclou und @relhei im Boot zum "Absegnen".

**Comment by relhei** [comment]
Passt für mich, danke!

**Comment by derclou** [comment]
Sieht gut aus. Ich schließe dann das Issue.

**Comment by derclou** [comment]
Vielen Dank! :)
