### ISSUE TITLE
Alerting: einzelne Alerts lassen sich nicht löschen

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#2953]
Beim Löschen eines Zeitschriften-Alerts im eigenen Konto passiert nichts. Es erfolgt noch die Abfrage "Ja bzw. Abbrechen", bei Bestätigung mit "Ja" bleibt die Seite allerdings stehen.

![grafik](https://github.com/user-attachments/assets/a1db90c5-52f1-48eb-94ae-3068b3fdde56)
https://relbib.de/MyResearch/Subscriptions

Bitte wieder Löschen ermöglichen.

**Comment by mtrojan-ub** [comment]
Ist reproduzierbar. Im Suchergebnis und im einzelnen Record funktioniert es, aber nicht im Benutzerkonto unter Meine Alerts. Ich kümmer mich drum.

**Comment by relhei** [comment]
Funktioniert wieder, danke!
