### ISSUE TITLE
Titelanzeige in RelBib trotz Abrufzeichen rwex

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#296]
Obwohl wir das Abrufzeichen rwex gesetzt haben, werden diese beiden Titel nach wie vor in RelBib angezeigt:

https://relbib.de/Search/Results?lookfor=rs%3A%5Brwex%5D&type=Title&limit=20&sort=year+desc%2C+issue+desc%2C+start_page+asc%2C+first_indexed+desc

**Comment by jriedl** [comment]
Problem war, dass "rwex" nicht in 935$a steht sondern in LOK 935$a. Ist jetzt angepasst und voraussichtlich morgen auf ptah sichtbar.

**Comment by relhei** [comment]
Passt. Danke!
