### ISSUE TITLE
Fiktive Person als "Verfasser" auffindbar

### ISSUE THREAD

**Issue by derclou** [ubtue/tuefind#2969]
Bei der Suche nach "Person / Körperschaft / Tagung": Personen, die nichts verfasst haben (können), können trotzdem gefunden werden, wenn man "Verfasser" als Suchkriterium wählt. Dies fällt besonders bei Romanfiguren auf, wie das Beispiel der Figur "Fanny Price" aus einem Roman von Jane Austen sehen kann (siehe Bild). Interessanterweise kann ich das Problem in RelBib nicht reproduzieren, obwohl der selbe Aufsatz auch in RelBib auffindbar ist.
![Screenshot 2024-08-22 at 09-33-09 Suchergebnisse - fanny price IxTheo](https://github.com/user-attachments/assets/a22023d4-2bd2-4851-952a-a7fd7b951744)

**Comment by mtrojan-ub** [comment]
Sieht so aus als ob die Suche nach "Verfasser" bisher genau das gleiche Ergebnis lieferte wie die Suche "Alle Felder". Der Eintrag taucht in RelBib nicht auf, da dieser allgemein für RelBib ausgeschlossen ist (also auch als Person ausgeschlossen, nicht nur als Verfasser).

Wir haben das jetzt so angepasst, das bei Suche nach "Verfasser" nur noch Einträge auftauchen die mit mindestens 1 Titel als Autor verknüpft sind. Ready for testing auf ptah + sobek.

**Comment by derclou** [comment]
Funktioniert wunderbar auf ptah, vielen Dank. Kleine Frage: Schließt man einen Issue erst dann, wenn der Fix von ptah auf ixtheo.de übertragen wurde, oder schon jetzt, wenn das Problem auf ptah behoben ist?

**Comment by mtrojan-ub** [comment]
Issues können üblicherweise bereits geschlossen werden sobald es auf ptah funktioniert. Seit heute ist diese Änderung übrigens auch auf dem Liveserver aktiv.

**Comment by derclou** [comment]
Vielen Dank für alles, Issue wird geschlossen.
