### ISSUE TITLE
Normdaten: Beziehungskennzeichen wird nicht angezeigt

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#2995]
https://ixtheo.de/AuthorityRecord/1902586999
https://ixtheo.de/AuthorityRecord/188837456X

**"Wirklicher Name" bzw. "Pseudonym" aus $i bzw. $e im verlinkten Datensatz wird nicht angezeigt:**

500 | 1 |   | \|0 (DE-627)188837456X    \|0 (DE-588)1329168496    \|a Zimmermann, Bernd    \|4 nawi    \|w r    \|i Wirklicher Name    \|e Wirklicher Name

500 | 1 |   | \|0 (DE-627)1902586999    \|0 (DE-588)1342139143    \|a Faber, Martin    \|4 pseu    \|w r    \|i Pseudonym    \|e Pseudonym

![Faber](https://github.com/user-attachments/assets/dffbd779-85c3-4447-bdd4-41d02e35f6f1)

![Faber2](https://github.com/user-attachments/assets/31d43274-13ab-4fc5-844c-120a75d93c13)

**Comment by mtrojan-ub** [comment]
Ready for testing auf ptah

**Comment by IxTheoKm** [comment]
Perfekt, danke!
Ich schließe.
