### ISSUE TITLE
Fehlende Verknüpfung (Gemeinsame Titel mit diesem Autor, wenn ID fehlt)

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#3002]
Auf der Personenseite gibt es eine Information zu den Verbundenen Autoren:
https://ixtheo.de/AuthorityRecord/610247964

Wenn man darauf klickt, werden Sie in einer Liste angezeigt:
https://ixtheo.de/AuthorityRecord/610247964

Es scheint nun so, dass nur bei Autoren, die ein GND Nummer haben, die gemeinsamen Werke (also das Kettensymbol) angezeigt wird, jedoch nicht bei Autoren ohne GND, bei denen logischerweise das Personen-Icon fehlt (Beispiel: Assefa, Daniel etc.)
<img width="451" alt="Bildschirm­foto 2024-10-02 um 13 17 54" src="https://github.com/user-attachments/assets/07acb7b2-5d90-4f22-ad3e-d4ae4ee4a742">

**Comment by mtrojan-ub** [comment]
Die 2. URL in der Beschreibung ist gleich wie die erste. Vermutlich ist die hier gemeint?
https://ixtheo.de/Author/Search?author_id=610247964

In diesem Fall hat der Ausgangs-Autor eine ID, aber der Ziel-Autor nicht. Das Kettensymbol wird bisher nur angezeigt wenn der Ziel-Autor ebenfalls eine ID hat.

Wie genau sollte denn der Link hinter dem Kettensymbol funktionieren? Titel abfragen die die ID des Ausgangs-Autors haben sowie den Namen des Ziel-Autors? (Also eine Fuzzy-Abfrage - brauchen wir dafür ein anderes Symbol?)

**Comment by thefass** [comment]
ja, diese ist gemeint. Ich schlage vor, wir nehmen das Issue in die nächste IT Besprechung mit

**Comment by mtrojan-ub** [comment]
Ergebnis des Meetings: Wenn etwas in der Liste auftaucht sollte auch der fuzzy-link angezeigt werden, aber ob man auch die Autoren ohne GND-Nummer aufnimmt oder nicht werden @thefass und @socheres noch im Anschluss weiter diskutieren.

**Comment by thefass** [comment]
Zwischen uns geklärt, bitte umsetzen.
Dabei haben wir zufällig festgestellt, dass jetzt schon das Kettensymbol in der Kurzliste (die 5 Häufigsten) auch bei unverknüpften Autoren angezeigt wird, nicht aber in der Langliste. Ihr müßt also nur das Kettensymbol auf die Langliste "mitnehmen".
Hier ein Beispiel dazu:
https://ixtheo.de/AuthorityRecord/781117895
Hier ist in den Verbundenen Autoren der nicht normierte Jost, Garry mit Kettensymboil dargestellt
<img width="335" alt="Bildschirm­foto 2024-10-29 um 13 00 55" src="https://github.com/user-attachments/assets/4a35451b-855a-4349-8679-6ffada74f867">

Sobald man aber auf "Alle anzeigen (7)" klickt > https://ixtheo.de/Author/Search?author_id=781117895 fehlt das Kettensymbol
<img width="534" alt="Bildschirm­foto 2024-10-29 um 13 02 30" src="https://github.com/user-attachments/assets/a0f7f906-8078-46f0-9fec-27976636f05e">

**Comment by mtrojan-ub** [comment]
ready for testing auf ptah

**Comment by thefass** [comment]
Perfekt, Danke.
