### ISSUE TITLE
Seitenladefehler bei "Fernleihe für Fachinformationsdienste"

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#3006]
Bei mir funktioniert aktuell die Weiterleitung auf die "Fernleihe für Fachinfrmationsdienste" nicht:
![grafik](https://github.com/user-attachments/assets/11c8e8d2-081d-49d7-91d2-5be3d7cd94cd)
https://relbib.de/Record/1858189535?sid=118208386

Ich habe für mehrere Titel probiert, immer kommt eine Fehlerseite wie diese:
https://fid.fernleihe.de/?&rft_id=info:gvi/(DE-627)1858189535&svc.ill=yes&req_dat=&rfr_id=info:sid/RelBib

Ist das bekannt?
Mit Hinblick auf unseren morgigen Workshop: Könnte die Funktionalität evt. ausgeblendet werden, bis der Fehler gelöst ist?

**Comment by mtrojan-ub** [comment]
fid.fernleihe.de scheint aktuell gar nicht mehr erreichbar zu sein => das ist wohl eher ein Problem auf Anbieterseite aber nicht bei uns, kann also sein es funktioniert bis morgen wieder

**Comment by thefass** [comment]
@relhei ich würde das nicht ausblenden, sondern anmerken, dass es bei Nutzung externer Dienste auch mal zu einem Ausfall kommen kann.

**Comment by jriedl** [comment]
Kurzer Nachtrag: Wenn man die fid.fernleihe.de-Addresse auflöst und einen Reverse Lookup der resultierende IP-Adresse macht, so gehört die Maschine zu kobv.de, also dem Kooperativen Bibliotheksverbund Berlin-Brandenburg. Vielleicht kann man denen zu Sicherheit Bescheid geben, dass ihr System unten ist.

**Comment by jriedl** [comment]
Soeben kam die Rückmeldung von KOBV, dass das Problem behoben wurde.

**Comment by relhei** [comment]
Super - vielen Dank fürs nachhaken!
