### ISSUE TITLE
Browser-Problematik: Katalog browsen > Verfasser > Alphabetisch mit merkwürdiger Darstellung

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#3007]
Wenn ich in RelBib "Browsen nach Kategorien" verwende und dann alphabetisch nach Verfassern browse, werden diese in einer wenig übersichtlichen Liste wie folgt angezeigt:
![grafik](https://github.com/user-attachments/assets/e69c835d-8b36-4320-abe4-febb71525c3e)
https://relbib.de/Browse/Author?findby=alphabetical&category=&query=A%2A&facet_prefix=A&query_field=author_facet&facet_field=author_facet

Ich verwende Mozilla Firefox in der Version 128.3.0 Firefox ESR. 
In einem anderen Browser (Edge) ist die Darstellung regulär:
![grafik](https://github.com/user-attachments/assets/0bcb4733-08c0-4fa2-93cd-29bb95e21741)

**Comment by IxTheoKm** [comment]
Ich verwende auch Firefox (dieselbe Version). Bei mir ist die Anzeige korrekt (wie im zweiten Screenshot).

**Comment by relhei** [comment]
Im Fehlerbehebungsmodus ist die Anzeige korrekt.

**Comment by relhei** [comment]
Ok, vielen Dank! Das war des Rätsels Lösung: Tampermonkey hatte das verursacht. Das war schon mal der Grund, hatte ich leider vergessen. Ich schließe!
