### ISSUE TITLE
Elektronische Reproduktion als "Band / Aufsatz" angezeigt

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#302]
Bei dem Titel handelt es sich um eine OA-Zweitveröffentlichung einer Monografie. Sie wird allerdings als Band angezeigt. Klickt man auf den Link hinter "In:" gelangt man zum Drucktitel. Auch dieser wird als "Band" angezeigt und bei Klick auf "In:" glengt man zurück zur elektronischen Reproduktion. Kann es sein, dass hier das Feld 776 nicht richtig ausgelesen wird?

https://relbib.de/Record/501621997

**Comment by IxTheoKm** [comment]
Dieser Fehler kommt nicht nur in RelBib vor.

https://ixtheo.de/Record/020985835
https://ixtheo.de/Record/505483378

Es handelt sich um Originaldokumente und Reproduktionen, die jeweils miteinander verlinkt sind.

**775**: Reproduktion liegt in gleicher physischer Form vor
Einleitende Wendungen in **$i** können sein:
    _Äquivalent
    Digitale Übertragung von / Digitale Übertragung
    Faksimile von / Faksimile
    Bestanderhaltungsfaksimile von / Bestanderhaltungsfaksimile
    Nachdruck von / Nachgedruckt als
    Reproduktion von / Reproduziert als_


**776**: Reproduktion in anderer physischer Form
Einleitende Wendungen in **$i** können sein:
    _Äquivalent
    Elektronische Reproduktion von / Elektronische Reproduktion
    Reproduktion von / Reproduziert als_


Die beiden Datensätze können in beiden Fällen 
- jeweils über PPN verknüpft sein (Beispiele s.o.)
- oder literal mit Unterfeldern erfasst sein: https://ixtheo.de/Record/492453853

- Bei PPN-Verknüpfung muss man auf den entspr. verlinkten Datensatz gelangen.

- Bei literaler Erfassung müssen die erfassten bibliographischen Daten angezeigt werden.
Bsp. PPN 492453853:

775 08$iFaksimile von$aBlau, Felix Anton, 1754-1798$tUeber die moralische Bildung des Menschen$dFrankfurt am Main : Eichenberg, 1795$h288 Seiten

Faksimile von: Blau, Felix Anton, 1754-1798: Ueber die moralische Bildung des Menschen. - Frankfurt am Main : Eichenberg, 1795. - 288 Seiten
(weitere Unterfelder können sein: $g, $o, $u, $z 
diese ggf. bei der Anzeige ebenfalls mit ". - " trennen)

Es gibt auch viele Einträge, in denen nur die o.g. einleitenden Wendungen in $i stehen und nichts weiter folgt. Das ist m.E. nicht korrekt. Anfrage beim BSZ folgt.

**Comment by IxTheoKm** [comment]
Lt. BSZ ist die Eingabe von $i mit einleitenden Wendungen ohne Verknüpfung oder verbale Angabe eines Werks nicht korrekt! 
Wenn in 775 oder 776 nach $i keine weiteren Unterfelder folgen, sollte dieses Feld gar nicht angezeigt werden (wenn das möglich ist).

Leider kommt das häufig vor, vor allem auch bei unseren eigenen Bibliographietool-Aufnahmen.
Bsp.:
https://ixtheo.de/Record/489000193
https://ixtheo.de/Record/486793532
https://ixtheo.de/Record/488787491

**Comment by IxTheoKm** [comment]
Bei den drei letztgenannten PPNs handelt es sich z.T. um Erfassungsfehler im SWB!
Nicht in allen Fällen 
Bei PPN 488787491 wurde dreimal fälschlich keine Beziehung zu einem anderen Werk erfasst, 
einmal wurde eine Beziehung korrekt in einem anderen Feld erfasst, das im selben MARC-Feld ausgeliefert wird:

4243 Erscheint mit$lDrobner, Hubertus$tPredigten zu den Psalmen 1 (Sermones 13-21)
4256 Elektronische Reproduktion
4256 Elektronische Reproduktion
4256 Elektronische Reproduktion

MARC21:
776 08$iErscheint mit$aDrobner, Hubertus$tPredigten zu den Psalmen 1 (Sermones 13-21)
776 08$iElektronische Reproduktion
776 08$iElektronische Reproduktion
776 08$iElektronische Reproduktion

Im Erfassungsfeld 4243, das auch in 776 ausgeliefert wird, stehen nicht nur parallele Ausgaben:
Einleitende Wendungen können sein:
 -   Äquivalent
 -   Erscheint auch als (in Unterfeld $n kann die jeweilige "Ausgabeform" angegeben werden, z.B. Erscheint auch als$nCD-ROM-Ausgabe)
 -   Mirror-Site
 -   Begleitet von
 -   Erscheint mit
 -   Auf Disk mit
 -   Verfilmt mit

**Comment by jriedl** [comment]
Problematik der übergeordneten Werke jetzt auf ptah behoben.

**Comment by relhei** [comment]
Das Problem hat sich jetzt verschoben: Nun wir nicht mehr die falsche Zuordnung an ein übergeorndetes Werk vorgenommen. Allerdings fehlt auch gänzlich die Information, dass die vorliegende Publikation eine elektronische Reproduktion des Originaltitels ist und auch der Link zur Ressource ist weg.

https://134.2.67.9/Record/098634372

**Comment by jriedl** [comment]
Die Normalisierung und Darstellung paralleler Ausgaben ist ein eigener Punkt im Antrag.

**Comment by relhei** [comment]
#207

**Comment by jriedl** [comment]
Es es gibt jetzt in der Volltitelanzeige ein eigenes Feld "Parallele Ausgabe", das die andere Ausgabe verlinkt.

**Comment by IxTheoKm** [comment]
Die Verlinkung zur parallelen Ausgabe funktioniert jetzt.

Was noch fehlt, ist die Anzeige einer parallelen Ausgabe in der Volltitelanzeige, wenn sie nur verbal erfasst ist:
Beispiel:
https://ptah.ub.uni-tuebingen.de/Record/492453853#details

775 08$iFaksimile von$aBlau, Felix Anton, 1754-1798$tUeber die moralische Bildung des Menschen$dFrankfurt am Main : Eichenberg, 1795$h288 Seiten

(s. Kommentar vom 8. Juni)

**Comment by jriedl** [comment]
Ausschließlich verbale Erfassungen werden nun auf ptah in der Volltitelanzeige angezeigt.

**Comment by relhei** [comment]
Sieht gut aus. Danke!
