### ISSUE TITLE
VuFind 10: Facetteneinträge manchmal zu schmal

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#3021]
![grafik](https://github.com/user-attachments/assets/b0f0c8db-1ef5-4c59-8276-8c0e9571519b)

Tritt aber scheinbar nur in manchen Facetten auf. In anderen sieht es ganz normal aus:

![grafik](https://github.com/user-attachments/assets/2c9c341d-f04c-41f5-a26c-cc5d3d47ce4b)

(Hat es evtl etwas mit dem Rendering von AND gegenüber ODER Facetten zu tun?

**Comment by relhei** [comment]
Sieht jetzt gut aus in den Testsystemen von RelBib und IxTheo.
