### ISSUE TITLE
Anzeigefehler im Feld Nebentitel

### ISSUE THREAD

**Issue by coeh** [ubtue/tuefind#3039]
Im Feld "Nebentitel" (ausgelesen aus Feld 3260 im K10plus) wird aktuell das Trennzeichen $d zwischen Ober- und Untertitel mit angezeigt (anstatt wie sonst durch einen Doppelpunkt o.ä. ersetzt zu werden). Das ist sowohl auf dem Livesystem von IxTheo als auch auf ptah der Fall, in RelBib ebenso. Beispiel PPN 1688803661:

![grafik](https://github.com/user-attachments/assets/7f7c88c3-9490-4c1a-acd8-03740768c585)

**Comment by mtrojan-ub** [comment]
Ist auch in BOSS so:
https://k10plus.boss.bsz-bw.de/Record/(DE-627)1688803661#details

Man sieht dass die Daten in MARC 246 inkorrekt sind:
![grafik](https://github.com/user-attachments/assets/5cf32ba9-0858-46ea-bdc0-f6c079923cd7)

Das Problem liegt also nicht auf unserer IT-Seite. Sind die Daten im entsprechenden PICA-Feld tatsächlich korrekt? Falls ja, müsste das an den BSZ Support weitergeleitet werden um zu prüfen ob es am MARC-Export liegt.

**Comment by IxTheoKm** [comment]
@coeh Feld 3260 kann benutzt werden statt 4212, darf aber kein Unterfeld $d haben. 
Dito für das Feld 4221/MARC 546 (das wird aber offensichtlich bei uns nicht angezeigt. Sollte es?)
Ich habe den Datensatz korrigiert.

**Comment by coeh** [comment]
@IxTheoKm Vielen Dank! @mtrojan-ub Dann war das meine Fehleinschätzung und das Problem liegt nicht auf technischer Ebene. Danke und Entschuldigung! Ich schließe daher das Issue.
