### ISSUE TITLE
Tag-Browsing: allgemeine einfache Suche nicht möglich

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#305]
Wenn ich im Tag-Browsing-Modus bin und dann im Suchschlitz wieder eine einfache Suche starten möchte, erscheinen keine Ergebnisse. Erst wenn ich wieder auf die Homepage gehe, kann ich eine einfache Suche starten. Hier ein Beispiel:
Erst Tag-Browsing:
https://relbib.de/Tag/Home?lookfor=T%C3%A4tigkeit
Dann Eingabe eines neuen Suchbegriffs im Suchschlitz:
https://relbib.de/Search/Results?lookfor=religi%C3%B6se+identit%C3%A4t&type=tag&limit=20&sort=title

Bei IxTheo das Gleiche: Offensichtlich werden nur solche Titel gelistet, die entsprechende Tags enthalten.
Beispiel: einfache Suche im Tag-Browsing-Modus nach "Theologie" - 1 Treffer
https://www.ixtheo.de/Search/Results?lookfor=Theologie&type=tag&limit=20&sort=title

Ist das so gewollt? Der Suchschlitz suggeriert mir erst einmal, dass ich eine einfache Suche an jeder Stelle in IxTheo / RelBib neu starten kann...

**Comment by thefass** [comment]
"Der Suchschlitz suggeriert mir erst einmal, dass ich eine einfache Suche an jeder Stelle in IxTheo / RelBib neu starten kann..." 
Ja, so sollte es sein

**Comment by jriedl** [comment]
Das ist auch in Standard-VuFind so - so hat man eine Möglichkeit, direkt nach Tags zu suchen. Deshalb erscheint auch das Auswahlfeld für die zu durchsuchenden Felder nicht. Wir werden es aber wie gewünscht auf das reguläre Verhalten umstellen.

**Comment by jriedl** [comment]
Ist jetzt auf ptah angepasst.

**Comment by relhei** [comment]
Warum werden jetzt auf ptah nur noch 3 Tags (RelBib) angezeigt?

https://134.2.67.9/Browse/Tag?findby=recent&query_field=tag

**Comment by jriedl** [comment]
Weil es offenbar nicht mehr Relbib-relevante Tags auf ptah gibt. Die Tags werden ja pro System vergeben, d.h. was auf ub16 eingegeben wurde, kommt nicht automatiscch auf ptah. Problem ist eher, dass offenbar Tags dazu verwendet wurden um zu entfernende Titel zu kennzeichnen, die dann gelöscht wurden und damit jetzt nicht mehr aufgelöst werden können. https://ptah.ub.uni-tuebingen.de/Browse/Tag?findby=recent&query_field=tag. Da müssen wir uns noch eine Lösung überlegen.

**Comment by jriedl** [comment]
Auf ptah qurden Tags, die auf nicht mehr existente Titel verweisen jetzt entfernt.

**Comment by thefass** [comment]
Die Tags haben den Sinn, Inhaltlich zu erschließen.
Organisatorische Auszeichnungen sollten wir damit nicht machen. 
Das kann man auch über das eigene VuFind Konto organisieren.
Das Thema sollten wir in der nächsten IT Sitzung einmal ansprechen

**Comment by relhei** [comment]
Da das ursprüngliche Problem gelöst wurde, schließe ich diesen Issue. Vielen Dank!
Für die Diskussion, wie zukünftig mit der Tagging-Funktion umgegangen werden soll, wäre ein Meeting gut.
