### ISSUE TITLE
Versenden einer Auswahl von Suchergebnissen per E-Mail funktioniert nicht

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#3058]
Nach Auswahl einer Seite von Suchergebnissen und Klick auf "E-Mail" kann ich zwar das Formular zum Versand ausfüllen, aber es passiert nichts, wenn ich auf "Senden" klicke. 
![grafik](https://github.com/user-attachments/assets/e61a707e-5e3f-48a4-9742-f26a56614223)

**Comment by mtrojan-ub** [comment]
Seems to be a different problem than #3059 and #3060, maybe some AJAX-related problem. I will assign @LysogorAndGmail for further investigations.

**Comment by ja-bre** [comment]
Problem besteht auch in IxTheo

**Comment by coeh** [comment]
Works fine on ptah for IxTheo, thank you! (@NMagin can you also try it out on RelBib before closing the issue?)

**Comment by NMagin** [comment]
The problem is fixed for RelBib as well. Thank you!

Closing the issue.
