### ISSUE TITLE
RelBib: Fehlerseite bei Nutzung des Formulars "Titel vorschlagen"

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#3059]
Das Formular "Titel vorschlagen" lässt sich ausfüllen, aber nach Klick auf "Senden" kommt diese Fehlerseite:
![grafik](https://github.com/user-attachments/assets/1f9748bc-6b81-43a5-83cb-cd014f55f51d)

**Comment by mtrojan-ub** [comment]
Wie schon vermutet handelt es sich um die selbe Ursache wie bei #3060 
=> Müsste jetzt auf ptah behoben sein

**Comment by relhei** [comment]
Funktioniert jetzt. Danke!
