### ISSUE TITLE
RelBib: Absenden des Feedback-Formulars funktioniert nicht

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#3060]
Das Ausfüllen des Feedback-Formulars funktioniert, auch CAPTCHA-Prüfung (wurde mit Fehler getestet), aber nach Klick auf "Senden" kommt diese Fehlermeldung:
![grafik](https://github.com/user-attachments/assets/3b4fb914-89ad-4b91-98a8-f7213d3f499e)

**Comment by mtrojan-ub** [comment]
Ist auf ptah jetzt behoben.

Hatte was mit der Verarbeitung von Daten des aktiven Benutzers in Mailformularen zu tun. Mit etwas Glück löst dieser Bugfix auch die anderen Formular-bezogenen Probleme in den verwandten Issues, ich teste das aber pro Issue nochmal gezielt.

**Comment by relhei** [comment]
Das funktioniert jetzt auch wieder. Danke!
