### ISSUE TITLE
Personenseiten: "Neueste Titel" auf Englisch

### ISSUE THREAD

**Issue by ja-bre** [ubtue/tuefind#3063]
bei den Personenseiten werden die "Neuesten Titel von/über" auch bei deutscher Spracheinstellung auf Englisch angezeigt

![grafik](https://github.com/user-attachments/assets/fb3670df-fa48-4758-8e9e-1fa08a6bfba0)

**Comment by mtrojan-ub** [comment]
Ist behoben, siehe ptah

**Comment by ja-bre** [comment]
Dankeschön, ich schließe!
