### ISSUE TITLE
Kartenanzeige(?) in der Ergebnisliste

### ISSUE THREAD

**Issue by NMagin** [ubtue/tuefind#3075]
Bei einem Titel wird ein großes rotes Feld mit dem Inhalt "Karte" ausgegeben (siehe Screenshot). Die Anzeige erfolgt auch in anderen Suchen, zur besseren Auffindbarkeit habe ich diese Suche ausgewählt: https://relbib.de/Search/Results?lookfor=maps+of+the+bible+land&type=AllFields&limit=20&botprotect=

![Screenshot 2024-11-20 at 09-27-12 Suchergebnisse - maps of the bible land RelBib](https://github.com/user-attachments/assets/0baf0c1f-69c0-488c-9555-646fc308761a)

Dieses Kartenfeld kommt nur in der Ergebnisliste. Die Volltitelanzeige sieht normal aus: https://relbib.de/Record/010073264?sid=120191129
Weitere Beispiele finden sich bei einer allgemeine Suche nach "Maps": https://relbib.de/Search/Results?lookfor=maps&type=AllFields&limit=20&botprotect=

**Comment by NMagin** [comment]
Ergänzung: In der Volltitelanzeige wird das Feld auch bei der Versionsanzeige angezeigt.
https://134.2.67.9/Record/389221945?sid=30687#versions
![Screenshot 2024-11-20 at 09-32-40 Beschreibung Historischer Atlas der antiken Welt RelBib](https://github.com/user-attachments/assets/3c7a1fb2-e205-4d9a-81b7-2f07d5cb5347)

**Comment by NMagin** [comment]
Habe noch die Links ausgetauscht, das Problem lässt sich auch im Live-System reproduzieren.

**Comment by jriedl** [comment]
Erstanalyse: Das Problem tritt nur im Relbib-Kontext auf und bei Records, die das Format "Map/Karte" haben. Es handelt sich um ein fehlformatiertes Format-Tag (sollte eigentlich aussehen wie "Druck" darüber), was auf ein CSS-Problem hindeutet.

**Comment by LysogorAndGmail** [comment]
Ready for testing auf ptah

**Comment by NMagin** [comment]
The "map"-tag now looks normal again. Thank you!

Closing this issue as solved.
