### ISSUE TITLE
Verknüpfung mit GND-Personensätzen & Zugriff auf Kontoseite "Meine Publikationen"

### ISSUE THREAD

**Issue by NMagin** [ubtue/tuefind#3098]
Wenn ich im Testsystem mit einem Account, der eine GND beansprucht hat, eingeloggt bin und im Konto auf die Unterseite "Meine Publikationen" navigieren will, bekomme ich die untenstehende Fehlermeldung: 
![Screenshot 2024-12-03 at 14-55-11 Es ist ein Fehler aufgetreten RelBib](https://github.com/user-attachments/assets/e6c63ba1-c3c9-437e-a1e5-25d85631d32c)

Im Live-System scheint es nicht reproduzierbar, dort bekomme ich die (korrekte) Meldung, dass ich noch keine ID beansprucht habe. Wenn der Fehler nur bei beanspruchter ID auftritt, kann es auch im Live-System vorkommen, das sehe ich dann aber nicht.

**Comment by NMagin** [comment]
Ich erweitere das Problem: Der Zugriff auf jegliche GND-Personendatensätze scheint gerade weg zu sein. Die Personensuche liefert generell keine Ergebnisse mehr und auch in den anderen Suchlisten ist das Icon zur Personensuche verschwunden:
![Screenshot 2024-12-03 at 15-08-32 Suchergebnisse RelBib](https://github.com/user-attachments/assets/c581a289-1c04-4770-a25e-fad645293457)

**Comment by jriedl** [comment]
Problem mit der Anzeige der GND-Personensätze wurde behoben. Damit sollte die Auflösung auf PPN 1807852180 ebenfalls wieder funktionieren.

**Comment by coeh** [comment]
Für IxTheo funktioniert es auf dem Livesystem und auf ptah jetzt korrekt (sowohl Meine Publikationen für einen bereits beanspruchten Datensatz als auch Suche nach einer anderen Person als auch Personenicon). Ich habe es aber eben erst ausprobiert und weiß daher nicht, ob/wie umfassend das Problem dort zuvor auch bestand. @NMagin wie ist es auf RelBib?

**Comment by NMagin** [comment]
Auf Relbib funktioniert auch alles wieder. Personenicons sind da, die Personensuche funktioniert und der Zugriff auf "Meine Publikationen" ist möglich. Danke für die schnelle Bearbeitung!

@coeh Ich gehe mal davon aus, dass es im Live-System kein Problem war/ist. Die Problematik schien ja an der Anzeige der GND-Sätze zu hängen und das hat dort durchgehend funktioniert.

Dann mache ich hier mal zu. :-)
