### ISSUE TITLE
Mobile Version: keine Sprachauswahl möglich

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#315]
Unterwegs ist aufgefallen, dass bei der mobilen Website-Version (Format Smartphone) keine Sprachauswahl möglich ist: Sie müsste im Menü oben rechts entsprechend noch ergänzt werden.

**Comment by mtrojan-ub** [comment]
Man kann über das Hamburger-Icon rechts oben zwar das Menü ausklappen, aber man sieht nicht alle Menüpunkte (weiße Schrift auf weißem Hintergrund). 

Siehe Screenshot: Hier sieht man "Login" gar nicht, "Language" wird in diesem Beispiel nur wegen Mouseover angezeigt.

Ich schaue mal ob ich da was machen kann.

![grafik](https://user-images.githubusercontent.com/26873381/43575607-8a7d7858-9647-11e8-85ed-3e33443a6c4a.png)

**Comment by mtrojan-ub** [comment]
Hab auf ptah die Höhe des Hintergrunds geändert damit das gesamte Menü reinpasst. Ist nicht optimal, aber man kann alle Menüpunkte benutzen, und das komplett neue Layout ist ja auch schon in Arbeit.

![grafik](https://user-images.githubusercontent.com/26873381/43576781-7690ef98-964a-11e8-8a1d-e9cc7b2e2390.png)

**Comment by relhei** [comment]
Passt! Danke.
