### ISSUE TITLE
IxTheo-Klassifikation: immer noch veraltete Begriffe

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#316]
Die IxTheo-Klassen werden zumindest im Deutschen immer noch mit den z. T. veralteten Begriffen angezeigt, z. B. KBN "Schwarzafrika". Was wird benötigt, damit diese baldmöglichst korrekt erscheinen? In der WinIBW wurde bereits alles aktualisiert.
![grafik](https://user-images.githubusercontent.com/25769591/41709365-4bef31b4-7543-11e8-9a07-d5365efa7dde.png)

**Comment by jriedl** [comment]
Die Umschreibungen sind bei uns in den Sprachdateien fest codiert. (vgl. https://github.com/ubtue/tuefind/blob/master/local/tuefind/languages/de.ini). Diese Datei müsste also angepasst werden bzw. uns eine Liste relevanter Änderungen zur Verfügung gestellt werden. Allerdings wurden die Bezeichnungen ja bereits in diverse Sprachen übersetzt. Falls das dann zu Inkonsistenzen führt, müsste das gesondert beachtet werden.

**Comment by relhei** [comment]
Änderungen wurden umgesetzt. Danke!
