### ISSUE TITLE
Lebensdaten von Personenschlagwörtern fließen in die Zeitfacette ein

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#318]
Beispiel:
https://ixtheo.de/Search/Results?lookfor=Response+to+the+Grant+Wacker+review+of+%22From+bible+belt+to+sunbelt%22&type=AllFields&limit=20&sort=year+desc%2C+issue_sort+desc%2C+start_page+asc

![600_zeitfacette_psw](https://user-images.githubusercontent.com/17004223/41961344-834d5bc8-79f2-11e8-8e77-b0ccd3d8f67a.jpg)

Wenn Einzel-Personenschlagwörter in MARC-Feld 600 transportiert werden, fließt das Geburtsjahr in $d offensichtlich in die Zeit-Facette ein:
600 17$0(DE-588)15186554X$0(DE-576)168396181$2gnd$aWacker, Grant$d1945-

Weiteres Beispiel (erster Treffer):
https://ixtheo.de/Search/Results?lookfor=response+to+Parrish+on+the+fine-tuning+argument&type=AllFields&limit=20&sort=year+desc%2C+issue_sort+desc%2C+start_page+asc

Bei Personenschlagwörtern aus Schlagwortfolgen in Feld MARC-Feld 689 passiert das nicht.
Bsp.:
https://ixtheo.de/Search/Results?lookfor=Benedikt+XVI.+Joseph+Ratzinger+zum+neunzigsten+Geburtstag+%3A+Stimmen&type=AllFields&limit=20&sort=year+desc%2C+issue_sort+desc%2C+start_page+asc

**Comment by IxTheoKm** [comment]
Ergänzung:
Bitte die Anzeige der Lebensdaten von 600 aus der Zeitfacette herausnehmen!

**Comment by jriedl** [comment]
600d wurde aus der Zeitfacette entfernt. Sollte nach dem nächsten Import sichtbar sein.

**Comment by IxTheoKm** [comment]
Ist jetzt in Ordnung, danke!
