### ISSUE TITLE
Suche nach Abrufzeichen ermöglichen

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#319]
Im IxTheo kann man mit rs: nach einem Abrufzeichen (Pica 8002 / Marc 935 $a) suchen.
Beispiel rs:ixbt
https://ixtheo.de/Search/Results?lookfor=rs%3Aixbt&type=AllFields&limit=20&sort=year+desc%2C+issue_sort+desc%2C+start_page+asc

bitte ermöglichen, dass das auch in der KrimDok funktioniert.
Beispiel: Suche nach mkri

**Comment by mtrojan-ub** [comment]
Ist jetzt auf sobek möglich. Allerdings sollte nicht nach "mkri" sondern nach "krim" gesucht werden, da der Inhalt direkt aus LOK 935a übernommen wird.

Beispiel: rs:krim
https://sobek.ub.uni-tuebingen.de/Search/Results?lookfor=rs%3Akrim&type=AllFields&limit=20&sort=year+desc%2C+issue_sort+desc%2C+start_page+asc

siehe auch ubtue/ixTheo#461

**Comment by mtrojan-ub** [comment]
Nach Absprache mit @ruschein habe ich jetzt auch noch 935a (nicht-LOK) aufgenommen. Daher kann man jetzt auch nach "mkri" Suchen. Allerdings ist die Trefferanzahl für "krim" und "mkri" nicht die gleiche.

Positiver Nebeneffekt: Damit ist auch auf ptah nicht nur die Suche nach "ixbt" sondern auch nach "mteo" möglich (ab dem nächsten Import, also morgen).

**Comment by IxTheoKm** [comment]
Vielen Dank! Für IxTheo bzw. ptah funktioniert es. 
Das wird auch für Bearbeitung eine Erleichterung bringen, da die Datenselektion von Kooperationspartnern möglich ist, die eigene Abrufzeichen im Titelfeld haben werden!

Für die Hilfetexte muss berücksichtigt werden, dass Groß- und Kleinschreibung relevant ist.
