### ISSUE TITLE
Titel trotz passender DDC in 082 nicht in RelBib angezeigt

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#320]
Unter Berücksichtigung der im Wiki hinterlegten Abzugskriterien müsste dieser Titel eigentlich in RelBib angezeigt werden (DDC-Nummer):

![grafik](https://user-images.githubusercontent.com/25769591/42032627-77f3166c-7ada-11e8-913e-82498cca3009.png)

Dies ist aber nicht der Fall. Ich habe bewusst noch nicht SSG-Nr. 0 in 084 |a eingetragen.

**Comment by IxTheoKm** [comment]
Ich weiß nicht, wo im Wiki die Abzugskriterien stecken, aber meines Wissens liefert das BSZ nur Titel mit 5056 0 bzw. 1 und 0575 mteo (084 $a0$a1$2ssgn und 935 $amteo). 
Wird nicht aus _diesen_ ausgelieferten Daten die DDC-Nummer für RelBib berücksichtigt, falls in 084 nicht "0" steht?

**Comment by relhei** [comment]
Ok, das macht Sinn. Auf mteo hatte ich nicht geachtet.
