### ISSUE TITLE
Verweisungsformen geographischer Normdaten sind nicht recherchierbar

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#321]
Beispiel 1:
Albanien > 164 Treffer
https://ixtheo.de/Search/Results?lookfor=Albanien&type=Subject&limit=20&sort=year+desc%2C+issue_sort+desc%2C+start_page+asc
Verweisungsform: Arnavutluk > kein Treffer
https://ixtheo.de/Search/Results?lookfor=Arnavutluk&type=Subject&limit=20&sort=year+desc%2C+issue_sort+desc%2C+start_page+asc

Beispiel 2:
Kasachstan > 58 Treffer
https://ixtheo.de/Search/Results?lookfor=Kasachstan&type=Subject&limit=20&sort=year+desc%2C+issue_sort+desc%2C+start_page+asc

Verweisungsform: Qazaqstan > kein Treffer
https://ixtheo.de/Search/Results?lookfor=Qazaqstan&type=Subject&limit=20&sort=year+desc%2C+issue_sort+desc%2C+start_page+asc

Siehe auch das offene Issue: Verweisungsformen der Normdaten sind nicht recherchierbar #126

**Comment by jriedl** [comment]
Wie besprochen: Problem trat nur auf, wenn das gleiche Schlagwort unterschiedliche Synonyme unter verschiedenen Normdaten-PPNs hat.  Hier werden jetzt alle Synonyme zusammengefasst. Im Bezug auf ubtue/ixtheo#126 lassen sich nach aktuellem Stand offenbar keine Regeln angeben, mit denen alle Fälle konsistent behandelt werden können. Anmerkung: Deutsche Synonyme finden sich in der Internansicht nach dem nächsten Import nicht mehr in 18X, sondern in 94X.

**Comment by thefass** [comment]
funktioniert
