### ISSUE TITLE
RelBib-Klassifikation: Anzeige unzugewiesene Treffer >100%

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#322]
Bei dieser Suche

https://relbib.de/Search/Results?sort=year+desc%2C+issue+desc%2C+start_page+asc%2C+first_indexed+desc&join=AND&lookfor0%5B%5D=indien&type0%5B%5D=AllFields&lookfor0%5B%5D=usa&type0%5B%5D=AllFields&lookfor0%5B%5D=&type0%5B%5D=AllFields&bool0%5B%5D=OR&lookfor1%5B%5D=Geschlechterrolle&type1%5B%5D=AllFields&bool1%5B%5D=AND&filter%5B%5D=%7Erelbib_notation_facet%3A%22AD%22&filter%5B%5D=%7Erelbib_notation_facet%3A%22BK%22&limit=20&daterange%5B%5D=publishDate&publishDatefrom=&publishDateto=

werden in der Facette "RelBib-Klassifikation" 215,4% unzugewiesene Treffer angezeigt. 

![grafik](https://user-images.githubusercontent.com/25769591/42160558-fd069af2-7df7-11e8-994b-a7fb0083c98b.png)

Das ergibt sich vmtl. aus der Tatsache, dass RelBib-Notationen mehrfach je Titel vergeben werden können, sollte aber so nicht stehen bleiben, oder?

**Comment by jriedl** [comment]
Das Problem hängt mit der internen Funktionsweise der ODER-Facetten zusammen: Technisch wird Relbib über eine sog. "Filter-Query" umgesetzt, d.h. die Ergebnismenge wird mit dem Menge der Relbib-Titel geschnitten. UND-Facetten funktionieren genauso d.h. es wird mit der gewählten Facette geschnitten. Eine ODER-Facette erweitert allerdings die Ergebnismenge, deshalb müssen hier für die Bestimmung der Anzahlen die Filter-Queries wieder "ausgeschaltet" werden. 

Das passiert jetzt allerdings für alle Filter-Queries, also auch die eigentlich notwendige Relbib-Einschränkung und so kommt es zum "Verzählen". Da es für die Relbib-Notationen ein eigenes Feld gibt, lässt sich in diesem Fall das Problem durch Kriterien beim Import umgehen. Sollte nach dem nächsten Import auf ptah sichtbar sein.

**Comment by jriedl** [comment]
Die Anpassungen für Relbib haben das Verhalten nur "so gut gemacht" wie auf IxTheo. Hier gab es allerdings auch Fälle, bei denen der Fehler auftrat. Um ihn zu vermeiden, wird jetzt bei den ODER-Facetten die Anzeige der Prozentzahl durch die absoluten Werte ersetzt, sobald eine Facette dieser Facetten angewählt ist.

**Comment by jriedl** [comment]
Auf ptah integriert.

**Comment by relhei** [comment]
Danke! Passt.
