### ISSUE TITLE
Zu große Trefferzahl bei erweiterter Suche

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#333]
Bei der erweiterten Suche mit konkretem Buchtitel und Einschränkung auf das Feld "Titel" kommen m. E. zu viele Treffer:

![grafik](https://user-images.githubusercontent.com/25769591/43076574-ea81d7f0-8e84-11e8-85e1-92d09f71459f.png)

**Comment by jriedl** [comment]
Die Standardverknüpfung innerhalb der einzelner Felder in der erweiterten Suche ist "ODER". Deshalb wird hier alles gefunden, was "Religion" oder "Geschlechterordnungen" beinhaltet. die Eingabe von "Religion AND Geschlechterordnungen" (ohne Anführungszeichen) liefert die gewünschte Ergebnismenge, alternativ "Religion" und "Geschlechterordnungen" in unterschiedlichen Feldern. Oder "Religion und Geschlechterordnungen" (mit Anführungszeichen), dann ist es allerdings eine Phrasensuche, bei der genau diese Anordnung von Termen vorkommen muss.

**Comment by relhei** [comment]
Danke! Evt. müssten wir die Hilfetexte daraufhin noch einmal überprüfen. Unter "Hilfe zu den Suchoperatoren" steht es nämlich anders:
![grafik](https://user-images.githubusercontent.com/25769591/45029194-29c96b00-b048-11e8-8edd-e23e3ced678b.png)

**Comment by jriedl** [comment]
Auf ptah behoben.

**Comment by relhei** [comment]
Passt. Vielen Dank!
