### ISSUE TITLE
Datenlieferung SSOAR

### ISSUE THREAD

**Issue by kdr154** [ubtue/tuefind#334]
https://www.gesis.org/ssoar/home/

**Daten für Kriminologie - einmalige Datenlieferung**

**Comment by kdr154** [comment]
### 1. Datenbasis
Suche mit „<leader>“ ergibt 600 Treffer,
die im April gesendete Datei mit Link zu den Originaldaten hatte 4 Treffer mehr, also 604.
Beim Aufrufen des Links https://www.ssoar.info/OAIHandler/request?verb=ListRecords&metadataPrefix=oai_dc&set=col_collection_10207 kommen 611 Treffer.
Zum Vergleich mit den Originaldaten brauchen wir einen aktuellen Link.

**Comment by kdr154** [comment]
### 2. RDA
Sollen die Titel als RDA-Titel ausgeliefert werden?	
Dann 040 $e rda (siehe auch Feld 773!)
Verlagsdaten, Kölner und ImageWare-Daten wurden nicht als RDA-Daten eingespielt!

**Comment by kdr154** [comment]
### 3. Leader
nam	439 Treffer	[Monographie] ***
		naa	142 Treffer	[Unselbständiges Werk]
		nac	  19 Treffer	[Sammelwerk]
			600 Treffer

Es sind zuviele Monographien, da:

		*** Treffer im MARC 21 Feld 500 mit $a In: … müssen „naa“ im Leader bekommen!

**Comment by kdr154** [comment]
### 4. MARC 21 Feld 264 $c
Ist immer doppelt angegeben.
Warum?

**Comment by kdr154** [comment]
### 5. MARC 21 Feld 041

Anmerkung Riedl: „Einfügen des 041$h (Sprachcode) aus 008. Falls 041$a vorhanden, Umbennenung in $h“.
		
Warum $h? 041 $a ist korrekt und auch immer so in den Daten vorhanden.

**Comment by kdr154** [comment]
### MARC 21 Feld 773 $i
In Nicht-RDA-Aufnahmen steht die einleitende Wendung „In:  ʺ
In RDA-Aufnahmen steht die einleitende Wendung „Enthalten in:  ʺ

**Comment by kdr154** [comment]
### 8. MARC 21 Feld 936
Fehlt in den Daten! Sollte aus „500 $a In: …“ bzw. 773 $g erzeugt werden:

Beispiel für die Umsetzung des obigen Titels:
\<datafield tag="936" ind1="u" ind2="w"\>
\<subfield code="d">62</subfield\>
\<subfield code="j">2016</subfield\>
\<subfield code="e">2</subfield\>
\<subfield code="h">183-222</subfield\>

**Comment by IxTheoKm** [comment]
### 9. MARC 21 Feld 246 

Ein vorliegender **Paralleltitel** in einer anderen Sprache steht normalerweise in **245 $b**

Er steht aber als **abweichender Titel** in **Feld 246 $a**. Wird er so geliefert?
Das heißt, eine Unterscheidung von anderen abweichenden Titeln zu anderssprachigen Paralleltiteln ist nicht möglich?

Bsp.: col_collection_102070000000004
https://www.ssoar.info/ssoar/handle/document/18840

- [ ] Antwort:

**Comment by kdr154** [comment]
### 10. MARC 21 Feld 540

Bis jetzt ist das Feld noch nicht definiert. 
In den SSOAR-Daten und Seiten stehen hier Vermerke zur Lizenz 
Etwa: https://www.ssoar.info/ssoar/handle/document/18839
Die MARC 21 Dokumentation sieht hierzu das Feld 856 $z vor
- [ ] Antwort:

**Comment by IxTheoKm** [comment]
### 11. MARC 21 Feld 024 $a

In den SWB-Daten steht der **DOI** in Feld 024 $a immer ohne Präfix:

Bsp.:
10.12759/hsr.22.1997.3/4.32-63
NICHT: https://doi.org/10.12759/hsr.22.1997.3/4.32-63

\<datafield tag="024" ind1="7" ind2=" "\>
\<subfield code="a"\>10.12759/hsr.22.1997.3/4.32-63\</subfield\>
\<subfield code="2"\>doi\</subfield\>

Die Resolving URL mit dem Präfix "https://doi.org/" sollte _zusätzlich_ in MARC-Feld 856 $u abgelegt werden. $u erfordert aber am Ende der Zeile einen Code in $x, der die Herkunft der URL angibt (Verlag, Resolving System u.ä.) 
Wenn die Herkunft aus den Daten nicht hervorgeht, sollte vermutlich nur 024 ohne 856 $u angegeben werden.

- [ ] Antwort:

**Comment by IxTheoKm** [comment]
### 12. MARC 21 Feld 856 $z

In den SWB-Daten steht statt "Open access" im Unterfeld $z "Kostenfrei". Der Datensatztyp wird damit als lizenzfreie Ressource gekennzeichnet.

Mit dem BSZ klären, ob "Open access" so geliefert werden soll?

- [ ] Antwort:

**Comment by IxTheoKm** [comment]
### 13. MARC 21 Feld 024 $a

Alle Einträge mit dem Präfix "**oai:gesis.izsoz.de:document/...**" bezeichnen nur die Herkunft der Metadaten.
Sie dürfen m.E. nicht in den Titeldaten abgelegt werden.

Die Identifier in Feld 001 sollen im lokalen PICA-Feld 7811 abgelegt werden. 
Sollen diese Einträge ebenfalls als Identifier lokal abgelegt werden?

- [ ] Antwort:

**Comment by kdr154** [comment]
### 14. MARC 21 Feld 093

bisher weder von DNB noch vom BSZ als MARC 21 Feld definiert.
Es steht in allen Datensätzen in der Form:
\<datafield tag="093" ind1=" " ind2=" "\>
\<subfield code="b">b</subfield\>
\</datafield\>

Worauf ist der Inhalt zurückzuführen, was bedeutet er?
Überflüssig?

- [ ] Antwort:

**Comment by kdr154** [comment]
### 15. MARC 21 Feld 540
Es steht in allen Datensätzen in der und enthält Lizenzinformationen, etwa:
\<datafield tag="540" ind1=" " ind2=" "\>
\<subfield code="a">Creative Commons - Namensnennung</subfield\>
\<subfield code="u">http://creativecommons.org/licenses/by/4.0/</subfield\>

es ist aber bisher weder von DNB noch vom BSZ als MARC 21 Feld definiert.

- [ ] Antwort:

**Comment by kdr154** [comment]
### 16. MARC 21 Feld 653

hier stehen freie Schlagwörter mit z. T. überflüssigen Bindestrichen.
Bsp.:
\<datafield tag="653" ind1=" " ind2=" "\>
\<subfield code="a">inter-­pretative Reper­-toires</subfield\>
\</datafield\>
\<datafield tag="653" ind1=" " ind2=" "\>
\<subfield code="a">Dis­-kurs­-psychologie</subfield\>
\</datafield\>
\<datafield tag="653" ind1=" " ind2=" "\>
\<subfield code="a">Diversity</subfield\>
\</datafield\>
\<datafield tag="653" ind1=" " ind2=" "\>
\<subfield code="a">Groß­-unternehmen</subfield\>
\</datafield\>

- [ ] Antwort:

**Comment by kdr154** [comment]
### 17. MARC 21 Feld 852
Es ist in allen Datensätzen enthalten und enthält die ISIL der UB Tübingen:
\<datafield tag="852" ind1=" " ind2=" "\>
\<subfield code="a">DE-21</subfield\>
\</datafield\>

es ist aber bisher weder von DNB noch vom BSZ als MARC 21 Feld definiert.

- [ ] Antwort:

**Comment by kdr154** [comment]
### 18. MARC 21 Feld 773 subfield code="7"

Es kommt insgesamt 23 mal vor und zwar immer dann , wenn "Historical Social Research" das übergeordnete Sammelwerk ist.
Der Inhalt ist immer "nnas",
wobei das "s" an der 4. Stelle darauf verweist, dass das übergeordnete Werk ein Sammelwerk ist.

1. Die 1., 2., und 3. Stelle ist in der MARC 21 Dokumentation bisher jedoch nur als Füllzeichen definiert.
Woher also die ersten drei Buchstaben "nna"?

2. wieso gibt es das subfield code="7" nur dann, wenn "Historical Social Research" das übergeordnete Sammelwerk ist?

- [ ] Antwort:

**Comment by kdr154** [comment]
### 19. ISSN
Manche Dokumente enthalten auf ihren SSOAR-Seiten eine ISSN:
https://www.ssoar.info/ssoar/handle/document/9880
Sie wird jedoch nicht abgegriffen. Ist dies nicht möglich?

- [ ] Antwort:

**Comment by ruschein** [comment]
Zu 18: Das ist ein Artikel.  Ich dachte, dass im BSZ ISSNs nur in den übergeordneten Werken stehen.  Oder übersehen ich da etwas?

**Comment by kdr154** [comment]
Ist die ISSN der übergeordneten Einheit. In diesem Fall das Forum Qualitative Sozialforschung. Die ISSN müsste, wenn ich das der Dokumentation richtig entnehme, in dem bisher in der  SSOAR-Daten nicht vorkommenden Feld 022 abgelegt werden.

 

Mit freundlichen Grüßen

Klaus-Dieter Rosenkranz

 

_________________________

 

Klaus-Dieter Rosenkranz

Eberhard Karls Universität Tübingen

Telefon: Universitätsbibliothek +49 7071 29 72963

Mobil: 0173 3194973

 

E-Mail: rosenkranz@uni-tuebingen.de

 

 

Von: Dr. Johannes Ruscheinski <notifications@github.com> 
Gesendet: Dienstag, 31. Juli 2018 08:30
An: ubtue/tuefind <tuefind@noreply.github.com>
Cc: kdr154 <rosenkranz@uni-tuebingen.de>; Author <author@noreply.github.com>
Betreff: Re: [ubtue/tuefind] Datenlieferung SSOAR (#334)

 

Zu 18: Das ist ein Artikel. Ich dachte, dass im BSZ ISSNs nur in den übergeordneten Werken stehen. Oder übersehen ich da etwas?

**Comment by kdr154** [comment]
Wurde in einzelne Issues aufgelöst und nach ubtue/DatenProbleme verschoben
