### ISSUE TITLE
Ungewollte Titel in RelBib

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#347]
Folgende Titel werden in RelBib angezeigt, obwohl sie weder in 084 |a die SSG-Nr. 0 aufweisen noch DDC-Nummern in 082 aufweisen. Allerdings stehen in 082 andere Werte drin: Haben die evt. zur Auswahl für RelBib geführt? Das sollte nicht so sein.
Beispiele:
https://relbib.de/Record/507709756#details
https://relbib.de/Record/501386378#details

**Comment by jriedl** [comment]
PPN 501386378 scheint eine 338.XXX DDC zu enthalten. Damit entspricht sie nicht den zu unterdrückenden DDCs (vgl. https://github.com/ubtue/tuefind/wiki/Daten-Abzugskriterien) und wird deshalb aufgenommen. Für die PPN 507709756 wurde für das  DDC-Kriterium "Nicht 400 oder 800" noch ein Plausbilitätscheck eingefügt, um offensichtliche "Nicht"-DDCs nicht versehentlich aufzunehmen. Voraussichtlich ab morgen auf ptah.

@mtrojan: Nein, die Logik wird noch einmal invertiert (vgl 103). 082 ohne DDC Kriterien ist genau kein RelBib-Datensatz (außer Nicht-DDC-Kriterien führen zur Aufnahme)

**Comment by relhei** [comment]
Passt. Vielen Dank!
