### ISSUE TITLE
Focus "Forschungsdaten" in Facette "Medienart"

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#353]
Bitte nach Möglichkeit einen Focus "Forschungsdaten" (aus Feld 655 |a) in der Facette "Medienart" neu einfügen. 

https://relbib.de/Record/406435790#details
In diesem Bsp. wird der Titel noch als "Buch" in Medienart aufgeführt - warum?

**Comment by jriedl** [comment]
Für o.g. Beispiel-PPN auf ptah integriert, für alle weitern nach Abschluss des nächsten Imports.

**Comment by Gazeller** [comment]
Zur Kenntnis: Suche in SWB Forschungsdaten als Form-SW ("swf") ergibt 178 Treffer; überwiegend NatWiss. und überweigend von UB HD. - In RelBib 9 Titel, davon 8 mit _SW_ Forschungsdaten, 1 Titel, wo in Kommentarfeld (Feld 500) das _Wort_ Forschungsdaten vorkommt: ppn 481646426

**Comment by jriedl** [comment]
Auswahl der Facette Forshungsdaten auf ptah ergibt 9 Treffer auf dem Gesamtbestand. Die Facette wird aus 655a generiert. Weitere Kriterien müsste man zusätzlich definieren.

**Comment by relhei** [comment]
Das passt erst mal so. Danke!
