### ISSUE TITLE
Autocomplete funktioniert nicht richtig

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#354]
Momentan wird autocomplete nicht richtig ausgeführt, wenn man auf das Feld "Verfasser" oder "Schlagwort" einschränkt.
Bsp.:

![grafik](https://user-images.githubusercontent.com/25769591/43642948-c0b9e5f4-9729-11e8-883e-4eacfbf8b7e4.png)

![grafik](https://user-images.githubusercontent.com/25769591/43642984-e133a98c-9729-11e8-9017-418fc6e4fe90.png)

In den Beispielen werden nur Titel angezeigt, keine Verfassernamen oder Schlagwörter.

**Comment by jriedl** [comment]
Ist derzeit auf ub16 und ptah nicht reproduzierbar.

**Comment by relhei** [comment]
Funktioniert wieder. Danke!

**Comment by relhei** [comment]
Funktioniert wieder nicht.

**Comment by jriedl** [comment]
Fehler momentan weder auf relbib noch ptah nachvollziehbar

**Comment by relhei** [comment]
Das Problem tritt offensichtlich nur bei mir auf. Daher schließe ich hier.
