### ISSUE TITLE
In prison and far from home: spatial distance effects on inmate misconduct (ppn 507521188)

### ISSUE THREAD

**Issue by jjspp01** [ubtue/tuefind#356]
Warum wird bei den Schlagwörtern der Begriff "Text" angeführt, habe ich nicht im SWB eingegeben.

**Comment by IxTheoKm** [comment]
Dieses "Formschlagwort" ist in 1131 (Marc 655) verknüpft. Es ist aber auch schon in 1140 und 0501 vorhanden, daher in 1131 m.E. nicht erforderlich. Es ist jedenfalls in RDA-Arbeishilfe AH-007 nicht aufgeführt.

**Comment by IxTheoKm** [comment]
Der fehlerhafte Titel wurde im SWB am 20.8. korrigiert, d.h. 1131 Text wurde gelöscht. Korrektur ist noch nicht in KrimDok angekommen.

**Comment by mtrojan-ub** [comment]
...dann hätte das ja am 24.08. importiert werden müssen. Ist das schon erfolgt? Falls nicht, können Sie uns bitte eine Beispiel-PPN nennen?

**Comment by ruschein** [comment]
@jjspp01 Ist das Problem jetzt behoben?  Falls ja, Issue bitte schließen.
