### ISSUE TITLE
Löschung der Tn-Autorensätze in den Titeldaten nicht nachvollzogen

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#357]
Namenssätze ohne Synonyme wurden in der SWB-Datenbank gelöscht (Abschluss der Aktion am 2.8.2018). In den Titelsätzen steht der Autorenname nun nur noch in verbaler Form:

Beispieltitelsatz:
https://ixtheo.de/Record/506537110#details
100 1 $aHumm, Michel$eVerfasserIn$0(DE-576)252453352$4aut

Müsste jetzt lauten: 
100 1 $aHumm, Michel$eVerfasserIn$4aut

In den IxTheo-Daten sind die PPN-Verknüpfungen noch vorhanden, da diese Aktion nicht in die Datendienste aufgenommen wurde. Siehe Info vom BSZ-Wiki:

"Rückbau der SWB-Tn-Sätze
In den vergangenen Wochen haben wir die bestehenden Tn-Sätze in der SWB-Datenbank zurückgebaut.
D.h. wir haben bei Tn-Sätzen, die nur ein Feld 100 (oder ein Feld 100 und Originalschrift in Feld 700) aber keine weiteren Namensformen (Felder 400) enthielten, den Namen als Klartext in die anhängenden Titelsätze übertragen und die Verknüpfung zum Tn-Satz gelöscht. In einem weiteren Schritt wurden die Tn-Sätze ohne Titel gelöscht.
**Die Korrekturen wurden nicht in die Datendienste gegeben. Für die gelöschten Namenssätze haben wir entsprechend den Wünschen der AG SWB vom Oktober 2017, PPN-Listen zur Verfügung gestellt. Die PPNs wurden ebenfalls in die wöchentlichen Löschlisten geschrieben** (s.a. Protokoll der 11. Sitzung der AG SWB am 26.10.2017). Damit wurden diese etwas umfangreicher."

Die PPN-Listen der gelöschten Namenssätze müssten ausgewertet werden, um die Titelsätze entspr. zu aktualisieren. Sonst werden diese Änderungen nur bei einem neuen Gesamtabzug wirksam.

**Comment by mtrojan-ub** [comment]
Da unser letzter Gesamtabzug noch recht jung ist (16.07.2018) wollen wir nicht schon wieder einen neuen anfordern. Wir arbeiten daher an einem Programm um die Titelsätze bei uns zu aktualisieren.

**Comment by mtrojan-ub** [comment]
Beispiel für KrimDok:

PPN: 006994180
ist: 100 1 $aGardiner, Muriel$0(DE-576)161061281
soll: 100 1 $aGardiner, Muriel

**Comment by mtrojan-ub** [comment]
sobek wurde aktualisiert
https://sobek.ub.uni-tuebingen.de/Record/007465890#details

**Comment by mtrojan-ub** [comment]
ptah wurde aktualisiert
https://ptah.ub.uni-tuebingen.de/Record/506537110#details

**Comment by IxTheoKm** [comment]
Scheint nicht ganz funktioniert zu haben, wenn nach dem Namen Beziehungskennzeichen stehen. Im Internformat steht 100 und 109:
https://ixtheo.de/Record/501102698#details
https://ptah.ub.uni-tuebingen.de/Record/501102698#details

So soll es aussehen:
100 1 $aKull, Anne$eVerfasserIn$4aut

Korrektes Beispiel:
https://ixtheo.de/Record/501228470#details

**Comment by IxTheoKm** [comment]
Sorry, schlechtes Beispiel! "Kull, Anne" ist ein IxTheo-Fall, für den ein Tn-Satz tatsächlich noch existiert! 
Scheint also korrekt zu funktionieren.

**Comment by mtrojan-ub** [comment]
Nur teilweise: Wir haben die Bereinigung nur auf die 100er Felder angewendet, allerdings können die Referenzen auch in anderen Feldern vorkommen. Ich werde das nochmals bereinigen, diesmal für folgende Felder:

100
110
111
700
710
711

Falls Ihnen noch weitere Felder bekannt sind, bitte ich um kurze Rückmeldung.

**Comment by IxTheoKm** [comment]
Bei den Feldern 110, 111, 710 und 711 darf das eigentlich nicht vorkommen!
Das sind Körperschaften und Kongresse. Nur Personennamen sind vom Rückbau der Tn-Sätze betroffen.

**Comment by mtrojan-ub** [comment]
sobek ist aktualisiert, ptah wird heute Nacht aktualisiert und sollte somit morgen früh auf dem korrekten Stand sein.

**Comment by IxTheoKm** [comment]
Auf PTAH jetzt o.k.

Aber gibt es eine Erklärung dafür, warum im IxTheo die Reihenfolge der Unterfelder teilweise unterschiedlich angezeigt wurde/wird:

https://ixtheo.de/Record/463686209#details

![tn-saetze](https://user-images.githubusercontent.com/17004223/44196591-a39ec080-a13c-11e8-9fd9-d59e4b9b848e.png)

**Comment by mtrojan-ub** [comment]
Im MARC Standard gibt es keinen Hinweis darauf dass die Reihenfolge eine Rolle spielt. 
Wir führen aber auch keine explizite Sortierung o.Ä. durch.

**Comment by IxTheoKm** [comment]
Danke! Für IxTheo damit erledigt.

**Comment by mtrojan-ub** [comment]
@KStelzel : könnt ihr bitte prüfen ob das auch für KrimDok erledigt ist?

**Comment by IxTheoKm** [comment]
In KrimDok Stichproben getestet: dort auch okay.
