### ISSUE TITLE
Keine Aktualisierung der IxTheo-Datenbank?

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#358]
Seit letzter Woche sind die Daten nicht mehr aktualisiert. Gibt es ein Problem?

**Comment by ruschein** [comment]
Ja, es gibt ein Problem und wir arbeiten gerade daran.  Leider waren Mario und Johannes Riedel letzte im Urlaub.  Mario ist wieder da und wir sind guter Hoffnung das Problem bis morgen behoben zu haben.


Viele Grüße,

Johannes Ruscheinski

--
Dr. Johannes Ruscheinski
Universitätsbibliothek Tübingen - IT-Abteilung -
Wilhelmstr. 32, 72074 Tübingen

Tel: +49 7071 29-72820
FAX: +49 7071 29-5069
Email: johannes.ruscheinski@uni-tuebingen.de

 The Sophisticate:  "The world isn't black and white.  No one does pure good or pure bad. It's all gray.  Therefore, no one is better than anyone else."
    The Zetet:  "Knowing only gray, you conclude that all grays are the same shade.  You mock the simplicity of the two-color view, yet you replace it with a one-color view..."
      —Marc Stiegler, David's Sling


________________________________

**Comment by mtrojan-ub** [comment]
Jetzt sind wieder aktuelle Daten drin, über Nacht sollte auf morgen dann wieder die gewohnten Cronjobs laufen (Alerting, ...)

**Comment by IxTheoKm** [comment]
Daten sind aktuell, Alerts sind heute angekommen. Danke!
