### ISSUE TITLE
Datenschutzerklärung verlinken

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#365]
Uni-Datenschutzerklärung verlinken, solange wir noch keine eigene Erklärung für die VuFind-Systeme haben

**Comment by mtrojan-ub** [comment]
Bei IxTheo/RelBib ist es nahe "About us" (=Impressum) im Header-Menü, bei KrimDok im Footer unter "Hilfe" weil es ja im alten KrimDok-Theme weder Header-Menü noch Impressum gibt.

![grafik](https://user-images.githubusercontent.com/26873381/44332039-5fc4f780-a46b-11e8-8b96-004169892031.png)
![grafik](https://user-images.githubusercontent.com/26873381/44332091-88e58800-a46b-11e8-8f08-a0b375c41720.png)
![grafik](https://user-images.githubusercontent.com/26873381/44332227-e37ee400-a46b-11e8-87a6-7478ebe3f163.png)

**Comment by thefass** [comment]
Ist swo ok bis wir etwas Eigenes haben
