### ISSUE TITLE
Link "Neuzugänge" platzieren

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#37]
Bitte den Link "Neuzugänge", der momentan nur ganz unten zu finden ist, zusätzlich unter der Suchzeile platzieren. Rechts von "Hilfe"
[Das ist jetzt erstmal eine Sofortmaßnahme, damit ich diese Funktion, die seit langem von der Community gewünscht wurde, bekannt machen kann]

**Comment by mtrojan-ub** [comment]
kann auf ptah getestet werden

**Comment by thefass** [comment]
Funktioniert
