### ISSUE TITLE
Subito für kostenfreie Online-Ressourcen ausblenden?

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#376]
https://ixtheo.de/Record/425482162

Momentan ist dieser Datensatz eine reine Online-Ressource, die zudem kostenfrei angeboten wird.
Macht es überhaupt Sinn für solche Datensätze einen Subito-Link anzuzeigen oder die Verfügbarkeit zu prüfen?

(Hinweis: Für diesen Datensatz kann sich das durch das Merging bald ändern, aber es gibt doch bestimmt auch andere reine kostenfreie online Zeitschriften, oder?)

**Comment by Gazeller** [comment]
Ich finde, dass bei dauerhaft frei zugänglichen Ressourcen SUBITO und Verfügbarkeit prüfen und all sowas unterdrückt werden sollte, wenn das geht. Wäre einfacher und übersichtlicher für die Nutzer

**Comment by IxTheoKm** [comment]
"Kostenfrei" wird auch bei Kataloganreicherungen (Inhaltsverzeichnis, Klappentext, ...) verwendet, wenn der Volltext _nicht_ kostenfrei zugänglich ist. Wurde das berücksichtigt?
Vgl. https://github.com/ubtue/ixTheo/issues/586

**Comment by thefass** [comment]
Bei der Umsetzung auf #586 berücksichtigen.
Bitte dann subito link unterdrücken

**Comment by mtrojan-ub** [comment]
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=&type=AllFields&filter[]=~format%3A"Serial"&filter[]=is_open_access%3A"open-access"&limit=20

Bei Stichproben im Suchergebnis gefiltert nach open access & Zeitschrift habe ich keine Datensätze mehr gefunden für die Subito angezeigt wird.

Die Anzeige ist unterdrückt, siehe Code:
- https://github.com/ubtue/tuefind/blob/859722c26fe80071647527fc206573811c81cbd2/module/TueFind/src/TueFind/RecordDriver/SolrMarc.php#L193
- https://github.com/ubtue/tuefind/blob/859722c26fe80071647527fc206573811c81cbd2/module/TueFind/src/TueFind/RecordDriver/SolrDefault.php#L195

Daher gehe ich davon aus dass dieser Issue erledigt ist.
Wieviel derzeit als open access markiert ist oder auch nicht, wird ja in einem anderen Issue weiterverfolgt, siehe oben.
