### ISSUE TITLE
Falsche IxTheo-Klassifikation

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#378]
Bitte prüfen: wie kommt diese IxTheo-Notation für über 2.400 Titel zustande?

![notation](https://user-images.githubusercontent.com/17004223/44842728-e5545e80-ac46-11e8-9011-3663ca2e7b8b.png)

Beispiel-Datensätze:
https://ixtheo.de/Record/510505236#details
https://ixtheo.de/Record/498658759#details
https://ixtheo.de/Record/501750738#details
...

652 |a HC"  "226    \|b DDCoderRVK

In den SWB-Daten gibt es weder dieses Feld noch irgendwo den Inhalt "HC" oder "226"

**Comment by jriedl** [comment]
Das hängt mit der automatischen Generierung von IxTheo-Notationen aus DDC und RVK zusammen. Bis zu einer Lösung ist ist diese Funktionalität auf den Produktivsystemen deaktivert, so dass nach Abschluss des nächsten Imports dies auf ixtheo.de nicht mehr auftauchen sollte.

**Comment by IxTheoKm** [comment]
Jetzt in Ordnung, danke!
