### ISSUE TITLE
Falsche Anzeige in der Facette Verfasser

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#379]
Bitte prüfen: in der Verfasser-Facette wird eine PPN angezeigt. Einen Titel kann ich dazu nicht aufrufen.
Die PPN gehört zum Normsatz !345224779!Munding, Emmanuel*1882-1960*

![autor](https://user-images.githubusercontent.com/17004223/44844010-010d3400-ac4a-11e8-972c-3694c193e763.jpg)

**Comment by jriedl** [comment]
Dieser "Verfasser" gehört zur PPN 07045308X. Im Feld 100 findet sich hier vor der dem Ausdruck in Ausrufezeichen auch noch ein Leerzeichen. Da bei einer Suche einleitende und endende Leerzeichen ignoriert werden, liefert die Suche kein Ergebnis.

**Comment by IxTheoKm** [comment]
Danke, ich habe in PPN 07045308X den Erfassungsfehler korrigiert!

**Comment by IxTheoKm** [comment]
In der Facette Verfasser tauchen Einträge auf, die **wegen fälschlich erfasster Leerzeichen** vor dem Namen falsch sortiert z.T. nicht gefunden werden.
Kein Treffer bei "Nabulsi" und "Smith" (Feld 100 = PICA 3000)
Aber Treffer bei "Costa" (Feld 700 = PICA 3010)

![Leerzeichen_Facette](https://user-images.githubusercontent.com/17004223/77894264-54f05c80-7275-11ea-9c76-98777e5a40de.JPG)

![Leerzeichen](https://user-images.githubusercontent.com/17004223/77894668-e069ed80-7275-11ea-9741-cf246fad9b4f.JPG)

![Leerzeichen2](https://user-images.githubusercontent.com/17004223/77894558-be706b00-7275-11ea-900a-bdd798e3927c.JPG)

Können die Leerzeichen ausfindig gemacht und unterdrückt werden?

**Comment by ruschein** [comment]
@IxTheoKm Ich kann das Problem nicht reproduzieren.  Könnten Sie bitte ein paar Beispiel-PPNs angeben falls das Problem noch existiert?

**Comment by IxTheoKm** [comment]
Das Problem existiert weiter (auch auf PTAH):
Suche mit der Gesamtdatenmenge 
https://ixtheo.de/Search/Results?lookfor=&type=AllFields&limit=20&botprotect=

Facette Verfasser,
alphabetisch sortieren,
wenn ich mit dem Scrollbalken bis zum Ende "runternudle" (bis "mehr...") kommen die genannten Fälle. Datensätze zu Nabulsi und Costa lassen sich nicht aufrufen.

![leerzeichen2](https://user-images.githubusercontent.com/17004223/84908018-351e4700-b0b4-11ea-94db-7fd2de95c55c.JPG)

**Comment by IxTheoKm** [comment]
Weitere Beispiele:
https://ixtheo.de/Search/Results?lookfor=id%3A1699823049&type=AllFields&limit=20&botprotect=
Verfasser van Blerk, Nico mit einleitedendem Leerzeichen lässt sich aus der Facette nicht aufrufen

**Comment by ruschein** [comment]
Auf IxTheo und Path.

**Comment by IxTheoKm** [comment]
Scheint jetzt zu funktionieren. Danke, ich schließe!
