### ISSUE TITLE
Export von Suchergebnissen als reine PPN-Liste

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#380]
... um die PPNs dann in anderen Tools weiter verwenden zu können. Angefordert von @thefass

=> In der Trefferliste "Alles Auswählen" => "Export", hier sollte eine zusätzliche Möglichkeit zur Verfügung gestellt werden.

![grafik](https://user-images.githubusercontent.com/26873381/44911481-47849080-ad27-11e8-92d0-45d58d178590.png)

**Comment by mtrojan-ub** [comment]
... kann jetzt auf ptah getestet werden, als Medienart "PPNList" auswählen

**Comment by thefass** [comment]
Funktioniert phantastisch

Wenn ich beim Export auf "Datei herunterlade" klicke, werden die PPNs im Browser angezeigt. 
Kann anstelle von html die Datei auch als txt erzeugt werden?

**Comment by thefass** [comment]
Perfekt.
