### ISSUE TITLE
Export einer Einzel-PPN in eine URL

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#383]
Der Digitale Assistent (DA-3) kann mittels URL eine PPN entgegen nehmen.

Ziel ist es, eine einzelne PPN direkt mittels dieser URL im DA-3 öffnen zu können. Damit kann aus dem IxTheo direkt ein einzelner Titel im DA-3 sacherschlossen werden.

URL im DA-3 mit PPN 1029980705
https://services.eurospider.com/da3/edit?q=1029980705

Szenarium im IxTheo:
Auswahl eines Titels im IxTheo mittels Checkbox
Aufruf des Export Links
Auswahl der Exportroutine: PPN_to_DA-3

**Comment by jriedl** [comment]
Ist auf ptah integriert. Da aber aus konzeptionellen Gründen immer nur eine PPN übergeben werden kann, lässt sich das Ganze nicht mit Checkboxen lösen: Hier muss immer die Möglichkeit bestehen, mehrere Records gleichzeitig auszuwählen. Stattdessen wird der DA3-Export in der Volltitelanzeige angeboten (Unter "Datensatz exportieren") und öffnet hier den Link zu DA3 in einem neuen Tab.

**Comment by thefass** [comment]
funktioniert super
