### ISSUE TITLE
HBZ Gateway Problem?

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#384]
Ein Nutzer hat im Feedback auf Fehlermeldungen bei der Verfügbarkeitsanzeige über HBZ Gateway aufmerksam gemacht. Ich habe es überprüft und ebenfalls bei mehreren Titeln, die z. T. mindestens an der UB Tübingen vorhanden sind, ebenfalls Fehlermeldungen erhalten.

Hier ein Beispiel:
![grafik](https://user-images.githubusercontent.com/25769591/45029585-75c8df80-b049-11e8-8f22-6d098a8645de.png)

Nach Abfrage über HBZ Gateway:
![grafik](https://user-images.githubusercontent.com/25769591/45029565-5fbb1f00-b049-11e8-9800-69b1318bed21.png)

**Comment by jriedl** [comment]
Fehler lässt sich auch mit anderen Tübinger Titeln reproduzieren. Wenn man auf den gelben Doppelpfeil unterhalb von "Lokaler Verfügbarkeit" klickt, erscheint der Bestandsnachweis. Diesbezügliche Anfrage läuft.

**Comment by jriedl** [comment]
Rückmeldung ist erfolgt. Momentan erscheint keine Fehlermeldung mehr.

**Comment by relhei** [comment]
Vielen Dank. Hab mir das o. g. Beispiel noch einmal angeschaut, das inzwischen anscheinend gemergt wurde (print und online). Es gibt jetzt zwar keine Fehlermeldung mehr, aber dafür "0 Treffer" für UB Tübingen. Und das, obwohl eine Druckausgabe des Buches in der UB vorhanden ist. HBZ Gateway sucht anscheinend über die ISBN und wählt in diesem Fall die der Online-Ausgabe aus > 0 Treffer. Kann man da noch was machen? Oder beim HBZ anfragen, ob sie über mehrere ISBN suchen können?

**Comment by jriedl** [comment]
Das HBZ-Gateway kann zwar mehrere ISBNs interpretieren, allerdings wird nur einer an das REDI-System (den Tübinger Katalog) weitergegeben. Deshalb verwenden wir jetzt bei Vorliegen von mehr als einer ISBN eine Titelsuche.

**Comment by thefass** [comment]
bei der Übergabe in REDI ans den SWB wird der Suchbefehlt TST vorangestellt und deswegen nichts gefunden.
![bildschirmfoto 2018-10-02 um 12 26 06](https://user-images.githubusercontent.com/14169098/46343570-7cde1000-c63e-11e8-90f6-a4e42b268778.png)

Wenn man TST löscht, werden zwei Titel gefunden:
http://swb.bsz-bw.de/DB=2.1/CMD?ACT=SRCHA&IKT=1016&SRT=RLV&TRM=%22Western+Sufism%3A+from+the+Abbasids+to+the+New+Age%22&MATCFILTER=N&MATCSET=N&NOABS=Y

**Comment by thefass** [comment]
Titelsuche in REDI auf unseren Katalog funktioniert, damit dürfte das für alle Bibliotheken im SWB ok sein

**Comment by thefass** [comment]
@relhei : Bitte auch andere Bibliotheken aus anderen Verbünden (z.B. München, Köln, Hamburg, Dresden, Berlin, Frankfurt etc.) im HBZ Gateway prüfen, damit wir die Folgen abschätzen können

**Comment by relhei** [comment]
Für das o. g. Beispiel habe ich auf ptah getestet: Durchleitung zur Verfügbarkeit in der BSB, StaBi, UB Gießen, UB Marburg etc. funktioniert nicht - diese Bibl. verfügen lt. KVK über den Titel.
Bei UB Marburg habe ich geprüft: In HeBIS wird auch ein Kürzel vorangestellt, so ähnlich wie im SWB. Wenn man dieses löscht, wird ein Treffer angezeigt.
![grafik](https://user-images.githubusercontent.com/25769591/46669453-c941c680-cbcf-11e8-99a0-562bc0f9dbca.png)

Hier läuft die Durchleitung: FU Berlin. 
HBZ NRW zeigt Treffer ("in anderen Bibliotheken"), aber gleichzeitig Hinweis, dass kein eindeutiges Identifizierungsmerkmal zur Verfügung steht (ISBN etc.).

**Comment by jriedl** [comment]
Nach dem Stand der Diskussion gestern erfolgt für Monographien ja zukünftig überhaupt keine Zusammenführung mehr. Damit greift wieder die ISBN-Suche und alles sollte sich verhalten wie bisher.

**Comment by relhei** [comment]
Funktioniert. Danke!
