### ISSUE TITLE
Nutzer-Tags nicht als Schlagwort anzeigen

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#387]
Nutzer, die Ihre Tags als Lesezeichen auffassen, weil sie das vermutlich aus anderen Anwendungen gewohnt sind, vergeben nicht unbedingt Begriffe, die man als Schlagwort ablegen kann.

https://ixtheo.de/Record/378604236
https://ixtheo.de/Record/348210949
https://ixtheo.de/Record/494480661 [53 Treffer mit "Testlauf"!]

Darum sollten Tags nur als Tags angezeigt werden, und nicht bei "Weitere Schlagwörter".

**Comment by jriedl** [comment]
Falls allgemein keine Einwände bestehen, die Konvertierung von Tags in "Weitere Schlagwörter" grundsätzlich zu deaktivieren, werden wir das machen.

**Comment by thefass** [comment]
Diskutieren und entscheiden wir zeitnah

**Comment by thefass** [comment]
siehe auch #386

**Comment by thefass** [comment]
Vereinbart ist, dass wir die Daten analysieren und danach die Funktion abschalten

**Comment by thefass** [comment]
siehe Issue #386
