### ISSUE TITLE
Öffentliche Favoritenliste: Titel ergänzbar?

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#393]
Wenn man im eigenen Konto eine öffentliche Liste erstellt und diese an andere per Mail verschickt, werden im Link lediglich die Titel aufgelistet. Wäre es möglich, den Titel und evt. auch die Beschreibung der Liste mit anzuzeigen? Außerdem erscheint oben ein hellgrau unterlegtes Feld "Datensätze ansehen", das nicht unbedingt notwendig ist.

https://relbib.de/Records/Home?id%5B%5D=Solr%7C511231857&id%5B%5D=Solr%7C511237979&id%5B%5D=Solr%7C511226020&id%5B%5D=Solr%7C511230885&id%5B%5D=Solr%7C496409565&id%5B%5D=Solr%7C511261748&id%5B%5D=Solr%7C500098379&id%5B%5D=Solr%7C511236891&id%5B%5D=Solr%7C511237472&id%5B%5D=Solr%7C511272359

**Comment by thefass** [comment]
@relhei Wie hast Du diese Liste gemacht? So wie der Link aussieht ist das ja die gesamt Suchsyntax.

**Comment by thefass** [comment]
Ich hatte auch mal eine öffentliche Liste gemacht. Sie ist erreichbar, indem man die URL bekannt gibt:
Öffentliche Liste:
https://www.ixtheo.de/MyResearch/MyList/83
hier eine private Liste, bei der man sich erst einloggen müßte:
https://www.ixtheo.de/MyResearch/MyList/56

Positiv:
Bei der öffentlichen Liste wird der Titel und auch die Beschreibung der Liste mit angzeigt

störend:
die Navigationselemente an der rechten Seite: 
Your Account... 
Ebenso: Edit Delete
Das verwirrt und sollte in der öffentlichen Listensicht ausgeblendet werden.
![bildschirmfoto 2018-09-26 um 19 46 49](https://user-images.githubusercontent.com/14169098/46098709-467b3d80-c1c5-11e8-9782-c646a01075a0.png)

Sinnvoll wäre dagegen, wenn die Facetten da wären, da dann die Liste nochmal eingeschränkt werden könnte

**Comment by relhei** [comment]
Danke! ich hatte die Liste über den Button "E-Mail" verschickt, in dem Fall kommt dann kein Listentitel mit. Deine Lösung ist in der Hinsicht natürlich besser. Eine Einschränkung auf die wesentlichen Informationen fänd ich da auch sinnvoll. Hintergrund ist der, dass wir die Fachcommunity zu Semesterbeginn in einem Newsletter auf die Nutzung der öffentlichen Listen hinweisen wollen.

**Comment by relhei** [comment]
Ergänzung: Wenn ich per E-Mail-Button die Liste verschicke, gibt es die Möglichkeit die Titel zu speichern (Button oben). Mit der URL ist diese Möglichkeit nicht geboten. Wäre zu überlegen, ob man diese Funktion noch ergänzt, dann könnten Nutzer der öffentlichen Liste diese in ihrem eigenen Konto speichern und damit arbeiten. Macht das Sinn?

**Comment by jriedl** [comment]
Die Elemente zur Editierung werden jetzt im nicht eingeloggten Zustand nicht mehr angezeigt. Eine Facettierung an dieser Stelle ist so nicht möglich, da es sich um eine in MySQL gespeicherte Liste handelt, d.h. dass die SOLR-Funktionalitäten für die Facettierung nicht zur Verfügung steht. Für die Extraktion von Titeln aus der Liste zur Weiterbearbeitung besteht die Möglichkeit, diese über die Checkboxen auszuwählen, sie sich selbst über die Email-Funktionalität zuzuschicken und sie dann in eigene Listen zu übernehmen.

**Comment by thefass** [comment]
ok. Kann m.E. geschlossen werden. @relhei einverstanden?

**Comment by relhei** [comment]
Ja, ist in Ordnung. Danke!
