### ISSUE TITLE
IxTheo in Endnote und Citavi einbinden

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#395]
Professoraler Nutzerwunsch!

Was ist dafür notwendig?
Was müßten wir dafür machen?

**Comment by mtrojan-ub** [comment]
Ein Export nach EndNote ist bereits möglich

![grafik](https://user-images.githubusercontent.com/26873381/46192765-72e5a580-c2fc-11e8-8bc1-2282a6bbec93.png)

Oder was genau ist mit "einbinden" gemeint? (wir haben in der Verwendung von EndNote leider keine Erfahrung)

**Comment by thefass** [comment]
Export aus IxTheo ist klar.
Es geht aber darum, dass die Metadaten des IxTheo in Endnote recherchierbar sind.

**Comment by mtrojan-ub** [comment]
Wenn ich als Endnote-Laie das richtig verstehe, kann man weitere Seiten nur über [EndNote Connection Files](https://endnote.com/downloads/connection-files/) freischalten. Das sieht nach einem Binärformat aus, und ich habe noch keine Dokumentation dazu gefunden. Muss man dazu mit dem Hersteller in Kontakt treten?

**Comment by thefass** [comment]
Vermutlich.
habe gesehen, dass die SWB Daten in Endnote eingebunden sind. Vielleicht kannst du mal dort nachfragen.
https://endnote.com/connections_download/swb-baden-wuerttemberg/

**Comment by obrandt** [comment]
Hallo Mario,

ja, das wäre für eine Aufwandsschätzung definitiv notwendig. Ich erinnere den Support  aber als eher unterdurchschnittlich.

Viel Glück

Olaf

Sent from Nine<http://www.9folders.com/>
________________________________
Von: Mario Trojan <notifications@github.com>
Gesendet: Freitag, 28. September 2018 2:45 nachm.
An: ubtue/tuefind
Cc: Subscribed
Betreff: Re: [ubtue/tuefind] IxTheo in Endnote einbinden (#395)


Wenn ich als Endnote-Laie das richtig verstehe, kann man weitere Seiten nur über EndNote Connection Files<https://endnote.com/downloads/connection-files/> freischalten. Das sieht nach einem Binärformat aus, und ich habe noch keine Dokumentation dazu gefunden. Muss man dazu mit dem Hersteller in Kontakt treten?

**Comment by mtrojan-ub** [comment]
OK, ich frage mal extern nach was genau dafür notwendig ist und melde mich dann wieder.

**Comment by ruschein** [comment]
Die Doku von Endnote legt es nahe, dass man dazu Z30.50 für VuFind implementieren müsste.  Das wäre eine größe Aktion und müsste in einen neuen Antrag einfließen.

**Comment by mtrojan-ub** [comment]
siehe auch: https://vufind.org/jira/browse/VUFIND-295

**Comment by ruschein** [comment]
Da wir hier nichts machen können (Wir wollen Z39.50 nicht implementieren!) mache ich das Issue zu.

**Comment by thefass** [comment]
Ist ok, ich informiere den Nutzer, der diesen Wunsch hatte.
Nur für unser Gedächtnis: Citavi kann den IxTheo aus seinem Literaturverwaltungsprogramm durchsuchen. Ich habe unsere Kollegen gebeten, zu erfragen wie das bei Citavi umgesetzt ist

**Comment by thefass** [comment]
Antwort von Citavi an einen Nutzer:
"Die Verbindungsdatei für die Recherche im Index Theologicus mussten wir schon vor vielen Wochen von unserem Server löschen, weil der Anbieter seine Datenbanktechnologie gewechselt hat. (Wenn Sie mit Citavi eine Recherche durchführen, wird eine sog. Verbindungsdatei von unserem Server geladen und auf Ihrem PC gespeichert; diese Datei können wir nicht löschen, darum erscheint der Katalog noch in Ihrer Auswahl.)

Sie müssten die Recherchen wieder online durchführen, können aber die Daten mit dem Citavi Picker übernehmen, da der Anbieter nun COinS als Exportformat unterstützt."

**Comment by jriedl** [comment]
Citavi-Verbindungsdatei ist angepasst, d.h. Recherche funktioniert wieder. Weiterhin Einbindung RelBib und Krimdok.

**Comment by thefass** [comment]
Citavi funktioniert für IxTheo, RelBib und KrimDok
Umsetzung für Endnote momentan nicht geplant
