### ISSUE TITLE
Suche nach ZWI ermöglichen

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#396]
von @thefass 

> Lieber Johannes,
> 
> könnt Ihr es bitte ermöglichen, dass man nach den Daten, die Ihr zusammengeführt habt, recherchieren kann.
> M.E. ist das an dem Feld ZWI erkennbar. Ist das richtig?
> Könnte man ähnlich wie rs:bril auch nach rs:zwi suchen?
> 
> Danke und hG Martin

**Comment by mtrojan-ub** [comment]
auf ptah kann man jetzt mittels "is_hybrid:1" danach suchen.
(es ist kein Teil von "rs", da es sich ja nicht um ein Abrufzeichen handelt)

**Comment by thefass** [comment]
funktioniert
