### ISSUE TITLE
Link "Neuzugänge" platzieren

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#40]
Bitte auch in RelBib zusätzlich einen Link "Neuzugänge" zwischen den Buttons "Hilfe" und "Zeitschriftenliste" unterhalb des Suchschlitzes platzieren - analog zu IxTheo.

**Comment by jriedl** [comment]
Ist auf ptah integriert.

**Comment by relhei** [comment]
Passt. Danke!
