### ISSUE TITLE
Trefferliste: Titelanzeige eines übergeordneten Werks

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#400]
Bei Anzeige eines Aufsatzes, der aus einer Verfasserschrift stammt, in der Kurzliste wird bisher nur der Verfasser des übergeordneten Werks angezeigt (s. Titel Nr. 13). 

![grafik](https://user-images.githubusercontent.com/25769591/46658617-6d694480-cbb3-11e8-9175-8743e28097be.png)

Wünschenswert wäre, dass der Titel des übergeordneten Werkes (mit) angezeigt wird. Dazu müsste, sofern vorhanden, zusätzlich zu Feld 773 $a das Feld 773 $t in die Anzeige der Kurzliste übernommen werden.

![grafik](https://user-images.githubusercontent.com/25769591/46658802-d486f900-cbb3-11e8-9aa2-0863bc344bfb.png)

**Comment by jriedl** [comment]
Es wird jetzt im Regelfall 773$t extrahiert und nur noch auf $a zurückgegriffen, wenn $t nicht existiert.

**Comment by jriedl** [comment]
Auf ptah sichtbar.

**Comment by IxTheoKm** [comment]
Sieht jetzt in IxTheo und RelBib richtig aus.

relhei hat "System: RelBib" gelabelt. M.E. sollten immer beide Labels erfasst werden, wenn auch IxTheo betroffen ist, oder reicht eines?

**Comment by jriedl** [comment]
Im Prinzip ist es natürlich sinnvoll, wenn beides betroffen ist, beide Label zu vergeben. Ob eine Änderung am System dann "automatisch" beide Systeme betrifft, hängt vom Einzelfall ab.

**Comment by IxTheoKm** [comment]
Da in beiden Systemen die Titelanzeige jetzt korrekt ist, schließe ich.
