### ISSUE TITLE
Anzeige von internen Bearbeitungshinweisen

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#403]
In den Exemplardaten können im Kommentarfeld 4801 = Marc 86630 $x interne Bearbeitungsvermerke abgelegt werden. Benutzerrelevante, exemplarbezogene Kommentare stehen ggf. in 4802 = Marc 0852 $z.
Bei 86630 $x handelt es sich um interne Vermerke/Codes zur Sacherschließung und Formalerschließung im SWB. Zur Aufbewahrung/Löschung bestimmter Bearbeitungsvermerke müssen wir zwar noch intern Festlegungen treffen. Aber sie sollten in der öffentlichen Version der Datenbank nicht angezeigt werden. M.E. auch nicht im Internformat.

Beispiel:
https://ixtheo.de/Record/25998390X#details

LOK 0 86630 |x ***** VK ***** Fußnote 4201 mit Hinweis auf das Doppelheft in den Aufsätzen analog ergänzen!

https://ixtheo.de/Record/032866747#details

LOK 0 86630 |x zeittot. - Abweichende Berichts-/Erscheinungsjahre  für Jaargang 19, 21 und 22 (per Autopsie ab 1. 1992 geprüft). - ZsOK. -  Keine Katalogisate von anderen Bibliotheken (TUUB/sb 6.3.2017). -  Letztes geliefertes Heft: 22. 2013 (2014) -> es läuft Anfrage per  Mahnroutine 02/2017 bei EBSCO (TUUB/sb 6.3.2017). - Lt. Mail  ZS-Akzession vom 6.4.2017: nach 22.2013(2014) Erscheinen eingestellt

**Comment by jriedl** [comment]
Lokalfelder mit 86630$x werden jetzt entfernt. Auf ptah integriert.

**Comment by IxTheoKm** [comment]
In Ordnung, vielen Dank!
