### ISSUE TITLE
Medienart Lexikonartikel

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#408]
Noch offen in https://github.com/ubtue/ixTheo/issues/640

**Comment by ruschein** [comment]
Auf "ready for testing" gesetzt.

**Comment by IxTheoKm** [comment]
Auf ptah okay, danke

**Comment by IxTheoKm** [comment]
Medienart Lexikonartikel ist jetzt verschwunden.

**Comment by jriedl** [comment]
Unser Kriterium für Lexikonartikel ist 935$a=uwlx. Laut [BSZ](http://swbtools.bsz-bw.de/cgi-bin/k10plushelp.pl?cmd=kat&val=1140&kattype=Standard) scheint das auch immer noch das gültige Kriterium zu sein. Allerdings finden sich im IxTheo-Bestand keine solchen Titel mehr.

**Comment by IxTheoKm** [comment]
Es sind über 400 Datensätze. Ein Beispiel:
https://ixtheo.de/Record/1585993727#details

Offensichtlich steht das jetzt in $c:
https://ptah.ub.uni-tuebingen.de/Record/1585993727#details

**Comment by jriedl** [comment]
Vielen Dank. Das ist überraschend, weil das scheinbar bedeuten würde, dass sich das PICA/MARC-Mapping geändert hätte. Gibt es dafür eine plausible Erklärung?

**Comment by IxTheoKm** [comment]
Da habe ich keinen Einblick. Ich kann nur die Tabelle https://wiki.k10plus.de/display/K10PLUS/Exportformate?preview=/27361336/138936322/Pica_Marc_TIteldaten_K10plus_20190412.xlsx durchsuchen (in der EXCEL-Datei Zeile 1835)

**Comment by IxTheoKm** [comment]
Ich frage bei der ZRED mal an, ob es eine Konkordanzliste für geänderte MARC-Felder gibt.

**Comment by IxTheoKm** [comment]
Antwort der ZRED:
"1140 wurde schon immer nach 935 $c ausgeliefert. Das Problem ist in diesem Fall, dass der Code uwlx bei der Migration in den K10plus in ein anderes Feld umgesetzt wurde. Früher stand uwlx in Feld 0575 und dieses wurde (und wird) nach 935 $a ausgeliefert."
Die Code-Umsetzungen wurden bei der MARC-Konvertierung nicht bedacht.

Das ist ein ähnliches Problem wie https://github.com/ubtue/tuefind/issues/653 oder https://github.com/ubtue/tuefind/issues/614

Das PICA-MARC-Mapping hat sich also nicht geändert, aber die _Inhalte_ der PICA-Felder.
Was bei der Umsetzung im VuFind-Katalog leider dieselben Probleme macht, wie es ein geändertes Mapping verursacht hätte...

Auf der Seite https://wiki.k10plus.de/display/K10PLUS/Schulungen gibt es ganz unten Konkordanzen zu den Formatumsetzungen.

**Comment by ruschein** [comment]
@IxTheoKm Heißt das nicht, dass das BSZ den Fehler jetzt beheben sollte?  Schließlich wurde uns versprochen, dass sich am ausgelieferten MARC-Format nicht ändert!  Was die intern in PICA machen interessiert uns nicht die Bohne! "Die Code-Umsetzungen wurden bei der MARC-Konvertierung nicht bedacht." Sollen jetzt etwa alle Institutionen, die diese Einträge auswerten ihre Programme anpassen??

**Comment by ruschein** [comment]
Auf Ptah

**Comment by IxTheoKm** [comment]
Auf prah in Ordnung, danke
