### ISSUE TITLE
Bibelstellensuche: nicht funktionierende Abkürzungen

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#410]
Hilfreich könnten die Bemerkung in folgendem Issue sein:
https://github.com/ubtue/ixTheo/issues/552

Nicht funktionieren:
5 Ezra/5 Ezr/5 Esra/5 Esd
Das ist die selbe Gruppe wie 4 Ezra 1-2 (mit anderen Worten: 4 Ezra 1-2 = 5 Ezra)
Die Suche nach [4 Ezra 1-2](https://www.ixtheo.de/Search/Results?lookfor=4+Ezra+1-2&type=BibleRangeSearch&limit=20&sort=relevance%2C+year+desc&botprotect=) funktioniert

Nicht funktionieren:
6 Ezra/6 Ezr/6 Esra/6 Esd
Das ist die selbe Gruppe wie 4 Ezra 15-16 (mit anderen Worten: 4 Ezra 15-16 = 6 Ezra)
Die Suche nach [4 Ezra 15-16](https://www.ixtheo.de/Search/Results?lookfor=4+Ezra+15-16&type=BibleRangeSearch&limit=20&sort=relevance%2C+year+desc&botprotect=) funktioniert

**Comment by thefass** [comment]
@ruschein Hast Du schon etwas verändert?

5 Ezra/5 Ezr/5 Esra/5 Esd > funktioniert
6 Ezra/6 Ezr/6 Esra/6 Esd > funktioniert noch nicht

Im Unterschied zu 5 Ezra findet sich 6 Ezra noch in der Datei https://github.com/ubtue/ub_tools/blob/master/cpp/data/books_of_the_bible_to_code.map in Zeile 79
Vermutlich muss diese Zeile gelöscht werden, damit der Zahlencode für 4esra=68 in der Datei https://github.com/ubtue/ub_tools/blob/master/cpp/data/books_of_the_bible_to_code.map greift

**Comment by ruschein** [comment]
Scheint jetzt auf Ptah zu tun.

**Comment by thefass** [comment]
5 Ezra/5 Ezr/5 Esra/5 Esd > funktioniert

Allerdings funktioniert jetzt die Suche nach einzelnen Stellen nicht:
5 Esra 1
5 Esra 1,11
5 Esra 1,38
5 Esra 1,39-40
5 Esra 2,8-9

Der Code in 809 ist falsch:
https://ptah.ub.uni-tuebingen.de/Record/464644011#details
https://ptah.ub.uni-tuebingen.de/Record/46708694X#details

------------------------

6 Ezra/6 Ezr/6 Esra/6 Esd > funktioniert

**Comment by ruschein** [comment]
@thefass Gibt es auch einzelne Stellen für 6 Esra und falls ja, was bedeuten die dann?

**Comment by thefass** [comment]
bisher noch nicht, könnte aber zukünftig passieren.

Struktur: das 6. Esrabuch ist in zwei Kapitel gegliedert, die als Kapitel 15 (Verse 1-63) und 16 (Verse 1-78) dem 4. Esrabuch angehängt wurden. 
https://de.wikisource.org/wiki/Esdras_sechstes_Buch
In der lateinischen Überlieferung wurden diese beiden Kapitel als Kapitel 1 und 2 des 6. Esrabuches überliefert.

fiktive Beispiele: <br>
6 Esra 1, 1-13 entspräche 4 Esra 15,1-13
6 Esra 2,1-35 entspräche 4 Esra 16,1-35

**Comment by ruschein** [comment]
@thefass Auf Ptah.

**Comment by ruschein** [comment]
@thefass Bitte nochmal testen.

**Comment by thefass** [comment]
funktioniert
