### ISSUE TITLE
Bibelstellensuche: nicht funktionierende Abkürzung Lev

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#411]
Die Suche nach Bibelstellen aus dem Buch Levitikus funktionieren nicht. 
Folgende Abkürzungen sind erlaubt: Lev Lv Le

Beispiel: https://www.ixtheo.de/Search/Results?lookfor=Le+18-26&type=BibleRangeSearch&limit=20&sort=relevance%2C+year+desc&botprotect=

**Comment by thefass** [comment]
@ruschein Hast Du etwas gemacht? Jetzt geht es wieder

**Comment by ruschein** [comment]
@thefass Gerade auf "redy for testing" gesetzt.

**Comment by thefass** [comment]
funktioniert
