### ISSUE TITLE
Formular für Anschaffungsvorschlag

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#414]
Integration eines Anschaffungsvorschlag-Formulars für Titel für die IxTheo und RelBib Bibliographie analog zur KrimDok.
https://krimdok.uni-tuebingen.de/AcquisitionRequest/Create

Verändungen, die über das Krimdok Formular hinaus gehen:
1. E-Mail Adresse verbindlich machen.
2. Möglichkeit anzubieten, sich einzuloggen und auf diese Weise die Kontaktdaten aus dem Login zu übernehmen

**Comment by jriedl** [comment]
Auf ptah findet sich jetzt im Footer ein Link auf den Anschaffungsvorschlag. Falls der Nutzer eingelogged ist, weden Vor- und Nachname und Emailadresse automatisch eingetragen. Du bist für Testzwecke als Empfänger eingetragen.

**Comment by thefass** [comment]
Bitte noch ergänzen:
1. Bemerkungsfeld, so dass der Nutzer einen Kommentar zu seinem Anschaffungsvorschlag hinterlassen kann. (kein Pflichtfeld)
2. Wenn nicht alle Pflichtfelder ausgefüllt sind, kommt beim Überfahren des Daten absenden Buttons ein Symbol. Besser wäre ein Kommentar wie: "bitte alle Felder mit Sternchen ausfüllen"
Müßte allerdings in die angebotenen Sprachen übersetzt werden (zum Start wenigstens Englisch)

**Comment by thefass** [comment]
Bug?

Nach dem Absenden kommt ein Dank an den Nutzer:
![bildschirmfoto 2018-10-23 um 20 35 29](https://user-images.githubusercontent.com/14169098/47382767-507c5780-d703-11e8-997a-1e8129f97337.png)

Wenn man danach aber z.B. die Sprache wechselt, erscheint ein unsinniger Kommentar:

![bildschirmfoto 2018-10-23 um 20 37 02](https://user-images.githubusercontent.com/14169098/47382832-7dc90580-d703-11e8-9479-2f51ef953efa.png)
Oder: 

![bildschirmfoto 2018-10-23 um 20 37 14](https://user-images.githubusercontent.com/14169098/47382829-77d32480-d703-11e8-994d-ff93d8725155.png)

**Comment by thefass** [comment]
Bitte den Anschaffungsvorschlag unter A-Z verankern:

Anschaffungsvorschlag (bitte als Link auf das Formular)

Ergänzung des Eintrages "Benutzergesteuerte Erwerbung":
siehe PDA
siehe Anschaffungsvorschlag

**Comment by mtrojan-ub** [comment]
via mail von @Gazeller :
(bitte beim nächsten Mal direkt ins Issue schreiben)

```
Lieber Mario (oder Kollegen),

bitte auch in RelBib den Anschaffungsvorschlag unterbringen.
Allerdings hätte ich gerne einen anderen Satz im Formular, nämlich:

„Wenn Sie ein Buch in RelBib nicht gefunden haben, können Sie es mit diesem Formular dem FID Religionswissenschaft zur Anschaffung vorschlagen. Sie werden benachrichtigt, wenn die Erwerbung gelungen ist und das Buch zur Verfügung steht.“

[Intern: der Hinweis auf vorheriges Prüfen, ob das Buch vorhanden ist, ist m.E. obsolet. Wir müssen das ohnehin noch einmal prüfen, bevor wir es bestellen. Wichtiger finde ich den Hinweis, dass wir Bescheid geben, wenn das Buch eingetroffen ist (bzw. wenn es doch irgendwie in der UB im Bestand ist und nur nicht in IxTheo/RelBib gelandet war.) Das machen wir doch, oder?]

 Gruß Gaby
```

**Comment by thefass** [comment]
Auch für IxTheo den Satz so anpassen wie von @Gazeller vorgeschlagen.

**Comment by jriedl** [comment]
Für RelBib funktioniert das schon: Einfach auf ptah-Relbib nach dem Aufruf der Startseite "/AcquisitionRequest/create" anfügen (möchte hier öffentlich keine IP-Adressen posten). Das muss nur noch verlinkt werden.

**Comment by jriedl** [comment]
Gibt es die Möglichkeit, ein gemeinsames Grundmuster für den Text für alle unsere FIDs zu finden? Der gesonderte Hinweis bei Krimdok für die Information bei optionaler Angabe einer IP-Adresse ist schon integriert, aber vielleicht kann man sich auf gemeinsame Einleitungssätze einigen.

**Comment by jriedl** [comment]
Bemerkungsfeld integriert. Tooltip integriert. Ein Aufruf der send-Action ohne Parameter (das ist der Erffekt der Auftritt, wenn die Sprache nach der Erfolgsmeldung geändert wird) führt jetzt zur Weiterleitung auf die Formularseite. Text ist allgemein angepasst. Verlinkung über A-Z in IxTheo und RelBib integriert. In RelBib ist derzeit kein Link im Footer, da er hier thematisch extrem aus dem Rahmen fällt.

**Comment by IxTheoKm** [comment]
Ich habe zum Test einen Anschaffungsvorschlag gemacht und alle Felder einschl. Kommentar ausgefüllt. Abschicken gelingt nicht. Es kommt die Meldung "Bitte alle Felder mit Sternchen ausfüllen":
![anschaffungsvorschlag](https://user-images.githubusercontent.com/17004223/47428254-004cd600-d793-11e8-84d8-a9aecc75e0b5.png)

**Comment by jriedl** [comment]
Funktioniert jetzt.

**Comment by thefass** [comment]
funktioniert

**Comment by IxTheoKm** [comment]
Anschaffungsvorschlag über ptah ist korrekt angekommen.
Nach Abschicken des Vorschlags und Wechsel der Sprache kommt jetzt korrekt das Formular in der gewählten Sprache.
