### ISSUE TITLE
JOP: Fehlermeldung auf Ptah

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#42]
Auf Ptah wird in der Volltitelanzeige in Zeile "Journals Online & Print" eine Fehlermeldung angezeigt: "invalid server response" und entsprechend keine Icons angezeigt.

![grafik](https://user-images.githubusercontent.com/25769591/33131722-d999afe6-cf97-11e7-9982-cbabf3d5686e.png)

In RelBib funktioniert es hingegen:

![grafik](https://user-images.githubusercontent.com/25769591/33131909-4f9420aa-cf98-11e7-8791-5b9ea4ff672f.png)

**Comment by jriedl** [comment]
Ist behoben.

**Comment by relhei** [comment]
Passt. Danke!
