### ISSUE TITLE
Fehlermeldung bei Verlinkung zur parallelen Ausgabe in 775 und 776

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#420]
https://ixtheo.de/Record/483450464#details
https://ixtheo.de/Record/068597959#details

Es wird im folgenden Satz nur die ISSN der parallelen Ausgabe angezeigt. Normalerweise steht dort "Elektronisch" oder "Nicht-elektronisch".
![paralleleausg](https://user-images.githubusercontent.com/17004223/47151220-70fa7b00-d2d9-11e8-908f-86b4ba23fbb6.png)

Folgt man dem Link, kommt die Fehlermeldung "Es ist ein Fehler aufgetreten"

Liegt es evtl. am vorausgehenden Doppelpunkt im Titel?
Der ist korrekt erfasst (siehe buhv.de/unterrichtsmaterial/sekundarstufe-i/in-religion/arbeitsblaetter.html)

776 08$iErscheint auch als$nDruck-Ausgabe$a:In Religion$dAachen : Bergmoser & Höller, 1997$x1434-2251$w(DE-576)068597959$w(DE-600)1439632-4

775 08$iErscheint auch als$nCD-ROM-Ausgabe, 2015, Nr. 4$a: in Religion$dAachen : Bergmoser + Höller Verlag AG, 2015$hCD-ROMs$x1434-2251$w(DE-576)483450464$w(DE-600)2884245-5

Weiteres Beispiel:
https://ixtheo.de/Record/508460646#details

**Comment by jriedl** [comment]
Auf ptah behoben. Auf ub16 voraussichtlich morgen früh.

**Comment by IxTheoKm** [comment]
Ist okay, vielen Dank
