### ISSUE TITLE
Fehlermeldung bei Verlinkung zu paralleler Ausgabe in 776

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#421]
https://ixtheo.de/Record/510059538#details

Merkwürdiger Inhalt von Feld 776. Im SWB steht das nicht:

![dangling](https://user-images.githubusercontent.com/17004223/47151750-dbf88180-d2da-11e8-8dc6-f0cf16f17ed4.jpg)

Beim Anklicken erfolgt die Fehlermeldung "Es ist ein Fehler aufgetreten"

Im SWB ist erfasst:
772 08$iSupplement zu$aAllgemeine Israelitische Wochenschrift$dBerlin : Cronbach, 1895$hOnline-Ressource$w(DE-576)40377862X$w(DE-600)2765070-4
**776** 08$i**Elektronische Reproduktion von**$aJeschurun$dBerlin, 1892$w(DE-576)45159570X$w(DE-600)983131-9

Weiteres Beispiel:
https://www.ixtheo.de/Record/452869730#details
https://ixtheo.de/Record/424914093#details

(772 wird gar nicht angezeigt; dafür mache ich ein eigenes Issue auf:
https://github.com/ubtue/tuefind/issues/423)

**Comment by ruschein** [comment]
Sollte jetzt behoben sein.

**Comment by IxTheoKm** [comment]
"dangling" ist jetzt verschwunden. 
Allerdings die parallelen Ausgaben in 772 $0 $8, 776 $0 $8 und 775 $0 $8 ebenso.

**Comment by mtrojan-ub** [comment]
Hier ein Beispiel bei dem es aktuell mit 776 funktioniert:
https://ptah.ub.uni-tuebingen.de/Record/508460646

Mit "dangling" haben wir alle Links markiert deren Ziel nicht im Datenbestand ist, und sie deshalb jetzt ausgeblendet.

Können Sie einen Datensatz nennen, bei dem es aktuell nicht so ist wie gedacht? (evtl speziell für 772?)

**Comment by jriedl** [comment]
Nachtrag: Das ist von 772-Inhalten unabhängig. Eine Anzeige/Verlinkung der parallelen Ausgabe kann nicht sinnvoll erfolgen, wenn die Ziel-PPN nicht im IxTheo-Datenbestand gefunden wurde - deshalb "dangling".

**Comment by thefass** [comment]
könnt ihr eine Liste mit den PPN dieser fehlenden Daten erzeugen? Diese müßten dann im SWB ausgezeichnet werden, damit sie auch in den IxTheo kommen

**Comment by IxTheoKm** [comment]
Es gibt Fälle, in denen die Titel in der ZDB nicht verlinkt sind, weil dafür keine Aufnahmen existieren.

**Comment by IxTheoKm** [comment]
Beispiele ohne Anzeige der Titel aus den Feldern 

773:
https://ptah.ub.uni-tuebingen.de/Record/015178854
https://ptah.ub.uni-tuebingen.de/Record/045286671

775:
https://ptah.ub.uni-tuebingen.de/Record/424914093

776:
https://ptah.ub.uni-tuebingen.de/Record/452869730

**Comment by thefass** [comment]
Bei folgendem Beispiel handelt es sich um eine Zeitschrift. Bei der Gesamtaufnahme der Zss sollten ja Zwitter erzeugt werden (und kein gegenseitges Verlinken), damit die an den beiden Gesamtaufnahmen hängenden Aufsätze unter einer fiktiven Gesamtaufnahme zusammengeführt werden können:

https://ptah.ub.uni-tuebingen.de/Record/508460646

LEADER | 02450nas a2200601   4500

**Comment by jriedl** [comment]
Anbei die Liste der [PPNs mit fehlenden referenzierten PPNs in 775w und 776w](https://ptah.ub.uni-tuebingen.de/dangling_ppns_full.txt) sowie nur die [fehlenden referenzierten PPNs](https://ptah.ub.uni-tuebingen.de/dangling_ppns.txt).

**Comment by IxTheoKm** [comment]
Sind nur ca. 17.000

**Comment by jriedl** [comment]
773 wird für die Verlinkung des übergeordneten Werks verwendet und war bislang nicht Gegenstand dieses Issues:
- Für https://ptah.ub.uni-tuebingen.de/Record/015178854 erscheint der Titel unter "In:" in der Volltitelanzeige. 
- Für https://ptah.ub.uni-tuebingen.de/Record/045286671 ist keine BSZ-PPN hinterlegt, deshalb keine Anzeige.
- Für https://ptah.ub.uni-tuebingen.de/Record/424914093 fehlt die referenzierte PPN 429384998 im IxTheo-Bestand
- Für https://ptah.ub.uni-tuebingen.de/Record/452869730 fehlt die referenzierte PPN 495956775 im IxTheo-Bestand.

Insofern erscheint mir das Verhalten des Systems bei diesen PPNs korrekt.

**Comment by IxTheoKm** [comment]
Ich muss die Beziehungsfelder, die in MARC 772-776 transportiert werden, noch genauer sichten. Dann teste ich den gesamten Komplex

**Comment by thefass** [comment]
die Liste müßte mit den neuen K10plus PPNs nochmal erstellt werden

**Comment by IxTheoKm** [comment]
**Übersicht der Beziehungsfelder** gemäß Formatdokumentation 
und K10plus-Wiki https://wiki.k10plus.de/display/K10PLUS/Exportformate, 
die berücksichtigt werden müssen:
[Beziehungen_Titeldaten.pdf](https://github.com/ubtue/tuefind/files/3131840/Beziehungen_Titeldaten.pdf)

Parallel dazu müssen aber die zukünftigen Fälle für eine Zusammenführung getrennt behandelt werden!
Siehe https://github.com/ubtue/tuefind/issues/530 und https://github.com/ubtue/tuefind/wiki/Zwitter

**Comment by IxTheoKm** [comment]
Folgende Felder fehlen noch bei der Anzeige unter dem Reiter "Beschreibung":
**787** 
(PICA-Feld 4244, 4245 und 4249. 
Außer "Rezension..." https://github.com/ubtue/tuefind/issues/502) 

Bsp.: 
PPN 504863274, 343516578, 815394950, 79955944X, 657585742, 656333804, 89477011X

**Comment by ruschein** [comment]
@IxTheoKm Welche MARC Felder fehlen bzw wie kann man 787 Felder identifizieren, die den Pica-Feldern entsprechen?

**Comment by IxTheoKm** [comment]
Es fehlt MARC **787** bei der Anzeige, wenn nicht "Rezension von" in $i steht.
Worum es sich jeweils handelt, steht jeweils variabel in $i. 
Soweit ich erkennen kann, gibt es bei den Altdaten keine normierten einleitenden Wendungen für die jeweiligen PICA-Felder.
Es muss (analog zu "Rezension von") jeweils der Inhalt von $i in der Anzeige vorangestellt werden:

Bsp.:
PPN 504863274, 343516578, 815394950, 79955944X, 657585742, 656333804, 89477011X

https://ptah.ub.uni-tuebingen.de/Record/504863274#details
![MARC_787](https://user-images.githubusercontent.com/17004223/62549754-547bff00-b869-11e9-8695-8c7b24f28904.JPG)

**Comment by mtrojan-ub** [comment]
787 wurde nun mit aufgenommen. Es kommt aber relativ häufig vor, dass die verknüpfte PPN bei uns nicht vorhanden ist.
Beispiel: https://ptah.ub.uni-tuebingen.de/Record/1586767976
Rezension wäre: https://ptah.ub.uni-tuebingen.de/Record/1041961472

Hier noch ein paar aktuelle Testfälle zu den verschiedenen Feldern:
770: https://ptah.ub.uni-tuebingen.de/Record/129533459
772: https://ptah.ub.uni-tuebingen.de/Record/130154571
775: https://ptah.ub.uni-tuebingen.de/Record/1662898622
776: https://ptah.ub.uni-tuebingen.de/Record/1663450560
787: https://ptah.ub.uni-tuebingen.de/Record/1669074935

| Feld | Beschreibung | URL  |
| ------------- |-------------| -----|
| 770 |  |  |
| 770 |  |  |
| 770 |  |  |

**Comment by IxTheoKm** [comment]
Die Beispiele mit verknüpften PPNs, deren Datensätze bei uns vorhanden sind, sind jetzt in Ordnung.

Dass verknüpfte PPN bei uns nicht vorhanden sind, ist ein grundsätzliches Problem. Es ist ja nur ein Teil der relevanten Datensätze überhaupt mit Selektionskriterien für den IxTheo ausgezeichnet. Ob eine "Sonderauslieferung" anhand der Liste (siehe oben) erfolgen kann, weiß ich nicht. Ich halte es aber auch nicht für gut, weil dann v.a. bei Zeitschriftenaufnahmen viel Nicht-Relevantes mitkommt.

Kann man die **Anzeige** der Bezugswerke, zu denen kein Datensatz in unserem Bestand ist, ändern? Das heißt, diese Fälle **nicht** als Link anzeigen?

**Comment by mtrojan-ub** [comment]
Grundsätzlich ist das in den Templates so hinterlegt.

Im Issue #502 wird auch bei einem der Beispiele trotzdem ein Bezug im Tab "Beschreibung" ohne Link angezeigt, bei dem keine PPN hinterlegt ist.

https://ptah.ub.uni-tuebingen.de/Record/1523587253

Gibt es noch einen konkreten Fall, für den eine verknüpfter Titel nicht angezeigt wird, da keine PPN für die Verknüpfung vorhanden ist?

**Comment by IxTheoKm** [comment]
Ich verstehe den letzten Eintrag / die letzte Frage nicht.

Beim genannten Beispiel https://ptah.ub.uni-tuebingen.de/Record/1523587253 _erfolgt_ die Anzeige des Titels von "787 |i Bezugnahme auf..." unter "Beschreibung" als Bezug und ist _nicht_ als Link ausgeführt, da es keine PPN gibt. Die Hinweis auf das rezensierte Werk ist als Link ausgeführt, weil der Datensatz mit der entspr. PPN vorhanden ist.
So sollte es doch sein.

Falls es Fälle noch geben sollte, in denen ein Link hergestellt wurde, obwohl der entspr. Titel mit der ausgewiesenen PPN nicht im Datenbestand ist, lässt sich bei der Datenmenge durch Stichproben nicht oder nur zufällig herausfinden.

**Comment by mtrojan-ub** [comment]
OK, dann sind also momentan keine Fälle mehr bekannt die nicht so funktionieren wie sie sollen.
Kann der Issue dann geschlossen werden?

**Comment by ruschein** [comment]
@IxTheoKm Ich möchte noch mal auf Herr Trojans Frage hinweisen of dieser Issue jetzt geschlossen werden kann.

**Comment by IxTheoKm** [comment]
Muss ich noch prüfen.

**Comment by ruschein** [comment]
Bitte prüfen.

**Comment by IxTheoKm** [comment]
Ich habe diese -wie die anderen Issues und Baustellen- auf dem Schirm und prüfe, wenn ich dazu Zeit habe.

**Comment by IxTheoKm** [comment]
In der Tabelle vom 14 August 2019 fehlt noch das MARC-Feld **773** (lt. Exportformat für PICA 4241; wenn 039B $i ungleich Supplement zu)

Beispiel PPN 130154571 hat über 40(!) Mal Verknüpfungen:
https://ptah.ub.uni-tuebingen.de/Record/130154571#details

Beispiel PPN 022879757 mit _einem_ Feld 773 (unverknüpft):
https://ptah.ub.uni-tuebingen.de/Record/022879757#details

Diese Felder werden derzeit noch nicht angezeigt.

**Comment by ruschein** [comment]
Sollte jetzt beides tun.

**Comment by IxTheoKm** [comment]
Jetzt in Ordnung, danke!
https://ptah.ub.uni-tuebingen.de/Record/130154571 ist beeindruckend...   ;-)
Ich schließe
