### ISSUE TITLE
Enthaltene Werke, Beilagen, Supplement in 770 und 772 werden nicht angezeigt

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#423]
Beispiele:
https://ixtheo.de/Record/510059538#details [PPN-Verknüpfung]
**772** 08$i**Supplement zu**$aAllgemeine Israelitische Wochenschrift$dBerlin : Cronbach, 1895$hOnline-Ressource$w(DE-576)40377862X$w(DE-600)2765070-4

https://ixtheo.de/Record/508460646#details [Verbale Angabe]
**770** 08$i**Supplement**$aReligionsgeschichtliche Bibliographie

https://ixtheo.de/Record/41763529X#details [PPN-Verknüpfung]
**770** 08$**iEnthält**$aBildung, Erziehung und Konfirmation in der Reformation$d[Speyer] : Verl.-Haus Speyer, 2014$hS. 245 - 328$z978-3-939512-68-4$w(DE-576)473656345

https://ixtheo.de/Record/493597719#details [Verbale Angabe]
**770** 08$**iEnthält**$aGurvil, Claire$tAnnexe: Les registres révolutionnaires aux Archives historiques du diocèse de Nantes : collecte, dépouillement et mise à disposition

Mögliche Inhalte lt. Formatdokumentation von PICA-Feld 4242 (MARC 770):

    Enthält
    Sonderdruck (kann noch nicht erfasst werden)
    Supplement
    Beilage
    Enthält Faksimile von

Mögliche Inhalte lt. Formatdokumentation von PICA-Feld 4241 (MARC 772):

    Supplement zu
    Enthalten in
    Sonderdruck aus
    Beigelegt in
    Faksimile enthalten in

**Comment by jriedl** [comment]
Auf ptah werden Inhalte von 770 und 772 jetzt im Beschreibungstab angezeigt und falls möglich verlinkt.

**Comment by IxTheoKm** [comment]
Das sieht jetzt gut aus, danke!
Allerdings wird nur in eine Richtung verlinkt, nicht reziprok:

Also in https://ptah.ub.uni-tuebingen.de/Record/510059538 wird über 772 $w nicht verlinkt, 
wohl aber in https://ptah.ub.uni-tuebingen.de/Record/40377862X über 770 $w.

**Comment by jriedl** [comment]
Wird jetzt angezeigt.

**Comment by IxTheoKm** [comment]
Jetzt okay, danke
