### ISSUE TITLE
Druckausgaben mit DOI in der Facette Medientyp

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#425]
Druckausgaben, die über den DOI einen Link zum Online-Volltext bieten, sollen in der Facette Medientyp zusätzlich zu "Nicht-elektronisch" auch als "Elektronisch" nachgewiesen werden.

Beispiel:
https://ixtheo.de/Record/46719873X

024 7 $a10.2143/EP.16.3.2042716$2doi
856 $uhttps://doi.org/10.2143/EP.16.3.2042716$xdoi

![doi_elektronisch](https://user-images.githubusercontent.com/17004223/47160929-3f8da980-d2f1-11e8-962a-d82a621f04d9.jpg)

**Comment by ruschein** [comment]
Kann auf Ptah getestet werden.

**Comment by IxTheoKm** [comment]
Der Datensatz wird nun **nur** als "elektronisch" angezeigt. 
Er sollte sowohl als "elektronisch" (wegen des Zugangs über den DOI zur Online-Ausgabe), als auch als "nicht-elektronisch" angezeigt werden, da der Datensatz für die gedruckte Version steht.

**Comment by ruschein** [comment]
@IxTheoKm Kann jetzt auf Ptah getestet werden.

**Comment by IxTheoKm** [comment]
Jetzt in Ordnung, danke!
