### ISSUE TITLE
Kleiner Darstellungsfehler in Detailansicht (Tabellenhintergrund)

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#428]
"Verfügbarkeit prüfen" + "Veröffentlicht" haben in diesem Beispiel die selbe Hintergrundfarbe
https://ixtheo.de/Record/508532477

![grafik](https://user-images.githubusercontent.com/26873381/47355196-02466480-d6c1-11e8-9a17-fa2ee87ed39e.png)

**Comment by IxTheoKm** [comment]
Auf ptah jetzt okay. Im IxTheo und RelBib noch nicht.

**Comment by IxTheoKm** [comment]
Jetzt in Ordnung, danke.
