### ISSUE TITLE
Darstellung der Kapitel in der Kurztitelanzeige

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#44]
Kapitel werden intern mit der Verzählung von 0-999 dargestellt. Das soll aber in der Kurztitelanzeige nicht dargestellt werden.
Beispiel: 
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=Romans+16+and+the+tent+makers&type=AllFields&limit=20&sort=relevance%2C+year+desc
Falsch ist die Anzeige: Rom 16.0–999
Richtig: Rom 16

**Comment by thefass** [comment]
fast korrekt. Bitte noch den Punkt nach dem Kapitel (Rom 16.) entfernen
![bildschirmfoto 2017-11-24 um 22 04 49](https://user-images.githubusercontent.com/14169098/33223818-a33bf634-d163-11e7-84a3-d8a7d27dda4f.png)

**Comment by ruschein** [comment]
@thefass Der Punkt sollte jetzt weg sein.

**Comment by thefass** [comment]
ok
