### ISSUE TITLE
OA Green: Verlinkung

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#449]
AP 3.4 des FID Theologie Antrages
### OA Green: Verlinkung zu Open Access (Zweit-)Veröffentlichungen aus externen Quellen

Unpaywall (zum Antragszeitpunkt hieß der Name OADOI) spürt weltweit frei zugängliche Green Open Access Publikationen auf. Über eine API können die Daten nachgenutzt werden. Im IxTheo sind momentan 37.543 Aufsätze, die einen DOI haben. Ca. 10% dieser Aufsätze sind über oadoi als Green OA in Repositorien frei zugänglich. Die Zugangs-URLs werden über die oadoi-API in den IxTheo verlinkt.

http://unpaywall.org/

Bitte gleich für alle drei Bibliographien verwirklichen: IxTheo, RelBib, KrimDok

**Comment by thefass** [comment]
Für uns kommen entweder die API oder der DataFeed in Frage.

Datafeed ist wohl am komfortablsten, kostet aber etwas:

http://unpaywall.org/products/data-feed
" The Data Feed is unique among our products in that it costs money. This is because it's more expensive to run than our other products; harvesting everything once is pretty cheap, but doing it in an ongoing way is not. In due time we'd like to have a transparent pricing structure for these, but for now we are handling it on a more custom basis, as we learn more about the market. As a nonprofit, our goal isn't to get rich off this, but rather to give everyone a fair deal while ensuring a sustainable model that keeps Unpaywall a working resource for the long haul.

If you're interested in the Data Feed, please drop us a line and let us know the size of your organization and your intended use of the data, and we'll get right back to you with a quote. We look forward to hearing from you! "

**Comment by thefass** [comment]
Das sollten wir für unsere Facetten nutzen:

"Can Unpaywall Data tell me whether an article is "Green," "Gold," or "Bronze" OA?
    We don't include the "OA Color" explicitly in the data schema, because we found that people's definitions of the colors vary pretty widely, and so it was causing confusion. Instead, we include all the data you'll need to decide the color based on your own definitions, whatever they may be. In particular, you'll probably want to look at the is_oa and journal_is_oa fields of the DOI Object, as well as the license and host_type fields of Location Objects. See the schema documentation for more details. "

**Comment by obrandt** [comment]
Hallo,

können wir das in den kommenden Antrag reinnehmen? Wir müssen ja die Daten abziehen bzw. immer aktuell abfragen.

Von: thefass [mailto:notifications@github.com]
Gesendet: Mittwoch, 31. Oktober 2018 10:32
An: ubtue/tuefind <tuefind@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [ubtue/tuefind] OA Green: Verlinkung (#449)


Das sollten wir für unsere Facetten nutzen:

"Can Unpaywall Data tell me whether an article is "Green," "Gold," or "Bronze" OA?
We don't include the "OA Color" explicitly in the data schema, because we found that people's definitions of the colors vary pretty widely, and so it was causing confusion. Instead, we include all the data you'll need to decide the color based on your own definitions, whatever they may be. In particular, you'll probably want to look at the is_oa and journal_is_oa fields of the DOI Object, as well as the license and host_type fields of Location Objects. See the schema documentation for more details. "

**Comment by jriedl** [comment]
Für Testzwecke könnte man ja einmal mit dem (offenbar kostenlosen) Snapshot anfangen: http://unpaywall.org/products/snapshot, da für Facetten ist ein Zugriff auf die Gesamtdaten zwingend notwendig ist. Das sind allerdings wirklich große Datenmengen (83GB entpackt).

**Comment by thefass** [comment]
Ja, mit Snapshot anfangen, denn unpaywall (oadoi) ist im FID Theo beantragt und genehmigt.
Weiterentwicklungen gerne in den kommenden FID Antrag

**Comment by thefass** [comment]
In irgendeinerweise sollte die Quelle "unpaywall" im Datensatz festgehalten und suchbar gemacht werden

**Comment by jriedl** [comment]
In allen drei (Test-)Systemen lassen sich nun mittels der Suche "has_unpaywall_entry:1" die Records selektieren, die durch die Auswertung des Unpaywall-Snapshots weitere Volltextlinks erhalten haben.

**Comment by jriedl** [comment]
Für eine Facettierung müssten Kriterien für die Zuordnung zu einer OA-Klasse definiert werden.

**Comment by thefass** [comment]
Analog zu den anderen Fällen (Siehe screenshot) bitte folgendermaßen umsetzen:
856 $xunpaywall $zKostenfrei

![bildschirmfoto 2018-11-07 um 12 14 41](https://user-images.githubusercontent.com/14169098/48128531-0eb4ea80-e287-11e8-8e11-2fc84ebe4f8c.png)

**Comment by thefass** [comment]
Alle Titel mit $xunpaywall können als OA definiert werden

**Comment by thefass** [comment]
Problemanzeige:
bei dem Datensatz https://ptah.ub.uni-tuebingen.de/Record/505409445#details führt der unpaywall link zum kostenpflichtigen Artikel auf der Sage Seite. Das dürfte eigentlich nicht sein. Ist das ein Fehler von unpaywall?

**Comment by thefass** [comment]
Problemanzeige 3:
auch kein Zugang bei diesem Datensatz: https://ptah.ub.uni-tuebingen.de/Record/453172423

kommt ein restricted Hinweis von babel.hathitrust,org
![bildschirmfoto 2018-11-07 um 12 41 16](https://user-images.githubusercontent.com/14169098/48129682-86d0df80-e28a-11e8-92c6-9d3180aaaddb.png)

**Comment by thefass** [comment]
Problemanzeige 4:
https://ptah.ub.uni-tuebingen.de/Record/492024340

hier kommt man zu einer Seite mit dem 404 Fehler

**Comment by thefass** [comment]
wir sollten das Procedere diskutieren.

Folgendes Vorgehen kann ich mir vorstellen:
1) Probleme an unpaywall melden, damit die ihre Daten verbessern
2) bei uns einbinden, auch wenn es fehlerhafte Links gibt
3) das dem Nutzer transparent machen, indem man in $z schreibt: "vermutlich kostenfreier Zugang" / "presumably free access"

**Comment by thefass** [comment]
Wir haben Lösung 3 umgesetzt

Aktuelles Wiki zu unpaywall: https://github.com/ubtue/tuefind/wiki/Unpaywall
