### ISSUE TITLE
Doppelungen der Bibelstellen vermeiden

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#45]
Bei der einfachen Suche werden die Bibelstellen nun zweimal dargestellt. Das sollte vermieden werden

Beispiel:
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=Romans+16+and+the+tent+makers&type=AllFields&limit=20&sort=relevance%2C+year+desc

**Comment by ruschein** [comment]
Diese Verdopplung lässt sich nur schwer vermeiden da wir nicht wissen was in den Schlagworten steht.
