### ISSUE TITLE
Supervision

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#450]
Viele Zeitschriften sind nur noch elektronisch subskripiert, viele Metdaten erheben wir zukünftig automatisch. Das macht eine Supervision nötig, die den fortlaufenden Eingang der Metadaten beobachtet.

**Ziel**:
auf eine einfache, schnelle Art muss festgestellt werden können, ob und welche Zeitschriftenhefte indiziert wurden.

**Umsetzung**:
1. Betroffen sind alle in Zeder festgehaltenen Quellen
2. Bezugskriterium ist die PPN (PPPN und EPPN)
3. anhand der PPN wird folgende Info erzeugt:
Jahr, Band, Heft, Zahl der Aufsätze
Delimiter: Komma Leerzeichen
4. Diese Angaben werden nach Zeder geschrieben
für die PPPN nach Spalte: fpppn
für die EPPN nach Spalte: feppn
5. es werden jeweils die 6 neuesten Ausgaben untereinander nach Zeder geschrieben; jeweils in eine eigene Zeile
6. die neueste Ausgabe steht ganz oben

**Beispiel**: Zeitschrift für die neutestamentliche Wissenschaft
PPPN 014825732
2018, 109, 1, 1
2014, 105, 1, 7
2013, 104, 2, 7
2013, 104, 1, 5
2012, 103, 2, 8
2012, 103, 1, 9

EPPN 094480885
2018, 109, 2, 7
2018, 109, 1, 9
2017, 108, 2, 7
2017, 108, 1, 7
2016, 107, 2, 8
2016, 107, 1, 8

7. Um einen Gesamtüberblick zu haben wird die kumulative Ausgabe für PPPN und EPPN in eine Textdatei geschrieben. Reihenfolge auch hier: neueste Ausgabe oben.
Diese Datei wird auch über Zeder zugänglich gemacht. Procedere muss geklärt werden

**Comment by thefass** [comment]
Die Spalten wurden in Zeder eingefügt:

Siehe Punkt 4 oben:
für die PPPN nach Spalte: fpppn
für die EPPN nach Spalte: feppn

Diese Spalten existieren für IxTheo/RleBib in der gemeinsamen Zederinstanz ixtheo als auch in der KrimDok Zederinstanz krim

**Comment by ruschein** [comment]
@thefass Das hängt immer noch an der Implemtierung von Ingo.

**Comment by thefass** [comment]
Wir sind als nächstes Projekt prioritär an der Reihe. Ich rechne mit Januar 2020. Dann aber alles, was in Zeder noch aussteht in einem Ruck. So ist es mit der Direktion verabredet.

**Comment by ruschein** [comment]
@thefass Ist da jemals etwas passiert?

**Comment by thefass** [comment]
noch nicht. Ich warte auch inständig darauf. Meine Info ist, dass wir im Februar drankommen

**Comment by ruschein** [comment]
@thefass Gibt es hier Fortschritte.

**Comment by thefass** [comment]
Ein Jahr später ... und kein Fortschritt ... nichts ... grrrh
Müssen wir unter vier Augen mal klären

**Comment by ruschein** [comment]
Update: Ich würde hier sehr gern weitermachen und habe dies auch mit Olaf heute besprochen.  Was mich blockiert ist folgendes:  Es steht im Raum, dass Arne und/oder Florian diese Datenbank nach Postgres migrieren.  Dadurch müsste Ingo sein R-Programm welches Zeder erzeugt anpassen.  Sobald es sicher ist, dass die Datenbank von MySQL nach Postgres migriert kann ich sofort weiter arbeiten.

**Comment by mtrojan-ub** [comment]
... wobei das nach relativ viel Aufwand klingt, weil ja unsere C++ DbConnection erstmal von Grund auf mit PostgreSQL kompatibel gemacht werden müsste, oder?

**Comment by thefass** [comment]
@ruschein 
bug in der Sortierung:
Datei: 478+561972656.txt

2019,45,4,408-436
2019,45,4,437-446
2020,46,1,112-134
2020,46,1,135-157
2020,46,1,158-176
2020,46,1,177-193
2020,46,1,194-211
2020,46,1,212-215
**2020,46,1,216-229
2020,46,1,32-58
2020,46,1,59-75
2020,46,1,7-31
2020,46,1,76-96
2020,46,1,97-111**
2020,46,2,260-281
2020,46,2,282-297
2020,46,2,298-314
2020,46,2,315-334
2020,46,2,335-348

**Comment by thefass** [comment]
muss nun auf Zeder Seite umgesetzt werden
