### ISSUE TITLE
Gelöschter Titel noch im IxTheo

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#454]
Der Titel PPN 51015493X wurde im SWB bereits vor längerer Zeit gelöscht. Er ist im IxTheo noch vorhanden:
https://ixtheo.de/Record/51015493X.
Eine andere Löschung von gestern (8.11.2018) ist heute korrekt erfolgt.

**Comment by jriedl** [comment]
Hier bestand ein jetzt behobenes Problem mit der Behandlung der allgemeinen Löschlisten. Die Einspielung der Korrekturen für zurückliegende Zeiträume wird auf ptah voraussichtlich heute im Laufe des Tages, auf ub16 ab morgen nach Abschluss des Imports sichtbar sein.

**Comment by IxTheoKm** [comment]
Titel wurde gelöscht, danke!
