### ISSUE TITLE
Fehler bei Suchanfrage aus Autocomplete-Vorschlag (Verfasser)

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#459]
Nach Auswahl eines Verfassernamens aus dem Autocomplete kommt bei Auslösung der Suchanfrage kein Ergbenis, wenn dem Stern ein Lebensdatum vorangestellt ist: 

![grafik](https://user-images.githubusercontent.com/25769591/49439560-a8f24a80-f7c1-11e8-8a8c-f155bb422db1.png)

Die Suchanfrage funktioniert erst dann, wenn man den Stern wieder händisch löscht:

![grafik](https://user-images.githubusercontent.com/25769591/49439812-55ccc780-f7c2-11e8-9f31-d7baaad7ad1f.png)

**Comment by jriedl** [comment]
Autorenvorschläge werden jetzt auf ptah so angepasst, dass die Suche keine leeren Ergebnisse mehr liefert.

**Comment by relhei** [comment]
Sieht gut aus. Danke!
