### ISSUE TITLE
Ptah: nach Suche keine Anzeige der Schlagwortfacetten

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#46]
Nach Auslösen einer Suche mit Suchbegriff über alle Felder werden die Schlagwortfacetten rechts nicht angezeigt, obwohl die Titel Schlagwörter aufweisen.

![grafik](https://user-images.githubusercontent.com/25769591/33167339-86eca5c2-d03d-11e7-9267-f3f89c8c0016.png)

![grafik](https://user-images.githubusercontent.com/25769591/33167360-9cf28e9a-d03d-11e7-9fc1-1f047222b665.png)

![grafik](https://user-images.githubusercontent.com/25769591/33167418-c4e9b162-d03d-11e7-80cb-c66279a81bc8.png)

**Comment by jriedl** [comment]
Wird wieder angezeigt.

**Comment by relhei** [comment]
Danke!
