### ISSUE TITLE
Suchaspekt CDD/DDC in der einfachen Suche abweichend von der erweiterten Suche

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#460]
Bitte für die französische Oberfläche die französische Abkürzung "**CDD**" (statt DDC) analog zur erweiterten Suche verwenden.

![ddc](https://user-images.githubusercontent.com/17004223/49449833-0dba9e80-f7dc-11e8-8512-878f6cabe397.png)

![ddc2](https://user-images.githubusercontent.com/17004223/49449851-14491600-f7dc-11e8-90ab-172d59ae4086.png)

**Comment by jriedl** [comment]
Ist angepasst.

**Comment by IxTheoKm** [comment]
Vielen Dank!
