### ISSUE TITLE
ISBN anzeigen und Suchbarmachen in KrimDok

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#472]
In IxTheo und Relbib wird die ISBN im Reiter Beschreibung angezeigt und ist in der allgemeinen Suche auch suchbar. Das sollte in KrimDok auch möglich sein.

Beispiel: https://relbib.de/Record/508532477

**Comment by thefass** [comment]
sorry, das geht normalerweise.
Nicht aber in diesem Fall: https://sobek.ub.uni-tuebingen.de:4445/Record/455667942#details

**Comment by thefass** [comment]
anscheinend wird dafür Feld 776 1 ausgewertet, das fehlt bei obigem Beispiel. Die ISBN steht aber anscheinend auch (immer?) nochmal in 020

**Comment by ruschein** [comment]
@thefass Wir werten 020$a aus.  Hier steht eine ungültige ISBN in $z: https://www.loc.gov/marc/bibliographic/bd020.html

**Comment by thefass** [comment]
Dann habe ich die berühmte Stecknadel im Haufen gefunden. Habe die Bibliothekarin um Korrektur gebeten

**Comment by thefass** [comment]
Datensatz wurde korrigiert
