### ISSUE TITLE
Fehlermeldung beim E-Mailen einer Literaturliste

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#482]
Beim Versenden einer E-Mail mit einer Literaturliste aus RelBib-Konto über den Funktionsbutton erscheint eine Fehlermeldung:
![grafik](https://user-images.githubusercontent.com/25769591/50053171-7553e080-0130-11e9-92c7-2a174b8baf95.png)

**Comment by jriedl** [comment]
Auf ptah und RelBib/IxTheo behoben.

**Comment by relhei** [comment]
Sieht gut aus. Danke!
