### ISSUE TITLE
Nur ein Teil der Rezensionen wird angezeigt

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#502]
Der Titel https://ixtheo.de/Record/507244230#details rezensiert 10 Bücher, die alle in 787 im Internformat aufgeführt werden (und auch bei einer Suche gefunden werden).
In der Volltitelanzeige werden aber nur 6 Bücher aufgeführt.

![bildschirmfoto 2019-01-16 um 22 28 13](https://user-images.githubusercontent.com/14169098/51279726-3b4f5600-19de-11e9-90a3-a173d933716a.png)

Es sollten alle angezeigt werden

**Comment by jriedl** [comment]
Bei den letzten vier Einträgen handelt es sich offenbar um Bände mit mehreren Herausgebern. Es fehlt das übliche Titelfeld $t, stattdessen findet sich der Titel in $a. Laut Konkordanz steht der Titel in $a wenn $l nicht vorhanden ist. Es findet sich aber auch bei den anderen Einträgen kein $l. Kann grundsätzlich $a als Titel verwendet werden, wenn $t nicht vorhanden ist? Weiterhin scheinen die in 787 angegebenen PPNs in $w offenbar nicht Teil des IxTheo-Datenbestandes zu sein.

**Comment by IxTheoKm** [comment]
Zum Vergleich: das geschlossene Issue https://github.com/ubtue/ixTheo/issues/177

**Comment by IxTheoKm** [comment]
Rückmeldungen bzw. Umsetzungen sind noch offen (sicher wegen K10plus):

**Stand der Anfragen:**

**SWB-Mailbox PPN 475425294:**
"... könnten Sie bitte die Marc-Auslieferung prüfen: es scheint so, als würden rezensierte Werke, die keinen Autor haben, mit $a statt mit $t ausgeliefert werden. ... **********, das ist ein Fehler in unserer Exportschnittstelle, anstelle $a muss bei Sachtitelwerken tatsächlich $t geliefert werden. Wir werden das im Zuge von mehreren MARC-Anpassungen ankündigen und dann nach einer Frist aktivieren. ********** ... Eine Änderung ist noch nicht erfolgt, richtig? Und ergänzend die Frage: bei alten RAK-Aufnahmen, die nicht verknüpft sind, steht der Titel auch immer nach $a, weil der Autor nach Schrägstrich ergänzt ist (Bsp. PPN 453587259, zweites Feld 4261). Müsste dort nicht auch $t stehen? ********** ... die MARC-Anpassung ($t anstelle $a) ist leider noch nicht erfolgt. Bei den alten RAK-Aufnahmen wird wohl $a bestehen bleiben, da ich sonst den Inhalt aufgrund der Deskriptionszeichen komplett auseinandernehmen lassen muss! ..."

**Mail:**
"... Sie schreiben, dass die Titel anonymer Werke in 689 $a ausgegeben werden.

Wenn ich mir Beispiele anschaue, werden die Titel von anonymen Werken wie die Titel von Verfasserwerken auch in $t ausgegeben:
Vgl. Sie PPN 041689178, 451555066, 435290134 …
689 00$Du$0(DE-588)4199505-3$0(DE-576)210129123$2gnd$tDer zwölfjährige Jesus im Tempel
689 01$Du$0(DE-588)4369917-0$0(DE-576)211699640$2gnd$tBibel$pSamuel$n1.$n1-3
…
689 00$Du$0(DE-588)1062665147$0(DE-576)419978925$2gnd$tTheologie heute

Zur zukünftigen Auslieferung in K10plus:
Die Auslieferung der anonymen Werke bleibt unverändert?"

**Comment by IxTheoKm** [comment]
Betr. **689 $t**
Die Auslieferung für anonyme Werke bleibt in K10plus unverändert in $t, daher hier kein Handlungsbedarf.

**Comment by IxTheoKm** [comment]
Betr. **787 $t**

Das BSZ hat nun den K10plus-Stand mitgeteilt: 
Bei **RDA-Aufnahmen (040 $e rda)** werden nun alle Werktitel in $t ausgeliefert.

Beispiel ("Rezension von"):
https://ixtheo.de/Record/154396236X#details

Wenn es einen Autor gibt, wird dieser in $a ausgeliefert, der Werktitel in $t.

Wenn es _keinen_ Autor gibt, fehlt $a. 
In diesen Fällen fehlt bisher die Anzeige der Rezensionen. Bitte auch diese Fälle für die Anzeige berücksichtigen!

**Comment by IxTheoKm** [comment]
**Betr. 787 $a**

Bei RAK-Aufnahmen (ohne 040 $e rda) werden alle _unverknüpft_ erfassten Bezugswerke in **$a ohne $t** ausgeliefert!

Beispiele:
https://ixtheo.de/Record/1632317265#details 
(_unverknüpft_: "Rezension von" $a...) Rezension wird nicht angezeigt

https://ixtheo.de/Record/1523587253#details
(_verknüpft_: "Rezension von" $t...) Rezension wird angezeigt
(_unverknüpft_: "Bezugnahme auf" $a...) Bezugswerk wird nicht angezeigt

Bitte bei RAK-Aufnahmen ohne 040 $e rda die Rezensionen bzw. Bezugswerke immer dann auch anzeigen wenn nur $a ohne $t vorliegt

**Comment by ruschein** [comment]
Auf Ptah

**Comment by IxTheoKm** [comment]
Aufnahme mit 040 $e rda ist jetzt in Ordnung. 
Beispiel PPN https://ptah.ub.uni-tuebingen.de/Record/154396236X#details

**Nicht in Ordnung sind Aufnahmen _ohne 040 $e rda_, mit $i Rezension oder $i Bezugnahme auf, in denen oft in 787 nur $a oder nur $t steht**
Beispiele:

https://ptah.ub.uni-tuebingen.de/Record/1523587253#details
Nicht angezeigt:
787 |i Bezugnahme auf   **|t** (Dis)closure in Qohelet / Mark Sneed. - In: Journal for the study of the Old Testament. - 27 (2002), S. 115-126

https://ptah.ub.uni-tuebingen.de/Record/1632317265#details
Nicht angezeigt:
787 |i Rezension von    **|a** La règle de saint Benoît, chemin de vie pour les lai͏̈cs / Pierre-Alban Delannoy. - Paris : Albin Michel, 2015

https://ptah.ub.uni-tuebingen.de/Record/1641422068#details
Nicht angezeigt:
787 |i Rezension von    **|a** Gottes Einzigkeit / Oswald Loretz

**Wenn es entweder _nur_ $a oder _nur_ $t gibt, sollen die Rezensionen angezeigt werden.
Beide müssen wie $t behandelt werden**

**Comment by mtrojan-ub** [comment]
Die Referenzen sind nun überall vorhanden. Im Detail:

1) https://ptah.ub.uni-tuebingen.de/Record/1523587253#details
Ist Keine "Rezension" oder "Rezension von". Sonstige Bezüge befinden sich unten im Tab "Beschreibung" unter "Bezug". Da keine PPN in 787 hinterlegt ist, wird hier nur der Titel ohne Link angezeigt.

![grafik](https://user-images.githubusercontent.com/26873381/63697239-d03fea80-c81c-11e9-8bcd-7e6fc9cf256d.png)

2) https://ptah.ub.uni-tuebingen.de/Record/1632317265#details
![grafik](https://user-images.githubusercontent.com/26873381/63697281-e6e64180-c81c-11e9-98aa-3767d9f8f587.png)

3) https://ptah.ub.uni-tuebingen.de/Record/1641422068#details
![grafik](https://user-images.githubusercontent.com/26873381/63697345-067d6a00-c81d-11e9-9ae8-75ea821859d4.png)

**Comment by mtrojan-ub** [comment]
Kleine Anmerkung: Auf den Screenshots oben bei 2 und 3 stand "Rezensionen" statt "Rezension von", das wurde nun aber ebenfalls behoben.

**Comment by thefass** [comment]
Fast perfekt.

In den Fällen, in denen es keine Verknüpfung gibt (also ohne PPN), sollte der literal angegebene Text nicht als Link gestaltet werden, sonst klickt man darauf und bekommt eine Fehlermeldung.
Beispiel: https://ptah.ub.uni-tuebingen.de/Record/1632317265#details#

![Bildschirmfoto 2019-08-28 um 16 13 31](https://user-images.githubusercontent.com/14169098/63863637-d796fd80-c9ae-11e9-8c4d-443348c11b11.png)

**Comment by mtrojan-ub** [comment]
...ist behoben, bitte nochmal testen!

**Comment by thefass** [comment]
auf ptah in Ordnung
