### ISSUE TITLE
Auffinden falscher Titel im IxTheo

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#51]
Durch Datenselektion wurden falsche Titel in den IxTheo aufgenommen.
Der Fehler kommt über die SSG Nummer. Für den IxTheo ziehen wir die 0 (SSG Nummer für Religionswissenschaft) und die 1 (SSG Theologie) ab. Es gibt aber andere SSGs, in denen eine 1 vorkommt. Z.B 19,1
Wenn nun ein Syntaxfehler bei der Eingabe gemacht wurde, dann wird die 1 als eigenständige, zweite SSG Nummer im Datensatz dargestellt und der Titel kommt fälschlich in den IxTheo
![bildschirmfoto 2017-11-24 um 20 57 00](https://user-images.githubusercontent.com/14169098/33223184-9d09f79e-d15d-11e7-92d6-8638c40c4224.png)
Eingabefehler in der WinIBW:
![bildschirmfoto 2017-11-24 um 21 48 19](https://user-images.githubusercontent.com/14169098/33223610-48e959da-d161-11e7-9628-84228ad1bf90.png)

Beispiele: PPN 04199342X

Diese Titel müssen manuell mit mtex ausgezeichnet und die SSG Nummer korrigiert werden.

Bitte eine Liste ausgeben nach folgender Syntax
PPN | SSG-Nummer
Kriterium: alle SSG Nummern, die außer den folgenden Mustern noch weitere SSG Nummern neben der 1 oder der 0 enthalten. Sortierung bitte nach SSG Nummer:
1
0
1 | 0
1 | 6,22
0 | 6,22
1 | 0 | 6,22

**Comment by jriedl** [comment]
[ssgn_irregular_clean_sorted_stripped.txt](https://github.com/ubtue/tuefind/files/1510969/ssgn_irregular_clean_sorted_stripped.txt)

**Comment by ruschein** [comment]
@thefass Können wir dieses Issue jetzt zumachen?

**Comment by thefass** [comment]
ja, auch wenn die Bereinigung noch andauern wird. Ist aber programmiertechnisches Problem/Lösung
