### ISSUE TITLE
Standardtext in Email verändern

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#52]
Bitte Standardtext verändern.

Momentan erscheint:
![bildschirmfoto 2017-11-26 um 22 53 52](https://user-images.githubusercontent.com/14169098/33244741-13adeedc-d2fd-11e7-830a-d0fbddf47320.png)

Korrektur für alle FIDs:
Bitte den Vorsatz "E-Mail-Link" verändern in:
- Link im IxTheo
- Link in RelBib
- Link in KrimDok
(in der KrimDok fehlt noch "Als E-Mail versenden" und "Zu den Favoriten", da noch keine Anmeldung von Nutzern freigeschaltet ist.)

Korrektur im IxTheo
die Adresse ixtheo-test in ixtheo verändern

**Comment by jriedl** [comment]
Texte in der Email sind angepasst. Ixtheo-Adress-Änderung erst im Rahmen des Updates auf tuefind.

**Comment by thefass** [comment]
Email Texte sind ok
