### ISSUE TITLE
Zwitter: falsche Verlinkung

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#529]
online PPN 433582189
https://ixtheo.de/Record/433582189
hat als print Pendant
print PPN 36326051X

Auf ptah ist in dem Zwitter fälschlicherweise aber mit 34036906X verlinkt. von dort ist in dem Zwitter auf ptah auch die beiden Links auf Inhaltsverzeichnis und Inhaltstext eingefügt
https://ptah.ub.uni-tuebingen.de/Record/433582189#details

**Comment by ruschein** [comment]
@thefass Ist behoben und sollte nach dem nächsten Pipleline-Durchlauf, also morgen, auch auf Path richtig angezeigt werden.

**Comment by thefass** [comment]
ist ok
