### ISSUE TITLE
Zwitter: keine Zusammenführung

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#530]
Die print und online Ausgabe der Zss Temenos wurden nicht zusammengeführt
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=Temenos+%3A+nordic&type=AllFields&filter%5B%5D=%7Eformat%3A%22Journal%22&limit=20&botprotect=

![bildschirmfoto 2019-02-16 um 11 55 06](https://user-images.githubusercontent.com/14169098/52898765-2125b500-31e2-11e9-8166-8781a18241f6.png)

**Comment by thefass** [comment]
Die Suche nach den Zwittern is_hybrid:1 führt zu 1027 Zss. Von meinem Gefühl her müßten das mehr sein.

**Comment by thefass** [comment]
Ebenso keine Zusammenführung
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=Journal+for+the+study+of+Paul+and+his+letters&type=AllFields&filter%5B%5D=%7Eformat%3A%22Journal%22

![bildschirmfoto 2019-02-16 um 22 50 46](https://user-images.githubusercontent.com/14169098/52905648-57dce900-323d-11e9-822f-217facb1f298.png)

**Comment by thefass** [comment]
was ich nicht verstehe, warum die Zusammenführung mal klappt und mal nicht.
hier ein Beispiel, wo es klappt:
https://ptah.ub.uni-tuebingen.de/Record/094480885

**Comment by ruschein** [comment]
Der Grund ist, dass wir bisher 775 und 776 für Querverweise auswerten und die finische Zeitschrift hat die Querverweise in den Feldern 780 und 785.  Hier ist die Documentation: [https://www.loc.gov/marc/bibliographic/bd76x78x.html](https://www.loc.gov/marc/bibliographic/bd76x78x.html).  @IxTheoKm Könnten Sie das bitte mal prüfen?

**Comment by thefass** [comment]
Der Fall Temenos ist damit erklärbar, da dort die Querverweise in 780 und 785 stehen.
770 und 785 werden nun auch ausgewertet. Das kann ab 19.2. getestet werden

**Comment by thefass** [comment]
Der Fall Journal of the study of Paul and his letters bleibt aber unklar.

In der Online Ausgabe mit der PPN 49724893X (im Feld 001) steht der Querverweis in 775 w (DE-576):
https://ptah.ub.uni-tuebingen.de/Record/49724893X#details
![bildschirmfoto 2019-02-18 um 15 58 53](https://user-images.githubusercontent.com/14169098/52959297-27f52900-3396-11e9-915e-2341077ebdd4.png)

In der Print Ausgabe mit der PPN 42579573X (im Feld 001) steht der Querverweis in 775 w (DE-576):
https://ptah.ub.uni-tuebingen.de/Record/42579573X#details
![bildschirmfoto 2019-02-18 um 16 01 24](https://user-images.githubusercontent.com/14169098/52959456-828e8500-3396-11e9-92f9-8a157a8f4717.png)

Es sind also immer die Paare 001 - 775 mit den reziproken Nummern vorhanden. Folglich müßten sie auch zu einem Zwitter zusammengefügt worden sein, was aber nicht der Fall ist:
https://ptah.ub.uni-tuebingen.de/Record/42579573X#details

**Comment by IxTheoKm** [comment]
Zum Fall Temenos:
Die Verlinkung der beiden Ausgaben steht im Feld für _Vorgänger_- und _Nachfolger_beziehungen, da in diesem Fall die Druckausgabe die Vorgängerausgabe, und die Online-Ausgabe zusätzlich die Nachfolgerausgabe ist.
Die Druckausgabe erscheint 1.1965-50.2014, die Online-Ausgabe erscheint 1.1965 ff.

**Comment by IxTheoKm** [comment]
Anbei das Format für Beziehungsfelder in der ZDB. Ob die Übersicht vollständig ist und was sich hinter 4243 und 4249 verbirgt, muss ich klären.
[ZDB-Format_Beziehungen.pdf](https://github.com/ubtue/tuefind/files/3002218/ZDB-Format_Beziehungen.pdf)

**Comment by thefass** [comment]
wird neu aufgesetzt und in einem Wiki dokumentiert:
https://github.com/ubtue/tuefind/wiki/Zwitter
