### ISSUE TITLE
Zwitter: Medientyp Angabe

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#531]
In der Kurztitelanzeige sollte bei den Zwittern angegeben werden:
Elektronisch + Print

und nicht nur Elektronisch. Beispiel:

![bildschirmfoto 2019-02-16 um 22 54 16](https://user-images.githubusercontent.com/14169098/52905696-f5d0b380-323d-11e9-80a7-0a1a3ecc4b10.png)

Es ist sonst verwirrend, dass in der Facette zwei Möglichkeiten zur Auswahl sind, aber nur ein Datensatz da ist.

**Comment by jriedl** [comment]
Auf ptah integriert

**Comment by thefass** [comment]
funktioniert auf ptah
