### ISSUE TITLE
Fehlende Aufsätze IxTheo/RelBib

### ISSUE THREAD

**Issue by Gazeller** [ubtue/tuefind#532]
Aufsätze des Jg 2018 (Heft 1 und 2) der Zs. Nova Religio (ppn 113563531) werden weder in IxTheo noch in RelBib angezeigt.
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=superior_ppn%3A113563531&type=AllFields&filter[]=~mediatype%3A"Electronic"

**Comment by jriedl** [comment]
Welche PPNs fehlen denn?
https://relbib.de/Search/Results?lookfor=superior_ppn%3A113563531&type=AllFields&limit=100&sort=year+desc%2C+issue_sort+desc%2C+start_page+asc&botprotect=
und 
https://ixtheo.de/Search/Results?filter%5B%5D=%7Emediatype%3A%22Electronic%22&lookfor=superior_ppn%3A113563531&type=AllFields
scheinen jeweils Treffer für Heft 1+2 von 2018 zu liefern.
Die höhere Gesamttrefferanzahl aller untergeordneten Werke auf ptah scheint durch die Zusammenlegung übergeordneter Werke zu entstehen (hier auf ixtheo noch übergeordnete PPN: 066688779)

**Comment by Gazeller** [comment]
510521509
510521487
510521479
510521460
513912088
51391207X
513912061
513912053
513912045
513912037
513912029
513912010

**Comment by jriedl** [comment]
Habe jetzt Stichproben gemacht: die ersten drei finden sich an Position 24, 22 und 21, die letzte an Position 12. Ist eventuell noch eine andere Facette aktiv

**Comment by Gazeller** [comment]
Ich hatte den (voreingestellten) Filter "Neueste zuerst" eingestellt. Sonst nichts.

**Comment by jriedl** [comment]
"Neueste zuerst" ist ja die Sortierungsauswahl und filtert gar nicht. 
Sind die Treffer für 1,2,3 und letzte PPN in obiger Liste an den genannten Positionen bei folgender Suche;
https://relbib.de/Search/Results?lookfor=superior_ppn%3A113563531&type=AllFields&limit=100&sort=year+desc%2C+issue_sort+desc%2C+start_page+asc&botprotect=

**Comment by Gazeller** [comment]
nein, bei dieser Suche steht an erster Stelle "Jahrgang" 21 (2018), In dieser Zs. beginnt eine neue Zählung innerhalb eines Jahres. Wir sind inzwischen im Verbundkatalog bei Nr 22 (2018) und zwar schon mit dem 2. "Heft".

**Comment by jriedl** [comment]
Die Titel sind also da, das Problem bezieht sich auf die Sortierung. Diese erfolgt nach Jahr (936j) und Heftnummer (936e). Damit wird die Heftnummer 4 an den Anfang gestellt und die Heftnummer 2 unterhalb. Damit solche Fälle abgedeckt werden, muss nun offenbar noch 936d (Bandzählung) mit in die Auswertung integriert werden.

**Comment by Gazeller** [comment]
Heute ein ähnliches Problem. Die Zs hat Jahr, Jahrgang (annee) und eine völlig verschiedene Bandzählung. Hinzu kommt, dass die Katalogisierung der gedruckten Bände anders gehandhabt wurde, als jetzt die Einspielung über Zotero.
ppn Druck: 014784270
ppn Online 281246386

Mir liegt Band Nr 180 (année 62) octobre-decembre 2017 vor. Die Aufsätze werden ziemlich durcheinander in Relbib angezeigt:
![grafik](https://user-images.githubusercontent.com/16898788/53006712-077cab80-3436-11e9-9c26-c45b67738d01.png)

**Comment by jriedl** [comment]
Band (=936d) fließt jetzt als zweites Kriterium nach Jahr und vor Heft in die Sortierung ein.

**Comment by Gazeller** [comment]
Funktioniert jetzt!
