### ISSUE TITLE
RelBib Export PPNList

### ISSUE THREAD

**Issue by Gazeller** [ubtue/tuefind#533]
Bitte auch für Relbib den Export einer PPNList ermöglichen zur Stapelverarbeitung im DA3 (Sacherschließung) wichtig.

**Comment by mtrojan-ub** [comment]
Ist aktiviert + kann auf ptah getestet werden

**Comment by Gazeller** [comment]
funktioniert nicht. Habe id:27177388X eingegeben, die Zs. erscheint zwar aber ohne Bände/ Aufsätze; auch Layout merkwürdig falsch. In IxTheo funktioniert die Abfrage und Export relevanter Aufsätze normal.

**Comment by mtrojan-ub** [comment]
Hast Du's im alten oder im neuen Layout probiert? Im alten hats bei mir funktioniert, im neuen siehts komisch aus aber das ist ja noch nicht live. (Das schaue ich mir nochmal separat an). Falls es ein Problem im alten Layout gibt, kannst Du bitte einen Screenshot posten?

**Comment by Gazeller** [comment]
Sorry, auf ptah im alten layout tut's, das hatte ich gar nicht auf meinem "Radar" - nur RelBib alt und ptah im neuen Layout. - Es tut richtig!
