### ISSUE TITLE
Bibelstellensuche: 4 Esra 6,38–9,25 wird nicht gefunden

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#540]
4 Esra 6,38–9,25 wird im Modus Bibelstellensuche auf ptah nicht gefunden, obwohl es einen Titel gibt.

![bildschirmfoto 2019-02-24 um 22 58 31](https://user-images.githubusercontent.com/14169098/53305955-c77b5580-3887-11e9-80e1-e0e8affad79b.png)

Hier der Datensatz: https://ptah.ub.uni-tuebingen.de/Record/463476050

809 |   |   | \|a 68006038_68009025

**Comment by thefass** [comment]
wird jetzt doch gefunden, sowohl auf ptah als auch auf ixtheo:

![bildschirmfoto 2019-02-24 um 23 33 05](https://user-images.githubusercontent.com/14169098/53306374-a23d1600-388c-11e9-844b-fa43b3a074b1.png)

Kann mir aber nciht erklären, warum das oben nicht ging

**Comment by thefass** [comment]
Liegt am Bindestrich

mit einfachem Bindestrich - geht es
https://www.ixtheo.de/Search/Results?lookfor=4+esra+6%2C38-9%2C25&type=BibleRangeSearch&limit=20&sort=relevance%2C+year+desc&botprotect=

jedoch nicht mit dem Geviertstrich (oder ist das der Halbgeviertstrich?) –
https://www.ixtheo.de/Search/Results?lookfor=4+esra+6%2C38%E2%80%939%2C25&type=BibleRangeSearch&limit=20&sort=relevance%2C+year+desc&botprotect=

Das ist heimtückisch, da der Fehler durch unsere Darstellung produziert wird!
Ich hatte die Stelle aus diesem Katalogisat mit copy&paste übernommen:
https://www.ixtheo.de/Search/Results?lookfor=El+4+de+Esdras+y+el+Targum+Palestinense+%3A+la+tercera&type=AllFields&limit=20&sort=year+desc%2C+issue_sort+desc%2C+start_page+asc&botprotect=

**Comment by thefass** [comment]
Bin nicht sicher, wie wir das lösen sollen.
@ruschein : was meinst Du/Ihr?

Es gib ja alle möglichen waagerechten Striche und wir wissen nicht, wer was verwendet und in welchen Ländern welche Konventionen herrschen.

Am besten ist vielleicht, wir implementieren alle bei Wikipedia aufgeführten Striche:
https://de.wikipedia.org/wiki/Geviertstrich
Minuszeichen
Viertelgeviertstrich
Halbgeviertstrich
Geviertstrich
Doppelgeviertstrich
Bindestrich-Minus.

**Comment by ruschein** [comment]
@thefass Auf Ptah sollten jetzt so ziemlich alle Striche tun.

**Comment by thefass** [comment]
soweit ich das testen kann: funkioniert

Sicher gehen:
Geviertstrich
Halbgeviertstrich
Bindestrich-Minus
da ich das auf dem Mac eingeben kann
