### ISSUE TITLE
Bibelstellensuche: Desiderat 2

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#542]
Ermöglichung, gleichzeitg nach einer Bibelstelle und einem Schlagwort zu suchen.

Desiderat ist angeregt von unsererm Kooperationsparter BILDI ind Innsbruck, bei denen man eine solche kombinierte Suche machen konnte.

Beispiel:
Eine Suche nach Röm 15 und dem SW Ahnenkult würde diesen Titel finden (oder ganz nach oben ranken):
https://www.ixtheo.de/Record/466527217

**Comment by mtrojan-ub** [comment]
Ich sehe gerade, dass das Thema im Rahmem des IxTheo-Antrags 2021-2023 bearbeitet werden soll.

**Comment by thefass** [comment]
Ist umgesetzt, muss aber den Nutzern noch erklärt werden
