### ISSUE TITLE
Treffer pro Seite

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#543]
aufgrund eines Wunsches des neuen Kooperationspartners BILDI bitte die Treffer pro Seite anpassen:

![bildschirmfoto 2019-02-25 um 00 20 54](https://user-images.githubusercontent.com/14169098/53306933-75403180-3893-11e9-9d0b-5056be7a6722.png)

auch 500 sollen möglich sein

**Comment by ruschein** [comment]
Implementiert auf Ptah.

**Comment by thefass** [comment]
funktioniert
