### ISSUE TITLE
PPN-Konzept in K10plus

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#547]
Welche Auswirkungen das PPN-Konzept in K10plus hat, kann ich mangels tieferem Verständnis der Exportinformationen auf den Seiten https://wiki.k10plus.de/display/K10PLUS/Allgemeines+zur+Datenbereitstellung nicht ermessen.

Grundsätzlich gewinnen beim Match & Merge der Altdaten die GBV-PPNs in PICA-Feld 0100 = MARC 001, die SWB-PPNs werden zusätzlich in eigenen Feldern abgelegt.
Bei Neuerfassungen gibt es nur noch neue, gemeinsame PPNs in 0100 = 001:
![k10plus_ppns](https://user-images.githubusercontent.com/17004223/53400557-6c904e00-39ae-11e9-908b-1923f5e89a3b.JPG)

Wenn ich die Tabellen von der Seite https://wiki.k10plus.de/display/K10PLUS/Exportformate richtig verstehe, bleibt es im SWB-eigenen Feld für die SWB-PPNs bei MARC-Feld 001. Das interpretiere ich so, dass der SWB die GBV-PPNs gar nicht ausliefert!
Damit könnten wir bei der alten SWB-PPNs bleiben.

Bei Zusammenführung von Dubletten würde die alte SWB-PPN in PICA-Feld 2111 (MARC ?) landen, wenn der GBV-Satz gewinnt.

**Comment by ruschein** [comment]
@IxTheoKm Wir haben beschlossen die neuen PPNs in IxTheo und KrimDok zu verwenden.  Somit sind wir vermutlich zukunftssicher und es macht Recherchen einfacher.

**Comment by IxTheoKm** [comment]
Verständnisfrage:
Welche Unterscheidung gibt es, wenn alte und neue PPN im selben Feld 001 ausgeliefert werden?
Jeweils eigene Unterfelder?

**Comment by obrandt** [comment]
Liebe Frau Kellmeyer,

dazu gleich eine Frage: soll es nicht in den nächsten Jahren weiter ein Match & Merge geben? Wie würde dann eine Dokumentation erfolgen bei Mehrfachumlenkung? Sind die Felder wiederholbar?

Viele Grüße

Olaf Brandt

Von: IxTheoKm <notifications@github.com>
Gesendet: Dienstag, 26. Februar 2019 10:25
An: ubtue/tuefind <tuefind@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [ubtue/tuefind] PPN-Konzept in K10plus (#547)


Welche Auswirkungen das PPN-Konzept in K10plus hat, kann ich mangels tieferem Verständnis der Exportinformationen auf den Seiten https://wiki.k10plus.de/display/K10PLUS/Allgemeines+zur+Datenbereitstellung nicht ermessen.

Grundsätzlich gewinnen beim Match & Merge der Altdaten die GBV-PPNs in PICA-Feld 0100 = MARC 001, die SWB-PPNs werden zusätzlich in eigenen Feldern abgelegt.
Bei Neuerfassungen gibt es nur noch neue, gemeinsame PPNs in 0100 = 001:
[k10plus_ppns]<https://user-images.githubusercontent.com/17004223/53400557-6c904e00-39ae-11e9-908b-1923f5e89a3b.JPG>

Wenn ich die Tabellen von der Seite https://wiki.k10plus.de/display/K10PLUS/Exportformate richtig verstehe, bleibt es im SWB-eigenen Feld für die SWB-PPNs bei MARC-Feld 001. Das interpretiere ich so, dass der SWB die GBV-PPNs gar nicht ausliefert!
Damit könnten wir bei der alten SWB-PPNs bleiben.

Bei Zusammenführung von Dubletten würde die alte SWB-PPN in PICA-Feld 2111 (MARC ?) landen, wenn der GBV-Satz gewinnt.

**Comment by IxTheoKm** [comment]
Zur ersten Frage:
was die Verbünde an weiteren Match & Merges planen, und wie die ggf. funktionieren weiß ich nicht.

Zur zweiten Frage:
in der K10plus-Online-Dokumentation für Feld 0110 steht "wiederholbar: nein".

**Comment by ruschein** [comment]
Zu 001:


Soweit ich es verstehe gibt es zwei Modi:


1) Die bisherige PPN wird weiter in 001 ausgeliefert.  Ich weiß nicht mehr ob dann die neue PPN auch ausgeliefert wird.  Falls ja, jedenfalls nicht auch in einem 001-Feld.

2) Die neue PPN wird in 001 ausgeliefert, die alte PPN steht dann in in 035$a mit dem Präfix "(DE-576)".


Viele Grüße,

Johannes Ruscheinski

--
Dr. Johannes Ruscheinski
Universitätsbibliothek Tübingen - IT-Abteilung -
Wilhelmstr. 32, 72074 Tübingen

Tel: +49 7071 29-72820
FAX: +49 7071 29-5069
Email: johannes.ruscheinski@uni-tuebingen.de

 The Sophisticate:  "The world isn't black and white.  No one does pure good or pure bad. It's all gray.  Therefore, no one is better than anyone else."
    The Zetet:  "Knowing only gray, you conclude that all grays are the same shade.  You mock the simplicity of the two-color view, yet you replace it with a one-color view..."
      —Marc Stiegler, David's Sling


________________________________

**Comment by ruschein** [comment]
Eigentlich ist das hier kein Issue.
