### ISSUE TITLE
Fehlermeldung bei Feedback

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#548]
Nach dem Absenden eines Feedbacks kommt die Meldung "Es ist ein Fehler aufgetreten."
![grafik](https://user-images.githubusercontent.com/25769591/53401803-d0b41180-39b0-11e9-912c-d10f0f1e65a0.png)

**Comment by jriedl** [comment]
Scheint behoben.

**Comment by relhei** [comment]
Funktioniert wieder. Danke!
