### ISSUE TITLE
Suche mit Wildcard*

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#55]
Die Suche nach Diocese Pistoia brachte kein Ergebnis
![bildschirmfoto 2017-11-27 um 23 49 48](https://user-images.githubusercontent.com/14169098/33293632-c2d14488-d3cd-11e7-839e-80f42f200b72.png)

Wenn man dann auf den Vorschlag im Blauen Kästchen " Diocese Pistoia*" klickt, kommt eine Fehlermeldung:
![bildschirmfoto 2017-11-27 um 23 51 51](https://user-images.githubusercontent.com/14169098/33293705-ffd9af32-d3cd-11e7-9a06-ee122d0d8b59.png)

**Comment by jriedl** [comment]
Wildcard-Suchen funtkionieren jetzt

**Comment by thefass** [comment]
funktioniert
