### ISSUE TITLE
Abzugskriterien für IxTheo

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#552]
Bitte die Abzugskriterien auf der Seite https://github.com/ubtue/tuefind/wiki/Daten-Abzugskriterien vervollständigen:
auch 5056 6,22 wird ausgeliefert!
Nach der Migration der Daten aus Innsbruck kommen zudem drei weitere Kriterien hinzu.

Hier die Information aus dem BSZ vom 30.07.2018:
Folgende Kriterien sind maßgeblich:
•	5056 enthält 0 oder 1 oder 6,22 
	und Abrufzeichen mtex in Feld 0575 ist *nicht* vorhanden
•	0575 ist mit mteo belegt 
	und Abrufzeichen mtex in Feld 0575 ist *nicht* vorhanden
•	0575 ist mit BIIN, KALD oder GIRA belegt 
	und Abrufzeichen mtex in Feld 0575 ist *nicht* vorhanden

**Comment by thefass** [comment]
ist erledigt
