### ISSUE TITLE
DOIs funktionieren nicht

### ISSUE THREAD

**Issue by Gazeller** [ubtue/tuefind#553]
Ich weiß nicht ob es ein IT- oder Verbindungsproblem ist oder ob es etwas mit der Katalogisierung zu tun hat: Bei der Zs. "Implicit Religion" ppn: 256442428
funktioniert schon zum wiederholten Mal der Aufruf des DOI nicht.

https://doi.org/10.1558/imre.297727 
https://dx.doi.org/10.1558/imre.30063

**Comment by jriedl** [comment]
Die zugehörigen PPNs der obigen DOIs sind 501531041 und 501531025. Die Links werden aus 024$a generiert. Da sie bei anderen Artikeln der gleichen Zeitschrift auflösen, scheint es sich nicht um ein IT-Problem zu handeln, sondern offenbar um eine inkorrekte oder noch nicht aktive DOI.

**Comment by IxTheoKm** [comment]
Das kommt leider haufenweise vor. Eine Meldung der nicht funktionierenden DOIs über das Formular führt zu nichts. Es gibt nie eine Reaktion.
