### ISSUE TITLE
ppn Zuordung rätselhaft

### ISSUE THREAD

**Issue by Gazeller** [ubtue/tuefind#559]
Die Zeitschrift "Fieldwork in religions" wird in RelBib / IxTheo nur mit der ppn 454850530 gefunden. Diese aber ist lt. WinIBW die ppn für die Druckausgabe. Die ppn für die Onlineausgabe, an der alle Aufsätze hängen, lautet 325342784 - sie führt in Relbib und IxTheo zu einer Fehlermeldung.

**Comment by thefass** [comment]
das kann ich nicht reproduzieren:
selbst bei falscher Schreibweise (Schluss- s in religions) wird die Zeitschrift gefunden:
https://www.ixtheo.de/Search/Results?lookfor=Fieldwork+in+religions&type=AllFields&limit=20&sort=year+desc%2C+issue_sort+desc%2C+start_page+asc&botprotect=
Dann auf Medienart Zeitschrift einschränken.

**Comment by thefass** [comment]
Auch eine Suche nach id:3A325342784
funktioniert einwandfrei:

https://www.ixtheo.de/Search/Results?lookfor=id%3A325342784&type=AllFields&limit=20&sort=year+desc%2C+issue_sort+desc%2C+start_page+asc&botprotect=

**Comment by Gazeller** [comment]
Über den Titel finde ich die Zs in Relbib auch. Rätselhaft ist nur, dass ich sie auf Relbib-ptah nicht mit der ppn: 325342784 finde, obwohl dies die ppn für die elektronische Version ist. (Übrigens ist die hier von thefass mitgeteilte ppn "3A..." falsch).

**Comment by thefass** [comment]
Ja, das war ein copy&paste Fehler aus der URL, ist korrigiert

Auf RelBib und IxTheo wird die Suche nach id:325342784 gefunden, jedoch nicht auf den beiden Ptahs. warum?

**Comment by mtrojan-ub** [comment]
Es handelt sich um einen Datensatz der vom Merging betroffen ist. 
Sucht man statt "id:325342784" nach "ids:325342784" so erhält man auch auf ptah den korrekten Treffer.

**Comment by thefass** [comment]
gelöst
