### ISSUE TITLE
Eng. Übersetzung Körperschaft wird nicht gefunden

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#56]
Im Normdatensatz GND 1068043539 ( PPN  427199107) ist die ixTheo Übersetzung ins Englische in 710 (PICA 910) eingetragen: Diocese Pistoia
![bildschirmfoto 2017-11-28 um 00 00 27](https://user-images.githubusercontent.com/14169098/33294042-2eb11056-d3cf-11e7-8ad8-1aeea4417bb2.png)

Trotzdem wird eine Allgemeine Suche über  Diocese Pistoia nicht fündig:
![bildschirmfoto 2017-11-28 um 00 01 29](https://user-images.githubusercontent.com/14169098/33294081-57eb47ac-d3cf-11e7-9965-e279c9cf24cc.png)

Das ist seltsam, da die Datensätze ja da sind. Beispiel PPN 466030576:
![bildschirmfoto 2017-11-28 um 00 03 55](https://user-images.githubusercontent.com/14169098/33294216-ddafbd82-d3cf-11e7-9d1d-30e09e2284cb.png)

Seltsam ist auch, dass die englische Übersetzung von Diocese Pistoia nicht angezeigt wird, wenn man die englische Sprache im ixTheo ausgewählt hat.

**Comment by jriedl** [comment]
In diesem Normdatensatz steht "Diözese Pistoia" in Marc 110$b. In 110a steht "Katholische Kirche". Bisher wurde (abgesehen von Sonderregeln) für die Übersetzung die Strategie verfolgt, dass der jeweilige Ausgangsterm in 1X0a, die Synonyme in 4X0a und die Übersetzungen in 7X0a stehen. Lässt sich hier eine allgemeine Regel definieren, wie verfahren werden soll?

**Comment by thefass** [comment]
müssen wir abwarten, bis Frau Kellmeyer aus dem Urlaub zurück ist.

**Comment by IxTheoKm** [comment]
Bei untergeordneten Körperschaften wird die **übergeordnete** Körperschaft in **110 $a** abgelegt, die **untergeordnete**, unselbständige Körperschaft in **110 $b**.  Teilweise auch als Mehrfachunterordnung. Das kommt so auch in den IxTheo-Übersetzungen vor, die in Allegro in der alten SWD-Struktur erfasst waren (in den GND-Sätzen sieht man diese alte Struktur mit Schrägstrich in 913 $Sswd; in der neuen Struktur durch das Unterfeld $b ausgedrückt). 

Bsp.: 
001 213221268
110 1 $aIrland$bGárda Síochána
410 1 $aIrland$bCivic Guard
410 1 $aIrland$bJustizministerium$bGárda Síochána
551   $0(DE-576)20897170X$0(DE-588)4027667-3$aIrland$94:adue$wr$iUeberordnung
710 1 $aIreland$bGárda Síochána$2IxTheo$9L:eng$9Z:AF
710 1 $aIreland$bCivic Guard$2IxTheo$9L:eng$9Z:VW
913   $Sswd$ic$aIrland / Gárda Síochána$0(DE-588c)4514329-8

110 2 $aDeutsche Bischofskonferenz$bAusschuss für Ordensangelegenheiten
710 2 $aGerman Bishops' Conference$bCommittee for Religious Order Affairs$2IxTheo$9L:eng$9Z:AF
913   $Sswd$ik$aDeutsche Bischofskonferenz / Ausschuss für Ordensangelegenheiten$0(DE-588c)4439483-4

110 2 $aAccademia dei Concordi$bBibliothek
710 2 $aAccademia dei Concordi$9g:Rovigo$bLibrary$2IxTheo$9L:eng$9Z:AF
913   $Sswd$ic$aRovigo / Accademia dei Concordi / Bibliothek$0(DE-588c)4420440-1

110 2 $aKatholische Kirche$bDiözese Aachen$bDomkapitel
710 2 $aDiocese Aachen$bMetropolitan chapter$2IxTheo$9L:eng$9Z:AF
913   $Sswd$ic$aAachen <Diözese> / Domkapitel$0(DE-588c)4280625-2

Die Diözesen waren nach alter Regel _selbständig_ anzusetzende Geographica, keine Körperschaften (siehe 913 $Sswd: Pistoia <Diözese>). So wurde es auch im Allegro-IxTheo angelegt. (Die umgedrehte Form ohne Winkelklammer wurde bei der Migration im Hinblick auf die zukünftige RDA-Ansetzung maschinell erzeugt, jedoch nicht die Unterordnung!)

Da es parallel Körperschaftssätze nach alten und nach neuen Regeln mit jeweils unterschiedlichen Strukturen gibt und die englischen IxTheo-Übersetzungen auch in unterschiedlichen Strukturen vorliegen, kann man eine einheitliche Regel nicht definieren. 
Es ist eher Zufall, ob ein migrierter alter IxTheo-Satz auf einen GND-Satz nach neuen Regeln oder auf einen nach alten Regeln erfassten GND-Satz gestoßen ist. Auch die Angabe des Ortssitzes einer Körperschaft war nach alten Regeln anders als nach neuen Regeln (s. beim Beispiel "Accademia dei Concordi" den Ort Rovigo).
Diese Problematik hatte ich bei der Migrationsvorbereitung v.a. im Zusammenhang mit den Übersetzungen angekündigt.


Weitere willkürlich herausgegriffene Beispiele alter oder abweichender Strukturen zeigen, dass es nichts gibt, was es nicht gibt. Ich sehe keine Möglichkeit, etwas Einheitliches zu formulieren. 
Genau genommen ist die Bezeichnung für die Entität immer der _gesamte_ Eintrag 110 $a und $b zusammen.

110 2 $aSanta Maria la Real$bKloster
410 2 $aSanta Maria la Real$bGradefes
410 2 $aMonasterio de Santa Maria
410 2 $aMonasterio de Santa Maria la Real de Gradefes
410 2 $aMonasterio de Gradefes
410 2 $aZisterzienserinnenkloster
710 2 $aMonastery$9g:Gradefes$2IxTheo$9L:eng$9Z:AF
913   $Sswd$ic$aGradefes / Santa Maria la Real / Kloster$0(DE-588c)4577876-0

110 2 $aUniversität Luzern$bInstitut für Jüdisch-Christliche Forschung
410 2 $aInstitut für jüdisch-christliche Forschung an der Universität Luzern
410 2 $aIJCF$94:abku$wr$iAbkuerzung$eAbkuerzung
410 2 $aInstitut für Jüdisch-Christliche Forschung der Universität Luzern
410 2 $aInstitut für Jüdisch-Christliche Forschung$9g:Luzern
410 2 $aUniversität Luzern$bTheologische Fakultät$bInstitut für Jüdisch-Christliche Forschung
410 2 $aIJCF$9g:Institut für Jüdisch-Christliche Forschung
410 2 $aInstitut für Jüdisch-Christliche Forschung$9g:Universität Luzern
410 2 $aInstitut für jüdisch-christliche Forschung$9g:Luzern
410 2 $aTheologische Fakultät$9g:Luzern$bInstitut für Jüdisch-Christliche Forschung
710 2 $aInstitut für Jüdisch-Christliche Forschung$9g:Lucerne$2IxTheo$9L:eng$9Z:AF
913   $Sgkd$ia$aInstitut für Jüdisch-Christliche Forschung <Luzern>$0(DE-588b)10167373-5

110 2 $aKloster St. Klara$9g:Stans
410 2 $aKloster Sankt Klara$9g:Stans
410 2 $aKapuzinerinnen-Kloster St. Klara$9g:Stans
410 2 $aKapuzinerinnenkloster Sankt Klara$9g:Stans
410 2 $aSankt Klara$bKloster$94:nswd$wr$inswd$enswd
710 2 $aMonastery$9g:Stans$2IxTheo$9L:eng$9Z:AF
913   $Sgkd$ia$aKloster St. Klara <Stans>$0(DE-588b)10046927-9
913   $Sswd$ic$aStans / Sankt Klara / Kloster$0(DE-588c)4711880-5

110 2 $aUniversität Zürich$bVölkerkundemuseum
410 2 $aVölkerkundemuseum der Universität Zürich$94:nauv$wr$iUnveraenderte Form$eUnveraenderte Form
410 2 $aVölkerkundemuseum$9g:Zürich
410 2 $aUniversität Zürich$bEthnological Museum
410 2 $aEthnological Museum$9g:Zürich
410 2 $aUniversität Zürich$bEthnographic Museum
410 2 $aEthnographic Museum$9g:Zürich
410 2 $aMuseo etnografico$9g:Zürich
410 2 $aVMZ$94:abku$wr$iAbkuerzung$eAbkuerzung
410 2 $aUniversität Zürich$bInstitut für Sozialanthropologie und Empirische Kulturwissenschaft$bVölkerkundemuseum
710 2 $aVölkerkundemuseum$9g:Zürich$2IxTheo$9L:eng$9Z:AF
710 2 $aEthnological museum$9g:Zürich$2IxTheo$9L:eng$9Z:VW
913   $Sgkd$ia$aVölkerkundemuseum <Zürich>$0(DE-588b)1021685-6
913   $Sswd$ic$aZürich / Völkerkundemuseum Zürich$0(DE-588c)4196143-2

**Comment by ruschein** [comment]
@IxTheoKm Solange wir keine eindeutigen Regeln haben können wir nicht wirklich etwas tun.
