### ISSUE TITLE
VuFind 5.1 Test: abweichende Reihenfolge bei Neuzugängen

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#566]
Bei identischer Suche in "Neuzugänge: seit 7 Tagen" gibt es eine leicht abweichende Reihenfolge in der Trefferliste auf ptah und RelBib: 

https://134.2.67.9/Search/NewItem?range=7&submit=Suchen&botprotect=
https://relbib.de/Search/NewItem?range=7&submit=Suchen&botprotect=

**Comment by jriedl** [comment]
Auf ptah ist bereits die angepasste Form der Sortierung aktiv, in die zusätzlich der Band als Sekundärkriterium in die Sortierreihenfolge einfließt.

**Comment by relhei** [comment]
Alles klar. Vielen Dank!
