### ISSUE TITLE
Kodierung "04" für Link auf Inhaltsverzeichnis

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#568]
In mehreren Fällen erscheint statt "Inhaltsverzeichnis" als Link in der Titelanzeige "04". Das ist für die NutzerInnen natürlich wenig aussagekräftig.
Beispiel:
![grafik](https://user-images.githubusercontent.com/25769591/54276524-d6534f00-458d-11e9-8a66-6b9554dee96b.png)

Seltener gibt es die Kodierung "93", die anstelle des Wortes "Titelblatt" erscheint. Auch hier wäre eine Verbalisierung sicher nutzerfreundlicher.
Beispiel:
![grafik](https://user-images.githubusercontent.com/25769591/54276667-2af6ca00-458e-11e9-809f-d7c7c0625744.png)

**Comment by ruschein** [comment]
@relhei   Das liegt daran, dass in diesen Fällen in 856$3 "04" steht.  Da wo "Inhaltsverzeichnis" angezeigt wird steht "Inhaltsverzeichnis" in 856$3.

**Comment by relhei** [comment]
Ich hab mir fast gedacht, dass es ein Datenproblem ist...

**Comment by ruschein** [comment]
@relhei Es gibt 139658 Datensätze in Ixtheo in denen "Inhaltsverzeichnis" steht und 417 in denen entweder 04 steht oder "04 Inhaltsverzeichnis".  Das sind 0,3%.

**Comment by IxTheoKm** [comment]
Die Anzeige o.g. Beispiele verstehe ich nicht: 

im SWB steht bei Titel PPN 459219073:
856 42$uhttps://opus4.kobv.de/opus4-fau/frontdoor/index/index/docId/6729$yVolltext$zKostenfrei
856 42$qapplication/pdf$uhttp://d-nb.info/1078916047/04$3Inhaltsverzeichnis

Bei Titel PPN 348611064:
856 42$mDE-601$nBibl.ISILDE-601$qpdf/application$uhttp://www.gbv.de/dms/spk/iai/toc/65456230X.pdf$yInhaltsverzeichnis$zKostenfrei
856 42$mDE-576;DE-21$qapplication/pdf$uhttp://swbplus.bsz-bw.de/bsz348611064inh.htm$v20111209102109$3Inhaltsverzeichnis
856 42$mDE-601$nBibl.ISILDE-601$qimage/jpeg$uhttp://www.gbv.de/dms/spk/iai/cov/65456230X.jpg$3Cover

Evtl. wurde das inzwischen im SWB im Zuge der K10plus-Vorbereitungen bereinigt?

**Comment by IxTheoKm** [comment]
Hier sind die Codierungen gelistet:
http://www.dnb.de/SharedDocs/Downloads/DE/DNB/wir/agVerbundKataloganreicherungsobjekte2010.pdf?__blob=publicationFile

**Comment by ruschein** [comment]
Tut jetzt auf Ptah.  (Alte IxTheo PPNs kann man mit oldid:PPN finden.)

**Comment by IxTheoKm** [comment]
https://ptah.ub.uni-tuebingen.de/Record/1618884042
auf PTAH okay (**Datensatz fehlt im IxTheo/RelBib**).

https://ptah.ub.uni-tuebingen.de/Record/1612120652
auf PTAH okay (**Datensatz fehlt im IxTheo/RelBib**).

**Hier hat es nicht funktioniert:**

https://ptah.ub.uni-tuebingen.de/Record/65456230X#details
![93](https://user-images.githubusercontent.com/17004223/56949335-eb327480-6b32-11e9-9601-6bad3d4d2b0c.JPG)

**Comment by mtrojan-ub** [comment]
Der Link zu den Codierungen funktioniert nicht mehr, stattdessen:
http://swbtools.bsz-bw.de/cgi-bin/k10plushelp.pl?cmd=kat&val=4960&kattype=Standard#$3

**Comment by IxTheoKm** [comment]
Jetzt in Ordnung, vielen Dank (siehe auch https://github.com/ubtue/tuefind/issues/644)
