### ISSUE TITLE
Gesonderte Anzeige der gemergten Datensätze in Facette "Medienart"?

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#569]
Wäre es evt. sinnvoll (für NutzerInnen) bzw. möglich, die Facette "Medienart" zu erweitern um den Focus "Elektronisch/Nichtelektronisch"? Auf diese Weise könnte man die gemergten Datensätze getrennt anzeigen. Im Moment ist es ja so, dass sie dann sowohl unter "elektronisch" als auch "nichtelektronisch" erfasst werden und daher in ptah (RelBib) etwa 9700 Datensätze quasi doppelt in der Facette enthalten sind.
![grafik](https://user-images.githubusercontent.com/25769591/54277718-ea4c8000-4590-11e9-98ca-ffc7d1aa7f5d.png)

**Comment by thefass** [comment]
Vielleicht am ehesten durch eine dritte Variante elektronsich/nicht-elektronisch
Sollten wir diskutieren

**Comment by relhei** [comment]
Meeting Discussion hatte ergeben, dass keine dritte Facette eingeführt wird, sondern es so bleibt. Zumal das Merging ohnehin gerade ausgesetzt ist.
