### ISSUE TITLE
VuFind 5.1 Test: Schlagwortkette bei Thema Browsen nicht in Trefferliste angezeigt

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#571]
Auf ptah wird die im "Thema Browsen-Modus" ausgewählte Schlagwortkette bei den einzelnen Treffern in der Trefferliste nicht mehr gehighlighted angezeigt:
RelBib
https://relbib.de/Search/Results?lookfor=%22Absolutheitsanspruch%2FAtheismus%2FS%C3%A4kularismus%22&type=Keywordchains
Ptah
https://134.2.67.9/Search/Results?lookfor=%22Absolutheitsanspruch%2FAtheismus%2FS%C3%A4kularismus%22&type=Keywordchains

**Comment by jriedl** [comment]
In diesem Kontext macht das Treffer-Highlighting wenig Sinn, da es immer genau der Suchanfrage entspricht. Deshalb ist es nicht mehr aktiv.

**Comment by relhei** [comment]
Alles klar. Danke!

**Comment by relhei** [comment]
Gerade habe ich eine andere Suchanfrage nach einem Verfasser gestartet, dort wird aber in der Trefferliste noch gehighlightet. Warum hier?
https://134.2.67.9/Search/Results?lookfor=Langguth%2C+Gerd+1946-2013&type=Author&limit=20&botprotect=

**Comment by jriedl** [comment]
Es ist ja nicht grundsätzlich das Highlighting abgeschaltet, sondern nur im Kontext von "Datensätze ansehen" im "Thema browsen"-Modus, weil hier der Feldinhalt und die Suche auf jeden Fall zusammenpassen. Hier wurde offenbar eine Verfassersuche durchgeführt, da erscheint es schon sinnvoll, zu sehen, wieviel von einer freien Suche gepasst hat.

**Comment by relhei** [comment]
ok. Danke.
