### ISSUE TITLE
VuFind 5.1 Test: Problem bei Einschränkung nach Erscheinungsjahr

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#572]
Diese Problematik ist merkwürdigerweise nur bei ptah RelBib aufgetreten. 
Nach dem Auswählen einer Schlagwortkette in Thema Browsen wurde versucht, eine Einschränkung des Ergebnisses nach Erscheinungsjahr vorzunehmen. Obwohl in der Trefferliste die Jahrgänge enthalten waren, führte die Einschränkung zu keinem Ergebnis.

https://134.2.67.9/Search/Results?lookfor=%22Absolutheitsanspruch%2FAtheismus%2FS%C3%A4kularismus%22&type=Author&daterange%5B%5D=publishDate&publishDatefrom=2007&publishDateto=2008&botprotect=

**Comment by relhei** [comment]
Ich habe gesehen, woran es liegt. Aus einer vorhergehenden Suche ist noch die Feldeinschränkung "Verfasser" neben dem Suchschlitz übernommen worden. Daher ergibt sich vmtl. das leere Ergebnis. Ist das so vorgesehen, dass das einmal ausgewählte Feld dann so beibehalten wird für die weitere Suche? Oder wäre es sinnvoller, auf die "default"-Einstellung "Alle Felder" automatisch zurückzuspringen?

**Comment by thefass** [comment]
Es wird ja farblich hervorgehoben und verbal darauf hingewiesen, dass noch Suchfilter aktiv sind.
Wir (und die Nutzer vermutlich auch) übersehen das immer wieder mal.
Trotzdem sollten wir dabei bleiben, weil man ja oft auch eingeschränkte Suchen weiter einschränken will. 
![Bildschirmfoto 2019-03-13 um 14 39 34](https://user-images.githubusercontent.com/14169098/54283424-48339480-459e-11e9-8b68-4c2f6213fc98.png)

**Comment by relhei** [comment]
Stimmt, dann hat sich das wohl erledigt. Danke!
