### ISSUE TITLE
New Journal Alert anpassen

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#573]
- Unterscheidung Relbib / IxTheo im E-Mail-Template (Footer, E-Mail-Adresse)
- Nur Einträge auflisten deren Erstaufnahme < 2 Jahren erfolgt ist

**Comment by IxTheoKm** [comment]
Die Beantwortung meiner Frage nach einem Jahr hat sich wohl erledigt:
wenn wir beim Alert die Wiederaufnahme der nach 2014 abbestellten Zeitschriften berücksichtigen wollten, müssten wir jetzt ein 4-5-Jahresgrenze einrichten. Das macht m.E. keinen Sinn. 
Ich schließe darum.

Wenn jemand das anders sieht, kann er/sie ja wieder öffnen.
