### ISSUE TITLE
alphabetisch browsen

### ISSUE THREAD

**Issue by socheres** [ubtue/tuefind#575]
das Suchkriteium "Signatur" im Auswahlmenü  wird nicht DDC, sondern LCC (Library Congress Classification) ausgewertet. @oobenland kannst du bitte dies noch schnell ändern? https://ptah.ub.uni-tuebingen.de/Alphabrowse/Home?source=topic
![ddc_bug](https://cloud.githubusercontent.com/assets/1545743/13395037/717b467e-deec-11e5-9dc4-1c8d6d49ecb6.png)
![lcc](https://cloud.githubusercontent.com/assets/1545743/13395071/a9853b42-deec-11e5-8c33-ec36002d2df6.png)

**ERLEDIGT**

**Comment by IxTheoKm** [comment]
Hier werden verschiedene Aspekte behandelt. 
Ich drösle das in neue Issues auf.

**Comment by IxTheoKm** [comment]
Einzelprobleme jetzt als neue Issues angelegt, daher schließe ich hier.
