### ISSUE TITLE
Thema browsen: Sortierung?

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#576]
Es gibt offensichtlich (außer bei den Schlagwortfolgen?) keine Sortierung der Treffer.  
Groß- und Kleinschreibung wird dabei getrennt angezeigt und erhöht die Treffermenge/-seiten.
Bei häufig vorkommenden Begriffen und mehreren Trefferseiten kann die Suche mühsam werden.

Bsp.: catholic [die Tippfehler Chrurch, Curch, Chuch ... habe ich bereits korrigiert]
https://ixtheo-test.de/Keywordchainsearch/Results?lookfor=catholic&type=KeywordChainSearch
![thema browsen_3](https://user-images.githubusercontent.com/17004223/28778757-fb31085c-7600-11e7-96a4-af3474178a7f.png)

https://ixtheo-test.de/Keywordchainsearch/Results?lookfor=catholic&type=keywordChainSearch&page=46
![thema browsen_4](https://user-images.githubusercontent.com/17004223/28778929-a2d11386-7601-11e7-8ba2-54e456952d61.png)

Bsp.: divine
https://ixtheo-test.de/Keywordchainsearch/Results?lookfor=divine&type=KeywordChainSearch
https://ixtheo-test.de/Keywordchainsearch/Results?lookfor=divine&type=keywordChainSearch&page=2

![thema browsen](https://user-images.githubusercontent.com/17004223/28778204-a81f6e80-75fe-11e7-8213-84580650f01e.png)

Bsp.: reformation
https://ixtheo-test.de/Keywordchainsearch/Results?lookfor=reformation&type=keywordChainSearch
![thema browsen_2](https://user-images.githubusercontent.com/17004223/28778372-3e6b4490-75ff-11e7-85ce-15dc038b008c.png)

**Comment by IxTheoKm** [comment]
Ist schon etwas besprochen worden, was die Datei für die Normalisierung unterschiedlicher Schreibweisen betrifft?

Aktuelle Links auf PTAH:
https://ptah.ub.uni-tuebingen.de/Keywordchainsearch/Results?lookfor=catholic&type=KeywordChainSearch

https://ptah.ub.uni-tuebingen.de/Keywordchainsearch/Results?lookfor=reformation&type=KeywordChainSearch

https://ptah.ub.uni-tuebingen.de/Keywordchainsearch/Results?lookfor=divine&type=KeywordChainSearch

**Comment by thefass** [comment]
Falls verschiedene Formen für den gleichen Begriff unterschiedlich oft vorkommen, dann auf die häufigste Form vereinheitlichen. Ansonsten willkürlich eine der häufigsten Form verwenden

**Comment by ruschein** [comment]
@thefass Dein Vorschlag sollte jetzt auf Ptah implementiert sein.

**Comment by IxTheoKm** [comment]
Scheint noch nicht ganz zu funktionieren:
https://ptah.ub.uni-tuebingen.de/Keywordchainsearch/Results?lookfor=catholic&type=KeywordChainSearch&botprotect=

![browsen_catholics](https://user-images.githubusercontent.com/17004223/68853315-f9646e80-06d9-11ea-8453-ea33492c4052.JPG)

**Comment by IxTheoKm** [comment]
Diese Sortierung verstehe ich nicht:
https://ptah.ub.uni-tuebingen.de/Keywordchainsearch/Results?lookfor=katholisch&type=KeywordChainSearch&botprotect=

![grafik](https://user-images.githubusercontent.com/17004223/68853631-b48d0780-06da-11ea-92c1-135aa2f45b00.png)

**Comment by jriedl** [comment]
Nur bezüglich des letzten Kommentars zum Thema Sortierung: Beim "Thema browsen" erfolgt die Sortierung anhand eines Präfix-Matches, d.h. wieviele Buchstaben stimmen im Vergleich zum Suchterm am Anfang des Wortes überein. Insofern erscheint das Ergebnis doch plausibel.

**Comment by IxTheoKm** [comment]
Ich frage mich, ob es das ist, was ein Nutzer beim Browsen erwartet. Ich hätte eine alphabetische Sortierung (also nicht "k" nach "s") erwartet.

**Comment by jriedl** [comment]
Dieser Ansatz wurde damals so spezifiziert. Für eine alphabetische Sortierung existiert ja das "Alphabetische Browsen".

**Comment by IxTheoKm** [comment]
Danke. Dann macht hier wohl Wortanfangssuche mit Trunkierung Sinn.

**Comment by ruschein** [comment]
Auf Ptah.

**Comment by IxTheoKm** [comment]
"CATHOLICS" scheint noch nicht auf "Catholics" normalisiert zu sein:
in der Datei steht "Catholics|catholics->CATHOLICS"

https://ptah.ub.uni-tuebingen.de/Keywordchainsearch/Results?lookfor=catholic&type=keywordChainSearch&page=2
![browsen_catholics](https://user-images.githubusercontent.com/17004223/69231482-76379280-0b89-11ea-94f9-03bba4ac45fb.JPG)


Wenn ich den analogen Eintrag in der o.g.  Datei zu "catholic|CATHOLIC->Catholic" richtig verstehe, sind folgende Einträge in der Datei nicht korrekt und sollten gerade umgekehrt lauten:
"Catholic Church / Philippines->CATHOLIC Church / Philippines" muss heißen
"CATHOLIC Church / Philippines->Catholic Church / Philippines"

"Catholic Church history->CATHOLIC Church history"
"CATHOLIC Church history->Catholic Church history"

"Church" muss mit großem Anfangsbuchstaben geschrieben werden wie in den anderen Fällen:
"Catholic Church / Education / France / History / 19th century->Catholic **church** / Education / France / History / 19th century"
"Catholic Church / Japan / History->Catholic **church** / Japan / History"


Ebenso umgekehrt CONCEPTION:
"Conception / Religious aspects / Catholic Church->CONCEPTION / Religious aspects / Catholic Church"


Generell gibt es aber noch viele Begriffe, die nicht auf eine Schreibweise normalisiert sind:
![divine](https://user-images.githubusercontent.com/17004223/69231866-2efdd180-0b8a-11ea-9af8-08c5a4bfc00f.JPG)

**Comment by ruschein** [comment]
@IxTheoKm Das ist von Herrn Faßnacht so gewünscht.  Seine Idee war auf die häufigste Form zu normalisieren und das habe ich so implementiert.  Dadurch haben wir jetzt keine 3 sondern nur noch einen Eintrag.  Ist zwar nicht schön aber funktional eindeutig besser, denke ich.

**Comment by thefass** [comment]
Wir hatten entschieden, dass die Normalisierungen nicht von Hand eingetragen werden können, da es zuviele sind. Deswegen die Idee, auf die am meisten vorkommende Form zu normalisieren. 
Dass wir dadurch viele Kapitälchen haben ist unschön, aber trotzdem funktional besser als jeweils einzeln.

**Comment by thefass** [comment]
@ruschein Allerdings müßte doch foglendes nach der Logik auch zusammensein, oder?

![Bildschirmfoto 2019-11-20 um 14 55 35](https://user-images.githubusercontent.com/14169098/69245133-8b6eea00-0ba6-11ea-97f7-fcfbf2f11c5c.png)

**Comment by IxTheoKm** [comment]
Ich hatte es auch so verstanden, dass es dann nur noch eine Form geben sollte (dass ggf. die Kapitälchenform die häufigste sein kann, hatte ich übersehen).

**Comment by ruschein** [comment]
Ich vermute das Problem ist behoben.

**Comment by IxTheoKm** [comment]
Leider unverändertt:
https://ptah.ub.uni-tuebingen.de/Keywordchainsearch/Results?lookfor=catholic&type=KeywordChainSearch&botprotect=

![sortCath](https://user-images.githubusercontent.com/17004223/86889934-d8370f00-c0fc-11ea-8d0e-2fb57c973a90.JPG)

**Comment by ruschein** [comment]
Der eine Datensatz mit "Catholics" hat einen Punkt am Ende und wurde deswegen nicht normalisiert.  Das sollte morgen auf Ptah behoben sein.  Bei den Andern könnte dies auch der Fall sein.

**Comment by IxTheoKm** [comment]
Das kommt tatsächlich bei Einspielungen (Zotero, Online-Publikationen) vor. Aber nicht bei allen betr. Fällen. Ich teste morgen nochmal.

![sortPunkt](https://user-images.githubusercontent.com/17004223/86911332-73d77800-c11b-11ea-8aec-218d6c43b4df.JPG)

![sortPunkt2](https://user-images.githubusercontent.com/17004223/86911729-11cb4280-c11c-11ea-8eca-572b7c642beb.JPG)

**Comment by IxTheoKm** [comment]
Inzwischen funktioniert es, wenn der Eintrag nur aus einem Wort besteht - aber nicht immer.
Wenn er aus mehreren Wörtern besteht, bleibt der Zustand unverändert:

https://ptah.ub.uni-tuebingen.de/Keywordchainsearch/Results?lookfor=catholic&type=KeywordChainSearch&botprotect=
https://ptah.ub.uni-tuebingen.de/Keywordchainsearch/Results?lookfor=divine&type=KeywordChainSearch&botprotect=
https://ptah.ub.uni-tuebingen.de/Keywordchainsearch/Results?lookfor=%22divination%22

![sortCatho](https://user-images.githubusercontent.com/17004223/87046104-0437ba80-c1f9-11ea-992e-e7757509aef9.JPG)

![sortDivi](https://user-images.githubusercontent.com/17004223/87046120-0863d800-c1f9-11ea-87f4-afecf86b1ba1.JPG)

**Nach Klick auf "divination" kommt Folgendes:**

![sortDivi2](https://user-images.githubusercontent.com/17004223/87046132-0d288c00-c1f9-11ea-8ed7-4aa5a92146c2.JPG)

**Comment by jriedl** [comment]
Aktueller Stand auf ptah.

**Comment by IxTheoKm** [comment]
Die meisten Einträge sind jetzt okay. Ausreißer gibt es weiterhin:

https://ptah.ub.uni-tuebingen.de/Keywordchainsearch/Results?lookfor=catholic&type=keywordChainSearch&page=2
https://ptah.ub.uni-tuebingen.de/Keywordchainsearch/Results?page=4&lookfor=catholic&type=keywordChainSearch
https://ptah.ub.uni-tuebingen.de/Keywordchainsearch/Results?page=5&lookfor=catholic&type=keywordChainSearch

https://ptah.ub.uni-tuebingen.de/Keywordchainsearch/Results?page=3&lookfor=divine&type=keywordChainSearch

![divi](https://user-images.githubusercontent.com/17004223/155120452-bca50771-7b6b-4263-937d-c8bb648215a6.JPG)
![cath3](https://user-images.githubusercontent.com/17004223/155120459-d233fc9d-c0d2-495c-ad30-3948afbee775.JPG)
![cath2](https://user-images.githubusercontent.com/17004223/155120463-27a66cce-efa3-4c65-8977-7193975a0194.JPG)
![cath](https://user-images.githubusercontent.com/17004223/155120464-d7b797f7-2c00-4cab-9ee1-b0dc8515f75b.JPG)

**Comment by jriedl** [comment]
Das liegt z.T. daran, dass es sich um Schlagwörter in 653 handelt. Dier Ersetzungsroutine schließt das nun mit ein und es sollte nach dem nächsten Import auf ptah sichtbar ein. Weiterhin wurde die Ausgangsfacette `facet_topic_de`um 653a erweitert. Nach einem Neuimport kann dan noch einmal eine neue Mappingtabelle erstellt werden. Eine gewisse Unschärfe wird immer bleiben, da die Zuordnungsliste aufgrund des Ressourcenverbrauches bei der Erstellung statisch (d.h. nur zum Zeitpunkt der Erstellung wirklich aktuell) ist.

**Comment by IxTheoKm** [comment]
Im größten Teil der Fälle in Ordnung, danke. Ich schließe.
