### ISSUE TITLE
Verweisungsformen der Normdaten sind nicht recherchierbar

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#579]
Autorennamen oder Schlagwörter sind nur unter ihrer Vorzugsbenennung (100) recherchierbar.
Werden die Normdaten nicht geladen/ausgewertet?

Bsp.:
Ich finde nichts unter Ratzinger, Joseph, nur unter Benedikt.
Ich finde nichts unter Kaliningrad, nur unter Königsberg.
(Ausgenommen die aus Titelstichwörtern erzeugten Schlagwörter).

Wer die Vorzugsbenennungen nicht kennt, geht leer aus

**Comment by IxTheoKm** [comment]
Für den Fall "Briefleserin" (Werktitel mit 079 $v wit) habe ich ein neues Issue https://github.com/ubtue/tuefind/issues/887 aufgemacht.

Für die anderen Fälle folgen noch Kommentare.

**Comment by thefass** [comment]
Durch die vorgesehene Bereinigung in der FID Laufzeit 2024-2026 dürfte sich das Problem entschärfen.
Ich schließe das Issue und lege für den Problemfall Jakobsleiter ein neues an.
