### ISSUE TITLE
Anzeige beigefügter Werke

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#580]
"Beigefügte Werke" werden in 245 $b. wie ein Zusatz zum Sachtitel ausgeliefert:
245 …$a Haupttitel $b. Titel des enthaltenen Werks / Autor des enthaltenen Werks /$c Autor des Haupttitels (Vorlageform)

Bsp.
245 14$aDie Manipulation des Menschen aus medizinisch-naturwissenschaftlicher Sicht$b. Der Mensch als Projekt / Klaus Winkler /$cJorge Cervós-Navarro

Das führt dazu, dass der Autor des beigefügten Werks als Titelstichwort ausgewertet wird.
Bitte abweichend vom Zusatz zum Sachtitel (245 :$b) das beigefügte Werk (245 $b. ) nicht in der Kurztitelliste anzeigen.

In der Volltitelanzeige bitte in einer eigenen Zeile anzeigen (Vgl. SWB):
![beigefwerk](https://cloud.githubusercontent.com/assets/17004223/13174721/f39fdfbe-d705-11e5-867e-cc5e1b893781.jpg)

**Comment by mtrojan-ub** [comment]
Da es sich hier um einen alten Issue handelt: Ist dies immer noch so? 245b wird von VuFind selbst als Titelzusatz bzw. Untertitel verwendet und da müssten wir einiges überschreiben.

In der Volltitelanzeige gibt es bereits einen Abschnitt für "Enthaltene Werke" bzw. "Enclosed titles", der aus 249a und 505t befüllt wird. Soll das dann an dieser Stelle hinzugefügt werden? (bzw. sollte das im Deutschen in "Beigefügte Werke" umbenannt werden?)

**Comment by IxTheoKm** [comment]
"Enthaltene" und "beigefügte" Werke gibt es inzwischen nicht mehr (zumindest diese Terminologie). Statt dessen gibt es eine Vielzahl von _Titel**beziehungen**_, die in ganz unterschiedlichen PICA-Feldern stehen. 
Da muss ich erst schauen, in welchen MARC-Feldern sie transportiert werden, und wie ggf. die Altdaten aussehen.

**Comment by IxTheoKm** [comment]
Die Erfassungsform für den o.g. Fall eines beigefügten Werks hat sich mit K10plus geändert, so dass das Problem für diesen Fall nicht mehr existiert. 
Weitere Änderungen im Erfassungsformat muss ich noch prüfen. Falls es damit Probleme gibt, mache ich dafür eigene Issues auf.
