### ISSUE TITLE
Hilfethemen, FAQ

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#581]
Für "Weitere Suchoptionen" muss es unbedingt einen Hilfetext geben, der erklärt, welche Anwendungsmöglichkeiten bzw. Unterschiede es zwischen den drei Browsing-Funktionen gibt.
Ich finde es nicht selbsterklärend, wofür die jeweilige Funktion steht und welche Ergebnisse ich erwarten kann:
z.B.
1. "Katalog browsen", "Thema (Schlagwort)", ... usw.
2. "Thema browsen"
2. "Alphabetisch browsen", "Nach Thema"

**Comment by mtrojan-ub** [comment]
Dieser Issue wurde im heutigen FID-Meeting besprochen.

Im IxTheo gibt es bereits einen solchen Hilfstext, auf der Startseite rechts in der Kategorie "Browsen".
Im neuen RelBib-Layout gibt es eine separate Hilfeseite mit Erklärungen:
https://relbib.de/Content/browse

Das IxTheo-Layout wird ja ab September nochmal komplett überarbeitet. Die Kollegen wurden darauf hingewiesen und werden beim Einreichen der neuen Texte für die Überarbeitung auch wieder entsprechende Hilfstexte mit einreichen.
