### ISSUE TITLE
In Titeln enthaltene Bibelstellen nicht als Bibelstellen erfasst

### ISSUE THREAD

**Issue by Mannsperger** [ubtue/tuefind#582]
Der Titel mit der PPN 320729311 (https://ptah.ub.uni-tuebingen.de/Record/320729311) handelt auch von Ps 22,2 (und Mk 15,34). 
Die Bibelstellen kommen jedoch nur im Titel vor (Feld 245) und  Ps 22,2 und Mk 15,34 sind nicht als Bibelstellen erfasst (weder in WinIBW noch in Ptah)

**Comment by obrandt** [comment]
Es wird eine nach Bibelbüchern sortierte Liste erstellt, die intellektuell geprüft wird.

**Comment by IxTheoKm** [comment]
Projekt der Ergänzung von Bibelstellen ist angelaufen.

@thefass Wird das Verfahren / die Liste irgendwo dokumentiert, 
z.B. auf https://github.com/ubtue/tuefind/wiki/Bible-search ?

Wird regelmäßig - in welchen Abständen? - eine neue Liste erstellt?

**Comment by thefass** [comment]
Die Listen müssen noch erstellt werden. Wie wir das dokumentieren auch.
In WinIBW sind die entsprechen nacherschlossenen Titel aber recherchierbar:
fidtue ... bible

**Comment by mtrojan-ub** [comment]
Durch k10plus hat sich die PPN des Datensatzes geändert, siehe: https://ptah.ub.uni-tuebingen.de/Record/1390729311
Außerdem scheinen die Bibelstellen dort vorhanden zu sein (630):
![grafik](https://user-images.githubusercontent.com/26873381/158985144-abfac0e6-05b4-4f16-9b97-86f40ae5f06f.png)

Kann der Issue demnach geschlossen werden?

**Comment by IxTheoKm** [comment]
Dieses Issue ist ja schon historisch  ;-)
@thefass Das Bibelstellen-Ergänzungsprojekt (anhand der genannten Listen) ist m.W. abgeschlossen., daher kann es geschlossen werden.

**Comment by thefass** [comment]
ja, das Bibelstellen Nacherschließungsprojekt ist abgeschlossen
