### ISSUE TITLE
Verweisungen aus Hinweissätzen sind nicht recherchierbar 

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#585]
Neben dem Problem der nicht recherchierbaren Verweisungsformen #126 gibt es noch das spezielle RSWK-Problem, dass auch in allen anderen OPACs seit Jahren relevant ist:
Es gibt die sogenannten Hinweissätze mit Satztyp Tsv1e. Mit ihnen sind keine Titel verknüpft. Sie dienen lediglich dazu, darauf hinzuweisen, mit welchen Einzelschlagwörtern man recherchieren muss, wenn ein Kompositum als Schlagwort nicht zugelassen ist.

Beispiele: 

**Scharia**
verwendet wird "Islam" und "Recht"

**Papstreise**
verwendet wird "Papst" und "Pastoralreise"

**Blondine** 
verwendet werden die Einzelschlagwörter "Frau" und "Blondes Haar"

Unabhängig davon, wie man zu den o.g. Fällen stehen mag (bei Scharia wurde soeben eine Redaktionsanfrage für eine Änderung gestellt):
Die fett gedruckten Begriffe sind als Schlagwort nicht recherchierbar, weil diese Hinweissätze nicht ausgeliefert werden, da mit ihnen keine Titel verknüpft sind.

Sollten sie nicht irgendwie für den IxTheo einbezogen werden?
Derzeit gibt es knapp 4.700 Tsv1e-Sätze im SWB (wovon sicher etliche nicht für die IxTheo-Titel relevant sind, z.B. "Nickel-Titan-Legierung", "Milchzellgehalt", "Frankenwein" (oder doch für das Abendmahl?) ...

**Comment by jriedl** [comment]
Hinweissätze werden ausgewertet (vgl. Feld 960)

**Comment by IxTheoKm** [comment]
Geprüft, danke!
