### ISSUE TITLE
facetten überschrift und Trefferanzahl farblich hervorheben

### ISSUE THREAD

**Issue by socheres** [ubtue/tuefind#586]
ähnlich wie im Screenshot:

![facetten_css](https://cloud.githubusercontent.com/assets/1545743/18120977/9f0aec00-6f62-11e6-884b-52057df2c15d.PNG)

**Comment by mtrojan-ub** [comment]
... das sollten wir am besten mit anschauen wenn wir ab September das IxTheo-Layout überarbeiten

**Comment by mtrojan-ub** [comment]
Im Rahmen des folgenden Issues wurde heute besprochen, dass die Farbgebung der Trefferanzahl den RelBib- und KrimDok-Facetten von IxTheo übernommen werden soll: #1894

**Comment by mtrojan-ub** [comment]
Soll es neben den in #1894 definierten Anpassungen noch weitere Änderungen geben?
Falls nicht, würde ich dieses Issue schließen

**Comment by thefass** [comment]
nein, ich schließe deswegen
