### ISSUE TITLE
zwei Stichwörter für gleiches Themenfeld, unterschiedliche Treffer

### ISSUE THREAD

**Issue by Mannsperger** [ubtue/tuefind#587]
Browst man z.B. nach "Verfasser" -> "nach Thema" - erhält man z.B. "Kirchengeschichte" mit 1,974 Treffern und "Church history" mit 2,467 Treffern (https://www.ixtheo-test.de/Browse/Author?findby=topic&category=&query=%22Church+history%22&query_field=topic_facet&facet_field=authorStr). Auch über die englische Suche erhält man die gleichen Treffer "nach Thema" (https://www.ixtheo-test.de/Browse/Author?findby=topic&category=&query=%22Kirchengeschichte%22&query_field=topic_facet&facet_field=authorStr)
![doppeltkch](https://cloud.githubusercontent.com/assets/16759964/16145711/69312eb4-347a-11e6-8602-788f345df99f.png)

Deswegen wäre mein Vorschlag, die beiden Stichwörter zu einem Stichwort zusammenzufassen, wenn das geht, sodass dann jeweils in der passenden Sprache ein Stichwort mit allen damit verknüpften Treffern angezeigt wird (also deutsch: Kirchengeschichte, englisch: Church history).
Das würde m.E. die Suche etwas erleichtern. 
Auch bei anderen Stichwörtern gibt es eine solche Dopplung, .z.B. "Geschichte"(676 Treffer) und "History"(8,501 Treffer)

**Comment by mtrojan-ub** [comment]
Zur Erläuterung:

**Daten**
Manche Datensätze enthalten "Kirchengeschichte":
https://ptah.ub.uni-tuebingen.de/Record/1655813587

Manche Datensätze enthalten "Church History":
https://ptah.ub.uni-tuebingen.de/Record/1665987448#details

Manche Datensätze enthalten beides:
https://ptah.ub.uni-tuebingen.de/Record/1659170079

**Facettierung**
Wählt man sowohl Church History als auch Kirchengeschichte bei der Facette aus:
https://ptah.ub.uni-tuebingen.de/Search/Results?filter%5B%5D=topic_facet%3A%22Kirchengeschichte%22&filter%5B%5D=topic_facet%3A%22Church+history%22&type=AllFields

...so hängt die Anzahl der Ergebnisse davon ab, ob man "Deutsch" oder "English" als Oberflächensprache eingestellt hat.

Bei "English" erhält man genau 1 Treffer. Die Oberfläche weiß, dass alle Treffer mit "Kirchengeschichte" im Englischen in "Church history" übersetzt werden müssen. Lediglich bei 1 Datensatz funktioniert das nicht, da nicht "Kirchengeschichte" sondern "Kirchengeschichte." mit Punkt am Ende in den Daten steht und die Übersetzung fehlschlägt.

Bei "Deutsch" erhält man 201 Treffer. Da die Übersetzung "DE => EN" nicht auch in die Richtung "EN => DE" angewendet wird, sind sowohl Treffer mit "Church history" als auch mit "Kirchengeschichte" enthalten.

**Comment by thefass** [comment]
Das AP 1.2 der laufenden FID Periode 2021-2023 wird hier Abhilfe schaffen. Ich schließe deswegen
