### ISSUE TITLE
Sortierungsproblem 4

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#590]
Sonderzeichen werden mit sortiert. In alphabetisch nach Titeln sortierten Treffermengen stehen sie dadurch ganz am Ende des Alphabets:
Bsp.:
https://ixtheo-test.de/Author/Home?author=Benedikt+XVI.+Papst+1927-&type=Author&sort=title&page=125
https://ixtheo-test.de/Author/Home?author=Dierken%2C+J%C3%B6rg+1959-&type=Author&sort=title&page=3

**Comment by mtrojan-ub** [comment]
Tritt das Problem seit der letzten Änderung noch auf?

**Comment by IxTheoKm** [comment]
Jetzt in Ordnung, danke.

**Comment by IxTheoKm** [comment]
Ich muss mich korrigieren:
Scheinbar werden Zeichen nun z.T. doch wieder mitsortiert:
https://ptah.ub.uni-tuebingen.de/Search/Results?sort=title&type=AllFields&page=106039
https://ptah.ub.uni-tuebingen.de/Search/Results?sort=title&page=106038&type=AllFields

![Sortierung](https://user-images.githubusercontent.com/17004223/62623807-024ae480-b922-11e9-817d-8d903c0a9f0c.JPG)

**Comment by mtrojan-ub** [comment]
In der vorigen Änderung hatten wir für die Sortierung alle Zeichen entfernt, die nicht Teil folgender Unicode-Zeichenklassen waren (siehe https://en.wikipedia.org/wiki/Template:General_Category_(Unicode)):
* L (Letters)
* N (Numbers)

Wie sich herausgestellt hat, enthält L folgende Unterklassen:
* Lu (Letter, uppercase)
* Lu (Letter, lowercase)
* Lt (Letter, titlecase)
* Lm (Letter, modifier)
* Lo (Letter, other)

Stichproben haben ergeben, dass unter Anderem folgende Zeichen enthalten waren:
* ʻ - MODIFIER LETTER TURNED COMMA - https://www.fileformat.info/info/unicode/char/02bb/index.htm
* ʺ - MODIFIER LETTER DOUBLE PRIME - https://www.fileformat.info/info/unicode/char/02ba/index.htm

Beide sind Teil der Klasse Lm (Letter, modifier). Das sind also keine Anführungszeichen, sondern Zeichen die die Aussprache von Buchstaben verändern und daher eine Untermenge der Klasse L  sind.

Wir haben nun alle Zeichen der Kategorie Lm aus der Sortierlogik entfernt. Das Ergebnis müsste morgen auf ptah zu sehen sein.

**Comment by IxTheoKm** [comment]
Da ich diese Zeichen nicht gezielt suchen oder optisch voneinander unterscheiden kann, ist ein Test schwierig. 
Die nach Titel geordnete vollständige Trefferliste (von hinten her gesucht) hat aber m.E. korrekte Ergebnisse geliefert. Darum schließe ich.
