### ISSUE TITLE
TAD wird auch für Monographien ausgelöst

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#591]
Der _Aufsatz_dienst wird auch für _Monographien_ ohne Einzelbeiträge ausgelöst!
Bsp.:
https://ixtheo-test.de/Record/477255485
Formular des TAD: " Aus der Zeitschrift „Islam and cultural change in Papua New Guinea“ mit der Signatur „57 A 601“ ... "
Es handelt sich aber um eine Monographie ohne Einzelbeiträge!

Wenn überhaupt Monographien berücksichtigt werden sollen, dann nur diejenigen, die auch Aufsätze enthalten. Das ist allerdings nicht in jedem Fall eindeutig. 
- Festschriften und Kongressschriften sind i.d.R. Aufsatzsammlungen. 
- Zusätzlich diejenigen Monographien, die als Schlagwort oder "Art des Inhalts" den Begriff Aufsatzsammlung enthalten. 
- Zusätzlich diejenigen Monographien, mit denen Aufsätze verknüpft sind.

Bei allen anderen Monographien kann man m.E. den TAD nicht anbieten.

**Comment by thefass** [comment]
Alle problematischen Beispiele sind geklärt. Es gab auch lange keine Nutzerbeschwerden
