### ISSUE TITLE
Fehlermeldung bei Klick auf Rezensionen

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#596]
In dieser Zeitschriften-Titelanzeige gibt es einen Link auf Rezensionen. Bei Klick darauf erscheint eine Fehlermeldung:
https://134.2.67.9/Record/093981384#details
https://relbib.de/Record/093981368
Das Problem betrifft beide Systeme.

**Comment by thefass** [comment]
Das ist kein Systemfehler, sondern ein Katalogisierungsfehler. Die verlinkte Rezension ist nicht im Abzug enthalten, da der Titel kein Abrufzeichen hat (SSG Nummer fehlt). Das muss also nachkatalogisiert werden, sobald wir im K10plus arbeiten können

**Comment by jriedl** [comment]
In diesem konkreten Fall liegt das daran, dass die für die Rezension verlinkte PPN 413871096 (wird aus Feld MARC 787$w ermittelt), nicht Teil des IxTheo-Datenbestandes ist.

**Comment by thefass** [comment]
Da das öfter vorkommen könnte: Frage an @ruschein und @jriedl
Könnte eine Liste mit PPNs ausgegeben werden, die im Abzug fehlen und nachkatalogisiert werden müßten?

**Comment by jriedl** [comment]
Ja, dafür kann man ein Programm schreiben. Wir müssten nur die die konkret in Betracht kommenden Felder definiert. Für die Querverlinkungen zwischen Titeln ist das bereits durch Auswertung der Logs möglich.

**Comment by thefass** [comment]
Dann wäre eine Ausgabe als csv sinnvoll, in der die PPN des vorhandenen Titels und die PPN des fehlenden Titels vorhanden sind

**Comment by jriedl** [comment]
In den Dateien im Anhang finden sich die Referenzen, die sich aus w-Unterfeldern von 775,776,780,785 und 787 nicht haben auflösen lassen. Die zweite Datei wurde anhand der BSZ-Konkordanz für K10+ erstellt. Falls in der Konkordanz eine referenzierte PPN nicht abbildbar war, ist dies gekennzeichnet.
[dangling.log](https://github.com/ubtue/tuefind/files/2988514/dangling.log)
[dangling_k10plus.txt](https://github.com/ubtue/tuefind/files/2988518/dangling_k10plus.txt)

**Comment by ruschein** [comment]
@relhei Ich denke dieses Issue sollte man jetzt schließen.

**Comment by relhei** [comment]
Alles ok. Danke!
