### ISSUE TITLE
Einzelne Bände einer Schriftenreihe und Anzeige "In:"

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#598]
Der Reihenname wird bei der Volltitelanzeige eines einzelnen Bandes gleich in zwei Zeilen angezeigt. Klickt man auf den Link nach "In:", gelangt man zur Gesamtaufnahme. Bei Klick auf den Link nach "Schriftenreihe/Zeitschrift:", gelangt man zu einer Liste aller Bände dieser Reihe. Reicht in dem Fall nicht einfach die Zeile "Schriftenreihe/Zeitschrift" mit Link auf die Gesamtaufnahme? Von dort aus gelangt man ja auch auf die einzelnen Bände.
![grafik](https://user-images.githubusercontent.com/25769591/54602588-5708c400-4a42-11e9-8057-af8b09647c45.png)

**Comment by IxTheoKm** [comment]
Das liegt sicher daran, dass die übergeordnete Aufnahme im Fall von Stücktiteln in zwei Feldern erfasst wird: 830 = Verknüpfungsfeld mit Bandnummer, 490 = Vorlageform

**Comment by relhei** [comment]
Ok, alles klar. Damit kann man leben, es liegt ja kein Fehler vor.
