### ISSUE TITLE
K10plus_ptah: Verlinkung

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#610]
Wenn man bei einem Aufsatz in der Kurztitelliste auf die Gesamtaufname klickt, kommt eine Fehlermeldung
https://ptah.ub.uni-tuebingen.de/Search/Results?type=AllFields&filter%5B%5D=%7Eformat%3A%22Article%22
1. Aufsatz: Kirche im postsäkularen Kontext 
Klick auf: in: Stimmen der Zeit , 237.2019 = 144 (2019), 3, Seite 161-162

Ergebnis:
![Bildschirmfoto 2019-03-29 um 10 06 07](https://user-images.githubusercontent.com/14169098/55221675-4eff1000-520a-11e9-83fd-d5d116ed1d8b.png)

**Comment by thefass** [comment]
Wenn man dagegen auf den Link zur Gesamtaufnahme in der Volltitelanzeige klickt, wird das richtig aufgelöst
https://ptah.ub.uni-tuebingen.de/Record/1650714076

**Comment by IxTheoKm** [comment]
In der Kurzliste wird die SWB-PPN 014876671 gesucht, in der Volltitelanzeige die K10plus-PPN 12948590X

**Comment by ruschein** [comment]
Scheint jetzt zu tun.

**Comment by thefass** [comment]
funktioniert
