### ISSUE TITLE
K10plus_ptah: Verknüpfung zu Aufsätzen etc.

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#611]
In ptah fehlen:
Verknüpfung zu: "Bände / Aufsätze: | Bände / Aufsätze anzeigen."

Unvollständige Schlagwortfolgen in den kategorien:
normierte Schlagwort(-folgen): 
weitere Schlagwörter: 

Parallele Ausgabe: 

IxTheo: 
![Bildschirmfoto 2019-03-29 um 10 16 31](https://user-images.githubusercontent.com/14169098/55222267-c41f1500-520b-11e9-8bf5-c564f0855e59.png)

Ptah:
![Bildschirmfoto 2019-03-29 um 10 17 04](https://user-images.githubusercontent.com/14169098/55222313-e0bb4d00-520b-11e9-8343-4177cacacb4a.png)

Mit scheint. als kämen nur die normierten Schlagwörter nicht mit rüber.

**Comment by IxTheoKm** [comment]
Möglicherweise hängt das mit den geänderten PPNs zusammen?

**Comment by thefass** [comment]
funktioniert
