### ISSUE TITLE
K10plus_ptah: Sortierung der Treffer

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#612]
Sortierung der Gesamtdaten nach Verfasser ergibt merkwürdige Reihenfolge:
![K10plus_Sort](https://user-images.githubusercontent.com/17004223/55232841-fa1dc280-5226-11e9-87ba-2d54b9186052.JPG)

**Comment by ruschein** [comment]
Die Nachnamen sind:

[F]uente Lafuente
[M]endola
[R]ubinstein
[S]erique dos Santos

Sieht auf den ersten Blick korrekt aus oder habe ich da etwas übersehen?

**Comment by IxTheoKm** [comment]
Das ist richtig. Nur sind das die ersten 4 Treffer der gesamten über 2Mio Daten. Da fehlen mir die Autoren mit A, B, C  ... usw.

**Comment by IxTheoKm** [comment]
Ich glaube, ich habe die Ursache gefunden: 
bei "Fuente..." und "Mendola..." war z.B. ein überzähliges Leerzeichen vor dem Namen erfasst worden.

**Comment by IxTheoKm** [comment]
Die mit Leerzeichen erfassten Autoren sind nun in K10plus korrigiert. Für die anderen auf den ersten Blick unplausiblen Sortierungen gibt es eine andere Erklärung, die allerdings nicht nur auf ptah auftritt. Daher Lege ich ein neues Issue an.
