### ISSUE TITLE
k10plus_ptah: SWB-PPN ist nicht recherchierbar

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#613]
Ich kann weder mit id noch mit ids die SWB-PPN finden.
Bsp. Judaica
K10plus 130097241
SWB 015629856

**Comment by thefass** [comment]
id findet die neuen K10plus PPN
ids die Zwitter
für die alten SWB PPN müssten eine Möglichkeit geschaffen werden: zb.B. oldid

**Comment by ruschein** [comment]
Lieber Martin,


das oldid-Feld haben wir schon.  Leider wurde es aufgrund eines Bugs nicht befüllt.  Ich habe den Fehler behoben.  Sollte vermutlich morgen funktionieren.


Gruß,

Johannes

--
Dr. Johannes Ruscheinski
Universitätsbibliothek Tübingen - IT-Abteilung -
Wilhelmstr. 32, 72074 Tübingen

Tel: +49 7071 29-72820
FAX: +49 7071 29-5069
Email: johannes.ruscheinski@uni-tuebingen.de

 The Sophisticate:  "The world isn't black and white.  No one does pure good or pure bad. It's all gray.  Therefore, no one is better than anyone else."
    The Zetet:  "Knowing only gray, you conclude that all grays are the same shade.  You mock the simplicity of the two-color view, yet you replace it with a one-color view..."
      —Marc Stiegler, David's Sling


________________________________

**Comment by thefass** [comment]
funktioniert mit oldid:
