### ISSUE TITLE
k10plus_ptah: Interne Bemerkungen aus den Exemplardaten werden angezeigt

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#614]
Die PICA-Felder 4801 und 4802 wurden in K10plus untereinander ausgetauscht. D.h. bibliotheksinterne Vermerke stehen jetzt in 4802, benutzerrelevante Vermerke in 4801.

Bsp.:
 $0000 xxxxxcx a22 zn 4500
$0001 734393644
$0003 DE-576
$0004 015629856
$0005 20190225170533
$0008 130110||||||||||||||||ger|||||||
$0040 $aDE-Tue135$cDE-576$dDE-Tue135
$0092 $on$80
$0852 $aDE-Tue135
$0852 1$cFo XVIII 735$900
_$0866 $xzeittot ********** Zur KLASSIFIKATORISCHEN Sacherschließung an REL !!! **********_
$0935 $aixzg

Das interne Feld ist jetzt 4802=**0866** soll **nicht** angezeigt werden!

Ich finde keine aktuelle Konkordanz. Auf dem K10plus-Wiki ist eine Datei vom 26.10.2018 mit folgenden Angaben: Marc21 Tag 852
![K10plus_4801_4802](https://user-images.githubusercontent.com/17004223/55235680-694ae500-522e-11e9-8563-e3522aa3021e.JPG)

Daher weiß ich nicht, in welchem Marc-Feld die benutzerrelevanten Kommentare von jetzt 4801 transportiert werden.

**Comment by ruschein** [comment]
@IxTheoKm Was sollen wir tun und/oder was ist in der IxTheo-Instanz auf Ptah falsch?

**Comment by IxTheoKm** [comment]
Wie oben beschrieben:
Das interne Feld 4802=0 866 soll **nicht** angezeigt werden! Derzeit wird es auf Ptah angezeigt (siehe Beispiel unten).
Für 4801 weiß ich das Marc-Feld noch nicht, da die Formatdokumentation scheinbar nicht stimmt. Dieses Feld muss angezeigt werden. Sobald ich das Marc-Feld weiß, prüfe ich die Anzeige.


https://ptah.ub.uni-tuebingen.de/Record/130097241#details

**Comment by ruschein** [comment]
@IxTheoKm Wenn ich Fr. Katz richtig verstanden hatte sollte sich die Belegung der MARC-Felder nach der K10+ Unstellung nicht ändern.  D.h., das wäre dann ein Bug in den Exportroutinen des BSZs.  Schließlich können die nicht erwarten , dass dutzende Institutionen die Verarbeitung anpassen, oder?

**Comment by IxTheoKm** [comment]
Das dachte ich auch, aber Fakt ist, dass es jetzt auf Ptah angezeigt wird, im IxTheo aber nicht:
https://ixtheo.de/Record/015629856#details
In welchem Feld es da stand, kann ich also nicht sehen. Ich habe eine Mailbox an die ZRED geschrieben.

**Comment by ruschein** [comment]
@IxTheoKm Gibt es schon eine Rückmeldung?

**Comment by IxTheoKm** [comment]
Nein, noch nicht

**Comment by IxTheoKm** [comment]
Hier die Informationen: 

"...hat sich bei der Auslieferung von Feld 4801 und 4802 in den Marc-Feldern etwas geändert? Bei uns wird jetzt die interne Bemerkung von 4802 angezeigt. Das war vor K10plus nicht der Fall. In der Tabelle auf dem K10plus-Wiki steht für beides das MARC21-Feld 852. Ausgeliefert wird hier 4802 in Marc-Feld 866 (welches wäre 4801)? ************* Feld 4801 (externe Bemerkungen) geht nach 852 $z, Feld 4802 (interne Bemerkungen) nach 866 $x. Insofern hat sich nichts geändert. Allerdings war im SWB das Picaformat anders, 4801 waren die internen Bemerkungen und 4802 die externen. Das haben wir aber bei der Migration umgesetzt."

**Comment by ruschein** [comment]
@IxTheoKm  Können Sie bitte zwei Beispiele (PPNs) angeben wo das Falsche angezeigt wird, bzw. das Richtige nicht angezeit wird?

**Comment by ruschein** [comment]
@IxTheoKm Könnten Sie hier bitte PPNs von einem Datensatz bein dem die falschen Daten angezeigt werden sowohl also auch von einem Datensatz wo die richtigen Daten nicht angezeigt werden auf Ptah angeben?

**Comment by IxTheoKm** [comment]
Das Beispiel für die falsche Anzeige von internen Bemerkungen in 866 $x=PICA 4802 ist das oben genannte PPN **130097241** und **182229971**
https://ptah.ub.uni-tuebingen.de/Record/130097241#details
https://ixtheo.de/Record/130097241#details

https://ptah.ub.uni-tuebingen.de/Record/182229971#details
https://ixtheo.de/Record/182229971#details

Die richtigen Daten für Benutzer in 852 $z=PICA 4801 werden im Internformat korrekt angezeigt!
Bsp. PPN **1647000947** und **1612348858**
https://ptah.ub.uni-tuebingen.de/Record/1647000947#details
https://ixtheo.de/Record/1647000947#details

https://ptah.ub.uni-tuebingen.de/Record/1612348858#details
https://ixtheo.de/Record/1612348858#details

**Comment by IxTheoKm** [comment]
Hier das urspr. Issue für die "Nicht-Anzeige" von 866 $x auch im Internformat:
https://github.com/ubtue/tuefind/issues/403

**Comment by IxTheoKm** [comment]
Zur Ergänzung: die internen Angaben von Feld 866 haben nur Belang für die Bearbeitung in K10plus, nicht für den VuFind-Katalog. Daher sollen sie dort auch nicht im Internformat angezeigt werden, wo sie von Nutzern einsehbar wären

**Comment by IxTheoKm** [comment]
Warum wurde das Issue geschlossen?
Die internen Bemerkungen werden auf ptah immer noch angezeigt. Lt. altem Issue #403 war das bisher anders.

**Comment by IxTheoKm** [comment]
Wie besprochen.
Ich habe jetzt alle Bearbeiter darauf hingewiesen, dass dieses Feld ggf. nicht "intern", sondern für alle sichtbar ist.
