### ISSUE TITLE
k10plus_ptah: Anzeige bei Alphabetisch browsen

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#615]
Siehe Screenshots 1 und 2. Sieht normalerweise aus wie beim 3. Screenshot:

![K10plus_browse](https://user-images.githubusercontent.com/17004223/55236845-1de60600-5231-11e9-96aa-c59b0c411597.JPG)

![K10plus_browse2](https://user-images.githubusercontent.com/17004223/55236848-21798d00-5231-11e9-8bcb-aa4395c81c86.JPG)

![K10plus_browse3](https://user-images.githubusercontent.com/17004223/55236992-67365580-5231-11e9-8ba8-4349afdab610.JPG)

**Comment by jriedl** [comment]
Problem war offenbar, dass die für ein im europäischen Raum nicht genutztes LCC-Feld bei den K10-Plus-Daten jetzt Werte vorhanden sind. DA bei LCC die passenden Ergebnistitel ausgelesen, wurde hier die Ergebnismenge so groß, dass ein Timeout aufgetreten. Sollte nach einem Reimport in dieser Form nicht mehr auftauchen.

**Comment by IxTheoKm** [comment]
Jetzt in Ordnung, danke
