### ISSUE TITLE
k10plus_ptah: Neuzugänge

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#616]
Nach der Gesamtlieferung werden _alle_ Daten als Neuzugang deklariert:

https://ptah.ub.uni-tuebingen.de/Search/NewItem?range=7&submit=Suchen&botprotect=

**Comment by Gazeller** [comment]
Dasselbe bei RelBib, allerdings merkwürdigerweise mit einigen „Verlusten“:
Gesamttrefferzahl war heute morgen 436.912 // Bei Neuzugänge (egal welcher Zeitraum) sind es 434.063
Gaby

-----------------
Dr. Gabriele Zeller
Tel. 29-74030
Zi. H 228 - UB Hauptgebäude

Von: IxTheoKm <notifications@github.com>
Gesendet: Freitag, 29. März 2019 14:52
An: ubtue/tuefind <tuefind@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [ubtue/tuefind] k10plus_ptah: Neuzugänge (#616)


Nach der Gesamtlieferung werden alle Daten als Neuzugang deklariert:

https://ptah.ub.uni-tuebingen.de/Search/NewItem?range=7&submit=Suchen&botprotect=

**Comment by jriedl** [comment]
Mit Ausnahme einiger Tausend PPNs, deren alte PPN sich jetzt auch im neuen Datenbestand findet, werden die die K10+-PPNs als "neu" erkannt, da diese PPNs dem System vorher noch nicht bekannt waren. Zukünftig funktioniert das wieder wie gehabt.

**Comment by IxTheoKm** [comment]
Datenstand im IxTheo und ptah sind heute nahezu gleich:
IxTheo: 2.058.862
ptah: 2.058.864

Neuzugänge:
7 Tage:
IxTheo: **709** - ptah: **1.006**

14 Tage:
IxTheo: 31.965 - ptah: 5.889

30 Tage:
IxTheo: 31.965 - ptah: 2.050.836

60 Tage:
IxTheo: 200.833 - ptah: 2.051.726

Ich kann nicht interpretieren, ob das nun korrekt ist, oder nicht.

**Comment by jriedl** [comment]
Der Datenbestand bei den Neuerscheinungen ist nun auf ptah weitgehend identisch zu den Produktivsystemen.

**Comment by IxTheoKm** [comment]
Danke!
Für alle Datenbanken und Neuzugangszeiträume am 30.04.2019 geprüft. 
(In IxTheo und RelBib jeweils bei allen Abfragen 2 Treffer mehr als auf PTAH.)

PTAH: 
IxTheo  /  RelBib
2.059.019  /  457.118  [Gesamt]
200.529  /  40.436  [60 Tage]
32.363  /  12.291  [30 Tage]
32.363  /  12.291  [14 Tage]
1.115  /  388  [7 Tage]
