### ISSUE TITLE
K10plus_ptah: Doppelte Aufsätze

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#617]
Aufsätze sind fälschlicherweise doppelt in ptah:

https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=iapt.cs&type=AllFields&botprotect=

![Bildschirmfoto 2019-04-01 um 10 48 59](https://user-images.githubusercontent.com/14169098/55315185-18283480-546c-11e9-90cd-7b0de9b8bd86.png)

**Comment by jriedl** [comment]
Vermutlich Korrekturen im aktuellen Komplettabzug noch nicht enthalten.

**Comment by jriedl** [comment]
Auf ptah jetzt behoben, auf ub16 nach dem nächsten Import.

**Comment by thefass** [comment]
auf ptah in Ordnung
