### ISSUE TITLE
Suchanfrage per RSS feed abonnieren

### ISSUE THREAD

**Issue by Gazeller** [ubtue/tuefind#619]
Fehleranzeige
![grafik](https://user-images.githubusercontent.com/16898788/55336123-b0d6a880-549c-11e9-9cd3-978e255ae293.png)

Soll diese Möglichkeit weiterhin möglich sein?

**Comment by ruschein** [comment]
@mtrojan-ub Funktioniert sowohl auf IxTheo.de und Vufind.org.  Vermutlich haben wir da etwas falsch gemacht.

**Comment by mtrojan-ub** [comment]
wurde behoben, bitte nochmal testen

**Comment by IxTheoKm** [comment]
Funktioniert!
