### ISSUE TITLE
Suchproblem im IxTheo Browsing Modus

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#62]
Die Suche nach SW "İmam-Hatip Lisesi" ergibt zwei Treffer (Achtung: der erste buchstabe ist ein türkisches i mit irgendetwas drauf; am besten mit copy&paste verwenden):
https://ixtheo.de/Search/Results?lookfor=%C4%B0mam-Hatip+Lisesi&type=Subject&limit=20&sort=year+desc%2C+issue_sort+desc%2C+start_page+asc

Wenn man die Suche im keywordchainsearch macht, werden diese beiden Treffer auch angezeigt
![bildschirmfoto 2017-12-01 um 09 55 42](https://user-images.githubusercontent.com/14169098/33475197-da2fbe7c-d67d-11e7-92e6-919bcea9df49.png)

Wenn man dann jedoch auf view records klickt, findet er nichts:
![bildschirmfoto 2017-12-01 um 09 57 35](https://user-images.githubusercontent.com/14169098/33475263-1b719888-d67e-11e7-8b31-4b67fbb1c240.png)
![bildschirmfoto 2017-12-01 um 09 58 18](https://user-images.githubusercontent.com/14169098/33475293-337d99a4-d67e-11e7-98d4-431f3a323326.png)

Irgendwie ist seltsam, was er in den suchschlitz übernimmt

**Comment by jriedl** [comment]
Datensatz wird jetzt zurückgeliefert

**Comment by thefass** [comment]
fu ktioniert auf ptah
