### ISSUE TITLE
Anzeige von Konferenzen als erster Verfasser

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#620]
Sortierung der Gesamttitelmenge nach Verfasser:
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=&type=AllFields&limit=20&sort=author&botprotect=
(Treffer 1 bis 6 sind Falscherfassungen, die ich inzwischen korrigiert habe).

Ab Treffer 7 sind als Autoren _Konferenzen_ erfasst, die mit einem Sonderzeichen (z.B. Anführungszeichen) beginnen. Diese Konferenzautoren von Feld 111 werden in der Kurzliste nicht angezeigt. Statt dessen nur die sonstigen Körperschaften von Feld 710.

1. Die Sonderzeichen sollen nicht mit sortiert werden (siehe https://github.com/ubtue/tuefind/issues/590).

2. Wenn Konferenzen als 1. Verfasser in Feld 111 katalogisiert wurden, sollten sie in der Kurzliste wie eine Person (oder eine Körperschaft als 1. Verfasser = Feld 110) angezeigt werden, sonst sieht die Sortierung unplausibel aus.

![Autoren_Koerperschaften](https://user-images.githubusercontent.com/17004223/55334720-107f8480-549a-11e9-97e6-65746850adb2.JPG)

Beispiel:
PPN 847396940:
**111** 2 $a"Da heime in miner Pfarre". Identitätsbildung und Kulturtransfer im europäischen Niederkirchenwesen vor 1600$gVeranstaltung$d2007$cWolfenbüttel$jVerfasserIn$0(DE-588)112736393X$0(DE-627)881876992$0(DE-576)485207613$4aut

PPN 1555353797:
**111** 2 $a"..., dass ihr hingeht"$gVeranstaltung$d2016$cMeißen$jVerfasserIn$0(DE-588)1127668382$0(DE-627)882185772$0(DE-576)485353490$4aut
**710** 2 $aEvangelisch-Lutherische Landeskirche Sachsens$eVeranstalterIn$0(DE-588)2010043-7$0(DE-627)101678215$0(DE-576)191648809$4orm

**Comment by ruschein** [comment]
@mtrojan-ub Ist das jetzt behoben?

**Comment by mtrojan-ub** [comment]
@ruschein 
Teil 1) ist meines Wissens nach erledigt (Sortierung).
Teil 2) steht noch aus (Anpassung der Kurzliste)

**Comment by mtrojan-ub** [comment]
@IxTheoKm: Habe ich das richtig verstanden, dass statt 111 dann 710 in der Kurztitelliste angezeigt werden soll? 

z.B. im Fall von https://ptah.ub.uni-tuebingen.de/Record/898862906#details
dann 111a, was im Wesentlichen schon dem Titel selbst entspricht?

**Comment by IxTheoKm** [comment]
Genau umgekehrt:
111 ist der erste "Verfasser" und soll angezeigt werden. Nicht in jedem Fall entspricht der Name der Konferenz auch dem Titel.)
Jeweils analog zu Personen werden Körperschaften und Konferenzen behandelt:

**Personen:** 
**100 = 1. Verfasser** 
700 = Weitere Personen

**Körperschaften** (Beispiel: https://ptah.ub.uni-tuebingen.de/Record/1180231139#details):
**110 = 1. Verfasser**
711 = Weitere Körperschaft

**Konferenzen** (Beispiel: https://ptah.ub.uni-tuebingen.de/Record/861432738#details):
**111 = 1. Verfasser**
711 = Weitere Konferenz

**Comment by mtrojan-ub** [comment]
Die Änderung ist jetzt auf ptah, bitte nochmal testen.

https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=ids%3A847396940&type=AllFields&limit=20&sort=author
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=ids%3A1555353797&type=AllFields&limit=20&sort=author

**Comment by IxTheoKm** [comment]
Sieht jetzt in Ordnung aus, danke!

**Comment by IxTheoKm** [comment]
Ich muss mich leider korrigieren:
die vollständige Anzeige mit allen Unterfeldern von Veranstaltungen als Verfasser steht noch aus.
Da dies in einem anderen Issue thematisiert ist, schließe ich diesen hier trotzdem.

Vgl. https://github.com/ubtue/tuefind/issues/1030
