### ISSUE TITLE
k10plus_ptah: Einfache Suche - Alle Felder

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#621]
In der Volltextsuche bekomme ich unterschiedliche Ergebnisse bei der Abfrage für die monatliche Sacherschließungsstatistik. Auf Ptah werden offensichtlich auch Teile von Begriffen oder ähnliche Begriffe gefunden. Ist das so gewollt?
Wenn nicht, bitte den Zustand von IxTheo wiederherstellen.
Wenn ja, brauche ich ab Umstellung auf Ptah eine Alternative für die Statistik.

Beispiel: 
**fid1 -fid1p -fid1d**

https://ixtheo.de/Search/Results?lookfor=fid1+-fid1p+-fid1d&type=AllFields&botprotect=
103 Treffer

https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=fid1+-fid1p+-fid1d&type=AllFields&limit=20&sort=title&botprotect=
2294 Treffer

**fid1p**
https://ixtheo.de/Search/Results?lookfor=fid1p&type=AllFields&limit=20&sort=year+desc%2C+issue_sort+desc%2C+start_page+asc&botprotect=
375 Treffer

https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=fid1p&type=AllFields&limit=20&sort=title&botprotect=
1497 Treffer

**fid0**
https://ixtheo.de/Search/Results?lookfor=fid0&type=AllFields&limit=20&sort=year+desc%2C+issue_sort+desc%2C+start_page+asc&botprotect=
911 Treffer

https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=fid0&type=AllFields&limit=20&sort=title&botprotect=
2555 Treffer

usw.

**Comment by thefass** [comment]
Nein, das ist so nicht gewollt. bitte Zustand von ixTheo herstellen

**Comment by jriedl** [comment]
Das hängt damit zusammen, dass mit der neuen Solr-Version von VuFind 5 sich die sog. Analyzer (also der Teil, der beim Import und einer Abfrage den Text so umwandelt, wie dann tatsächlich Werte gespeichert und gesucht werden) verändert haben. Standardmäßig gilt eine Zahl innerhalb eines Wortes jetzt als Worttrenner, was in vielen Fällen ja auch sinnvoll ist. Es ist möglich, das falls gewünscht, zu deaktivieren. Als Workaround besteht die Möglichkeit, o.g. Suche mit Anführungszeichen auszuführen, also `"fid1" -"fid1p" -"fid1d"`, was dann dem ursprünglichen Verhalten ähnliche Ergebnisse liefert. Falls sich aber die relevanten Werte immer an definierten Stellen finden, wäre es eventuell sinnvoll, für diesen Anwendungsfall ein eigenes Feld anzulegen.

**Comment by jriedl** [comment]
Auf ptah wurde jetzt das splitOnNumeric deaktivert. Um die Abfrage auch im Hinblick auf mögliche spätere Änderungen stabiler zu machen, wurde weiterhin ein Feld `local_notes_1` eingefügt, das nur die Inhalte von 591$a enthält. Eine Abfrage ist im folgenden Format möglich: `local_notes_1:*fid1* AND NOT local_notes_1:*fid1p* AND NOT local_notes_1:*fid1d*`.

**Comment by IxTheoKm** [comment]
Danke, es funktioniert jetzt beides: 
Suche mit Anführungszeichen oder 
Suche mit local_notes_1.

Im ersten Fall ist offensichtlich Groß- und Kleinschreibung nicht relevant, im zweiten Fall schon.
Bsp.: 
"tuub19" oder "TUUB19" --> gleiche Treffermenge **53**
local_notes_1:\*tuub19\* --> keine Treffer
local_notes_1:\*TUUB19\* --> **54** Treffer

Lässt sich das bei local_notes_1 anpassen? Die meisten verwenden zwar Masken, aber theoretisch könnte auch jemand "FID1..." oder "tuub19" verwenden statt "fid1..." oder "TUUB19".

**Comment by IxTheoKm** [comment]
Weiteres Problem für diese Statistik-Anfrage:
Das Feld 591 $a wird in K10plus nicht mehr verwendet!
Es steht jetzt in PICA-Feld 5550 $A (MARC21 689) und wird offensichtlich gar nicht mehr ausgeliefert!
Beispiel:
https://ptah.ub.uni-tuebingen.de/Record/1662421591#details
Dort haben wir **5550 $A**DE-Tue135/19-**fid1d** erfasst.

Anfrage an ZRED läuft.

**Comment by ruschein** [comment]
@IxTheoKm Liebe Fr Kellmeyer, ist eine Antwort auf Ihre Anfrage erfolgt?  Falls nicht wäre sicher gut nochmals nachzufragen.

**Comment by IxTheoKm** [comment]
PICA-Feld 5550 $A (MARC21 689) und wird definitiv nicht ausgeliefert, aber die Recherche in der WinIBW ist möglich. Das bedeutet: aktuelle Erschließungsdaten muss ich dort abfragen.

Die bisherigen Daten, die in 591 $a erfasst wurden, bleiben aber dort stehen, so dass ich sie weiter im VuFind-Katalog recherchieren können muss. Das ist in der WinIBW (noch) nicht recherchierbar.

**Comment by ruschein** [comment]
@IxTheoKm Kann man dann diese Issue zumachen?

**Comment by IxTheoKm** [comment]
Wenn die Suche mit Anführungszeichen und local_notes_1 in der Groß- und Kleinschreibung angepasst ist, (das heißt: nicht relevant ist) dann ja. 
Da kam aber noch kein "ready for testing".

**Comment by IxTheoKm** [comment]
Bei der Recherche über "local_notes_1" sollte die Groß- und Kleinschreibung keine Rolle spielen, da die Erfassung möglicherweise variieren kann.
Bitte analog zur Suche in Anführungszeichen ausführen:

"tuub19" oder "TUUB19" --> gleiche Treffermenge 50
local_notes_1:*tuub19* --> keine Treffer
local_notes_1:*TUUB19* --> 50 Treffer

**Comment by jriedl** [comment]
Auf ptah integriert.

**Comment by IxTheoKm** [comment]
Perfekt, vielen Dank!
