### ISSUE TITLE
k10plus_ptah: TAD fehlt

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#622]
Trotz Login wird der TAD nicht angeboten:

https://ixtheo.de/Record/258315768
![TAD1](https://user-images.githubusercontent.com/17004223/55461933-f5c22280-55f5-11e9-9910-96b810e8ee6e.JPG)

https://ptah.ub.uni-tuebingen.de/Record/1661826466
![TAD2](https://user-images.githubusercontent.com/17004223/55461945-fc509a00-55f5-11e9-9de0-835b0e2eb470.JPG)

**Comment by jriedl** [comment]
Das hängt mit dem veränderten Leader zusammen. Als Kriterium für TAD wird abgeprüft, ob im Leader an Position 7 ein 'a' steht. Dies war in der Vergangenheit auch für Artikel der Fall, obwohl es laut Marc 21 Standard einen "Monographic component part" bezeichnet. Jetzt steht hier ein wohl standardkonformeres 'b' (="Serial component part"). Es sind ab jetzt beide Fälle zulässig.

**Comment by thefass** [comment]
das funktioniert

**Comment by thefass** [comment]
es kommt aber folgende, falsche Fehlermeldung:
![Bildschirmfoto 2019-04-03 um 19 31 15](https://user-images.githubusercontent.com/14169098/55499783-1b2b4c80-5647-11e9-8fcf-b72488eab571.png)

Liegt das an den PPN im Lokalsystem?

**Comment by jriedl** [comment]
Anfrage wegen TAD läuft.

**Comment by IxTheoKm** [comment]
TAD funktioniert wieder korrekt, danke
