### ISSUE TITLE
Französische Übersetzung Volltitelanzeige

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#624]
"In:" wurde nicht übersetzt in "dans" wie in der Kurztitelanzeige.
Bitte ergänzen.
![dans](https://user-images.githubusercontent.com/17004223/55618927-fdb9c800-5797-11e9-9e8a-2c448e6e8001.JPG)

**Comment by jriedl** [comment]
Auf ptah integriert.

**Comment by IxTheoKm** [comment]
Auf ptah jetzt o.k., danke
