### ISSUE TITLE
Falsche Trennung im keywordschainsearch

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#63]
Die Suche nach Ju/‘hoan (Normsatz PPN  211610925) wird falsch getrennt, da im Begriff ein / steht:

![bildschirmfoto 2017-12-01 um 11 10 56](https://user-images.githubusercontent.com/14169098/33478085-664e763c-d688-11e7-91fc-a2abc24f1664.png)

Natürlich findet er dann den Datensatz nicht

**Comment by jriedl** [comment]
'/' in Schlagworten werden jetzt so escaped und behandelt, dass z.B. https://ptah.ub.uni-tuebingen.de/Record/465755232 beim Thema-Browsen die Schlagwortfolge erhalten und somit der zugehörige Datensatz gefunden wird.

**Comment by IxTheoKm** [comment]
Ist es Absicht, dass der Backslash mit angezeigt wird?
Bei Thema browsen wird man fündig mit Ju'hoan, bei Alphabetisch browsen, nach Thema nicht (weder mit noch ohne Apostroph im Begriff)

![juhoan](https://user-images.githubusercontent.com/17004223/35338191-8cf75564-011d-11e8-8ce5-a5bcebcecb04.png)

![juhoan2](https://user-images.githubusercontent.com/17004223/35338193-8f27debc-011d-11e8-8941-858a856b9fa6.png)

![juhoan3](https://user-images.githubusercontent.com/17004223/35338202-9164b0d8-011d-11e8-999f-3536eb4d76aa.png)

**Comment by jriedl** [comment]
Ja, der Backslash soll mitangezeigt werden. Da der Slash als Trenner der Schlagwortfolgen definiert ist, benötigt er eine Sonderbehandlung.

**Comment by jriedl** [comment]
Das alphabetische Browsen wurde bisher immer in der VuFind-Standardkonfiguration betrieben. Die Anpassungen bezogen sich ausschließlich auf die Codebasis, um innerhalb von RelBib keine leeren Treffer zu erhalten. Um hier in Zukunft eine bessere Abdeckung erhalten, wird in Zukunft nicht mehr das topic-Feld, sondern an die Zeit-, Region-, Genre- und Thema-Facette einfließen.

**Comment by thefass** [comment]
Finden und Anzeigen funktioniert!

Verwirrend ist allerdings tatsächlich die Kombination von Backslash und Slash, was bei mir wie ein großes V aussieht.

![bildschirmfoto 2018-06-04 um 15 16 31](https://user-images.githubusercontent.com/14169098/40919626-538e5350-680a-11e8-858a-ad3b273d843f.png)

Könnte das in Thema browsen nicht so angezeigt werden wie im Titeldatensatz, wo der Slash auch nicht das eigentliche Wort trennt, trotzdem aber in der Anzeige kein Backslash erforederlich ist?

https://ixtheo.de/Record/388111267

![bildschirmfoto 2018-06-04 um 15 16 08](https://user-images.githubusercontent.com/14169098/40919696-852ef928-680a-11e8-9f8a-060853be3f8a.png)

**Comment by jriedl** [comment]
Auf ptah angepasst: Der Backslash wird bei der Anzeige jetzt unterdrückt. Bei Einfügen durch Klicken wird er automatisch mit eingefügt. Bei manueller Eingabe muss er beachtet werden.

**Comment by thefass** [comment]
funktionert
