### ISSUE TITLE
Bug beim Export von mehr als 200 Treffern

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#638]
Rückmeldung aus Louvain:
es gibt jetzt die Möglichkeit, bis zu 500 Treffer anzuzeigen bzw. zu exportieren. Bei Anzeige bis zu 200 Treffern funktioniert das auch. Bei 500 Treffern kommt nach Auswahl von "Export" folgende Anzeige:
![IxTheo_Export](https://user-images.githubusercontent.com/17004223/56564516-7a2d1300-65ae-11e9-8e63-33083feeb3f3.JPG)

**Comment by mtrojan-ub** [comment]
Das Problem ist behoben, bitte kurz Ausprobieren ob's jetzt funktioniert.

Bis zu 499 Treffern funktionierte es noch. (Also wenn man 500 eingestellt hat, manuell eins wieder abgewählt hat und dann auf Export geklickt hat, konnte man einen Export durchführen).

Konkret war es kein Problem in VuFind selbst, sondern in der PHP-Konfiguration auf dem Server. Der Wert für `max_input_vars` musste erhöht werden. In der VuFind-Konfiguration wurde nicht darauf hingewiesen dass man beim Hochsetzen des Limits auch diese Einstellung anpassen muss. Wir haben das jetzt als Feedback an die VuFind-Mailingliste geschrieben.

siehe auch: https://sourceforge.net/p/vufind/mailman/message/36647134/

**Comment by IxTheoKm** [comment]
Jetzt kommt folgende Meldung:
"Request-URI Too Long
The requested URL's length exceeds the capacity limit for this server."

**Comment by mtrojan-ub** [comment]
Das gilt aber nur für den Refworks-Export, richtig?

Dort wird ja eine externe Seite aufgerufen. Die lange URL kommt davon, dass dort mehr IDs als bisher enthalten sind. Scheint so als ob man für Refworks kleinere Gruppen von IDs verwenden muss.

Bei z.B. 200 erhalte ich eine andere Fehlermeldung
=> The request filtering module is configured to deny a request where the query string is too long.

Bei z.B. 50 kommt jedoch die Frage
=> In welche Version von RefWorks möchten Sie gerne exportieren?

**Comment by IxTheoKm** [comment]
Ich hatte RIS und PPN-Liste getestet. Bei beiden kam dieselbe Meldung.
EndNote habe ich jetzt auch getestet: 
"Request URL Too Long
HTTP Error 414. The request URL is too long."

**Comment by mtrojan-ub** [comment]
Ah stimmt! Allerdings erst beim Klicken auf "Datei herunterladen"

![grafik](https://user-images.githubusercontent.com/26873381/56583221-62b74f80-65d9-11e9-9979-7b4512060db1.png)

Es hat sich herausgestellt dass wir auch in unserem Apache Web Server noch die Einstellung `LimitRequestLine` von der Voreinstellung 8190 auf einen höheren Wert setzen mussten.

Bitte nochmal ausprobieren! (außer bei Refworks, da können wir auf unserer Seite vermutlich nichts machen)

**Comment by IxTheoKm** [comment]
Danke, funktioniert jetzt bei den RIS, EndNote und PPN-Liste.

**Comment by thefass** [comment]
Email Versand geht zwar, allerdings sind nur die ersten 35 Titel als Link ausgewiesen, der Rest nicht.

![Bildschirmfoto 2019-04-25 um 00 57 14](https://user-images.githubusercontent.com/14169098/56699293-3c86d200-66f5-11e9-82e4-5730dcb43777.png)

**Comment by thefass** [comment]
Export nach RIS funktioniert ab 100 Titel nicht (EndNote und PPN List funktionieren, RefWorks ist eigenes Problem)

Es kommt folgende Fehlermeldung:
![Bildschirmfoto 2019-04-25 um 01 15 51](https://user-images.githubusercontent.com/14169098/56699896-cb94e980-66f7-11e9-9413-5cc1e0e0d9ed.png)

**Comment by mtrojan-ub** [comment]
@thefass:
Der Hyperlink wird von VuFind korrekt generiert und versendet. Das Problem kommt daher, dass in E-Mails laut Standard max 1000 (bzw. 998) Zeichen pro Zeile erlaubt sind.
siehe auch: https://www.ietf.org/rfc/rfc2822.txt (Abschnitt 2.1.1)

Wenn ich manuell eine E-Mail mit mehr Zeichen pro Zeile an meine eigene Uni-Tuebingen Adresse schicke dann klappt das zwar, aber wenn die Mail zwischen verschiedenen Mailservern durchgereicht wird (z.B. Postfix-Server mit Standard-Konfiguration) dann kann nicht garantiert werden dass die Mail auch so ankommt wie sie abgesendet wurde. 

In Deinem Beispiel sind alle benötigten Zeichen da, aber einer der Mailserver in der Zustellungskette hat automatisch Zeilenumbrüche eingefügt um dem Limit-Problem vorzubeugen. Selbst wenn wir unsere internen Mailserver alle auf höhere Limits einstellen würden, wäre also nicht sichergestellt dass Benutzer am anderen Ende des Internets den korrekten Link angezeigt bekommen.

Wenn man aber manuell die Zeilenumbrüche und Leerzeichen rausmacht, dann geht's.

Momentan wüssten wir also nicht wie wir das umgehen sollten, aber wir schreiben es mal auf die VuFind-Mailingliste.

**Comment by mtrojan-ub** [comment]
Das RIS-Export-Problem ist vermutlich kein Problem des Exports, sondern ein Datenproblem.

Leere Suche mit 200 Treffer pro Seite (neueste zuerst) exportieren nach RIS + runterladen
- Seite 1: Fehler, laut Log-Datei existiert eine PPN nicht die als übergeordnetes Werk bei mindestens einem Datensatz vorhanden war
- Seite 6: funktioniert problemlos

Beispiel-Datensatz: https://ixtheo.de/Record/1663280606
Übergeordnetes Werk lässt sich nicht öffnen (Theologische Quartalschrift, 129497029)

**Comment by mtrojan-ub** [comment]
- Das Datenproblem ist behoben (siehe #649), somit funktioniert auch der RIS Export wieder
- Für das E-Mail-Problem könnte z.B. auch ein "Link Shortener" erstellt werden. Laut der VuFind-Mailingliste wäre das auch als allgemeines Feature sinnvoll: https://sourceforge.net/p/vufind/mailman/message/36650519/

**Comment by mtrojan-ub** [comment]
Wir arbeiten bereits an einem Link Shortener, der voraussichtlich auch offiziell in VuFind 6 einfließen wird.

**Comment by mtrojan-ub** [comment]
Der Link Shortener ist offizieller Teil der 6.0 geworden.
siehe: https://vufind.org/wiki/changelog

**Comment by mtrojan-ub** [comment]
Mittlerweile sind wir auf VuFind 6.0.1 und der URL Shortener ist aktiv, d.h. es werden jetzt auch kurze Hyperlinks in den E-Mails versendet.

=> Bitte nochmal testen!

**Comment by IxTheoKm** [comment]
Ich habe willkürlich 500 Treffer zum Export ausgewählt:
https://ptah.ub.uni-tuebingen.de/Search/Results?limit=500&filter%5B%5D=%7Edewey-hundreds%3A%22500+-+Science%22&type=AllFields

RefWorks funktioniert nicht:
Request URL Too Long
HTTP Error 414. The request URL is too long.

Beim Versenden der Mail werden jetzt keine Links zu den Treffern geschickt (s. oben Kommentar 25. Apr.) sondern ein Link zur Suche. Ist das so gewollt?
Link im IxTheo: <https://ptah.ub.uni-tuebingen.de/short/J>

**Comment by mtrojan-ub** [comment]
Ich habe eben die Mechanik der Weiterleitung umgestellt, da wir auf ptah Probleme mit php-fpm unter CentOS 8 hatten. Es wird jetzt kurz eine Weiterleitungsseite angezeigt:

![grafik](https://user-images.githubusercontent.com/26873381/72054443-48d5ae00-32c9-11ea-984f-b9898d4b0210.png)

Was den Inhalt bzw. das Ziel angeht: Also bei mir ist es ein Link zu den Treffern (ohne Suchfeld):

![grafik](https://user-images.githubusercontent.com/26873381/72054333-162bb580-32c9-11ea-8d87-27c027941548.png)

Für RefWorks glaube ich dass man statt des Callback-Verfahrens ein Form Post-Verfahren verwenden muss, aber um das zu testen brauche ich Zugangsdaten (siehe Rundmail).

Siehe auch: http://www.refworks.com/directexport.htm

**Comment by mtrojan-ub** [comment]
Heute im Meeting besprochen: @AleAprile organisiert einen Testzugang.

**Comment by AleAprile** [comment]
Über das Kontaktformular von Refworks habe ich meine Anfrage gestellt. Hoffentlich bekommen wir bald eine positive Rückmeldung.

**Comment by mtrojan-ub** [comment]
Die Anpassung für RefWorks ist auf ptah aktiv, ich setze es wieder auf "ready for testing"

**Comment by AleAprile** [comment]
Bis dato habe ich noch keine Rückmeldung von Refworks erhalten, obwohl ich inzwischen auch die für den Südwesten zuständige Mitarbeiterin angeschrieben habe.

**Comment by mtrojan-ub** [comment]
In der Zwischenzeit wurde mir eine E-Mail mit einem Link auf diese Webseite weitergeleitet:
https://www.refworks.com/content/path_benefit/trial_request.asp

Dort kann man sich angeblich selbst einen Testaccount erstellen. Ich werde das ausprobieren und melde mich wieder.

**Comment by mtrojan-ub** [comment]
Das Formular zum Registrieren eines Testaccounts auf der RefWorks-Seite kann sowohl in Firefox als auch in Chrome nicht benutzt werdeen. Laut JavaScript-Console gibt es Fehler bei der Einbindung von Google ReCaptcha.

Firefox:
![grafik](https://user-images.githubusercontent.com/26873381/74716923-bb726b80-522f-11ea-8ac2-ddddb42fb73d.png)

Chrome:
![grafik](https://user-images.githubusercontent.com/26873381/74716984-d6dd7680-522f-11ea-9a2b-99153acc6040.png)

**Comment by mtrojan-ub** [comment]
Die Anpassung von ptah ist am Montag live gegangen.

@IxTheoKm: Lässt sich der von Ihnen am 9.12. beschriebene Fehler mit RefWorks aktuell noch reproduzieren?

**Comment by IxTheoKm** [comment]
Ich bekomme schon bei "Export" dieses Bild:
![export](https://user-images.githubusercontent.com/17004223/74948791-11e0d500-53fd-11ea-8c0c-c7f9d6cec0d2.JPG)

**Comment by mtrojan-ub** [comment]
Das kann ich aktuell nicht reproduzieren. Falls es auftritt hat es bestimmt wieder etwas mit einem fehlenden übergeordneten Werk zu tun.

**Comment by IxTheoKm** [comment]
Es tritt immer noch auf, z.B. bei 

https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=superior_ppn%3A497677458&type=AllFields

https://ptah.ub.uni-tuebingen.de/Search/Results?limit=500&filter%5B%5D=%7Edewey-hundreds%3A%22500+-+Science%22&type=AllFields

https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=superior_ppn%3A268128154&type=AllFields

...

Es gelingt mir nicht, bei Auswahl von 500 Treffern, zum Export zu kommen.

**Comment by mtrojan-ub** [comment]
Auf ptah wurde ein Problem mit der PHP-Konfiguration festgestellt:

`[Mon Mar 09 10:04:30.843280 2020] [proxy_fcgi:error] [pid 5201:tid 140137350534912] [client 134.2.66.63:51776] AH01071: Got error 'PHP message: PHP Warning:  Unknown: Input variables exceeded 1000. To increase the limit change max_input_vars in php.ini. in Unknown on line 0\n', referer: https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=superior_ppn%3A497677458&type=AllFields`

Wir hatten zwar max_input_vars schon auf 10000 hochgesetzt aber es gab einen Syntaxfehler in der Zeile und daher hatte die Einstellung keinen Effekt.

Auf den anderen Servern war diese Einstellung korrekt gesetzt + aktiv, es schien sich also um ein Ptah-spezifisches Problem zu handeln. (Daher war es in meiner lokalen Installation nicht reproduzierbar)

Bitte jetzt nochmal testen.

**Comment by IxTheoKm** [comment]
Ich habe alle Exporte mit 500 Treffern durchgetestet. Sie funktionieren.
Exportfunktion für RefWorks klappt jetzt im Prinzip. Ich kann aber das Ergebnis ohne Registrierung nicht testen. @mtrojan-ub Das Problem war aber wohl gelöst.

Meine Frage vom 9. Dezember 2019, ob es gewollt ist, dass keine Treffer, sondern ein Link über die Funktion "E-Mail" gesendet wird, wurde nicht beantwortet.

Wenn beides so okay ist, kann dieses Issue geschlossen werden.

**Comment by thefass** [comment]
Ist ok so. Ich schließe das Issue.
