### ISSUE TITLE
Bug: Doppelte Aufsätze IAPT.CS

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#643]
hier sind doppelte Aufsätze vorhandenen, obwohl im K10plus alle 26 Aufsätze nur einmal vorhanden sind.
https://ixtheo.de/Search/Results?lookfor=superior_ppn%3A1656189313&type=AllFields

K10plus
![Bildschirmfoto 2019-04-25 um 01 36 14](https://user-images.githubusercontent.com/14169098/56700467-ace42200-66fa-11e9-96b8-cd68aa108924.png)

**Comment by IxTheoKm** [comment]
Die doppelten Aufsätze haben unterschiedliche PPNs!
Vermutlich versehentlich zweimal katalogisiert und inzwischen wieder gelöscht

**Comment by mtrojan-ub** [comment]
Diese Woche gab es schon Probleme beim Importieren von Löschlisten, da das BSZ unabsichtlich etwas am Format geändert hat. Allerdings konnte ich bei einer Stichprobe die gelöschte PPN auch nicht in den Löschlisten finden.

Beispiel: Im SWB ist die 1662420773 zwar vorhanden aber die 1662412169 nicht mehr, obwohl beide im IxTheo sind. (die 1662412169 taucht aber auch nicht in den Löschlisten auf UB16 auf)

@ruschein, kannst Du Dir das bitte mal anschauen?

**Comment by ruschein** [comment]
Der Datensatz mit der PPN 1662412169 war im Komplettabzug mit Lokaldaten SA-MARC-ixtheo-190326.tar.  Der Datensatz mit der PPN 1662420773 war im Komplettabzug ohne Lokaldaten SA-MARC-ixtheo_o-190326.tar.  1662412169 ist in der Löschliste LOEKXP-190404.

**Comment by thefass** [comment]
auf ptha behoben
