### ISSUE TITLE
Code 93 wird nicht aufgelöst

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#644]
In https://www.ixtheo.de/Record/129303348 wird der Code 93 nicht aufgelöst.

856 | 4 | 2 | \|u http://www.brill.nl/images/covers/7403.jpg    \|y Cover    \|3 93
-- | -- | -- | --

@IxTheoKm : ist das ein Erfassungsfehler?
Wenn nicht, bitte auflösen

**Comment by IxTheoKm** [comment]
Gleiches Problem wie https://github.com/ubtue/tuefind/issues/568 

Der oben genannte Titel ist eine ZDB-Aufnahme. Ich habe eine Mailbox an Sh und ZRED geschrieben, da ich aus der Formatdokumentation nicht ganz schlau werde:
http://swbtools.bsz-bw.de/cgi-bin/k10plushelp.pl?cmd=kat&val=4960&kattype=Standard#$3

Ich verstehe sie so, dass nicht der Code, sondern Klartext erfasst werden muss.

**Comment by IxTheoKm** [comment]
Rückmeldung der ZRED:
"das sind URLs aus dem GBV. Der GBV hat in $3 fälschlicherweise eine zeitlang Codes erfasst... das soll noch bereingt werden... steht schon auf der "ToDo-Korrekturliste" des GBV"

Die Frage ist also, ob auf die korrekte Erfassung gewartet werden soll (wie lange?) oder die Codes bei der Anzeige in VuFind umgesetzt werden sollen. Vgl. https://github.com/ubtue/tuefind/issues/568

**Comment by ruschein** [comment]
Scheint behoben zu sein.

**Comment by IxTheoKm** [comment]
Leider nicht:
https://ixtheo.de/Record/65456230X
https://ptah.ub.uni-tuebingen.de/Record/65456230X#details

![code](https://user-images.githubusercontent.com/17004223/60512727-b0d18900-9cd5-11e9-8688-88271e2c8d88.JPG)

**Comment by ruschein** [comment]
@IxTheoKm Stimmt jetzt hoffentlich auf Ptah.

**Comment by IxTheoKm** [comment]
Funktioniert jetzt, danke!
Ich schließe auch https://github.com/ubtue/tuefind/issues/568
