### ISSUE TITLE
Fehlermeldung bei Klick auf übergeordneten Titel

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#649]
Sowohl über die Kurzliste als auch über den Volltitel kommt im IxTheo und auf ptah die Fehlermeldung 
![Fehler](https://user-images.githubusercontent.com/17004223/56797112-42270980-6814-11e9-9cae-b3f103be0714.JPG)

**Comment by mtrojan-ub** [comment]
Gilt aber nur für bestimmte PPNs, oder? siehe auch #638 
z.B. die dort genannte Beispiel PPN 129497029 (verwiesen von 1663280606) 

Die 129497029 ist in den MARC-Daten enthalten, es gab jedoch Fehler beim Solr-Import.
Das hatte ich diese Woche schon mit @ruschein besprochen, er sagte er hatte Ihnen eine Liste mit ca. 30 fehlerhaften PPNs mit Bitte um Korrektur geschickt, ist die PPN dort enthalten?

**Comment by IxTheoKm** [comment]
Wenn diese Liste gemeinst ist: https://github.com/ubtue/fid/issues/1
Nein, die PPN ist darin nicht enthalten.

**Comment by mtrojan-ub** [comment]
Der genannte Fehler bezieht sich auf das Feld 936j welches mehrere Werte enthält, obwohl nur ein Wert enthalten sein darf. Obwohl sich das Feld auf ein "Jahr" beziehen soll, sind scheinbar Schlagwörter enthalten.

Bei 129497029 => Theologie, Religionswissenschaft: Allgemeines, Religion, Magie

**Comment by jriedl** [comment]
Das Problem, dass in 936j fehlerhafte Daten stehen und deshalb der Import des entsprechenden Records abbricht, tritt auch in Krimdok auf: [936j_error_sobek.txt](https://github.com/ubtue/tuefind/files/3127278/936j_error_sobek.txt)

**Comment by IxTheoKm** [comment]
Lt. Export-Tabelle auf dem K10plus-Wiki ist das kein Fehler.
Siehe https://github.com/ubtue/fid/issues/4

**Comment by jriedl** [comment]
Auf ptah behoben.
