### ISSUE TITLE
Medienart Websites / Datenbanken verschwunden

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#653]
Websites werden in der Facette nicht mehr aufgeführt
Datenbanken fehlen auch als Facette.

Dagegen ist die Gruppe der Software angewachsen. Da kann was nicht stimmen, Stecken da vielleicht die fehlenden Gattungen drin?

**Comment by jriedl** [comment]
Unser bisheriges Kriterium für Websites/Datenbanken war "website" bzw. "daten" in 935c, was laut Konkordanz aus PICA 1140 erzeigt wird (vgl. [http://swbtools.bsz-bw.de/winibwhelp/Liste_1140.htm](url)). Records mit dieser Auszeichnung existieren aber offenbar im aktuellen Datenbestand nicht mehr.

**Comment by IxTheoKm** [comment]
Die meisten Begriffe aus 1140 wurden mit K10plus in 1131 verschoben:
http://swbtools.bsz-bw.de/cgi-bin/k10plushelp.pl?cmd=kat&val=1131&kattype=Standard
(siehe auch Export-Tabelle)

In 1140 gibt es nur noch 15 Codes:
http://swbtools.bsz-bw.de/cgi-bin/k10plushelp.pl?cmd=kat&val=1140&kattype=Standard

**Comment by IxTheoKm** [comment]
Beispiele für Websites:
1040968201
1657131858
1588131106

Beispiele für Datenbanken:
1655830058
1654576379
871331128

**Comment by jriedl** [comment]
Websites, Datenbanken und Festschriften werden als Formate auf ptah jetzt wieder erkannt.

**Comment by IxTheoKm** [comment]
Danke, funktioniert!
