### ISSUE TITLE
Fehlermeldung nach Alert für RelBib, weil Daten fehlen

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#654]
Ein Alert für RelBib mit 3 Titelmeldungen führt zu Fehlermeldungen, da die Titel dort nicht vorhanden sind. Im IxTheo sind sie vorhanden, gehören aber nicht in RelBib (Neues Testament):
https://relbib.de/Record/1649204582
https://relbib.de/Record/1649204604
https://relbib.de/Record/1649204612

Ich muss zu Testzwecken ein Konto in beiden Datenbanken haben.
Wenn ich eine Zeitschrift im IxTheo abonniere, ist sie dadurch gleichzeitig in RelBib abonniert.

Gibt es Nutzer, die sowohl für IxTheo als auch für RelBib ein Konto angelegt haben?
Dann hätten sie dasselbe Problem, dass neue Datensätze gemeldet werden, obwohl sie nur im IxTheo und nicht in RelBib sind.

**Comment by thefass** [comment]
Ich halte es nicht für wahrscheinlich, aber es ist denkbar, dass jemand in beiden Bibliographien ein Konto hat

**Comment by jriedl** [comment]
Das hängt wohl damit zusammen, dass die Zeitschriften unter IxTheo abonniert wurden und der letzte Login an RelBib erfolgt ist. Das System geht dann von einem RelBib-Benutzer aus und es kommt zu dem beschriebenen Verhalten. Für eine saubere Trennung bestände die Möglichkeit, für RelBib explizit ein zweites Konto (mit eigenem Login und eigener Email-Addresse anzulegen) - diese wären dann komplett unabhängig.

**Comment by IxTheoKm** [comment]
Danke. Das ist dann auch ein Thema für einen Hilfetext. Ich habe das in die Datei IxTheo_Hilfstexte.xlsx eingefügt. Allerdings hat evtl. nicht jeder eine zweite E-Mail-Adresse.

**Comment by IxTheoKm** [comment]
Ich habe nun zum Testen jeweils getrennte Konten eingerichtet.

Vorab hatte ich zunächst in RelBib mein altes Konto gelöscht. Damit war dann auch gleichzeitig das Konto (unter demselben Namen) für den IxTheo gelöscht. Das passiert dann wohl nicht, wenn ich jeweils unterschiedliche Konten-Namen verwende, richtig?

**Comment by mtrojan-ub** [comment]
Laut aktueller Aussage von @ruschein werden wir das Verhalten so ändern, dass die Anmeldung im anderen System verhindert und eine entsprechende Fehlermeldung angezeigt wird.

**Comment by thefass** [comment]
Ja, das wäre auch aus meiner Sicht am sinnvollsten

**Comment by mtrojan-ub** [comment]
Die Änderung ist jetzt auf ptah aktiv.

Falls jemand aktuell noch ein Konto hat welches versehentlich mit dem falschen System assoziiert ist, bitte kurz melden, wir können es dann einmalig ändern.

![grafik](https://user-images.githubusercontent.com/26873381/61789567-5380b180-ae15-11e9-9d74-8964a73cf9a5.png)

**Comment by IxTheoKm** [comment]
Funktioniert. Danke
