### ISSUE TITLE
Abfragen "First-indexed" und "tue-local-indexed" funktionieren nicht

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#661]
Die Abfrage first_indexed:[jjjj-mm-ttT00\:00\:00Z TO NOW], mit der ich den aktuellen **Datenstand** ermittle, funktioniert nicht auf PTAH. Ist sie nur für IxTheo/RelBib eingerichtet?

Mit der Abfrage tue_local_indexed_date:[jjjj-mm-ttT00\:00\:00Z TO NOW] für KrimDok bekomme ich gar keine Treffer mehr (rückwirkend bis 1.4.2019 getestet).

**Comment by jriedl** [comment]
Problem auf ptah behoben. Die Krimdok-Problematik ist momentan nicht reproduzierbar: Mit tue_local_indexed_date:[2019-04-01T00:00:00Z TO NOW]  erhalte ich auf Krimdok 94 Treffer.

**Comment by IxTheoKm** [comment]
Danke, funktioniert jetzt auf PTAH.
Auch KrimDok funktioniert jetzt wieder. Hatte vorher keine Treffer gebracht - warum auch immer. 
Eine Fehlermeldung gab es da nicht. Aber jetzt ist es o.k.
Danke!
