### ISSUE TITLE
Zss fehlt in IxTheo

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#664]
Die Zeitschrift "Theologische Zeitschrift" wird in IxTheo nicht angezeigt, obwohl SSG 1 vorhanden:
https://ixtheo.de/Record/129458708

![Bildschirmfoto 2019-05-02 um 09 25 14](https://user-images.githubusercontent.com/14169098/57061228-683d2580-6cbc-11e9-9ebd-41963e5187f0.png)

**Comment by IxTheoKm** [comment]
Siehe Issue https://github.com/ubtue/tuefind/issues/649

**Comment by jriedl** [comment]
Auf ptah behoben.

**Comment by thefass** [comment]
ist ok

**Comment by thefass** [comment]
ist ok
