### ISSUE TITLE
773 unverknüpfte Gesamtaufnahme

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#666]
In der Krimdok wurden die SSOAR Daten eingespielt. In den meisten Fällen sind die Aufsätze nicht mit der Gesamtaufnahme verknüpft, es gibt aber eine literal angegeben Quelle in 773$a.

Beispiel: https://krimdok.uni-tuebingen.de/Record/1588527255

Bitte in den Fällen, in denen keine Verknüpfung vorhanden ist, 773$a auslesen und in der Zeile IN: vor der Jahresangabe darstellen
![Bildschirmfoto 2019-05-02 um 13 20 08](https://user-images.githubusercontent.com/14169098/57072171-1062e680-6cdd-11e9-85e8-cf0d715a651d.png)

**Comment by jriedl** [comment]
Auf sobek integriert.

**Comment by thefass** [comment]
gelöst
