### ISSUE TITLE
Erweiterte Suche nach Autor 

### ISSUE THREAD

**Issue by socheres** [ubtue/tuefind#668]
[ Suche nach Autor in der Erweiterten Suche](https://ixtheo.de/Search/Results?join=AND&lookfor0%5B%5D=zenger%2C+erich&type0%5B%5D=Author&lookfor0%5B%5D=&type0%5B%5D=AllFields&lookfor0%5B%5D=&type0%5B%5D=AllFields&bool0%5B%5D=AND&limit=20&daterange%5B%5D=publishDate&publishDatefrom=&publishDateto=&botprotect=) führt zur folgenden Fehlermeldung: 
"Es ist ein Fehler aufgetreten
Ein Fehler ist aufgetreten. Bitte versuchen Sie es später noch einmal.
Bitte kontaktieren Sie ihre Bibliothek für weitere Hilfe "

**Comment by jriedl** [comment]
Auf ptah und ub16 behoben.
