### ISSUE TITLE
IxTheo-Impressum

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#67]
Das Impressum auf PTAH ist (wieder?) veraltet. Ist die PTAH-Version die zukünftige IxTheo-Version, oder kann man solche Abweichungen bei Tests ignorieren?

**Comment by relhei** [comment]
Das Problem gilt auch für RelBib: Veraltetes Impressum. Zudem Telefonnummer von Gaby Zeller falsch. Richtig lautet diese: +49 (0)7071 2974030

**Comment by IxTheoKm** [comment]
Jetzt o.k.
