### ISSUE TITLE
GBV-Sammelschriften mit anhängenden Aufsätzen

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#674]
Es kommt vor, dass Sammelschriften eine SWB- und eine GBV-Aufnahme in K10plus haben, wobei an der GBV-Aufnahme bereits Aufsätze hängen, die wir gerne nachweisen wollen. 
Beispiel:
SWB-Aufnahme ohne Aufsätze
https://www.ixtheo.de/Record/1615090258#details
GBV-Aufnahme mit Aufsätzen
https://www.ixtheo.de/Record/684693585#details
Wir würden in diesem Fall die GBV-Aufnahme zusätzlich zur SWB-Aufnahme in IxTheo / RelBib indizieren. Wichtig wäre allerdings, dass in der Bibliografie eine Verknüpfung beider Aufnahmen realisiert wird, sinnvollerweise über die ISBN - Marc-Feld 020 $a.
Ist das umsetzbar?

**Comment by ruschein** [comment]
Das sollte das BSZ lösen.
