### ISSUE TITLE
IxTheo Klaasifikation Verlinkung funktioniert nicht mehr

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#679]
Bei Klick auf eine IxTheo Klasse kommt der Fehler:

Es ist ein Fehler aufgetreten
Seite nicht gefunden.

https://www.ixtheo.de/IxTheoClassification

**Comment by jriedl** [comment]
Auf ptah und ub16 behoben.

**Comment by thefass** [comment]
gelöst
