### ISSUE TITLE
Fehler bei Suchanfrage aus Autosuggest

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#681]
Nach Auswahl eines Titels mit Satzzeichen am Ende aus der Autosuggest-Liste, führt die Suche zu keinem Ergebnis. Erst, wenn das Sternchen händisch gelöscht wird, gelangt man zur Ergebnisanzeige.

![grafik](https://user-images.githubusercontent.com/25769591/57607750-0e661680-756c-11e9-807f-04ac58aa98b4.png)

Bei Titeln ohne Satzzeichen gibt es das Problem hingegen nicht:

![grafik](https://user-images.githubusercontent.com/25769591/57607965-74eb3480-756c-11e9-9bba-d0d62ff3f04a.png)

**Comment by jriedl** [comment]
Auf ptah in diesen Fällen jetzt ohne Wildcard am Ende.

**Comment by relhei** [comment]
Leider anscheinend nicht nur bei Satzzeichen am Ende. Hier noch ein Beispiel, bei dem kein Ergebnis mit Wildcard kommt:

![grafik](https://user-images.githubusercontent.com/25769591/57679632-171e2180-762c-11e9-9761-7795ff3ae465.png)

**Comment by jriedl** [comment]
Diesmal lag es am im Titel vorkommenden Minus.

**Comment by relhei** [comment]
Vielen Dank!
