### ISSUE TITLE
IxTheo_Exportfunktion

### ISSUE THREAD

**Issue by AleAprile** [ubtue/tuefind#685]
Hallo Zusammen,
bei der Exportfunktion (RIS-Format) passiert Folgendes. Einzelne Einträge können problemlos exportiert werden, auch bei 10 oder 15 geht es. Wähle ich aber alles aus, dann bekomme ich eine Fehlermeldung. 

Zum Testen: 
Verfasser: Hieke, Thomas
Zeitraum: 2015 - 2019
Trefferzahl: 82 Titel

**Comment by jriedl** [comment]
Das scheint die gleiche Problematik zu sein, wie in #638: Ein übergeordnetes Werk findet sich nicht im Datenbestand. In der Liste findet sich die PPN 1662613482, deren übergeordnete PPN 165731842 nicht Teil des IxTheo-Bestandes ist. Wählt man diesen aus der Liste ab, funktioniert der Export.

**Comment by ruschein** [comment]
@AleAprile Scheint jetzt zu tun.

**Comment by IxTheoKm** [comment]
Ich habe die o.g. Suche nochmals getestet (die o.g. PPN 165731842 gibt es weiterhin nicht in der Datenbank):
Export der esten 20 Treffer funktioniert. Wenn ich alle 128 exportieren will kommt eine Fehlermeldung:
https://ixtheo.de/Search/Results?filter%5B%5D=publishDate%3A%22%5B2015+TO+2019%5D%22&lookfor=hieke%2C+thomas&type=AllFields

![export_685](https://user-images.githubusercontent.com/17004223/92717082-f79e2280-f35f-11ea-8b58-81e9a33c2b78.JPG)

**Comment by mtrojan-ub** [comment]
Aktuell gab es einen Bug im ris Export template ("volume"-spezifisch). Ich habe ihn auf ptah behoben und kann jetzt die ersten 200 Einträge problemlos exportieren. Bitte nochmal testen.

**Comment by AleAprile** [comment]
Es wird leider keine Datei beim Export großer Datenmenge heruntergeladen, obwohl sich das Fenster "Datei herunterladen" nach der Auswahl der Titel öffnet.

**Comment by mtrojan-ub** [comment]
Ist diesmal ein anderer Bug im Zusammenhang mit der Serie, ich kümmer mich drum.

**Comment by mtrojan-ub** [comment]
Bitte nochmal auf ptah testen.

**Comment by AleAprile** [comment]
Ich habe auf ptah erneut getestet. Mit 10 und 20 zu exportierenden Titeln funktioniert es gut, ab 50 dann nicht mehr. Test-Autor: Hieke, Thomas. Interessanterweise wenn ich einen anderen Autor nehme, etwa Arnold Claus, dann funktioniert die Exportfunktion mit 50 Titeln problemlos, mit 100 dann nicht mehr. 

Mit "Kaufmann Thomas" bekomme ich auch andere Ergebnisse:  Da lässt sich eine RIS-Datei mit 213 Titeln allesamt und problemlos herunterladen.

**Comment by mtrojan-ub** [comment]
Kann ich nicht reproduzieren. Bitte um die genaue URL des Suchergebnisses.

**Comment by AleAprile** [comment]
Ja, gerne.

Hieke, Thomas mit 50 Titeln: https://ptah.ub.uni-tuebingen.de/Author/Home?author=%22Hieke%2C+Thomas+1968-%22&type=Author [keine Datei wird heruntergeladen]

Arnold, Claus mit 95 Titel: https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=Arnold%2C+Claus+1965-&type=Author [keine Datei wird heruntergeladen]

Kaufmann, Thomas mit 199: https://ptah.ub.uni-tuebingen.de/Author/Home?author=%22Kaufmann%2C+Thomas+1962-%22&type=Author [**die Datei wird heruntergeladen**]

**Comment by thefass** [comment]
Ich weiß nicht, ob das damit zusammenhängt.
Eine große Liste mit 426 Titeln kann auch nicht im eigenen Konto als Liste gespeichert werden.
https://ptah.ub.uni-tuebingen.de/Author/Home?author=%22Hieke%2C+Thomas+1968-%22&type=Author
![Bildschirmfoto 2020-09-29 um 14 35 22](https://user-images.githubusercontent.com/14169098/94559279-45bc8c80-0261-11eb-83b8-0ae764c4324e.png)
![Bildschirmfoto 2020-09-29 um 14 35 43](https://user-images.githubusercontent.com/14169098/94559302-4ead5e00-0261-11eb-9ecb-ba582992c10b.png)

**Comment by mtrojan-ub** [comment]
@AleAprile das erste Beispiel lässt sich isolieren, Problem taucht auch auf wenn man versucht folgenden Datensatz einzeln zu exportieren:
https://ptah.ub.uni-tuebingen.de/Cart/doExport?f=RIS&i%5B%5D=Solr%7C1662613482

**Comment by mtrojan-ub** [comment]
Ich habe einen Fehler bei der Abfrage des übergeordneten Werkes behoben. Wenn die PPN zwar hinterlegt ist aber der Datensatz nicht existiert, wurde dieser Fehlerfall nicht richtig abgefangen. Jetzt funktioniert der Export in allen 3 von @AleAprile genannten Fällen.

Allerdings: Wenn das übergeordnete Werk nicht gefunden wird, kann auch nicht geprüft werden ob es sich tatsächlich um eine Zeitschrift handelt (Default, TY = JOUR) oder nur um ein Buchkapitel (TY = CHAP). Dementsprechen sind ggf. auch weiterführende Angaben falsch falls das übergeordnete Werk fehlt (insbesondere CY, PB, PY).

@AleAprile: Bitte nochmal testen
@thefass: Das mit dem Speichern hat damit nichts zu tun, ich verschiebe diese Frage in ein separates Issue.

**Comment by AleAprile** [comment]
Testergebnisse mit den drei besagten Fällen: 

- [x] Hieke, Thomas - **428 Titel erfolgreich exportiert**, siehe: https://ptah.ub.uni-tuebingen.de/Author/Home?author=%22Hieke%2C+Thomas+1968-%22&type=Author

- [x] Arnold, Claus - **dito mit 95 Titeln**, siehe: https://ptah.ub.uni-tuebingen.de/Author/Home?author=%22Arnold%2C+Claus+1965-%22&type=Author

- [x] Kaufmann, Thomas - **dito mit 213 Titeln**, siehe: https://ptah.ub.uni-tuebingen.de/Author/Home?author=%22Kaufmann%2C+Thomas%22&type=Author

Frage: Sind weitere Stichproben mit anderen Autoren gewünscht oder reichen die drei hier aus?

**Comment by mtrojan-ub** [comment]
Grundsätzlich gerne, aber ich kann nicht beantworten wann "genug getestet" wurde

**Comment by AleAprile** [comment]
Das ist ein guter Punkt. Alle im IxTheo indexierten Autoren zu testen, wäre undenkbar. Aus meiner Sicht können jedoch drei weitere Stichproben, am besten mit möglichst schreibfreudigen Autoren, sicherlich nicht schaden. Ich kümmere mich darum und melde mich zurück, wenn ich die Ergebnisse habe.

**Comment by AleAprile** [comment]
Drei weitere Tests:

- Lohfink, Gerhard - 500 Titel erfolgreich exportiert: https://ptah.ub.uni-tuebingen.de/Author/Home?author=%22Lohfink%2C+Gerhard%22&type=Author

- Leppin, Volker - 500 Titel erfolgreich exportiert: https://ptah.ub.uni-tuebingen.de/Author/Home?author=%22Leppin%2C+Volker+1966-%22&type=Author

- Hubert, Wolf - 308 Titel erfolgreich exportiert: https://ptah.ub.uni-tuebingen.de/Author/Home?author=%22Wolf%2C+Hubert+1959-%22&type=Author

**Comment by mtrojan-ub** [comment]
Heißt das der Issue kann jetzt geschlossen werden?

**Comment by IxTheoKm** [comment]
Ich habe auch noch zwei Tests mit je 500 Treffern gemacht, die beim Export problemlos liefen.

Was weiter nicht funktioniert, ist das speichern einer Liste mit großer Treffermenge (siehe https://github.com/ubtue/tuefind/issues/685#issuecomment-700674334)

![Liste speichern](https://user-images.githubusercontent.com/17004223/95213828-84b58980-07ef-11eb-8568-9d37aaf76caa.JPG)

**Comment by mtrojan-ub** [comment]
@IxTheoKm: Dieses Problem wird in Issue #1311 weiter verfolgt, siehe oben.
Ich würde also diesen Issue schließen und das Problem im genannten anderen Issue weiter verfolgen.
