### ISSUE TITLE
nicht anklickbare Titel in Trefferliste

### ISSUE THREAD

**Issue by Gazeller** [ubtue/tuefind#687]
![grafik](https://user-images.githubusercontent.com/16898788/57771059-fd570a00-7711-11e9-8936-4c2133ee7adc.png)

Woran kann das liegen? So auf ptah gefunden.

**Comment by mtrojan-ub** [comment]
das kann ich so nicht reproduzieren, bei mir sieht's wie folgt aus und ist ganz normal anklickbar:

![grafik](https://user-images.githubusercontent.com/26873381/57776166-0ef2de80-771f-11e9-8982-abe66de89925.png)

Könnt Ihr bitte einen Link auf ein Suchergebnis zur Verfügung stellen?

**Comment by Gazeller** [comment]
https://134.2.67.9:4445/Search/Results?lookfor=material+religion+culture&type=Title&limit=20&botprotect= 
Es ist der Titel Nr. 14

**Comment by mtrojan-ub** [comment]
Sieht bei mir trotzdem alles OK aus (Firefox 66.0.5). Welchen Browser+Version verwendest Du denn?

**Comment by relhei** [comment]
Passt.
