### ISSUE TITLE
Highlighting nicht konsistent

### ISSUE THREAD

**Issue by Gazeller** [ubtue/tuefind#688]
Nach Suchanfrage auf ptah (material religion) highlighting sehr unterschiedlich:
![grafik](https://user-images.githubusercontent.com/16898788/57771422-f7155d80-7712-11e9-8356-18e1bb2e9c26.png)

**Comment by jriedl** [comment]
Das hängt mit dem Zusammenspiel von Highlighting und der gewählten Standardsortierung (die bei RelBib und IxTheo primär das Erscheinungsjahr) zusammen. Zuerst werden die Datensätze bestimmt, die matchen, und dann erst Sortierung und für die zulässigen Felder das Highlighting vorgenommen. Es sind aber nicht alle Felder für das Highlighting freigegeben und je nachdem, ob das Feld, das ursprünglich zum Treffer beigetragen hat, im Highlighting angezeigt werden kann oder nicht, kommt es zu Ergebnissen ähnlich dem obigen. Wir als Sortierung "Relevanz" ausgewählt, scheinen die ersten Treffer der Ergebnisse deutlich homogener, die hier die "wichtigen Felder" höher gewichtet werden.
