### ISSUE TITLE
Abonnieren-button fehlt in Volltitelanzeige

### ISSUE THREAD

**Issue by Gazeller** [ubtue/tuefind#690]
![grafik](https://user-images.githubusercontent.com/16898788/57771595-6ee38800-7713-11e9-83d7-202e1180f45c.png)

Bei Aufruf eines Zeitschriftentitels auf ptah fehlt oben der Button "Abonnieren"

**Comment by mtrojan-ub** [comment]
Ich kümmere mich drum. Werde auch SMS deaktivieren. 

Zusätzlich ist mir aufgefallen, dass die Buttons hier in einem ganz anderen Stil sind als die im Suchergebnis

![grafik](https://user-images.githubusercontent.com/26873381/57772912-039bb500-7717-11e9-8551-a745897ae90b.png)

Das werde ich dann auch noch anpassen.

**Comment by mtrojan-ub** [comment]
kann auf ptah getestet werden

**Comment by relhei** [comment]
Passt. Danke!
