### ISSUE TITLE
Tagging entfernen auf ptah

### ISSUE THREAD

**Issue by Gazeller** [ubtue/tuefind#691]
Auf ptah ist wieder Taggingfunktion aktiviert:
![grafik](https://user-images.githubusercontent.com/16898788/57772702-6e002580-7716-11e9-89ba-e75b799fb993.png)

Bitte entfernen

**Comment by mtrojan-ub** [comment]
Ist entfernt... ist nur im neuen Layout auf ptah aufgetreten, hatte aber nichts mit dem layout selbst sondern mit einer alten Konfiguration für die separate Instanz auf ptah zu tun, auf der das neue Layout läuft

**Comment by Gazeller** [comment]
okay, danke!
