### ISSUE TITLE
Bug bei Favoriten speichern

### ISSUE THREAD

**Issue by Gazeller** [ubtue/tuefind#692]
Nach dem Speichern eines Titels im eigenen Konto auf ptah erscheint der Hinweis "Gespeicher in ..." zweimal.
![grafik](https://user-images.githubusercontent.com/16898788/57773122-89b7fb80-7717-11e9-8bcb-c104e029a24e.png)

**Comment by mtrojan-ub** [comment]
kann auf ptah getestet werden

**Comment by relhei** [comment]
Passt. Danke!
