### ISSUE TITLE
Browsen / nach Kategorien: Buchstabenkürzel der Klassen fehlt

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#70]
Bei den Hauptklassen der RelBib-Klassifikation fehlt momentan das Buchstabenkürzel. Im IxTheo wird es angezeigt. 

![grafik](https://user-images.githubusercontent.com/25769591/33608024-5bc0e158-d9c3-11e7-82a5-40da42381fb6.png)

![grafik](https://user-images.githubusercontent.com/25769591/33608042-719d74d2-d9c3-11e7-8c5b-28e1878db546.png)

**Comment by jriedl** [comment]
Wird jetzt angezeigt.

**Comment by relhei** [comment]
Passt. Danke!
