### ISSUE TITLE
neues RelBib Design - oberste Zeile fast nicht lesbar

### ISSUE THREAD

**Issue by Gazeller** [ubtue/tuefind#701]
Die oberste Zeile mit "Home" "Login" "Sprache" müsste farblich stärker hervorgehoben werden. Außerdem ist das irgendwie zu weit rechts, gefühlt ist es "außerhalb"... Kann man das ändern?
![grafik](https://user-images.githubusercontent.com/16898788/57847917-f0045300-77d7-11e9-8e37-c15dbde53207.png)

**Comment by mtrojan-ub** [comment]
Das Menü ist auf ptah jetzt dunkler. Ich könnte das Menü noch oben rechts nahe dem Ende der Suchbox zentrieren. Was passiert dann mit dem zweiten (kleinen) RelBib Logo links oben? Bleibt das drin oder soll es rausfliegen?

**Comment by mtrojan-ub** [comment]
Durch das Feedback der Direktion hat sich die Kopfzeile ja ohnehin verändert. Kann der Issue jetzt geschlossen werden?

![grafik](https://user-images.githubusercontent.com/26873381/58402516-d2997980-8060-11e9-8c31-c0e08530a04d.png)

**Comment by relhei** [comment]
Sieht gut aus. das einzige, was mir noch aufgefallen ist: Kann es sein, dass die Logos von Uni und UB etwas unscharfer sind als die restliche Schrift? Es wirkt zumindest so bei großer Ansicht.

**Comment by mtrojan-ub** [comment]
Stimmt, es scheint so als wäre das Logo auf der neuen Uni-Seite schärfer. Ich tausch's aus. Gilt dann auch für KrimDok.

**Comment by mtrojan-ub** [comment]
Das Uni-Logo ist jetzt schärfer. Das UB Logo liegt mir nicht als schärfere Version vor, aber wir schauen mal was sich machen lässt.

**Comment by mtrojan-ub** [comment]
UB Logo ist jetzt ebenfalls schärfer, bitte auf ptah ausprobieren

**Comment by relhei** [comment]
Sieht jetzt gut aus! Danke!
