### ISSUE TITLE
Rezensionen werden nicht in der Facette Review angezeigt

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#704]
Bitte zusätzlich zu Aufnahmen mit **"655 $a Rezension"** auch Aufnahmen mit **"787 $i Rezension von"** in der Facette Review anzeigen.

Bsp.:
https://ixtheo.de/Search/Results?lookfor=Come+Thou+Long+Expected+Jesus&type=AllFields&limit=20&botprotect=

https://ixtheo.de/Search/Results?lookfor=Kommunion+auf+die+Zunge+und+auf+den+Knien+empfangen&type=AllFields&limit=20&botprotect=

https://ixtheo.de/Search/Results?lookfor=Rezension+von+Frederickson+David+E.+Eros+and+the+Christ&type=AllFields&limit=20&botprotect=

https://ixtheo.de/Record/1664983597#details
https://ixtheo.de/Record/1643349872#details
https://ixtheo.de/Record/1663374562#details

Die Aufnahmen enthalten **787 $i Rezension von**, werden aber nicht in der Facette Review angezeigt.

Als Review angezeigt werden z.B.
https://ixtheo.de/Record/1588147673#details
https://ixtheo.de/Record/1665457279#details
https://ixtheo.de/Record/1586767976#details

Diese Aufnahmen enthalten **655 $aRezension** (ca. 170.000 Datensätze)

**Comment by ruschein** [comment]
@IxTheoKm Ich verstehe nicht was wir hier tun sollen??

**Comment by IxTheoKm** [comment]
Siehe erster Satz im Issue:
Aufnahmen mit 787 $i Rezension von sollen (wie Aufnahmen mit 655 $ Rezension) in der Facette Medienart nicht als Aufsätze sondern als Review angezeigt werden:
![review](https://user-images.githubusercontent.com/17004223/57918103-65365d80-7896-11e9-9c0a-2427b3d90d41.JPG)

**Comment by IxTheoKm** [comment]
Noch eine Ergänzung:
Bitte unbedingt auf die Zeichenfolge **"Rezension von"** achten!

787 08$iRezension$a _ohne_ "von" darf nicht als Review angezeigt werden!

**Comment by ruschein** [comment]
Auf Ptah.

**Comment by IxTheoKm** [comment]
Jetzt werden die Datensätze doppelt angezeigt: in der Facette Medienart als Review und als Aufsatz. Sie sollen nur als Review angezeigt werden.

**Comment by ruschein** [comment]
Auf Ptah.

**Comment by IxTheoKm** [comment]
Jetzt wird der Medientyp "Elektronisch" zusätzlich/doppelt in der Facette Medienart angezeigt. Bei nicht-elektronischen Datensätzen passiert das nicht.

![review_elektr](https://user-images.githubusercontent.com/17004223/58485154-c6e2ab80-8163-11e9-8179-74f474febbc4.JPG)

**Comment by ruschein** [comment]
@IxTheoKm "Elektronisch" in der Facette Medienart sollte ab morgen verschwunden sein.

**Comment by IxTheoKm** [comment]
Jetzt o.k., danke
