### ISSUE TITLE
Lokale Abrufzeichen in LOK 935 $a unvollständig

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#705]
Der größte Teil der Theologischen Literaturzeitung hat in LOK 935 $a nur eines der beiden lokalen Abrufzeichen theo und ixrz.

https://ixtheo.de/Search/Results?lookfor=superior_ppn%3A320517764+AND+NOT+rs%3Aixrz&type=AllFields&limit=20&botprotect=

https://ixtheo.de/Search/Results?lookfor=superior_ppn%3A129081191+AND+NOT+rs%3Aixrz&type=AllFields&limit=20&botprotect=

Erfasst sind $atheo und $aixrz

Bsp.:
https://ixtheo.de/Record/1521158681#details
https://ixtheo.de/Record/1476293880#details

Bei einigen Titeln sind beide vorhanden:

https://ixtheo.de/Search/Results?lookfor=superior_ppn%3A129081191+AND+rs%3Atheo+AND+rs%3Aixrz&type=AllFields&limit=20&botprotect=

https://ixtheo.de/Search/Results?lookfor=superior_ppn%3A320517764+AND+rs%3Atheo+AND+rs%3Aixrz&type=AllFields&limit=20&botprotect=

**Comment by ruschein** [comment]
@IxTheoKm Entschuldigung, meine Frage betraf eigentlich dieses Issue.

**Comment by IxTheoKm** [comment]
Würden Sie bitte prüfen, ob in den Daten bei Ihnen _zwei_ Abrufzeichen (theo und ixrz) angekommen sind.
Wenn ja, sollten beide in LOK 935 $a angezeigt und recherchierbar gemacht werden.

Wenn nicht, müssten die Daten nach einer Neuauslieferung auf Vollständigkeit geprüft werden.
Ich meine aber, dass man warten könnte, bis ohnehin eine neue Gesamtlieferung geplant ist.

**Comment by ruschein** [comment]
@IxTheoKm Die Beiden Abrufzeichen sind beide vorhanden und koennen mit "rs:theo" bzw. "rs:ixrz" gefunden werden.

**Comment by IxTheoKm** [comment]
Bei den beiden o.g. Beispielen fehlen die lokalen Abrufzeichen ixrz:
https://ixtheo.de/Record/1521158681#details
https://ixtheo.de/Record/1476293880#details

Im K10plus ist  $0935 $atheo$aixrz erfasst, im VuFind steht nur theo.

Wenn ich anfrage mit "superior_ppn:320517764 AND rs:theo **AND NOT** rs:ixrz" bekomme ich fast 46.000 Treffer, in denen das der Fall ist. Die haben aber alle theo und ixrz in den Originaldaten in K10plus.

Wenn ich "superior_ppn:320517764 AND rs:theo AND rs:ixrz" anfrage, bekomme ich nur 104 Treffer, in denen beide Abrufzeichen stehen. Die sind also korrekt.

IxTheo und ptah liefern jeweils dasselbe Ergebnis.

**Comment by ruschein** [comment]
Habe mit gerade den Datensatz zu 1521158681 angeschaut.  Da ist kein ixrz vorhanden.  In den Lokaldaten steht in 935 theo.  Wird wohl so vom BSZ ausgeliefert.

**Comment by IxTheoKm** [comment]
Ich habe bei PPN 1521158681 eine Scheinkorrektur im Datensatz gemacht und prüfe, ob beide lokale Abrufzeichen ankommen.

**Comment by IxTheoKm** [comment]
In https://ixtheo.de/Record/1521158681#details sind nach der Neuauslieferung beide lokale Abrufzeichen vorhanden. Daher vermute ich, dass bei der ersten Auslieferung der Aufsätze von PPN 320517764 ein Fehler zu unvollständigen lokalen Abrufzeichen geführt hat. 

"ixrz" ist nicht relevant für die Facette Medienart "Review", sondern hat lediglich statistische Funktion. Ich würde daher wie oben geschrieben auf eine neue Gesamtlieferung warten.
@thefass Gibt es Einwände dagegen?

**Comment by ruschein** [comment]
@thefass Ich würde das Issue gerne zumachen da bei uns kein Handlungsbedarf zu bestehen scheint.

**Comment by thefass** [comment]
Nein, es gibt keine Einwände und wir warten wie vorgeschlagen auf einen Gesamtabzug
