### ISSUE TITLE
Thema Browsen: abweichende Auflistung der Treffer bei Sprachauswahl "Englisch"

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#71]
Bei Eingabe zweier Suchbegriffe in Thema Browsen (Ptah, Sprachauswahl Englisch) kommt eine andere Auflistung von Schlagwortketten als unter gleichen Bedingungen in RelBib / IxTheo: Es werden nicht mehr Schlagwortketten, die beide Begriffe enthalten, zuerst aufgelistet.
Ptah:
![grafik](https://user-images.githubusercontent.com/25769591/33608846-16ec1676-d9c6-11e7-9575-c96c0e7e4947.png)

RelBib:
![grafik](https://user-images.githubusercontent.com/25769591/33608860-2281585c-d9c6-11e7-87aa-05492ea6e179.png)

**Comment by jriedl** [comment]
Die Problematik mit "China Buddhism"  ist jetzt auf ptah behoben.

**Comment by relhei** [comment]
Vielen Dank!
