### ISSUE TITLE
Autocompletefunktion bei Schlagwörtern

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#715]
Die Autocompletefunktion funktioniert bei Schlagwörtern nicht so wie z.B. bei Verfassern.
Beispiel: Tauf
![Bildschirmfoto 2019-05-22 um 11 16 56](https://user-images.githubusercontent.com/14169098/58162828-2d0e9080-7c83-11e9-8490-529f677f77d5.png)

Es sollte aber eine Auswahl aller Möglichkeiten erscheinen, so wie das in der WebGND umgesetzt ist:
![Bildschirmfoto 2019-05-22 um 11 10 51](https://user-images.githubusercontent.com/14169098/58166717-bbd2db80-7c8a-11e9-8723-d5a0513ba9d8.png)

**Comment by jriedl** [comment]
Das ist aufgrund der Art und Weise, wie Autosuggest bei VuFind implementiert ist, nicht möglich: Die Autosuggest-Funktion setzt eine Suchabfrage auf definierte Felder ab und extrahiert dann aus den ersten Treffern und definierten Feldern die Vorschlagsliste. Damit kann diese Liste nicht abschließend sein, da das Suchergebnis abgeschnitten wird und oft auch in dieser Trefferliste häufig der gleiche Term vorkommt, der dann nur einmal vorgeschlagen wird. Für die Schlagwörter gilt aber ab sofort auf ptah folgendes: Durch Anpassung der durchsuchten und ausgewerteten Felder und der Verwendung der Relevanzsortierung bei dieser Abfrage sollten nun keine Rohdatenfelder mehr vorgeschlagen werden und im Vergleich "bessere" Ergebnisse erzielt werden. Weiterhin ist die Vorschlagsfunktion jetzt sprachsensitiv, d.h. bei Auswahl einer anderen Sprache werden Schlagwörter so vorhanden in dieser Sprache vorgeschlagen.

**Comment by obrandt** [comment]
Vorschlag wird von Fachreferenten erarbeitet.

**Comment by thefass** [comment]
das ist ausreichend so
