### ISSUE TITLE
Doppelte Anzeige von "elektronisch" bzw. "electronic" in Trefferliste

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#735]
Elektronisch verfügbare Titel werden in der englischen und deutschen Trefferliste doppelt mit "electronic" bzw. "elektronisch" ausgewiesen. Liegt es evt. daran, dass "elektronisch" bzw. "electronic" in die "falsche" Facette gerutscht ist (Medienart)?
![grafik](https://user-images.githubusercontent.com/25769591/58545225-1deb8d80-8203-11e9-9766-1b1a831c8089.png)

**Comment by mtrojan-ub** [comment]
... hierzu haben wir gestern bereits etwas geändert, das sollte dann ab morgen bzw. Freitag auf ptah gelöst sein.

**Comment by mtrojan-ub** [comment]
noch nicht testbar da es die letzten Tage Pipeline-Probleme auf ptah gab

**Comment by mtrojan-ub** [comment]
In der Zwischenzeit wurde ein neuer Import durchgeführt und der Issue kann jetzt getestet werden.

**Comment by relhei** [comment]
Passt jetzt. Danke!
