### ISSUE TITLE
Autocomplete funktioniert nicht

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#751]
Momentan funktioniert Autocomplete auf RelBib nicht:

![grafik](https://user-images.githubusercontent.com/25769591/58955658-d6ce4100-879c-11e9-8b2d-669ade853729.png)

**Comment by mtrojan-ub** [comment]
@KStelzel: KrimDok ist hiervon ebenfalls betroffen.
Wir haben das Problem behoben, es kann jetzt auf ptah und sobek getestet werden.

**Comment by relhei** [comment]
Funktioniert wieder. Danke!
