### ISSUE TITLE
Medienart "unbekannt" zu groß

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#752]
Die Treffermenge für "Medienart: unbekannt" ist m. E. viel zu groß (fast die Hälfte aller Treffer in RelBib). 
![grafik](https://user-images.githubusercontent.com/25769591/58956795-8efce900-879f-11e9-88e5-17e61fe9f179.png)

War das schon immer so? Oder sind evt. einige Medienarten "verloren gegangen"? Bei Stichprobe liegen normierte Angaben in Feld 655 7$a vor, die anscheinend nicht ausgelesen werden.
Hier ein Beispiel (für Medienart "Hochschulschrift"):
https://relbib.de/Record/788886525#details

**Comment by relhei** [comment]
Die Medienart "Weblog" wurde zuvor aus Feld 655 7$a ausgelesen, aktuell nicht mehr. Beispiel:
![grafik](https://user-images.githubusercontent.com/25769591/59025765-2c662480-8855-11e9-8ef1-f238b05c3ce8.png)

https://www.relbib.de/Search/Results?lookfor=Zeitlupe&type=AllFields&limit=20&botprotect=

**Comment by IxTheoKm** [comment]
Auch Feld 336 wird scheinbar nicht ausgelesen:
https://ixtheo.de/Record/1014413818#details

Hier: "unbewegtes Bild"

![Medienart_Unbekannt](https://user-images.githubusercontent.com/17004223/59027045-32a9d000-8858-11e9-8c95-f01b741ffcb5.JPG)

**Comment by ruschein** [comment]
Auf Ptah.

**Comment by Gazeller** [comment]
Es wird besser, sind aber immer noch zu viele "unbekannte"
![grafik](https://user-images.githubusercontent.com/16898788/59255193-ed0f4d80-8c31-11e9-9e88-d839a72e2af1.png)

die Trefferliste zeigt, dass Zeitschriften- und Reihen (als Ganzes) als unbekannt angesehen wird.
![grafik](https://user-images.githubusercontent.com/16898788/59255451-69a22c00-8c32-11e9-8569-def16437d9d4.png)

**Comment by ruschein** [comment]
@Gazeller Bitte nochmals auf Ptah testen.

**Comment by Gazeller** [comment]
Jetzt passt's. Auf RelBib-ptah nur noch 42 "unbekannte"!
