### ISSUE TITLE
Lizenzfreie Aufsätze an Print-Ausgabe nicht in Facette Open Access angezeigt

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#755]
URL bei gedruckten Aufsätzen werden nicht vollständig ausgelesen, so dass bei Vorliegen eines lizenzfreien Volltextes diese dennoch nicht in der Open-Access-Facette erscheinen. 
Beispiel:
![grafik](https://user-images.githubusercontent.com/25769591/59029252-114be280-885e-11e9-9e82-7a1f807ce9e3.png)
![grafik](https://user-images.githubusercontent.com/25769591/59029318-46f0cb80-885e-11e9-9563-11ef6bdc49fb.png)
In der WinIBW gibt es mehr Unterfelder:
856 42$uhttps://doi.org/10.15496/publikation-17561$xResolving-System$3Volltext$$zLF
Dies wird in Zukunft einige der Zweitveröffentlichungen betreffen, daher ist es wichtig, dass die entsprechenden Unterfelder für die Anzeige als "Open Access" ausgelesen werden.

**Comment by relhei** [comment]
Außerdem wird der Aufsatz als "elektronisch" angezeigt, ist aber vom Satztyp her eigentlich ein Print-Aufsatz.

**Comment by relhei** [comment]
https://www.relbib.de/Record/1536161373#details

**Comment by thefass** [comment]
ist das ein Datenlieferproblem oder ein Problem der Verarbeitung in der Pipeline?

In der WinIBW steht:
856 42$uhttps://doi.org/10.15496/publikation-17561$xResolving-System$3Volltext$$zLF
ankommen tut bei uns:

856 |   |   | \|u https://doi.org/10.15496/publikation-17561    \|x doi -- | -- | -- | --

An $3 erkennt man, dass es ein Volltext ist, an $zLF, dass es open access ist
(LF steht für Lizenzfrei). Das muss beides augelesen werden

**Comment by thefass** [comment]
Zum anderen Problem: 
das ist ja ein Spezialfall, da wir in ein Katalogisat vom Typ Druck den DOI integrieren (das machen wir öfter, in dem Fall ist das aber Open Access) und damit entsteht sozusagen ein Zwitter.
Wie wir damit umgehen, müssen wir erst noch diskutieren.

**Comment by relhei** [comment]
Das ist vmtl. ein Problem der Datenauslieferung durchs BSZ. Im PICA-Format steht korrekt ...$3Volltext$zLF. Im MRC-Format ist hingegen ein $-Zeichen zu viel: ...$3Volltext$$zLF. Möglicherweise liegt darin der Fehler. Kontaktaufnahme mit BSZ (Mailbox) ist geplant.

**Comment by ruschein** [comment]
@IxTheoKm Wie können wir am MARC-Datensatz erkennen, dass es sich um eine Druckausgabe handelt?

**Comment by IxTheoKm** [comment]
Das Problem in Feld 856 müsste nun gelöst sein. Ich habe über die Formatdokumentation die korrekte Erfassungsform herausgefunden.
URLs in Druckausgaben standen vor K10plus in einem anderen PICA-Feld 4089. 
Im neuen PICA-Feld 4961 muss ein Code für "Volltext" ergänzt werden, und "LF" steht in einem anderen Unterfeld. Ich habe die Fälle korrigiert, die ich gefunden habe. 

@ruschein Ist es möglich, eine Liste mit PPNs von Titeln zu bekommen, in denen in 856 "$3Volltext$$zLF" vorkommt, bzw. generell "$$"?

Wegen der Kennzeichnung von Druckausgaben muss ich noch schauen.

**Comment by ruschein** [comment]
@IxTheoKm Hier ist die Liste mit Inhalten von 856$3 die vermutlich korrigiert werden müssen:

1443933376:8563:Volltext$zLF
1444074644:8563:Volltext$zLF
1445189100:8563:Volltext$zLF
1535044128:8563:Volltext$zLF
1584867957:8563:Volltext$zLF
1645929779:8563:Volltext$zLF
1646275950:8563:Volltext$zLF
164699552X:8563:Volltext$zLF
1649146027:8563:Volltext$zLF
1662475128:8563:Volltext$hLF
824037359:8563:LF
1389137708:8563:Volltext$zLF
1443855081:8563:Volltext$zLF
1570289085:8563:Volltext$zLF
1590295587:8563:Volltext$zLF
1590297040:8563:Volltext$zLF
1647485762:8563:Volltext$zLF
1649156235:8563:Volltext$zLF

**Comment by IxTheoKm** [comment]
@ruschein Vielen Dank! Die o.g. PPNs sind jetzt alle korrigiert. Es sind ja erfreulich wenige.

Ich habe allerdings recherchiert, dass außer "Volltext" noch weitere Begriffe vorkommen dürfen. 
Verstehe ich Ihre Liste richtig, dass Sie nur nach der Zeichenfolge "LF" gesucht haben (siehe Beispiel 824037359:8563:LF). Dann müssten alle Fälle erwischt worden sein.

**Comment by IxTheoKm** [comment]
Hier aus den MARC21-Schulungsunterlagen die Unterscheidung zwischen Druck und elektronischer Ausgabe:
![MARC21_Druck](https://user-images.githubusercontent.com/17004223/59098620-145bd700-8921-11e9-8bed-5afaa303ff42.JPG)

**Comment by ruschein** [comment]
@IxTheoKm Danke, und, ich hatte im Unterfeld 3 nur nach LF gesucht.

**Comment by ruschein** [comment]
Bitte auf Ptha testen.

**Comment by relhei** [comment]
Momentan wird das Ausgangsbeispiel immer noch nicht als "open access" angezeigt:
https://134.2.67.9/Search/Results?lookfor=Imperium+Romanum+und+r%C3%B6mische+Gemeinden&type=Title

**Comment by ruschein** [comment]
@relhei Da in 856 weder im Unterfelf z LF steht und auch nicht kostenfrei ist der Datensatz kein Beispeil für eine Open-Access Publikation oder habe ich da etwas übersehen?

**Comment by relhei** [comment]
Das liegt vmtl. daran, dass noch nicht alle Unterfelder von 856 ausgelesen werden.

In der WinIBW steht:
856 42$uhttps://doi.org/10.15496/publikation-17561$xResolving-System**$zKostenfrei$3Volltext**

In RelBib kommt an:

856 |   |   | \|u https://doi.org/10.15496/publikation-17561    \|x doi
-- | -- | -- | --

**Comment by ruschein** [comment]
@relhei Auf Ptah.

**Comment by relhei** [comment]
Sieht gut aus! Vielen Dank.
