### ISSUE TITLE
Unterschiedliche Meldungen für dieselbe Anfrage in der einfachen oder erweiterten Suche

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#76]
Werden Zahlenfolgen in der _einfachen Suche_ erfasst, kommt bei Nichttreffer die Rückmeldung "Keine Ergebnisse ..."
Das ist auch der Fall, wenn in der Zahlenfolge ein Bindestrich steht.
Bsp.:
id:11885408-9
11885408-9

In der _erweiterten Suche_ kommen bei Nichttreffer für diese Anfragen verschiedene Rückmeldungen:
Bsp.:
[Alle Felder:] id:11885408-9 --> "Keine Treffer ..."
[Alle Felder:] 11885408-9 --> "Es ist ein Fehler aufgetreten ..."

Die Folge ist auch, dass in der erweiterten Suche z.B. ISSN über alle Felder gesucht werden können, wenn kein Bindestrich eingegeben wird. Mit Bindestrich kommt die Fehlermeldung.
Bsp.:
[Alle Felder:] 15736121 -->741 Treffer
[Alle Felder:] 1573-6121 --> "Es ist ein Fehler aufgetreten ..."

Denkbar ist auch die Suche nach Zeitabschnitten wie 1900-2000

Warum führen Bindestriche in Zahlenfolgen in der erweiterten Suche zu Fehlermeldungen statt zur Meldung "Keine Ergebnisse ..."?

**Comment by ruschein** [comment]
@IxTheoKm Probieren Sie es bitte einmal mit Gänsefüschen um die Zahlen, vor allem wenn da noch Bindestriche bzw. Minuszeichen enthalten sind, zu versuchen.  Gibt es tatsächlich PPNs die Minuszeichen enthalten?

**Comment by IxTheoKm** [comment]
Dasselbe Ergebnis in der erweiterten Suche mit Anführungszeichen:
[Alle Felder:] "1573-6121" --> "Es ist ein Fehler aufgetreten ..." [hier sollte es 741 Treffer geben]
[Alle Felder:] "11885408-9" --> "Es ist ein Fehler aufgetreten ..." [hier sollte es "_keine Treffer ..._" geben]

Beispiele für PPNs mit Bindestrichen sind die PPNs der ZDB (Gesamtaufnahmen von Zeitschriften; damit hatte Ro gesucht und sich über die unterschiedlichen Meldungen gewundert):
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=2190527-7&type=AllFields&limit=20&sort=year+desc%2C+issue_sort+desc%2C+start_page+asc

Einfache Suche 
[Alle Felder]: **2190527-7** --> 691 Treffer

Erweiterte Suche:
[Alle Felder:] 2190527-7 --> "Es ist ein Fehler aufgetreten ..."
[Alle Felder:] "2190527-7" --> "Es ist ein Fehler aufgetreten ..."

**Comment by IxTheoKm** [comment]
Ergänzung:
Dieses Phänomen betrifft nicht zur Ziffernfolgen! Auch Bindestriche in Buchstabenfolgen führen mit oder ohne Anführungszeichen zu einer Fehlermeldung:
Bsp.:
Einfache Suche:
[Alle Felder:] Qumran-Texte --> 279 Treffer

Erweiterte Suche:
[Alle Felder:] Qumran-Texte --> "Es ist ein Fehler aufgetreten ..."
[Alle Felder:] "Qumran-Texte" --> "Es ist ein Fehler aufgetreten ..."

**Comment by IxTheoKm** [comment]
Ergänzung 2:
Dieses Phäneomen betrifft die erweiterte Suche generell:
man kann in keinem Suchfeld der erweiterten Suche mit Bindestrich suchen.

Bsp.:
Gerl-Falkovitz, Hanna-Barbara bzw. Hanna-Barbara Gerl-Falkovitz
(Alle Felder, Verfasser, Schlagwort, Titel] --> "Es ist ein Fehler aufgetreten ..."

**Comment by jriedl** [comment]
Sollte behoben sein.

**Comment by IxTheoKm** [comment]
Ist behoben, vielen Dank!
