### ISSUE TITLE
Unkorrekte Anzeige bei der Funktion "Zitieren"

### ISSUE THREAD

**Issue by AleAprile** [ubtue/tuefind#762]
Es kommt immer wieder vor, dass die vorgeschlagenen Zitationsmöglichkeiten, vor allem Chigago und MLA, unkorrekt sind. 

Klein/Großschreibung im Titel wird oft verändert, Erscheinungsort oder andere im Datensatz korrekt vorhandenen Angaben, etwa Bandzählung, werden oft nicht berücksichtigt, Leerzeichen werden nicht gesetzt etc...Auffälliger sind die Fehler bei Schriftreihen.

Hier ein paar Beispiele:
id:645418390
id:1567544363
id:1032254238

Der Meldung "Achtung: Diese Zitate sind unter Umständen nicht zu 100% korrekt" wird ja angezeigt. Wenn aber die Zitate nachgebessert werden, wäre benutzerfreundlicher.

**Comment by mtrojan-ub** [comment]
Der Issue wurde beim heutigen FID-Meeting besprochen. Er wird erstmal zurückgestellt und ggf. in einem DFG-Antrag aufgegriffen.

Hintergrund: Die Fehler in den hinterlegten Zitierstilen kommen zum Teil schon so von VuFind. Eigentlich müsste beim Generieren der Zitationen noch viel stärker zwischen Medienarten usw. differenziert werden. Das Thema müsste von Grund auf neu bearbeitet werden und dann ggf. auch auch vufind.org zur Verfügung gestellt werden.

**Comment by mtrojan-ub** [comment]
Ich denke dass dieser Issue mit einem anderen Issue zusammengeführt werden kann: #578
Und würde daher diesen Issue schließen und einen Verweis in den besagten Issue aufnehmen, damit die Informationen nicht verloren gehen.
