### ISSUE TITLE
Doppelte Anzeige von "Favoriten" in "Mein Konto"

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#763]
Nach Login im eigenen Konto werden die Favoriten auf der rechten Seite zweimal angezeigt: einmal im Block "Mein Konto" und einmal im Block "Meine Listen". 
![grafik](https://user-images.githubusercontent.com/25769591/59598225-fac64680-90fb-11e9-8f3d-5529f6622956.png)
Das ist m. E. nicht unbedingt notwendig, es reicht eine einmalige Anzeige unterhalb "Meine Listen". Und dann evt. auch eher "Alle Favoriten" (Englisch: "All saved items") anstelle von "Meine Favoriten" (Englisch "Saved items")? So wäre klar, dass damit keine extra Liste gemeint ist, sondern alle gespeicherten Treffer. 
Was meinen die anderen?

**Comment by mtrojan-ub** [comment]
Heute beim FID-Meeting besprochen: "Meine Favoriten" (unten) soll entfernt werden, Mareike testet dann auf ptah

**Comment by relhei** [comment]
Hab getestet: Es sieht besser aus. Wenn man die default-Liste mit "Favoriten" bedient, wird automatisch die Liste "Meine Favoriten" erzeugt. Im Unterschied zu vorher wird diese Liste aber nun nicht von vornherein angezeigt. Danke!
