### ISSUE TITLE
Keine Titelvorschläge mehr in der einfachen Suche

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#77]
Auf PTAH werden nun nicht mehr wie im IxTheo Titel zur Sucheingabe vorgeschlagen.
Ist das bewusst so eingerichtet?

![titelvorschlag](https://user-images.githubusercontent.com/17004223/33707977-782e5632-db39-11e7-8765-6c99bdc5d1b7.png)

**Comment by thefass** [comment]
siehe auch Issue #96

**Comment by IxTheoKm** [comment]
Scheint jetzt prinzipiell zu funktionieren - wenn auch manche Vorschläge recht abstrus scheinen. Das verbuche ich mal unter "Kreativität" des Systems:
![falkovitz](https://user-images.githubusercontent.com/17004223/34568768-1df770f6-f167-11e7-8379-45fffe7134f7.png)

Es gibt Festschriften für Hanna-Barbara Gerl-Falkovitz mit
655 7$aFestschrift$0(DE-588)4016928-5$0(DE-576)208917802$2gnd-content

Wählt man diesen "Schlagwort"vorschlag aus, kommt allerdings eine Fehlermeldung.
Ein Fall für einen neuen Issue?

**Comment by jriedl** [comment]
Fehlermeldung ist behoben. Vorschläge beschränken sich nun auf die für Facetten relevanten Unterfelder.

**Comment by IxTheoKm** [comment]
Fehlermeldung kommt jetzt tatsächlich nicht mehr. Die Vorschläge finde ich weiterhin mehr als merkwürdig, aber von den maßgeblichen Parametern verstehe ich nichts.
@thefass 
Ist das aus Nutzersicht tolerabel?

Ich Suche ein/zwei Autos und bekomme 1400 Garagen angeboten ...
![autocomplete](https://user-images.githubusercontent.com/17004223/34951430-9321b9b0-fa16-11e7-955b-52fdff57ccaf.png)

**Comment by thefass** [comment]
es kommen jetzt 329 sinnvolle Treffer:
https://www.ixtheo.de/Search/Results?limit=100&lookfor=hanna-barbara+gerl-falkovitz&type=AllFields
