### ISSUE TITLE
https://relbib.de/A-Z hat als Überschrift "IxTheo A-Z"

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#770]
![grafik](https://user-images.githubusercontent.com/26873381/60277962-dee25200-98fe-11e9-96a9-de5016c50f10.png)

gemeldet von @relhei

**Comment by mtrojan-ub** [comment]
kann getestet werden:
live (falsch): https://relbib.de/A-Z
test (richtig): https://134.2.67.9/A-Z

@relhei: passt das so?
Wenn wir es dann live schalten kann es eine Weile dauern, bis es bei Google ankommt.

**Comment by relhei** [comment]
Stimmt so. Danke!
