### ISSUE TITLE
Medienart falsch ausgelesen

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#776]
Es wurden 5 neue Aufnahmen für Videobeiträge erstellt, die in RelBib falsch unter der Medienart "Dia" erscheinen. 
![grafik](https://user-images.githubusercontent.com/25769591/60671116-adbfcf80-9e72-11e9-99b1-267ac10e7c29.png)

Bsp. in WinIBW:
![grafik](https://user-images.githubusercontent.com/25769591/60671169-cb8d3480-9e72-11e9-81a5-9ab200c1d302.png)

PPN des Bsp.: 1668450364

**Comment by IxTheoKm** [comment]
Ich meine, dass laut Formatdokumentation http://swbtools.bsz-bw.de/cgi-bin/k10plushelp.pl?cmd=kat&val=1140&katalog=Standard noch der Code "vide" in PICA 1140 erfasst werden und habe bei PPN 1668450364 ein Mailbox geschrieben. Ich werde aber aus der Exporttabelle nicht schlau, in welchem Marc-Feld das dann landet.

**Comment by ruschein** [comment]
Auf Ptah

**Comment by relhei** [comment]
Medienart "Video" ist jetzt drin, aber "Dia" auch noch...

**Comment by relhei** [comment]
Passt jetzt! Vielen Dank.
