### ISSUE TITLE
Abzugskriterien RelBib

### ISSUE THREAD

**Issue by Gazeller** [ubtue/tuefind#78]
Da hat sich wohl ein Fehler eingeschlichen oder ich verstehe die Angabe falsch:
![grafik](https://user-images.githubusercontent.com/16898788/33718651-7c95a3ae-db5e-11e7-9e37-ab6cc1d8c4c7.png)

Für RelBib sollen **nicht** DDC 220-289, sondern nur DDC 200-219 sowie DDC 290-299 berücksichtigt werden.

**Comment by ruschein** [comment]
Im code ist es so wie Du es beschreibst Gabi.  Habe den Wiki-Eintrag korrigiert.
