### ISSUE TITLE
Anzeige MARC-Feld 100 

### ISSUE THREAD

**Issue by socheres** [ubtue/tuefind#786]
bei https://ixtheo.de/Record/1582076421 
wird 100-Feld nicht angezeigt.

**Comment by ruschein** [comment]
Der Datensatz ist vermutlich falsch katalogisiert da Übersetzer vermutlich in das Feld 700 gehören.

**Comment by IxTheoKm** [comment]
Das Problem ist "Kommentarverfasser". Es handelt sich hier um einen "Verfasser". Übersetzer darf als zweite Beziehungskennzeichnung stehen bleiben. Ich habe den Datensatz korrigiert.

**Comment by socheres** [comment]
die Daten sehen nun korrekt aus.
