### ISSUE TITLE
PPN-Verknüpfung für Vorgänger / Nachfolger momentan nicht ausgelesen

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#789]
Bei Zeitschriften mit Vorgängern oder Nachfolgern, werden diese verlinkt im Volltitel der Zeitschriften-Gesamtaufnahme angezeigt. 
https://www.relbib.de/Record/500571422

Klickt man auf den Link, wäre ein Wechsel zur Zeitschriftengesamtaufnahme des Vorgängers bzw. Nachfolgers zu erwarten. Stattdessen wird allerdings eine Titelsuche ausgelöst, die u. U. mehrere Treffer zur Folge hat, das eigentlich gewünschte Ergbenis geht da nicht besonders nutzerfreundlich etwas unter:
https://www.relbib.de/Search/Results?lookfor=%22The+journal+of+Bible+and+religion%22&type=Title

Wäre es möglich, über die in den Feldern 780 und 785 angegebenen PPN (Unterfeld |w) zu verknüpfen?
![grafik](https://user-images.githubusercontent.com/25769591/61211092-dbbcd380-a6fe-11e9-9a03-ce26a7f834f0.png)

Quasi so wie es für die Verknüpfung zur Druckaufnahme praktiziert wird.

**Comment by thefass** [comment]
gute Idee!

**Comment by ruschein** [comment]
@relhei Von welcher Seite oder PPN kam die Titelsuche?

**Comment by ruschein** [comment]
@relhei Entweder verstehe ich hier etwas nicht richtig oder das Problem ist gelöst?  Meinst die bei [https://www.relbib.de/Record/500571422](https://www.relbib.de/Record/500571422) die Verlinkung auf die Druckausgabe?  Falls ja, ist das Problem behoben.

**Comment by IxTheoKm** [comment]
Gemeint ist nicht der Link zur Druckausgabe, der schon so eingerichtet ist.

Der Link zum Vorgänger und Nachfolger sollte analog eingerichtet werden:
also 780 und 785 sollten analog zu 776 direkt zum entspr. Datensatz verlinkt werden. Es sollte keine Titelsuche ausgeführt werden:

![vorg_nachf](https://user-images.githubusercontent.com/17004223/70432575-e5652000-1a7f-11ea-95aa-ab5516f38239.JPG)

**Comment by ruschein** [comment]
Auf https://ptah.ub.uni-tuebingen.de:4447/

**Comment by IxTheoKm** [comment]
Das ist ein KALDI-Link ???

In https://134.2.67.9/Record/500571422#details fehlt jetzt 780 und 785 komplett:

![780_785b](https://user-images.githubusercontent.com/17004223/73549754-84d0de80-4443-11ea-8652-49a7accefd29.JPG)

Im Internformat fehlen die Felder.

So sieht es korrekt aus:
https://www.relbib.de/Record/500571422#details

![780_785](https://user-images.githubusercontent.com/17004223/73549713-62d75c00-4443-11ea-95c4-d6b85d9d8a2d.JPG)

**Comment by ruschein** [comment]
https://ub26.uni-tuebingen.de/Record/500571422

**Comment by relhei** [comment]
Auf den Produktivsystemen funktioniert es - danke! Auf ptah allerdings funktioniert das nicht - warum? Der zuletzt geschickte Link auf ub26 weist wieder die anfangs beschriebene Problematik auf...

**Comment by IxTheoKm** [comment]
@ruschein Evtl. ein ähnliches Problem bei Feld 780 und 785 wie bei https://github.com/ubtue/tuefind/issues/421 und https://github.com/ubtue/tuefind/issues/1158 Feld 773?

**Comment by ruschein** [comment]
@relhei Wir haben die neueste Version des Codes auf dem Produktionssystem und da tut es auch jetzt noch.  Der Grund warum es auf Ptah nicht tut ist vermutlich weil wir die übergeordneten Werke kombinieren.  D.h., Du kannst dieses Issue schließen.

**Comment by IxTheoKm** [comment]
Durch Umsetzung von https://github.com/ubtue/tuefind/issues/1296 (Zusammenführung von Parallel-Ausgaben einschl. Vorgänger-Nachfolger-Beziehungen gelöst. Daher schließe ich.
