### ISSUE TITLE
Kurztitel fehlerhaft angezeigt

### ISSUE THREAD

**Issue by Gazeller** [ubtue/tuefind#79]
Zufallsfund bei Abfrage nach DDC 220 in RelBib:
2. Treffer hat ein bug
![grafik](https://user-images.githubusercontent.com/16898788/33720553-9ca53474-db64-11e7-993e-9f939e35e32b.png)

Die Volltextanzeige des Titels sieht normal aus.

**Comment by mtrojan-ub** [comment]
URL zum reproduzieren:
https://134.2.67.9/Search/Results?lookfor=220&type=CallNumber&limit=20&sort=year+desc%2C+issue+desc%2C+start_page+asc%2C+first_indexed+desc

**Comment by mtrojan-ub** [comment]
Ich halte das für ein Vufind4-Problem und habe daher einen Pull Request an vufind-org gestellt, siehe: https://github.com/vufind-org/vufind/pull/1088

**Comment by mtrojan-ub** [comment]
Demian Katz hat den Vorschlag bereits in die 4.1 übernommen :relaxed:  Kann jetzt auf ptah getestet werden

**Comment by thefass** [comment]
ok
