### ISSUE TITLE
Unklar - Übergang von Neuzugänge zu Gesamtdatenbank

### ISSUE THREAD

**Issue by Gazeller** [ubtue/tuefind#80]
Wenn man  in "Neuzugänge" recherchiert hat, ist der Weg zurück zur Datenbank nicht ersichtlich. Ging bei mir eben nur durch mehrfaches "Back" bzw. Neustarten der Datenbank. Selbst bei Klick auf RelBib Home (Schriftlogo) blieb Einstellung "Neuzugänge" erhalten.
Vielleicht könnte man "Neuzugänge" analog zu den Filtereinstellungen behandeln? Also rechts anzeigen und durch X weg klicken?

**Comment by Gazeller** [comment]
Wurde daran etwas gemacht? Heute kann man innerhalb der Neuzugänge keinen Suchbegriff mehr eingeben. Man kommt dann immer sofort auf die Gesamtdatenbank.
Beispiel: Neuzugänge 7 Tage + sSuchen = 238 Treffer
Eingabe "islam" im Suchfeld = 19.047 Treffer 
Einzige Möglichkeit Titel mit "islam" in 'Neuzugänge' zu finden ist heute über Filter (Schlagwort) 
![grafik](https://user-images.githubusercontent.com/16898788/33826163-5805fb48-de64-11e7-93e7-6c7c3b01f865.png)

Ist das so gewollt? Dann müsste der Filter in der alphabetischen Sortierung mindestens eine Möglichkeit bieten, direkt zu den Buchstaben zu springen. 
Eigentlich hatte ich mit dem _issue_ nur darum bitten wollen, dass der Pfad von Neuzugänge zurück zur Datenbank klar gemacht wird. Eine Recherche innerhalb der Neuzugänge wäre eigentlich schon gut.

**Comment by ruschein** [comment]
@Gazeller Nein, bisher haben wir da nichts gemacht.

An alle Nichtentwickler: Bitte setzt Assignees nie, das machen wir Entwickler selber.  Danke.

**Comment by jriedl** [comment]
Dass der Neuerscheinungsfilter bei einer neuen Suche noch gesetzt, war kein intendiertes Verhalten, sondern offenbar ein Bug, der jetzt nicht mehr auftritt. Eine Möglichkeit für Experten, eine bestimmte Suche auf Neuzugänge einzuschränken besteht in der Verwendung des first_indexed-Feldes in der Abfrage im Suchfeld: `Islam AND first_indexed:[NOW-30DAY TO NOW]` für die letzten 30 Tage.
