### ISSUE TITLE
JOP Dienst wird zweimal dargestellt

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#804]
Einmal reicht. Bitte zweite JOP Zeile entfernen. Siehe Screenshot

![Bildschirmfoto 2019-07-24 um 12 46 20](https://user-images.githubusercontent.com/14169098/61787977-42ce3c80-ae11-11e9-949c-f889eb7137f3.png)

Hier der direkte Link: https://ixtheo.de/Record/129525790

**Comment by mtrojan-ub** [comment]
Bei diesem Datensatz sind 3 ISSNs hinterlegt (eine davon ist doppelt), von daher wäre es gut wenn jemand einen Blick auf die Rohdaten wirft.

![grafik](https://user-images.githubusercontent.com/26873381/61790369-4664c200-ae17-11e9-8d7f-22532c301ec1.png)

Für die beiden eindeutigen ISSNs wird jeweils ein JOP-Block dargestellt. Das ist auch sinnvoll, es könnte ja sein dass die Abfrage nur über eine der beiden ISSNs erfolgreich ist.

Sollen wir ggf. die jeweilige ISSN noch mit anzeigen damit es klarer wird?

**Comment by thefass** [comment]
Müssen wir auf @IxTheoKm  warten

**Comment by IxTheoKm** [comment]
Die Datenerfassung ist korrekt:

In den ZDB-Erfassungsdaten wurden die ISSN differenziert in Vorlageformen (PICA-Feld 2010) und autorisierte ISSN (PICA-Feld 2005, nur von der DNB vergeben):
**2005** 0342-5517
**2010** 0342-5541
**2010** 0342-5517

Ausgeliefert werden aber alle ISSN im selben MARC-Feld 022 $a

**Comment by mtrojan-ub** [comment]
Interessanterweise haben sich mittlerweile die ISSNs bei diesem Datensatz in 022 geändert.
Es sind jetzt 3 verschiedene:

![grafik](https://user-images.githubusercontent.com/26873381/62872234-5e947680-bd1d-11e9-9cb6-3d48c5ee7b88.png)

Falls mehrere ISSNs vorhanden waren wurde bisher schon der Titel mit angezeigt, sofern dieser für die jeweilige ISSN vorhanden ist. Da dies aber nicht der Fall war (wie bei diesem Datensatz) gab es keine Anzeige und es entstand der Eindruck, dass der selbe Block mehrfach angezeigt wird.

Wir haben das so geändert, dass bei mehreren Einträgen jeweils die ISSN angezeigt wird, falls kein Titel verfügbar ist, siehe:

https://ptah.ub.uni-tuebingen.de/Record/129525790#details

Die Ergebnisse der Abfrage pro ISSN sehen ähnlich aus, das muss ja aber nicht pauschal für alle Datensätze gelten. Außerdem sind die URLs hinter den Icons auch in diesem Fall unterschiedlich, da es ja unterschiedliche ISSNs sind.

**Comment by thefass** [comment]
Prima gelöst
