### ISSUE TITLE
Sortierung der Zeitschriftenhefte eines Jahrgangs

### ISSUE THREAD

**Issue by KStelzel** [ubtue/tuefind#81]
Bisher wurde bei einer Zeitschrift das neueste Heft (bzw. Artikel daraus) zuerst angezeigt. Jetzt fängt die Sortierung mit Heft 1 eines Jahrgangs an. Bsp.: superior_ppn:106575325 
- http://sobek.ub.uni-tuebingen.de/Search/Results?lookfor=superior_ppn%3A106575325&type=AllFields
- https://krimdok.uni-tuebingen.de/Search/Results?lookfor=superior_ppn%3A106575325&type=AllFields&limit=20&sort=year

Die Sortierung nach aktuellem Heft zuerst ist logischer (zumal in der Anzeigeauswahl "Neueste zuerst").

**Comment by ruschein** [comment]
Vermutlich ist das ein reiner Zufall.  Bei IxTheo hingegen haben wir Sekundärkriterien ausgewertet welche zu einer besseren, weniger zufälligen Sortierung führen.  Diese Anpassung könnten wir eventuell nach dem Wechsel auf TueFind auch für KrimDok vornehmen.

**Comment by thefass** [comment]
Ja, bitte die Sekundärkriterien auch in der KrimDok implementieren

**Comment by KStelzel** [comment]
ja, bitte mit aufnehmen

**Comment by jriedl** [comment]
Ist auf sobek umgesetzt - vgl auch Issue #257:
https://sobek.ub.uni-tuebingen.de/Search/Results?lookfor=superior_ppn:079718906

**Comment by jriedl** [comment]
Wie besprochen.
