### ISSUE TITLE
Unterschiedliche Trefferanzahlen

### ISSUE THREAD

**Issue by KStelzel** [ubtue/tuefind#82]
Grundsätzlich ist die Gesamttrefferanzahl in Sobek leicht niedriger als in KrimDok (rund 200 Treffer weniger), was am Abzug liegen könnte.

Interessanterweise ist die Trefferzahl bei einer Titelsuche nach „Strafrecht“ in Sobek mit 4.641 Treffern deutlich höher als in KrimDok (3.279 Treffer): 
- http://sobek.ub.uni-tuebingen.de/Search/Results?lookfor=Strafrecht&type=Title&limit=20&sort=year
- https://krimdok.uni-tuebingen.de/Search/Results?lookfor=Strafrecht&type=Title&limit=20&sort=year

Gibt es dafür einen Grund?

**Comment by mtrojan-ub** [comment]
Beispiele für Treffer die nur auf sobek auftauchen:

![grafik](https://user-images.githubusercontent.com/26873381/34154111-b52d11f2-e4b4-11e7-849f-a1bbc29df473.png)

![grafik](https://user-images.githubusercontent.com/26873381/34154328-629d60e4-e4b5-11e7-9c27-cdc4cedc4af5.png)

Meine erste Vermutung ist, dass es etwas mit Stemming bzw. anderen Feldtypen in der neuen VuFind- oder Solr-Version zu tun hat. Das prüfe ich aber noch genauer.

**Comment by mtrojan-ub** [comment]
Weitere Recherchen haben folgendes ergeben:

Beim Zusammenführen der IxTheo- und der KrimDok-Konfiguration wurden auch Feldtypen vereinheitlicht. Konkret geht es um den Feldtyp "text", der von vielen Feldern verwendet wird (insbesondere auch von den Titelfeldern).

Die Spracheinstellung der "SnowballPorterFilterFactory" wurde von "English" auf "German2" verändert, da dies als Grundeinstellung im IxTheo so gesetzt war. Dadurch ergibt sich ein verbessertes Stemming-Verhalten bei der Suche.

Eine genauere Erklärung für "German" gibt's hier:
http://snowball.tartarus.org/algorithms/german/stemmer.html

(Für "German2" gelten zusätzliche Regeln für Umlaute, siehe auch:
http://snowball.tartarus.org/algorithms/german2/stemmer.html)
