### ISSUE TITLE
500 Treffer pro Seite

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#825]
Das Umstellen auf 500 Treffer pro Seite funktioniert nicht (immer).
Es kommt eine leere Seite. Gestern passierte das nur auf PTAH, heute auch im IxTheo/RelBib. 
Versucht man es mehrfach nochmals, funktioniert es ab und zu, aber eben nicht immer.
Auch nach langem Warten wird keine Seite aufgebaut.

**Comment by jriedl** [comment]
Einerseits hängt das wahrscheinlich damit zusammen, dass vorhin im Hintergrund noch der Import gelaufen ist, was ja im Regelfall tagsüber nicht der Fall ist. Weiterhin gilt, dass wir mit 500 Ergebnissen pro Seite am Limit dessen operieren, was im Prinzip für eine Anfrage an Speicher zur Verfügung steht und hier in bestimmten Fällen diese Grenze überschritten wird. Das dürfte auch der Grund sein, warum so große Ergebnismengen in Standard-VuFind nicht angeboten werden. Testweise habe ich jetzt auf ptah dieses Speicherlimit erhöht. Anfragen wie https://ptah/Search/Results?filter%5B%5D=%7Epublisher_facet%3A%22De+Gruyter%22&type=AllFields, die vorher zum Abbruch geführt haben, lassen sich jetzt erfolgreich abschließen. Auf dem Produktivsystem ub16 würde ich aus Sicherheitsagründen momentan in Anbetracht der aktuellen Ausstattung mit Arbeitsspeicher und der vorhandenen Last auf dem System allerdings abraten, das einfach so hochzusetzen.

**Comment by jriedl** [comment]
Anpassung ist jetzt auch auf ub16 erfolgt.

**Comment by IxTheoKm** [comment]
Funktioniert jetzt, danke.
