### ISSUE TITLE
Anzeige der Verfassernamen

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#826]
Die Lebensdaten werden dem Verfassernamen jetzt in der Kurz- und Vollanzeige vorangestellt.
Sie sollten wie bisher hinter dem Namen stehen.

![ptah_verf](https://user-images.githubusercontent.com/17004223/62619023-ffe28d80-b915-11e9-902b-fca2f91437b5.JPG)

![ptah_verf2](https://user-images.githubusercontent.com/17004223/62619029-04a74180-b916-11e9-87a9-f2c9ac80e3c7.JPG)

**Comment by jriedl** [comment]
Das Problem kommt daher, dass bei der Extraktion der Daten beim Import die Unterfelder in der Reihenfolge ihres Auftretens verknüpft werden werden. Im Regelfall steht das Unterfeld $d immer hinter dem Unterfeld $a. Bei diesen Records kommt 100$d allerdings ganz am Anfang des Feldes und damit vor 100$a. Die MARC-Seiten der LOC scheinen momentan nicht erreichbar. Ist jemandem bekannt, ob das in dieser Form noch noch gültiges MARC-21 ist?

**Comment by IxTheoKm** [comment]
Das ist etwas völlig schief/vermischt?!
Feld 100 im IxTheo hat nichts mit den Titeln zu tun!

Der erste Titel PPN 1642129178 hat einen völlig anderen Autor, PPN 1418205648 hat gar keine Lebensdaten:

100 |d 1934-  |e VerfasserIn  |0 (DE-588)132102994  |0 (DE-627)518136124   |0 (DE-576)298945517   |4 aut  |**a Blondel la Rougery    |g Firma**

**Lt. K10plus:**
nab a22 4500
001 501089527
003 DE-576
005 20180315110945.0
007 tu
008 180315s2017 xx ||||| o 00| ||swe c
035 $a(DE-627)1642129178
035 $a(DE-576)501089527
035 $a(DE-599)BSZ501089527
040 $aDE-576$bger$cDE-576$erda
041 $aswe
084 $a1$2ssgn
**100 1 $aNilsén, Anna$d1934-$eVerfasserIn$0(DE-588)132102994$0(DE-627)518136124$0(DE-576)298945517$4aut**
245 10$aNytt bokverk om Tyska ordens huvudsäte i Malbork$cAnna Nilsén
264 1$c[2017]
300 $bIllustrationen
336 $aText$btxt$2rdacontent
337 $aohne Hilfsmittel zu benutzen$bn$2rdamedia
338 $aBand$bnc$2rdacarrier
655 7$aRezension$0(DE-588)4049712-4$0(DE-627)106186019$0(DE-576)209083166$2gnd-content
773 08$iEnthalten in$tKyrkohistorisk årsskrift$dUppsala : Föreningen, 1900$g(2017), Seite 120-125$w(DE-627)129883654$w(DE-600)300470-3$w(DE-576)015180859$x0085-2619
787 08$iRezension von$tKościół Najświętszej Marii Panny na Zamku Wysokim w Malborku$z978-83-60518-79-3
787 08$iRezension von$tKaplica Św. Anny na Zamku w Malborku$z978-83-60518-80-9
787 08$iRezension von$tWieża Klesza i Domek Dzwonnika na Zamku Wysokim w Malborku$z978-83-60518-81-6
936 uw$j2017$h120-125
951 $aAR


100 |**d 1973-**    |0 (DE-588)1049428951    |0 (DE-627)781934168    |0 (DE-576)185054757    |a Oestigaard, Terje


**Lt. K10plus:**
cam a22 4500
001 1418205648
003 DE-627
005 20130303041450.0
007 tu
008 110803s2011 xx ||||| 00| ||eng c
020 $z9781407307909$9978-1-4073-0790-9
035 $a(DE-627)1418205648
035 $a(DE-576)348205643
035 $a(DE-599)BSZ348205643
035 $a(OCoLC)753106936
040 $aDE-627$bger$cDE-627$erakwb
041 $aeng
084 $a6,21$2ssgn
**100 1 $aOestigaard, Terje$0(DE-588)1049428951$0(DE-627)781934168$0(DE-576)185054757**
245 10$aHorus' eye and Osiris' efflux$bthe Egyptian civilisation of inundation c. 3000-2000 BCE$cTerje Oestigaard
264 1$aOxford$bArchaeopress$c2011
300 $a124 S.$bIll., Kt.$c30 cm
336 $aText$btxt$2rdacontent
337 $aohne Hilfsmittel zu benutzen$bn$2rdamedia
338 $aBand$bnc$2rdacarrier
490 1 $aBAR$aInternational series$v2228
591 $a5550: HDUB/s66 ; IMD-Felder und 1131 maschinell ergänzt (SWB)
689 00$Dg$0(DE-588)4068430-1$0(DE-627)106105639$0(DE-576)209173815$aÄgypten$gAltertum$2gnd
689 01$Ds$0(DE-588)4049396-9$0(DE-627)106187155$0(DE-576)209081880$aReligion$2gnd
689 02$Dg$0(DE-588)4042339-6$0(DE-627)106214926$0(DE-576)209049871$aNil$2gnd
689 03$Ds$0(DE-588)4293487-4$0(DE-627)104193352$0(DE-576)210952911$aÜberflutung$2gnd
689 04$Az$2gnd$aGeschichte 3000 v. Chr.-2000 v. Chr.
689 0 $5(DE-627)
830 0$aBAR / International series$v2228$92228$w(DE-627)130552151$w(DE-576)005734614$w(DE-600)783066-X$x0143-3067
935 $amteo
951 $aBO

**Comment by jriedl** [comment]
Das scheint mit fehlerhaften Normdaten zusammenzuhängen. Laut Titeldaten ist für 1642129178 die K10+-Autoren-Normdaten-PPN 518136124 (also für DE-627), bei uns in den Normdaten findet sich aber dafür aber nur eine alte BSZ-PPN (also DE-576) und die beschreibt offenbar die Firma "Blondel la Rougery". Deshalb die Ersetzung. Wir müssen jetzt abklären, wie überhaupt alte BSZ-Records als "Reste" in unseren Normdaten vorkommen können.

Für den zweiten Fall ist in den ursprünglichen Titeldaten noch das Geburtsdatum 1973 angegeben, seltsamerweise findet es sich aber nicht mehr in den Normdaten, weshalb das Unterfeld "d" als Rest des ursprünglichen Titels stehenbleibt. Kann korrekterweise der Fall auftreten, dass ein bereits vorhandenes Lebensdatum wieder entfernt wird?

**Comment by IxTheoKm** [comment]
Ja, das passiert i.d.R. bei noch lebenden Personen, bei denen aus Datenschutzgründen kein Geburtsjahr stehen darf. Es gibt Autoren, die ausdrücklich um Löschung bitten.

**Comment by jriedl** [comment]
Problem der fehlerhaften Normdaten sollte jetzt behoben sein. Zu dem zweiten Beschriebenen Fall
Die Problematik nicht mehr vorhandene Unterfelder beim Einfügen von SEKKOR-Abzügen ist ja schon in anderen Fällen aufgetaucht. Man müsste dann den Ansatz wählen, das komplette Feld zu löschen und durch die Angaben aus Normdatendifferenzabzug zu ersetzen.

**Comment by jriedl** [comment]
Um subtile Fehler durch die Ersetzung kompletter Felder zu vermeiden, würde ich vorschlagen, die Problematik entfernter Unterfelder im Rahmen von Komplettabzügen zu beheben.

**Comment by IxTheoKm** [comment]
"Blondel"-Fälle sind jetzt in Ordnung.
PPN 1418205648 ist mit der Voranstellung des Geburtsjahres noch nicht in Ordnung. 
![oestigaard](https://user-images.githubusercontent.com/17004223/63678096-c2737080-c7ee-11e9-87db-c76e5b6aad21.JPG)

Es wird dann wohl aber bei einem Komplettabzug behoben sein, weil das Geburtsjahr im Normsatz nicht mehr vorhanden ist.

Was mir weiterhin unklar ist:
warum steht bisher in 100 $d am Anfang, so dass das Geburtsjahr, wenn vorhanden, vorne steht?
![oestigaard2](https://user-images.githubusercontent.com/17004223/63678818-4aa64580-c7f0-11e9-81be-1aa062b3b3b7.JPG)

Mir scheint es aber ein Einzelfall zu sein. In der nach Verfassern sortierten Treffermenge taucht nur der "Ostigaard"-Fall auf. Daher denke ich auch, dass solche Fälle per Komplettabzug gelöst werden sollten und schließe.
