### ISSUE TITLE
Autorennamen in 249 $v und 505 $r

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#827]
Bei enthaltenen Werken in Zusammenstellungen werden die jeweiligen Autoren der Werke nicht angezeigt. Sie stehen in 249 $v sowie in 505 $r

Bsp.: 
PPN 1668215950
PPN 1664875271
PPN 1663217157 (zwei enthaltene Werke in einem Feld 249)
PPN 873534328

Bsp.:
![enth_werk_autor](https://user-images.githubusercontent.com/17004223/62627434-b4d27580-b929-11e9-9b18-f939d6cefa25.JPG)
![enth_werk_autor2](https://user-images.githubusercontent.com/17004223/62627444-b865fc80-b929-11e9-91f7-090696d00319.JPG)

Bsp. PPN 1663217157:
![enth_werk_autor4](https://user-images.githubusercontent.com/17004223/62628070-e992fc80-b92a-11e9-9610-426e64a3f3fc.JPG)
![enth_werk_autor5](https://user-images.githubusercontent.com/17004223/62628078-ebf55680-b92a-11e9-86a3-4da1f14174d8.JPG)

Die Autoren müssen im Anschluss an den Titel aufgeführt werden.
Bei Rezensionen wird der Autor von 787 $a am Ende in runden Klammern angezeigt. Das könnte hier analog erfolgen.
Bsp. PPN 154396236X

Anzeigebeispiel PPN 873534328 in K10plus:

![enth_werk_autor3](https://user-images.githubusercontent.com/17004223/62627458-bdc34700-b929-11e9-92a7-00914b42f33d.JPG)

**Comment by jriedl** [comment]
Ist umgesetzt außer dem Fall mit 1663217157. Dies lässt sich mit den vorhandenen Standardverfahren nicht abbilden und erfordert neuen Ansatz für die Art, wie die Felder ausgelesen werden.

**Comment by IxTheoKm** [comment]
PPN 1668215950, PPN 1664875271 und PPN 873534328 sind jetzt in Ordnung, danke.

Wie ist der Hinweis auf PPN 1663217157 zu verstehen? Soll daran noch etwas gedreht werden?

**Comment by jriedl** [comment]
Scheint durch @ruschein behoben.

**Comment by IxTheoKm** [comment]
Vielen Dank, ist jetzt perfekt!
