### ISSUE TITLE
Auffinden von Zeitschriften

### ISSUE THREAD

**Issue by KStelzel** [ubtue/tuefind#83]
1. British Journal of Criminology
In Sobek wird „british journal criminology“ wird die Zeitschrift nicht bei den ersten Treffern angezeigt. In KrimDok hingegen erscheint sie ab dem zweiten Treffer.
- http://sobek.ub.uni-tuebingen.de/Search/Results?lookfor=British+journal+criminology+&type=AllFields&limit=20&sort=year
- https://krimdok.uni-tuebingen.de/Search/Results?lookfor=British+journal+criminology&type=AllFields&limit=20&sort=year

2. American Sociological Review
Man kommt zu dieser Zeitschrift (ppn: 014855291 und 094425426), aber es ist nicht leicht - weder in Sobek noch in KrimDok.

**Comment by ruschein** [comment]
Da nur nach dem Jahr sortiert wird ist die Reihenfolge innerhalb eines Jahres willkürlich.  In IxTheo verwenden wir mittlerweise noch Sekundärkriterien wie Issuenummer etc.
Zu 1. Bei einer akutellen auf Sobek kommen jetzt schon Treffer mit "british journal criminology" ab der 2. Position.  Was auch berücksichtigt wird sind Teffer im Volltext was nicht unnedingt leicht nachvollziehbar ist und auch nicht im Highlighting erscheint.

**Comment by thefass** [comment]
In diesen Fällen Anführungszeichen helfen (""). Und dann eine Einschränkung der Medienart auf Zeitschriften:
https://krimdok.uni-tuebingen.de/Search/Results?lookfor=%22British+Journal+of+Criminology%22&type=AllFields&limit=20&sort=year+desc%2C+issue_sort+desc%2C+start_page+asc

https://krimdok.uni-tuebingen.de/Search/Results?lookfor=%22American+Sociological+Review%22&type=AllFields&filter%5B%5D=format%3A%22Journal%22

@KStelzel: reicht das?

**Comment by thefass** [comment]
auf Sobek funktioniert die Suche mit "" nicht:

http://sobek.ub.uni-tuebingen.de/Search/Results?lookfor=%22British+journal+criminology%22&type=AllFields&limit=20&sort=year+desc%2C+issue_sort+desc%2C+start_page+asc

**Comment by jriedl** [comment]
Die Zeitschrift heißt "British journal **of** criminology". Da es mit Anführungszeichen eine Phrasensuche ist, muss das exakt sein. http://sobek.ub.uni-tuebingen.de/Search/Results?lookfor=%22british+journal+of+criminology%22&type=AllFields&filter%5B%5D=format%3A%22Journal%22

**Comment by KStelzel** [comment]
@thefass und @jriedl: ja, das reicht als Info. Danke!

**Comment by thefass** [comment]
@jriedl: thanks!
