### ISSUE TITLE
Alphabetisch browsen nach Titel - Spaltenbreite

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#831]
Lassen sich die Spalten der Tabelle beim Browsen verschieben?
Für die Titel, die z.T. sehr lang sein können, ist wenig Platz. Für Format, Erscheinungsjahr und Ergebnis würden schmalere Spalten reichen.

![browse](https://user-images.githubusercontent.com/17004223/62761222-5a9af700-ba86-11e9-9279-bb660df63e65.JPG)

**Comment by mtrojan-ub** [comment]
Die Breite der Titelspalte wurde nun für Auflösungen ab 768px auf 40% erhöht (siehe ptah).

![grafik](https://user-images.githubusercontent.com/26873381/62932693-ef705e00-bdc0-11e9-8db2-975a62507ae9.png)

**Comment by IxTheoKm** [comment]
Sieht besser aus, danke.
