### ISSUE TITLE
Alphabetisch browsen nach Titel - Titel werden nicht gefunden

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#832]
Titel werden nur gefunden, wenn man sie ohne Leerzeichen zwischen den einzelnen Stichwörtern sucht. Soll das so bleiben? Das ist zumindest nicht selbsterklärend und müsste ggf. deutlich hervorgehoben werden. Ich finde das aber nicht benutzerfreundlich:

![browse6](https://user-images.githubusercontent.com/17004223/62763581-3215fb80-ba8c-11e9-98aa-be1191503db8.JPG)

Weitere Beispiele für eine vergebliche Suche nur mit dem ersten Wort:

**PPN 1644696150** [Druckausgabe, mit Sortierzeichen erfasst]
4000 Die @Auseinandersetzung mit den internen und äußeren Opponenten in mittelalterlicher-jüdischer Schriftauslegung
**245 14$a**Die Auseinandersetzung mit den internen und äußeren Opponenten in mittelalterlicher-jüdischer Schriftauslegung

**PPN 1523195770** [Online-Ausgabe, ohne Sortierzeichen erfasst]
4000 Die Auseinandersetzung mit den internen und äußeren Opponenten in mittelalterlicher-jüdischer Schriftauslegung
**245 10$a**Die Auseinandersetzung mit den internen und äußeren Opponenten in mittelalterlicher-jüdischer Schriftauslegung

![browse2](https://user-images.githubusercontent.com/17004223/62762124-a6e73680-ba88-11e9-96bf-4a86a71ded61.JPG)

![browse3](https://user-images.githubusercontent.com/17004223/62762130-ac448100-ba88-11e9-83ba-dc6b62bf22ee.JPG)

**Comment by jriedl** [comment]
Auf ptah findet sich nun eine Version der Titelsuche, die nun als Schlüssel für den Einsprung den "echten" Titel verwendet. Leerzeichen werden damit beachtet.

**Comment by IxTheoKm** [comment]
Jetzt in Ordnung, danke!

Grundsatzproblem der Mitsortierung von Artikeln ist der unterschiedlichen Datenerfassung mal mit und mal ohne Sortierzeichen geschuldet
(siehe https://github.com/ubtue/tuefind/issues/833)
