### ISSUE TITLE
Alphabetisch browsen nach Titel - Abweichende Titel

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#834]
Auch Nebentitel 246 $a müssen in diesen Index einfließen. Sie fehlen bisher.

Bsp.:
https://ixtheo.de/Record/166757144#details

![browse7](https://user-images.githubusercontent.com/17004223/62764001-2a0a8b80-ba8d-11e9-830e-0582fa652c59.JPG)

![browse8](https://user-images.githubusercontent.com/17004223/62764823-13653400-ba8f-11e9-96dc-112315b1b022.JPG)

![browse6](https://user-images.githubusercontent.com/17004223/62764830-17915180-ba8f-11e9-8dba-e22fac53a155.JPG)

**Comment by mtrojan-ub** [comment]
Ich habe versucht das über solrmarc-Konfiguration zu lösen, komme aber nicht weiter und warte auf eine Rückmeldung auf meine Anfrage in der solrmarc-tech mailingliste.

**Comment by jriedl** [comment]
Es fließen jetzt auch die in title_alt (100t:130adfgklnpst:240a:246a:505t:700t:710t:711t:730adfgklnpst:740a) extrahierten Werte in das alphabetische Browsen ein. Auf ptah sollte dies nach dem nächsten Import voraussichtlich morgen früh sichtbar sein.

**Comment by jriedl** [comment]
Sowohl die Schreibweise mit also auch ohne "the" des o.g. titels fließt nun ein.

**Comment by IxTheoKm** [comment]
Jetzt in Ordnung, danke!
