### ISSUE TITLE
Exportfunktion in RIS bei mehreren Titelauswahl 

### ISSUE THREAD

**Issue by socheres** [ubtue/tuefind#846]
>  Wenn ich mehrere Titel auswähle und auf Exportieren --> RIS  
Export --> Herunterladen klicke, öffnet sich nur eine leere Seite

Wenn ich nur einen Titel auswähle, funktioniert aber der Export.

**Comment by jriedl** [comment]
Sollte behoben sein.

**Comment by socheres** [comment]
ja, ist der Fall.
