### ISSUE TITLE
Stark abweichende Trefferzahlen

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#86]
Eine Suche nacht testament hat im IxTheo folgende Trefferzahl:
![bildschirmfoto 2017-12-08 um 21 52 40](https://user-images.githubusercontent.com/14169098/33784738-2f564792-dc62-11e7-800d-605143a2368d.png)

In Ptah nur 15
![bildschirmfoto 2017-12-08 um 21 53 40](https://user-images.githubusercontent.com/14169098/33784761-498acdfe-dc62-11e7-9a46-b99a8265fad0.png)

**Comment by thefass** [comment]
Auch nach Lösung der Pipeline-Probleme auf ptah wichen die Treffer stark ab, allerdings nun völlig anders.
Einfache Suche über alle Felder:
![bildschirmfoto 2017-12-11 um 22 38 39](https://user-images.githubusercontent.com/14169098/33855069-1aa09d34-dec4-11e7-8d2e-646a6c30215a.png)

![bildschirmfoto 2017-12-11 um 22 39 31](https://user-images.githubusercontent.com/14169098/33855097-36cf6d50-dec4-11e7-9778-1dd41f24ffa5.png)

Auf ptah also dopplet soviele Treffer wie auf Ixtheo

Ähnlich bei einer Suche über Aspekt Schlagwort:
![bildschirmfoto 2017-12-11 um 22 40 53](https://user-images.githubusercontent.com/14169098/33855195-7f277c96-dec4-11e7-9ff2-68a1e597f683.png)

![bildschirmfoto 2017-12-11 um 22 41 17](https://user-images.githubusercontent.com/14169098/33855200-836def88-dec4-11e7-9b13-1af847e12e0e.png)

**Comment by ruschein** [comment]
@thefass Die Frage ist jetzt welches Trefferanzahl ist korrekt?  Gibt es auf Ptah Treffer die falsch sind?  TueFind basiert auf einer neueren Version von VuFind.  Könnt Ihr auch nur einen Treffer auf Path finden der nicht korrekt ist.  Falls nicht liegt es nahe, dass die Zahlen auf Ptah die richtigen sind.

**Comment by Gazeller** [comment]
bei RelBib sind bei einer **leeren Suche** seit 3 Tagen die Trefferzahlen auf ptah und relbib identisch

**Comment by thefass** [comment]
sowohl bei allgemeiner als auch bei SW oder Titel Suche sind die Treffer nun zwischen IxTheo und Ptah gleich. Da sie mit der Anzahl der oben schon genannten IxTheo Treffer übereinstimmen, muss es auf ptah zwischenzeitlich falsche Treffer gegeben haben.
@ruschein habt ihr etwas verändert, was das erklären könnte?

**Comment by ruschein** [comment]
Wir hatten mehrere Bugs die zu Problemen in der Pipeline und beim Import geführt hatten.  Leider kann ich nicht sagen welche Änderung für den Unterschied bei den Zahlen verantwortlich ist.  Die Bugs in der Pipeline hatten auch dzu geführt, dass die Anzahl der Datensätze in TueFind zuim Teil viel zu klein waren.

**Comment by thefass** [comment]
ok
