### ISSUE TITLE
trunkierte Suche funktioniert nicht auf ptah

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#87]
![bildschirmfoto 2017-12-08 um 21 56 08](https://user-images.githubusercontent.com/14169098/33784840-a9679590-dc62-11e7-94d3-9c746664cac4.png)
Ergebnis: https://www.ixtheo.de/Search/Results?lookfor=Dogma*&type=AllFields&limit=20&sort=year+desc%2C+issue_sort+desc%2C+start_page+asc

Ptah:
![bildschirmfoto 2017-12-08 um 21 57 04](https://user-images.githubusercontent.com/14169098/33784862-c4fb4dce-dc62-11e7-97e6-0c971aca2334.png)

https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=dogma*&type=AllFields&limit=20&sort=year+desc%2C+issue_sort+desc%2C+start_page+asc

**Comment by jriedl** [comment]
Kann ich momentan nicht reproduzieren. Obiger Link auf ptah liefert  14,736 Treffer.

**Comment by thefass** [comment]
Das Problem dürfte auch an den fehlenden Daten gelegen haben. Ist jetzt in Ordnung
