### ISSUE TITLE
Zu viel SPAM bei Feedback-Emails

### ISSUE THREAD

**Issue by ruschein** [ubtue/tuefind#875]
Es gibt immer wieder Beschwerden, dass der Großteil der Feedback-Emails Spam sind.  Eine Lösung wäre ein Einloggen zu erzwingen.  Man könnte im nichteingeloggten Zustand eine Meldunbg anzeigen, die das Problem erkärt und die Anwender bittet sich einzulogen.  Andere, wesentlich aufwendigere [Alternativen zu Captcha sind](https://www.dtelepathy.com/blog/design/captcha-alternatives-better-ux).

**Comment by mtrojan-ub** [comment]
In VuFind gibt es standardäßig die Möglichkeit, Google APIs einzubinden. Allerdings können wir nicht ausschließen, dass dann personenbezogene Daten an Google übermittelt werden. Diese Möglichkeit wurde daher in der Diskussion per E-Mail ausgeschlossen, ich werde bei Gelegenheit auf die o.g. Liste mit Alternativen werfen.

**Comment by IxTheoKm** [comment]
Die Spam-Mails über Feedback nehmen aktuell wieder zu, nachdem es (nur sehr kurzfristig) etwas weniger geworden war.

**Comment by thefass** [comment]
Mit @ruschein mündlich besprochen: wir verwenden ein eigenes, einfaches mathematisches Captcha (Addition oder Subtraktion)

**Comment by mtrojan-ub** [comment]
Wie sich herausgestellt hat gibt es im Zend Framework ein Image CAPTCHA, das wir mit etwas Arbeit in VuFind einbinden konnten. Es kann jetzt auf den Testservern ausprobiert werden:

![grafik](https://user-images.githubusercontent.com/26873381/71896834-10ad5e80-3155-11ea-9167-ca15b3594486.png)

Die Komplexität des Bildes können wir per Einstellung erhöhen oder reduzieren (also Anzahl der Zeichen + Komplexitätslevel fürs "Rauschen", also Punkte und Linien).
Es ist auf den Testservern für alle Feedback + Anschaffungsvorschlags-Formulare in allen Instanzen aktiv.

**Comment by IxTheoKm** [comment]
Keine Chance, irgendein Feeback zu schicken. Meist kommt folgende Meldung:

![feedback](https://user-images.githubusercontent.com/17004223/71979409-ef647500-321d-11ea-8dcc-e1a0289442f7.JPG)

Seltener diese:

![feedback2](https://user-images.githubusercontent.com/17004223/71979436-030fdb80-321e-11ea-8e38-c13bf85a3138.JPG)

**Comment by mtrojan-ub** [comment]
... wurde behoben, bitte nochmal testen.

(Der Code war in Ordnung, aber nach der Neuinstallation von ptah auf CentOS 8 war der Postfix-Mailserver noch nicht eingerichtet).

"CAPTCHA nicht korrekt eingegeben" ist übrigens die deutsche Fehlermeldung die angezeigt wird wenn man die Zeichenkette nicht richtig abgeschrieben hat. Der Text kommt standardmäßig so aus VuFind.

**Comment by IxTheoKm** [comment]
Alle Tests sind jetzt angekommen!
Die Zeichenketten waren jetzt auch besser lesbar (evtl. nur Zufall).

**Comment by thefass** [comment]
Funktioniert auch beim Anschaffungsvorschlag.
Jedoch nerven an dieser Art von Captcha, dass viele auch bei bestem Willen nicht richtig interpretiert werden können. Zwei Beispiele, die ich falsch eingeben habe:

![Bildschirmfoto 2020-01-08 um 14 21 43](https://user-images.githubusercontent.com/14169098/71981664-1f624700-3223-11ea-9600-7f6023aa09b6.png)
Hier ist das Problem, dass die Zeichenketten abgeschnitten sind und deswegen so oder so verstanden werden können.

![Bildschirmfoto 2020-01-08 um 14 24 32](https://user-images.githubusercontent.com/14169098/71981739-4751aa80-3223-11ea-8b82-83fca4ae2c13.png)
war auch falsch, vermutlich das dritte Zeichen. Aber was soll das sein, außer einem o?

@mtrojan-ub Könnt Ihr da was machen? Manchmal sieht man, dass man ein weiteres (anderes) Captcha anfordern kann, wenn man auf einen Blick sieht, dass das angezeigte nicht richtig gelöst werden kann.

**Comment by IxTheoKm** [comment]
Abgeschnittene Zeichen warem auch mein Problem: das dritte Zeichen im zweiten Beispiel könnte beim genauen Hinsehen und mit viel Phantasie ein p sein. Es dürfen m.E. keine abgeschnittenen Zeichen vorkommen.

**Comment by mtrojan-ub** [comment]
Ist behoben, bitte nochmal testen.

Hintergrund: Mit Standardeinstellungen hat die Grafik eine Höhe von 50 bei einer Schriftgröße von 24 Pixeln. Ich habe die Höhe auf 75 Pixel erhöht und das Rauschen reduziert.

**Comment by thefass** [comment]
wesentlich besser. Probleme gibt es bei der Unterscheidung von i und l (Kleinbuchstabe L). 
diese Buchstaben wird man aber nicht auschließen können, oder @mtrojan-ub ?

**Comment by mtrojan-ub** [comment]
Doch, kann man und ist geändert!

**Comment by IxTheoKm** [comment]
Bei mir haben nun alle Feedback-Tests auf Anhieb funktioniert.

**Comment by thefass** [comment]
Ja, ist jetzt ok. was man alles konfigurieren kann. Danke!
Bitte noch die Fehlermeldung ins Englische, Italienische, Französische übersetzen (lassen). Oder einfach nur aktivieren, wenn das in VuFind schon integriert ist?

![Bildschirmfoto 2020-01-08 um 16 06 58](https://user-images.githubusercontent.com/14169098/71989058-3c9e1200-3231-11ea-84d3-c0c31bc34ec3.png)

**Comment by mtrojan-ub** [comment]
Die Meldung "Bitte füllen Sie dieses Feld aus." wird vom Browser gesetzt. Es ist ein Standardfeature in HTML5. Die Sprache der Meldung ändert sich also nur, wenn man in seinem Browser die Sprache anpasst. 

siehe auch:
https://www.w3schools.com/tags/att_input_required.asp

Beispiel Firefox (in "about:preferences"):
![grafik](https://user-images.githubusercontent.com/26873381/71994666-6c511800-3239-11ea-8852-7e42ecdeeb1b.png)

**Comment by thefass** [comment]
Ich habe das neue Thema Mehrsprchigkeit in eigenes Issue übernommen. #1055 
Schließe das Captcha Issue
