### ISSUE TITLE
Titelvollanzeige kann nicht aufgerufen werden

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#883]
Auf Benutzerhinweis wollte ich folgenden Titel aufrufen, um ihn danach als nicht relevant im K10plus zu kennzeichnen (935 mtex statt mteo):
https://ixtheo.de/Search/Results?lookfor=id%3A53961548X&type=AllFields&limit=20&botprotect=
oder 
https://ixtheo.de/Search/Results?lookfor=romantik+in+heidelberg&type=Title&botprotect=

![PPN53961548X](https://user-images.githubusercontent.com/17004223/65435075-2bff9280-de20-11e9-918e-0817f136b221.JPG)

Es kommt eine Fehlermeldung beim Versuch, die Vollanzeige aufzurufen.

**Comment by ruschein** [comment]
Fehler tritt hier auf: /usr/local/vufind/module/TueFind/src/TueFind/RecordDriver/SolrMarc.php in Funktion getReferencesFrom787().
