### ISSUE TITLE
936 bk $j Basisklassifikation

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#886]
Bei den Issues der zu bereinigenden Daten liegt noch die Liste der vermeintlich falsch erfassten "Jahresangaben": https://github.com/ubtue/fid/issues/4  

Das ist aber vermutlich keine Falscherfassung sondern ein korrekt erfasster anderer Inhalt:
keine Jahresangabe, sondern die Basisklassifikation. (Siehe Exporttabellenauszug auf https://github.com/ubtue/fid/issues/4)

Wenn dem bei allen ca. 170 Datensätzen so ist, kann das Issue zur Bereinigung von Daten dort geschlossen werden. 
Feld 936 bk $j muss als Basisklassifikation angezeigt werden.

**Comment by ruschein** [comment]
@IxTheoKm Besteht hier noch Handlungsbedarf?

**Comment by thefass** [comment]
@IxTheoKm nächste Woche wieder zurück

**Comment by IxTheoKm** [comment]
936 bk ist im Internformat vorhanden. Von daher nun kein Handlungsbedarf mehr.

Parallel dazu existiert aber 084, von dem ich nicht weiß, wozu das dient. 
Hier weicht es in Teilen ab von 936 rv mit 084 $2 rvk $0...: 
Bei 084 $2 bk fehlt $0

Wenn das für irgendwas gebraucht wird, besteht Handlungsbedarf.
Sonst kann das Issue geschlossen werden.

Bsp.:
https://ixtheo.de/Record/1040880940#details

![936bk](https://user-images.githubusercontent.com/17004223/69960632-3d44d980-150a-11ea-8f6d-4f048ab7efe4.JPG)

![936bk_2](https://user-images.githubusercontent.com/17004223/69960635-40d86080-150a-11ea-9d2b-e28ee44149e8.JPG)

**Comment by ruschein** [comment]
Da 084$0 von uns nicht ausgewertet wird schließe ich diesen Issue.
