### ISSUE TITLE
AcquisitionRequest-Mail geht an die falsche Adresse

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#894]
Auf dem Live-Server ist folgende Einstellung gesetzt (local_overrides):
acquisition_request_receivers = "ixtheo-pda@ub.uni-tuebingen.de"

Mails aus dem zugehörigen Formular scheinen aber trotzdem an die standard-Adresse geschickt zu werden:
ixtheo@ub.uni-tuebingen.de

**Comment by mtrojan-ub** [comment]
... kann auf ptah getestet werden. Allerdings die Konfiguration dort momentan so, dass acquisition_request_receiver einzig und allein auf die E-Mail-Adresse von @thefass zeigt.

**Comment by IxTheoKm** [comment]
Sowohl auf PTAH als auch nochmal im IxTheo getestet: von PTAH kommt jetzt nichts mehr über die Adresse "ixtheo". Von daher korrekt.

Ob für PDA und andere Anschaffungsvorschläge ein eigener Funktionsaccount angelegt werden soll, hatte @thefass am 9.7. über den Verteiler ixtheo2 gefragt. Ob das jemand geklärt hat, weiß ich nicht.
