### ISSUE TITLE
ppn Liste von Aufsatzsammlungen 

### ISSUE THREAD

**Issue by Gazeller** [ubtue/tuefind#896]
Zur Vorbereitung des  FID-RW Teilprojekts 'Erschließung von Sammelschriften' mit Imageware bitte ich um eine Liste, die folgende Kategorien berücksichtigen bzw. Aussagen beinhalten soll:
PICA 5056 (MARC 650) = SSG-Nr "0"
PICA 1131 (MARC 655) = "Aufsatzsammlung" OR "Festschrift" OR "Konferenzschrift"
Die Liste soll enthalten: 
1. ppn
2. Titel (ggf gekürzt)
3. Inh.Verzeichnis (IHV): ja/nein
4. Zahl der bereits enthaltenen Aufsätze 0, 1,2 ... X
5. Jahr

**Comment by thefass** [comment]
Ich ergänze zu Punkt 3:
Kriterium für das Vorhandensein eines IHV an einem Datensatz ist  856 $3Inhaltsverzeichnis 
![Bildschirmfoto 2019-09-27 um 15 07 14](https://user-images.githubusercontent.com/14169098/65771468-8d817300-e138-11e9-8b98-4e1e8c79cab5.png)

Quelle: https://relbib.de/Record/1664818324#details

**Comment by ruschein** [comment]
Hallo Gabi,


hier ist die von Dir benötigte Liste.


Gruß,

Johannes

--
Dr. Johannes Ruscheinski
Universitätsbibliothek Tübingen - IT-Abteilung -
Wilhelmstr. 32, 72074 Tübingen

Tel: +49 7071 29-72820
FAX: +49 7071 29-5069
Email: johannes.ruscheinski@uni-tuebingen.de

 The Sophisticate:  "The world isn't black and white.  No one does pure good or pure bad. It's all gray.  Therefore, no one is better than anyone else."
    The Zetet:  "Knowing only gray, you conclude that all grays are the same shade.  You mock the simplicity of the two-color view, yet you replace it with a one-color view..."
      —Marc Stiegler, David's Sling


________________________________

**Comment by ruschein** [comment]
@Gazeller Hallo Gabi, was war hier noch falsch oder kann man das Issue zumachen?

**Comment by Gazeller** [comment]
Hallo, ich konnte die am 2.10. per E-Mail geschickte Liste nach einigem Hin+Her öffnen und stelle fest, dass wohl das Hauptkriterium, nach welchem die Liste erstellt werden sollte, abhanden gekommen ist: 
In einem ersten Schritt möchten wir nur die Aufsatzsammlungen, die das **SSG Zeichen "0"** enthalten. Der Übersicht halber, schicke ich hier noch einmal die Kriterien gebündelt:

MRC 650 = SSG-Nr "0" [Pica 5056]
MRC 655 = "Aufsatzsammlung" OR "Festschrift" OR "Konferenzschrift" [Pica 1131]
Die Liste soll enthalten:
  1.  ppn
  2.  Titel (ggf gekürzt)
  3.  Inh.Verzeichnis (IHV): ja/nein -> MRC 856 $3Inhaltsverzeichnis
  4.  Zahl der bereits enthaltenen Aufsätze 0, 1,2 ... X
  5.  Erscheinungsjahr

**Comment by Gazeller** [comment]
Neue Liste erhalten (email) - jedoch neuer Fehler: Nun sind u.a. alle Zeitschriften mit ihren Aufsätzen drin! Aufsatzsammlung / Festschrift / Konferenzschrift sind jedoch Monografien. Zusätzliche Abfrage nach Monografie nötig!

**Comment by ruschein** [comment]
@Gazeller Kann dieses Issue jetzt geschlossen werden?
