### ISSUE TITLE
Sonderdrucke von Aufsätzen werden als Buch angezeigt

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#899]
Leider finde ich keinen Issue zu diesem Thema, vielleicht ist das nie über GitHub gelaufen:

sollen nicht "Monographienaufnahmen" mit dem Abrufzeichen für Sonderdrucke als Aufsätze angezeigt werden?

Das ehemalige Abrufzeichen "sodr", jetzt 935 $c **so**, ist nach meiner Erinnerung Kriterium dafür.

Trotzdem werden z.B. folgende Titel als Buch deklariert:

https://ixtheo.de/Search/Results?lookfor=Etlich+Artickel+Gottes+Lob+und+des+heyligen+r%C3%B6mischen+Reichs&type=AllFields&limit=20&botprotect=

https://ixtheo.de/Record/1154854205

https://ixtheo.de/Search/Results?lookfor=semitische+Perfect+im+Assyrischen&type=AllFields&limit=20&botprotect=

https://ixtheo.de/Record/1353146774

**Comment by ruschein** [comment]
@IxTheoKm PPN 1383928630 hat noch sodr in 935$c.

**Comment by ruschein** [comment]
Behoben auf Ptah.

**Comment by IxTheoKm** [comment]
Jetzt auf Ptah in Ordnung, danke.
