### ISSUE TITLE
Medienart / Format: Abweichungen in Ptah

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#90]
Es gibt momentan Abweichungen bei den Foci in der Facette Medienart bzw. Format (engl.) zwischen Ptah und RelBib bzw. IxTheo. In Ptah werden momentan keine Reviews aufgeführt. 
Zusätzlich angezeigt werden "Microfiche" (Ptah RelBib und Ptah IxTheo) und "Lexikonartikel" (nur Ptah IxTheo), die bisher nicht in RelBib und IxTheo auftauchen.

Bsp. für RelBib / Ptah:

![grafik](https://user-images.githubusercontent.com/25769591/33929768-f2a534ac-dfea-11e7-9399-17cd16a2c062.png)

![grafik](https://user-images.githubusercontent.com/25769591/33929791-05f76052-dfeb-11e7-821d-0a5e0c7ba94c.png)

**Comment by jriedl** [comment]
Reviews werden jetzt wieder gesondert ausgewiesen.

**Comment by relhei** [comment]
Passt. Danke!
