### ISSUE TITLE
Glockensymbol für das Alerting fehlt...

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#904]
... bei "Zwitter-"Zeitschriften(?) auf PTAH.

Bsp.:
https://ptah.ub.uni-tuebingen.de/Record/770030149
![glocke](https://user-images.githubusercontent.com/17004223/66382620-d6002280-e9bb-11e9-9bcb-0ce4628392c4.JPG)

https://ixtheo.de/Record/12948590X
![glocke2](https://user-images.githubusercontent.com/17004223/66382815-1f507200-e9bc-11e9-90a7-09ae1662d474.JPG)

**Comment by mtrojan-ub** [comment]
Die Ursache besteht **nicht** darin, dass es sich um eine Zwitter-Zeitschrift handelt.

In Beispiel 1 wird über 008 ermittelt ob es sich bereits um eine abgeschlossene Zeitschrift handelt ( die Stellen 12-16 werden gegen "9999" verglichen). Bei abgeschlossenen Zeitschriften ist kein Alerting möglich.

Nach Absprache mit @ruschein werden wir hier bei Gelegenheit eine entsprechende Meldung anzeigen.

(Beispiel 2 ist laut obiger Definition keine abgeschlossene Zeitschrift, daher ist auch das Alerting möglich).

**Comment by mtrojan-ub** [comment]
Das Merging-Problem wurde behoben.

In der Kurztitelanzeige wird der Datensatz jetzt mit Glockensymbol dargestellt. Allerdings gibt es in der Volltitelanzeige noch Probleme.

- ixtheo: https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=ids%3A1671030923&type=AllFields&limit=20&sort=author&botprotect=
- relbib: https://134.2.67.9/Search/Results?lookfor=ids%3A1671030923&type=AllFields&botprotect=

Kurztitelanzeige:
![grafik](https://user-images.githubusercontent.com/26873381/67929798-7a8e1280-fbbe-11e9-99bb-a9087fc94055.png)

Volltitelanzeige ixtheo (button fehlt):
![grafik](https://user-images.githubusercontent.com/26873381/67929837-9db8c200-fbbe-11e9-8a6b-9ba295b00da8.png)

Volltitelanzeige relbib (button sieht ander aus als die anderen):
![grafik](https://user-images.githubusercontent.com/26873381/67929868-bb862700-fbbe-11e9-9259-c0cde898d98a.png)

Das könnte jetzt allerdings auch mit VuFind6 zusammenhängen. Ich werde mir das noch im Detail anschauen.

**Comment by mtrojan-ub** [comment]
Die Probleme wurden behoben. Zusätzlich wurden folgende Änderungen durchgeführt:
- Ist eine Zeitschrift schon abonniert, wird ein anderes icon + anderer Text angezeigt
- Nach dem Abschicken des Formulars für subscribe / unsubscribe wird die Seite neu geladen, damit auch der neue Zustand richtig angezeigt wird.

Bitte nochmal testen.

**Comment by IxTheoKm** [comment]
Sieht jetzt gut aus, danke!
