### ISSUE TITLE
Ermöglichung einer Suche nach IxTheo-Klassen

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#909]
_Die Anregung zu diesem Issue kommt von einem Fachkollegen aus Wuppertal_

Bitte Suchaspekt "IxTheo-Klassifikation" einfügen in der
- einfachen Suche
![Bildschirmfoto 2019-10-10 um 15 25 30](https://user-images.githubusercontent.com/14169098/66573007-42248700-eb72-11e9-861a-9b5287064cd2.png)

- erweiterten Suche
![Bildschirmfoto 2019-10-10 um 15 27 16](https://user-images.githubusercontent.com/14169098/66573152-8152d800-eb72-11e9-9720-7609cc3684e7.png)

In beiden Fällen sollen Boolsche Operatoren angewendet werden können (das dürfte m.E automatisch der Fall sein, wenn der Suchaspekt eingerichtet ist).

Den Suchaspekt bitte vor dem Aspekt DDC-Klassifikation einordnen

**Comment by thefass** [comment]
Die Suche soll ermöglicht werden nach

- den Notationen der Klassen (z.B. NCE)
- exakt oder trunkiert ( z.B. KDA oder KD* oder K*)
- den Bezeichnungen der Klassen (z.B. "Angelologie; Heiliger Geist")
- auch nach den anderssprachigen Klassenbezeichnungen (z.B. "New Testament")

**Comment by IxTheoKm** [comment]
Betrifft nur die Begrifflichkeit und Darstellung:

![Notationen](https://user-images.githubusercontent.com/17004223/70811615-3d748d00-1dc6-11ea-9117-ff855760140e.png)

![Notationen2](https://user-images.githubusercontent.com/17004223/70811785-a0feba80-1dc6-11ea-9841-1bbd6056fc45.png)

In der Facette und in der erweiterten Suche wird "IxTheo-Klassifikation" verwendet.
Das sollte m.E. daran angeglichen werden:

![notation3](https://user-images.githubusercontent.com/17004223/70811690-67c64a80-1dc6-11ea-9e2e-895d4efe30f8.JPG)

**Comment by thefass** [comment]
Es funktioniert:

1. Suche nach einzelnen Notationen oder deren Benennung funktioniert.
z.B. 
AE > 3.395 Treffer
Religionspsychologie > 3.395 Treffer.

2. Boolsche Operatoren, wenn man sie mit Kapitälchen schreibt
z.B. HC AND NBF > 
https://ixtheo.de/Search/Results?lookfor=HC+AND+NBF&type=IxTheoNotations&limit=20&botprotect=
z.B. HC OR NBF >
https://ixtheo.de/Search/Results?lookfor=HC+OR+NBF&type=IxTheoNotations&limit=20&botprotect=
3. Kombinationen
(HC AND HB) AND NBF
(HC AND HB) OR NBF
(HC OR HB) AND NBF
4. Trunkierte Suche

**Comment by thefass** [comment]
Seltsame Ergebnisse:
1. Suche nach HA > Treffer 38.977
https://ixtheo.de/Search/Results?lookfor=HB&type=IxTheoNotations&limit=20&botprotect=
2. Suche nach der deutschen Bezeichnung "Altes Testament" > Treffer 84.132
https://ixtheo.de/Search/Results?lookfor=Altes+Testament&type=IxTheoNotations&limit=20&botprotect=
2. Suche nach der italienischen Bezeichnung "antico testamento" > Treffer 84,324
https://ixtheo.de/Search/Results?lookfor=antico+testamento&type=IxTheoNotations&limit=20&botprotect=
3. Suche nach der englischen Bezeichnung "Old Testament" >  83.978
https://ixtheo.de/Search/Results?lookfor=old+Testament&type=IxTheoNotations&limit=20&botprotect=

M.E. müßte das doch immer die gleiche Treffermenge sein, oder?

**Comment by ruschein** [comment]
@thefass 1) HA ist "Bibel" und nicht "Altes Testament".
2) Du solltest bei den Suchen 2. bis 4. mit Gänsefüßchen suchen und dann sind die Trefferzahlen auch alle identisch.

**Comment by ruschein** [comment]
Kann ab morgen auf Ptah getestet werden.

**Comment by ruschein** [comment]
Jetzt finde ich auf Path für "HA", "Bibel" und "Bible" die exakt gleichen Treffermengen.

**Comment by thefass** [comment]
Aber:
HB 85.230 Treffer
Altes Testament 85.385 Treffer
"Altes Testament" 85.230 Treffer
nur mit "" ist die Anzahl gleich

**Comment by ruschein** [comment]
D.h., dass "Altes Testament" oder "Altes" + "Testament" etc. als Substrings vorkommen und ist das normale Suchverhalten bei allen Standartsuchen.

**Comment by thefass** [comment]
ok
