### ISSUE TITLE
Sprache: Abweichungen in Ptah

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#91]
In der Facette "Sprache" gibt es zahlreiche Abweichungen in Ptah zu RelBib. Z. B.

1. Neugriechisch gibt es auf Ptah nicht. Die Trefferzahl von "Neugriechisch" in RelBib (=90) entspricht der Trefferzahl für "Griechisch" auf Ptah. "Griechisch" gibt es aber zusätzlich in RelBib mit 750 Treffern.
RelBib: 
![grafik](https://user-images.githubusercontent.com/25769591/33932031-2447dc7e-dff2-11e7-8393-f2485389f0ca.png)
![grafik](https://user-images.githubusercontent.com/25769591/33932097-518b05b2-dff2-11e7-814e-289d3e212fc4.png)
Ptah:
![grafik](https://user-images.githubusercontent.com/25769591/33932064-36ca161e-dff2-11e7-9b39-5e282843f703.png)

2. Einige Sprachen, wie z. B. Sranantongo oder Somali, scheinen auf Ptah zu fehlen. Andere wiederum sind auf Ptah vorhanden und fehlen in RelBib (z. B. Kroatisch). Soll eine Liste der Abweichungen zusammengestellt werden?

3. Ein Fehler, der vielleicht noch jetzt auf RelBib behoben werden sollte, wenn möglich: In RelBib gibt es derzeit keine Anzeige der Sprache "Spanisch". Auf Ptah wird Spanisch angezeigt. Die Trefferzahl entspricht hier genau jener von "Sardisch" auf RelBib (= 6737).
RelBib:
![grafik](https://user-images.githubusercontent.com/25769591/33932572-8d9592a6-dff3-11e7-945d-c8f84b52df77.png)
Ptah: 
![grafik](https://user-images.githubusercontent.com/25769591/33932593-9bf163de-dff3-11e7-832f-23910826894b.png)

4. Hier noch ein Tippfehler auf Ptah: Es muss richtig heißen "Tschagataisch" anstelle von "Tschgataisch".

5. Letzte Frage: Warum läuft die alphabetische Sortierung der Sprachen nicht durch? Es gibt zwei alphabetisch sortierte Blöcke, der zweite beginnt mit "Ägyptisch". Betrifft sowohl Ptah als auch RelBib...

![grafik](https://user-images.githubusercontent.com/25769591/33932522-6eac5cda-dff3-11e7-879a-d1122719cbd7.png)

Die Abweichungen in der Sprache-Facette betreffen vmtl. auch IxTheo.

**Comment by ruschein** [comment]
Die Übersetzung "Griechisch" ist korrekt.  Der englische Eintrag lautet nämlich "Greek".  "Neugriechisch" ist im Englischen "Modern Greek".  Das steht da aber nicht.   Also ist die Übersetzung auf Ptah korrekt und falsch auf IxTheo.de.  (Die Referenzsprache ist in VuFind immer Englisch.)

**Comment by relhei** [comment]
Und was ist dann mit den Einträgen unter "Griechisch" (750 Treffer) auf relbib.de? Wo werden die auf ptah eingeordnet?

**Comment by ruschein** [comment]
@relhei Es sieht so aus als ob die Übersetzung auf ReBib und Ptah falsch wären.  Wen man dort von Deutsch auf Englisach wechselt wird aus Griechisch "Ancient Greek".  Auf unseren Testsystemen wird aus Griechisch "Greek" und aus Altgriechisch "Ancient Greek".  Dann stimmen die Zahlen auch überein.

**Comment by ruschein** [comment]
Zusatz: Auf den Produktionssystemen sind die Zahlen bei der deutschen Anzeige also falsch wegen der falschen Übersetzung.  Z.B., die Zahl 752 für Griechisch auf RelBib kommt von "Ancient Greek".

**Comment by relhei** [comment]
Syriac und Old Syriac wurde beide Male auf ptah mit "Altsyrisch" übersetzt" - jetzt gibt es also zwei Einträge "Altsyrisch".

**Comment by relhei** [comment]
Ansonsten scheint die Übersetzung auf ptah korrekt zu sein. Manche Sprachen wurden mit Alternativbegriffen ins Deutsche übersetzt: z. B. Galla (dt.) - Oromo (engl.).

**Comment by ruschein** [comment]
@relhei Ich schlage vor, dass wir "Old Syriac" durch "Syriac" ersetzen.  Ich glaube kaum, dass wir ein Altaltsyrisch einführen wollen.  ;-)

**Comment by relhei** [comment]
Ich würde Syriac mit Syrisch oder Syriakisch übersetzen. Und Old syriac mit Altsyrisch beibehalten. Es gibt da schon einen Unterschied: s. https://de.wikipedia.org/wiki/Syrische_Sprache

**Comment by ruschein** [comment]
Wird gemacht.  Danke.

**Comment by relhei** [comment]
Das sieht jetzt gut aus. Vielen Dank!

Was ist mit den Punkten 2-5? Insbesondere Punkt 3 wäre wichtig, weil aufgrund der hohen Trefferzahl in der Facette für den RelBib-Nutzer sofort sichtbar.

**Comment by ruschein** [comment]
Zu 2.: eine Liste wäre hilfreich.

**Comment by relhei** [comment]
ad 2) Die meisten Unterschiede beruhen tatsächlich auf einer falschen Übersetzung vom Deutschen ins Englische auf relBib. Auf Ptah stimmt das meiste. Verbesserungsvorschläge hänge ich im Dokument an.
[Übersetzung der Sprachen auf Ptah.docx](https://github.com/ubtue/tuefind/files/1575296/Ubersetzung.der.Sprachen.auf.Ptah.docx)

**Comment by relhei** [comment]
Sieht gut aus. Vielen Dank!
