### ISSUE TITLE
Zählung der Häufigkeit im Browsing-Modus

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#910]
Die Angaben der Häufigkeit in der letzten Spalte stimmen nicht. Sie können rein logisch nicht größer sein als in der ersten Spalte. 
Wenn man sich die Datensätze anzeigen lässt, kommen die richtigen Zahlenergebnisse

Beispiel_1
https://www.ixtheo.de/Browse/IxTheo-Classification?findby=topic&category=&query=%22Bibel%22&query_field=topic_facet&facet_field=ixtheo_notation_facet
![Bildschirmfoto 2019-10-10 um 15 15 17](https://user-images.githubusercontent.com/14169098/66574565-c0822880-eb74-11e9-96e7-def250eb2a86.png)

Beispiel_2
URL:https://www.ixtheo.de/Browse/Dewey?findby=%22200+-+Religion%22&category=&query=%22290+-+Other+religions%22+AND+dewey-hundreds%3A%22200+-+Religion%22&query_field=dewey-tens&facet_field=dewey-ones
![Bildschirmfoto 2019-10-10 um 15 45 22](https://user-images.githubusercontent.com/14169098/66574761-0f2fc280-eb75-11e9-9957-25f8a753a011.png)

**Comment by jriedl** [comment]
Aut ptah behoben.

**Comment by thefass** [comment]
ok
