### ISSUE TITLE
Personenangaben Doppelungen in Nachlassdatensätzen

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#911]
bei dem Datensatz:
https://ptah.ub.uni-tuebingen.de/Record/LR041688#details
![Bildschirmfoto 2019-10-14 um 00 08 41](https://user-images.githubusercontent.com/14169098/66723234-ff370d80-ee16-11e9-8844-a679c62f0060.png)

gibt es Doppelungen, die entfernt werden müssen

Das Problem taucht in weiteren Datensätzen auf, z.B.:
https://ptah.ub.uni-tuebingen.de/Record/LR041658
https://ptah.ub.uni-tuebingen.de/Record/LR041651
https://ptah.ub.uni-tuebingen.de/Record/LR041652

**Comment by ruschein** [comment]
Auf Ptah.

**Comment by IxTheoKm** [comment]
Doppelungen sind jetzt weg.
Siehe aber #1029
