### ISSUE TITLE
Anzeige von "basic_search_keep_filters" bei aktiver Facette

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#918]
... nach Upgrade auf VuFind 6.0.1 (siehe label)

![grafik](https://user-images.githubusercontent.com/26873381/66908270-150d2400-f00b-11e9-8220-e60868b09f90.png)

**Comment by relhei** [comment]
Was mir noch aufgefallen ist: In VuFind 6 scheint der Kasten "Suchfilter entfernen" mit den darin aufgelisteten ausgewählten Suchfiltern entfallen zu sein. Hier der Ist-Zustand in RelBib:
![grafik](https://user-images.githubusercontent.com/25769591/67391775-a21e2300-f59f-11e9-9b33-1f83c8cfa3f2.png)
Und hier auf ptah:
![grafik](https://user-images.githubusercontent.com/25769591/67391740-916dad00-f59f-11e9-9d12-5d57ecc72941.png)

**Comment by mtrojan-ub** [comment]
Stimmt, dieser Kasten wurde in 6 abgeschafft und unter die Suchbox verschoben. Da wir aber in den neuen Layouts den Platz unter der Suchbox schon mit anderen Dingen benutzen, muss das alte Feature wohl aus VuFind5 in TueFind6 portiert werden, damit es dort wieder angezeigt wird.

**Comment by mtrojan-ub** [comment]
... ist jetzt auf den Testservern geändert und kann getestet werden

**Comment by relhei** [comment]
Passt. Vielen Dank!
