### ISSUE TITLE
Vufind6 - Aufruf von Zs über ppn fehlerhaft

### ISSUE THREAD

**Issue by Gazeller** [ubtue/tuefind#928]
Bei Aufruf von ppn 490718434 (Material religion) gibt es auf relbib-ptah keinen Treffer, wohl aber auf relbib.de

Ähnlich aber umgekehrt:
Bei Aufruf von ppn 834395193 (Revue des sciences religieuses) gibt es Treffer auf ptah und auf relbib.de - Aber: bei ptah werden unter Bände/Aufsätze diese angezeigt, bei relbib.de gibt es Fehlermeldung

**Comment by Gazeller** [comment]
Der Aufruf eines Aufsatzes unter seinem Titel klappt auf beiden Systemen!

**Comment by ruschein** [comment]
Die beiden Probleme haben beide nichts mit dem VuFind-Upgrade zu tun.  Das erste ist gar kein Problem da der Datensatz mit einem anderen gemergt wurde.  Kann man mit der Suche "ids:490718434" finden.  Das zweite Problem sollte auch behoben sein aber das kann man erst testen wenn der neue Code auf den Produktivsystemen landet.  Also nachem wir das Update für VuFind 6 eingespielt haben.
