### ISSUE TITLE
Abweichende Trefferzahl je Autor bei leerer Suche

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#93]
Bei einer leeren Suche in RelBib und auf Ptah werden bei den gleichen Verfassern unterschiedliche Trefferzahlen angezeigt. Dies betrifft auch IxTheo.

RelBib: 
![grafik](https://user-images.githubusercontent.com/25769591/33935088-05ccec36-dffb-11e7-81f0-926563931c07.png)

Ptah:
![grafik](https://user-images.githubusercontent.com/25769591/33935106-1632bf38-dffb-11e7-9e8d-220e0d0d7e6a.png)

**Comment by mtrojan-ub** [comment]
ist aktuell nicht mehr reproduzierbar - falls noch relevant, bitte nochmal aktuelle Screenshots posten
