### ISSUE TITLE
Auswirkungen von Nachlässen (LR) auf "Neuzugänge" + Sortierung "neueste zuerst"

### ISSUE THREAD

**Issue by AleAprile** [ubtue/tuefind#935]
Eine allgemeine Suche nach neuen Zugängen (egal in welchem Zeitraum) auf ptah liefert immer eine größere Treffermenge als eine ähnliche Suche im Produktivsystem.

Beispiele.
Ptah: https://ptah.ub.uni-tuebingen.de/Search/NewItem?range=7&submit=Suchen&botprotect= 
Produktivsystem: https://www.ixtheo.de/Search/NewItem?range=7&submit=Suchen&botprotect=

Sollte die Treffermenge perfekt identisch sein?

**Comment by mtrojan-ub** [comment]
Ich nehme an, dass dieser Issue ausschließlich etwas mit Neuzugängen im Kontext Nachlässe zu tun hat. Das ist kein VuFind-Upgrade-spezifisches Problem, aber hängt wohl trotzdem mit einer Änderung zusammen die vor Kurzem gemacht wurde.

Meines Wissens nach werden Datensätze mit ID "LR"... von uns künstlich erzeugt und mit aktuellem Datum versehen.

@ruschein und @jriedl, könnt Ihr das bestätigen?
(siehe create_literary_remains_records.cc)

**Comment by ruschein** [comment]
Kann die Aussage von Mario bestätigen, die Datensätze, deren Control Number mit LR anfangen sind Nachlassdatensätze, die von uns erzeugt werden.  LR steht für "literary remains:.

**Comment by AleAprile** [comment]
Offensichtlich hab' den Issue zu schnell geschlossen, sorry!

Deinen Vorschlag finde ich sehr gut. Als Nutzer würde ich mir auch wünschen, dass unter "Neuen Zugängen" zunächst nur echte bibliographische Einträge zu finden sind. Zudem habe ich von anderen Fachreferenten für Theologie in anderen Bibliotheken mitbekommen, dass sie die Funktion nutzen, um zu erfahren, was neu in der Theologie erschienen ist. 

Hoffentlich lassen sich die Nachlässen bei dieser Funktion ausklammern.

**Comment by mtrojan-ub** [comment]
Das ging schneller als gedacht, wenn auch auf andere Weise. Ist also umgesetzt, bitte nochmal testen.

**Comment by AleAprile** [comment]
Es funktioniert sehr gut. 
Als Ergebnisse bekommt man nun nur echte "Neuzugänge"
