### ISSUE TITLE
OA-Facette auf Ptah

### ISSUE THREAD

**Issue by AleAprile** [ubtue/tuefind#936]
Wenn eine Suche mit der Facette "Open Access" eingeschränkt wird, werden in der Trefferliste teilweise auch lizenzpflichtige oder nur in der Druckausgabe erscheinende Zeitschriften angezeigt.

Siehe die ersten zwei Treffer: https://ptah.ub.uni-tuebingen.de/Search/NewItem?filter%5B%5D=is_open_access%3A%22open-access%22&hiddenFilters%5B%5D=first_indexed%3A%22%5BNOW-7DAY+TO+NOW%5D%22&range=7&department=

Vielleicht hat das wenig mit Ptah zu tun und ist ein generelles Problem, welches vielmehr auf die Kennzeichnung vom OA-Angebot zurückzuführen ist.

**Comment by relhei** [comment]
Das ist in der Tat merkwürdig. Hier habe ich mal ins Internformat geschaut: "Open Access" wird als weiteres Schlagwort in Feld 655 angezeigt.
![grafik](https://user-images.githubusercontent.com/25769591/67389870-c841c400-f59b-11e9-905c-a117936f7337.png)
In der WinIBW hingegen ist bei Umschalten auf Marc-Format kein Feld 655 zu entdecken und auch das Schlagwort "Open Access" taucht nicht auf.
![grafik](https://user-images.githubusercontent.com/25769591/67389813-ad6f4f80-f59b-11e9-976c-072a1dbd3f8b.png)

**Comment by AleAprile** [comment]
Das ist auch ein anderer wichtiger Punkt, der mir auch aufgefallen ist. 
Im Vufind gibt es mehrere "OA-Einträge", welche mit dem "Open Access" im Feld "weitere Schlawörter" versehen ist. Nirgendswo ist aber das Schlagwort "Open Access" im K10plus-Datensatz zu sehen.

**Comment by AleAprile** [comment]
Wenn ich richtig sehe, korreliert das in diesem Issues geschilderte Problem **teilweise** mit #809. Und da gib es bereits ganz konkrete Lösungen. Insofern ist das auch nicht VuFind 6 spezifisch.
Nichtsdestotrotzt finde ich auf ptah nicht immer nachvollziehbar, wie unter die sehr wichtige Facette "Open Access" die Einträge gelangen.

**Comment by mtrojan-ub** [comment]
Als "open access" wird gekennzeichnet, was OASa = 1 gesetzt hat. Das wiederum wird von uns intern gesetzt, wenn mindestens eine der folgenden Bedingungen zutrifft:
- 024$2 == "doi" und die DOI ist in einer unserer maps für "unpaywall"
- 655a == "open access"
- 856z == "LF"
- 856z beginnt mit "kostenfrei" und Unterfeld 3 == "volltext"
- 856x == "unpaywall"

Außerdem: Ist z.B. eine Zeitschrift als Open Access markiert, werden auch die enthaltenen Aufsätze als Open Access markiert (über 655a). Im obigen Falle:
- Aufsatz: https://134.2.67.9/Record/1535185988
- Zeitschrift: https://134.2.67.9/Record/719752078
... wird also wohl beim Aufsatz 655a von uns im Aufsatz eingefügt, da es sich um eine Open Access Zeitschrift handelt. Vielleicht wäre es besser, statt 655a hier OASa = 1 zu setzen, damit klar ist dass diese Information von uns stammt.

@ruschein und @jriedl, siehe: 
https://github.com/ubtue/ub_tools/blob/1d7af018e577fd88406f0534e88d6eef7350d7be/cpp/pipelines/add_isbns_or_issns_to_articles.cc#L130

**Comment by mtrojan-ub** [comment]
Statt 655a setzen wir jetzt OASa = 1. Beispiel:
https://134.2.67.9/Record/1535185988#details

![grafik](https://user-images.githubusercontent.com/26873381/70306539-5d74e100-1807-11ea-9bc4-ea542b719806.png)

Gibt es aktuell noch Datensätze bei denen das Verhalten unklar ist, oder kann der Issue jetzt geschlossen werden?

**Comment by ruschein** [comment]
@AleAprile Kann dieses Issue jetzt geschlossen werden?
