### ISSUE TITLE
 Suche nach Personenname 

### ISSUE THREAD

**Issue by AleAprile** [ubtue/tuefind#937]
Tippe ich zum Test verschiedene Personennamen (Vor-und Nachname, oder umgehkert) ein, bekomme ich gar keine Ergebnisse. Hinzu sehe ich den Hinweis, dass ich mich vielleicht vertippt habe. Klicke ich auf die von System vorsgeschlagene Schreibweise, dann bekomme ebenfalls keine Ergebnisse zu sehen.

Gestern habe ich auch dieses Problem festgestellt, dann ging es wieder. Heute ist so eine Recherche erneut nicht möglich

**Comment by AleAprile** [comment]
Ich stelle soeben noch zwei Sachen fest.
1. keine Ergebnisse werden geliefert, wenn man
* Themen oder Titel von Artikel oder Werken in den Suchschlitz eintippt
* Vorschläge aus der Top-down-Liste auswählt, nachdem ein Name, Titel, oder Thema eingegeben wird 

2. Wenn ich den Button "Volltexte" aktiviere und meine Suchabfragen wiederhole, liefert das System Ergebnisse. Wähle ich den Button "IxTheo" über dem Suchschlitz zurück und tippe erneut die Namen oder Themen ein, für die vorhin es angeblich keine Ergebnisse gab, werden die passenden Treffer angezeigt.

**Comment by mtrojan-ub** [comment]
Der Tab "Volltexte" ist ja noch in Arbeit und sollte fürs Testing der 6.0 nicht berücksichtigt werden.
Das genannte Problem kann ich so nicht nachvollziehen, bitte um konkrete Beispiele.

Folgendes Beispiel funktioniert (gibt > 2000 Treffer):
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=Hans+K%C3%BCng&type=AllFields&limit=20&botprotect=

![grafik](https://user-images.githubusercontent.com/26873381/67479833-3602f400-f65f-11e9-818d-04e471b3d01b.png)

**Comment by AleAprile** [comment]
Es ist mir nun nicht möglich, konkrete Beispiele zu nennen, weil die Suche jetzt ganz normal funktioniert (umso besser!)
In den vergangenen Tagen ist mir mehrmals passiert, dass eine normale Suche nach Themen oder Autoren schlicht und ergreifend nicht funktioniert hat. Es kam nur der Hinweis "keine Ergebnisse!"
Wenn es so ist und bleibt, kann man dann diese Issues schließen!
