### ISSUE TITLE
RSS-Feed abonnieren

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#939]
Dies betrifft nicht das Update auf VuFind 6, weil in beiden Systemen vorhanden: Bei Klick auf "RSS-Feed abonnieren" unterhalb der Trefferliste erscheint eine XML-Datei. Wie kann man das Abonnement dann einrichten? Die Darstellung war mal anders. Auch ausprobiert mit anderem Browser (MS Edge).
https://www.relbib.de/Search/Results?filter%5B%5D=%7Emediatype%3A%22Non-Electronic%22&filter%5B%5D=%7Eformat%3A%22Article%22&filter%5B%5D=%7Elanguage%3A%22English%22&filter%5B%5D=%7Erelbib_notation_facet%3A%22BH%22&filter%5B%5D=topic_facet%3A%22Rabbinismus%22&filter%5B%5D=%7Eauthor_facet%3A%22Neusner%2C+Jacob+1932-2016%22&type=AllFields&view=rss

**Comment by mtrojan-ub** [comment]
Es handelt sich hierbei um eine Standardfunktion von VuFind, die einen RSS-Feed ausgibt, was nichts anderes als eine spezielle Art von XML-Datei ist.

Wenn sich etwas ändert liegt es daran, dass viele Browser derzeit allgemein viele Browser etwas an ihrer RSS-Funktionalität ändern. Manche unterstützen ja auch in der Zwischenzeit kein RSS mehr, z.B. Firefox.

Einen RSS Feed direkt per Klick auf den Button zu abonnieren klappt nur dann, wenn
a) Der Browser RSS-Feeds unterstützt, oder
b) Auf dem Rechner ein RSS-Reader installiert ist, der so eingerichtet ist dass beim Klick auf den RSS-Feed im Browser der RSS-Reader verwendet wird (das wird nicht bei allen RSS Readern bei der Installation so eingerichtet).

**Comment by ruschein** [comment]
https://addons.mozilla.org/en-US/firefox/search/?platform=linux&q=rss%20reader
