### ISSUE TITLE
Verlag: LIT wird zu Literatur

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#94]
In der Verlag-Facette wird "Literatur" als Verlag aufgeführt. 
![grafik](https://user-images.githubusercontent.com/25769591/33937061-36769c90-e002-11e7-92c5-cff6a51370ba.png)

Der Verlag heißt richtig "LIT" und wird als solcher auch in den Interndaten angegeben ("Lit" in Feld 260). 

![grafik](https://user-images.githubusercontent.com/25769591/33936953-bab55dbc-e001-11e7-8a26-d1e4482bcbf8.png)

Das Problem betrifft sowohl Ptah als auch RelBib / IxTheo.

**Comment by ruschein** [comment]
Die Daten sind falsch.  Wenn der Datensatz "LIT" anstatt "Lit" enthält, lässt sich das Problem nicht reproduzieren.  Bitte die Daten korrigieren.

**Comment by relhei** [comment]
Wir können die Daten nicht ohne Weiteres korrigieren, da sie aus verschiedenen Quellen kommen. Gibt es eine andere Möglichkeit, z. B. mit Unterdrückung der automatischen Ergänzung von Lit / Lit. o. ä. in Feld 260 |b?

**Comment by jriedl** [comment]
Das Umschreiben für den Lit-Verlag wird jetzt auf ptah für die Beispiel-PPN unterdrückt, für alle weiteren nach dem nächsten Import

**Comment by relhei** [comment]
Das passt. Danke!
Allerdings ist mir aufgefallen, dass gerade bei den Verlagen die Liste unglaublich aufgebläht wird durch nur geringfügig abweichende Schreibungen ein- und desselben Verlages. Lässt sich da auch noch was unterdrücken? Z. B. Groß- und Kleinschreibung, Apostrophe, Anführungszeichen etc. Oder über Ähnlichkeiten zusammenführen?

Bsp.: 

1. Oxford University Press vs. Oxford Univ. Press
2. de Gruyter vs. De Gruyter
3. Lit vs. LIT
...
Und hier mein Lieblingsbeispiel:
![grafik](https://user-images.githubusercontent.com/25769591/41710490-0c4850f6-7546-11e8-9f4a-5784bf77d627.png)

**Comment by thefass** [comment]
Das problem ist die fehlende Normalisierung bei Verlagen. Das wird es auch auf absehbare Zeit nicht geben. Ebensowenig können wir die Datensätze korrigieren.

Was wir machen könnten, wäre eine Konkordanz in der MarcPipeline dazwischen zu schalten, auf der wir die unterschiedlichsten Schreibweisen auf eine mappen. 
Wir sollten aber nicht versuchen, das systematisch zu machen, sondern nur, wenn uns das auffällt, sonst wird das ein zu großes Projekt.

**Comment by obrandt** [comment]
Hallo,

da gibt es eine sehr einfache Lösung: die Daten vereinheitlichen. :-)

Viele Grüße

Olaf

Von: relhei [mailto:notifications@github.com]
Gesendet: Donnerstag, 21. Juni 2018 11:29
An: ubtue/tuefind <tuefind@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [ubtue/tuefind] Verlag: LIT wird zu Literatur (#94)


Das passt. Danke!
Allerdings ist mir aufgefallen, dass gerade bei den Verlagen die Liste unglaublich aufgebläht wird durch nur geringfügig abweichende Schreibungen ein- und desselben Verlages. Lässt sich da auch noch was unterdrücken? Z. B. Groß- und Kleinschreibung, Apostrophe, Anführungszeichen etc. Oder über Ähnlichkeiten zusammenführen?

Bsp.:

  1.  Oxford University Press vs. Oxford Univ. Press
  2.  de Gruyter vs. De Gruyter
  3.  Lit vs. LIT
...
Und hier mein Lieblingsbeispiel:
[grafik]<https://user-images.githubusercontent.com/25769591/41710490-0c4850f6-7546-11e8-9f4a-5784bf77d627.png>

**Comment by jriedl** [comment]
Wie bereits für die Schlagwörter (https://github.com/ubtue/ub_tools/blob/master/cpp/data/keyword_normalistion.map) existieren mit https://github.com/ubtue/ub_tools/blob/master/cpp/data/publisher_normalistion.map und https://github.com/ubtue/ub_tools/blob/master/cpp/data/author_normalistion.map jetzt Mapping-Dateien, die für die Felder 100$a und 700$a (Autoren) und 260$b und 264$b) (Publisher) ein Umschreiben auf eine normalisierte Form vornehmen können.

**Comment by jriedl** [comment]
Am einfachsten ist wahrscheinlich, die Datei wird jeweils von Github heruntergeladen, editiert und uns per Mail zugeschickt - wir checken Sie dann wieder ein. Zu beachten ist eigentlich nur, dass die linke Seite neben dem "->" ein regulärer Ausdruck ist, d.h. die im Kopf der Dateien angegebenen Zeichen mit spezieller Bedeutung müssen escaped werden.

**Comment by relhei** [comment]
Gibt es die Mapping-Dateien noch? Die Links führen ins Leere...

**Comment by jriedl** [comment]
Die existieren noch, allerdings haben sich die Dateinamen geändert, da in den ursprünglichen Namen ein "a" gefehlt hat:
https://github.com/ubtue/ub_tools/blob/master/cpp/data/keyword_normalisation.map
https://github.com/ubtue/ub_tools/blob/master/cpp/data/author_normalisation.map
https://github.com/ubtue/ub_tools/blob/master/cpp/data/publisher_normalisation.map

**Comment by relhei** [comment]
Prozedere ist klar, Links bekannt. Daher kann issue geschlossen werden.
