### ISSUE TITLE
Ähnliche Einträge

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#940]
Es gibt jetzt in der Volltitelanzeige unterhalb der bibliographischen Kerndaten 4 Reiter, darunter "Ähnliche Einträge". Wenn kein Buchcover vorhanden ist, wird hier erst einmal nichts angezeigt: Man muss mit der Maus drüberfahren, um die Titelvorschläge zu sehen. Außerdem dupliziert dieser Reiter die "More like this"-Funktion rechts neben der Volltitelanzeige. 
![grafik](https://user-images.githubusercontent.com/25769591/67393018-dbf02900-f5a1-11e9-9f7c-b7e5f12e0d3d.png)
Sollte noch mal überdacht werden, ob das so übernommen wird. Evt. könnten Titelanfänge in den Containerfeldern angezeigt werden? Eine doppelte Anzeige fänd ich in jedem Fall nicht sinnvoll.

**Comment by jriedl** [comment]
Auf ptah jetzt bisheriges Anzeigeverhalten.

**Comment by relhei** [comment]
Das passt so. Vielen Dank. Sollte trotzdem noch einmal im Meeting besprochen werden.

**Comment by relhei** [comment]
Im Meeting letzte Woche besprochen: Könnte die rechte Spalte "More like this" (Ähnliche Einträge) durch einen "Mehr"- oder "Weitere"-Button ergänzt werden, wo dann die weiteren Ergebnisse angezeigt werden, die in der neuen (jetzt wieder entfernten) Anzeige enthalten waren?

**Comment by jriedl** [comment]
Auf ptah existiert jetzt ein "mehr"-Knopf für weitere Ergebnisse

**Comment by relhei** [comment]
Sieht gut aus! Vielen Dank.
