### ISSUE TITLE
Falsche Werte in der Zeit (Schlagwort)-Facette

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#941]
Das Poblem wird sichtbar nach einer Bibelstellensuche Mk 5,1-20
Sowohl auf Ptah als auch auf IxTheo
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=Mk+5%2C1-20&type=BibleRangeSearch
https://www.ixtheo.de/Search/Results?lookfor=Mk+5%2C1-20&type=BibleRangeSearch&botprotect=
![Bildschirmfoto 2019-10-23 um 15 49 32](https://user-images.githubusercontent.com/14169098/67399854-21662380-f5ad-11e9-8e28-e126269db9d1.png)

Die Buchstaben u s p g b sind vermutlich aus den 689 $d Feldern.

Beispiel: https://ptah.ub.uni-tuebingen.de/Record/1582018030#details
PPN 1582018030
![Bildschirmfoto 2019-10-23 um 16 23 28](https://user-images.githubusercontent.com/14169098/67402890-815ec900-f5b1-11e9-91a1-e16913d392e9.png)
Hier in $D die Buchstaben
Wieso die Schlagwortindikatoren allerdings in der Zeitfacette ausgelesen werden ist mir unklar.

**Comment by jriedl** [comment]
Im Kontext der Bibelstellensuche wurden hier innerhalb der Facettierung nicht die korrekten, sprachabhängigen Felder verwendet. Ist auf ptah behoben

**Comment by thefass** [comment]
ok
