### ISSUE TITLE
Problem beim Umschalten von Bibelstellensuche nach Allgemeiner Suche

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#942]
Nach einer Bibelstelle sollte wieder eine allgemeine Suche nach einem Titel gemacht werden.
Obwohl der Suchaspekt Alle Felder ausgewählt wurde, wurde der Titel nicht gefunden.
Siehe Screenshot.
![Bildschirmfoto 2019-10-23 um 16 27 18](https://user-images.githubusercontent.com/14169098/67403748-aef84200-f5b2-11e9-9320-970e84e45c27.png)

Auf IxTheo funktioniert das

![Bildschirmfoto 2019-10-23 um 16 32 25](https://user-images.githubusercontent.com/14169098/67403826-c6cfc600-f5b2-11e9-8b17-e7dc42ddfa8d.png)

**Comment by mtrojan-ub** [comment]
Das Problem kann ich leider nicht reproduzieren. Auf Deinen Screenshots fällt auf, dass im oberen Screenshot ein Sonderzeichen am Ende mit eingegeben wurde. Hängt es evtl damit zusammen? (ein * oder ", auf dem Screenshot nicht genau erkennbar)

**Comment by thefass** [comment]
Am Sonderzeichen lag es nicht, das ist in * und wird angefügt, wenn man das auto-suggest in die Suchzeile durch Klick übernimmt. Siehe Screenhot
![Bildschirmfoto 2020-09-09 um 11 53 27](https://user-images.githubusercontent.com/14169098/92583933-534eaa00-f293-11ea-8815-827f67dfcf6b.png)

Das Suchverhalten ist allerdings jetzt wie gewünscht und damit besteht das oben beschriebene Problem nicht mehr. Manches ist halt auch in unserer Zeit mysteriös!
