### ISSUE TITLE
Nutzung von "Mein Konto" nicht möglich

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#945]
Login ist noch möglich, bei Klick auf "Mein Konto" erfolgt aber eine Fehlermeldung. Ebenso ist das Hinzufügen eines Titels zur Favoritenliste im Konto möglich, bei gewünschter Einsicht der Liste erfolgt wieder eine Fehlermeldung.
Hier eins Beispiel:
https://134.2.67.9/MyResearch/Home?redirect=0

**Comment by mtrojan-ub** [comment]
ist reproduzierbar, hängt wohl mit einem Fehler in einem der templates zusammen (list-entry.phtml)

2019-10-24T13:47:25+02:00 CRIT (2): Error : Call to undefined method VuFind\RecordDriver\Missing::getResourceSource()

ich kümmere mich heute Nachmittag drum

**Comment by mtrojan-ub** [comment]
ist behoben, bitte nochmal testen

**Comment by relhei** [comment]
Funktioniert gut. Danke!
