### ISSUE TITLE
Titel vorschlagen - Rückmeldung an NutzerInnen

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#946]
Das ist kein Problem mit dem VuFind Upgrade.
Nutzer*innen sollten nach dem Abschicken eines Titelvorschlags evt. eine andere Rückmeldung erhalten als "Besten dank für Ihr Feedback."
![grafik](https://user-images.githubusercontent.com/25769591/67481375-305add80-f662-11e9-9b74-e75e0e1ba1eb.png)

Vorschlag:
" Vielen / Besten Dank für Ihren Titelvorschlag."

**Comment by mtrojan-ub** [comment]
Das ist eine VuFind-Standardfunktion. Die angezeigte Meldung lässt sich recht einfach durch Konfiguration verändern (FeedbackForms.yaml->forms->AcquisitionRequest->response).

Soll es nur für Relbib oder auch für IxTheo/KrimDok angepasst werden? Und was soll in den anderen  Sprachen angezeigt werden?

**Comment by relhei** [comment]
Bitte auch in den anderen Systemen anpassen. 
Englisch: "Thank you for suggesting a title." 
Französisch und andere Sprachen: DeepL fragen? Da benötigen wir Unterstützung... Ansonsten erst einmal Englisch als default.

**Comment by relhei** [comment]
Bitte noch Texte auf Deutsch und Englisch anpassen. Es steht immer noch "Besten Dank für Ihr Feedback."

Bitte neu:
"Vielen Dank für Ihren Titelvorschlag."
"Thank you for suggesting a title."

**Comment by mtrojan-ub** [comment]
Kann auf sobek+ptah getestet werden

**Comment by relhei** [comment]
Passt auf RelBib - danke!

**Comment by relhei** [comment]
Kann ich schließen oder sollen die Kolleg*innen von IxTheo / KrimDok noch testen?

**Comment by relhei** [comment]
@thefass @KStelzel 
Bitte testen.

**Comment by KStelzel** [comment]
Auf KrimDok klappt das gut. Viel besser so. Vielen Dank an Mareike und Mario!

**Comment by thefass** [comment]
ich bin nicht sicher, aber ich glaube, wir haben das im IxTheo noch gar nicht verlinkt.

**Comment by relhei** [comment]
Stimmt! @thefass: Könnt ihr das evt. schon auf dem Testsystem fürs neue Theme sehen / testen?

**Comment by thefass** [comment]
Vermutlich nicht, Aber wenn es ansonsten passt, kann das Issue trotzdem geschlossen werden

**Comment by relhei** [comment]
Ok, ich schließe. Danke!
