### ISSUE TITLE
alte Suchanfrage in Suchhistorie

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#947]
Wie kann es sein, dass eine Suchanfrage von 2017, die nicht gespeichert wurde, in der Suchhistorie auftaucht? Cache wurde erst wenige Minuten davor geleert...
![grafik](https://user-images.githubusercontent.com/25769591/67481763-cd1d7b00-f662-11e9-90a5-2f24814f0ce6.png)
Nicht ganz klar, ob mit VuFind Upgrade zusammenhängend. Aber auf RelBib gab es nicht dieses "Problem".

**Comment by mtrojan-ub** [comment]
Sieht so aus als ob ein cronjob nicht eingerichtet wurde der alte nicht-gespeicherte Suchen löschen soll. Auf ub16 haben wir ca. 30 Mio davon in der DB die gelöscht werden könnten, wobei nur ca 300 tatsächlich durch Benutzer gespeicherte Anfragen drin sind die erhalten bleiben sollen :speak_no_evil: :see_no_evil: :hankey:

Ich kümmer mich drum

**Comment by mtrojan-ub** [comment]
Der cronjob ist jetzt auf den Servern eingerichtet, d.h. es werden jetzt jede Nacht alle Suchen gelöscht die älter als 90 Tage sind und nicht explizit von einem Benutzer gespeichert wurden.

Offen bleibt noch zu klären:
1) Ob der Zeitraum von 90 Tagen so passt bzw. verändert werden muss
2) Ob in der Datenschutzerklärung explizit darauf hingewiesen werden muss:
https://ixtheo.de/Content/privacy
Aktuell wird unter "Verbesserung unseres Onlineauftritts" darauf hingewiesen, dass gewisse Daten (Server-Logfiles) 3 Monate gespeichert bleiben. Allerdings wird im Abschnitt "Gespeicherte Suchen" nicht explizit darauf hingewiesen, dass auch nicht-gespeicherte Suchen eine Zeit lang in der Datenbank gespeichert bleiben.

**Comment by mtrojan-ub** [comment]
Es handelt sich ja teilweise um personenbezogene Daten die wir in diesem Umfang gar nicht haben dürften. Daher halten wir eine statistische Auswertung rechtlich gesehen für potenziell problematisch. Die Daten werden nach der Löschung aus der Datenbank noch wenige Tage im Backup verfügbar sein.

Unabhängig davon sind immer noch die Fragen 1) und 2) offen.

**Comment by mtrojan-ub** [comment]
@relhei : Existiert das Problem noch? Laut Datenbank hast Du auf ub16 3 Benutzerkonten (akimh01, mareikeh und relhei). In 2 davon gibt es noch Suchen von 2017. Diese stehen aber laut der Datenbank auf "gespeichert" und werden deshalb nicht gelöscht. Falls noch etwas gelöscht werden soll, bitte genaues Benutzerkonto und Datum / Uhrzeit des Suchergebnisses angeben.

**Comment by relhei** [comment]
Hab alle Suchanfragen selbst gelöscht und musste dann noch einmal "Entferne alle Suchanfragen, die nicht gespeichert sind." klicken, damit sie aus dem Konto "Gespeicherte Suche" tatsächlich verschwinden. Jetzt ist alles ok.

**Comment by relhei** [comment]
Passt. Vielen Dank!

**Comment by mtrojan-ub** [comment]
Soll der Zeitraum mit 90 Tagen noch weiter verringert werden?

**Comment by thefass** [comment]
Nein

**Comment by mtrojan-ub** [comment]
OK dann schließe ich den issue
