### ISSUE TITLE
Abweichende Titelsortierung nach Thema Browsen

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#948]
Nach Eingabe von "China Buddhismus" in Thema browsen erhält man in beiden Systemen 18 Treffer zu dieser Keywordchain. Bei Klick auf die Trefferliste und Einstellung der Sortierung nach Relevanz werden die Titel nicht gleich sortiert aufgelistet.
RelBib:
https://www.relbib.de/Search/Results?lookfor=%22Buddhismus%2FChina%22&type=Keywordchains&sort=relevance&botprotect=
Ptah:
https://134.2.67.9/Search/Results?lookfor=%22Buddhismus%2FChina%22&type=Keywordchains

**Comment by mtrojan-ub** [comment]
@jriedl: Kannst Du Dir das bitte anschauen?

In der VuFind changelog für die 6.0 habe ich nichts gefunden was unmittelbar darauf hinweist, aber es gab ja auch kleinere Änderungen in z.B. der searchspecs.yaml. Ich bin aber nicht sicher ob die etwas damit zu tun haben können.

**Comment by jriedl** [comment]
Unabhängig vom searchspecs.yaml. Bei dieser Art von Suche erzielen alle Treffer im Bezug auf die Relevanz das gleiche Scoring, da die zugehörige Schlagwortfolge identisch ist. Auf ptah ist für die Sortierung dann noch ein Sekundärkriterium aktiv (Jahr absteigend), das dann hier greift, auf Relbib aber noch nicht existiert.

**Comment by relhei** [comment]
Der eingangs benannte Unterschied besteht nach wie vor. Was auffällt: Bei der Suche auf RelBib werden als erstes relativ alte Titel aufgelistet. Wünschenswert wäre hier eine Sortierung (nach Greifen des Sortierkriteriums Relevanz) nach "neuesten Titeln zuerst". Bitte nach Möglichkeit anpassen.

**Comment by relhei** [comment]
Auf ptah passt die Sortierung.
Auf RelBib kommt bei Klick auf den o.g. Link jetzt eine Fehlermeldung. Was stimmt da nicht?

**Comment by mtrojan-ub** [comment]
Die Fehlermeldung kann ich nicht reproduzieren bzw. der o.g. Link lässt sich bei mir problemlos öffnen

**Comment by relhei** [comment]
Ok, ist wieder i. O. Danke!
