### ISSUE TITLE
Weiterleitungsseite auch für Suche nach superior_ppn

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#950]
Beim direkten Aufruf kommt eine Weiterleitungsseite:
https://134.2.67.9/Record/12988328X

Bei Suche nach Artikeln für die superior_ppn wird dies noch nicht berücksichtigt:
https://134.2.67.9/Search/Results?lookfor=superior_ppn%3A12988328X&type=AllFields&botprotect=

Potenziell problematisch (insbesondere fürs Merging). Es wurden teilweise URLs nach außen kommuniziert, die über Suche nach superior_ppn direkt alle Artikel einer Zeitschrift anzeigen.

**Comment by mtrojan-ub** [comment]
Falls direkt nach "id:" oder "superior_ppn:" gesucht wird und es keine Treffer gibt, wird nun eine Box mit einem Link zur "ids:" Suche angezeigt:

![grafik](https://user-images.githubusercontent.com/26873381/71666559-a9ad3580-2d61-11ea-9c5d-ebdf12ce2c20.png)

**Comment by relhei** [comment]
Die Anzeige und Weiterleitung funktioniert in den getesteten Fällen. Nutzer gelangen nun zur Anzeige der Aufsätze einer Zeitschrift erst nach drei weiteren Klicks. Ist etwas umständlich, aber vermutlich lässt sich das nicht anders einrichten?
https://134.2.67.9/Search/Results?lookfor=superior_ppn%3A35716749X&type=AllFields&sort=year+asc%2C+volume_sort+asc%2C+issue_sort+asc%2C+start_page+asc&botprotect=

**Comment by IxTheoKm** [comment]
@relhei der letzte Kommentar meint, dass noch etwas versucht werden soll?
@mtrojan-ub ich habe daher das Label neu gesetzt

**Comment by relhei** [comment]
@IxTheoKm Ja, genau - das ist eine Bitte um Optimierung, wenn möglich. Vielen Dank fürs Labeländern und Präzisieren!

**Comment by mtrojan-ub** [comment]
Die Weiterleitungen waren nur eine temporäre Lösung die mit einem der letzten VuFind Upgrades abgeschafft wurde, daher schließe ich den Issue.
