### ISSUE TITLE
Login nich möglich

### ISSUE THREAD

**Issue by AleAprile** [ubtue/tuefind#952]
![Screenshot_2019-10-25Login](https://user-images.githubusercontent.com/41292389/67554281-5a1e0e00-f70f-11e9-94fc-61400a8041ad.png)

Auf IxTheo kann ich mich problemlos anmelden. Und vertippt habe ich mich nicht.

**Comment by mtrojan-ub** [comment]
Deine Anfrage bezieht sich auf ptah, richtig?

Auf ptah gibt es keinen Benutzer der "Alessandro Aprile" heißt. Auf ub16 aber schon. Der Test- und Liveserver läuft nicht auf der selben Datenbank.

**Comment by mtrojan-ub** [comment]
Genau, bitte lege Dir dort ebenfalls ein Konto an.

**Comment by AleAprile** [comment]
Ok, es funktioniert. Dann mache ich diesen Issues zu.
