### ISSUE TITLE
Funktion "als E-Mail versenden"

### ISSUE THREAD

**Issue by AleAprile** [ubtue/tuefind#953]
Diese Funktion funktioniert einwandfrei. 

Aus dem Betreff der erhaltenen E-Mail sollte meines Erachtens aber deutlicher hervorgehen, dass ein IxTheo-Service ist.

Auf dem jetzigen IxTheo lautet der Betreff: "Datensatz Bibliothekskatalog"
Auf Ptah: "Referenz aus dem Bibliothekskatalog"

Wäre vielleicht nicht besser: "Referenz aus IxTheo"? Lässt sich das ändern?

**Comment by mtrojan-ub** [comment]
Nur mit Programmieraufwand.

Aktuell ist das ein einzelner Displaytext, der für alle Instanzen gleich ist.
https://github.com/ubtue/tuefind/blob/56789c6f0ecc242a700f5bcb80a119372c9a7b2e/languages/de.ini#L142

Man könnte es so umstellen, dass er den "Site title" aus der Konfiguration mitbenutzt.
https://github.com/ubtue/tuefind/blob/56789c6f0ecc242a700f5bcb80a119372c9a7b2e/local/tuefind/instances/ixtheo/config/vufind/config.ini#L29

Außerdem ist mir aufgefallen, dass wir den VuFind 6 URL Shortener noch nicht aktiviert haben. Das werde ich bei der Gelegenheit auch gleich nachholen.

**Comment by AleAprile** [comment]
Wenn die von Dir vorgeschlagene Umstellung nicht zu aufwändig ist und alle andere auch einverstanden sind, würde ich für eine Änderung in "IxTheo" plädieren.

**Comment by mtrojan-ub** [comment]
Habe es jetzt wie folgt geändert:
- de: "Referenzen aus %%siteTitle%%"
- en: "Library Catalog Items from %%siteTitle%%"

Falls es für die anderen Sprachen auch geändert werden soll, teilt mir bitte den entsprechenden Text mit.

**Comment by mtrojan-ub** [comment]
Das wurde jetzt auch geändert. Für die Mail mit dem einzelnen Datensatz lauten jetzt die Betreffs:
- de: "Datensatz aus %%siteTitle%%"
- en: "Record from %%siteTitle%%"

Auch hier gilt => Falls es für die anderen Sprachen auch geändert werden soll, teilt mir bitte den entsprechenden Text mit.

**Comment by AleAprile** [comment]
* de: Es kommt nun zu unterschliedlichen Ergebnissen. 
Wenn ein einziger Datensatz per E-Mail versandt wird, lautet der Betreff "Datensatz aus IxTheo". 
Wenn mehrere sind, dann "Referenzen aus IxTheo". Eine Vereinheitlichung wäre meines Erachtens gut.
"Referenzen aus IxTheo" in beiden Fällen fände ich gut.

* en: der Betreff lautet nach wie vor "Library Catalog Items from...". Keine Änderung sichtbar!
* it: bitte ändern in "Risultati ricerca IxTheo", unabhängig von Anzahl der exportierten Items
* fr: frage ich unsere wiss. Hilfskraft nach

**Comment by relhei** [comment]
Auf RelBib funktioniert die neue Anzeige auf Deutsch und Englisch inkl. Kurzlink. Vielen Dank!

**Comment by mtrojan-ub** [comment]
@AleAprile: Kannst Du uns bitte noch die passende französische Übersetzung nennen?

**Comment by AleAprile** [comment]
ja, gerne.  ich muss aber Hern Cloutier fragen. Französisch ist seine Muttersprache. Ich melde mich zurück, sobald ich eine Antwort bekomme. ich kümmere mich drum

**Comment by AleAprile** [comment]
Résultats de recherche IxTheo

**Comment by mtrojan-ub** [comment]
Ready for testing auf ptah
