### ISSUE TITLE
Datensatz exportieren - Anzeige

### ISSUE THREAD

**Issue by AleAprile** [ubtue/tuefind#956]
Lässt sich der Eintrag "Exportieren nach RIS (Citavi,Zotero etc. )" in der Dropdown-Liste nach oben bewegen?
![Screenshot_2019-10-25 Exemplare „Disce aliquid “– „Lerne etwas “ Die Gebrauchsspuren in der De imitatione Christi als Spieg](https://user-images.githubusercontent.com/41292389/67570023-ad548880-f730-11e9-8bc4-624be5ed5bcd.png)

Ich gehe stark davon aus, dass die meisten Zotero oder Citavi nutzen, sodass sinnvoller wäre, der Eintrag als erster anzuzeigen. Auf IxTheo ist es momentan so.

**Comment by mtrojan-ub** [comment]
Ist behoben, bitte nochmal ausprobieren

**Comment by AleAprile** [comment]
Es funktioniert! Danke. 
Ich schließe dann den Issue
