### ISSUE TITLE
Autocomplete Funktion fehlt auf ptah

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#96]
Im IxTheo fuktioniert die autocomplete Funktion:
![bildschirmfoto 2017-12-13 um 13 24 32](https://user-images.githubusercontent.com/14169098/33938804-11914b4e-e009-11e7-9510-c7d34a080ce9.png)

auf ptah nicht
![bildschirmfoto 2017-12-13 um 13 25 39](https://user-images.githubusercontent.com/14169098/33938827-2bf65f56-e009-11e7-8f79-0bef1adefbca.png)

Das scheint für alle Suchaspekte zu gelten:
IxTheo, Suchaspekt Verfasser:
![bildschirmfoto 2017-12-13 um 13 27 30](https://user-images.githubusercontent.com/14169098/33938893-66309f38-e009-11e7-9766-ef698f457a3c.png)

Ptah:
![bildschirmfoto 2017-12-13 um 13 28 08](https://user-images.githubusercontent.com/14169098/33938912-7df7ef40-e009-11e7-8b4e-359937514564.png)

**Comment by relhei** [comment]
Jetzt kommen zwar Titelvorschläge, aber in jedem Suchaspekt dieselben. Mindestens bei Einschränkung auf Verfasser müsste aber eine Liste mit Namensvorschlägen kommen.

RelBib:
![grafik](https://user-images.githubusercontent.com/25769591/34154184-e9636052-e4b4-11e7-9414-6a16ad3f00bb.png)

Ptah:
![grafik](https://user-images.githubusercontent.com/25769591/34154196-f5843f32-e4b4-11e7-8e11-0b20118a78f9.png)

**Comment by mtrojan-ub** [comment]
ist korrigiert, bitte auf ptah testen.

(Es haben IDs in HTML Feldern gefehlt, diese wurden nun hinzugefügt. Die IDs haben übrigens auch auf KrimDok gefehlt, dort habe ich sie bei der Gelegenheit ebenfalls hinzugefügt - aber aktuell noch nicht auf sobek.)

**Comment by relhei** [comment]
Sieht jetzt gut aus. Danke!

**Comment by thefass** [comment]
Das Problem ist noch nicht ganz behoben. Es kommen zwar autocomplete Vorschläge. 
Nicht aber Autoren-Vorschläge, wenn man den Suchaspekt auf Verfasser ändert
![bildschirmfoto 2017-12-19 um 21 21 55](https://user-images.githubusercontent.com/14169098/34177153-df7c9196-e502-11e7-939e-a16da8776c96.png)

es kommen dann noch immer Titel- und keine Verfasservorschläge

**Comment by relhei** [comment]
Auf dem RelBib-Ptah funktioniert es... 
![grafik](https://user-images.githubusercontent.com/25769591/34199889-77aee772-e56f-11e7-8e46-de4a5b9acc69.png)

**Comment by mtrojan-ub** [comment]
@thefass : auf ptah (ixtheo) kann ich das nicht reproduzieren, siehe Screenshot. Bitte nochmal testen bzw. genauer beschreiben falls es noch auftritt

![grafik](https://user-images.githubusercontent.com/26873381/34207461-d3f5a6ea-e58a-11e7-8299-4d9ff086d985.png)

**Comment by thefass** [comment]
Was für ein Weihnachtswunder hast Du da bewirkt? Es geht jetzt.

**Comment by relhei** [comment]
Ohne jetzt das Weihnachtswunder anzweifeln zu wollen: Bei mir funktionierte es gestern erst, nachdem ich den Browser geschlossen und noch mal ganz neu gestartet hatte.
