### ISSUE TITLE
Responsive Webdesign

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#964]
Hier ist noch eine kleine Anpassung notwendig:
"Zu den Favoriten" bzw. "Save to list" bitte zentrieren
![grafik](https://user-images.githubusercontent.com/25769591/67672182-b08d8580-f977-11e9-9339-b513cdadc3aa.png)

**Comment by mtrojan-ub** [comment]
Die Änderung wurde auf ptah eingespielt und kann getestet werden

**Comment by relhei** [comment]
Passt. Vielen Dank!
