### ISSUE TITLE
Alerts im Konto: Text anpassen

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#965]
Hier müsste noch der englische Text angepasst werden.

![grafik](https://user-images.githubusercontent.com/25769591/67672452-41646100-f978-11e9-973a-c0bec1565a83.png)

Vorschlag: 
"You do not have any alerts yet. Perform a search and use the "Subscribe" button to receive alerts."

**Comment by relhei** [comment]
Addendum: Diese Seite sollte auch noch eine Überschrift erhalten, analog zu "Saved items".
Vorschlag:
"My Alerts"
Diese Überschrift fehlt auch noch auf der deutschen Seite: "Meine Alerts".

**Comment by mtrojan-ub** [comment]
... und wie soll der Text auf Deutsch lauten?

**Comment by relhei** [comment]
"Meine Alerts"

**Comment by mtrojan-ub** [comment]
Die Überschrift wurde eingefügt.

Das mit dem Deutschen Text bezieht sich auf etwas anderes:
"You do not have any alerts yet. Perform a search and use the "Subscribe" button to receive alerts."
=> Was soll hier auf Deutsch stehen? Momentan steht da nur "Sie haben noch keine Daten gespeichert", aber das ist der allgemeine Text der sich nicht auf alerts bezieht.

**Comment by relhei** [comment]
deutscher Text für "Meine Alerts":
"Sie haben noch keine Alerts gespeichert. Führen Sie eine Suche durch und benutzen Sie den Button "Abonnieren" (Glockesymbol) um Alerts zu erhalten."

deutscher Text für "Meine Favoriten":
"Sie haben noch keine Favoriten gespeichert. Führen Sie eine Suche durch und benutzen Sie den Button "Zu den Favoriten" (Sternsymbol) um Titel zu speichern."

**Comment by mtrojan-ub** [comment]
... falls der deutsche Text für "Meine Favoriten" auch noch geändert werden soll, bitte zusätzlich auch eine englische Übersetzung definieren.

Außerdem weise ich darauf hin, dass aktuell im Bereich "Buchbeschaffung" bzw. "Book acquisition" ebenfalls noch ein eigener Text fehlt, sowohl DE als auch EN.

**Comment by relhei** [comment]
Text für "Saved items":
"You do not have any saved resources. Perform a search and use the "Save to List" (Sternsymbol) button to save items."

**Vorschläge** für Buchbeschaffung: Hier bitte ich noch einmal um Rückmeldung von den anderen. Der Text ist ein bisschen lang...

Buchbeschaffung:
Sie haben noch keine Buchbestellung aufgegeben. Wenn ein gesuchter Buchtitel nicht in Deutschland vorhanden ist, wird dies angezeigt. Folgen Sie den Anweisungen, damit das Buch kostenlos über die UB Tübingen beschafft wird.

Book acquisition:
You have not placed any book order. If a book title in your results is not available in Germany, it will be indicated. Follow the instructions and the title will be acquired free of charge via Tübingen University Library.

**Comment by ruschein** [comment]
Anstatt "Sternsymbol" sollte man vermutlich "Unicode Character 'BLACK STAR' (U+2605)" verwenden. Sieht dann so ★ aus.  Kann man natürlich auch größer machen.

**Comment by relhei** [comment]
Bitte - so weit noch nicht geschehen - die o.g. Texte in "Mein Konto" einpflegen und dabei die in Klammern stehenden Symbole durch das entsprechende Unicode-Zeichen ersetzen (Stern und Glocke). Mir ist aufgefallen, dass da z. T. immer noch die voreingestellten, unspezifischen Texte stehen. Vielen Dank!

**Comment by mtrojan-ub** [comment]
Habs auf ptah geändert, aber mit dem Unicode bell character könnten wir in utf8mb4 Problematiken reinlaufen (ggf. nicht im Code, aber bei manueller Administration). @ruschein @jriedl ich glaube dass wir eine Einstellung auf sämtlichen Rechnern vornehmen müssen um dem vorzubeugen, detaillierte Erklärung gibt's morgen früh bei der 8:30 VC.

**Comment by ruschein** [comment]
https://www.compart.com/en/unicode/U+1F514

[https://www.compart.com/en/unicode/images/icon/icon-compart.svg]<https://www.compart.com/en/unicode/U+1F514>

“🔔” U&#43;1F514 Bell Unicode Character<https://www.compart.com/en/unicode/U+1F514>
www.compart.com
U&#43;1F514 is the unicode hex value of the character Bell. Char U&#43;1F514, Encodings, HTML Entitys:&#128276;,&#x1F514;, UTF-8 (hex), UTF-16 (hex), UTF-32 (hex)


Wie man sehen kann braucht es 4 bytes für den Bell Character in UTF-8.


--
Dr. Johannes Ruscheinski
Universitätsbibliothek Tübingen - IT-Abteilung -
Wilhelmstr. 32, 72074 Tübingen

Tel: +49 7071 29-72820
FAX: +49 7071 29-5069
Email: ***@***.***

 The Sophisticate:  "The world isn't black and white.  No one does pure good or pure bad. It's all gray.  Therefore, no one is better than anyone else."
    The Zetet:  "Knowing only gray, you conclude that all grays are the same shade.  You mock the simplicity of the two-color view, yet you replace it with a one-color view..."
      —Marc Stiegler, David's Sling



________________________________

**Comment by mtrojan-ub** [comment]
... und mal wieder stolpern wir über einen Unterschied zwischen Ubuntu/MySQL und CentOS/MariaDB. In Ubuntu 20.04 verwenden wir mittlerweile MySQL 8, dort wurden mehrere defaults bereits auf utf8mb4 gesetzt:
https://mysqlserverteam.com/new-defaults-in-mysql-8-0/

In CentOS 8 bzw. MariaDB / mysql "Ver 15.1 Distrib 10.3.27-MariaDB" ist aber scheinbar immer noch utf8 der Standard:
https://mariadb.com/kb/en/server-system-variables/#character_set_connection

Daher fällt das Problem mal wieder nur auf den Servern, aber nicht auf den Entwicklungsmaschinen auf. Ich mache noch weitere Tests...

**Comment by relhei** [comment]
Hier bitte ich noch mal um Rückmeldung von den anderen, gfs. auch im nächsten IT-Meeting abschließen. Alle anderen texte passen jetzt. Danke!

> **Vorschläge** für Buchbeschaffung: Hier bitte ich noch einmal um Rückmeldung von den anderen. Der Text ist ein bisschen lang...
> 
> Buchbeschaffung:
> Sie haben noch keine Buchbestellung aufgegeben. Wenn ein gesuchter Buchtitel nicht in Deutschland vorhanden ist, wird dies angezeigt. Folgen Sie den Anweisungen, damit das Buch kostenlos über die UB Tübingen beschafft wird.
> 
> Book acquisition:
> You have not placed any book order. If a book title in your results is not available in Germany, it will be indicated. Follow the instructions and the title will be acquired free of charge via Tübingen University Library.

**Comment by relhei** [comment]
Addendum: 
Bei Klick auf "Delete Account" erscheint aktuell folgender Text:

"Saved searches and favorite lists will be deleted. You can still establish a new account later if you wish."

Könnten wir das "favorite" im englischen Text streichen? Es kommt ja ansonsten überhaupt nicht mehr vor...

**Comment by mtrojan-ub** [comment]
"favorite" kommt sehr oft vor! Hier einige Beispiele:

```
add_to_favorites_html = "Add <em>%%title%%</em> to favorites"
delete_account_description_html = "Saved searches and favorite lists will be deleted. You can still establish a new account later if you wish."
delete_selected_favorites = "Delete Selected Favorites"
email_selected_favorites = "Email Selected Favorites"
Export Favorites = "Export Favorites"
export_selected_favorites = "Export Selected Favorites"
fav_delete = "Delete Selected Favorites"
fav_delete_deleting = "Your favorite(s) are being deleted."
fav_delete_fail = "Sorry, an error has occurred. Your favorite(s) were not deleted."
fav_delete_missing = "Some data was missing. Your favorite(s) were not deleted."
fav_delete_success = "Your favorite(s) were deleted."
fav_delete_warn = "You are about to delete these favorites from all your lists - If you want to delete favorites from a specific list only, please select the list before clicking delete."
fav_email_fail = "Sorry, an error has occurred. Your favorite(s) were not emailed."
fav_email_missing = "Some data was missing. Your favorite(s) were not emailed."
fav_email_success = "Your favorite(s) were emailed as requested."
fav_export = "Export Favorites"
Favorites = "Saved Items"
Item removed from favorites = "Item removed from favorites"
My Favorites = "Favorites"
too_many_favorites = "This list is too large to display all at once. Try rearranging your favorites into more lists or limiting using tags."
Your Favorites = "Saved Items"

```

**Comment by mtrojan-ub** [comment]
Telefonisch mit @relhei besprochen: 
Displaytexte scheinen schon im englischen Original inkonsistent zu sein. Manchmal ist von "Saved Items" die Rede, manchmal von "favorites". Ich werde es beim nächsten Community Call am 6.7. ansprechen

**Comment by mtrojan-ub** [comment]
Pull request an VuFind gestellt, siehe: vufind-org/vufind#2020

Beim Community Call wurde bestätigt, dass die Texte konsistent sein sollen. Außerdem wurde entschieden dass "Saved Items" die bevorzugte Benennung ist, da es auf eine größere Anzahl von Fällen zutrifft als "Favorites".

**Comment by mtrojan-ub** [comment]
Die Änderungen wurden für VuFind 8 übernommen. Daher werden sie bei uns einfließen sobald wir auf 8 upgraden. Ich kennzeichne den Issue mit "for future vufind version".

**Comment by mtrojan-ub** [comment]
Die Testserver sind nun auf VuFind 8 => ready for testing!

**Comment by relhei** [comment]
Stichprobe: Sieht jetzt gut aus. Danke!
