### ISSUE TITLE
Saved items im Konto: Text (EN) anpassen

### ISSUE THREAD

**Issue by relhei** [ubtue/tuefind#966]
Der englische Text müsste noch angepasst werden.
![grafik](https://user-images.githubusercontent.com/25769591/67673063-77561500-f979-11e9-9221-00071426735c.png)
Vorschlag:
"You do not have any saved resources. Perform a search and use the "Save to list" button to save items.

**Comment by mtrojan-ub** [comment]
Das kommt schon inkonsistent von vufind-org, siehe:
https://github.com/vufind-org/vufind/blob/2683f4fe5bec2cb65e4aed3d928a674e7b5983dd/languages/en.ini

**Comment by mtrojan-ub** [comment]
siehe vufind-org/vufind#1483

**Comment by mtrojan-ub** [comment]
Da wir aktuell auf 6.0.1 sind und keine 6.0.2 angekündigt wurde, gehe ich davon aus dass die Änderung in 6.1 kommt.

**Comment by relhei** [comment]
Das passt jetzt. Super - vielen Dank!
