### ISSUE TITLE
Indexierung Feld 787 $t

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#970]
Titel von "enthaltenen Werken" in Feld 787 $t sind nur im Freitext, nicht aber als Titel recherchierbar. 
Bitte 787 $t auch als Titel indexieren.

Bsp.: 
https://ixtheo.de/Record/1567853404#details

**Comment by mtrojan-ub** [comment]
Den o.g. Datensatz gibt es scheinbar nicht mehr. 787t wird jetzt aber mit indexiert, Beispiel:
https://ptah.ub.uni-tuebingen.de/Record/022946225

**Comment by IxTheoKm** [comment]
Funktioniert, danke
