### ISSUE TITLE
Suche über Schlagwortketten funktioniert nicht

### ISSUE THREAD

**Issue by k-decker** [ubtue/tuefind#984]
Die Suche, die ausgelöst wird, wenn man in der Einzeltitelanzeige auf ein Schlagwort in einer Schlagwortkette klickt, funktioniert in KrimDok nicht. Anstatt dem angeklickten Schlagwort oder nach mehreren Slagwörtern aus der Schlagwortkette wird nach einem zusammengesetzten Schlagwort gesucht, das nicht existiert.

Im IxTheo funktioniert es. Wäre schön, wenn das angeglichen wird.

![Screenshot_2019-11-05 Beschreibung Italian mafias today](https://user-images.githubusercontent.com/44361973/68210351-9ede5a80-ffd5-11e9-8948-c9aa9b99e856.png)
![Screenshot_2019-11-05 Suchergebnisse - Organized crime Political aspects Italy ](https://user-images.githubusercontent.com/44361973/68210363-a4d43b80-ffd5-11e9-9509-521c916c26d1.png)

**Comment by jriedl** [comment]
Auf sobek behoben.

**Comment by k-decker** [comment]
Sieht gut aus!
