### ISSUE TITLE
[System: KrimDok, caused by VuFind upgrade]: Responsive Webdesign - Dropdown "Filter anzeigen"

### ISSUE THREAD

**Issue by k-decker** [ubtue/tuefind#985]
Dropdownmenü "Filter anzeigen" funktioniert nicht. Wenn man drauf klickt, tut sich nichts. Außerdem taucht es auch in der Einzeltitelanzeige auf, wo es eigentlich nichts verloren hat.

![Screenshot_2019-11-05 Suchergebnisse](https://user-images.githubusercontent.com/44361973/68214806-6b53fe00-ffde-11e9-9e41-01ea62a1b9d4.png)
![Screenshot_2019-11-05 Beschreibung Dubbel de klos](https://user-images.githubusercontent.com/44361973/68214818-7149df00-ffde-11e9-8ee7-185b0a3f44a0.png)

**Comment by jriedl** [comment]
Es wurde entschieden, beim Update auf VuFind 6 die ausgewählten Filternicht oben noch einmal gesondert anzuzeigen, sondern sich hier an der bisherigen Strategie von VuFind 5 zu orientieren. Deshalb macht "Filter anzeigen" auch im Mobile-Mode keinen Sinn mehr. Die Anzeige wurde deshalb entfernt.

**Comment by k-decker** [comment]
Sieht gut aus.
