### ISSUE TITLE
Alerting: Untertitel mit ausgeben

### ISSUE THREAD

**Issue by thefass** [ubtue/tuefind#986]
Im Alerting wird momentan nur der Haupttitel in der Alerting-Mail ausgegeben.
Oft steckt jedoch erst im Untertitel der eigentliche Sachverhalt.

Beispiel: letzte Ausgabe der Herderkorrespondenz (73, 2019, 10)
Das kam in der Alerting-Mail:
![Bildschirmfoto 2019-11-06 um 09 52 52](https://user-images.githubusercontent.com/14169098/68283177-5f6a4980-007b-11ea-829d-e098dc6e29ce.png)
Das sind die vollständigen Titel:
![Bildschirmfoto 2019-11-06 um 09 52 29](https://user-images.githubusercontent.com/14169098/68283236-7ad55480-007b-11ea-8047-2e47ef0214ef.png)

Deswegen: bitte auch die Untertitel in der Alertingmail ausgeben. Trennzeichen zwischen Haupt- und Untertitel soll wie im IxTheo der Doppelpunkt sein

**Comment by ruschein** [comment]
@thefass Hallo Martin, die Untertitel sollten ab morgen in Emails von Path erscheinen.  Bitte testen und, falls korrekt, das Issue schließen.

**Comment by IxTheoKm** [comment]
Ich habe heute E-Mails mit Alerts aus IxTheo und aus PTAH bekommen. 
Untertitel werden bei beiden angezeigt, daher schließe ich.
