### ISSUE TITLE
Interviewte und Interviewer fehlen in der Anzeige als erste Verfasser

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#993]
Laut Tabelle in http://swbtools.bsz-bw.de/cgi-bin/k10plushelp.pl?cmd=kat&val=3000&katalog=Standard#$B können auch $BInterviewerIn$4ivr und $BInterviewteR$4ive in PICA-Feld 3000 = MARC 100 stehen.

Bitte alle in der Tabelle aufgeführten Beziehungskennzeichnungen für Feld 100 zulassen und die Personen damit - analog zu ersten Verfassern - anzeigen.

Die Interwier und Interviewten fehlen in der Kurz- und Vollanzeige (auch auf Ptah).
Bsp.:

https://ixtheo.de/Search/Results?lookfor=id%3A1681768526&type=AllFields&limit=20&botprotect=
https://ixtheo.de/Record/1681768526#details

https://ixtheo.de/Search/Results?lookfor=id%3A1681578395&type=AllFields&limit=20&botprotect=
https://ixtheo.de/Record/1681578395#details

https://ixtheo.de/Search/Results?lookfor=id%3A1666281379&type=AllFields&limit=20&botprotect=
https://ixtheo.de/Record/1666281379#details

**Comment by mtrojan-ub** [comment]
Habe auch die Schreibweise "InterviewteR" der Kategorie "ive" hinzugefügt, damit es richtig erkannt wird.

Die Änderung kann nach dem nächsten Import (also morgen Vormittag) auf ptah getestet werden.

**Comment by IxTheoKm** [comment]
Jetzt in Ordnung, vielen Dank!
