### ISSUE TITLE
Alerting: Band, Jahrgang, Heft mit ausgeben

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/tuefind#994]
Beschluss aus der Abteilungsbesprechung, da das Alerting auch zur Meldung für die Sacherschließer genutzt werden soll:
bitte beim Alerting die Band-, Jahrgangs- und Heftangaben aus 936 uw$d...$j...$e... mit ausgeben.

Der Titel der Zeitschrift soll nicht bei jedem einzelnen Aufsatz stehen, sondern nur einmal - ggf. für mehrere Hefte.

Die Band- Jahrgangs- und Heftzählung eines Heftes soll jeweils auch nur einmal - ggf. für mehrere Aufsätze aufgeführt werden.

Etwa in der folgenden Form (s.a. https://github.com/ubtue/tuefind/issues/986):

![Herder](https://user-images.githubusercontent.com/17004223/69346511-3220bc80-0c73-11ea-8eda-2ea2379c1de7.JPG)

**Comment by mtrojan-ub** [comment]
Die Änderung dazu ist bereits in Vorbereitung. Da wir jedoch am Donnerstag auf VuFind 6 gehen möchten, wollen wir den Live-Branch bis dahin möglichst wenig verändern und halten die Änderung noch zurück.

Ein ähnlicher Issue (#986) sollte bereits behoben sein, es muss dann auch getestet werden ob mit der Änderung die Untertitel immer noch korrekt ausgegeben werden, falls vorhanden.

**Comment by IxTheoKm** [comment]
Ich habe heute eine E-Mail mit einem Alert aus PTAH bekommen, in der diese Änderung wirksam ist. Das sieht - einschließlich Untertitel - sehr gut aus, aber die Anzeige der Hefte ist noch nicht korrekt: Leerzeichen Klammern und Komma fehlen noch.
Also statt **29 (2017), 1** steht dort **2920171**, statt **30 (2018), 2** steht dort **3020182**.

Die 16 Beiträge der Online-Ausgabe von 30 (2018), 2 wurden am 02.12.2019 neu erfasst.

Der Beitrag PPN 1639768300 der Druckausgabe von 29 (2017), 1 wurde schon am **07.11.2017** neu erfasst und am **02.12.2019** nur korrigiert. Ist es korrekt, dass er trotzdem im Alert erscheint?

![Alert](https://user-images.githubusercontent.com/17004223/70216618-2ee00300-1740-11ea-9141-0fcd103da8a6.JPG)

**Comment by ruschein** [comment]
"Der Beitrag PPN 1639768300 der Druckausgabe von 29 (2017), 1 wurde schon am 07.11.2017 neu erfasst und am 02.12.2019 nur korrigiert. Ist es korrekt, dass er trotzdem im Alert erscheint?"

Das kann ich nicht entscheiden.  @thefass Was meinst Du Martin?

**Comment by mtrojan-ub** [comment]
Da wir auf ptah derzeit öfters testen haben wir einen Teil der Informationen über bereits verschickte Alerts wieder gelöscht, sonst hätten wir nicht in dieser Häufigkeit testen können. Es ist nicht auszuschließen dass dieses Verhalten von der Vorgehensweise beim Testing kommt.

**Comment by ruschein** [comment]
Ready for testing auf Ptah!

**Comment by IxTheoKm** [comment]
Sieht jetzt perfekt aus. Vielen Dank!

**Comment by IxTheoKm** [comment]
... oh, doch nicht so ganz:
wenn Datensätze für mehrere Zeitschriften aufgeführt werden, rücken die Absätze für die Zeitschriften, Hefte und Aufsätze jeweils eine Ebene nach hinten (ich habe in der Datei die gemeldeten Aufsätze ein wenig zusammengekürzt, damit alles auf eine Seite passt):

[Alert.pdf](https://github.com/ubtue/tuefind/files/3938407/Alert.pdf)

**Comment by ruschein** [comment]
Auf Ptah.

**Comment by IxTheoKm** [comment]
Kann ich erst prüfen, wenn an einem Tag gleichzeitig _mehrere_ Zeitschriften mit jeweils _mehreren_ Heften erfasst wurden. Wenn der Fall vorliegt, prüfe ich.

**Comment by IxTheoKm** [comment]
Anzeige jetzt vollständig und perfekt, vielen Dank.
